var annotated_dup =
[
    [ "kcenon", "namespacekcenon.html", [
      [ "network", "namespacekcenon_1_1network.html", [
        [ "concepts", "namespacekcenon_1_1network_1_1concepts.html", [
          [ "datagram_receive_guard", "classkcenon_1_1network_1_1concepts_1_1datagram__receive__guard.html", "classkcenon_1_1network_1_1concepts_1_1datagram__receive__guard" ],
          [ "socket_read_guard", "classkcenon_1_1network_1_1concepts_1_1socket__read__guard.html", "classkcenon_1_1network_1_1concepts_1_1socket__read__guard" ]
        ] ],
        [ "config", "namespacekcenon_1_1network_1_1config.html", [
          [ "logger_config", "structkcenon_1_1network_1_1config_1_1logger__config.html", "structkcenon_1_1network_1_1config_1_1logger__config" ],
          [ "monitoring_config", "structkcenon_1_1network_1_1config_1_1monitoring__config.html", "structkcenon_1_1network_1_1config_1_1monitoring__config" ],
          [ "network_config", "structkcenon_1_1network_1_1config_1_1network__config.html", "structkcenon_1_1network_1_1config_1_1network__config" ],
          [ "network_system_config", "structkcenon_1_1network_1_1config_1_1network__system__config.html", "structkcenon_1_1network_1_1config_1_1network__system__config" ],
          [ "thread_pool_config", "structkcenon_1_1network_1_1config_1_1thread__pool__config.html", "structkcenon_1_1network_1_1config_1_1thread__pool__config" ]
        ] ],
        [ "core", "namespacekcenon_1_1network_1_1core.html", [
          [ "connection_pool", "classkcenon_1_1network_1_1core_1_1connection__pool.html", "classkcenon_1_1network_1_1core_1_1connection__pool" ],
          [ "http_client", "classkcenon_1_1network_1_1core_1_1http__client.html", "classkcenon_1_1network_1_1core_1_1http__client" ],
          [ "http_request_buffer", "structkcenon_1_1network_1_1core_1_1http__request__buffer.html", "structkcenon_1_1network_1_1core_1_1http__request__buffer" ],
          [ "http_request_context", "structkcenon_1_1network_1_1core_1_1http__request__context.html", "structkcenon_1_1network_1_1core_1_1http__request__context" ],
          [ "http_route", "structkcenon_1_1network_1_1core_1_1http__route.html", "structkcenon_1_1network_1_1core_1_1http__route" ],
          [ "http_server", "classkcenon_1_1network_1_1core_1_1http__server.html", "classkcenon_1_1network_1_1core_1_1http__server" ],
          [ "http_url", "structkcenon_1_1network_1_1core_1_1http__url.html", "structkcenon_1_1network_1_1core_1_1http__url" ],
          [ "messaging_client", "classkcenon_1_1network_1_1core_1_1messaging__client.html", "classkcenon_1_1network_1_1core_1_1messaging__client" ],
          [ "messaging_quic_client", "classkcenon_1_1network_1_1core_1_1messaging__quic__client.html", "classkcenon_1_1network_1_1core_1_1messaging__quic__client" ],
          [ "messaging_quic_server", "classkcenon_1_1network_1_1core_1_1messaging__quic__server.html", "classkcenon_1_1network_1_1core_1_1messaging__quic__server" ],
          [ "messaging_server", "classkcenon_1_1network_1_1core_1_1messaging__server.html", "classkcenon_1_1network_1_1core_1_1messaging__server" ],
          [ "messaging_session", "classkcenon_1_1network_1_1core_1_1messaging__session.html", "classkcenon_1_1network_1_1core_1_1messaging__session" ],
          [ "messaging_udp_client", "classkcenon_1_1network_1_1core_1_1messaging__udp__client.html", "classkcenon_1_1network_1_1core_1_1messaging__udp__client" ],
          [ "messaging_udp_server", "classkcenon_1_1network_1_1core_1_1messaging__udp__server.html", "classkcenon_1_1network_1_1core_1_1messaging__udp__server" ],
          [ "messaging_ws_client", "classkcenon_1_1network_1_1core_1_1messaging__ws__client.html", "classkcenon_1_1network_1_1core_1_1messaging__ws__client" ],
          [ "messaging_ws_server", "classkcenon_1_1network_1_1core_1_1messaging__ws__server.html", "classkcenon_1_1network_1_1core_1_1messaging__ws__server" ],
          [ "network_context", "classkcenon_1_1network_1_1core_1_1network__context.html", "classkcenon_1_1network_1_1core_1_1network__context" ],
          [ "packet_header", "structkcenon_1_1network_1_1core_1_1packet__header.html", "structkcenon_1_1network_1_1core_1_1packet__header" ],
          [ "packet_info", "structkcenon_1_1network_1_1core_1_1packet__info.html", "structkcenon_1_1network_1_1core_1_1packet__info" ],
          [ "quic_client_config", "structkcenon_1_1network_1_1core_1_1quic__client__config.html", "structkcenon_1_1network_1_1core_1_1quic__client__config" ],
          [ "quic_connection_stats", "structkcenon_1_1network_1_1core_1_1quic__connection__stats.html", "structkcenon_1_1network_1_1core_1_1quic__connection__stats" ],
          [ "quic_server_config", "structkcenon_1_1network_1_1core_1_1quic__server__config.html", "structkcenon_1_1network_1_1core_1_1quic__server__config" ],
          [ "reliable_udp_client", "classkcenon_1_1network_1_1core_1_1reliable__udp__client.html", "classkcenon_1_1network_1_1core_1_1reliable__udp__client" ],
          [ "reliable_udp_stats", "structkcenon_1_1network_1_1core_1_1reliable__udp__stats.html", "structkcenon_1_1network_1_1core_1_1reliable__udp__stats" ],
          [ "secure_messaging_client", "classkcenon_1_1network_1_1core_1_1secure__messaging__client.html", "classkcenon_1_1network_1_1core_1_1secure__messaging__client" ],
          [ "secure_messaging_server", "classkcenon_1_1network_1_1core_1_1secure__messaging__server.html", "classkcenon_1_1network_1_1core_1_1secure__messaging__server" ],
          [ "secure_messaging_udp_client", "classkcenon_1_1network_1_1core_1_1secure__messaging__udp__client.html", "classkcenon_1_1network_1_1core_1_1secure__messaging__udp__client" ],
          [ "secure_messaging_udp_server", "classkcenon_1_1network_1_1core_1_1secure__messaging__udp__server.html", "classkcenon_1_1network_1_1core_1_1secure__messaging__udp__server" ],
          [ "session_concept", "classkcenon_1_1network_1_1core_1_1session__concept.html", "classkcenon_1_1network_1_1core_1_1session__concept" ],
          [ "session_config", "structkcenon_1_1network_1_1core_1_1session__config.html", "structkcenon_1_1network_1_1core_1_1session__config" ],
          [ "session_handle", "classkcenon_1_1network_1_1core_1_1session__handle.html", "classkcenon_1_1network_1_1core_1_1session__handle" ],
          [ "session_info", "structkcenon_1_1network_1_1core_1_1session__info.html", "structkcenon_1_1network_1_1core_1_1session__info" ],
          [ "session_info_base", "structkcenon_1_1network_1_1core_1_1session__info__base.html", null ],
          [ "session_info_base< SessionType, false >", "structkcenon_1_1network_1_1core_1_1session__info__base_3_01SessionType_00_01false_01_4.html", "structkcenon_1_1network_1_1core_1_1session__info__base_3_01SessionType_00_01false_01_4" ],
          [ "session_info_base< SessionType, true >", "structkcenon_1_1network_1_1core_1_1session__info__base_3_01SessionType_00_01true_01_4.html", "structkcenon_1_1network_1_1core_1_1session__info__base_3_01SessionType_00_01true_01_4" ],
          [ "session_manager", "classkcenon_1_1network_1_1core_1_1session__manager.html", "classkcenon_1_1network_1_1core_1_1session__manager" ],
          [ "session_manager_base", "classkcenon_1_1network_1_1core_1_1session__manager__base.html", "classkcenon_1_1network_1_1core_1_1session__manager__base" ],
          [ "session_model", "classkcenon_1_1network_1_1core_1_1session__model.html", "classkcenon_1_1network_1_1core_1_1session__model" ],
          [ "session_traits", "structkcenon_1_1network_1_1core_1_1session__traits.html", "structkcenon_1_1network_1_1core_1_1session__traits" ],
          [ "session_traits< session::messaging_session >", "structkcenon_1_1network_1_1core_1_1session__traits_3_01session_1_1messaging__session_01_4.html", "structkcenon_1_1network_1_1core_1_1session__traits_3_01session_1_1messaging__session_01_4" ],
          [ "session_traits< ws_connection >", "structkcenon_1_1network_1_1core_1_1session__traits_3_01ws__connection_01_4.html", "structkcenon_1_1network_1_1core_1_1session__traits_3_01ws__connection_01_4" ],
          [ "ssl_config", "structkcenon_1_1network_1_1core_1_1ssl__config.html", "structkcenon_1_1network_1_1core_1_1ssl__config" ],
          [ "unified_messaging_client", "classkcenon_1_1network_1_1core_1_1unified__messaging__client.html", "classkcenon_1_1network_1_1core_1_1unified__messaging__client" ],
          [ "unified_messaging_server", "classkcenon_1_1network_1_1core_1_1unified__messaging__server.html", "classkcenon_1_1network_1_1core_1_1unified__messaging__server" ],
          [ "unified_session_config", "structkcenon_1_1network_1_1core_1_1unified__session__config.html", "structkcenon_1_1network_1_1core_1_1unified__session__config" ],
          [ "unified_session_manager", "classkcenon_1_1network_1_1core_1_1unified__session__manager.html", "classkcenon_1_1network_1_1core_1_1unified__session__manager" ],
          [ "unified_udp_messaging_client", "classkcenon_1_1network_1_1core_1_1unified__udp__messaging__client.html", "classkcenon_1_1network_1_1core_1_1unified__udp__messaging__client" ],
          [ "unified_udp_messaging_server", "classkcenon_1_1network_1_1core_1_1unified__udp__messaging__server.html", "classkcenon_1_1network_1_1core_1_1unified__udp__messaging__server" ],
          [ "ws_client_config", "structkcenon_1_1network_1_1core_1_1ws__client__config.html", "structkcenon_1_1network_1_1core_1_1ws__client__config" ],
          [ "ws_connection", "classkcenon_1_1network_1_1core_1_1ws__connection.html", "classkcenon_1_1network_1_1core_1_1ws__connection" ],
          [ "ws_connection_impl", "classkcenon_1_1network_1_1core_1_1ws__connection__impl.html", "classkcenon_1_1network_1_1core_1_1ws__connection__impl" ],
          [ "ws_server_config", "structkcenon_1_1network_1_1core_1_1ws__server__config.html", "structkcenon_1_1network_1_1core_1_1ws__server__config" ],
          [ "ws_session_manager", "classkcenon_1_1network_1_1core_1_1ws__session__manager.html", "classkcenon_1_1network_1_1core_1_1ws__session__manager" ]
        ] ],
        [ "events", "namespacekcenon_1_1network_1_1events.html", [
          [ "network_connection_event", "structkcenon_1_1network_1_1events_1_1network__connection__event.html", "structkcenon_1_1network_1_1events_1_1network__connection__event" ],
          [ "network_health_event", "structkcenon_1_1network_1_1events_1_1network__health__event.html", "structkcenon_1_1network_1_1events_1_1network__health__event" ],
          [ "network_latency_event", "structkcenon_1_1network_1_1events_1_1network__latency__event.html", "structkcenon_1_1network_1_1events_1_1network__latency__event" ],
          [ "network_metric_event", "structkcenon_1_1network_1_1events_1_1network__metric__event.html", "structkcenon_1_1network_1_1events_1_1network__metric__event" ],
          [ "network_transfer_event", "structkcenon_1_1network_1_1events_1_1network__transfer__event.html", "structkcenon_1_1network_1_1events_1_1network__transfer__event" ]
        ] ],
        [ "facade", "namespacekcenon_1_1network_1_1facade.html", [
          [ "http_facade", "classkcenon_1_1network_1_1facade_1_1http__facade.html", "classkcenon_1_1network_1_1facade_1_1http__facade" ],
          [ "quic_facade", "classkcenon_1_1network_1_1facade_1_1quic__facade.html", "classkcenon_1_1network_1_1facade_1_1quic__facade" ],
          [ "tcp_facade", "classkcenon_1_1network_1_1facade_1_1tcp__facade.html", "classkcenon_1_1network_1_1facade_1_1tcp__facade" ],
          [ "udp_facade", "classkcenon_1_1network_1_1facade_1_1udp__facade.html", "classkcenon_1_1network_1_1facade_1_1udp__facade" ],
          [ "websocket_facade", "classkcenon_1_1network_1_1facade_1_1websocket__facade.html", "classkcenon_1_1network_1_1facade_1_1websocket__facade" ]
        ] ],
        [ "integration", "namespacekcenon_1_1network_1_1integration.html", [
          [ "detail", "namespacekcenon_1_1network_1_1integration_1_1detail.html", [
            [ "static_destruction_guard", "classkcenon_1_1network_1_1integration_1_1detail_1_1static__destruction__guard.html", "classkcenon_1_1network_1_1integration_1_1detail_1_1static__destruction__guard" ]
          ] ],
          [ "basic_container", "classkcenon_1_1network_1_1integration_1_1basic__container.html", "classkcenon_1_1network_1_1integration_1_1basic__container" ],
          [ "basic_logger", "classkcenon_1_1network_1_1integration_1_1basic__logger.html", "classkcenon_1_1network_1_1integration_1_1basic__logger" ],
          [ "basic_monitoring", "classkcenon_1_1network_1_1integration_1_1basic__monitoring.html", "classkcenon_1_1network_1_1integration_1_1basic__monitoring" ],
          [ "basic_thread_pool", "classkcenon_1_1network_1_1integration_1_1basic__thread__pool.html", "classkcenon_1_1network_1_1integration_1_1basic__thread__pool" ],
          [ "BridgeConfig", "structkcenon_1_1network_1_1integration_1_1BridgeConfig.html", "structkcenon_1_1network_1_1integration_1_1BridgeConfig" ],
          [ "BridgeMetrics", "structkcenon_1_1network_1_1integration_1_1BridgeMetrics.html", "structkcenon_1_1network_1_1integration_1_1BridgeMetrics" ],
          [ "common_to_network_thread_adapter_unavailable", "structkcenon_1_1network_1_1integration_1_1common__to__network__thread__adapter__unavailable.html", "structkcenon_1_1network_1_1integration_1_1common__to__network__thread__adapter__unavailable" ],
          [ "container_interface", "classkcenon_1_1network_1_1integration_1_1container__interface.html", "classkcenon_1_1network_1_1integration_1_1container__interface" ],
          [ "container_manager", "classkcenon_1_1network_1_1integration_1_1container__manager.html", "classkcenon_1_1network_1_1integration_1_1container__manager" ],
          [ "function_job_unavailable", "structkcenon_1_1network_1_1integration_1_1function__job__unavailable.html", "structkcenon_1_1network_1_1integration_1_1function__job__unavailable" ],
          [ "INetworkBridge", "classkcenon_1_1network_1_1integration_1_1INetworkBridge.html", "classkcenon_1_1network_1_1integration_1_1INetworkBridge" ],
          [ "io_context_thread_manager", "classkcenon_1_1network_1_1integration_1_1io__context__thread__manager.html", "classkcenon_1_1network_1_1integration_1_1io__context__thread__manager" ],
          [ "logger_integration_manager", "classkcenon_1_1network_1_1integration_1_1logger__integration__manager.html", "classkcenon_1_1network_1_1integration_1_1logger__integration__manager" ],
          [ "logger_interface", "classkcenon_1_1network_1_1integration_1_1logger__interface.html", "classkcenon_1_1network_1_1integration_1_1logger__interface" ],
          [ "messaging_bridge", "classkcenon_1_1network_1_1integration_1_1messaging__bridge.html", "classkcenon_1_1network_1_1integration_1_1messaging__bridge" ],
          [ "monitoring_integration_manager", "classkcenon_1_1network_1_1integration_1_1monitoring__integration__manager.html", "classkcenon_1_1network_1_1integration_1_1monitoring__integration__manager" ],
          [ "monitoring_interface", "classkcenon_1_1network_1_1integration_1_1monitoring__interface.html", "classkcenon_1_1network_1_1integration_1_1monitoring__interface" ],
          [ "network_to_common_thread_adapter_unavailable", "structkcenon_1_1network_1_1integration_1_1network__to__common__thread__adapter__unavailable.html", "structkcenon_1_1network_1_1integration_1_1network__to__common__thread__adapter__unavailable" ],
          [ "NetworkSystemBridge", "classkcenon_1_1network_1_1integration_1_1NetworkSystemBridge.html", "classkcenon_1_1network_1_1integration_1_1NetworkSystemBridge" ],
          [ "NetworkSystemBridgeConfig", "structkcenon_1_1network_1_1integration_1_1NetworkSystemBridgeConfig.html", "structkcenon_1_1network_1_1integration_1_1NetworkSystemBridgeConfig" ],
          [ "ObservabilityBridge", "classkcenon_1_1network_1_1integration_1_1ObservabilityBridge.html", "classkcenon_1_1network_1_1integration_1_1ObservabilityBridge" ],
          [ "thread_integration_manager", "classkcenon_1_1network_1_1integration_1_1thread__integration__manager.html", "classkcenon_1_1network_1_1integration_1_1thread__integration__manager" ],
          [ "thread_pool_interface", "classkcenon_1_1network_1_1integration_1_1thread__pool__interface.html", "classkcenon_1_1network_1_1integration_1_1thread__pool__interface" ],
          [ "thread_system_pool_adapter_unavailable", "structkcenon_1_1network_1_1integration_1_1thread__system__pool__adapter__unavailable.html", "structkcenon_1_1network_1_1integration_1_1thread__system__pool__adapter__unavailable" ],
          [ "ThreadPoolBridge", "classkcenon_1_1network_1_1integration_1_1ThreadPoolBridge.html", "classkcenon_1_1network_1_1integration_1_1ThreadPoolBridge" ]
        ] ],
        [ "interfaces", "namespacekcenon_1_1network_1_1interfaces.html", [
          [ "callback_adapter", "classkcenon_1_1network_1_1interfaces_1_1callback__adapter.html", "classkcenon_1_1network_1_1interfaces_1_1callback__adapter" ],
          [ "connection_observer", "classkcenon_1_1network_1_1interfaces_1_1connection__observer.html", "classkcenon_1_1network_1_1interfaces_1_1connection__observer" ],
          [ "i_client", "classkcenon_1_1network_1_1interfaces_1_1i__client.html", "classkcenon_1_1network_1_1interfaces_1_1i__client" ],
          [ "i_network_component", "classkcenon_1_1network_1_1interfaces_1_1i__network__component.html", "classkcenon_1_1network_1_1interfaces_1_1i__network__component" ],
          [ "i_protocol_client", "classkcenon_1_1network_1_1interfaces_1_1i__protocol__client.html", "classkcenon_1_1network_1_1interfaces_1_1i__protocol__client" ],
          [ "i_protocol_server", "classkcenon_1_1network_1_1interfaces_1_1i__protocol__server.html", "classkcenon_1_1network_1_1interfaces_1_1i__protocol__server" ],
          [ "i_quic_client", "classkcenon_1_1network_1_1interfaces_1_1i__quic__client.html", "classkcenon_1_1network_1_1interfaces_1_1i__quic__client" ],
          [ "i_quic_server", "classkcenon_1_1network_1_1interfaces_1_1i__quic__server.html", "classkcenon_1_1network_1_1interfaces_1_1i__quic__server" ],
          [ "i_quic_session", "classkcenon_1_1network_1_1interfaces_1_1i__quic__session.html", "classkcenon_1_1network_1_1interfaces_1_1i__quic__session" ],
          [ "i_server", "classkcenon_1_1network_1_1interfaces_1_1i__server.html", "classkcenon_1_1network_1_1interfaces_1_1i__server" ],
          [ "i_session", "classkcenon_1_1network_1_1interfaces_1_1i__session.html", "classkcenon_1_1network_1_1interfaces_1_1i__session" ],
          [ "i_udp_client", "classkcenon_1_1network_1_1interfaces_1_1i__udp__client.html", "classkcenon_1_1network_1_1interfaces_1_1i__udp__client" ],
          [ "i_udp_server", "classkcenon_1_1network_1_1interfaces_1_1i__udp__server.html", "classkcenon_1_1network_1_1interfaces_1_1i__udp__server" ],
          [ "i_websocket_client", "classkcenon_1_1network_1_1interfaces_1_1i__websocket__client.html", "classkcenon_1_1network_1_1interfaces_1_1i__websocket__client" ],
          [ "i_websocket_server", "classkcenon_1_1network_1_1interfaces_1_1i__websocket__server.html", "classkcenon_1_1network_1_1interfaces_1_1i__websocket__server" ],
          [ "i_websocket_session", "classkcenon_1_1network_1_1interfaces_1_1i__websocket__session.html", "classkcenon_1_1network_1_1interfaces_1_1i__websocket__session" ],
          [ "null_connection_observer", "classkcenon_1_1network_1_1interfaces_1_1null__connection__observer.html", "classkcenon_1_1network_1_1interfaces_1_1null__connection__observer" ]
        ] ],
        [ "internal", "namespacekcenon_1_1network_1_1internal.html", [
          [ "adapters", "namespacekcenon_1_1network_1_1internal_1_1adapters.html", [
            [ "http_client_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1http__client__adapter.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1http__client__adapter" ],
            [ "http_request_session", "classkcenon_1_1network_1_1internal_1_1adapters_1_1http__request__session.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1http__request__session" ],
            [ "http_server_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1http__server__adapter.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1http__server__adapter" ],
            [ "quic_client_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1quic__client__adapter.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1quic__client__adapter" ],
            [ "quic_server_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1quic__server__adapter.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1quic__server__adapter" ],
            [ "quic_session_wrapper", "classkcenon_1_1network_1_1internal_1_1adapters_1_1quic__session__wrapper.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1quic__session__wrapper" ],
            [ "tcp_server_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1tcp__server__adapter.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1tcp__server__adapter" ],
            [ "udp_client_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1udp__client__adapter.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1udp__client__adapter" ],
            [ "udp_endpoint_session", "classkcenon_1_1network_1_1internal_1_1adapters_1_1udp__endpoint__session.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1udp__endpoint__session" ],
            [ "udp_server_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1udp__server__adapter.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1udp__server__adapter" ],
            [ "ws_client_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1ws__client__adapter.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1ws__client__adapter" ],
            [ "ws_server_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1ws__server__adapter.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1ws__server__adapter" ],
            [ "ws_session_wrapper", "classkcenon_1_1network_1_1internal_1_1adapters_1_1ws__session__wrapper.html", "classkcenon_1_1network_1_1internal_1_1adapters_1_1ws__session__wrapper" ]
          ] ],
          [ "cookie", "structkcenon_1_1network_1_1internal_1_1cookie.html", "structkcenon_1_1network_1_1internal_1_1cookie" ],
          [ "dtls_socket", "classkcenon_1_1network_1_1internal_1_1dtls__socket.html", "classkcenon_1_1network_1_1internal_1_1dtls__socket" ],
          [ "http_error", "structkcenon_1_1network_1_1internal_1_1http__error.html", "structkcenon_1_1network_1_1internal_1_1http__error" ],
          [ "http_error_response", "classkcenon_1_1network_1_1internal_1_1http__error__response.html", "classkcenon_1_1network_1_1internal_1_1http__error__response" ],
          [ "http_parser", "classkcenon_1_1network_1_1internal_1_1http__parser.html", "classkcenon_1_1network_1_1internal_1_1http__parser" ],
          [ "http_request", "structkcenon_1_1network_1_1internal_1_1http__request.html", "structkcenon_1_1network_1_1internal_1_1http__request" ],
          [ "http_response", "structkcenon_1_1network_1_1internal_1_1http__response.html", "structkcenon_1_1network_1_1internal_1_1http__response" ],
          [ "multipart_file", "structkcenon_1_1network_1_1internal_1_1multipart__file.html", "structkcenon_1_1network_1_1internal_1_1multipart__file" ],
          [ "parse_error", "structkcenon_1_1network_1_1internal_1_1parse__error.html", "structkcenon_1_1network_1_1internal_1_1parse__error" ],
          [ "quic_socket", "classkcenon_1_1network_1_1internal_1_1quic__socket.html", "classkcenon_1_1network_1_1internal_1_1quic__socket" ],
          [ "secure_tcp_socket", "classkcenon_1_1network_1_1internal_1_1secure__tcp__socket.html", "classkcenon_1_1network_1_1internal_1_1secure__tcp__socket" ],
          [ "socket_config", "structkcenon_1_1network_1_1internal_1_1socket__config.html", "structkcenon_1_1network_1_1internal_1_1socket__config" ],
          [ "socket_metrics", "structkcenon_1_1network_1_1internal_1_1socket__metrics.html", "structkcenon_1_1network_1_1internal_1_1socket__metrics" ],
          [ "tcp_socket", "classkcenon_1_1network_1_1internal_1_1tcp__socket.html", "classkcenon_1_1network_1_1internal_1_1tcp__socket" ],
          [ "tls_config", "structkcenon_1_1network_1_1internal_1_1tls__config.html", "structkcenon_1_1network_1_1internal_1_1tls__config" ],
          [ "udp_socket", "classkcenon_1_1network_1_1internal_1_1udp__socket.html", "classkcenon_1_1network_1_1internal_1_1udp__socket" ],
          [ "websocket_frame", "classkcenon_1_1network_1_1internal_1_1websocket__frame.html", "classkcenon_1_1network_1_1internal_1_1websocket__frame" ],
          [ "websocket_handshake", "classkcenon_1_1network_1_1internal_1_1websocket__handshake.html", "classkcenon_1_1network_1_1internal_1_1websocket__handshake" ],
          [ "websocket_protocol", "classkcenon_1_1network_1_1internal_1_1websocket__protocol.html", "classkcenon_1_1network_1_1internal_1_1websocket__protocol" ],
          [ "websocket_socket", "classkcenon_1_1network_1_1internal_1_1websocket__socket.html", "classkcenon_1_1network_1_1internal_1_1websocket__socket" ],
          [ "ws_frame_header", "structkcenon_1_1network_1_1internal_1_1ws__frame__header.html", "structkcenon_1_1network_1_1internal_1_1ws__frame__header" ],
          [ "ws_handshake_result", "structkcenon_1_1network_1_1internal_1_1ws__handshake__result.html", "structkcenon_1_1network_1_1internal_1_1ws__handshake__result" ],
          [ "ws_message", "structkcenon_1_1network_1_1internal_1_1ws__message.html", "structkcenon_1_1network_1_1internal_1_1ws__message" ]
        ] ],
        [ "metrics", "namespacekcenon_1_1network_1_1metrics.html", [
          [ "histogram", "classkcenon_1_1network_1_1metrics_1_1histogram.html", "classkcenon_1_1network_1_1metrics_1_1histogram" ],
          [ "histogram_config", "structkcenon_1_1network_1_1metrics_1_1histogram__config.html", "structkcenon_1_1network_1_1metrics_1_1histogram__config" ],
          [ "histogram_snapshot", "structkcenon_1_1network_1_1metrics_1_1histogram__snapshot.html", "structkcenon_1_1network_1_1metrics_1_1histogram__snapshot" ],
          [ "metric_reporter", "classkcenon_1_1network_1_1metrics_1_1metric__reporter.html", "classkcenon_1_1network_1_1metrics_1_1metric__reporter" ],
          [ "sliding_histogram", "classkcenon_1_1network_1_1metrics_1_1sliding__histogram.html", "classkcenon_1_1network_1_1metrics_1_1sliding__histogram" ],
          [ "sliding_histogram_config", "structkcenon_1_1network_1_1metrics_1_1sliding__histogram__config.html", "structkcenon_1_1network_1_1metrics_1_1sliding__histogram__config" ]
        ] ],
        [ "policy", "namespacekcenon_1_1network_1_1policy.html", [
          [ "is_tls_enabled", "structkcenon_1_1network_1_1policy_1_1is__tls__enabled.html", null ],
          [ "no_tls", "structkcenon_1_1network_1_1policy_1_1no__tls.html", "structkcenon_1_1network_1_1policy_1_1no__tls" ],
          [ "tls_enabled", "structkcenon_1_1network_1_1policy_1_1tls__enabled.html", "structkcenon_1_1network_1_1policy_1_1tls__enabled" ]
        ] ],
        [ "protocol", "namespacekcenon_1_1network_1_1protocol.html", [
          [ "quic", "namespacekcenon_1_1network_1_1protocol_1_1quic.html", [
            [ "quic_config", "structkcenon_1_1network_1_1protocol_1_1quic_1_1quic__config.html", "structkcenon_1_1network_1_1protocol_1_1quic_1_1quic__config" ]
          ] ],
          [ "is_connection_oriented", "structkcenon_1_1network_1_1protocol_1_1is__connection__oriented.html", null ],
          [ "is_reliable", "structkcenon_1_1network_1_1protocol_1_1is__reliable.html", null ],
          [ "quic_protocol", "structkcenon_1_1network_1_1protocol_1_1quic__protocol.html", "structkcenon_1_1network_1_1protocol_1_1quic__protocol" ],
          [ "tcp_protocol", "structkcenon_1_1network_1_1protocol_1_1tcp__protocol.html", "structkcenon_1_1network_1_1protocol_1_1tcp__protocol" ],
          [ "udp_protocol", "structkcenon_1_1network_1_1protocol_1_1udp__protocol.html", "structkcenon_1_1network_1_1protocol_1_1udp__protocol" ],
          [ "websocket_protocol", "structkcenon_1_1network_1_1protocol_1_1websocket__protocol.html", "structkcenon_1_1network_1_1protocol_1_1websocket__protocol" ]
        ] ],
        [ "protocols", "namespacekcenon_1_1network_1_1protocols.html", [
          [ "grpc", "namespacekcenon_1_1network_1_1protocols_1_1grpc.html", [
            [ "bidi_stream_impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1bidi__stream__impl.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1bidi__stream__impl" ],
            [ "call_options", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1call__options.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1call__options" ],
            [ "channel_credentials_config", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1channel__credentials__config.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1channel__credentials__config" ],
            [ "client_stream_writer_impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1client__stream__writer__impl.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1client__stream__writer__impl" ],
            [ "generic_service", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1generic__service.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1generic__service" ],
            [ "grpc_channel_config", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__channel__config.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__channel__config" ],
            [ "grpc_client", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__client.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__client" ],
            [ "grpc_message", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__message.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__message" ],
            [ "grpc_server", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__server.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__server" ],
            [ "grpc_server_config", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__server__config.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__server__config" ],
            [ "grpc_service", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__service.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__service" ],
            [ "grpc_status", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__status.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__status" ],
            [ "grpc_trailers", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__trailers.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__trailers" ],
            [ "health_service", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1health__service.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1health__service" ],
            [ "method_descriptor", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1method__descriptor.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1method__descriptor" ],
            [ "method_handler", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1method__handler.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1method__handler" ],
            [ "registry_config", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1registry__config.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1registry__config" ],
            [ "server_context", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__context.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__context" ],
            [ "server_reader", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__reader.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__reader" ],
            [ "server_reader_writer", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__reader__writer.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__reader__writer" ],
            [ "server_stream_reader_impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__stream__reader__impl.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__stream__reader__impl" ],
            [ "server_writer", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__writer.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__writer" ],
            [ "service_base", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1service__base.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1service__base" ],
            [ "service_descriptor", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1service__descriptor.html", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1service__descriptor" ],
            [ "service_registry", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1service__registry.html", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1service__registry" ]
          ] ],
          [ "http2", "namespacekcenon_1_1network_1_1protocols_1_1http2.html", [
            [ "data_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1data__frame.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1data__frame" ],
            [ "dynamic_table", "classkcenon_1_1network_1_1protocols_1_1http2_1_1dynamic__table.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1dynamic__table" ],
            [ "frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1frame.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1frame" ],
            [ "frame_header", "structkcenon_1_1network_1_1protocols_1_1http2_1_1frame__header.html", "structkcenon_1_1network_1_1protocols_1_1http2_1_1frame__header" ],
            [ "goaway_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1goaway__frame.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1goaway__frame" ],
            [ "headers_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1headers__frame.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1headers__frame" ],
            [ "hpack_decoder", "classkcenon_1_1network_1_1protocols_1_1http2_1_1hpack__decoder.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1hpack__decoder" ],
            [ "hpack_encoder", "classkcenon_1_1network_1_1protocols_1_1http2_1_1hpack__encoder.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1hpack__encoder" ],
            [ "http2_client", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__client.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__client" ],
            [ "http2_request", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__request.html", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__request" ],
            [ "http2_response", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__response.html", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__response" ],
            [ "http2_server", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__server.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__server" ],
            [ "http2_server_connection", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__server__connection.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__server__connection" ],
            [ "http2_server_stream", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__server__stream.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__server__stream" ],
            [ "http2_settings", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__settings.html", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__settings" ],
            [ "http2_stream", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__stream.html", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__stream" ],
            [ "http_header", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http__header.html", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http__header" ],
            [ "ping_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1ping__frame.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1ping__frame" ],
            [ "rst_stream_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1rst__stream__frame.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1rst__stream__frame" ],
            [ "setting_parameter", "structkcenon_1_1network_1_1protocols_1_1http2_1_1setting__parameter.html", "structkcenon_1_1network_1_1protocols_1_1http2_1_1setting__parameter" ],
            [ "settings_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1settings__frame.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1settings__frame" ],
            [ "static_table", "classkcenon_1_1network_1_1protocols_1_1http2_1_1static__table.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1static__table" ],
            [ "tls_config", "structkcenon_1_1network_1_1protocols_1_1http2_1_1tls__config.html", "structkcenon_1_1network_1_1protocols_1_1http2_1_1tls__config" ],
            [ "window_update_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1window__update__frame.html", "classkcenon_1_1network_1_1protocols_1_1http2_1_1window__update__frame" ]
          ] ],
          [ "quic", "namespacekcenon_1_1network_1_1protocols_1_1quic.html", [
            [ "ack_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ack__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ack__frame" ],
            [ "ack_range", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ack__range.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ack__range" ],
            [ "congestion_controller", "classkcenon_1_1network_1_1protocols_1_1quic_1_1congestion__controller.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1congestion__controller" ],
            [ "connection", "classkcenon_1_1network_1_1protocols_1_1quic_1_1connection.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1connection" ],
            [ "connection_close_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1connection__close__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1connection__close__frame" ],
            [ "connection_id", "classkcenon_1_1network_1_1protocols_1_1quic_1_1connection__id.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1connection__id" ],
            [ "connection_id_entry", "structkcenon_1_1network_1_1protocols_1_1quic_1_1connection__id__entry.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1connection__id__entry" ],
            [ "connection_id_manager", "classkcenon_1_1network_1_1protocols_1_1quic_1_1connection__id__manager.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1connection__id__manager" ],
            [ "crypto_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1crypto__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1crypto__frame" ],
            [ "data_blocked_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1data__blocked__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1data__blocked__frame" ],
            [ "ecn_counts", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ecn__counts.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ecn__counts" ],
            [ "ecn_tracker", "classkcenon_1_1network_1_1protocols_1_1quic_1_1ecn__tracker.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1ecn__tracker" ],
            [ "flow_control_stats", "structkcenon_1_1network_1_1protocols_1_1quic_1_1flow__control__stats.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1flow__control__stats" ],
            [ "flow_controller", "classkcenon_1_1network_1_1protocols_1_1quic_1_1flow__controller.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1flow__controller" ],
            [ "frame_builder", "classkcenon_1_1network_1_1protocols_1_1quic_1_1frame__builder.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1frame__builder" ],
            [ "frame_parser", "classkcenon_1_1network_1_1protocols_1_1quic_1_1frame__parser.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1frame__parser" ],
            [ "handshake_done_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1handshake__done__frame.html", null ],
            [ "hkdf", "classkcenon_1_1network_1_1protocols_1_1quic_1_1hkdf.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1hkdf" ],
            [ "initial_keys", "classkcenon_1_1network_1_1protocols_1_1quic_1_1initial__keys.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1initial__keys" ],
            [ "key_pair", "structkcenon_1_1network_1_1protocols_1_1quic_1_1key__pair.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1key__pair" ],
            [ "long_header", "structkcenon_1_1network_1_1protocols_1_1quic_1_1long__header.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1long__header" ],
            [ "loss_detection_result", "structkcenon_1_1network_1_1protocols_1_1quic_1_1loss__detection__result.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1loss__detection__result" ],
            [ "loss_detector", "classkcenon_1_1network_1_1protocols_1_1quic_1_1loss__detector.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1loss__detector" ],
            [ "max_data_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1max__data__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1max__data__frame" ],
            [ "max_stream_data_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1max__stream__data__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1max__stream__data__frame" ],
            [ "max_streams_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1max__streams__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1max__streams__frame" ],
            [ "new_connection_id_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1new__connection__id__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1new__connection__id__frame" ],
            [ "new_token_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1new__token__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1new__token__frame" ],
            [ "packet_builder", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__builder.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__builder" ],
            [ "packet_number", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__number.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__number" ],
            [ "packet_number_space", "structkcenon_1_1network_1_1protocols_1_1quic_1_1packet__number__space.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1packet__number__space" ],
            [ "packet_parser", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__parser.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__parser" ],
            [ "packet_protection", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__protection.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__protection" ],
            [ "padding_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1padding__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1padding__frame" ],
            [ "path_challenge_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1path__challenge__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1path__challenge__frame" ],
            [ "path_response_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1path__response__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1path__response__frame" ],
            [ "ping_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ping__frame.html", null ],
            [ "pmtud_config", "structkcenon_1_1network_1_1protocols_1_1quic_1_1pmtud__config.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1pmtud__config" ],
            [ "pmtud_controller", "classkcenon_1_1network_1_1protocols_1_1quic_1_1pmtud__controller.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1pmtud__controller" ],
            [ "preferred_address_info", "structkcenon_1_1network_1_1protocols_1_1quic_1_1preferred__address__info.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1preferred__address__info" ],
            [ "quic_crypto", "classkcenon_1_1network_1_1protocols_1_1quic_1_1quic__crypto.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1quic__crypto" ],
            [ "quic_keys", "structkcenon_1_1network_1_1protocols_1_1quic_1_1quic__keys.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1quic__keys" ],
            [ "replay_filter", "classkcenon_1_1network_1_1protocols_1_1quic_1_1replay__filter.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1replay__filter" ],
            [ "reset_stream_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1reset__stream__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1reset__stream__frame" ],
            [ "retire_connection_id_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1retire__connection__id__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1retire__connection__id__frame" ],
            [ "rtt_estimator", "classkcenon_1_1network_1_1protocols_1_1quic_1_1rtt__estimator.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1rtt__estimator" ],
            [ "sent_packet", "structkcenon_1_1network_1_1protocols_1_1quic_1_1sent__packet.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1sent__packet" ],
            [ "sent_packet_info", "structkcenon_1_1network_1_1protocols_1_1quic_1_1sent__packet__info.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1sent__packet__info" ],
            [ "session_ticket_info", "structkcenon_1_1network_1_1protocols_1_1quic_1_1session__ticket__info.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1session__ticket__info" ],
            [ "session_ticket_store", "classkcenon_1_1network_1_1protocols_1_1quic_1_1session__ticket__store.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1session__ticket__store" ],
            [ "short_header", "structkcenon_1_1network_1_1protocols_1_1quic_1_1short__header.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1short__header" ],
            [ "stop_sending_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1stop__sending__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1stop__sending__frame" ],
            [ "stream", "classkcenon_1_1network_1_1protocols_1_1quic_1_1stream.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1stream" ],
            [ "stream_data_blocked_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1stream__data__blocked__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1stream__data__blocked__frame" ],
            [ "stream_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1stream__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1stream__frame" ],
            [ "stream_manager", "classkcenon_1_1network_1_1protocols_1_1quic_1_1stream__manager.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1stream__manager" ],
            [ "streams_blocked_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1streams__blocked__frame.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1streams__blocked__frame" ],
            [ "transport_parameters", "structkcenon_1_1network_1_1protocols_1_1quic_1_1transport__parameters.html", "structkcenon_1_1network_1_1protocols_1_1quic_1_1transport__parameters" ],
            [ "varint", "classkcenon_1_1network_1_1protocols_1_1quic_1_1varint.html", "classkcenon_1_1network_1_1protocols_1_1quic_1_1varint" ]
          ] ]
        ] ],
        [ "session", "namespacekcenon_1_1network_1_1session.html", [
          [ "messaging_session", "classkcenon_1_1network_1_1session_1_1messaging__session.html", "classkcenon_1_1network_1_1session_1_1messaging__session" ],
          [ "quic_session", "classkcenon_1_1network_1_1session_1_1quic__session.html", "classkcenon_1_1network_1_1session_1_1quic__session" ],
          [ "secure_session", "classkcenon_1_1network_1_1session_1_1secure__session.html", "classkcenon_1_1network_1_1session_1_1secure__session" ]
        ] ],
        [ "tracing", "namespacekcenon_1_1network_1_1tracing.html", [
          [ "batch_config", "structkcenon_1_1network_1_1tracing_1_1batch__config.html", "structkcenon_1_1network_1_1tracing_1_1batch__config" ],
          [ "otlp_config", "structkcenon_1_1network_1_1tracing_1_1otlp__config.html", "structkcenon_1_1network_1_1tracing_1_1otlp__config" ],
          [ "span", "classkcenon_1_1network_1_1tracing_1_1span.html", "classkcenon_1_1network_1_1tracing_1_1span" ],
          [ "span_event", "structkcenon_1_1network_1_1tracing_1_1span__event.html", "structkcenon_1_1network_1_1tracing_1_1span__event" ],
          [ "trace_context", "classkcenon_1_1network_1_1tracing_1_1trace__context.html", "classkcenon_1_1network_1_1tracing_1_1trace__context" ],
          [ "tracing_config", "structkcenon_1_1network_1_1tracing_1_1tracing__config.html", "structkcenon_1_1network_1_1tracing_1_1tracing__config" ]
        ] ],
        [ "unified", "namespacekcenon_1_1network_1_1unified.html", [
          [ "adapters", "namespacekcenon_1_1network_1_1unified_1_1adapters.html", [
            [ "quic_connection_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1quic__connection__adapter.html", "classkcenon_1_1network_1_1unified_1_1adapters_1_1quic__connection__adapter" ],
            [ "quic_listener_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1quic__listener__adapter.html", "classkcenon_1_1network_1_1unified_1_1adapters_1_1quic__listener__adapter" ],
            [ "tcp_connection_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1tcp__connection__adapter.html", "classkcenon_1_1network_1_1unified_1_1adapters_1_1tcp__connection__adapter" ],
            [ "tcp_listener_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1tcp__listener__adapter.html", "classkcenon_1_1network_1_1unified_1_1adapters_1_1tcp__listener__adapter" ],
            [ "udp_connection_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1udp__connection__adapter.html", "classkcenon_1_1network_1_1unified_1_1adapters_1_1udp__connection__adapter" ],
            [ "udp_listener_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1udp__listener__adapter.html", "classkcenon_1_1network_1_1unified_1_1adapters_1_1udp__listener__adapter" ],
            [ "ws_connection_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1ws__connection__adapter.html", "classkcenon_1_1network_1_1unified_1_1adapters_1_1ws__connection__adapter" ],
            [ "ws_listener_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1ws__listener__adapter.html", "classkcenon_1_1network_1_1unified_1_1adapters_1_1ws__listener__adapter" ]
          ] ],
          [ "connection_callbacks", "structkcenon_1_1network_1_1unified_1_1connection__callbacks.html", "structkcenon_1_1network_1_1unified_1_1connection__callbacks" ],
          [ "connection_options", "structkcenon_1_1network_1_1unified_1_1connection__options.html", "structkcenon_1_1network_1_1unified_1_1connection__options" ],
          [ "endpoint_info", "structkcenon_1_1network_1_1unified_1_1endpoint__info.html", "structkcenon_1_1network_1_1unified_1_1endpoint__info" ],
          [ "i_connection", "classkcenon_1_1network_1_1unified_1_1i__connection.html", "classkcenon_1_1network_1_1unified_1_1i__connection" ],
          [ "i_listener", "classkcenon_1_1network_1_1unified_1_1i__listener.html", "classkcenon_1_1network_1_1unified_1_1i__listener" ],
          [ "i_transport", "classkcenon_1_1network_1_1unified_1_1i__transport.html", "classkcenon_1_1network_1_1unified_1_1i__transport" ],
          [ "listener_callbacks", "structkcenon_1_1network_1_1unified_1_1listener__callbacks.html", "structkcenon_1_1network_1_1unified_1_1listener__callbacks" ]
        ] ],
        [ "utils", "namespacekcenon_1_1network_1_1utils.html", [
          [ "buffer_pool", "classkcenon_1_1network_1_1utils_1_1buffer__pool.html", "classkcenon_1_1network_1_1utils_1_1buffer__pool" ],
          [ "callback_manager", "classkcenon_1_1network_1_1utils_1_1callback__manager.html", "classkcenon_1_1network_1_1utils_1_1callback__manager" ],
          [ "compression_pipeline", "classkcenon_1_1network_1_1utils_1_1compression__pipeline.html", "classkcenon_1_1network_1_1utils_1_1compression__pipeline" ],
          [ "connection_health", "structkcenon_1_1network_1_1utils_1_1connection__health.html", "structkcenon_1_1network_1_1utils_1_1connection__health" ],
          [ "connection_state", "classkcenon_1_1network_1_1utils_1_1connection__state.html", "classkcenon_1_1network_1_1utils_1_1connection__state" ],
          [ "health_monitor", "classkcenon_1_1network_1_1utils_1_1health__monitor.html", "classkcenon_1_1network_1_1utils_1_1health__monitor" ],
          [ "lifecycle_manager", "classkcenon_1_1network_1_1utils_1_1lifecycle__manager.html", "classkcenon_1_1network_1_1utils_1_1lifecycle__manager" ],
          [ "memory_profiler", "classkcenon_1_1network_1_1utils_1_1memory__profiler.html", "classkcenon_1_1network_1_1utils_1_1memory__profiler" ],
          [ "memory_snapshot", "structkcenon_1_1network_1_1utils_1_1memory__snapshot.html", "structkcenon_1_1network_1_1utils_1_1memory__snapshot" ],
          [ "resilient_client", "classkcenon_1_1network_1_1utils_1_1resilient__client.html", "classkcenon_1_1network_1_1utils_1_1resilient__client" ],
          [ "startable_base", "classkcenon_1_1network_1_1utils_1_1startable__base.html", "classkcenon_1_1network_1_1utils_1_1startable__base" ],
          [ "tcp_client_callback_index", "structkcenon_1_1network_1_1utils_1_1tcp__client__callback__index.html", "structkcenon_1_1network_1_1utils_1_1tcp__client__callback__index" ]
        ] ],
        [ "connection_guard", "classkcenon_1_1network_1_1connection__guard.html", "classkcenon_1_1network_1_1connection__guard" ],
        [ "connection_limiter", "classkcenon_1_1network_1_1connection__limiter.html", "classkcenon_1_1network_1_1connection__limiter" ],
        [ "message_limits", "structkcenon_1_1network_1_1message__limits.html", "structkcenon_1_1network_1_1message__limits" ],
        [ "message_validator", "classkcenon_1_1network_1_1message__validator.html", "classkcenon_1_1network_1_1message__validator" ],
        [ "module_version", "structkcenon_1_1network_1_1module__version.html", "structkcenon_1_1network_1_1module__version" ],
        [ "per_client_connection_limiter", "classkcenon_1_1network_1_1per__client__connection__limiter.html", "classkcenon_1_1network_1_1per__client__connection__limiter" ],
        [ "rate_limiter", "classkcenon_1_1network_1_1rate__limiter.html", "classkcenon_1_1network_1_1rate__limiter" ],
        [ "rate_limiter_config", "structkcenon_1_1network_1_1rate__limiter__config.html", "structkcenon_1_1network_1_1rate__limiter__config" ],
        [ "Result", "classkcenon_1_1network_1_1Result.html", "classkcenon_1_1network_1_1Result" ],
        [ "session_timeout_manager", "classkcenon_1_1network_1_1session__timeout__manager.html", "classkcenon_1_1network_1_1session__timeout__manager" ],
        [ "simple_error", "structkcenon_1_1network_1_1simple__error.html", "structkcenon_1_1network_1_1simple__error" ]
      ] ]
    ] ],
    [ "chat_observer", "classchat__observer.html", "classchat__observer" ],
    [ "receive_only_observer", "classreceive__only__observer.html", "classreceive__only__observer" ]
];