Network System: kcenon::network::core::secure_messaging_client Class Reference
kcenon::network::core::secure_messaging_client Class Reference export
module kcenon.network
A secure client for establishing TLS/SSL encrypted TCP connections to a server.
#include <secure_messaging_client.h>
Public Types
using receive_callback_t = std::function< void(const std::vector< uint8_t > &)>
Callback type for received data.
using connected_callback_t = std::function< void()>
Callback type for connection established.
using disconnected_callback_t = std::function< void()>
Callback type for disconnection.
using error_callback_t = std::function< void(std::error_code)>
Callback type for errors.
Public Member Functions
secure_messaging_client (std::string_view client_id, bool verify_cert=true)
Constructs a secure messaging client.
~secure_messaging_client () noexcept
Destructor. Calls stop_client() if still connected.
secure_messaging_client (const secure_messaging_client &)=delete
secure_messaging_client & operator= (const secure_messaging_client &)=delete
secure_messaging_client (secure_messaging_client &&)=delete
secure_messaging_client & operator= (secure_messaging_client &&)=delete
auto start_client (std::string_view host, unsigned short port) -> VoidResult
Starts the client and connects to the specified host and port.
auto stop_client () -> VoidResult
Stops the client and disconnects from the server.
auto wait_for_stop () -> void
Blocks until stop_client() is called.
auto is_running () const noexcept -> bool
Checks if the client is currently running.
auto is_connected () const noexcept -> bool
Checks if the client is connected to the server.
auto client_id () const -> const std::string &
Returns the client identifier.
auto send_packet (std::vector< uint8_t > &&data) -> VoidResult
Sends data to the connected server.
auto set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received data.
auto set_connected_callback (connected_callback_t callback) -> void
Sets the callback for connection established.
auto set_disconnected_callback (disconnected_callback_t callback) -> void
Sets the callback for disconnection.
auto set_error_callback (error_callback_t callback) -> void
Sets the callback for errors.
secure_messaging_client (std::string_view client_id, const ssl_config &config={})
Construct a secure client with SSL configuration.
virtual ~secure_messaging_client () noexcept
Destructor.
secure_messaging_client (const secure_messaging_client &)=delete
secure_messaging_client & operator= (const secure_messaging_client &)=delete
secure_messaging_client (secure_messaging_client &&) noexcept
secure_messaging_client & operator= (secure_messaging_client &&) noexcept
bool start_client (std::string_view host, uint16_t port)
Start the client and connect securely.
void stop_client ()
Stop the client.
bool wait_for_stop (std::chrono::milliseconds timeout=std::chrono::milliseconds(5000))
Wait for the client to stop.
bool send_packet (std::span< const uint8_t > data)
Send encrypted data.
bool send_packet (std::string_view data)
Send encrypted string data.
bool is_connected () const noexcept
Check if the client is connected and TLS handshake completed.
bool is_running () const noexcept
Check if the client is running.
connection_state get_state () const noexcept
Get the current connection state.
std::string_view client_id () const noexcept
Get the client identifier.
void set_connection_callback (connection_callback callback)
Set connection callback (called after TLS handshake)
void set_disconnection_callback (disconnection_callback callback)
Set disconnection callback.
void set_error_callback (error_callback callback)
Set error callback.
void set_data_callback (data_callback callback)
Set data received callback.
std::optional< std::string > get_peer_certificate_subject () const
Get peer certificate information.
std::string get_protocol_version () const
Get the negotiated TLS protocol version.
std::string get_cipher_suite () const
Get the negotiated cipher suite.
Private Types
using callback_index = tcp_client_callback
Callback index type alias for clarity.
using callbacks_t = utils::callback_manager< receive_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t >
Callback manager type for this client.
Private Member Functions
auto do_start_impl (std::string_view host, unsigned short port) -> VoidResult
Secure TCP-specific implementation of client start.
auto do_stop_impl () -> VoidResult
Secure TCP-specific implementation of client stop.
auto do_send_impl (std::vector< uint8_t > &&data) -> VoidResult
Secure TCP-specific implementation of data send.
auto set_connected (bool connected) -> void
Sets the connected state.
auto invoke_receive_callback (const std::vector< uint8_t > &data) -> void
Invokes the receive callback.
auto invoke_connected_callback () -> void
Invokes the connected callback.
auto invoke_disconnected_callback () -> void
Invokes the disconnected callback.
auto invoke_error_callback (std::error_code ec) -> void
Invokes the error callback.
auto on_receive (const std::vector< uint8_t > &data) -> void
Callback for when encrypted data arrives from the server.
auto on_error (std::error_code ec) -> void
Callback for handling socket errors.
Private Attributes
std::string client_id_
utils::lifecycle_manager lifecycle_
callbacks_t callbacks_
std::atomic< bool > is_connected_ {false}
std::unique_ptr< asio::io_context > io_context_
std::unique_ptr< asio::executor_work_guard< asio::io_context::executor_type > > work_guard_
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::future< void > io_context_future_
std::unique_ptr< asio::ssl::context > ssl_context_
std::shared_ptr< internal::secure_tcp_socket > socket_
bool verify_cert_ {true}
std::unique_ptr< impl > pimpl_
Detailed Description
A secure client for establishing TLS/SSL encrypted TCP connections to a server.
An SSL/TLS encrypted TCP client.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling.
Thread Safety
All public methods are thread-safe.
Connection state (is_connected_) is protected by atomic operations.
Socket operations are serialized through ASIO's io_context.
Key Responsibilities
Establishes encrypted connection to a remote server using TLS/SSL.
Performs SSL handshake after TCP connection.
Manages asio::io_context and runs it in a background thread.
Provides start_client() to connect and stop_client() to disconnect.
Sends encrypted data via send_packet().
Optionally verifies server certificate.
Usage Example
auto client = std::make_shared<secure_messaging_client>("ClientID");
auto result = client->start_client("server.example.com", 5555);
if (!result) {
    std::cerr << "Connection failed\n";
    return;
}
std::vector<uint8_t> data = {1, 2, 3};
client->send_packet(std::move(data));
client->stop_client();
This class provides a secure TCP client with SSL/TLS encryption, certificate verification, and modern TLS features.
Thread Safety
All public methods are thread-safe.
Key Features
TLS 1.2/1.3 support
Certificate verification
SNI support
Session resumption
import kcenon.network;
using namespace kcenon::network::core;
ssl_config config;
config.ca_certificate_path = "/path/to/ca.pem";
config.server_name = "example.com";
auto client = std::make_unique<secure_messaging_client>("secure_client", config);
client->start_client("example.com", 443);
Definition at line 99 of file secure_messaging_client.h.
Member Typedef Documentation
callback_index
using kcenon::network::core::secure_messaging_client::callback_index = tcp_client_callback private
Callback index type alias for clarity.
Definition at line 294 of file secure_messaging_client.h.
callbacks_t
using kcenon::network::core::secure_messaging_client::callbacks_t = utils::callback_manager< receive_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t > private
Callback manager type for this client.
Definition at line 297 of file secure_messaging_client.h.
connected_callback_t
using kcenon::network::core::secure_messaging_client::connected_callback_t = std::function<void()>
Callback type for connection established.
Definition at line 106 of file secure_messaging_client.h.
disconnected_callback_t
using kcenon::network::core::secure_messaging_client::disconnected_callback_t = std::function<void()>
Callback type for disconnection.
Definition at line 108 of file secure_messaging_client.h.
error_callback_t
using kcenon::network::core::secure_messaging_client::error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Definition at line 110 of file secure_messaging_client.h.
receive_callback_t
using kcenon::network::core::secure_messaging_client::receive_callback_t = std::function<void(const std::vector<uint8_t>&)>
Callback type for received data.
Definition at line 104 of file secure_messaging_client.h.
Constructor & Destructor Documentation
secure_messaging_client() [1/6]
kcenon::network::core::secure_messaging_client::secure_messaging_client (std::string_view client_id, bool verify_cert = true) explicit
Constructs a secure messaging client.
Parameters
client_id A descriptive identifier for this client instance.
verify_cert Whether to verify server certificate (default: true)
Definition at line 45 of file secure_messaging_client.cpp.
    : client_id_(client_id),
      verify_cert_(verify_cert) {
  // Initialize SSL context with TLS 1.3 support (TICKET-009: TLS 1.3 only by default)
  ssl_context_ =
      std::make_unique<asio::ssl::context>(asio::ssl::context::tls_client);
  // Set SSL context options - disable all legacy protocols
  ssl_context_->set_options(
      asio::ssl::context::default_workarounds | asio::ssl::context::no_sslv2 |
      asio::ssl::context::no_sslv3 | asio::ssl::context::no_tlsv1 |
      asio::ssl::context::no_tlsv1_1);
  // Enforce TLS 1.3 minimum version using native OpenSSL handle
  // This prevents protocol downgrade attacks (CVSS 7.5)
  SSL_CTX *native_ctx = ssl_context_->native_handle();
  if (native_ctx) {
    // Set minimum protocol version to TLS 1.3 (security hardening)
    SSL_CTX_set_min_proto_version(native_ctx, TLS1_3_VERSION);
    SSL_CTX_set_max_proto_version(native_ctx, TLS1_3_VERSION);
    // Set strong cipher suites for TLS 1.3
    SSL_CTX_set_ciphersuites(native_ctx,
        "TLS_AES_256_GCM_SHA384:"
        "TLS_CHACHA20_POLY1305_SHA256:"
        "TLS_AES_128_GCM_SHA256");
  }
  if (verify_cert_) {
    // Set verification mode to verify peer certificate
    ssl_context_->set_verify_mode(asio::ssl::verify_peer);
    // Load default certificate paths for verification
    ssl_context_->set_default_verify_paths();
    NETWORK_LOG_INFO("[secure_messaging_client] SSL context initialized with "
                     "TLS 1.3 only and certificate verification");
  } else {
    // No certificate verification
    ssl_context_->set_verify_mode(asio::ssl::verify_none);
    NETWORK_LOG_WARN("[secure_messaging_client] SSL context initialized with "
                     "TLS 1.3 only WITHOUT certificate verification");
  }
}
References NETWORK_LOG_INFO, NETWORK_LOG_WARN, ssl_context_, and verify_cert_.
~secure_messaging_client() [1/2]
kcenon::network::core::secure_messaging_client::~secure_messaging_client () noexcept
Destructor. Calls stop_client() if still connected.
Definition at line 92 of file secure_messaging_client.cpp.
{
  if (lifecycle_.is_running()) {
    (void)stop_client();
  }
}
References kcenon::network::utils::lifecycle_manager::is_running(), lifecycle_, and stop_client().
secure_messaging_client() [2/6]
kcenon::network::core::secure_messaging_client::secure_messaging_client (const secure_messaging_client &) delete
secure_messaging_client() [3/6]
kcenon::network::core::secure_messaging_client::secure_messaging_client (secure_messaging_client &&) delete
secure_messaging_client() [4/6]
kcenon::network::core::secure_messaging_client::secure_messaging_client (std::string_view client_id, const ssl_config & config = {}) explicit export
Construct a secure client with SSL configuration.
Parameters
client_id A string identifier for this client instance
config SSL/TLS configuration
~secure_messaging_client() [2/2]
virtual kcenon::network::core::secure_messaging_client::~secure_messaging_client () export virtual noexcept
Destructor.
secure_messaging_client() [5/6]
kcenon::network::core::secure_messaging_client::secure_messaging_client (const secure_messaging_client &) export delete
secure_messaging_client() [6/6]
kcenon::network::core::secure_messaging_client::secure_messaging_client (secure_messaging_client &&) export noexcept
Member Function Documentation
client_id() [1/2]
auto kcenon::network::core::secure_messaging_client::client_id () const -> const std::string&
Returns the client identifier.
Returns
The client_id string.
Definition at line 171 of file secure_messaging_client.cpp.
{
  return client_id_;
}
References client_id_.
client_id() [2/2]
std::string_view kcenon::network::core::secure_messaging_client::client_id () const export noexcept
Get the client identifier.
Returns
Client ID string
do_send_impl()
auto kcenon::network::core::secure_messaging_client::do_send_impl (std::vector< uint8_t > && data) -> VoidResult private
Secure TCP-specific implementation of data send.
Parameters
data The data to send (moved for efficiency).
Returns
Result<void> - Success if sent, or error
Definition at line 415 of file secure_messaging_client.cpp.
                  {
  if (!socket_) {
    return error_void(
        error_codes::network_system::send_failed, "Socket is not available",
        "secure_messaging_client::do_send_impl", "Client ID: " + client_id_);
  }
  // Send data directly over the secure connection
  socket_->async_send(
      std::move(data), [this](std::error_code ec, std::size_t bytes_transferred) {
        if (ec) {
          NETWORK_LOG_ERROR("[secure_messaging_client] Send error: " +
                            ec.message());
        } else {
          NETWORK_LOG_DEBUG("[secure_messaging_client] Sent " +
                            std::to_string(bytes_transferred) + " bytes");
        }
      });
  return ok();
}
References kcenon::network::error_void(), NETWORK_LOG_DEBUG, NETWORK_LOG_ERROR, kcenon::network::ok(), and kcenon::network::error_codes::network_system::send_failed.
do_start_impl()
auto kcenon::network::core::secure_messaging_client::do_start_impl (std::string_view host, unsigned short port) -> VoidResult private
Secure TCP-specific implementation of client start.
Parameters
host The server hostname or IP address.
port The server port number.
Returns
Result<void> - Success if connected, or error with code:
error_codes::network_system::connection_failed
error_codes::network_system::connection_timeout
error_codes::common_errors::internal_error
Definition at line 245 of file secure_messaging_client.cpp.
{
  try {
    // Create io_context
    io_context_ = std::make_unique<asio::io_context>();
    // Create work guard to keep io_context running
    work_guard_ = std::make_unique<
        asio::executor_work_guard<asio::io_context::executor_type>>(
        asio::make_work_guard(*io_context_));
    // Resolve the server address
    tcp::resolver resolver(*io_context_);
    auto endpoints = resolver.resolve(std::string(host), std::to_string(port));
    // Create TCP socket first (not SSL socket yet)
    tcp::socket tcp_sock(*io_context_);
    // Connect to server (plain TCP)
    std::error_code connect_ec;
    asio::connect(tcp_sock, endpoints, connect_ec);
    if (connect_ec) {
      return error_void(error_codes::network_system::connection_failed,
                        "Failed to connect to server: " + connect_ec.message(),
                        "secure_messaging_client::do_start_impl",
                        "Host: " + std::string(host) +
                            ", Port: " + std::to_string(port));
    }
    // Now create secure socket with connected TCP socket
    socket_ = std::make_shared<internal::secure_tcp_socket>(std::move(tcp_sock),
                                                            *ssl_context_);
    // Set up callbacks
    auto self = shared_from_this();
    socket_->set_receive_callback(
        [this, self](const std::vector<uint8_t> &data) { on_receive(data); });
    socket_->set_error_callback(
        [this, self](std::error_code ec) { on_error(ec); });
    // Perform SSL handshake (synchronously for now)
    std::promise<std::error_code> handshake_promise;
    auto handshake_future = handshake_promise.get_future();
    socket_->async_handshake(asio::ssl::stream_base::client,
                             [&handshake_promise](std::error_code ec) {
                               handshake_promise.set_value(ec);
                             });
    // Get thread pool from network context
    thread_pool_ = network_context::instance().get_thread_pool();
    if (!thread_pool_) {
      // Fallback: create a temporary thread pool if network_context is not
      // initialized
      NETWORK_LOG_WARN(
          "[secure_messaging_client::" + client_id_ +
          "] network_context not initialized, creating temporary thread pool");
      thread_pool_ = std::make_shared<integration::basic_thread_pool>(
          std::thread::hardware_concurrency());
    }
    // Start io_context on thread pool for handshake to complete
    io_context_future_ = thread_pool_->submit([this]() {
      try {
        NETWORK_LOG_DEBUG("[secure_messaging_client::" + client_id_ +
                          "] io_context started");
        io_context_->run();
        NETWORK_LOG_DEBUG("[secure_messaging_client::" + client_id_ +
                          "] io_context stopped");
      } catch (const std::exception &e) {
        NETWORK_LOG_ERROR(
            "[secure_messaging_client::" + client_id_ +
            "] Exception in io_context: " + std::string(e.what()));
      }
    });
    // Wait for handshake to complete (with timeout)
    auto status = handshake_future.wait_for(std::chrono::seconds(10));
    if (status == std::future_status::timeout) {
      return error_void(error_codes::network_system::connection_timeout,
                        "SSL handshake timeout",
                        "secure_messaging_client::do_start_impl",
                        "Host: " + std::string(host) +
                            ", Port: " + std::to_string(port));
    }
    auto handshake_ec = handshake_future.get();
    if (handshake_ec) {
      return error_void(error_codes::network_system::connection_failed,
                        "SSL handshake failed: " + handshake_ec.message(),
                        "secure_messaging_client::do_start_impl",
                        "Host: " + std::string(host) +
                            ", Port: " + std::to_string(port));
    }
    // Begin reading after successful handshake
    socket_->start_read();
    // Mark as connected
    set_connected(true);
    NETWORK_LOG_INFO("[secure_messaging_client] Connected to " +
                     std::string(host) + ":" + std::to_string(port) +
                     " (TLS/SSL secured)");
    // Invoke connected callback
    invoke_connected_callback();
    return ok();
  } catch (const std::system_error &e) {
    return error_void(error_codes::network_system::connection_failed,
                      "Failed to connect: " + std::string(e.what()),
                      "secure_messaging_client::do_start_impl",
                      "Host: " + std::string(host) +
                          ", Port: " + std::to_string(port));
  } catch (const std::exception &e) {
    return error_void(error_codes::common_errors::internal_error,
                      "Failed to connect: " + std::string(e.what()),
                      "secure_messaging_client::do_start_impl",
                      "Host: " + std::string(host) +
                          ", Port: " + std::to_string(port));
  }
}
References kcenon::network::error_codes::network_system::connection_failed, kcenon::network::error_codes::network_system::connection_timeout, kcenon::network::error_void(), kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_DEBUG, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, NETWORK_LOG_WARN, and kcenon::network::ok().
do_stop_impl()
auto kcenon::network::core::secure_messaging_client::do_stop_impl () -> VoidResult private
Secure TCP-specific implementation of client stop.
Returns
Result<void> - Success if stopped, or error
Definition at line 371 of file secure_messaging_client.cpp.
{
  try {
    // Close socket safely using atomic close() method
    // This prevents data races between close and async read operations
    if (socket_) {
      socket_->close();
    }
    // Release work guard
    if (work_guard_) {
      work_guard_.reset();
    }
    // Stop io_context
    if (io_context_) {
      io_context_->stop();
    }
    // Wait for io_context task to complete
    if (io_context_future_.valid()) {
      try {
        io_context_future_.wait();
      } catch (const std::exception &e) {
        NETWORK_LOG_ERROR("[secure_messaging_client::" + client_id_ +
                          "] Exception while waiting for io_context: " +
                          std::string(e.what()));
      }
    }
    // Release resources
    socket_.reset();
    thread_pool_.reset();
    io_context_.reset();
    NETWORK_LOG_INFO("[secure_messaging_client] Disconnected.");
    return ok();
  } catch (const std::exception &e) {
    return error_void(error_codes::common_errors::internal_error,
                      "Failed to stop client: " + std::string(e.what()),
                      "secure_messaging_client::do_stop_impl",
                      "Client ID: " + client_id_);
  }
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, and kcenon::network::ok().
get_cipher_suite()
std::string kcenon::network::core::secure_messaging_client::get_cipher_suite () const export
Get the negotiated cipher suite.
Returns
Cipher suite name
get_peer_certificate_subject()
std::optional< std::string > kcenon::network::core::secure_messaging_client::get_peer_certificate_subject () const export
Get peer certificate information.
Returns
Peer certificate subject name, or empty if not available
get_protocol_version()
std::string kcenon::network::core::secure_messaging_client::get_protocol_version () const export
Get the negotiated TLS protocol version.
Returns
Protocol version string
get_state()
connection_state kcenon::network::core::secure_messaging_client::get_state () const export noexcept
Get the current connection state.
Returns
Current connection state
invoke_connected_callback()
auto kcenon::network::core::secure_messaging_client::invoke_connected_callback () -> void private
Invokes the connected callback.
Definition at line 229 of file secure_messaging_client.cpp.
{
  callbacks_.invoke<to_index(callback_index::connected)>();
}
References kcenon::network::to_index().
invoke_disconnected_callback()
auto kcenon::network::core::secure_messaging_client::invoke_disconnected_callback () -> void private
Invokes the disconnected callback.
Definition at line 233 of file secure_messaging_client.cpp.
{
  callbacks_.invoke<to_index(callback_index::disconnected)>();
}
References kcenon::network::to_index().
invoke_error_callback()
auto kcenon::network::core::secure_messaging_client::invoke_error_callback (std::error_code ec) -> void private
Invokes the error callback.
Definition at line 237 of file secure_messaging_client.cpp.
{
  callbacks_.invoke<to_index(callback_index::error)>(ec);
}
References kcenon::network::to_index().
invoke_receive_callback()
auto kcenon::network::core::secure_messaging_client::invoke_receive_callback (const std::vector< uint8_t > & data) -> void private
Invokes the receive callback.
Definition at line 225 of file secure_messaging_client.cpp.
{
  callbacks_.invoke<to_index(callback_index::receive)>(data);
}
References kcenon::network::to_index().
is_connected() [1/2]
bool kcenon::network::core::secure_messaging_client::is_connected () const export noexcept
Check if the client is connected and TLS handshake completed.
Returns
true if securely connected
is_connected() [2/2]
auto kcenon::network::core::secure_messaging_client::is_connected () const -> bool noexcept
Checks if the client is connected to the server.
Returns
true if connected, false otherwise.
Definition at line 167 of file secure_messaging_client.cpp.
{
  return is_connected_.load(std::memory_order_acquire);
}
References is_connected_.
is_running() [1/2]
bool kcenon::network::core::secure_messaging_client::is_running () const export noexcept
Check if the client is running.
Returns
true if running
is_running() [2/2]
auto kcenon::network::core::secure_messaging_client::is_running () const -> bool noexcept
Checks if the client is currently running.
Returns
true if running, false otherwise.
Definition at line 163 of file secure_messaging_client.cpp.
{
  return lifecycle_.is_running();
}
References kcenon::network::utils::lifecycle_manager::is_running(), and lifecycle_.
on_error()
auto kcenon::network::core::secure_messaging_client::on_error (std::error_code ec) -> void private
Callback for handling socket errors.
Parameters
ec The std::error_code describing the error.
Definition at line 455 of file secure_messaging_client.cpp.
{
  NETWORK_LOG_ERROR("[secure_messaging_client] Socket error: " + ec.message());
  // Invoke error callback
  invoke_error_callback(ec);
  // Invoke disconnected callback if was connected
  if (is_connected()) {
    invoke_disconnected_callback();
  }
  // Mark connection as lost
  set_connected(false);
}
References NETWORK_LOG_ERROR.
on_receive()
auto kcenon::network::core::secure_messaging_client::on_receive (const std::vector< uint8_t > & data) -> void private
Callback for when encrypted data arrives from the server.
Parameters
data A vector containing a chunk of received bytes.
Definition at line 442 of file secure_messaging_client.cpp.
            {
  if (!is_connected()) {
    return;
  }
  NETWORK_LOG_DEBUG("[secure_messaging_client] Received " +
                    std::to_string(data.size()) + " bytes.");
  // Invoke receive callback
  invoke_receive_callback(data);
}
References NETWORK_LOG_DEBUG.
operator=() [1/4]
secure_messaging_client & kcenon::network::core::secure_messaging_client::operator= (const secure_messaging_client &) delete
operator=() [2/4]
secure_messaging_client & kcenon::network::core::secure_messaging_client::operator= (const secure_messaging_client &) export delete
operator=() [3/4]
secure_messaging_client & kcenon::network::core::secure_messaging_client::operator= (secure_messaging_client &&) export noexcept
operator=() [4/4]
secure_messaging_client & kcenon::network::core::secure_messaging_client::operator= (secure_messaging_client &&) delete
send_packet() [1/3]
bool kcenon::network::core::secure_messaging_client::send_packet (std::span< const uint8_t > data) export
Send encrypted data.
Parameters
data The data to send
Returns
true if data was queued for sending
send_packet() [2/3]
bool kcenon::network::core::secure_messaging_client::send_packet (std::string_view data) export
Send encrypted string data.
Parameters
data The string data to send
Returns
true if data was queued for sending
send_packet() [3/3]
auto kcenon::network::core::secure_messaging_client::send_packet (std::vector< uint8_t > && data) -> VoidResult
Sends data to the connected server.
Parameters
data The buffer to send (moved for efficiency).
Returns
Result<void> - Success if data queued for send, or error with code:
error_codes::network_system::connection_closed if not connected
error_codes::network_system::send_failed for other failures
Definition at line 179 of file secure_messaging_client.cpp.
{
  if (!is_connected_.load(std::memory_order_acquire)) {
    return error_void(
        error_codes::network_system::connection_closed,
        "Not connected",
        "secure_messaging_client::send_packet");
  }
  if (data.empty()) {
    return error_void(
        error_codes::common_errors::invalid_argument,
        "Data cannot be empty",
        "secure_messaging_client::send_packet");
  }
  return do_send_impl(std::move(data));
}
References kcenon::network::error_codes::network_system::connection_closed, kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::invalid_argument.
set_connected()
auto kcenon::network::core::secure_messaging_client::set_connected (bool connected) -> void private
Sets the connected state.
Parameters
connected The new connection state.
Definition at line 221 of file secure_messaging_client.cpp.
{
  is_connected_.store(connected, std::memory_order_release);
}
References kcenon::network::core::connected.
set_connected_callback()
auto kcenon::network::core::secure_messaging_client::set_connected_callback (connected_callback_t callback) -> void
Sets the callback for connection established.
Parameters
callback Function called when connection is established.
Definition at line 205 of file secure_messaging_client.cpp.
{
  callbacks_.set<to_index(callback_index::connected)>(std::move(callback));
}
References kcenon::network::to_index().
set_connection_callback()
void kcenon::network::core::secure_messaging_client::set_connection_callback (connection_callback callback) export
Set connection callback (called after TLS handshake)
Parameters
callback Function to call when securely connected
set_data_callback()
void kcenon::network::core::secure_messaging_client::set_data_callback (data_callback callback) export
Set data received callback.
Parameters
callback Function to call when decrypted data is received
set_disconnected_callback()
auto kcenon::network::core::secure_messaging_client::set_disconnected_callback (disconnected_callback_t callback) -> void
Sets the callback for disconnection.
Parameters
callback Function called when disconnected.
Definition at line 209 of file secure_messaging_client.cpp.
{
  callbacks_.set<to_index(callback_index::disconnected)>(std::move(callback));
}
References kcenon::network::to_index().
set_disconnection_callback()
void kcenon::network::core::secure_messaging_client::set_disconnection_callback (disconnection_callback callback) export
Set disconnection callback.
Parameters
callback Function to call when disconnected
set_error_callback() [1/2]
void kcenon::network::core::secure_messaging_client::set_error_callback (error_callback callback) export
Set error callback.
Parameters
callback Function to call on errors
set_error_callback() [2/2]
auto kcenon::network::core::secure_messaging_client::set_error_callback (error_callback_t callback) -> void
Sets the callback for errors.
Parameters
callback Function called when an error occurs.
Definition at line 213 of file secure_messaging_client.cpp.
{
  callbacks_.set<to_index(callback_index::error)>(std::move(callback));
}
References kcenon::network::to_index().
set_receive_callback()
auto kcenon::network::core::secure_messaging_client::set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received data.
Parameters
callback Function called when data is received.
Definition at line 201 of file secure_messaging_client.cpp.
{
  callbacks_.set<to_index(callback_index::receive)>(std::move(callback));
}
References kcenon::network::to_index().
start_client() [1/2]
bool kcenon::network::core::secure_messaging_client::start_client (std::string_view host, uint16_t port) export
Start the client and connect securely.
Parameters
host The host address to connect to
port The port number to connect to
Returns
true if connection initiated successfully
start_client() [2/2]
auto kcenon::network::core::secure_messaging_client::start_client (std::string_view host, unsigned short port) -> VoidResult
Starts the client and connects to the specified host and port.
Parameters
host The remote hostname or IP address.
port The remote port number to connect.
Returns
Result<void> - Success if client started, or error with code:
error_codes::network_system::client_already_running if already running
error_codes::common_errors::invalid_argument if empty host
error_codes::common_errors::internal_error for other failures
Definition at line 102 of file secure_messaging_client.cpp.
                  {
  if (lifecycle_.is_running()) {
    return error_void(
        error_codes::common_errors::already_exists,
        "Client is already running",
        "secure_messaging_client::start_client");
  }
  if (host.empty()) {
    return error_void(
        error_codes::common_errors::invalid_argument,
        "Host cannot be empty",
        "secure_messaging_client::start_client");
  }
  if (!lifecycle_.try_start()) {
    return error_void(
        error_codes::common_errors::already_exists,
        "Client is already starting",
        "secure_messaging_client::start_client");
  }
  is_connected_.store(false, std::memory_order_release);
  // Call implementation
  auto result = do_start_impl(host, port);
  if (result.is_err()) {
    lifecycle_.mark_stopped();
  }
  return result;
}
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::invalid_argument.
stop_client() [1/2]
void kcenon::network::core::secure_messaging_client::stop_client () export
Stop the client.
stop_client() [2/2]
auto kcenon::network::core::secure_messaging_client::stop_client () -> VoidResult
Stops the client and disconnects from the server.
Returns
Result<void> - Success if client stopped, or error with code:
error_codes::common_errors::internal_error for failures
Definition at line 136 of file secure_messaging_client.cpp.
{
  if (!lifecycle_.is_running()) {
    return ok();
  }
  if (!lifecycle_.prepare_stop()) {
    return ok(); // Already stopping or not running
  }
  is_connected_.store(false, std::memory_order_release);
  // Call implementation
  auto result = do_stop_impl();
  // Signal stop completion
  lifecycle_.mark_stopped();
  // Invoke disconnected callback
  invoke_disconnected_callback();
  return result;
}
References kcenon::network::ok().
Referenced by ~secure_messaging_client().
wait_for_stop() [1/2]
auto kcenon::network::core::secure_messaging_client::wait_for_stop () -> void
Blocks until stop_client() is called.
Definition at line 159 of file secure_messaging_client.cpp.
{
  lifecycle_.wait_for_stop();
}
wait_for_stop() [2/2]
bool kcenon::network::core::secure_messaging_client::wait_for_stop (std::chrono::milliseconds timeout = std::chrono::milliseconds(5000)) export
Wait for the client to stop.
Parameters
timeout Maximum wait time
Returns
true if stopped within timeout
Member Data Documentation
callbacks_
callbacks_t kcenon::network::core::secure_messaging_client::callbacks_ private
Callback manager.
Definition at line 310 of file secure_messaging_client.h.
client_id_
std::string kcenon::network::core::secure_messaging_client::client_id_ private
Client identifier.
Definition at line 308 of file secure_messaging_client.h.
Referenced by client_id().
io_context_
std::unique_ptr<asio::io_context> kcenon::network::core::secure_messaging_client::io_context_ private
The I/O context for async ops.
Definition at line 314 of file secure_messaging_client.h.
io_context_future_
std::future<void> kcenon::network::core::secure_messaging_client::io_context_future_ private
Future for io_context run task.
Definition at line 321 of file secure_messaging_client.h.
is_connected_
std::atomic<bool> kcenon::network::core::secure_messaging_client::is_connected_ {false} private
Connection state.
Definition at line 311 of file secure_messaging_client.h.
{false};
Referenced by is_connected().
lifecycle_
utils::lifecycle_manager kcenon::network::core::secure_messaging_client::lifecycle_ private
Lifecycle state manager.
Definition at line 309 of file secure_messaging_client.h.
Referenced by is_running(), and ~secure_messaging_client().
pimpl_
std::unique_ptr<impl> kcenon::network::core::secure_messaging_client::pimpl_ export private
Definition at line 266 of file ssl.cppm.
socket_
std::shared_ptr<internal::secure_tcp_socket> kcenon::network::core::secure_messaging_client::socket_ private
The secure TCP socket for this connection.
Definition at line 327 of file secure_messaging_client.h.
ssl_context_
std::unique_ptr<asio::ssl::context> kcenon::network::core::secure_messaging_client::ssl_context_ private
SSL context for encryption.
Definition at line 324 of file secure_messaging_client.h.
Referenced by secure_messaging_client().
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::secure_messaging_client::thread_pool_ private
Thread pool for async operations.
Definition at line 319 of file secure_messaging_client.h.
verify_cert_
bool kcenon::network::core::secure_messaging_client::verify_cert_ {true} private
Whether to verify server certificate.
Definition at line 329 of file secure_messaging_client.h.
{true};
Referenced by secure_messaging_client().
work_guard_
std::unique_ptr<asio::executor_work_guard<asio::io_context::executor_type> > kcenon::network::core::secure_messaging_client::work_guard_ private
Keeps io_context running.
Definition at line 316 of file secure_messaging_client.h.
The documentation for this class was generated from the following files:
src/internal/core/secure_messaging_client.h
src/modules/ssl.cppm
src/core/secure_messaging_client.cpp