Network System: kcenon::network::core::http_server Class Reference
kcenon::network::core::http_server Class Reference
HTTP/1.1 server built on top of messaging_server.
#include <http_server.h>
Public Member Functions
http_server (const std::string &server_id)
Construct HTTP server with server ID.
~http_server ()
Destructor - stops server if running.
auto start (unsigned short port) -> VoidResult
Start HTTP server on specified port.
auto stop () -> VoidResult
Stop HTTP server.
auto wait_for_stop () -> void
Wait for server to stop (blocking)
auto get (const std::string &pattern, http_handler handler) -> void
Register GET route handler.
auto post (const std::string &pattern, http_handler handler) -> void
Register POST route handler.
auto put (const std::string &pattern, http_handler handler) -> void
Register PUT route handler.
auto del (const std::string &pattern, http_handler handler) -> void
Register DELETE route handler.
auto patch (const std::string &pattern, http_handler handler) -> void
Register PATCH route handler.
auto head (const std::string &pattern, http_handler handler) -> void
Register HEAD route handler.
auto options (const std::string &pattern, http_handler handler) -> void
Register OPTIONS route handler.
auto set_not_found_handler (http_handler handler) -> void
Set custom 404 Not Found handler.
auto set_error_handler (http_handler handler) -> void
Set custom 500 Internal Server Error handler.
auto set_error_handler (internal::http_error_code code, error_handler handler) -> void
Set custom error handler for specific HTTP error code.
auto set_default_error_handler (error_handler handler) -> void
Set default error handler for all unhandled error codes.
auto set_request_timeout (std::chrono::milliseconds timeout) -> void
Set request timeout duration.
auto set_json_error_responses (bool enable) -> void
Enable JSON format for error responses.
auto set_compression_enabled (bool enable) -> void
Enable automatic response compression.
auto set_compression_threshold (size_t threshold_bytes) -> void
Set minimum response size for compression.
Private Member Functions
auto register_route (internal::http_method method, const std::string &pattern, http_handler handler) -> void
Register route with method and pattern.
auto find_route (internal::http_method method, const std::string &path, std::map< std::string, std::string > &path_params) const -> const http_route *
Find matching route for request.
auto handle_request (const std::vector< uint8_t > &request_data) -> std::vector< uint8_t >
Handle incoming HTTP request.
auto process_http_request (const internal::http_request &request) -> internal::http_response
Process HTTP request and generate response object.
auto should_close_connection (const internal::http_request &request, const internal::http_response &response) const -> bool
Determine if connection should be closed after response.
auto create_error_response (int status_code, const std::string &message) -> internal::http_response
Create default error response.
auto apply_compression (const internal::http_request &request, internal::http_response &response) -> void
Apply compression to response if appropriate.
auto choose_compression_algorithm (const std::string &accept_encoding) const -> utils::compression_algorithm
Determine compression algorithm from Accept-Encoding header.
auto build_error_response (const internal::http_error &error) -> internal::http_response
Build error response using registered handlers.
Static Private Member Functions
static auto pattern_to_regex (const std::string &pattern, std::vector< std::string > &param_names) -> std::string
Convert route pattern to regex pattern.
Private Attributes
std::shared_ptr< messaging_server > tcp_server_
std::vector< http_route > routes_
std::mutex routes_mutex_
http_handler not_found_handler_
http_handler error_handler_
std::map< std::shared_ptr< session::messaging_session >, http_request_buffer > session_buffers_
std::mutex buffers_mutex_
bool compression_enabled_ = false
size_t compression_threshold_ = 1024
std::mutex compression_mutex_
std::map< internal::http_error_code, error_handler > error_handlers_
std::mutex error_handlers_mutex_
error_handler default_error_handler_
bool use_json_errors_ = false
std::chrono::milliseconds request_timeout_ {30000}
Detailed Description
HTTP/1.1 server built on top of messaging_server.
Thread Safety
All public methods are thread-safe
Routes can be registered before or after server starts
Multiple requests are handled concurrently
Route handlers should be thread-safe
Features
HTTP/1.1 protocol support
GET, POST, PUT, DELETE, HEAD, OPTIONS, PATCH methods
Route pattern matching with path parameters (e.g., /users/:id)
Query parameter parsing
Request body handling
Automatic Content-Length header
Custom error handlers (404, 500, etc.)
Middleware support (future)
Usage Example
auto server = std::make_shared<http_server>("my_http_server");
// Register routes
server->get("/", [](const http_request_context& ctx) {
    http_response response;
    response.status_code = 200;
    response.set_body_string("Hello, World!");
    response.set_header("Content-Type", "text/plain");
    return response;
});
server->get("/users/:id", [](const http_request_context& ctx) {
    auto user_id = ctx.get_path_param("id").value_or("unknown");
    http_response response;
    response.status_code = 200;
    response.set_body_string("User ID: " + user_id);
    response.set_header("Content-Type", "text/plain");
    return response;
});
// Start server
server->start(8080);
server->wait_for_stop();
Route Patterns
Static routes: /users, /api/v1/products
Parameter routes: /users/:id, /products/:category/:id
Regex support for complex patterns
Limitations
Only HTTP/1.1 supported (no HTTP/2)
No chunked transfer encoding
No compression support
No file upload support (multipart/form-data)
No cookie management
Definition at line 234 of file http_server.h.
Constructor & Destructor Documentation
http_server()
kcenon::network::core::http_server::http_server (const std::string & server_id) explicit
Construct HTTP server with server ID.
Parameters
server_id Server identifier for logging
Definition at line 161 of file http_server.cpp.
    : tcp_server_(std::make_shared<messaging_server>(server_id)) {
  // Set up default 404 handler
  not_found_handler_ =
      [this](const http_request_context &) -> internal::http_response {
    return create_error_response(404, "Not Found");
  };
  // Set up default 500 handler
  error_handler_ =
      [this](const http_request_context &) -> internal::http_response {
    return create_error_response(500, "Internal Server Error");
  };
}
References create_error_response(), error_handler_, and not_found_handler_.
~http_server()
kcenon::network::core::http_server::~http_server ()
Destructor - stops server if running.
Definition at line 176 of file http_server.cpp.
{
  if (tcp_server_) {
    (void)tcp_server_->stop_server();
  }
}
References tcp_server_.
Member Function Documentation
apply_compression()
auto kcenon::network::core::http_server::apply_compression (const internal::http_request & request, internal::http_response & response) -> void private
Apply compression to response if appropriate.
Parameters
request HTTP request (for Accept-Encoding header)
response HTTP response to potentially compress
Definition at line 656 of file http_server.cpp.
{
  // Check if compression is enabled and response size meets threshold
  {
    std::lock_guard<std::mutex> lock(compression_mutex_);
    if (!compression_enabled_) {
      return; // Compression disabled
    }
    if (response.body.size() < compression_threshold_) {
      return; // Response too small to compress
    }
  }
  // Get Accept-Encoding header from request
  auto accept_encoding = request.get_header("Accept-Encoding");
  if (!accept_encoding) {
    return; // Client doesn't support compression
  }
  // Determine best compression algorithm
  auto algorithm = choose_compression_algorithm(*accept_encoding);
  if (algorithm == utils::compression_algorithm::none) {
    return; // No supported compression algorithm
  }
  // Store original size for logging
  const size_t original_size = response.body.size();
  // Create compression pipeline for the selected algorithm
  auto pipeline = std::make_shared<utils::compression_pipeline>(algorithm);
  // Compress response body
  auto compressed_result = pipeline->compress(response.body);
  if (compressed_result.is_err()) {
    // Compression failed - send uncompressed
    // TODO: Add error logging when needed
    return;
  }
  // Get compressed size before moving
  const size_t compressed_size = compressed_result.value().size();
  // Replace response body with compressed data
  response.body = std::move(compressed_result.value());
  // Set Content-Encoding header to indicate compression
  if (algorithm == utils::compression_algorithm::gzip) {
    response.set_header("Content-Encoding", "gzip");
  } else if (algorithm == utils::compression_algorithm::deflate) {
    response.set_header("Content-Encoding", "deflate");
  }
  // Update Content-Length header with new compressed size
  response.set_header("Content-Length", std::to_string(response.body.size()));
  // Suppress unused variable warnings
  (void)original_size;
  (void)compressed_size;
}
References kcenon::network::utils::deflate, kcenon::network::utils::gzip, and kcenon::network::utils::none.
build_error_response()
auto kcenon::network::core::http_server::build_error_response (const internal::http_error & error) -> internal::http_response private
Build error response using registered handlers.
Parameters
error Error details
Returns
HTTP response
Definition at line 341 of file http_server.cpp.
{
  // Check for specific error handler
  {
    std::lock_guard<std::mutex> lock(error_handlers_mutex_);
    auto it = error_handlers_.find(error.code);
    if (it != error_handlers_.end()) {
      return it->second(error);
    }
    // Check for default error handler
    if (default_error_handler_) {
      return default_error_handler_(error);
    }
  }
  // Use built-in error response builder
  if (use_json_errors_) {
    return internal::http_error_response::build_json_error(error);
  }
  return internal::http_error_response::build_html_error(error);
}
References kcenon::network::internal::http_error_response::build_html_error(), kcenon::network::internal::http_error_response::build_json_error(), and kcenon::network::error.
choose_compression_algorithm()
auto kcenon::network::core::http_server::choose_compression_algorithm (const std::string & accept_encoding) const -> utils::compression_algorithm private
Determine compression algorithm from Accept-Encoding header.
Parameters
accept_encoding Accept-Encoding header value
Returns
Best supported compression algorithm
Definition at line 631 of file http_server.cpp.
{
  // Parse Accept-Encoding header value (e.g., "gzip, deflate, br")
  // Priority: gzip > deflate > none
  // Note: We only support gzip and deflate (not br/brotli)
  // Convert to lowercase for case-insensitive comparison
  std::string accept_lower = accept_encoding;
  std::transform(accept_lower.begin(), accept_lower.end(), accept_lower.begin(),
                 [](unsigned char c) { return std::tolower(c); });
  // Check for gzip first (highest priority)
  if (accept_lower.find("gzip") != std::string::npos) {
    return utils::compression_algorithm::gzip;
  }
  // Check for deflate next
  if (accept_lower.find("deflate") != std::string::npos) {
    return utils::compression_algorithm::deflate;
  }
  // No supported compression algorithm found
  return utils::compression_algorithm::none;
}
References kcenon::network::utils::deflate, kcenon::network::utils::gzip, and kcenon::network::utils::none.
create_error_response()
auto kcenon::network::core::http_server::create_error_response (int status_code, const std::string & message) -> internal::http_response private
Create default error response.
Parameters
status_code HTTP status code
message Error message
Returns
HTTP response
Definition at line 549 of file http_server.cpp.
{
  // Create http_error from status code
  auto error = internal::http_error_response::make_error(
      static_cast<internal::http_error_code>(status_code), message);
  return build_error_response(error);
}
References kcenon::network::error, kcenon::network::internal::http_error_response::make_error(), and kcenon::network::message.
Referenced by http_server().
del()
auto kcenon::network::core::http_server::del (const std::string & pattern, http_handler handler) -> void
Register DELETE route handler.
Parameters
pattern Route pattern
handler Handler function
Definition at line 290 of file http_server.cpp.
            {
  register_route(internal::http_method::HTTP_DELETE, pattern,
                 std::move(handler));
}
References kcenon::network::internal::HTTP_DELETE.
find_route()
auto kcenon::network::core::http_server::find_route (internal::http_method method, const std::string & path, std::map< std::string, std::string > & path_params) const -> const http_route* private
Find matching route for request.
Parameters
method HTTP method
path URI path
path_params Output: extracted path parameters
Returns
Pointer to matching route or nullptr
Definition at line 380 of file http_server.cpp.
{
  // Note: routes_mutex_ is mutable, so we can lock it in const methods
  // But for now, we'll const_cast to avoid making mutex mutable
  auto &mutable_mutex = const_cast<std::mutex &>(routes_mutex_);
  std::lock_guard<std::mutex> lock(mutable_mutex);
  for (const auto &route : routes_) {
    if (route.matches(method, path, path_params)) {
      return &route;
    }
  }
  return nullptr;
}
get()
auto kcenon::network::core::http_server::get (const std::string & pattern, http_handler handler) -> void
Register GET route handler.
Parameters
pattern Route pattern (e.g., "/users/:id")
handler Handler function
Definition at line 275 of file http_server.cpp.
            {
  register_route(internal::http_method::HTTP_GET, pattern, std::move(handler));
}
References kcenon::network::internal::HTTP_GET.
handle_request()
auto kcenon::network::core::http_server::handle_request (const std::vector< uint8_t > & request_data) -> std::vector<uint8_t> private
Handle incoming HTTP request.
Parameters
request_data Raw request data
Returns
HTTP response data
Definition at line 398 of file http_server.cpp.
{
  // Parse HTTP request
  auto request_result = internal::http_parser::parse_request(request_data);
  if (request_result.is_err()) {
    // Failed to parse request - send 400 Bad Request
    auto error_response = create_error_response(400, "Bad Request");
    return internal::http_parser::serialize_response(error_response);
  }
  auto http_request = std::move(request_result.value());
  // Create request context
  http_request_context ctx;
  ctx.request = std::move(http_request);
  internal::http_response response;
  try {
    // Find matching route
    auto route =
        find_route(ctx.request.method, ctx.request.uri, ctx.path_params);
    if (route) {
      // Execute handler
      response = route->handler(ctx);
    } else {
      // No matching route - send 404
      response = not_found_handler_(ctx);
    }
  } catch (const std::exception &e) {
    // Handler threw exception - send 500
    response = error_handler_(ctx);
  } catch (...) {
    // Unknown exception - send 500
    response = error_handler_(ctx);
  }
  // Add standard headers if not present
  if (!response.get_header("Content-Length")) {
    response.set_header("Content-Length", std::to_string(response.body.size()));
  }
  if (!response.get_header("Server")) {
    response.set_header("Server", "NetworkSystem-HTTP-Server/1.0");
  }
  // Serialize and return response
  return internal::http_parser::serialize_response(response);
}
References kcenon::network::internal::http_response::body, kcenon::network::internal::http_response::get_header(), kcenon::network::internal::http_request::method, kcenon::network::internal::http_parser::parse_request(), kcenon::network::core::http_request_context::path_params, kcenon::network::core::http_request_context::request, kcenon::network::internal::http_parser::serialize_response(), kcenon::network::internal::http_response::set_header(), and kcenon::network::internal::http_request::uri.
head()
auto kcenon::network::core::http_server::head (const std::string & pattern, http_handler handler) -> void
Register HEAD route handler.
Parameters
pattern Route pattern
handler Handler function
Definition at line 302 of file http_server.cpp.
            {
  register_route(internal::http_method::HTTP_HEAD, pattern, std::move(handler));
}
References kcenon::network::internal::HTTP_HEAD.
options()
auto kcenon::network::core::http_server::options (const std::string & pattern, http_handler handler) -> void
Register OPTIONS route handler.
Parameters
pattern Route pattern
handler Handler function
Definition at line 307 of file http_server.cpp.
            {
  register_route(internal::http_method::HTTP_OPTIONS, pattern,
                 std::move(handler));
}
References kcenon::network::internal::HTTP_OPTIONS.
patch()
auto kcenon::network::core::http_server::patch (const std::string & pattern, http_handler handler) -> void
Register PATCH route handler.
Parameters
pattern Route pattern
handler Handler function
Definition at line 296 of file http_server.cpp.
            {
  register_route(internal::http_method::HTTP_PATCH, pattern,
                 std::move(handler));
}
References kcenon::network::internal::HTTP_PATCH.
pattern_to_regex()
auto kcenon::network::core::http_server::pattern_to_regex (const std::string & pattern, std::vector< std::string > & param_names) -> std::string static private
Convert route pattern to regex pattern.
Parameters
pattern Route pattern (e.g., "/users/:id")
param_names Output: parameter names
Returns
Regex pattern string
Definition at line 559 of file http_server.cpp.
                 {
  param_names.clear();
  std::ostringstream regex_str;
  regex_str << "^";
  std::size_t pos = 0;
  while (pos < pattern.length()) {
    // Look for parameter placeholder (:param_name)
    auto param_start = pattern.find(':', pos);
    if (param_start == std::string::npos) {
      // No more parameters, add remaining literal part
      auto remaining = pattern.substr(pos);
      // Escape special regex characters
      for (char c : remaining) {
        if (c == '.' || c == '*' || c == '+' || c == '?' || c == '[' ||
            c == ']' || c == '(' || c == ')' || c == '{' || c == '}' ||
            c == '^' || c == '$' || c == '|' || c == '\\') {
          regex_str << '\\';
        }
        regex_str << c;
      }
      break;
    }
    // Add literal part before parameter
    for (std::size_t i = pos; i < param_start; ++i) {
      char c = pattern[i];
      if (c == '.' || c == '*' || c == '+' || c == '?' || c == '[' ||
          c == ']' || c == '(' || c == ')' || c == '{' || c == '}' ||
          c == '^' || c == '$' || c == '|' || c == '\\') {
        regex_str << '\\';
      }
      regex_str << c;
    }
    // Find end of parameter name
    auto param_end = param_start + 1;
    while (param_end < pattern.length() &&
           (std::isalnum(pattern[param_end]) || pattern[param_end] == '_')) {
      ++param_end;
    }
    // Extract parameter name
    auto param_name =
        pattern.substr(param_start + 1, param_end - param_start - 1);
    param_names.push_back(param_name);
    // Add regex capture group for parameter (matches anything except /)
    regex_str << "([^/]+)";
    pos = param_end;
  }
  regex_str << "$";
  return regex_str.str();
}
post()
auto kcenon::network::core::http_server::post (const std::string & pattern, http_handler handler) -> void
Register POST route handler.
Parameters
pattern Route pattern
handler Handler function
Definition at line 280 of file http_server.cpp.
            {
  register_route(internal::http_method::HTTP_POST, pattern, std::move(handler));
}
References kcenon::network::internal::HTTP_POST.
process_http_request()
auto kcenon::network::core::http_server::process_http_request (const internal::http_request & request) -> internal::http_response private
Process HTTP request and generate response object.
Parameters
request Parsed HTTP request
Returns
HTTP response object
Definition at line 449 of file http_server.cpp.
{
  // Create request context
  http_request_context ctx;
  ctx.request = http_request;
  internal::http_response response;
  try {
    // Find matching route
    auto route =
        find_route(ctx.request.method, ctx.request.uri, ctx.path_params);
    if (route) {
      // Execute handler
      response = route->handler(ctx);
    } else {
      // No matching route - send 404
      response = not_found_handler_(ctx);
    }
  } catch (const std::exception &e) {
    // Handler threw exception - send 500
    response = error_handler_(ctx);
  } catch (...) {
    // Unknown exception - send 500
    response = error_handler_(ctx);
  }
  // Add standard headers if not present
  if (!response.get_header("Content-Length")) {
    response.set_header("Content-Length", std::to_string(response.body.size()));
  }
  if (!response.get_header("Server")) {
    response.set_header("Server", "NetworkSystem-HTTP-Server/1.0");
  }
  // Add Connection header based on request if not already present
  if (!response.get_header("Connection")) {
    // HTTP/1.1 defaults to keep-alive, HTTP/1.0 defaults to close
    if (http_request.version == internal::http_version::HTTP_1_0) {
      auto conn = http_request.get_header("Connection");
      if (conn && *conn == "keep-alive") {
        response.set_header("Connection", "keep-alive");
      } else {
        response.set_header("Connection", "close");
      }
    } else // HTTP/1.1
    {
      auto conn = http_request.get_header("Connection");
      if (conn && *conn == "close") {
        response.set_header("Connection", "close");
      }
      // else: keep-alive is default for HTTP/1.1
    }
  }
  // Apply compression if enabled and appropriate
  apply_compression(http_request, response);
  return response;
}
References kcenon::network::internal::http_response::body, kcenon::network::internal::http_response::get_header(), kcenon::network::internal::HTTP_1_0, kcenon::network::internal::http_request::method, kcenon::network::core::http_request_context::path_params, kcenon::network::core::http_request_context::request, kcenon::network::internal::http_response::set_header(), and kcenon::network::internal::http_request::uri.
put()
auto kcenon::network::core::http_server::put (const std::string & pattern, http_handler handler) -> void
Register PUT route handler.
Parameters
pattern Route pattern
handler Handler function
Definition at line 285 of file http_server.cpp.
            {
  register_route(internal::http_method::HTTP_PUT, pattern, std::move(handler));
}
References kcenon::network::internal::HTTP_PUT.
register_route()
auto kcenon::network::core::http_server::register_route (internal::http_method method, const std::string & pattern, http_handler handler) -> void private
Register route with method and pattern.
Parameters
method HTTP method
pattern Route pattern
handler Handler function
Definition at line 364 of file http_server.cpp.
{
  http_route route;
  route.method = method;
  route.pattern = pattern;
  route.handler = std::move(handler);
  // Convert pattern to regex
  auto regex_str = pattern_to_regex(pattern, route.param_names);
  route.regex_pattern = std::regex(regex_str);
  std::lock_guard<std::mutex> lock(routes_mutex_);
  routes_.push_back(std::move(route));
}
References kcenon::network::core::http_route::handler, kcenon::network::core::http_route::method, kcenon::network::core::http_route::param_names, kcenon::network::core::http_route::pattern, and kcenon::network::core::http_route::regex_pattern.
set_compression_enabled()
auto kcenon::network::core::http_server::set_compression_enabled (bool enable) -> void
Enable automatic response compression.
Parameters
enable True to enable compression, false to disable
Definition at line 621 of file http_server.cpp.
{
  std::lock_guard<std::mutex> lock(compression_mutex_);
  compression_enabled_ = enable;
}
set_compression_threshold()
auto kcenon::network::core::http_server::set_compression_threshold (size_t threshold_bytes) -> void
Set minimum response size for compression.
Parameters
threshold_bytes Minimum size in bytes (default: 1024)
Definition at line 626 of file http_server.cpp.
{
  std::lock_guard<std::mutex> lock(compression_mutex_);
  compression_threshold_ = threshold_bytes;
}
set_default_error_handler()
auto kcenon::network::core::http_server::set_default_error_handler (error_handler handler) -> void
Set default error handler for all unhandled error codes.
Parameters
handler Default error handler function
Definition at line 327 of file http_server.cpp.
{
  std::lock_guard<std::mutex> lock(error_handlers_mutex_);
  default_error_handler_ = std::move(handler);
}
set_error_handler() [1/2]
auto kcenon::network::core::http_server::set_error_handler (http_handler handler) -> void
Set custom 500 Internal Server Error handler.
Parameters
handler Handler function
Definition at line 317 of file http_server.cpp.
{
  error_handler_ = std::move(handler);
}
set_error_handler() [2/2]
auto kcenon::network::core::http_server::set_error_handler (internal::http_error_code code, error_handler handler) -> void
Set custom error handler for specific HTTP error code.
Parameters
code HTTP error code to handle
handler Error handler function
Definition at line 321 of file http_server.cpp.
{
  std::lock_guard<std::mutex> lock(error_handlers_mutex_);
  error_handlers_[code] = std::move(handler);
}
set_json_error_responses()
auto kcenon::network::core::http_server::set_json_error_responses (bool enable) -> void
Enable JSON format for error responses.
Parameters
enable True to use JSON, false for HTML
Definition at line 337 of file http_server.cpp.
{
  use_json_errors_ = enable;
}
set_not_found_handler()
auto kcenon::network::core::http_server::set_not_found_handler (http_handler handler) -> void
Set custom 404 Not Found handler.
Parameters
handler Handler function
Definition at line 313 of file http_server.cpp.
{
  not_found_handler_ = std::move(handler);
}
set_request_timeout()
auto kcenon::network::core::http_server::set_request_timeout (std::chrono::milliseconds timeout) -> void
Set request timeout duration.
Parameters
timeout Timeout duration
Definition at line 332 of file http_server.cpp.
            {
  request_timeout_ = timeout;
}
should_close_connection()
auto kcenon::network::core::http_server::should_close_connection (const internal::http_request & request, const internal::http_response & response) const -> bool private
Determine if connection should be closed after response.
Parameters
request HTTP request
response HTTP response
Returns
true if connection should be closed
Definition at line 512 of file http_server.cpp.
{
  // Check response Connection header first
  auto response_conn = response.get_header("Connection");
  if (response_conn) {
    std::string conn_lower = *response_conn;
    std::transform(conn_lower.begin(), conn_lower.end(), conn_lower.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    if (conn_lower == "close") {
      return true;
    }
    if (conn_lower == "keep-alive") {
      return false;
    }
  }
  // Check request Connection header
  auto request_conn = request.get_header("Connection");
  if (request_conn) {
    std::string conn_lower = *request_conn;
    std::transform(conn_lower.begin(), conn_lower.end(), conn_lower.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    if (conn_lower == "close") {
      return true;
    }
  }
  // HTTP/1.0 defaults to close unless Connection: keep-alive
  if (request.version == internal::http_version::HTTP_1_0) {
    return true;
  }
  // HTTP/1.1 defaults to keep-alive
  return false;
}
References kcenon::network::internal::http_response::get_header(), and kcenon::network::internal::HTTP_1_0.
start()
auto kcenon::network::core::http_server::start (unsigned short port) -> VoidResult
Start HTTP server on specified port.
Parameters
port Port number to listen on
Returns
Result indicating success or error
Definition at line 182 of file http_server.cpp.
{
  // Set up receive callback to handle HTTP requests with buffering
  tcp_server_->set_receive_callback(
      [this](
          std::shared_ptr<kcenon::network::session::messaging_session> session,
          const std::vector<uint8_t> &data) {
        if (!session) {
          return;
        }
        // Get or create buffer for this session
        std::unique_lock<std::mutex> lock(buffers_mutex_);
        auto &buffer = session_buffers_[session];
        lock.unlock();
        // Append new data to buffer
        if (!buffer.append(data)) {
          // Buffer size limit exceeded
          lock.lock();
          session_buffers_.erase(session);
          lock.unlock();
          // Send error response
          if (buffer.data.size() > http_request_buffer::MAX_REQUEST_SIZE) {
            auto error_response =
                create_error_response(413, "Payload Too Large");
            auto response_data =
                internal::http_parser::serialize_response(error_response);
            session->send_packet(std::move(response_data));
          } else {
            auto error_response =
                create_error_response(431, "Request Header Fields Too Large");
            auto response_data =
                internal::http_parser::serialize_response(error_response);
            session->send_packet(std::move(response_data));
          }
          return;
        }
        // Check if request is complete
        if (buffer.is_complete()) {
          // Parse HTTP request
          auto request_result =
              internal::http_parser::parse_request(buffer.data);
          // Clean up buffer first
          lock.lock();
          session_buffers_.erase(session);
          lock.unlock();
          if (request_result.is_err()) {
            // Failed to parse - send 400 Bad Request
            auto error_response = create_error_response(400, "Bad Request");
            auto response_data =
                internal::http_parser::serialize_response(error_response);
            session->send_packet(std::move(response_data));
            // Close connection on parse error
            session->stop_session();
            return;
          }
          auto http_request = std::move(request_result.value());
          // Process request and generate response
          auto response = process_http_request(http_request);
          // Determine if connection should be closed
          bool close_conn = should_close_connection(http_request, response);
          // Serialize and send response
          auto response_data =
              internal::http_parser::serialize_response(response);
          session->send_packet(std::move(response_data));
          // Close connection if required
          if (close_conn) {
            // Give time for response to be sent before closing
            // In a production system, we would wait for send completion
            // callback
            session->stop_session();
          }
        }
        // Otherwise, wait for more data
      });
  // Start TCP server
  return tcp_server_->start_server(port);
}
References kcenon::network::core::http_request_buffer::MAX_REQUEST_SIZE, kcenon::network::internal::http_parser::parse_request(), and kcenon::network::internal::http_parser::serialize_response().
stop()
auto kcenon::network::core::http_server::stop () -> VoidResult
Stop HTTP server.
Returns
Result indicating success or error
Definition at line 271 of file http_server.cpp.
{ return tcp_server_->stop_server(); }
wait_for_stop()
auto kcenon::network::core::http_server::wait_for_stop () -> void
Wait for server to stop (blocking)
Definition at line 273 of file http_server.cpp.
{ tcp_server_->wait_for_stop(); }
Member Data Documentation
buffers_mutex_
std::mutex kcenon::network::core::http_server::buffers_mutex_ private
Definition at line 459 of file http_server.h.
compression_enabled_
bool kcenon::network::core::http_server::compression_enabled_ = false private
Definition at line 462 of file http_server.h.
compression_mutex_
std::mutex kcenon::network::core::http_server::compression_mutex_ private
Definition at line 464 of file http_server.h.
compression_threshold_
size_t kcenon::network::core::http_server::compression_threshold_ = 1024 private
Definition at line 463 of file http_server.h.
default_error_handler_
error_handler kcenon::network::core::http_server::default_error_handler_ private
Definition at line 469 of file http_server.h.
error_handler_
http_handler kcenon::network::core::http_server::error_handler_ private
Definition at line 455 of file http_server.h.
Referenced by http_server().
error_handlers_
std::map<internal::http_error_code, error_handler> kcenon::network::core::http_server::error_handlers_ private
Definition at line 467 of file http_server.h.
error_handlers_mutex_
std::mutex kcenon::network::core::http_server::error_handlers_mutex_ private
Definition at line 468 of file http_server.h.
not_found_handler_
http_handler kcenon::network::core::http_server::not_found_handler_ private
Definition at line 454 of file http_server.h.
Referenced by http_server().
request_timeout_
std::chrono::milliseconds kcenon::network::core::http_server::request_timeout_ {30000} private
Definition at line 471 of file http_server.h.
{30000};  // 30 seconds default
routes_
std::vector<http_route> kcenon::network::core::http_server::routes_ private
Definition at line 452 of file http_server.h.
routes_mutex_
std::mutex kcenon::network::core::http_server::routes_mutex_ private
Definition at line 453 of file http_server.h.
session_buffers_
std::map<std::shared_ptr<session::messaging_session>, http_request_buffer> kcenon::network::core::http_server::session_buffers_ private
Definition at line 458 of file http_server.h.
tcp_server_
std::shared_ptr<messaging_server> kcenon::network::core::http_server::tcp_server_ private
Definition at line 451 of file http_server.h.
Referenced by ~http_server().
use_json_errors_
bool kcenon::network::core::http_server::use_json_errors_ = false private
Definition at line 470 of file http_server.h.
The documentation for this class was generated from the following files:
src/internal/http/http_server.h
src/http/http_server.cpp