Network System: kcenon::network::unified::adapters::quic_connection_adapter Class Reference
kcenon::network::unified::adapters::quic_connection_adapter Class Reference
Adapter that wraps QUIC connection to implement i_connection.
#include <quic_connection_adapter.h>
Public Member Functions
quic_connection_adapter (const protocol::quic::quic_config &config, std::string_view connection_id)
Constructs an adapter with QUIC configuration.
~quic_connection_adapter () override
Destructor ensures proper cleanup.
quic_connection_adapter (const quic_connection_adapter &)=delete
quic_connection_adapter & operator= (const quic_connection_adapter &)=delete
quic_connection_adapter (quic_connection_adapter &&)=delete
quic_connection_adapter & operator= (quic_connection_adapter &&)=delete
auto send (std::span< const std::byte > data) -> VoidResult override
Sends raw data to the remote endpoint.
auto send (std::vector< uint8_t > &&data) -> VoidResult override
Sends data from a uint8_t vector.
auto is_connected () const noexcept -> bool override
Checks if the transport is currently connected.
auto id () const noexcept -> std::string_view override
Gets the unique identifier for this transport/connection.
auto remote_endpoint () const noexcept -> endpoint_info override
Gets the remote endpoint information.
auto local_endpoint () const noexcept -> endpoint_info override
Gets the local endpoint information.
auto connect (const endpoint_info &endpoint) -> VoidResult override
Connects to a remote endpoint using host/port.
auto connect (std::string_view url) -> VoidResult override
Connects to a remote endpoint using URL.
auto close () noexcept -> void override
Closes the connection gracefully.
auto set_callbacks (connection_callbacks callbacks) -> void override
Sets all connection callbacks at once.
auto set_options (connection_options options) -> void override
Sets connection options.
auto set_timeout (std::chrono::milliseconds timeout) -> void override
Sets the connection timeout.
auto is_connecting () const noexcept -> bool override
Checks if the connection is in the process of connecting.
auto wait_for_stop () -> void override
Blocks until the component has stopped.
Public Member Functions inherited from kcenon::network::unified::i_connection
~i_connection () override=default
Virtual destructor.
i_connection (const i_connection &)=delete
i_connection & operator= (const i_connection &)=delete
i_connection (i_connection &&)=default
i_connection & operator= (i_connection &&)=default
Public Member Functions inherited from kcenon::network::unified::i_transport
virtual ~i_transport ()=default
Virtual destructor for proper cleanup of derived classes.
i_transport (const i_transport &)=delete
i_transport & operator= (const i_transport &)=delete
i_transport (i_transport &&)=default
i_transport & operator= (i_transport &&)=default
Private Member Functions
auto io_thread_func () -> void
I/O processing thread function.
auto process_outgoing () -> void
Process outgoing packets.
auto process_incoming () -> void
Process incoming packets.
auto handle_state_change () -> void
Handle connection state changes.
auto parse_url (std::string_view url) -> std::pair< std::string, uint16_t >
Parse URL to extract host and port.
Private Attributes
std::string connection_id_
protocol::quic::quic_config config_
std::unique_ptr< protocols::quic::connection > quic_conn_
int socket_fd_ {-1}
std::thread io_thread_
std::atomic< bool > running_ {false}
std::atomic< bool > stop_requested_ {false}
std::mutex callbacks_mutex_
connection_callbacks callbacks_
std::mutex endpoint_mutex_
endpoint_info remote_endpoint_
endpoint_info local_endpoint_
std::atomic< bool > is_connecting_ {false}
std::atomic< bool > is_connected_ {false}
connection_options options_
std::mutex stop_mutex_
std::condition_variable stop_cv_
std::mutex send_queue_mutex_
std::deque< std::vector< uint8_t > > send_queue_
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::unified::i_connection
i_connection ()=default
Default constructor (only for derived classes)
Protected Member Functions inherited from kcenon::network::unified::i_transport
i_transport ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps QUIC connection to implement i_connection.
This adapter bridges the QUIC protocol implementation with the unified interface, enabling protocol factory functions to return i_connection while using the QUIC connection underneath.
QUIC Specifics
Uses Stream 0 (bidirectional) for default data transfer
Supports multiplexed streams internally
Built-in TLS 1.3 encryption
Connection migration support
Thread Safety
Thread-safe. All methods can be called from any thread.
Ownership
The adapter owns the underlying QUIC connection and manages its lifecycle.
Definition at line 42 of file quic_connection_adapter.h.
Constructor & Destructor Documentation
quic_connection_adapter() [1/3]
kcenon::network::unified::adapters::quic_connection_adapter::quic_connection_adapter (const protocol::quic::quic_config & config, std::string_view connection_id)
Constructs an adapter with QUIC configuration.
Parameters
config QUIC configuration options
connection_id Unique identifier for this connection
Definition at line 70 of file quic_connection_adapter.cpp.
    : connection_id_(connection_id)
    , config_(config)
{
}
References config.
~quic_connection_adapter()
kcenon::network::unified::adapters::quic_connection_adapter::~quic_connection_adapter () override
Destructor ensures proper cleanup.
Definition at line 78 of file quic_connection_adapter.cpp.
{
    close();
}
References close().
quic_connection_adapter() [2/3]
kcenon::network::unified::adapters::quic_connection_adapter::quic_connection_adapter (const quic_connection_adapter &) delete
quic_connection_adapter() [3/3]
kcenon::network::unified::adapters::quic_connection_adapter::quic_connection_adapter (quic_connection_adapter &&) delete
Member Function Documentation
close()
auto kcenon::network::unified::adapters::quic_connection_adapter::close () -> void override virtual noexcept
Closes the connection gracefully.
Behavior
Initiates graceful shutdown
Pending sends may be completed before close
Triggers on_disconnected callback when fully closed
Thread Safety
Thread-safe. Safe to call multiple times.
Note
After close(), is_connected() returns false and send() returns error.
Implements kcenon::network::unified::i_connection.
Definition at line 264 of file quic_connection_adapter.cpp.
{
    stop_requested_ = true;
    if (quic_conn_ && quic_conn_->is_established()) {
        (void)quic_conn_->close(0, "Connection closed by client");
    }
    if (io_thread_.joinable()) {
        io_thread_.join();
    }
    if (socket_fd_ >= 0) {
        close_socket(socket_fd_);
        socket_fd_ = -1;
    }
    quic_conn_.reset();
    is_connected_ = false;
    is_connecting_ = false;
    running_ = false;
    {
        std::lock_guard lock(stop_mutex_);
    }
    stop_cv_.notify_all();
}
References io_thread_, is_connected_, is_connecting_, quic_conn_, running_, socket_fd_, stop_cv_, stop_mutex_, and stop_requested_.
Referenced by ~quic_connection_adapter().
connect() [1/2]
auto kcenon::network::unified::adapters::quic_connection_adapter::connect (const endpoint_info & endpoint) -> VoidResult nodiscard override virtual
Connects to a remote endpoint using host/port.
Parameters
endpoint The remote endpoint to connect to
Returns
VoidResult indicating success or failure
Behavior
Initiates connection to the specified endpoint
May block until connection is established (sync mode)
May return immediately and notify via callback (async mode)
Error Conditions
Returns error if already connected
Returns error if connection fails
Returns error if host resolution fails
Returns error if connection timeout expires
Thread Safety
Thread-safe. Only one connect operation can succeed at a time.
Implements kcenon::network::unified::i_connection.
Definition at line 157 of file quic_connection_adapter.cpp.
{
    if (is_connected_.load() || running_.load()) {
        return error_void(
            static_cast<int>(std::errc::already_connected),
            "Already connected or connecting"
        );
    }
    {
        std::lock_guard lock(endpoint_mutex_);
        remote_endpoint_ = endpoint;
    }
    // Create UDP socket
#ifdef _WIN32
    WSADATA wsaData;
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
        return error_void(
            static_cast<int>(std::errc::io_error),
            "Failed to initialize Winsock"
        );
    }
#endif
    socket_fd_ = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (socket_fd_ < 0) {
        return error_void(
            static_cast<int>(std::errc::io_error),
            "Failed to create UDP socket"
        );
    }
    if (!set_nonblocking(socket_fd_)) {
        close_socket(socket_fd_);
        socket_fd_ = -1;
        return error_void(
            static_cast<int>(std::errc::io_error),
            "Failed to set socket to non-blocking mode"
        );
    }
    // Create QUIC connection (client side)
    auto initial_dcid = generate_random_cid();
    quic_conn_ = std::make_unique<protocols::quic::connection>(false, initial_dcid);
    // Set transport parameters from config
    protocols::quic::transport_parameters local_params;
    local_params.initial_max_data = config_.initial_max_data;
    local_params.initial_max_stream_data_bidi_local = config_.initial_max_stream_data_bidi;
    local_params.initial_max_stream_data_bidi_remote = config_.initial_max_stream_data_bidi;
    local_params.initial_max_stream_data_uni = config_.initial_max_stream_data_uni;
    local_params.initial_max_streams_bidi = config_.max_bidi_streams;
    local_params.initial_max_streams_uni = config_.max_uni_streams;
    if (config_.idle_timeout.count() > 0) {
        local_params.max_idle_timeout =
            static_cast<uint64_t>(config_.idle_timeout.count());
    }
    quic_conn_->set_local_params(local_params);
    // Enable PMTUD if configured
    if (config_.enable_pmtud) {
        quic_conn_->enable_pmtud();
    }
    // Start handshake
    std::string server_name = config_.server_name;
    if (server_name.empty()) {
        server_name = endpoint.host;
    }
    auto hs_result = quic_conn_->start_handshake(server_name);
    if (!hs_result.is_ok()) {
        quic_conn_.reset();
        close_socket(socket_fd_);
        socket_fd_ = -1;
        return error_void(
            static_cast<int>(std::errc::connection_refused),
            "Failed to start QUIC handshake"
        );
    }
    is_connecting_ = true;
    running_ = true;
    stop_requested_ = false;
    // Start I/O thread
    io_thread_ = std::thread(&quic_connection_adapter::io_thread_func, this);
    return ok();
}
References kcenon::network::error_void(), kcenon::network::protocols::quic::transport_parameters::initial_max_data, kcenon::network::protocols::quic::transport_parameters::initial_max_stream_data_bidi_local, kcenon::network::protocols::quic::transport_parameters::initial_max_stream_data_bidi_remote, kcenon::network::protocols::quic::transport_parameters::initial_max_stream_data_uni, kcenon::network::protocols::quic::transport_parameters::initial_max_streams_bidi, kcenon::network::protocols::quic::transport_parameters::initial_max_streams_uni, io_thread_func(), kcenon::network::protocols::quic::transport_parameters::max_idle_timeout, and kcenon::network::ok().
connect() [2/2]
auto kcenon::network::unified::adapters::quic_connection_adapter::connect (std::string_view url) -> VoidResult nodiscard override virtual
Connects to a remote endpoint using URL.
Parameters
url The URL to connect to (e.g., "wss://example.com/ws")
Returns
VoidResult indicating success or failure
This overload is primarily for URL-based protocols like WebSocket and HTTP. For socket-based protocols, use the endpoint_info overload.
Error Conditions
Same as connect(endpoint_info) plus:
Returns error if URL is malformed
Returns error if protocol is not supported
Implements kcenon::network::unified::i_connection.
Definition at line 251 of file quic_connection_adapter.cpp.
{
    auto [host, port] = parse_url(url);
    if (host.empty() || port == 0) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "Invalid QUIC URL format (expected: quic://host:port or host:port)"
        );
    }
    return connect(endpoint_info{host, port});
}
References kcenon::network::error_void().
handle_state_change()
auto kcenon::network::unified::adapters::quic_connection_adapter::handle_state_change () -> void private
Handle connection state changes.
Definition at line 489 of file quic_connection_adapter.cpp.
{
    if (!quic_conn_) {
        return;
    }
    bool was_connecting = is_connecting_.load();
    bool is_now_established = quic_conn_->is_established();
    if (was_connecting && is_now_established) {
        is_connecting_ = false;
        is_connected_ = true;
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_connected) {
            callbacks_.on_connected();
        }
    }
    if (quic_conn_->is_draining() || quic_conn_->is_closed()) {
        is_connected_ = false;
        auto error_code = quic_conn_->close_error_code();
        if (error_code && *error_code != 0) {
            std::lock_guard lock(callbacks_mutex_);
            if (callbacks_.on_error) {
                callbacks_.on_error(std::make_error_code(std::errc::connection_reset));
            }
        }
    }
    // Process incoming data
    process_incoming();
}
id()
auto kcenon::network::unified::adapters::quic_connection_adapter::id () const -> std::string_view nodiscard override virtual noexcept
Gets the unique identifier for this transport/connection.
Returns
A string view of the transport ID
The ID is unique within the application and remains constant for the lifetime of the transport instance.
Implements kcenon::network::unified::i_transport.
Definition at line 140 of file quic_connection_adapter.cpp.
{
    return connection_id_;
}
References connection_id_.
io_thread_func()
auto kcenon::network::unified::adapters::quic_connection_adapter::io_thread_func () -> void private
I/O processing thread function.
Definition at line 319 of file quic_connection_adapter.cpp.
{
    constexpr int POLL_TIMEOUT_MS = 10;
    constexpr size_t MAX_PACKET_SIZE = 65535;
    std::vector<uint8_t> recv_buffer(MAX_PACKET_SIZE);
    sockaddr_in remote_addr{};
    remote_addr.sin_family = AF_INET;
    // Resolve remote address
    {
        std::lock_guard lock(endpoint_mutex_);
        remote_addr.sin_port = htons(remote_endpoint_.port);
        struct addrinfo hints{}, *result = nullptr;
        hints.ai_family = AF_INET;
        hints.ai_socktype = SOCK_DGRAM;
        if (getaddrinfo(remote_endpoint_.host.c_str(), nullptr, &hints, &result) == 0
            && result) {
            remote_addr.sin_addr =
                reinterpret_cast<sockaddr_in*>(result->ai_addr)->sin_addr;
            freeaddrinfo(result);
        } else {
            inet_pton(AF_INET, remote_endpoint_.host.c_str(), &remote_addr.sin_addr);
        }
    }
    while (!stop_requested_.load()) {
        // Poll for incoming data
#ifdef _WIN32
        WSAPOLLFD pfd{};
        pfd.fd = socket_fd_;
        pfd.events = POLLIN;
        int poll_result = WSAPoll(&pfd, 1, POLL_TIMEOUT_MS);
#else
        pollfd pfd{};
        pfd.fd = socket_fd_;
        pfd.events = POLLIN;
        int poll_result = poll(&pfd, 1, POLL_TIMEOUT_MS);
#endif
        if (poll_result > 0 && (pfd.revents & POLLIN)) {
            // Receive incoming packet
            sockaddr_in from_addr{};
            socklen_t from_len = sizeof(from_addr);
            auto received = recvfrom(socket_fd_, reinterpret_cast<char*>(recv_buffer.data()),
                                     static_cast<int>(recv_buffer.size()), 0,
                                     reinterpret_cast<sockaddr*>(&from_addr), &from_len);
            if (received > 0) {
                std::span<const uint8_t> packet_data(recv_buffer.data(),
                                                     static_cast<size_t>(received));
                auto result = quic_conn_->receive_packet(packet_data);
                (void)result;
                // Check for state changes
                handle_state_change();
            }
        }
        // Process outgoing data
        process_outgoing();
        // Check for timeouts
        if (quic_conn_) {
            auto timeout = quic_conn_->next_timeout();
            if (timeout && std::chrono::steady_clock::now() >= *timeout) {
                quic_conn_->on_timeout();
            }
        }
        // Handle state changes
        handle_state_change();
        // Generate and send QUIC packets
        if (quic_conn_) {
            auto packets = quic_conn_->generate_packets();
            for (const auto& packet : packets) {
                sendto(socket_fd_, reinterpret_cast<const char*>(packet.data()),
                       static_cast<int>(packet.size()), 0,
                       reinterpret_cast<const sockaddr*>(&remote_addr),
                       sizeof(remote_addr));
            }
        }
        // Check if connection is closed
        if (quic_conn_ && quic_conn_->is_closed()) {
            break;
        }
    }
    running_ = false;
    is_connected_ = false;
    is_connecting_ = false;
    // Notify callbacks
    {
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_disconnected) {
            callbacks_.on_disconnected();
        }
    }
    {
        std::lock_guard lock(stop_mutex_);
    }
    stop_cv_.notify_all();
}
Referenced by connect().
is_connected()
auto kcenon::network::unified::adapters::quic_connection_adapter::is_connected () const -> bool nodiscard override virtual noexcept
Checks if the transport is currently connected.
Returns
true if connected and ready to send/receive, false otherwise
Thread Safety
Thread-safe. Uses atomic operations internally.
Note
A false return may indicate:
Connection not yet established
Connection closed by remote peer
Connection closed locally
Network error occurred
Implements kcenon::network::unified::i_transport.
Definition at line 135 of file quic_connection_adapter.cpp.
{
    return is_connected_.load();
}
References is_connected_.
is_connecting()
auto kcenon::network::unified::adapters::quic_connection_adapter::is_connecting () const -> bool nodiscard override virtual noexcept
Checks if the connection is in the process of connecting.
Returns
true if connect() was called but not yet completed
Implements kcenon::network::unified::i_connection.
Definition at line 308 of file quic_connection_adapter.cpp.
{
    return is_connecting_.load();
}
References is_connecting_.
local_endpoint()
auto kcenon::network::unified::adapters::quic_connection_adapter::local_endpoint () const -> endpoint_info nodiscard override virtual noexcept
Gets the local endpoint information.
Returns
endpoint_info of the local side
Returns valid information only when connected/listening. Returns empty endpoint_info if not bound.
Implements kcenon::network::unified::i_transport.
Definition at line 151 of file quic_connection_adapter.cpp.
{
    std::lock_guard lock(endpoint_mutex_);
    return local_endpoint_;
}
References endpoint_mutex_, and local_endpoint_.
operator=() [1/2]
quic_connection_adapter & kcenon::network::unified::adapters::quic_connection_adapter::operator= (const quic_connection_adapter &) delete
operator=() [2/2]
quic_connection_adapter & kcenon::network::unified::adapters::quic_connection_adapter::operator= (quic_connection_adapter &&) delete
parse_url()
auto kcenon::network::unified::adapters::quic_connection_adapter::parse_url (std::string_view url) -> std::pair<std::string, uint16_t> private
Parse URL to extract host and port.
Definition at line 524 of file quic_connection_adapter.cpp.
{
    std::string url_str(url);
    // Remove quic:// prefix if present
    const std::string quic_prefix = "quic://";
    if (url_str.substr(0, quic_prefix.size()) == quic_prefix) {
        url_str = url_str.substr(quic_prefix.size());
    }
    // Find the last colon for port separation
    auto colon_pos = url_str.rfind(':');
    if (colon_pos == std::string::npos) {
        return {"", 0};
    }
    std::string host = url_str.substr(0, colon_pos);
    std::string port_str = url_str.substr(colon_pos + 1);
    uint16_t port = 0;
    try {
        port = static_cast<uint16_t>(std::stoi(port_str));
    } catch (...) {
        return {"", 0};
    }
    return {host, port};
}
process_incoming()
auto kcenon::network::unified::adapters::quic_connection_adapter::process_incoming () -> void private
Process incoming packets.
Definition at line 459 of file quic_connection_adapter.cpp.
{
    if (!quic_conn_ || !quic_conn_->is_established()) {
        return;
    }
    auto& stream_mgr = quic_conn_->streams();
    // Read data from all readable streams
    for (uint64_t stream_id = 0; stream_id < 1000; stream_id += 4) {
        auto* stream = stream_mgr.get_stream(stream_id);
        if (stream && stream->has_data()) {
            std::vector<uint8_t> buffer(4096);
            auto read_result = stream->read(buffer);
            if (read_result.is_ok() && read_result.value() > 0) {
                buffer.resize(read_result.value());
                std::lock_guard lock(callbacks_mutex_);
                if (callbacks_.on_data) {
                    std::span<const std::byte> byte_span(
                        reinterpret_cast<const std::byte*>(buffer.data()),
                        buffer.size()
                    );
                    callbacks_.on_data(byte_span);
                }
            }
        }
    }
}
process_outgoing()
auto kcenon::network::unified::adapters::quic_connection_adapter::process_outgoing () -> void private
Process outgoing packets.
Definition at line 432 of file quic_connection_adapter.cpp.
{
    if (!quic_conn_ || !quic_conn_->is_established()) {
        return;
    }
    std::deque<std::vector<uint8_t>> data_to_send;
    {
        std::lock_guard lock(send_queue_mutex_);
        data_to_send.swap(send_queue_);
    }
    for (auto& data : data_to_send) {
        // Get or create bidirectional stream
        auto& stream_mgr = quic_conn_->streams();
        auto stream_result = stream_mgr.create_bidirectional_stream();
        if (stream_result.is_ok()) {
            uint64_t stream_id = stream_result.value();
            auto* stream = stream_mgr.get_stream(stream_id);
            if (stream) {
                (void)stream->write(data);
            }
        }
    }
}
remote_endpoint()
auto kcenon::network::unified::adapters::quic_connection_adapter::remote_endpoint () const -> endpoint_info nodiscard override virtual noexcept
Gets the remote endpoint information.
Returns
endpoint_info of the remote peer
Returns valid information only when connected. Returns empty endpoint_info if not connected.
Implements kcenon::network::unified::i_transport.
Definition at line 145 of file quic_connection_adapter.cpp.
{
    std::lock_guard lock(endpoint_mutex_);
    return remote_endpoint_;
}
References endpoint_mutex_, and remote_endpoint_.
send() [1/2]
auto kcenon::network::unified::adapters::quic_connection_adapter::send (std::span< const std::byte > data) -> VoidResult nodiscard override virtual
Sends raw data to the remote endpoint.
Parameters
data The data to send as a span of bytes
Returns
VoidResult indicating success or failure
Error Conditions
Returns error if not connected
Returns error if send operation fails
Returns error if data size exceeds protocol limits
Thread Safety
Thread-safe. Multiple sends may be queued internally.
Performance Note
Data is typically copied to an internal send buffer. For zero-copy sends, see protocol-specific implementations.
Implements kcenon::network::unified::i_transport.
Definition at line 83 of file quic_connection_adapter.cpp.
{
    if (!is_connected_.load()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "QUIC connection is not established"
        );
    }
    if (!quic_conn_) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "QUIC connection object is null"
        );
    }
    // Queue data for sending on the default stream (stream 0)
    std::vector<uint8_t> buffer(data.size());
    std::memcpy(buffer.data(), data.data(), data.size());
    {
        std::lock_guard lock(send_queue_mutex_);
        send_queue_.push_back(std::move(buffer));
    }
    return ok();
}
References kcenon::network::error_void(), and kcenon::network::ok().
send() [2/2]
auto kcenon::network::unified::adapters::quic_connection_adapter::send (std::vector< uint8_t > && data) -> VoidResult nodiscard override virtual
Sends data from a uint8_t vector.
Parameters
data The data to send as a vector of uint8_t
Returns
VoidResult indicating success or failure
Convenience overload for compatibility with existing code using std::vector<uint8_t>.
Implements kcenon::network::unified::i_transport.
Definition at line 111 of file quic_connection_adapter.cpp.
{
    if (!is_connected_.load()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "QUIC connection is not established"
        );
    }
    if (!quic_conn_) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "QUIC connection object is null"
        );
    }
    {
        std::lock_guard lock(send_queue_mutex_);
        send_queue_.push_back(std::move(data));
    }
    return ok();
}
References kcenon::network::error_void(), and kcenon::network::ok().
set_callbacks()
auto kcenon::network::unified::adapters::quic_connection_adapter::set_callbacks (connection_callbacks callbacks) -> void override virtual
Sets all connection callbacks at once.
Parameters
callbacks The callback structure with handlers
Replaces all previously set callbacks. Empty callback functions in the structure will clear the corresponding handler.
Thread Safety
Thread-safe, but callbacks may be invoked from I/O threads.
Implements kcenon::network::unified::i_connection.
Definition at line 292 of file quic_connection_adapter.cpp.
{
    std::lock_guard lock(callbacks_mutex_);
    callbacks_ = std::move(callbacks);
}
set_options()
auto kcenon::network::unified::adapters::quic_connection_adapter::set_options (connection_options options) -> void override virtual
Sets connection options.
Parameters
options The configuration options
Some options may only be effective before connect() is called.
Thread Safety
Thread-safe. Changes may not affect in-flight operations.
Implements kcenon::network::unified::i_connection.
Definition at line 298 of file quic_connection_adapter.cpp.
{
    options_ = options;
}
set_timeout()
auto kcenon::network::unified::adapters::quic_connection_adapter::set_timeout (std::chrono::milliseconds timeout) -> void override virtual
Sets the connection timeout.
Parameters
timeout Timeout duration (0 = no timeout)
Shorthand for setting just the connect_timeout option.
Implements kcenon::network::unified::i_connection.
Definition at line 303 of file quic_connection_adapter.cpp.
{
    options_.connect_timeout = timeout;
}
wait_for_stop()
auto kcenon::network::unified::adapters::quic_connection_adapter::wait_for_stop () -> void override virtual
Blocks until the component has stopped.
Waits for all pending operations to complete and the connection to be fully closed.
Thread Safety
Safe to call from any thread. Uses internal synchronization.
Implements kcenon::network::unified::i_connection.
Definition at line 313 of file quic_connection_adapter.cpp.
{
    std::unique_lock lock(stop_mutex_);
    stop_cv_.wait(lock, [this] { return !running_.load(); });
}
Member Data Documentation
callbacks_
connection_callbacks kcenon::network::unified::adapters::quic_connection_adapter::callbacks_ private
Definition at line 129 of file quic_connection_adapter.h.
callbacks_mutex_
std::mutex kcenon::network::unified::adapters::quic_connection_adapter::callbacks_mutex_ mutable private
Definition at line 128 of file quic_connection_adapter.h.
config_
protocol::quic::quic_config kcenon::network::unified::adapters::quic_connection_adapter::config_ private
Definition at line 114 of file quic_connection_adapter.h.
connection_id_
std::string kcenon::network::unified::adapters::quic_connection_adapter::connection_id_ private
Definition at line 113 of file quic_connection_adapter.h.
Referenced by id().
endpoint_mutex_
std::mutex kcenon::network::unified::adapters::quic_connection_adapter::endpoint_mutex_ mutable private
Definition at line 132 of file quic_connection_adapter.h.
Referenced by local_endpoint(), and remote_endpoint().
io_thread_
std::thread kcenon::network::unified::adapters::quic_connection_adapter::io_thread_ private
Definition at line 123 of file quic_connection_adapter.h.
Referenced by close().
is_connected_
std::atomic<bool> kcenon::network::unified::adapters::quic_connection_adapter::is_connected_ {false} private
Definition at line 138 of file quic_connection_adapter.h.
{false};
Referenced by close(), and is_connected().
is_connecting_
std::atomic<bool> kcenon::network::unified::adapters::quic_connection_adapter::is_connecting_ {false} private
Definition at line 137 of file quic_connection_adapter.h.
{false};
Referenced by close(), and is_connecting().
local_endpoint_
endpoint_info kcenon::network::unified::adapters::quic_connection_adapter::local_endpoint_ private
Definition at line 134 of file quic_connection_adapter.h.
Referenced by local_endpoint().
options_
connection_options kcenon::network::unified::adapters::quic_connection_adapter::options_ private
Definition at line 139 of file quic_connection_adapter.h.
quic_conn_
std::unique_ptr<protocols::quic::connection> kcenon::network::unified::adapters::quic_connection_adapter::quic_conn_ private
Definition at line 117 of file quic_connection_adapter.h.
Referenced by close().
remote_endpoint_
endpoint_info kcenon::network::unified::adapters::quic_connection_adapter::remote_endpoint_ private
Definition at line 133 of file quic_connection_adapter.h.
Referenced by remote_endpoint().
running_
std::atomic<bool> kcenon::network::unified::adapters::quic_connection_adapter::running_ {false} private
Definition at line 124 of file quic_connection_adapter.h.
{false};
Referenced by close().
send_queue_
std::deque<std::vector<uint8_t> > kcenon::network::unified::adapters::quic_connection_adapter::send_queue_ private
Definition at line 147 of file quic_connection_adapter.h.
send_queue_mutex_
std::mutex kcenon::network::unified::adapters::quic_connection_adapter::send_queue_mutex_ mutable private
Definition at line 146 of file quic_connection_adapter.h.
socket_fd_
int kcenon::network::unified::adapters::quic_connection_adapter::socket_fd_ {-1} private
Definition at line 120 of file quic_connection_adapter.h.
{-1};
Referenced by close().
stop_cv_
std::condition_variable kcenon::network::unified::adapters::quic_connection_adapter::stop_cv_ private
Definition at line 143 of file quic_connection_adapter.h.
Referenced by close().
stop_mutex_
std::mutex kcenon::network::unified::adapters::quic_connection_adapter::stop_mutex_ mutable private
Definition at line 142 of file quic_connection_adapter.h.
Referenced by close().
stop_requested_
std::atomic<bool> kcenon::network::unified::adapters::quic_connection_adapter::stop_requested_ {false} private
Definition at line 125 of file quic_connection_adapter.h.
{false};
Referenced by close().
The documentation for this class was generated from the following files:
src/internal/unified/adapters/quic_connection_adapter.h
src/unified/adapters/quic_connection_adapter.cpp