Network System: kcenon::network::core::http_client Class Reference
kcenon::network::core::http_client Class Reference
HTTP/1.1 client built on top of messaging_client.
#include <http_client.h>
Public Member Functions
http_client ()
Construct HTTP client with default timeout.
http_client (std::chrono::milliseconds timeout_ms)
Construct HTTP client with custom timeout.
~http_client ()=default
Destructor.
auto get (const std::string &url, const std::map< std::string, std::string > &query={}, const std::map< std::string, std::string > &headers={}) -> Result< internal::http_response >
Perform HTTP GET request.
auto post (const std::string &url, const std::string &body, const std::map< std::string, std::string > &headers={}) -> Result< internal::http_response >
Perform HTTP POST request.
auto post (const std::string &url, const std::vector< uint8_t > &body, const std::map< std::string, std::string > &headers={}) -> Result< internal::http_response >
Perform HTTP POST request with binary body.
auto put (const std::string &url, const std::string &body, const std::map< std::string, std::string > &headers={}) -> Result< internal::http_response >
Perform HTTP PUT request.
auto del (const std::string &url, const std::map< std::string, std::string > &headers={}) -> Result< internal::http_response >
Perform HTTP DELETE request.
auto head (const std::string &url, const std::map< std::string, std::string > &headers={}) -> Result< internal::http_response >
Perform HTTP HEAD request.
auto patch (const std::string &url, const std::string &body, const std::map< std::string, std::string > &headers={}) -> Result< internal::http_response >
Perform HTTP PATCH request.
auto set_timeout (std::chrono::milliseconds timeout_ms) -> void
Set request timeout.
auto get_timeout () const -> std::chrono::milliseconds
Get current timeout setting.
Private Member Functions
auto request (internal::http_method method, const std::string &url, const std::vector< uint8_t > &body, const std::map< std::string, std::string > &headers, const std::map< std::string, std::string > &query) -> Result< internal::http_response >
Perform generic HTTP request.
auto build_request (internal::http_method method, const http_url &url_info, const std::vector< uint8_t > &body, const std::map< std::string, std::string > &headers) -> internal::http_request
Build HTTP request from components.
Private Attributes
std::chrono::milliseconds timeout_
Detailed Description
HTTP/1.1 client built on top of messaging_client.
Thread Safety
All public methods are thread-safe
Multiple requests can be made concurrently from different threads
Each request uses its own messaging_client instance
Features
HTTP/1.1 protocol support
GET, POST, PUT, DELETE, HEAD, OPTIONS, PATCH methods
Custom headers support
Query parameters support
Request/response body handling
Timeout configuration
Automatic Content-Length calculation
Connection: close header for proper cleanup
Usage Example
auto client = std::make_shared<http_client>();
// Simple GET request
auto response = client->get("http://example.com/api/users");
if (response) {
    std::cout << "Status: " << response->status_code << "\n";
    std::cout << "Body: " << response->get_body_string() << "\n";
}
// POST with JSON body
std::map<std::string, std::string> headers = {
    {"Content-Type", "application/json"}
};
std::string json_body = R"({"name": "John", "age": 30})";
auto post_response = client->post("http://example.com/api/users",
                                  json_body, headers);
Limitations
Only HTTP/1.1 supported (no HTTP/2)
No persistent connections (Connection: close)
No chunked transfer encoding
No automatic redirect following
No cookie management
No compression support
Definition at line 93 of file http_client.h.
Constructor & Destructor Documentation
http_client() [1/2]
kcenon::network::core::http_client::http_client ()
Construct HTTP client with default timeout.
Definition at line 71 of file http_client.cpp.
: timeout_(DEFAULT_TIMEOUT_MS) {}
http_client() [2/2]
kcenon::network::core::http_client::http_client (std::chrono::milliseconds timeout_ms) explicit
Construct HTTP client with custom timeout.
Parameters
timeout_ms Timeout in milliseconds
Definition at line 73 of file http_client.cpp.
    : timeout_(timeout_ms) {}
~http_client()
kcenon::network::core::http_client::~http_client () default
Destructor.
Member Function Documentation
build_request()
auto kcenon::network::core::http_client::build_request (internal::http_method method, const http_url & url_info, const std::vector< uint8_t > & body, const std::map< std::string, std::string > & headers) -> internal::http_request private
Build HTTP request from components.
Parameters
method HTTP method
url_info Parsed URL
body Request body
headers Custom headers
Returns
HTTP request object
Definition at line 132 of file http_client.cpp.
{
  internal::http_request request;
  request.method = method;
  request.uri = url_info.path;
  request.version = internal::http_version::HTTP_1_1;
  request.query_params = url_info.query;
  request.body = body;
  // Add custom headers
  for (const auto &[name, value] : headers) {
    request.set_header(name, value);
  }
  // Add required headers
  request.set_header("Host", url_info.host);
  request.set_header("Connection", "close");
  request.set_header("Accept", "*/*");
  // Add Content-Length if body is present
  if (!body.empty()) {
    request.set_header("Content-Length", std::to_string(body.size()));
  }
  // Add User-Agent if not present
  if (!request.get_header("User-Agent")) {
    request.set_header("User-Agent", "NetworkSystem-HTTP-Client/1.0");
  }
  return request;
}
References kcenon::network::internal::http_request::body, kcenon::network::internal::http_request::get_header(), kcenon::network::internal::HTTP_1_1, kcenon::network::internal::http_request::method, kcenon::network::internal::http_request::query_params, kcenon::network::internal::http_request::set_header(), kcenon::network::internal::http_request::uri, and kcenon::network::internal::http_request::version.
del()
auto kcenon::network::core::http_client::del (const std::string & url, const std::map< std::string, std::string > & headers = {}) -> Result<internal::http_response>
Perform HTTP DELETE request.
Parameters
url Full URL
headers Custom headers (optional)
Returns
Result containing HTTP response or error
Definition at line 104 of file http_client.cpp.
{
  return request(internal::http_method::HTTP_DELETE, url, {}, headers, {});
}
References kcenon::network::internal::HTTP_DELETE.
get()
auto kcenon::network::core::http_client::get (const std::string & url, const std::map< std::string, std::string > & query = {}, const std::map< std::string, std::string > & headers = {}) -> Result<internal::http_response>
Perform HTTP GET request.
Parameters
url Full URL (e.g., "http://example.com/path")
query Query parameters (optional)
headers Custom headers (optional)
Returns
Result containing HTTP response or error
Definition at line 76 of file http_client.cpp.
{
  return request(internal::http_method::HTTP_GET, url, {}, headers, query);
}
References kcenon::network::internal::HTTP_GET.
get_timeout()
auto kcenon::network::core::http_client::get_timeout () const -> std::chrono::milliseconds
Get current timeout setting.
Returns
Timeout in milliseconds
Definition at line 128 of file http_client.cpp.
{
  return timeout_;
}
References timeout_.
head()
auto kcenon::network::core::http_client::head (const std::string & url, const std::map< std::string, std::string > & headers = {}) -> Result<internal::http_response>
Perform HTTP HEAD request.
Parameters
url Full URL
headers Custom headers (optional)
Returns
Result containing HTTP response or error
Definition at line 110 of file http_client.cpp.
{
  return request(internal::http_method::HTTP_HEAD, url, {}, headers, {});
}
References kcenon::network::internal::HTTP_HEAD.
patch()
auto kcenon::network::core::http_client::patch (const std::string & url, const std::string & body, const std::map< std::string, std::string > & headers = {}) -> Result<internal::http_response>
Perform HTTP PATCH request.
Parameters
url Full URL
body Request body
headers Custom headers (optional)
Returns
Result containing HTTP response or error
Definition at line 116 of file http_client.cpp.
{
  std::vector<uint8_t> body_bytes(body.begin(), body.end());
  return request(internal::http_method::HTTP_PATCH, url, body_bytes, headers,
                 {});
}
References kcenon::network::internal::HTTP_PATCH.
post() [1/2]
auto kcenon::network::core::http_client::post (const std::string & url, const std::string & body, const std::map< std::string, std::string > & headers = {}) -> Result<internal::http_response>
Perform HTTP POST request.
Parameters
url Full URL
body Request body
headers Custom headers (optional)
Returns
Result containing HTTP response or error
Definition at line 83 of file http_client.cpp.
{
  std::vector<uint8_t> body_bytes(body.begin(), body.end());
  return request(internal::http_method::HTTP_POST, url, body_bytes, headers,
                 {});
}
References kcenon::network::internal::HTTP_POST.
post() [2/2]
auto kcenon::network::core::http_client::post (const std::string & url, const std::vector< uint8_t > & body, const std::map< std::string, std::string > & headers = {}) -> Result<internal::http_response>
Perform HTTP POST request with binary body.
Parameters
url Full URL
body Request body as bytes
headers Custom headers (optional)
Returns
Result containing HTTP response or error
Definition at line 91 of file http_client.cpp.
{
  return request(internal::http_method::HTTP_POST, url, body, headers, {});
}
References kcenon::network::internal::HTTP_POST.
put()
auto kcenon::network::core::http_client::put (const std::string & url, const std::string & body, const std::map< std::string, std::string > & headers = {}) -> Result<internal::http_response>
Perform HTTP PUT request.
Parameters
url Full URL
body Request body
headers Custom headers (optional)
Returns
Result containing HTTP response or error
Definition at line 97 of file http_client.cpp.
{
  std::vector<uint8_t> body_bytes(body.begin(), body.end());
  return request(internal::http_method::HTTP_PUT, url, body_bytes, headers, {});
}
References kcenon::network::internal::HTTP_PUT.
request()
auto kcenon::network::core::http_client::request (internal::http_method method, const std::string & url, const std::vector< uint8_t > & body, const std::map< std::string, std::string > & headers, const std::map< std::string, std::string > & query) -> Result<internal::http_response> private
Perform generic HTTP request.
Parameters
method HTTP method
url Full URL
body Request body (optional)
headers Custom headers
query Query parameters
Returns
Result containing HTTP response or error
Definition at line 167 of file http_client.cpp.
{
  // Parse URL
  auto url_result = http_url::parse(url);
  if (url_result.is_err()) {
    return error<internal::http_response>(-1, "Failed to parse URL: " +
                                                  url_result.error().message);
  }
  auto url_info = std::move(url_result.value());
  // Merge query parameters
  for (const auto &[key, value] : query) {
    url_info.query[key] = value;
  }
  // Check for HTTPS (not supported yet)
  if (url_info.scheme == "https") {
    return error<internal::http_response>(
        -1, "HTTPS not supported yet. Use HTTP for now.");
  }
  // Build HTTP request
  auto http_request = build_request(method, url_info, body, headers);
  // Serialize request
  auto request_bytes = internal::http_parser::serialize_request(http_request);
  // Create messaging client for this request
  auto client = std::make_shared<messaging_client>(
      "http_client_" +
      std::to_string(
          std::chrono::system_clock::now().time_since_epoch().count()));
  // Response data collection
  std::vector<uint8_t> response_data;
  std::mutex response_mutex;
  std::condition_variable response_cv;
  bool response_complete = false;
  bool has_error = false;
  std::string error_message;
  // Set up receive callback
  client->set_receive_callback([&](const std::vector<uint8_t> &data) {
    std::lock_guard<std::mutex> lock(response_mutex);
    response_data.insert(response_data.end(), data.begin(), data.end());
    // Check if we have received the complete response
    // For simplicity, we check for end of headers + Content-Length
    // or connection close
    std::string_view response_str(
        reinterpret_cast<const char *>(response_data.data()),
        response_data.size());
    auto headers_end = response_str.find("\r\n\r\n");
    if (headers_end != std::string_view::npos) {
      // We have headers, check Content-Length
      auto headers_section = response_str.substr(0, headers_end);
      // Simple Content-Length extraction
      auto cl_pos = headers_section.find("Content-Length:");
      if (cl_pos == std::string_view::npos) {
        cl_pos = headers_section.find("content-length:");
      }
      if (cl_pos != std::string_view::npos) {
        auto cl_start = headers_section.find(':', cl_pos) + 1;
        auto cl_end = headers_section.find('\r', cl_start);
        auto cl_str = headers_section.substr(cl_start, cl_end - cl_start);
        // Trim whitespace
        while (!cl_str.empty() && std::isspace(cl_str.front()))
          cl_str.remove_prefix(1);
        while (!cl_str.empty() && std::isspace(cl_str.back()))
          cl_str.remove_suffix(1);
        try {
          std::size_t content_length = std::stoull(std::string(cl_str));
          std::size_t body_start = headers_end + 4;
          if (response_data.size() >= body_start + content_length) {
            response_complete = true;
            response_cv.notify_one();
          }
        } catch (...) {
          // Invalid Content-Length, treat as complete
          response_complete = true;
          response_cv.notify_one();
        }
      } else {
        // No Content-Length, will rely on connection close
      }
    }
  });
  // Set up error callback
  client->set_error_callback([&](std::error_code ec) {
    std::lock_guard<std::mutex> lock(response_mutex);
    if (!response_complete) {
      // Connection closed, mark as complete if we have any data
      if (!response_data.empty()) {
        response_complete = true;
      } else {
        has_error = true;
        error_message = ec.message();
      }
      response_cv.notify_one();
    }
  });
  // Connect to server
  auto connect_result = client->start_client(url_info.host, url_info.port);
  if (connect_result.is_err()) {
    return error<internal::http_response>(
        -1, "Failed to connect to " + url_info.host + ":" +
                std::to_string(url_info.port) + ": " +
                connect_result.error().message);
  }
  // Wait for connection (give it a moment to establish)
  std::this_thread::sleep_for(std::chrono::milliseconds(100));
  // Send request
  auto send_result = client->send_packet(std::move(request_bytes));
  if (send_result.is_err()) {
    (void)client->stop_client();
    return error<internal::http_response>(-1, "Failed to send request: " +
                                                  send_result.error().message);
  }
  // Wait for response with timeout
  {
    std::unique_lock<std::mutex> lock(response_mutex);
    if (!response_cv.wait_for(lock, timeout_,
                              [&] { return response_complete || has_error; })) {
      (void)client->stop_client();
      return error<internal::http_response>(-1, "Request timeout");
    }
  }
  // Stop client
  (void)client->stop_client();
  // Check for errors
  if (has_error) {
    return error<internal::http_response>(-1,
                                          "Request failed: " + error_message);
  }
  // Parse response
  auto response_result = internal::http_parser::parse_response(response_data);
  if (response_result.is_err()) {
    return error<internal::http_response>(
        -1, "Failed to parse response: " + response_result.error().message);
  }
  return response_result;
}
References kcenon::network::error, kcenon::network::core::http_url::parse(), kcenon::network::internal::http_parser::parse_response(), and kcenon::network::internal::http_parser::serialize_request().
set_timeout()
auto kcenon::network::core::http_client::set_timeout (std::chrono::milliseconds timeout_ms) -> void
Set request timeout.
Parameters
timeout_ms Timeout in milliseconds
Definition at line 124 of file http_client.cpp.
{
  timeout_ = timeout_ms;
}
Member Data Documentation
timeout_
std::chrono::milliseconds kcenon::network::core::http_client::timeout_ private
Definition at line 235 of file http_client.h.
Referenced by get_timeout().
The documentation for this class was generated from the following files:
src/internal/http/http_client.h
src/http/http_client.cpp