Network System: kcenon::network::core::secure_messaging_udp_server Class Reference
kcenon::network::core::secure_messaging_udp_server Class Reference export
module kcenon.network
A secure UDP server using DTLS (Datagram TLS) for encrypted communication.
#include <secure_messaging_udp_server.h>
Classes
struct dtls_session
DTLS session for a client.
struct endpoint_hash
Hash function for endpoint (for unordered_map).
Public Types
using udp_receive_callback_t = std::function< void(const std::vector< uint8_t > &, const asio::ip::udp::endpoint &)>
UDP-specific callback types with endpoint information.
using udp_client_callback_t = std::function< void(const asio::ip::udp::endpoint &)>
using dtls_data_callback = std::function< void(const std::string &session_id, std::span< const uint8_t > data)>
Callback type for DTLS data reception.
Public Member Functions
secure_messaging_udp_server (std::string_view server_id)
Constructs a secure_messaging_udp_server with an identifier.
~secure_messaging_udp_server () noexcept
Destructor. Automatically calls stop_server() if still running.
secure_messaging_udp_server (const secure_messaging_udp_server &)=delete
secure_messaging_udp_server & operator= (const secure_messaging_udp_server &)=delete
auto set_certificate_chain_file (const std::string &file_path) -> VoidResult
Sets the certificate chain file for TLS.
auto set_private_key_file (const std::string &file_path) -> VoidResult
Sets the private key file for TLS.
auto start_server (uint16_t port) -> VoidResult
Starts the server and begins listening for DTLS connections.
auto stop_server () -> VoidResult
Stops the server and releases all resources.
auto wait_for_stop () -> void
Blocks the calling thread until the server is stopped.
auto async_send_to (std::vector< uint8_t > &&data, const asio::ip::udp::endpoint &endpoint, std::function< void(std::error_code, std::size_t)> handler=nullptr) -> void
Sends an encrypted datagram to a specific client.
auto set_receive_callback (udp_receive_callback_t callback) -> void
Sets a UDP-specific callback to handle received decrypted datagrams.
auto set_error_callback (std::function< void(std::error_code)> callback) -> void
Sets a callback to handle errors.
auto set_client_connected_callback (udp_client_callback_t callback) -> void
Sets a UDP-specific callback for new client connection.
auto set_client_disconnected_callback (udp_client_callback_t callback) -> void
Sets a UDP-specific callback for client disconnection.
auto is_running () const noexcept -> bool
Returns whether the server is currently running.
auto server_id () const -> const std::string &
Returns the server identifier.
secure_messaging_udp_server (std::string_view server_id, const ssl_config &config)
Construct a secure UDP server with DTLS configuration.
virtual ~secure_messaging_udp_server () noexcept
Destructor.
secure_messaging_udp_server (const secure_messaging_udp_server &)=delete
secure_messaging_udp_server & operator= (const secure_messaging_udp_server &)=delete
secure_messaging_udp_server (secure_messaging_udp_server &&) noexcept
secure_messaging_udp_server & operator= (secure_messaging_udp_server &&) noexcept
bool start_server (uint16_t port)
Start the secure UDP server.
bool start_server (std::string_view address, uint16_t port)
Start the secure UDP server on a specific interface.
void stop_server ()
Stop the server.
bool send_to (std::string_view session_id, std::span< const uint8_t > data)
Send encrypted datagram to a specific session.
bool is_running () const noexcept
Check if the server is running.
size_t session_count () const noexcept
Get the number of active DTLS sessions.
std::string_view server_id () const noexcept
Get the server identifier.
void set_session_connected_callback (std::function< void(const std::string &)> callback)
Set session connected callback.
void set_session_disconnected_callback (std::function< void(const std::string &)> callback)
Set session disconnected callback.
void set_data_callback (dtls_data_callback callback)
Set data received callback.
void set_error_callback (error_callback callback)
Set error callback.
Private Member Functions
auto init_ssl_context () -> VoidResult
Initializes the SSL context for DTLS server.
auto do_receive () -> void
Handles incoming datagrams and routes them to appropriate sessions.
auto process_session_data (const std::vector< uint8_t > &data, const asio::ip::udp::endpoint &sender) -> void
Processes received data for an existing session.
auto create_session (const asio::ip::udp::endpoint &client_endpoint) -> std::shared_ptr< dtls_session >
Creates a new DTLS session for a client.
Private Attributes
std::string server_id_
std::atomic< bool > is_running_ {false}
std::optional< std::promise< void > > stop_promise_
std::future< void > stop_future_
std::unique_ptr< asio::io_context > io_context_
std::unique_ptr< asio::ip::udp::socket > socket_
SSL_CTX * ssl_ctx_ {nullptr}
std::string cert_file_
std::string key_file_
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::future< void > io_context_future_
std::array< uint8_t, 65536 > read_buffer_
asio::ip::udp::endpoint sender_endpoint_
std::mutex sessions_mutex_
std::unordered_map< asio::ip::udp::endpoint, std::shared_ptr< dtls_session >, endpoint_hash > sessions_
std::mutex callback_mutex_
udp_receive_callback_t receive_callback_
std::function< void(std::error_code)> error_callback_
udp_client_callback_t client_connected_callback_
udp_client_callback_t client_disconnected_callback_
std::unique_ptr< impl > pimpl_
Detailed Description
A secure UDP server using DTLS (Datagram TLS) for encrypted communication.
A DTLS encrypted UDP server.
This class uses the same lifecycle management pattern as other messaging classes (is_running_, stop_promise_, etc.) but with UDP-specific callbacks that include endpoint information.
Thread Safety
All public methods are thread-safe.
Session management is protected by appropriate mutexes.
Atomic flags prevent race conditions.
Key Characteristics
Uses DTLS 1.2/1.3 for encryption over UDP transport.
Manages multiple client sessions with individual DTLS contexts.
Provides confidentiality and integrity for UDP datagrams.
Suitable for secure real-time server applications.
Usage Example
auto server = std::make_shared<secure_messaging_udp_server>("SecureUDPServer");
// Configure certificates
server->set_certificate_chain_file("server.crt");
server->set_private_key_file("server.key");
// Set callback to handle received datagrams
server->set_receive_callback(
    [](const std::vector<uint8_t>& data, const asio::ip::udp::endpoint& sender) {
        std::cout << "Received " << data.size() << " encrypted bytes\n";
    });
// Start server
auto result = server->start_server(5555);
if (!result) {
    std::cerr << "Failed to start: " << result.error().message << "\n";
    return -1;
}
// Send response to client
server->async_send_to(response_data, client_endpoint, handler);
// Stop server
server->stop_server();
This class provides secure UDP server using DTLS, supporting multiple encrypted client connections.
import kcenon.network;
using namespace kcenon::network::core;
ssl_config config;
config.protocol = ssl_protocol::dtls_1_2;
config.certificate_path = "/path/to/server.pem";
config.private_key_path = "/path/to/server.key";
auto server = std::make_unique<secure_messaging_udp_server>("dtls_server", config);
server->start_server(5684);
Definition at line 114 of file secure_messaging_udp_server.h.
Member Typedef Documentation
dtls_data_callback
using kcenon::network::core::secure_messaging_udp_server::dtls_data_callback = std::function<void(const std::string& session_id, std::span<const uint8_t> data)> export
Callback type for DTLS data reception.
Definition at line 588 of file ssl.cppm.
udp_client_callback_t
using kcenon::network::core::secure_messaging_udp_server::udp_client_callback_t = std::function<void(const asio::ip::udp::endpoint&)>
Definition at line 120 of file secure_messaging_udp_server.h.
udp_receive_callback_t
using kcenon::network::core::secure_messaging_udp_server::udp_receive_callback_t = std::function<void(const std::vector<uint8_t>&, const asio::ip::udp::endpoint&)>
UDP-specific callback types with endpoint information.
Definition at line 118 of file secure_messaging_udp_server.h.
Constructor & Destructor Documentation
secure_messaging_udp_server() [1/5]
kcenon::network::core::secure_messaging_udp_server::secure_messaging_udp_server (std::string_view server_id) explicit
Constructs a secure_messaging_udp_server with an identifier.
Parameters
server_id A descriptive identifier for this server instance.
Definition at line 42 of file secure_messaging_udp_server.cpp.
    : server_id_(server_id)
{
}
~secure_messaging_udp_server() [1/2]
kcenon::network::core::secure_messaging_udp_server::~secure_messaging_udp_server () noexcept
Destructor. Automatically calls stop_server() if still running.
Definition at line 47 of file secure_messaging_udp_server.cpp.
{
    try
    {
        // Ignore the return value in destructor to avoid throwing
        (void)stop_server();
    }
    catch (...)
    {
        // Destructor must not throw - swallow all exceptions
    }
}
References stop_server().
secure_messaging_udp_server() [2/5]
kcenon::network::core::secure_messaging_udp_server::secure_messaging_udp_server (const secure_messaging_udp_server &) delete
secure_messaging_udp_server() [3/5]
kcenon::network::core::secure_messaging_udp_server::secure_messaging_udp_server (std::string_view server_id, const ssl_config & config) explicit export
Construct a secure UDP server with DTLS configuration.
Parameters
server_id A string identifier for this server instance
config SSL/DTLS configuration
~secure_messaging_udp_server() [2/2]
virtual kcenon::network::core::secure_messaging_udp_server::~secure_messaging_udp_server () export virtual noexcept
Destructor.
secure_messaging_udp_server() [4/5]
kcenon::network::core::secure_messaging_udp_server::secure_messaging_udp_server (const secure_messaging_udp_server &) export delete
secure_messaging_udp_server() [5/5]
kcenon::network::core::secure_messaging_udp_server::secure_messaging_udp_server (secure_messaging_udp_server &&) export noexcept
Member Function Documentation
async_send_to()
auto kcenon::network::core::secure_messaging_udp_server::async_send_to (std::vector< uint8_t > && data, const asio::ip::udp::endpoint & endpoint, std::function< void(std::error_code, std::size_t)> handler = nullptr) -> void
Sends an encrypted datagram to a specific client.
Parameters
data The plaintext data to encrypt and send (moved for efficiency).
endpoint The target client endpoint.
handler Optional completion handler.
Definition at line 443 of file secure_messaging_udp_server.cpp.
{
    std::shared_ptr<dtls_session> session;
    {
        std::lock_guard<std::mutex> lock(sessions_mutex_);
        auto it = sessions_.find(endpoint);
        if (it != sessions_.end())
        {
            session = it->second;
        }
    }
    if (!session || !session->socket || !session->handshake_complete)
    {
        if (handler)
        {
            handler(std::make_error_code(std::errc::not_connected), 0);
        }
        return;
    }
    session->socket->async_send_to(std::move(data), endpoint, std::move(handler));
}
create_session()
auto kcenon::network::core::secure_messaging_udp_server::create_session (const asio::ip::udp::endpoint & client_endpoint) -> std::shared_ptr<dtls_session> private
Creates a new DTLS session for a client.
Definition at line 367 of file secure_messaging_udp_server.cpp.
{
    // Create a new UDP socket for this client session
    // Note: In a real implementation, you might want to use a single socket
    // and demultiplex based on endpoint, but that requires more complex
    // BIO handling with OpenSSL's DTLS.
    try
    {
        asio::ip::udp::socket client_socket(*io_context_, asio::ip::udp::v4());
        auto session = std::make_shared<dtls_session>();
        session->socket = std::make_shared<internal::dtls_socket>(
            std::move(client_socket), ssl_ctx_);
        session->socket->set_peer_endpoint(client_endpoint);
        // Set receive callback
        session->socket->set_receive_callback(
            [this, client_endpoint](const std::vector<uint8_t>& data,
                                    const asio::ip::udp::endpoint& /*sender*/)
            {
                std::function<void(const std::vector<uint8_t>&, const asio::ip::udp::endpoint&)> callback;
                {
                    std::lock_guard<std::mutex> lock(callback_mutex_);
                    callback = receive_callback_;
                }
                if (callback)
                {
                    callback(data, client_endpoint);
                }
            });
        // Perform handshake
        session->socket->async_handshake(
            internal::dtls_socket::handshake_type::server,
            [this, session, client_endpoint](std::error_code ec)
            {
                if (ec)
                {
                    // Handshake failed, remove session
                    {
                        std::lock_guard<std::mutex> lock(sessions_mutex_);
                        sessions_.erase(client_endpoint);
                    }
                    return;
                }
                session->handshake_complete = true;
                // Notify client connected
                std::function<void(const asio::ip::udp::endpoint&)> callback;
                {
                    std::lock_guard<std::mutex> lock(callback_mutex_);
                    callback = client_connected_callback_;
                }
                if (callback)
                {
                    callback(client_endpoint);
                }
            });
        // Store session
        {
            std::lock_guard<std::mutex> lock(sessions_mutex_);
            sessions_[client_endpoint] = session;
        }
        return session;
    }
    catch (const std::exception& /*e*/)
    {
        return nullptr;
    }
}
References kcenon::network::internal::dtls_socket::server.
do_receive()
auto kcenon::network::core::secure_messaging_udp_server::do_receive () -> void private
Handles incoming datagrams and routes them to appropriate sessions.
Definition at line 278 of file secure_messaging_udp_server.cpp.
{
    if (!is_running_.load(std::memory_order_acquire) || !socket_)
    {
        return;
    }
    auto self = shared_from_this();
    socket_->async_receive_from(
        asio::buffer(read_buffer_),
        sender_endpoint_,
        [this, self](std::error_code ec, std::size_t length)
        {
            if (!is_running_.load(std::memory_order_acquire))
            {
                return;
            }
            if (ec)
            {
                if (ec != asio::error::operation_aborted)
                {
                    std::function<void(std::error_code)> callback;
                    {
                        std::lock_guard<std::mutex> lock(callback_mutex_);
                        callback = error_callback_;
                    }
                    if (callback)
                    {
                        callback(ec);
                    }
                }
                return;
            }
            if (length > 0)
            {
                std::vector<uint8_t> data(read_buffer_.begin(),
                                          read_buffer_.begin() + length);
                process_session_data(data, sender_endpoint_);
            }
            // Continue receiving
            if (is_running_.load(std::memory_order_acquire))
            {
                do_receive();
            }
        });
}
init_ssl_context()
auto kcenon::network::core::secure_messaging_udp_server::init_ssl_context () -> VoidResult private
Initializes the SSL context for DTLS server.
Returns
Result<void> - Success if context initialized.
Definition at line 74 of file secure_messaging_udp_server.cpp.
{
    // Create DTLS server context
    ssl_ctx_ = SSL_CTX_new(DTLS_server_method());
    if (!ssl_ctx_)
    {
        return error_void(error_codes::common_errors::internal_error,
                          "Failed to create DTLS context",
                          "secure_messaging_udp_server::init_ssl_context");
    }
    // Set DTLS options
    SSL_CTX_set_options(ssl_ctx_, SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3);
    // Load certificate
    if (!cert_file_.empty())
    {
        if (SSL_CTX_use_certificate_chain_file(ssl_ctx_, cert_file_.c_str()) != 1)
        {
            SSL_CTX_free(ssl_ctx_);
            ssl_ctx_ = nullptr;
            return error_void(error_codes::common_errors::internal_error,
                              "Failed to load certificate: " + cert_file_,
                              "secure_messaging_udp_server::init_ssl_context");
        }
    }
    // Load private key
    if (!key_file_.empty())
    {
        if (SSL_CTX_use_PrivateKey_file(ssl_ctx_, key_file_.c_str(), SSL_FILETYPE_PEM) != 1)
        {
            SSL_CTX_free(ssl_ctx_);
            ssl_ctx_ = nullptr;
            return error_void(error_codes::common_errors::internal_error,
                              "Failed to load private key: " + key_file_,
                              "secure_messaging_udp_server::init_ssl_context");
        }
        // Verify private key matches certificate
        if (SSL_CTX_check_private_key(ssl_ctx_) != 1)
        {
            SSL_CTX_free(ssl_ctx_);
            ssl_ctx_ = nullptr;
            return error_void(error_codes::common_errors::internal_error,
                              "Private key does not match certificate",
                              "secure_messaging_udp_server::init_ssl_context");
        }
    }
    // Set verification mode (server doesn't verify client by default)
    SSL_CTX_set_verify(ssl_ctx_, SSL_VERIFY_NONE, nullptr);
    return ok();
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, and kcenon::network::ok().
is_running() [1/2]
bool kcenon::network::core::secure_messaging_udp_server::is_running () const export noexcept
Check if the server is running.
Returns
true if running
is_running() [2/2]
auto kcenon::network::core::secure_messaging_udp_server::is_running () const -> bool inline noexcept
Returns whether the server is currently running.
Returns
true if server is running.
Definition at line 216 of file secure_messaging_udp_server.h.
        {
            return is_running_.load(std::memory_order_acquire);
        }
References is_running_.
operator=() [1/3]
secure_messaging_udp_server & kcenon::network::core::secure_messaging_udp_server::operator= (const secure_messaging_udp_server &) delete
operator=() [2/3]
secure_messaging_udp_server & kcenon::network::core::secure_messaging_udp_server::operator= (const secure_messaging_udp_server &) export delete
operator=() [3/3]
secure_messaging_udp_server & kcenon::network::core::secure_messaging_udp_server::operator= (secure_messaging_udp_server &&) export noexcept
process_session_data()
auto kcenon::network::core::secure_messaging_udp_server::process_session_data (const std::vector< uint8_t > & data, const asio::ip::udp::endpoint & sender) -> void private
Processes received data for an existing session.
Definition at line 328 of file secure_messaging_udp_server.cpp.
{
    std::shared_ptr<dtls_session> session;
    // Look up existing session
    {
        std::lock_guard<std::mutex> lock(sessions_mutex_);
        auto it = sessions_.find(sender);
        if (it != sessions_.end())
        {
            session = it->second;
        }
    }
    // Create new session if needed
    if (!session)
    {
        session = create_session(sender);
        if (!session)
        {
            return;
        }
    }
    // For a proper DTLS server, we would need to:
    // 1. Parse the DTLS record to determine if it's a ClientHello
    // 2. Handle cookie exchange for DoS protection
    // 3. Create per-client SSL objects
    // For this implementation, we rely on the dtls_socket to handle
    // the DTLS protocol, but in a real server, each client needs its own
    // SSL object and BIO pair.
    // Note: A complete DTLS server implementation would require
    // more sophisticated session management. This is a simplified version.
}
send_to()
bool kcenon::network::core::secure_messaging_udp_server::send_to (std::string_view session_id, std::span< const uint8_t > data) export
Send encrypted datagram to a specific session.
Parameters
session_id The target session ID
data The data to send
Returns
true if data was sent
server_id() [1/2]
auto kcenon::network::core::secure_messaging_udp_server::server_id () const -> const std::string& inline
Returns the server identifier.
Returns
The server_id string provided at construction.
Definition at line 225 of file secure_messaging_udp_server.h.
{ return server_id_; }
References server_id_.
server_id() [2/2]
std::string_view kcenon::network::core::secure_messaging_udp_server::server_id () const export noexcept
Get the server identifier.
Returns
Server ID string
session_count()
size_t kcenon::network::core::secure_messaging_udp_server::session_count () const export noexcept
Get the number of active DTLS sessions.
Returns
Number of active sessions
set_certificate_chain_file()
auto kcenon::network::core::secure_messaging_udp_server::set_certificate_chain_file (const std::string & file_path) -> VoidResult
Sets the certificate chain file for TLS.
Parameters
file_path Path to the certificate chain file (PEM format).
Returns
Result<void> - Success if file loaded.
Must be called before start_server().
Definition at line 60 of file secure_messaging_udp_server.cpp.
{
    cert_file_ = file_path;
    return ok();
}
References kcenon::network::ok().
set_client_connected_callback()
auto kcenon::network::core::secure_messaging_udp_server::set_client_connected_callback (udp_client_callback_t callback) -> void
Sets a UDP-specific callback for new client connection.
Parameters
callback Function called when a new client completes DTLS handshake.
Definition at line 486 of file secure_messaging_udp_server.cpp.
{
    std::lock_guard<std::mutex> lock(callback_mutex_);
    client_connected_callback_ = std::move(callback);
}
set_client_disconnected_callback()
auto kcenon::network::core::secure_messaging_udp_server::set_client_disconnected_callback (udp_client_callback_t callback) -> void
Sets a UDP-specific callback for client disconnection.
Parameters
callback Function called when a client session ends.
Definition at line 493 of file secure_messaging_udp_server.cpp.
{
    std::lock_guard<std::mutex> lock(callback_mutex_);
    client_disconnected_callback_ = std::move(callback);
}
set_data_callback()
void kcenon::network::core::secure_messaging_udp_server::set_data_callback (dtls_data_callback callback) export
Set data received callback.
Parameters
callback Function to call when decrypted data is received
set_error_callback() [1/2]
void kcenon::network::core::secure_messaging_udp_server::set_error_callback (error_callback callback) export
Set error callback.
Parameters
callback Function to call on errors
set_error_callback() [2/2]
auto kcenon::network::core::secure_messaging_udp_server::set_error_callback (std::function< void(std::error_code)> callback) -> void
Sets a callback to handle errors.
Parameters
callback Function with signature void(std::error_code)
Definition at line 479 of file secure_messaging_udp_server.cpp.
{
    std::lock_guard<std::mutex> lock(callback_mutex_);
    error_callback_ = std::move(callback);
}
set_private_key_file()
auto kcenon::network::core::secure_messaging_udp_server::set_private_key_file (const std::string & file_path) -> VoidResult
Sets the private key file for TLS.
Parameters
file_path Path to the private key file (PEM format).
Returns
Result<void> - Success if file loaded.
Must be called before start_server().
Definition at line 67 of file secure_messaging_udp_server.cpp.
{
    key_file_ = file_path;
    return ok();
}
References kcenon::network::ok().
set_receive_callback()
auto kcenon::network::core::secure_messaging_udp_server::set_receive_callback (udp_receive_callback_t callback) -> void
Sets a UDP-specific callback to handle received decrypted datagrams.
Parameters
callback Function with signature void(const std::vector<uint8_t>&, const asio::ip::udp::endpoint&)
Definition at line 471 of file secure_messaging_udp_server.cpp.
{
    std::lock_guard<std::mutex> lock(callback_mutex_);
    receive_callback_ = std::move(callback);
}
set_session_connected_callback()
void kcenon::network::core::secure_messaging_udp_server::set_session_connected_callback (std::function< void(const std::string &)> callback) export
Set session connected callback.
Parameters
callback Function to call when a DTLS session is established
set_session_disconnected_callback()
void kcenon::network::core::secure_messaging_udp_server::set_session_disconnected_callback (std::function< void(const std::string &)> callback) export
Set session disconnected callback.
Parameters
callback Function to call when a DTLS session ends
start_server() [1/3]
bool kcenon::network::core::secure_messaging_udp_server::start_server (std::string_view address, uint16_t port) export
Start the secure UDP server on a specific interface.
Parameters
address The interface address to bind to
port The port to listen on
Returns
true if server started successfully
start_server() [2/3]
bool kcenon::network::core::secure_messaging_udp_server::start_server (uint16_t port) export
Start the secure UDP server.
Parameters
port The port to listen on
Returns
true if server started successfully
start_server() [3/3]
auto kcenon::network::core::secure_messaging_udp_server::start_server (uint16_t port) -> VoidResult
Starts the server and begins listening for DTLS connections.
Parameters
port The UDP port to bind to.
Returns
Result<void> - Success if server started.
Spawns a background thread for I/O operations. DTLS handshakes are performed automatically for new clients.
Definition at line 130 of file secure_messaging_udp_server.cpp.
{
    if (is_running_.load(std::memory_order_acquire))
    {
        return error_void(error_codes::network_system::server_already_running,
                          "Server already running",
                          "secure_messaging_udp_server::start_server");
    }
    // Check if certificates are configured
    if (cert_file_.empty() || key_file_.empty())
    {
        return error_void(error_codes::common_errors::invalid_argument,
                          "Certificate and private key files must be set",
                          "secure_messaging_udp_server::start_server");
    }
    // Initialize SSL context
    auto ssl_result = init_ssl_context();
    if (!ssl_result.is_ok())
    {
        return ssl_result;
    }
    // Create io_context
    io_context_ = std::make_unique<asio::io_context>();
    // Create and bind UDP socket
    try
    {
        socket_ = std::make_unique<asio::ip::udp::socket>(
            *io_context_,
            asio::ip::udp::endpoint(asio::ip::udp::v4(), port));
    }
    catch (const std::exception& e)
    {
        SSL_CTX_free(ssl_ctx_);
        ssl_ctx_ = nullptr;
        return error_void(error_codes::network_system::bind_failed,
                          std::string("Failed to bind port: ") + e.what(),
                          "secure_messaging_udp_server::start_server");
    }
    // Get thread pool from network context
    thread_pool_ = network_context::instance().get_thread_pool();
    if (!thread_pool_) {
        // Fallback: create a temporary thread pool if network_context is not initialized
        thread_pool_ = std::make_shared<integration::basic_thread_pool>(std::thread::hardware_concurrency());
    }
    // Prepare promise/future for wait_for_stop()
    stop_promise_.emplace();
    stop_future_ = stop_promise_->get_future();
    // Start io_context in background
    io_context_future_ = thread_pool_->submit(
        [this]()
        {
            auto work_guard = asio::make_work_guard(*io_context_);
            io_context_->run();
        });
    is_running_.store(true, std::memory_order_release);
    // Start receiving
    do_receive();
    return ok();
}
References kcenon::network::error_codes::network_system::bind_failed, kcenon::network::error_void(), kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), kcenon::network::error_codes::common_errors::invalid_argument, kcenon::network::ok(), and kcenon::network::error_codes::network_system::server_already_running.
stop_server() [1/2]
void kcenon::network::core::secure_messaging_udp_server::stop_server () export
Stop the server.
stop_server() [2/2]
auto kcenon::network::core::secure_messaging_udp_server::stop_server () -> VoidResult
Stops the server and releases all resources.
Returns
Result<void> - Success if server stopped.
Definition at line 200 of file secure_messaging_udp_server.cpp.
{
    if (!is_running_.exchange(false, std::memory_order_acq_rel))
    {
        // Already stopped
        if (ssl_ctx_)
        {
            SSL_CTX_free(ssl_ctx_);
            ssl_ctx_ = nullptr;
        }
        return ok();
    }
    // Clear sessions
    {
        std::lock_guard<std::mutex> lock(sessions_mutex_);
        for (auto& [endpoint, session] : sessions_)
        {
            if (session && session->socket)
            {
                session->socket->stop_receive();
            }
        }
        sessions_.clear();
    }
    // Close socket
    if (socket_)
    {
        std::error_code ec;
        socket_->close(ec);
        socket_.reset();
    }
    // Stop io_context
    if (io_context_)
    {
        io_context_->stop();
    }
    // Wait for io_context thread
    if (io_context_future_.valid())
    {
        io_context_future_.wait();
    }
    // Cleanup SSL context
    if (ssl_ctx_)
    {
        SSL_CTX_free(ssl_ctx_);
        ssl_ctx_ = nullptr;
    }
    // Signal the promise for wait_for_stop()
    if (stop_promise_.has_value())
    {
        try
        {
            stop_promise_->set_value();
        }
        catch (const std::future_error&)
        {
            // Promise already satisfied - this is OK during shutdown
        }
        stop_promise_.reset();
    }
    return ok();
}
References kcenon::network::ok().
Referenced by ~secure_messaging_udp_server().
wait_for_stop()
auto kcenon::network::core::secure_messaging_udp_server::wait_for_stop () -> void
Blocks the calling thread until the server is stopped.
Definition at line 270 of file secure_messaging_udp_server.cpp.
{
    if (stop_future_.valid())
    {
        stop_future_.wait();
    }
}
Member Data Documentation
callback_mutex_
std::mutex kcenon::network::core::secure_messaging_udp_server::callback_mutex_ mutable private
Protects callbacks.
Definition at line 299 of file secure_messaging_udp_server.h.
cert_file_
std::string kcenon::network::core::secure_messaging_udp_server::cert_file_ private
Certificate file path.
Definition at line 285 of file secure_messaging_udp_server.h.
client_connected_callback_
udp_client_callback_t kcenon::network::core::secure_messaging_udp_server::client_connected_callback_ private
Definition at line 302 of file secure_messaging_udp_server.h.
client_disconnected_callback_
udp_client_callback_t kcenon::network::core::secure_messaging_udp_server::client_disconnected_callback_ private
Definition at line 303 of file secure_messaging_udp_server.h.
error_callback_
std::function<void(std::error_code)> kcenon::network::core::secure_messaging_udp_server::error_callback_ private
Definition at line 301 of file secure_messaging_udp_server.h.
io_context_
std::unique_ptr<asio::io_context> kcenon::network::core::secure_messaging_udp_server::io_context_ private
ASIO I/O context.
Definition at line 281 of file secure_messaging_udp_server.h.
io_context_future_
std::future<void> kcenon::network::core::secure_messaging_udp_server::io_context_future_ private
Future for io_context run task.
Definition at line 289 of file secure_messaging_udp_server.h.
is_running_
std::atomic<bool> kcenon::network::core::secure_messaging_udp_server::is_running_ {false} private
Running state flag.
Definition at line 276 of file secure_messaging_udp_server.h.
{false};
Referenced by is_running().
key_file_
std::string kcenon::network::core::secure_messaging_udp_server::key_file_ private
Private key file path.
Definition at line 286 of file secure_messaging_udp_server.h.
pimpl_
std::unique_ptr<impl> kcenon::network::core::secure_messaging_udp_server::pimpl_ export private
Definition at line 682 of file ssl.cppm.
read_buffer_
std::array<uint8_t, 65536> kcenon::network::core::secure_messaging_udp_server::read_buffer_ private
Buffer for receiving datagrams.
Definition at line 291 of file secure_messaging_udp_server.h.
receive_callback_
udp_receive_callback_t kcenon::network::core::secure_messaging_udp_server::receive_callback_ private
Definition at line 300 of file secure_messaging_udp_server.h.
sender_endpoint_
asio::ip::udp::endpoint kcenon::network::core::secure_messaging_udp_server::sender_endpoint_ private
Current sender endpoint.
Definition at line 292 of file secure_messaging_udp_server.h.
server_id_
std::string kcenon::network::core::secure_messaging_udp_server::server_id_ private
Server identifier.
Definition at line 275 of file secure_messaging_udp_server.h.
Referenced by server_id().
sessions_
std::unordered_map<asio::ip::udp::endpoint, std::shared_ptr<dtls_session>, endpoint_hash> kcenon::network::core::secure_messaging_udp_server::sessions_ private
Active DTLS sessions.
Definition at line 296 of file secure_messaging_udp_server.h.
sessions_mutex_
std::mutex kcenon::network::core::secure_messaging_udp_server::sessions_mutex_ private
Protects sessions map.
Definition at line 294 of file secure_messaging_udp_server.h.
socket_
std::unique_ptr<asio::ip::udp::socket> kcenon::network::core::secure_messaging_udp_server::socket_ private
Main UDP socket.
Definition at line 282 of file secure_messaging_udp_server.h.
ssl_ctx_
SSL_CTX* kcenon::network::core::secure_messaging_udp_server::ssl_ctx_ {nullptr} private
OpenSSL SSL context.
Definition at line 284 of file secure_messaging_udp_server.h.
{nullptr};
stop_future_
std::future<void> kcenon::network::core::secure_messaging_udp_server::stop_future_ private
Future that wait_for_stop() waits on.
Definition at line 278 of file secure_messaging_udp_server.h.
stop_promise_
std::optional<std::promise<void> > kcenon::network::core::secure_messaging_udp_server::stop_promise_ private
Used to signal wait_for_stop().
Definition at line 277 of file secure_messaging_udp_server.h.
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::secure_messaging_udp_server::thread_pool_ private
Definition at line 288 of file secure_messaging_udp_server.h.
The documentation for this class was generated from the following files:
src/internal/core/secure_messaging_udp_server.h
src/modules/ssl.cppm
src/core/secure_messaging_udp_server.cpp