Network System: kcenon::network::internal::adapters::http_server_adapter Class Reference
kcenon::network::internal::adapters::http_server_adapter Class Reference
Adapter that wraps http_server to implement i_protocol_server.
#include <http_server_adapter.h>
Public Member Functions
http_server_adapter (std::string_view server_id)
Constructs an adapter with a unique server ID.
~http_server_adapter () override
Destructor ensures proper cleanup.
http_server_adapter (const http_server_adapter &)=delete
http_server_adapter & operator= (const http_server_adapter &)=delete
http_server_adapter (http_server_adapter &&)=delete
http_server_adapter & operator= (http_server_adapter &&)=delete
auto is_running () const -> bool override
Checks if the component is currently running.
auto wait_for_stop () -> void override
Blocks until the component has stopped.
auto start (uint16_t port) -> VoidResult override
Starts the server and begins listening for connections.
auto stop () -> VoidResult override
Stops the server and closes all connections.
auto connection_count () const -> size_t override
Gets the number of active client connections.
auto set_connection_callback (connection_callback_t callback) -> void override
Sets the callback for new connections.
auto set_disconnection_callback (disconnection_callback_t callback) -> void override
Sets the callback for disconnections.
auto set_receive_callback (receive_callback_t callback) -> void override
Sets the callback for received data.
auto set_error_callback (error_callback_t callback) -> void override
Sets the callback for errors.
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Member Functions
auto setup_internal_routes () -> void
Sets up internal HTTP routes to bridge to i_protocol_server callbacks.
auto get_or_create_session (const std::string &address, uint16_t port) -> std::shared_ptr< http_request_session >
Gets or creates a session for the given request.
auto remove_session (const std::string &session_id) -> void
Removes a session after request processing.
Static Private Member Functions
static auto make_session_id (const std::string &address, uint16_t port, uint64_t request_id) -> std::string
Creates a unique session ID from request info.
Private Attributes
std::string server_id_
std::shared_ptr< core::http_server > server_
std::mutex callbacks_mutex_
connection_callback_t connection_callback_
disconnection_callback_t disconnection_callback_
receive_callback_t receive_callback_
error_callback_t error_callback_
std::mutex sessions_mutex_
std::unordered_map< std::string, std::shared_ptr< http_request_session > > sessions_
std::atomic< uint64_t > request_counter_ {0}
std::atomic< bool > is_running_ {false}
Additional Inherited Members
Public Types inherited from kcenon::network::interfaces::i_protocol_server
using connection_callback_t = std::function< void(std::shared_ptr< i_session >)>
Callback type for new connections.
using disconnection_callback_t = std::function< void(std::string_view)>
Callback type for disconnections (session_id)
using receive_callback_t = std::function< void(std::string_view, const std::vector< uint8_t > &)>
Callback type for received data (session_id, data)
using error_callback_t = std::function< void(std::string_view, std::error_code)>
Callback type for errors (session_id, error)
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps http_server to implement i_protocol_server.
This adapter bridges the HTTP server implementation with the unified i_protocol_server interface. It allows http_facade to return i_protocol_server without modifying the existing http_server class.
Design Rationale
The adapter pattern is used because:
HTTP server uses routing (GET, POST handlers) vs callback-only i_protocol_server
HTTP responses must be sent within the request handler context
HTTP has request/response semantics, not streaming
Request Handling
The adapter registers a catch-all route that:
Invokes connection_callback when a request arrives
Invokes receive_callback with the request body
Waits for send() on the session to get response data
Returns the response to the HTTP client
Session Management
Each HTTP request is treated as a temporary session
Session ID is derived from client endpoint + request timestamp
Sessions are removed after response is sent
Thread Safety
Thread-safe. All methods can be called from any thread.
See also
i_protocol_server
http_server
Definition at line 126 of file http_server_adapter.h.
Constructor & Destructor Documentation
http_server_adapter() [1/3]
kcenon::network::internal::adapters::http_server_adapter::http_server_adapter (std::string_view server_id) explicit
Constructs an adapter with a unique server ID.
Parameters
server_id Unique identifier for this server
Definition at line 111 of file http_server_adapter.cpp.
    : server_id_(server_id)
    , server_(std::make_shared<core::http_server>(std::string(server_id)))
{
    setup_internal_routes();
}
References setup_internal_routes().
~http_server_adapter()
kcenon::network::internal::adapters::http_server_adapter::~http_server_adapter () override
Destructor ensures proper cleanup.
Definition at line 118 of file http_server_adapter.cpp.
{
    if (server_ && is_running_.load(std::memory_order_acquire))
    {
        (void)server_->stop();
    }
}
References is_running_, and server_.
http_server_adapter() [2/3]
kcenon::network::internal::adapters::http_server_adapter::http_server_adapter (const http_server_adapter &) delete
http_server_adapter() [3/3]
kcenon::network::internal::adapters::http_server_adapter::http_server_adapter (http_server_adapter &&) delete
Member Function Documentation
connection_count()
auto kcenon::network::internal::adapters::http_server_adapter::connection_count () const -> size_t override virtual
Gets the number of active client connections.
Returns
The count of currently connected clients.
Definition of "Active"
A connection is considered active if:
Connection is established (handshake complete if applicable)
Session has not been closed
No fatal errors have occurred on the session
Protocol-Specific Notes
TCP/WebSocket/QUIC: Count of established connections
UDP: Count of unique peer endpoints seen recently
HTTP: Count of active persistent connections or requests
Thread Safety
Thread-safe. Uses atomic operations for accurate count.
Performance
O(1) operation. Does not iterate through connections.
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 189 of file http_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(sessions_mutex_);
    return sessions_.size();
}
References sessions_, and sessions_mutex_.
get_or_create_session()
auto kcenon::network::internal::adapters::http_server_adapter::get_or_create_session (const std::string & address, uint16_t port) -> std::shared_ptr<http_request_session> private
Gets or creates a session for the given request.
Definition at line 365 of file http_server_adapter.cpp.
{
    const auto request_id = request_counter_.fetch_add(1, std::memory_order_relaxed);
    const auto session_id = make_session_id(address, port, request_id);
    std::lock_guard<std::mutex> lock(sessions_mutex_);
    auto session = std::make_shared<http_request_session>(
        session_id, address, port, server_);
    sessions_[session_id] = session;
    return session;
}
is_running()
auto kcenon::network::internal::adapters::http_server_adapter::is_running () const -> bool override virtual
Checks if the component is currently running.
Returns
true if the component is active, false otherwise.
This method must be thread-safe and use atomic operations for the running state.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 130 of file http_server_adapter.cpp.
{
    return is_running_.load(std::memory_order_acquire);
}
References is_running_.
make_session_id()
auto kcenon::network::internal::adapters::http_server_adapter::make_session_id (const std::string & address, uint16_t port, uint64_t request_id) -> std::string static private
Creates a unique session ID from request info.
Definition at line 355 of file http_server_adapter.cpp.
{
    std::ostringstream oss;
    oss << address << ":" << port << "#" << request_id;
    return oss.str();
}
operator=() [1/2]
http_server_adapter & kcenon::network::internal::adapters::http_server_adapter::operator= (const http_server_adapter &) delete
operator=() [2/2]
http_server_adapter & kcenon::network::internal::adapters::http_server_adapter::operator= (http_server_adapter &&) delete
remove_session()
auto kcenon::network::internal::adapters::http_server_adapter::remove_session (const std::string & session_id) -> void private
Removes a session after request processing.
Definition at line 381 of file http_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(sessions_mutex_);
    sessions_.erase(session_id);
}
set_connection_callback()
auto kcenon::network::internal::adapters::http_server_adapter::set_connection_callback (connection_callback_t callback) -> void override virtual
Sets the callback for new connections.
Parameters
callback The callback function.
Callback Parameters
session: Shared pointer to the new session object
Callback Behavior
Called when:
TCP: After accept() and initial handshake complete
WebSocket: After HTTP upgrade handshake succeeds
UDP: After first datagram received from new peer
QUIC: After connection establishment handshake
HTTP: After request line and headers parsed (HTTP/1.1)
Session Object
The session object allows:
Sending data to the specific client
Retrieving session metadata (ID, remote endpoint)
Closing the session individually
Thread Safety
The callback may be invoked from I/O threads. If the callback accesses shared state, it must be thread-safe.
Example
server->set_connection_callback([](std::shared_ptr<i_session> session) {
    std::cout << "New client: " << session->id() << std::endl;
    // Send welcome message
    session->send({0x01, 0x02, 0x03});
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 195 of file http_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    connection_callback_ = std::move(callback);
}
set_disconnection_callback()
auto kcenon::network::internal::adapters::http_server_adapter::set_disconnection_callback (disconnection_callback_t callback) -> void override virtual
Sets the callback for disconnections.
Parameters
callback The callback function.
Callback Parameters
session_id: String identifier of the disconnected session
Callback Behavior
Called when:
Client closes connection gracefully
Connection lost due to network error
Server closes the session
Timeout or keepalive failure
Clean-up Responsibility
The callback is the appropriate place to:
Remove session from application state
Log disconnection events
Release session-specific resources
Thread Safety
The callback may be invoked from I/O threads. Session cleanup code must be thread-safe.
Example
server->set_disconnection_callback([](std::string_view session_id) {
    std::cout << "Client disconnected: " << session_id << std::endl;
    // Remove from session map
    sessions.erase(std::string(session_id));
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 201 of file http_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    disconnection_callback_ = std::move(callback);
}
set_error_callback()
auto kcenon::network::internal::adapters::http_server_adapter::set_error_callback (error_callback_t callback) -> void override virtual
Sets the callback for errors.
Parameters
callback The callback function.
Callback Parameters
session_id: String identifier of the affected session (may be empty for server-level errors)
error: std::error_code describing the error
Error Categories
Connection errors: Reset, timeout, refused
Protocol errors: Invalid handshake, malformed data
System errors: Out of memory, file descriptor limits
Application errors: Send queue full, rate limit exceeded
Error Handling Strategy
The callback should:
Log the error for diagnostics
Decide whether to close the session
Update error metrics/statistics
Notify monitoring systems if critical
Automatic Disconnection
Some errors trigger automatic session closure:
Connection reset (ECONNRESET)
Protocol violations
Fatal security errors
For these, disconnection_callback will also be invoked.
Thread Safety
The callback may be invoked from I/O threads. Error handling code must be thread-safe.
Example
server->set_error_callback([](std::string_view session_id,
                               std::error_code error) {
    std::cerr << "Error on session " << session_id << ": "
              << error.message() << std::endl;
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 213 of file http_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    error_callback_ = std::move(callback);
}
set_receive_callback()
auto kcenon::network::internal::adapters::http_server_adapter::set_receive_callback (receive_callback_t callback) -> void override virtual
Sets the callback for received data.
Parameters
callback The callback function.
Callback Parameters
session_id: String identifier of the sending session
data: Vector of bytes received
Data Ownership
The data vector is passed by const reference. If the callback needs to retain the data, it must copy it. The data is valid only for the duration of the callback.
Protocol-Specific Notes
TCP: May deliver partial messages (stream-based)
UDP: Delivers complete datagrams (message boundaries preserved)
WebSocket: Delivers complete messages (frame assembled)
QUIC: Delivers complete messages (stream data)
Thread Safety
The callback may be invoked from I/O threads. Multiple callbacks may execute concurrently for different sessions.
Example
server->set_receive_callback([](std::string_view session_id,
                                 const std::vector<uint8_t>& data) {
    std::cout << "Received " << data.size() << " bytes from "
              << session_id << std::endl;
    // Process data...
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 207 of file http_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    receive_callback_ = std::move(callback);
}
setup_internal_routes()
auto kcenon::network::internal::adapters::http_server_adapter::setup_internal_routes () -> void private
Sets up internal HTTP routes to bridge to i_protocol_server callbacks.
Definition at line 223 of file http_server_adapter.cpp.
{
    if (!server_)
    {
        return;
    }
    // Register a catch-all POST handler for unified protocol interface
    // The i_protocol_client.send() performs HTTP POST, so we handle POST requests
    server_->post("/:path", [this](const core::http_request_context& ctx) {
        // Create a session for this request
        const auto request_id = request_counter_.fetch_add(1, std::memory_order_relaxed);
        const auto session_id = make_session_id("client", 0, request_id);
        auto session = std::make_shared<http_request_session>(
            session_id, "client", 0, server_);
        // Track the session
        {
            std::lock_guard<std::mutex> lock(sessions_mutex_);
            sessions_[session_id] = session;
        }
        // Notify connection callback
        {
            connection_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = connection_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session);
            }
        }
        // Notify receive callback with request body
        {
            receive_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = receive_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session_id, ctx.request.body);
            }
        }
        // Build response from session data
        network::internal::http_response response;
        response.status_code = 200;
        response.body = session->get_response_data();
        response.set_header("Content-Type", "application/octet-stream");
        // Notify disconnection callback
        {
            disconnection_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = disconnection_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session_id);
            }
        }
        // Remove session
        remove_session(session_id);
        return response;
    });
    // Also register root POST handler
    server_->post("/", [this](const core::http_request_context& ctx) {
        const auto request_id = request_counter_.fetch_add(1, std::memory_order_relaxed);
        const auto session_id = make_session_id("client", 0, request_id);
        auto session = std::make_shared<http_request_session>(
            session_id, "client", 0, server_);
        {
            std::lock_guard<std::mutex> lock(sessions_mutex_);
            sessions_[session_id] = session;
        }
        {
            connection_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = connection_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session);
            }
        }
        {
            receive_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = receive_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session_id, ctx.request.body);
            }
        }
        network::internal::http_response response;
        response.status_code = 200;
        response.body = session->get_response_data();
        response.set_header("Content-Type", "application/octet-stream");
        {
            disconnection_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = disconnection_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session_id);
            }
        }
        remove_session(session_id);
        return response;
    });
}
References kcenon::network::internal::http_request::body, kcenon::network::internal::http_response::body, kcenon::network::core::http_request_context::request, kcenon::network::internal::http_response::set_header(), and kcenon::network::internal::http_response::status_code.
Referenced by http_server_adapter().
start()
auto kcenon::network::internal::adapters::http_server_adapter::start (uint16_t port) -> VoidResult override virtual
Starts the server and begins listening for connections.
Parameters
port The port number to listen on.
Returns
VoidResult indicating success or failure.
Behavior
Binds to the specified port on all interfaces (0.0.0.0/::)
Begins accepting incoming connections
Initializes protocol-specific resources
Invokes connection_callback for each new client
Error Conditions
Returns error if already running
Returns error if port is already in use (EADDRINUSE)
Returns error if port binding fails (permission, invalid port)
Returns error if underlying protocol initialization fails
Protocol-Specific Notes
TCP/WebSocket/QUIC: Creates listening socket
UDP: Creates datagram socket, begins receiving
HTTP: May create connection pool or thread pool
Port Range
Valid ports: 1-65535
Privileged ports (< 1024) may require elevated permissions
Port 0 requests OS to assign an available port
Thread Safety
Thread-safe. Only one start operation can succeed at a time. Subsequent calls while running will return an error.
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 147 of file http_server_adapter.cpp.
{
    if (!server_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Server not initialized",
            "http_server_adapter::start"
        );
    }
    auto result = server_->start(port);
    if (result.is_ok())
    {
        is_running_.store(true, std::memory_order_release);
    }
    return result;
}
References kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::internal_error.
stop()
auto kcenon::network::internal::adapters::http_server_adapter::stop () -> VoidResult override virtual
Stops the server and closes all connections.
Returns
VoidResult indicating success or failure.
Behavior
Stops accepting new connections
Closes all active client sessions gracefully
Invokes disconnection_callback for each session
Cancels all pending operations
Releases protocol-specific resources
Error Conditions
Returns error if not running
Graceful Shutdown
The stop operation attempts to:
Stop accepting new connections immediately
Close existing connections gracefully (protocol-dependent)
Wait for pending operations to complete (with timeout)
Force-close remaining connections if timeout expires
Protocol-Specific Notes
TCP: Sends FIN to all clients, waits for ACK
WebSocket: Sends close frame to all clients
UDP: Stops receiving, no client "close" needed
QUIC: Sends CONNECTION_CLOSE to all clients
Thread Safety
Thread-safe. Safe to call from any thread including callbacks. The method blocks until shutdown is complete.
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 166 of file http_server_adapter.cpp.
{
    if (!server_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Server not initialized",
            "http_server_adapter::stop"
        );
    }
    auto result = server_->stop();
    is_running_.store(false, std::memory_order_release);
    // Clear tracked sessions on stop
    {
        std::lock_guard<std::mutex> lock(sessions_mutex_);
        sessions_.clear();
    }
    return result;
}
References kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::internal_error.
wait_for_stop()
auto kcenon::network::internal::adapters::http_server_adapter::wait_for_stop () -> void override virtual
Blocks until the component has stopped.
This method should be used to synchronize shutdown operations. It returns immediately if the component is not running.
Thread Safety
Safe to call from any thread. Uses internal synchronization.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 135 of file http_server_adapter.cpp.
{
    if (server_)
    {
        server_->wait_for_stop();
    }
}
Member Data Documentation
callbacks_mutex_
std::mutex kcenon::network::internal::adapters::http_server_adapter::callbacks_mutex_ mutable private
Definition at line 190 of file http_server_adapter.h.
connection_callback_
connection_callback_t kcenon::network::internal::adapters::http_server_adapter::connection_callback_ private
Definition at line 191 of file http_server_adapter.h.
disconnection_callback_
disconnection_callback_t kcenon::network::internal::adapters::http_server_adapter::disconnection_callback_ private
Definition at line 192 of file http_server_adapter.h.
error_callback_
error_callback_t kcenon::network::internal::adapters::http_server_adapter::error_callback_ private
Definition at line 194 of file http_server_adapter.h.
is_running_
std::atomic<bool> kcenon::network::internal::adapters::http_server_adapter::is_running_ {false} private
Definition at line 199 of file http_server_adapter.h.
{false};
Referenced by is_running(), and ~http_server_adapter().
receive_callback_
receive_callback_t kcenon::network::internal::adapters::http_server_adapter::receive_callback_ private
Definition at line 193 of file http_server_adapter.h.
request_counter_
std::atomic<uint64_t> kcenon::network::internal::adapters::http_server_adapter::request_counter_ {0} private
Definition at line 198 of file http_server_adapter.h.
{0};
server_
std::shared_ptr<core::http_server> kcenon::network::internal::adapters::http_server_adapter::server_ private
Definition at line 188 of file http_server_adapter.h.
Referenced by ~http_server_adapter().
server_id_
std::string kcenon::network::internal::adapters::http_server_adapter::server_id_ private
Definition at line 187 of file http_server_adapter.h.
sessions_
std::unordered_map<std::string, std::shared_ptr<http_request_session> > kcenon::network::internal::adapters::http_server_adapter::sessions_ private
Definition at line 197 of file http_server_adapter.h.
Referenced by connection_count().
sessions_mutex_
std::mutex kcenon::network::internal::adapters::http_server_adapter::sessions_mutex_ mutable private
Definition at line 196 of file http_server_adapter.h.
Referenced by connection_count().
The documentation for this class was generated from the following files:
src/internal/adapters/http_server_adapter.h
src/adapters/http_server_adapter.cpp