Network System: kcenon::network::integration::logger_integration_manager Class Reference
kcenon::network::integration::logger_integration_manager Class Reference
Manager for logger system integration.
#include <logger_integration.h>
Classes
class impl
Public Member Functions
void set_logger (std::shared_ptr< logger_interface > logger)
Set the logger implementation.
std::shared_ptr< logger_interface > get_logger ()
Get the current logger.
void log (log_level level, const std::string &message)
Log a message.
void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function)
Log a message with location.
Static Public Member Functions
static logger_integration_manager & instance ()
Get the singleton instance.
Private Member Functions
logger_integration_manager ()
~logger_integration_manager ()
Private Attributes
std::unique_ptr< impl > pimpl_
Detailed Description
Manager for logger system integration.
This class manages the integration between network_system and logger implementations. When KCENON_WITH_COMMON_SYSTEM is enabled, it delegates to GlobalLoggerRegistry internally.
Definition at line 194 of file logger_integration.h.
Constructor & Destructor Documentation
logger_integration_manager()
kcenon::network::integration::logger_integration_manager::logger_integration_manager () private
Definition at line 309 of file logger_integration.cpp.
    : pimpl_(std::make_unique<impl>()) {}
Referenced by instance().
~logger_integration_manager()
kcenon::network::integration::logger_integration_manager::~logger_integration_manager () private default
Member Function Documentation
get_logger()
std::shared_ptr< logger_interface > kcenon::network::integration::logger_integration_manager::get_logger ()
Get the current logger.
Returns
Current logger (creates basic logger if none set)
Definition at line 318 of file logger_integration.cpp.
{
    return pimpl_->get_logger();
}
References kcenon::network::integration::logger_integration_manager::impl::get_logger(), and pimpl_.
instance()
logger_integration_manager & kcenon::network::integration::logger_integration_manager::instance () static
Get the singleton instance.
Returns
Reference to the singleton instance
Definition at line 302 of file logger_integration.cpp.
{
    // Intentionally leak the singleton to avoid destruction order issues
    // during sanitizer runs and shutdown hooks.
    static logger_integration_manager* instance = new logger_integration_manager();
    return *instance;
}
References instance(), and logger_integration_manager().
Referenced by kcenon::network::core::network_context::initialize(), kcenon::network::initialize(), instance(), and kcenon::network::core::network_context::set_logger().
log() [1/2]
void kcenon::network::integration::logger_integration_manager::log (log_level level, const std::string & message)
Log a message.
Parameters
level Log level
message Message to log
Definition at line 322 of file logger_integration.cpp.
{
    pimpl_->log(level, message);
}
References kcenon::network::integration::logger_integration_manager::impl::log(), kcenon::network::message, and pimpl_.
log() [2/2]
void kcenon::network::integration::logger_integration_manager::log (log_level level, const std::string & message, const std::string & file, int line, const std::string & function)
Log a message with location.
Parameters
level Log level
message Message to log
file Source file
line Line number
function Function name
Definition at line 326 of file logger_integration.cpp.
{
    pimpl_->log(level, message, file, line, function);
}
References kcenon::network::integration::logger_integration_manager::impl::log(), kcenon::network::message, and pimpl_.
set_logger()
void kcenon::network::integration::logger_integration_manager::set_logger (std::shared_ptr< logger_interface > logger)
Set the logger implementation.
Parameters
logger Logger to use
Definition at line 314 of file logger_integration.cpp.
{
    pimpl_->set_logger(logger);
}
References pimpl_, and kcenon::network::integration::logger_integration_manager::impl::set_logger().
Referenced by kcenon::network::core::network_context::initialize(), kcenon::network::initialize(), and kcenon::network::core::network_context::set_logger().
Member Data Documentation
pimpl_
std::unique_ptr<impl> kcenon::network::integration::logger_integration_manager::pimpl_ private
Definition at line 237 of file logger_integration.h.
Referenced by get_logger(), log(), log(), and set_logger().
The documentation for this class was generated from the following files:
src/internal/integration/logger_integration.h
src/integration/logger_integration.cpp