Network System: kcenon::network::unified::adapters::quic_listener_adapter Class Reference
kcenon::network::unified::adapters::quic_listener_adapter Class Reference
Adapter that implements i_listener for QUIC protocol.
#include <quic_listener_adapter.h>
Classes
struct connection_info
Public Member Functions
quic_listener_adapter (const protocol::quic::quic_config &config, std::string_view listener_id)
Constructs an adapter with QUIC configuration.
~quic_listener_adapter () override
Destructor ensures proper cleanup.
quic_listener_adapter (const quic_listener_adapter &)=delete
quic_listener_adapter & operator= (const quic_listener_adapter &)=delete
quic_listener_adapter (quic_listener_adapter &&)=delete
quic_listener_adapter & operator= (quic_listener_adapter &&)=delete
auto start (const endpoint_info &bind_address) -> VoidResult override
Starts listening for incoming connections.
auto start (uint16_t port) -> VoidResult override
Starts listening on a specific port (all interfaces)
auto stop () noexcept -> void override
Stops listening and closes all connections.
auto set_callbacks (listener_callbacks callbacks) -> void override
Sets all listener callbacks at once.
auto set_accept_callback (accept_callback_t callback) -> void override
Sets the accept callback for new connections.
auto is_listening () const noexcept -> bool override
Checks if the listener is currently listening.
auto local_endpoint () const noexcept -> endpoint_info override
Gets the local endpoint the listener is bound to.
auto connection_count () const noexcept -> size_t override
Gets the number of active connections.
auto send_to (std::string_view connection_id, std::span< const std::byte > data) -> VoidResult override
Sends data to a specific connection.
auto broadcast (std::span< const std::byte > data) -> VoidResult override
Broadcasts data to all connected clients.
auto close_connection (std::string_view connection_id) noexcept -> void override
Closes a specific connection.
auto wait_for_stop () -> void override
Blocks until the listener has stopped.
Public Member Functions inherited from kcenon::network::unified::i_listener
virtual ~i_listener ()=default
Virtual destructor.
i_listener (const i_listener &)=delete
i_listener & operator= (const i_listener &)=delete
i_listener (i_listener &&)=default
i_listener & operator= (i_listener &&)=default
Private Member Functions
auto accept_thread_func () -> void
Accept thread function.
auto process_connections () -> void
Process incoming packets for all connections.
auto generate_connection_id (const protocols::quic::connection_id &cid) -> std::string
Generate unique connection ID.
auto handle_new_connection (std::unique_ptr< protocols::quic::connection > conn, const std::string &conn_id) -> void
Handle new connection.
auto setup_socket (const endpoint_info &bind_address) -> VoidResult
Setup UDP socket for listening.
Private Attributes
std::string listener_id_
protocol::quic::quic_config config_
int socket_fd_ {-1}
std::thread accept_thread_
std::atomic< bool > running_ {false}
std::atomic< bool > stop_requested_ {false}
std::mutex callbacks_mutex_
listener_callbacks callbacks_
accept_callback_t accept_callback_
std::mutex endpoint_mutex_
endpoint_info local_endpoint_
std::mutex connections_mutex_
std::unordered_map< std::string, connection_info > connections_
std::mutex stop_mutex_
std::condition_variable stop_cv_
Additional Inherited Members
Public Types inherited from kcenon::network::unified::i_listener
using accept_callback_t = std::function<void(std::unique_ptr<i_connection>)>
Callback for accepted connections.
Protected Member Functions inherited from kcenon::network::unified::i_listener
i_listener ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that implements i_listener for QUIC protocol.
This adapter creates a QUIC server that accepts incoming connections. Each accepted connection is managed internally and can be accessed via the listener's connection management methods.
QUIC Server Specifics
Requires TLS certificates (cert_file and key_file)
Supports 0-RTT for session resumption
Multiplexed streams per connection
Connection migration support
Thread Safety
Thread-safe. All methods can be called from any thread.
Connection Management
Accepted connections are tracked internally and can be accessed via send_to(), broadcast(), and close_connection() methods.
Definition at line 42 of file quic_listener_adapter.h.
Constructor & Destructor Documentation
quic_listener_adapter() [1/3]
kcenon::network::unified::adapters::quic_listener_adapter::quic_listener_adapter (const protocol::quic::quic_config & config, std::string_view listener_id)
Constructs an adapter with QUIC configuration.
Parameters
config QUIC configuration options (cert_file and key_file required)
listener_id Unique identifier for this listener
Definition at line 79 of file quic_listener_adapter.cpp.
    : listener_id_(listener_id)
    , config_(config)
{
}
References config.
~quic_listener_adapter()
kcenon::network::unified::adapters::quic_listener_adapter::~quic_listener_adapter () override
Destructor ensures proper cleanup.
Definition at line 87 of file quic_listener_adapter.cpp.
{
    stop();
}
References stop().
quic_listener_adapter() [2/3]
kcenon::network::unified::adapters::quic_listener_adapter::quic_listener_adapter (const quic_listener_adapter &) delete
quic_listener_adapter() [3/3]
kcenon::network::unified::adapters::quic_listener_adapter::quic_listener_adapter (quic_listener_adapter &&) delete
Member Function Documentation
accept_thread_func()
auto kcenon::network::unified::adapters::quic_listener_adapter::accept_thread_func () -> void private
Accept thread function.
Definition at line 372 of file quic_listener_adapter.cpp.
{
    constexpr int POLL_TIMEOUT_MS = 10;
    constexpr size_t MAX_PACKET_SIZE = 65535;
    std::vector<uint8_t> recv_buffer(MAX_PACKET_SIZE);
    while (!stop_requested_.load()) {
        // Poll for incoming data
#ifdef _WIN32
        WSAPOLLFD pfd{};
        pfd.fd = socket_fd_;
        pfd.events = POLLIN;
        int poll_result = WSAPoll(&pfd, 1, POLL_TIMEOUT_MS);
#else
        pollfd pfd{};
        pfd.fd = socket_fd_;
        pfd.events = POLLIN;
        int poll_result = poll(&pfd, 1, POLL_TIMEOUT_MS);
#endif
        if (poll_result > 0 && (pfd.revents & POLLIN)) {
            // Receive incoming packet
            sockaddr_in from_addr{};
            socklen_t from_len = sizeof(from_addr);
            auto received = recvfrom(socket_fd_, reinterpret_cast<char*>(recv_buffer.data()),
                                     static_cast<int>(recv_buffer.size()), 0,
                                     reinterpret_cast<sockaddr*>(&from_addr), &from_len);
            if (received > 0) {
                std::span<const uint8_t> packet_data(recv_buffer.data(),
                                                     static_cast<size_t>(received));
                // Identify or create connection based on source address
                std::string client_addr = sockaddr_to_string(from_addr);
                std::lock_guard lock(connections_mutex_);
                auto it = connections_.find(client_addr);
                if (it == connections_.end()) {
                    // New connection - create QUIC connection
                    auto initial_dcid = generate_random_cid();
                    auto new_conn = std::make_unique<protocols::quic::connection>(
                        true, initial_dcid);
                    // Initialize server handshake
                    auto init_result = new_conn->init_server_handshake(
                        config_.cert_file, config_.key_file);
                    if (!init_result.is_ok()) {
                        continue;
                    }
                    // Set transport parameters
                    protocols::quic::transport_parameters local_params;
                    local_params.initial_max_data = config_.initial_max_data;
                    local_params.initial_max_stream_data_bidi_local =
                        config_.initial_max_stream_data_bidi;
                    local_params.initial_max_stream_data_bidi_remote =
                        config_.initial_max_stream_data_bidi;
                    local_params.initial_max_stream_data_uni =
                        config_.initial_max_stream_data_uni;
                    local_params.initial_max_streams_bidi = config_.max_bidi_streams;
                    local_params.initial_max_streams_uni = config_.max_uni_streams;
                    if (config_.idle_timeout.count() > 0) {
                        local_params.max_idle_timeout =
                            static_cast<uint64_t>(config_.idle_timeout.count());
                    }
                    new_conn->set_local_params(local_params);
                    if (config_.enable_pmtud) {
                        new_conn->enable_pmtud();
                    }
                    connection_info info;
                    info.conn = std::move(new_conn);
                    info.last_activity = std::chrono::steady_clock::now();
                    connections_[client_addr] = std::move(info);
                    // Notify accept callback
                    std::lock_guard cb_lock(callbacks_mutex_);
                    if (callbacks_.on_accept) {
                        callbacks_.on_accept(client_addr);
                    }
                }
                // Process packet on existing connection
                auto conn_it = connections_.find(client_addr);
                if (conn_it != connections_.end() && conn_it->second.conn) {
                    auto result = conn_it->second.conn->receive_packet(packet_data);
                    (void)result;
                    conn_it->second.last_activity = std::chrono::steady_clock::now();
                }
            }
        }
        // Process all connections
        process_connections();
    }
    running_ = false;
    {
        std::lock_guard lock(stop_mutex_);
    }
    stop_cv_.notify_all();
}
References kcenon::network::protocols::quic::transport_parameters::initial_max_data, kcenon::network::protocols::quic::transport_parameters::initial_max_stream_data_bidi_local, kcenon::network::protocols::quic::transport_parameters::initial_max_stream_data_bidi_remote, kcenon::network::protocols::quic::transport_parameters::initial_max_stream_data_uni, kcenon::network::protocols::quic::transport_parameters::initial_max_streams_bidi, kcenon::network::protocols::quic::transport_parameters::initial_max_streams_uni, and kcenon::network::protocols::quic::transport_parameters::max_idle_timeout.
Referenced by start().
broadcast()
auto kcenon::network::unified::adapters::quic_listener_adapter::broadcast (std::span< const std::byte > data) -> VoidResult nodiscard override virtual
Broadcasts data to all connected clients.
Parameters
data The data to send to all connections
Returns
VoidResult indicating success or failure
Behavior
Sends data to all currently connected clients
Returns success if at least one send succeeded
Failures on individual connections are logged but don't fail the call
Implements kcenon::network::unified::i_listener.
Definition at line 252 of file quic_listener_adapter.cpp.
{
    std::lock_guard lock(connections_mutex_);
    bool any_success = false;
    for (auto& [conn_id, conn_info] : connections_) {
        if (conn_info.conn && conn_info.conn->is_established()) {
            auto& stream_mgr = conn_info.conn->streams();
            auto stream_result = stream_mgr.create_bidirectional_stream();
            if (stream_result.is_ok()) {
                auto* stream = stream_mgr.get_stream(stream_result.value());
                if (stream) {
                    std::vector<uint8_t> buffer(data.size());
                    std::memcpy(buffer.data(), data.data(), data.size());
                    auto write_result = stream->write(buffer);
                    if (write_result.is_ok()) {
                        any_success = true;
                    }
                }
            }
        }
    }
    if (!any_success && !connections_.empty()) {
        return error_void(
            static_cast<int>(std::errc::io_error),
            "Failed to send to any connection"
        );
    }
    return ok();
}
References kcenon::network::error_void(), and kcenon::network::ok().
close_connection()
auto kcenon::network::unified::adapters::quic_listener_adapter::close_connection (std::string_view connection_id) -> void override virtual noexcept
Closes a specific connection.
Parameters
connection_id The ID of the connection to close
Triggers the on_disconnect callback for the connection.
Implements kcenon::network::unified::i_listener.
Definition at line 287 of file quic_listener_adapter.cpp.
{
    std::lock_guard lock(connections_mutex_);
    auto it = connections_.find(std::string(connection_id));
    if (it != connections_.end()) {
        if (it->second.conn) {
            (void)it->second.conn->close(0, "Connection closed by server");
        }
        // Notify callback
        {
            std::lock_guard cb_lock(callbacks_mutex_);
            if (callbacks_.on_disconnect) {
                callbacks_.on_disconnect(connection_id);
            }
        }
        connections_.erase(it);
    }
}
connection_count()
auto kcenon::network::unified::adapters::quic_listener_adapter::connection_count () const -> size_t nodiscard override virtual noexcept
Gets the number of active connections.
Returns
The count of currently connected clients
Implements kcenon::network::unified::i_listener.
Definition at line 188 of file quic_listener_adapter.cpp.
{
    std::lock_guard lock(connections_mutex_);
    return connections_.size();
}
References connections_, and connections_mutex_.
generate_connection_id()
auto kcenon::network::unified::adapters::quic_listener_adapter::generate_connection_id (const protocols::quic::connection_id & cid) -> std::string private
Generate unique connection ID.
Definition at line 570 of file quic_listener_adapter.cpp.
{
    std::ostringstream oss;
    oss << std::hex;
    for (size_t i = 0; i < cid.length(); ++i) {
        oss << std::setfill('0') << std::setw(2)
            << static_cast<int>(cid.data()[i]);
    }
    return oss.str();
}
handle_new_connection()
auto kcenon::network::unified::adapters::quic_listener_adapter::handle_new_connection (std::unique_ptr< protocols::quic::connection > conn, const std::string & conn_id) -> void private
Handle new connection.
Definition at line 582 of file quic_listener_adapter.cpp.
{
    connection_info info;
    info.conn = std::move(conn);
    info.last_activity = std::chrono::steady_clock::now();
    {
        std::lock_guard lock(connections_mutex_);
        connections_[conn_id] = std::move(info);
    }
    std::lock_guard cb_lock(callbacks_mutex_);
    if (callbacks_.on_accept) {
        callbacks_.on_accept(conn_id);
    }
}
is_listening()
auto kcenon::network::unified::adapters::quic_listener_adapter::is_listening () const -> bool nodiscard override virtual noexcept
Checks if the listener is currently listening.
Returns
true if listening for connections, false otherwise
Implements kcenon::network::unified::i_listener.
Definition at line 177 of file quic_listener_adapter.cpp.
{
    return running_.load();
}
References running_.
local_endpoint()
auto kcenon::network::unified::adapters::quic_listener_adapter::local_endpoint () const -> endpoint_info nodiscard override virtual noexcept
Gets the local endpoint the listener is bound to.
Returns
endpoint_info of the local binding
Returns valid information only when listening. Returns empty endpoint_info if not bound.
Implements kcenon::network::unified::i_listener.
Definition at line 182 of file quic_listener_adapter.cpp.
{
    std::lock_guard lock(endpoint_mutex_);
    return local_endpoint_;
}
References endpoint_mutex_, and local_endpoint_.
operator=() [1/2]
quic_listener_adapter & kcenon::network::unified::adapters::quic_listener_adapter::operator= (const quic_listener_adapter &) delete
operator=() [2/2]
quic_listener_adapter & kcenon::network::unified::adapters::quic_listener_adapter::operator= (quic_listener_adapter &&) delete
process_connections()
auto kcenon::network::unified::adapters::quic_listener_adapter::process_connections () -> void private
Process incoming packets for all connections.
Definition at line 486 of file quic_listener_adapter.cpp.
{
    std::lock_guard lock(connections_mutex_);
    std::vector<std::string> to_remove;
    for (auto& [conn_id, conn_info] : connections_) {
        if (!conn_info.conn) {
            to_remove.push_back(conn_id);
            continue;
        }
        // Check for timeouts
        auto timeout = conn_info.conn->next_timeout();
        if (timeout && std::chrono::steady_clock::now() >= *timeout) {
            conn_info.conn->on_timeout();
        }
        // Generate and send packets
        auto packets = conn_info.conn->generate_packets();
        // Parse connection ID to get address for sending
        auto colon_pos = conn_id.rfind(':');
        if (colon_pos != std::string::npos && !packets.empty()) {
            std::string host = conn_id.substr(0, colon_pos);
            uint16_t port = static_cast<uint16_t>(
                std::stoi(conn_id.substr(colon_pos + 1)));
            sockaddr_in dest_addr{};
            dest_addr.sin_family = AF_INET;
            dest_addr.sin_port = htons(port);
            inet_pton(AF_INET, host.c_str(), &dest_addr.sin_addr);
            for (const auto& packet : packets) {
                sendto(socket_fd_, reinterpret_cast<const char*>(packet.data()),
                       static_cast<int>(packet.size()), 0,
                       reinterpret_cast<const sockaddr*>(&dest_addr),
                       sizeof(dest_addr));
            }
        }
        // Check for received data on streams
        if (conn_info.conn->is_established()) {
            auto& stream_mgr = conn_info.conn->streams();
            // Check bidirectional streams (client-initiated: 0, 4, 8, ...)
            for (uint64_t stream_id = 0; stream_id < 1000; stream_id += 4) {
                auto* stream = stream_mgr.get_stream(stream_id);
                if (stream && stream->has_data()) {
                    std::vector<uint8_t> buffer(4096);
                    auto read_result = stream->read(buffer);
                    if (read_result.is_ok() && read_result.value() > 0) {
                        buffer.resize(read_result.value());
                        std::lock_guard cb_lock(callbacks_mutex_);
                        if (callbacks_.on_data) {
                            std::span<const std::byte> byte_span(
                                reinterpret_cast<const std::byte*>(buffer.data()),
                                buffer.size()
                            );
                            callbacks_.on_data(conn_id, byte_span);
                        }
                    }
                }
            }
        }
        // Check if connection is closed
        if (conn_info.conn->is_closed()) {
            to_remove.push_back(conn_id);
            std::lock_guard cb_lock(callbacks_mutex_);
            if (callbacks_.on_disconnect) {
                callbacks_.on_disconnect(conn_id);
            }
        }
    }
    // Remove closed connections
    for (const auto& conn_id : to_remove) {
        connections_.erase(conn_id);
    }
}
send_to()
auto kcenon::network::unified::adapters::quic_listener_adapter::send_to (std::string_view connection_id, std::span< const std::byte > data) -> VoidResult nodiscard override virtual
Sends data to a specific connection.
Parameters
connection_id The ID of the target connection
data The data to send
Returns
VoidResult indicating success or failure
Error Conditions
Returns error if connection_id not found
Returns error if send fails
Implements kcenon::network::unified::i_listener.
Definition at line 194 of file quic_listener_adapter.cpp.
{
    std::lock_guard lock(connections_mutex_);
    auto it = connections_.find(std::string(connection_id));
    if (it == connections_.end()) {
        return error_void(
            static_cast<int>(std::errc::no_such_file_or_directory),
            "Connection not found"
        );
    }
    auto& conn_info = it->second;
    if (!conn_info.conn || !conn_info.conn->is_established()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "Connection is not established"
        );
    }
    // Write data to the first available bidirectional stream
    auto& stream_mgr = conn_info.conn->streams();
    // Create or get stream
    auto stream_result = stream_mgr.create_bidirectional_stream();
    if (!stream_result.is_ok()) {
        return error_void(
            static_cast<int>(std::errc::no_buffer_space),
            "Failed to create stream"
        );
    }
    auto* stream = stream_mgr.get_stream(stream_result.value());
    if (!stream) {
        return error_void(
            static_cast<int>(std::errc::io_error),
            "Failed to get stream"
        );
    }
    std::vector<uint8_t> buffer(data.size());
    std::memcpy(buffer.data(), data.data(), data.size());
    auto write_result = stream->write(buffer);
    if (!write_result.is_ok()) {
        return error_void(
            static_cast<int>(std::errc::io_error),
            "Failed to write to stream"
        );
    }
    conn_info.last_activity = std::chrono::steady_clock::now();
    return ok();
}
References kcenon::network::error_void(), and kcenon::network::ok().
set_accept_callback()
auto kcenon::network::unified::adapters::quic_listener_adapter::set_accept_callback (accept_callback_t callback) -> void override virtual
Sets the accept callback for new connections.
Parameters
callback Called when a connection is accepted
This callback receives ownership of the connection object. If set, the on_accept callback in listener_callbacks is not called.
Thread Safety
Thread-safe. Callback invoked from I/O thread.
Implements kcenon::network::unified::i_listener.
Definition at line 171 of file quic_listener_adapter.cpp.
{
    std::lock_guard lock(callbacks_mutex_);
    accept_callback_ = std::move(callback);
}
set_callbacks()
auto kcenon::network::unified::adapters::quic_listener_adapter::set_callbacks (listener_callbacks callbacks) -> void override virtual
Sets all listener callbacks at once.
Parameters
callbacks The callback structure with handlers
Replaces all previously set callbacks.
Thread Safety
Thread-safe, but callbacks are invoked from I/O threads.
Implements kcenon::network::unified::i_listener.
Definition at line 165 of file quic_listener_adapter.cpp.
{
    std::lock_guard lock(callbacks_mutex_);
    callbacks_ = std::move(callbacks);
}
setup_socket()
auto kcenon::network::unified::adapters::quic_listener_adapter::setup_socket (const endpoint_info & bind_address) -> VoidResult nodiscard private
Setup UDP socket for listening.
Definition at line 315 of file quic_listener_adapter.cpp.
{
#ifdef _WIN32
    WSADATA wsaData;
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
        return error_void(
            static_cast<int>(std::errc::io_error),
            "Failed to initialize Winsock"
        );
    }
#endif
    socket_fd_ = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (socket_fd_ < 0) {
        return error_void(
            static_cast<int>(std::errc::io_error),
            "Failed to create UDP socket"
        );
    }
    // Allow address reuse
    int reuse = 1;
    setsockopt(socket_fd_, SOL_SOCKET, SO_REUSEADDR,
               reinterpret_cast<const char*>(&reuse), sizeof(reuse));
    if (!set_nonblocking(socket_fd_)) {
        close_socket(socket_fd_);
        socket_fd_ = -1;
        return error_void(
            static_cast<int>(std::errc::io_error),
            "Failed to set socket to non-blocking mode"
        );
    }
    // Bind to address
    sockaddr_in bind_addr{};
    bind_addr.sin_family = AF_INET;
    bind_addr.sin_port = htons(bind_address.port);
    if (bind_address.host == "0.0.0.0" || bind_address.host.empty()) {
        bind_addr.sin_addr.s_addr = INADDR_ANY;
    } else {
        inet_pton(AF_INET, bind_address.host.c_str(), &bind_addr.sin_addr);
    }
    if (bind(socket_fd_, reinterpret_cast<sockaddr*>(&bind_addr), sizeof(bind_addr)) < 0) {
        close_socket(socket_fd_);
        socket_fd_ = -1;
        return error_void(
            static_cast<int>(std::errc::address_in_use),
            "Failed to bind socket to address"
        );
    }
    return ok();
}
References kcenon::network::error_void(), and kcenon::network::ok().
start() [1/2]
auto kcenon::network::unified::adapters::quic_listener_adapter::start (const endpoint_info & bind_address) -> VoidResult nodiscard override virtual
Starts listening for incoming connections.
Parameters
bind_address The local address to bind to
Returns
VoidResult indicating success or failure
Behavior
Binds to the specified local address
Begins accepting incoming connections
Accepted connections are delivered via callbacks
Error Conditions
Returns error if already listening
Returns error if bind fails (e.g., address in use)
Returns error if listen fails
Thread Safety
Thread-safe. Only one start operation can succeed at a time.
Implements kcenon::network::unified::i_listener.
Definition at line 92 of file quic_listener_adapter.cpp.
{
    if (running_.load()) {
        return error_void(
            static_cast<int>(std::errc::already_connected),
            "Listener is already running"
        );
    }
    // Validate that cert and key files are provided
    if (config_.cert_file.empty() || config_.key_file.empty()) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "QUIC server requires cert_file and key_file in configuration"
        );
    }
    auto setup_result = setup_socket(bind_address);
    if (!setup_result.is_ok()) {
        return setup_result;
    }
    {
        std::lock_guard lock(endpoint_mutex_);
        local_endpoint_ = bind_address;
    }
    running_ = true;
    stop_requested_ = false;
    // Start accept thread
    accept_thread_ = std::thread(&quic_listener_adapter::accept_thread_func, this);
    return ok();
}
References accept_thread_func(), kcenon::network::error_void(), and kcenon::network::ok().
start() [2/2]
auto kcenon::network::unified::adapters::quic_listener_adapter::start (uint16_t port) -> VoidResult nodiscard override virtual
Starts listening on a specific port (all interfaces)
Parameters
port The port number to listen on
Returns
VoidResult indicating success or failure
Convenience overload that binds to all interfaces (0.0.0.0 / ::).
Implements kcenon::network::unified::i_listener.
Definition at line 128 of file quic_listener_adapter.cpp.
{
    return start(endpoint_info{"0.0.0.0", port});
}
stop()
auto kcenon::network::unified::adapters::quic_listener_adapter::stop () -> void override virtual noexcept
Stops listening and closes all connections.
Behavior
Stops accepting new connections
Closes all active connections
Triggers on_disconnect callback for each connection
Thread Safety
Thread-safe. Safe to call multiple times.
Implements kcenon::network::unified::i_listener.
Definition at line 133 of file quic_listener_adapter.cpp.
{
    stop_requested_ = true;
    // Close all connections
    {
        std::lock_guard lock(connections_mutex_);
        for (auto& [conn_id, info] : connections_) {
            if (info.conn && info.conn->is_established()) {
                (void)info.conn->close(0, "Server shutting down");
            }
        }
        connections_.clear();
    }
    if (accept_thread_.joinable()) {
        accept_thread_.join();
    }
    if (socket_fd_ >= 0) {
        close_socket(socket_fd_);
        socket_fd_ = -1;
    }
    running_ = false;
    {
        std::lock_guard lock(stop_mutex_);
    }
    stop_cv_.notify_all();
}
References accept_thread_, connections_, connections_mutex_, running_, socket_fd_, stop_cv_, stop_mutex_, and stop_requested_.
Referenced by ~quic_listener_adapter().
wait_for_stop()
auto kcenon::network::unified::adapters::quic_listener_adapter::wait_for_stop () -> void override virtual
Blocks until the listener has stopped.
Waits for all connections to close and the listener to fully stop.
Thread Safety
Safe to call from any thread.
Implements kcenon::network::unified::i_listener.
Definition at line 309 of file quic_listener_adapter.cpp.
{
    std::unique_lock lock(stop_mutex_);
    stop_cv_.wait(lock, [this] { return !running_.load(); });
}
Member Data Documentation
accept_callback_
accept_callback_t kcenon::network::unified::adapters::quic_listener_adapter::accept_callback_ private
Definition at line 122 of file quic_listener_adapter.h.
accept_thread_
std::thread kcenon::network::unified::adapters::quic_listener_adapter::accept_thread_ private
Definition at line 115 of file quic_listener_adapter.h.
Referenced by stop().
callbacks_
listener_callbacks kcenon::network::unified::adapters::quic_listener_adapter::callbacks_ private
Definition at line 121 of file quic_listener_adapter.h.
callbacks_mutex_
std::mutex kcenon::network::unified::adapters::quic_listener_adapter::callbacks_mutex_ mutable private
Definition at line 120 of file quic_listener_adapter.h.
config_
protocol::quic::quic_config kcenon::network::unified::adapters::quic_listener_adapter::config_ private
Definition at line 109 of file quic_listener_adapter.h.
connections_
std::unordered_map<std::string, connection_info> kcenon::network::unified::adapters::quic_listener_adapter::connections_ private
Definition at line 135 of file quic_listener_adapter.h.
Referenced by connection_count(), and stop().
connections_mutex_
std::mutex kcenon::network::unified::adapters::quic_listener_adapter::connections_mutex_ mutable private
Definition at line 134 of file quic_listener_adapter.h.
Referenced by connection_count(), and stop().
endpoint_mutex_
std::mutex kcenon::network::unified::adapters::quic_listener_adapter::endpoint_mutex_ mutable private
Definition at line 125 of file quic_listener_adapter.h.
Referenced by local_endpoint().
listener_id_
std::string kcenon::network::unified::adapters::quic_listener_adapter::listener_id_ private
Definition at line 108 of file quic_listener_adapter.h.
local_endpoint_
endpoint_info kcenon::network::unified::adapters::quic_listener_adapter::local_endpoint_ private
Definition at line 126 of file quic_listener_adapter.h.
Referenced by local_endpoint().
running_
std::atomic<bool> kcenon::network::unified::adapters::quic_listener_adapter::running_ {false} private
Definition at line 116 of file quic_listener_adapter.h.
{false};
Referenced by is_listening(), and stop().
socket_fd_
int kcenon::network::unified::adapters::quic_listener_adapter::socket_fd_ {-1} private
Definition at line 112 of file quic_listener_adapter.h.
{-1};
Referenced by stop().
stop_cv_
std::condition_variable kcenon::network::unified::adapters::quic_listener_adapter::stop_cv_ private
Definition at line 139 of file quic_listener_adapter.h.
Referenced by stop().
stop_mutex_
std::mutex kcenon::network::unified::adapters::quic_listener_adapter::stop_mutex_ mutable private
Definition at line 138 of file quic_listener_adapter.h.
Referenced by stop().
stop_requested_
std::atomic<bool> kcenon::network::unified::adapters::quic_listener_adapter::stop_requested_ {false} private
Definition at line 117 of file quic_listener_adapter.h.
{false};
Referenced by stop().
The documentation for this class was generated from the following files:
src/internal/unified/adapters/quic_listener_adapter.h
src/unified/adapters/quic_listener_adapter.cpp