Network System: kcenon::network::internal::adapters::quic_client_adapter Class Reference
kcenon::network::internal::adapters::quic_client_adapter Class Reference
Adapter that wraps messaging_quic_client to implement i_protocol_client.
#include <quic_client_adapter.h>
Public Member Functions
quic_client_adapter (std::string_view client_id)
Constructs an adapter with a unique client ID.
~quic_client_adapter () override
Destructor ensures proper cleanup.
quic_client_adapter (const quic_client_adapter &)=delete
quic_client_adapter & operator= (const quic_client_adapter &)=delete
quic_client_adapter (quic_client_adapter &&)=delete
quic_client_adapter & operator= (quic_client_adapter &&)=delete
auto set_alpn_protocols (const std::vector< std::string > &protocols) -> void
Sets the ALPN protocols for negotiation.
auto set_ca_cert_path (std::string_view path) -> void
Sets CA certificate path for server verification.
auto set_client_cert (std::string_view cert_path, std::string_view key_path) -> void
Sets client certificate path for mutual TLS.
auto set_verify_server (bool verify) -> void
Sets whether to verify server certificate.
auto set_max_idle_timeout (uint64_t timeout_ms) -> void
Sets max idle timeout in milliseconds.
auto is_running () const -> bool override
Checks if the component is currently running.
auto wait_for_stop () -> void override
Blocks until the component has stopped.
auto start (std::string_view host, uint16_t port) -> VoidResult override
Starts the client and connects to the specified server.
auto stop () -> VoidResult override
Stops the client and closes the connection.
auto send (std::vector< uint8_t > &&data) -> VoidResult override
Sends data to the connected server.
auto is_connected () const -> bool override
Checks if the client is connected to the server.
auto set_observer (std::shared_ptr< interfaces::connection_observer > observer) -> void override
Sets the connection observer for unified event handling.
auto set_receive_callback (receive_callback_t callback) -> void override
Sets the callback for received data.
auto set_connected_callback (connected_callback_t callback) -> void override
Sets the callback for connection established.
auto set_disconnected_callback (disconnected_callback_t callback) -> void override
Sets the callback for disconnection.
auto set_error_callback (error_callback_t callback) -> void override
Sets the callback for errors.
Public Member Functions inherited from kcenon::network::interfaces::i_protocol_client
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Member Functions
auto setup_internal_callbacks () -> void
Sets up internal callbacks to bridge QUIC callbacks to i_protocol_client callbacks.
Private Attributes
std::string client_id_
std::shared_ptr< core::messaging_quic_client > client_
std::vector< std::string > alpn_protocols_
std::optional< std::string > ca_cert_path_
std::optional< std::string > client_cert_path_
std::optional< std::string > client_key_path_
bool verify_server_ {true}
uint64_t max_idle_timeout_ms_ {30000}
std::mutex callbacks_mutex_
std::shared_ptr< interfaces::connection_observer > observer_
receive_callback_t receive_callback_
connected_callback_t connected_callback_
disconnected_callback_t disconnected_callback_
error_callback_t error_callback_
Additional Inherited Members
Public Types inherited from kcenon::network::interfaces::i_protocol_client
using receive_callback_t = std::function<void(const std::vector<uint8_t>&)>
Callback type for received data.
using connected_callback_t = std::function<void()>
Callback type for connection established.
using disconnected_callback_t = std::function<void()>
Callback type for disconnection.
using error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps messaging_quic_client to implement i_protocol_client.
This adapter bridges the QUIC client implementation with the unified i_protocol_client interface. It allows quic_facade to return i_protocol_client without modifying the existing messaging_quic_client class.
Design Rationale
The adapter pattern is used because:
QUIC's i_quic_client has additional methods (multi-stream, 0-RTT, ALPN)
QUIC always uses TLS 1.3, so SSL/TLS configuration is implicit
For QUIC-specific features, users should use messaging_quic_client directly
ALPN Configuration
ALPN protocols can be configured via set_alpn_protocols() before start(). Common values: "h3" (HTTP/3), "hq-29" (HTTP/QUIC draft-29)
Message Handling
send() sends data on the default stream (stream 0)
For multi-stream operations, use messaging_quic_client directly
Thread Safety
Thread-safe. All methods can be called from any thread.
See also
i_protocol_client
messaging_quic_client
Definition at line 51 of file quic_client_adapter.h.
Constructor & Destructor Documentation
quic_client_adapter() [1/3]
kcenon::network::internal::adapters::quic_client_adapter::quic_client_adapter (std::string_view client_id) explicit
Constructs an adapter with a unique client ID.
Parameters
client_id Unique identifier for this client
Definition at line 22 of file quic_client_adapter.cpp.
    : client_id_(client_id)
    , client_(std::make_shared<core::messaging_quic_client>(client_id))
{
    setup_internal_callbacks();
}
References setup_internal_callbacks().
~quic_client_adapter()
kcenon::network::internal::adapters::quic_client_adapter::~quic_client_adapter () override
Destructor ensures proper cleanup.
Definition at line 29 of file quic_client_adapter.cpp.
{
    if (client_ && client_->is_running())
    {
        (void)client_->stop();
    }
}
References client_.
quic_client_adapter() [2/3]
kcenon::network::internal::adapters::quic_client_adapter::quic_client_adapter (const quic_client_adapter &) delete
quic_client_adapter() [3/3]
kcenon::network::internal::adapters::quic_client_adapter::quic_client_adapter (quic_client_adapter &&) delete
Member Function Documentation
is_connected()
auto kcenon::network::internal::adapters::quic_client_adapter::is_connected () const -> bool nodiscard override virtual
Checks if the client is connected to the server.
Returns
true if connected, false otherwise.
Connection States
Not started: is_running() == false, is_connected() == false
Starting/Connecting: is_running() == true, is_connected() == false
Connected: is_running() == true, is_connected() == true
Disconnected: is_running() == true, is_connected() == false
Stopped: is_running() == false, is_connected() == false
Protocol-Specific Notes
TCP/WebSocket/QUIC: Returns true only when connection is established
UDP: Returns true when target endpoint is set (no actual "connection")
HTTP: Returns true if connection pool has active connections
Thread Safety
Thread-safe. Uses atomic operations for state checking.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 152 of file quic_client_adapter.cpp.
{
    return client_ && client_->is_connected();
}
References client_.
is_running()
auto kcenon::network::internal::adapters::quic_client_adapter::is_running () const -> bool nodiscard override virtual
Checks if the component is currently running.
Returns
true if the component is active, false otherwise.
This method must be thread-safe and use atomic operations for the running state.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 75 of file quic_client_adapter.cpp.
{
    return client_ && client_->is_running();
}
References client_.
operator=() [1/2]
quic_client_adapter & kcenon::network::internal::adapters::quic_client_adapter::operator= (const quic_client_adapter &) delete
operator=() [2/2]
quic_client_adapter & kcenon::network::internal::adapters::quic_client_adapter::operator= (quic_client_adapter &&) delete
send()
auto kcenon::network::internal::adapters::quic_client_adapter::send (std::vector< uint8_t > && data) -> VoidResult nodiscard override virtual
Sends data to the connected server.
Parameters
data The data to send.
Returns
VoidResult indicating success or failure.
Behavior
Queues data for transmission
May block if send queue is full (protocol-dependent)
Data is moved, not copied
Error Conditions
Returns error if not connected
Returns error if send buffer is full
Returns error if underlying protocol send fails
Protocol-Specific Notes
TCP: Stream-based, may fragment data
UDP: Datagram-based, preserves message boundaries
WebSocket: Frame-based, preserves message boundaries
HTTP: Typically request/response, may queue
Thread Safety
Thread-safe. Multiple sends may be queued concurrently. Send operations are serialized internally.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 129 of file quic_client_adapter.cpp.
{
    if (!client_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Client not initialized",
            "quic_client_adapter::send"
        );
    }
    if (!client_->is_connected())
    {
        return error_void(
            error_codes::common_errors::invalid_argument,
            "Client is not connected",
            "quic_client_adapter::send"
        );
    }
    return client_->send(std::move(data));
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, and kcenon::network::error_codes::common_errors::invalid_argument.
set_alpn_protocols()
auto kcenon::network::internal::adapters::quic_client_adapter::set_alpn_protocols (const std::vector< std::string > & protocols) -> void
Sets the ALPN protocols for negotiation.
Parameters
protocols List of protocol identifiers (e.g., {"h3", "hq-29"})
Must be called before start() to take effect.
Definition at line 41 of file quic_client_adapter.cpp.
{
    alpn_protocols_ = protocols;
    if (client_)
    {
        client_->set_alpn_protocols(protocols);
    }
}
set_ca_cert_path()
auto kcenon::network::internal::adapters::quic_client_adapter::set_ca_cert_path (std::string_view path) -> void
Sets CA certificate path for server verification.
Parameters
path Path to CA certificate file (PEM format)
Definition at line 50 of file quic_client_adapter.cpp.
{
    ca_cert_path_ = std::string(path);
}
set_client_cert()
auto kcenon::network::internal::adapters::quic_client_adapter::set_client_cert (std::string_view cert_path, std::string_view key_path) -> void
Sets client certificate path for mutual TLS.
Parameters
cert_path Path to client certificate file (PEM format)
key_path Path to client private key file (PEM format)
Definition at line 55 of file quic_client_adapter.cpp.
{
    client_cert_path_ = std::string(cert_path);
    client_key_path_ = std::string(key_path);
}
set_connected_callback()
auto kcenon::network::internal::adapters::quic_client_adapter::set_connected_callback (connected_callback_t callback) -> void override virtual
Sets the callback for connection established.
Parameters
callback The callback function.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 169 of file quic_client_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    connected_callback_ = std::move(callback);
}
set_disconnected_callback()
auto kcenon::network::internal::adapters::quic_client_adapter::set_disconnected_callback (disconnected_callback_t callback) -> void override virtual
Sets the callback for disconnection.
Parameters
callback The callback function.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 175 of file quic_client_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    disconnected_callback_ = std::move(callback);
}
set_error_callback()
auto kcenon::network::internal::adapters::quic_client_adapter::set_error_callback (error_callback_t callback) -> void override virtual
Sets the callback for errors.
Parameters
callback The callback function.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 181 of file quic_client_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    error_callback_ = std::move(callback);
}
set_max_idle_timeout()
auto kcenon::network::internal::adapters::quic_client_adapter::set_max_idle_timeout (uint64_t timeout_ms) -> void
Sets max idle timeout in milliseconds.
Parameters
timeout_ms Maximum idle timeout (default: 30000)
Definition at line 66 of file quic_client_adapter.cpp.
{
    max_idle_timeout_ms_ = timeout_ms;
}
set_observer()
auto kcenon::network::internal::adapters::quic_client_adapter::set_observer (std::shared_ptr< interfaces::connection_observer > observer) -> void override virtual
Sets the connection observer for unified event handling.
Parameters
observer The observer instance (shared ownership).
The observer receives all connection events through a single interface:
on_connected(): Connection established
on_disconnected(): Connection lost or closed
on_receive(data): Data received from server
on_error(error_code): Error occurred
Recommended Pattern
This is the preferred method for event handling as it:
Centralizes all event handling in one place
Provides consistent interface across all protocols
Enables easier testing through mock observers
Usage
class my_observer : public connection_observer {
    void on_connected() override { // handle connect
    }
    void on_receive(const std::vector<uint8_t>& data) override {
        // handle data
    }
    // ... implement other methods
};
client->set_observer(std::make_shared<my_observer>());
Thread Safety
Thread-safe. Observer methods may be invoked from I/O threads. Observer must be thread-safe if shared across multiple clients.
See also
connection_observer
callback_adapter
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 157 of file quic_client_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    observer_ = std::move(observer);
}
set_receive_callback()
auto kcenon::network::internal::adapters::quic_client_adapter::set_receive_callback (receive_callback_t callback) -> void override virtual
Sets the callback for received data.
Parameters
callback The callback function.
Thread Safety
Thread-safe. The callback may be invoked from I/O threads. Callback must be thread-safe if it accesses shared state.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 163 of file quic_client_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    receive_callback_ = std::move(callback);
}
set_verify_server()
auto kcenon::network::internal::adapters::quic_client_adapter::set_verify_server (bool verify) -> void
Sets whether to verify server certificate.
Parameters
verify True to verify (default), false to skip verification
Definition at line 61 of file quic_client_adapter.cpp.
{
    verify_server_ = verify;
}
setup_internal_callbacks()
auto kcenon::network::internal::adapters::quic_client_adapter::setup_internal_callbacks () -> void private
Sets up internal callbacks to bridge QUIC callbacks to i_protocol_client callbacks.
Definition at line 191 of file quic_client_adapter.cpp.
{
    if (!client_)
    {
        return;
    }
    // Bridge receive callback
    client_->set_receive_callback([this](const std::vector<uint8_t>& data) {
        std::shared_ptr<interfaces::connection_observer> observer_copy;
        receive_callback_t callback_copy;
        {
            std::lock_guard<std::mutex> lock(callbacks_mutex_);
            observer_copy = observer_;
            callback_copy = receive_callback_;
        }
        if (observer_copy)
        {
            observer_copy->on_receive(data);
        }
        if (callback_copy)
        {
            callback_copy(data);
        }
    });
    // Bridge connected callback
    client_->set_connected_callback([this]() {
        std::shared_ptr<interfaces::connection_observer> observer_copy;
        connected_callback_t callback_copy;
        {
            std::lock_guard<std::mutex> lock(callbacks_mutex_);
            observer_copy = observer_;
            callback_copy = connected_callback_;
        }
        if (observer_copy)
        {
            observer_copy->on_connected();
        }
        if (callback_copy)
        {
            callback_copy();
        }
    });
    // Bridge disconnected callback
    client_->set_disconnected_callback([this]() {
        std::shared_ptr<interfaces::connection_observer> observer_copy;
        disconnected_callback_t callback_copy;
        {
            std::lock_guard<std::mutex> lock(callbacks_mutex_);
            observer_copy = observer_;
            callback_copy = disconnected_callback_;
        }
        if (observer_copy)
        {
            observer_copy->on_disconnected();
        }
        if (callback_copy)
        {
            callback_copy();
        }
    });
    // Bridge error callback
    client_->set_error_callback([this](std::error_code ec) {
        std::shared_ptr<interfaces::connection_observer> observer_copy;
        error_callback_t callback_copy;
        {
            std::lock_guard<std::mutex> lock(callbacks_mutex_);
            observer_copy = observer_;
            callback_copy = error_callback_;
        }
        if (observer_copy)
        {
            observer_copy->on_error(ec);
        }
        if (callback_copy)
        {
            callback_copy(ec);
        }
    });
}
Referenced by quic_client_adapter().
start()
auto kcenon::network::internal::adapters::quic_client_adapter::start (std::string_view host, uint16_t port) -> VoidResult nodiscard override virtual
Starts the client and connects to the specified server.
Parameters
host The server hostname or IP address.
port The server port number.
Returns
VoidResult indicating success or failure.
Behavior
Creates the underlying protocol-specific connection
Resolves hostname to IP address if needed
Establishes connection with the server
Begins receiving data (for connection-oriented protocols)
Invokes connected callback/observer on success
Error Conditions
Returns error if already running
Returns error if host resolution fails
Returns error if connection establishment fails
Returns error if underlying protocol initialization fails
Protocol-Specific Notes
TCP/WebSocket/QUIC: Establishes stateful connection
UDP: Sets default target endpoint, does not "connect" in traditional sense
HTTP: May establish connection pool or persistent connection
Thread Safety
Thread-safe. Only one start operation can succeed at a time. Subsequent calls while running will return an error.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 92 of file quic_client_adapter.cpp.
{
    if (!client_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Client not initialized",
            "quic_client_adapter::start"
        );
    }
    // Build configuration
    core::quic_client_config config;
    config.ca_cert_file = ca_cert_path_;
    config.client_cert_file = client_cert_path_;
    config.client_key_file = client_key_path_;
    config.verify_server = verify_server_;
    config.alpn_protocols = alpn_protocols_;
    config.max_idle_timeout_ms = max_idle_timeout_ms_;
    return client_->start_client(host, port, config);
}
References config, kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::internal_error.
stop()
auto kcenon::network::internal::adapters::quic_client_adapter::stop () -> VoidResult nodiscard override virtual
Stops the client and closes the connection.
Returns
VoidResult indicating success or failure.
Behavior
Cancels all pending operations
Closes the connection gracefully if possible
Invokes disconnected callback/observer
Releases protocol-specific resources
Error Conditions
Returns error if not running
Protocol-Specific Notes
TCP: Sends FIN, waits for graceful close
WebSocket: Sends close frame with status code
UDP: Stops receiving, no "close" required
QUIC: Sends CONNECTION_CLOSE frame
Thread Safety
Thread-safe. Safe to call from any thread including callbacks. Pending operations will be cancelled and cleaned up.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 115 of file quic_client_adapter.cpp.
{
    if (!client_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Client not initialized",
            "quic_client_adapter::stop"
        );
    }
    return client_->stop_client();
}
References kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::internal_error.
wait_for_stop()
auto kcenon::network::internal::adapters::quic_client_adapter::wait_for_stop () -> void override virtual
Blocks until the component has stopped.
This method should be used to synchronize shutdown operations. It returns immediately if the component is not running.
Thread Safety
Safe to call from any thread. Uses internal synchronization.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 80 of file quic_client_adapter.cpp.
{
    if (client_)
    {
        client_->wait_for_stop();
    }
}
Member Data Documentation
alpn_protocols_
std::vector<std::string> kcenon::network::internal::adapters::quic_client_adapter::alpn_protocols_ private
Definition at line 140 of file quic_client_adapter.h.
ca_cert_path_
std::optional<std::string> kcenon::network::internal::adapters::quic_client_adapter::ca_cert_path_ private
Definition at line 141 of file quic_client_adapter.h.
callbacks_mutex_
std::mutex kcenon::network::internal::adapters::quic_client_adapter::callbacks_mutex_ mutable private
Definition at line 147 of file quic_client_adapter.h.
client_
std::shared_ptr<core::messaging_quic_client> kcenon::network::internal::adapters::quic_client_adapter::client_ private
Definition at line 137 of file quic_client_adapter.h.
Referenced by is_connected(), is_running(), and ~quic_client_adapter().
client_cert_path_
std::optional<std::string> kcenon::network::internal::adapters::quic_client_adapter::client_cert_path_ private
Definition at line 142 of file quic_client_adapter.h.
client_id_
std::string kcenon::network::internal::adapters::quic_client_adapter::client_id_ private
Definition at line 136 of file quic_client_adapter.h.
client_key_path_
std::optional<std::string> kcenon::network::internal::adapters::quic_client_adapter::client_key_path_ private
Definition at line 143 of file quic_client_adapter.h.
connected_callback_
connected_callback_t kcenon::network::internal::adapters::quic_client_adapter::connected_callback_ private
Definition at line 150 of file quic_client_adapter.h.
disconnected_callback_
disconnected_callback_t kcenon::network::internal::adapters::quic_client_adapter::disconnected_callback_ private
Definition at line 151 of file quic_client_adapter.h.
error_callback_
error_callback_t kcenon::network::internal::adapters::quic_client_adapter::error_callback_ private
Definition at line 152 of file quic_client_adapter.h.
max_idle_timeout_ms_
uint64_t kcenon::network::internal::adapters::quic_client_adapter::max_idle_timeout_ms_ {30000} private
Definition at line 145 of file quic_client_adapter.h.
{30000};
observer_
std::shared_ptr<interfaces::connection_observer> kcenon::network::internal::adapters::quic_client_adapter::observer_ private
Definition at line 148 of file quic_client_adapter.h.
receive_callback_
receive_callback_t kcenon::network::internal::adapters::quic_client_adapter::receive_callback_ private
Definition at line 149 of file quic_client_adapter.h.
verify_server_
bool kcenon::network::internal::adapters::quic_client_adapter::verify_server_ {true} private
Definition at line 144 of file quic_client_adapter.h.
{true};
The documentation for this class was generated from the following files:
src/internal/adapters/quic_client_adapter.h
src/adapters/quic_client_adapter.cpp