Network System: kcenon::network::facade::udp_facade Class Reference
kcenon::network::facade::udp_facade Class Reference
Simplified facade for creating UDP clients and servers.
#include <udp_facade.h>
Classes
struct client_config
Configuration for creating a UDP client.
struct server_config
Configuration for creating a UDP server.
Public Member Functions
auto create_client (const client_config &config) const -> Result< std::shared_ptr< interfaces::i_protocol_client > >
Creates a UDP client with the specified configuration.
auto create_server (const server_config &config) const -> Result< std::shared_ptr< interfaces::i_protocol_server > >
Creates a UDP server with the specified configuration.
Static Private Member Functions
static auto generate_client_id () -> std::string
Generates a unique client ID.
static auto generate_server_id () -> std::string
Generates a unique server ID.
static auto validate_client_config (const client_config &config) -> VoidResult
Validates client configuration.
static auto validate_server_config (const server_config &config) -> VoidResult
Validates server configuration.
Detailed Description
Simplified facade for creating UDP clients and servers.
This facade provides a simple, unified API for creating UDP protocol clients and servers, hiding the complexity of template parameters, protocol tags, and implementation details from the user.
Design Goals
Simplicity: No template parameters or protocol tags
Consistency: Same API pattern across all protocol facades
Type Safety: Returns standard IProtocolClient/IProtocolServer interfaces
Zero Cost: No performance overhead compared to direct instantiation
Thread Safety
All methods are thread-safe and can be called concurrently.
Usage Example
using namespace kcenon::network::facade;
// Create UDP client
udp_facade facade;
auto client = facade.create_client({
    .host = "127.0.0.1",
    .port = 5555,
    .client_id = "my-udp-client"
});
// Create UDP server
auto server = facade.create_server({
    .port = 5555,
    .server_id = "my-udp-server"
});
See also
interfaces::i_protocol_client
interfaces::i_protocol_server
Examples
udp_echo.cpp.
Definition at line 71 of file udp_facade.h.
Member Function Documentation
create_client()
auto kcenon::network::facade::udp_facade::create_client (const client_config & config) const -> Result<std::shared_ptr<interfaces::i_protocol_client>> nodiscard
Creates a UDP client with the specified configuration.
Parameters
config Client configuration.
Returns
Result containing shared pointer to IProtocolClient, or error.
Behavior
Creates a UDP client adapter wrapping messaging_udp_client
Client ID is auto-generated if not provided
Automatically connects to the specified target endpoint
Error Conditions
Returns error if host is empty
Returns error if port is 0 or > 65535
Definition at line 68 of file udp_facade.cpp.
{
    // Validate configuration
    auto validation = validate_client_config(config);
    if (validation.is_err())
    {
        return error<std::shared_ptr<interfaces::i_protocol_client>>(
            validation.error().code, validation.error().message, "udp_facade");
    }
    // Generate client ID if not provided
    const std::string client_id = config.client_id.empty() ? generate_client_id() : config.client_id;
    // Create UDP client adapter that wraps messaging_udp_client
    auto client = std::make_shared<internal::adapters::udp_client_adapter>(client_id);
    // Start the client and connect to target
    auto result = client->start(config.host, config.port);
    if (result.is_err())
    {
        return error<std::shared_ptr<interfaces::i_protocol_client>>(
            -600, "udp_facade: failed to start client: " + result.error().message, "udp_facade");
    }
    return ok(std::shared_ptr<interfaces::i_protocol_client>(client));
}
References config, kcenon::network::error, kcenon::network::message, and kcenon::network::ok().
create_server()
auto kcenon::network::facade::udp_facade::create_server (const server_config & config) const -> Result<std::shared_ptr<interfaces::i_protocol_server>> nodiscard
Creates a UDP server with the specified configuration.
Parameters
config Server configuration.
Returns
Result containing shared pointer to IProtocolServer, or error.
Behavior
Creates a UDP server adapter wrapping messaging_udp_server
Server ID is auto-generated if not provided
Automatically starts listening on the specified port
Error Conditions
Returns error if port is 0 or > 65535
Definition at line 96 of file udp_facade.cpp.
{
    // Validate configuration
    auto validation = validate_server_config(config);
    if (validation.is_err())
    {
        return error<std::shared_ptr<interfaces::i_protocol_server>>(
            validation.error().code, validation.error().message, "udp_facade");
    }
    // Generate server ID if not provided
    const std::string server_id = config.server_id.empty() ? generate_server_id() : config.server_id;
    // Create UDP server adapter that wraps messaging_udp_server
    auto server = std::make_shared<internal::adapters::udp_server_adapter>(server_id);
    // Start the server
    auto result = server->start(config.port);
    if (result.is_err())
    {
        return error<std::shared_ptr<interfaces::i_protocol_server>>(
            -660, "udp_facade: failed to start server: " + result.error().message, "udp_facade");
    }
    return ok(std::shared_ptr<interfaces::i_protocol_server>(server));
}
References config, kcenon::network::error, kcenon::network::message, and kcenon::network::ok().
generate_client_id()
auto kcenon::network::facade::udp_facade::generate_client_id () -> std::string static nodiscard private
Generates a unique client ID.
Definition at line 27 of file udp_facade.cpp.
{
    const auto id = g_client_id_counter.fetch_add(1, std::memory_order_relaxed);
    std::ostringstream oss;
    oss << "udp_client_" << std::setfill('0') << std::setw(8) << id;
    return oss.str();
}
generate_server_id()
auto kcenon::network::facade::udp_facade::generate_server_id () -> std::string static nodiscard private
Generates a unique server ID.
Definition at line 35 of file udp_facade.cpp.
{
    const auto id = g_server_id_counter.fetch_add(1, std::memory_order_relaxed);
    std::ostringstream oss;
    oss << "udp_server_" << std::setfill('0') << std::setw(8) << id;
    return oss.str();
}
validate_client_config()
auto kcenon::network::facade::udp_facade::validate_client_config (const client_config & config) -> VoidResult static private
Validates client configuration.
Definition at line 43 of file udp_facade.cpp.
{
    if (config.host.empty())
    {
        return error_void(-1, "udp_facade: host cannot be empty", "udp_facade");
    }
    if (config.port == 0 || config.port > 65535)
    {
        return error_void(-1, "udp_facade: port must be between 1 and 65535", "udp_facade");
    }
    return ok();
}
References config, kcenon::network::error_void(), and kcenon::network::ok().
validate_server_config()
auto kcenon::network::facade::udp_facade::validate_server_config (const server_config & config) -> VoidResult static private
Validates server configuration.
Definition at line 58 of file udp_facade.cpp.
{
    if (config.port == 0 || config.port > 65535)
    {
        return error_void(-1, "udp_facade: port must be between 1 and 65535", "udp_facade");
    }
    return ok();
}
References config, kcenon::network::error_void(), and kcenon::network::ok().
The documentation for this class was generated from the following files:
include/kcenon/network/facade/udp_facade.h
src/facade/udp_facade.cpp