Network System: kcenon::network::integration::io_context_thread_manager::impl Class Reference
kcenon::network::integration::io_context_thread_manager::impl Class Reference
Classes
struct context_entry
Public Member Functions
impl ()
~impl ()
std::shared_ptr< thread_pool_interface > get_thread_pool ()
std::future< void > run_io_context (std::shared_ptr< asio::io_context > io_context, const std::string &component_name)
void stop_io_context (std::shared_ptr< asio::io_context > io_context)
void stop_all ()
void wait_all ()
size_t active_count () const
bool is_active (std::shared_ptr< asio::io_context > io_context) const
void set_thread_pool (std::shared_ptr< thread_pool_interface > pool)
io_context_thread_manager::metrics get_metrics () const
Private Member Functions
void cleanup_expired ()
Private Attributes
std::mutex mutex_
std::shared_ptr< thread_pool_interface > thread_pool_
std::vector< context_entry > entries_
std::atomic< size_t > total_started_
std::atomic< size_t > total_completed_
Detailed Description
Definition at line 23 of file io_context_thread_manager.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::integration::io_context_thread_manager::impl::impl () inline
Definition at line 30 of file io_context_thread_manager.cpp.
: total_started_(0), total_completed_(0) {}
~impl()
kcenon::network::integration::io_context_thread_manager::impl::~impl () inline
Definition at line 32 of file io_context_thread_manager.cpp.
            {
        stop_all();
        wait_all();
    }
References stop_all(), and wait_all().
Member Function Documentation
active_count()
size_t kcenon::network::integration::io_context_thread_manager::impl::active_count () const inline
Definition at line 169 of file io_context_thread_manager.cpp.
{
        std::lock_guard<std::mutex> lock(mutex_);
        size_t count = 0;
        for (const auto& entry : entries_) {
            auto ctx = entry.context.lock();
            if (ctx && !ctx->stopped()) {
                ++count;
            }
        }
        return count;
    }
References entries_, and mutex_.
Referenced by get_metrics().
cleanup_expired()
void kcenon::network::integration::io_context_thread_manager::impl::cleanup_expired () inline private
Definition at line 210 of file io_context_thread_manager.cpp.
{
        std::lock_guard<std::mutex> lock(mutex_);
        entries_.erase(
            std::remove_if(entries_.begin(), entries_.end(),
                [](const context_entry& entry) {
                    return entry.context.expired();
                }),
            entries_.end()
        );
    }
References entries_, and mutex_.
Referenced by run_io_context().
get_metrics()
io_context_thread_manager::metrics kcenon::network::integration::io_context_thread_manager::impl::get_metrics () const inline
Definition at line 201 of file io_context_thread_manager.cpp.
{
        io_context_thread_manager::metrics m;
        m.active_contexts = active_count();
        m.total_started = total_started_.load(std::memory_order_relaxed);
        m.total_completed = total_completed_.load(std::memory_order_relaxed);
        return m;
    }
References kcenon::network::integration::io_context_thread_manager::metrics::active_contexts, active_count(), kcenon::network::integration::io_context_thread_manager::metrics::total_completed, total_completed_, kcenon::network::integration::io_context_thread_manager::metrics::total_started, and total_started_.
get_thread_pool()
std::shared_ptr< thread_pool_interface > kcenon::network::integration::io_context_thread_manager::impl::get_thread_pool () inline
Definition at line 37 of file io_context_thread_manager.cpp.
{
        std::lock_guard<std::mutex> lock(mutex_);
        if (!thread_pool_) {
            thread_pool_ = kcenon::network::core::network_context::instance().get_thread_pool();
            if (!thread_pool_) {
                // Fallback to basic thread pool with size for concurrent io_contexts
                // Tests like ConnectionScaling need 20+ clients + server
                // Use larger size to avoid thread exhaustion
                auto pool_size = std::max(32u, std::thread::hardware_concurrency() * 4);
                thread_pool_ = std::make_shared<basic_thread_pool>(pool_size);
            }
        }
        return thread_pool_;
    }
References kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), mutex_, and thread_pool_.
Referenced by run_io_context().
is_active()
bool kcenon::network::integration::io_context_thread_manager::impl::is_active (std::shared_ptr< asio::io_context > io_context) const inline
Definition at line 181 of file io_context_thread_manager.cpp.
{
        if (!io_context) {
            return false;
        }
        std::lock_guard<std::mutex> lock(mutex_);
        for (const auto& entry : entries_) {
            auto ctx = entry.context.lock();
            if (ctx && ctx.get() == io_context.get() && !ctx->stopped()) {
                return true;
            }
        }
        return false;
    }
References entries_, and mutex_.
run_io_context()
std::future< void > kcenon::network::integration::io_context_thread_manager::impl::run_io_context (std::shared_ptr< asio::io_context > io_context, const std::string & component_name) inline
Definition at line 52 of file io_context_thread_manager.cpp.
      {
        auto pool = get_thread_pool();
        if (!pool) {
            auto promise = std::make_shared<std::promise<void>>();
            promise->set_exception(
                std::make_exception_ptr(
                    std::runtime_error("Thread pool not available")
                )
            );
            return promise->get_future();
        }
        // Submit io_context::run to thread pool
        auto ctx_weak = std::weak_ptr<asio::io_context>(io_context);
        auto name = component_name.empty() ? "unnamed" : component_name;
        // Create a shared promise for the caller's future
        auto caller_promise = std::make_shared<std::promise<void>>();
        auto caller_future = caller_promise->get_future();
        // Track the entry for metrics and stop_all functionality
        {
            std::lock_guard<std::mutex> lock(mutex_);
            context_entry entry;
            entry.context = io_context;
            entry.component_name = name;
            entries_.push_back(std::move(entry));
            total_started_.fetch_add(1, std::memory_order_relaxed);
        }
        // Submit the io_context::run task - this is the ONLY task we submit
        // No separate monitoring task to avoid thread pool exhaustion
        // Note: Capture total_completed_ by pointer to avoid capturing 'this',
        // which can cause heap corruption during static destruction.
        auto* completed_ptr = &total_completed_;
        // Submit io_context::run task to thread pool
        // IMPORTANT: Avoid logging inside this task to prevent heap corruption during
        // static destruction. When common_system's GlobalLoggerRegistry is destroyed
        // before this thread pool task completes, logging causes heap corruption.
        // Use detail::static_destruction_guard::is_logging_safe() for any necessary logging.
        pool->submit([ctx_weak, caller_promise, completed_ptr]() {
            auto ctx = ctx_weak.lock();
            if (!ctx) {
                // io_context expired - this can happen during rapid shutdown
                caller_promise->set_value();
                return;
            }
            try {
                ctx->run();
                caller_promise->set_value();
            } catch (...) {
                caller_promise->set_exception(std::current_exception());
            }
            completed_ptr->fetch_add(1, std::memory_order_relaxed);
        });
        // Clean up expired entries periodically
        cleanup_expired();
        return caller_future;
    }
References cleanup_expired(), kcenon::network::integration::io_context_thread_manager::impl::context_entry::component_name, kcenon::network::integration::io_context_thread_manager::impl::context_entry::context, entries_, get_thread_pool(), mutex_, total_completed_, and total_started_.
set_thread_pool()
void kcenon::network::integration::io_context_thread_manager::impl::set_thread_pool (std::shared_ptr< thread_pool_interface > pool) inline
Definition at line 196 of file io_context_thread_manager.cpp.
{
        std::lock_guard<std::mutex> lock(mutex_);
        thread_pool_ = pool;
    }
References mutex_, and thread_pool_.
stop_all()
void kcenon::network::integration::io_context_thread_manager::impl::stop_all () inline
Definition at line 127 of file io_context_thread_manager.cpp.
                    {
        // NOTE: No logging here to prevent heap corruption during static
        // destruction. This may be called when GlobalLoggerRegistry is destroyed.
        std::lock_guard<std::mutex> lock(mutex_);
        for (auto& entry : entries_) {
            auto ctx = entry.context.lock();
            if (ctx) {
                ctx->stop();
            }
        }
    }
References entries_, and mutex_.
Referenced by ~impl().
stop_io_context()
void kcenon::network::integration::io_context_thread_manager::impl::stop_io_context (std::shared_ptr< asio::io_context > io_context) inline
Definition at line 119 of file io_context_thread_manager.cpp.
{
        // NOTE: No logging here to prevent heap corruption during static
        // destruction. This may be called when GlobalLoggerRegistry is destroyed.
        if (io_context) {
            io_context->stop();
        }
    }
wait_all()
void kcenon::network::integration::io_context_thread_manager::impl::wait_all () inline
Definition at line 139 of file io_context_thread_manager.cpp.
                    {
        // Since futures are returned directly to callers, wait_all just
        // waits for all tracked io_contexts to be stopped.
        // The callers should wait on their own futures.
        auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(10);
        while (std::chrono::steady_clock::now() < deadline) {
            {
                std::lock_guard<std::mutex> lock(mutex_);
                bool all_stopped = true;
                for (const auto& entry : entries_) {
                    auto ctx = entry.context.lock();
                    if (ctx && !ctx->stopped()) {
                        all_stopped = false;
                        break;
                    }
                }
                if (all_stopped) {
                    entries_.clear();
                    break;
                }
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
        }
        // Clear any remaining expired entries
        std::lock_guard<std::mutex> lock(mutex_);
        entries_.clear();
    }
References entries_, and mutex_.
Referenced by ~impl().
Member Data Documentation
entries_
std::vector<context_entry> kcenon::network::integration::io_context_thread_manager::impl::entries_ private
Definition at line 223 of file io_context_thread_manager.cpp.
Referenced by active_count(), cleanup_expired(), is_active(), run_io_context(), stop_all(), and wait_all().
mutex_
std::mutex kcenon::network::integration::io_context_thread_manager::impl::mutex_ mutable private
Definition at line 221 of file io_context_thread_manager.cpp.
Referenced by active_count(), cleanup_expired(), get_thread_pool(), is_active(), run_io_context(), set_thread_pool(), stop_all(), and wait_all().
thread_pool_
std::shared_ptr<thread_pool_interface> kcenon::network::integration::io_context_thread_manager::impl::thread_pool_ private
Definition at line 222 of file io_context_thread_manager.cpp.
Referenced by get_thread_pool(), and set_thread_pool().
total_completed_
std::atomic<size_t> kcenon::network::integration::io_context_thread_manager::impl::total_completed_ private
Definition at line 225 of file io_context_thread_manager.cpp.
Referenced by get_metrics(), and run_io_context().
total_started_
std::atomic<size_t> kcenon::network::integration::io_context_thread_manager::impl::total_started_ private
Definition at line 224 of file io_context_thread_manager.cpp.
Referenced by get_metrics(), and run_io_context().
The documentation for this class was generated from the following file:
src/integration/io_context_thread_manager.cpp