Network System: kcenon::network::integration::basic_container Class Reference
kcenon::network::integration::basic_container Class Reference
Basic container implementation for standalone use.
#include <container_integration.h>
Classes
class impl
Public Member Functions
basic_container ()
~basic_container ()
std::vector< uint8_t > serialize (const std::any &data) const override
Serialize data to bytes.
std::any deserialize (const std::vector< uint8_t > &bytes) const override
Deserialize bytes to data.
std::string type_name () const override
Get container type name.
bool is_valid () const override
Check if container is valid.
void set_serializer (std::function< std::vector< uint8_t >(const std::any &)> serializer)
Set custom serializer.
void set_deserializer (std::function< std::any(const std::vector< uint8_t > &)> deserializer)
Set custom deserializer.
Public Member Functions inherited from kcenon::network::integration::container_interface
virtual ~container_interface ()=default
Private Attributes
std::unique_ptr< impl > pimpl_
Detailed Description
Basic container implementation for standalone use.
This provides a simple container implementation for when container_system is not available.
Definition at line 116 of file container_integration.h.
Constructor & Destructor Documentation
basic_container()
kcenon::network::integration::basic_container::basic_container ()
Definition at line 142 of file container_integration.cpp.
    : pimpl_(std::make_unique<impl>()) {
}
~basic_container()
kcenon::network::integration::basic_container::~basic_container () default
Member Function Documentation
deserialize()
std::any kcenon::network::integration::basic_container::deserialize (const std::vector< uint8_t > & bytes) const override virtual
Deserialize bytes to data.
Parameters
bytes The bytes to deserialize
Returns
Deserialized data
Implements kcenon::network::integration::container_interface.
Definition at line 152 of file container_integration.cpp.
{
    return pimpl_->deserialize(bytes);
}
References kcenon::network::integration::basic_container::impl::deserialize(), and pimpl_.
is_valid()
bool kcenon::network::integration::basic_container::is_valid () const override virtual
Check if container is valid.
Returns
true if valid, false otherwise
Implements kcenon::network::integration::container_interface.
Definition at line 160 of file container_integration.cpp.
{
    return true;
}
serialize()
std::vector< uint8_t > kcenon::network::integration::basic_container::serialize (const std::any & data) const override virtual
Serialize data to bytes.
Parameters
data The data to serialize
Returns
Serialized bytes
Implements kcenon::network::integration::container_interface.
Definition at line 148 of file container_integration.cpp.
{
    return pimpl_->serialize(data);
}
References pimpl_, and kcenon::network::integration::basic_container::impl::serialize().
set_deserializer()
void kcenon::network::integration::basic_container::set_deserializer (std::function< std::any(const std::vector< uint8_t > &)> deserializer)
Set custom deserializer.
Parameters
deserializer Custom deserialization function
Definition at line 170 of file container_integration.cpp.
  {
    pimpl_->set_deserializer(deserializer);
}
References pimpl_, and kcenon::network::integration::basic_container::impl::set_deserializer().
set_serializer()
void kcenon::network::integration::basic_container::set_serializer (std::function< std::vector< uint8_t >(const std::any &)> serializer)
Set custom serializer.
Parameters
serializer Custom serialization function
Definition at line 164 of file container_integration.cpp.
  {
    pimpl_->set_serializer(serializer);
}
References pimpl_, and kcenon::network::integration::basic_container::impl::set_serializer().
type_name()
std::string kcenon::network::integration::basic_container::type_name () const override virtual
Get container type name.
Returns
Type name string
Implements kcenon::network::integration::container_interface.
Definition at line 156 of file container_integration.cpp.
{
    return "basic_container";
}
Member Data Documentation
pimpl_
std::unique_ptr<impl> kcenon::network::integration::basic_container::pimpl_ private
Definition at line 145 of file container_integration.h.
Referenced by deserialize(), serialize(), set_deserializer(), and set_serializer().
The documentation for this class was generated from the following files:
src/internal/integration/container_integration.h
src/integration/container_integration.cpp