Network System: kcenon::network::internal::adapters::quic_server_adapter Class Reference
kcenon::network::internal::adapters::quic_server_adapter Class Reference
Adapter that wraps messaging_quic_server to implement i_protocol_server.
#include <quic_server_adapter.h>
Public Member Functions
quic_server_adapter (std::string_view server_id)
Constructs an adapter with a unique server ID.
~quic_server_adapter () override
Destructor ensures proper cleanup.
quic_server_adapter (const quic_server_adapter &)=delete
quic_server_adapter & operator= (const quic_server_adapter &)=delete
quic_server_adapter (quic_server_adapter &&)=delete
quic_server_adapter & operator= (quic_server_adapter &&)=delete
auto set_cert_path (std::string_view path) -> void
Sets the server certificate path.
auto set_key_path (std::string_view path) -> void
Sets the server private key path.
auto set_alpn_protocols (const std::vector< std::string > &protocols) -> void
Sets the ALPN protocols for negotiation.
auto set_ca_cert_path (std::string_view path) -> void
Sets CA certificate path for client verification.
auto set_require_client_cert (bool require) -> void
Sets whether to require client certificate (mutual TLS)
auto set_max_idle_timeout (uint64_t timeout_ms) -> void
Sets max idle timeout in milliseconds.
auto set_max_connections (size_t max) -> void
Sets maximum number of concurrent connections.
auto is_running () const -> bool override
Checks if the component is currently running.
auto wait_for_stop () -> void override
Blocks until the component has stopped.
auto start (uint16_t port) -> VoidResult override
Starts the server and begins listening for connections.
auto stop () -> VoidResult override
Stops the server and closes all connections.
auto connection_count () const -> size_t override
Gets the number of active client connections.
auto set_connection_callback (connection_callback_t callback) -> void override
Sets the callback for new connections.
auto set_disconnection_callback (disconnection_callback_t callback) -> void override
Sets the callback for disconnections.
auto set_receive_callback (receive_callback_t callback) -> void override
Sets the callback for received data.
auto set_error_callback (error_callback_t callback) -> void override
Sets the callback for errors.
Public Member Functions inherited from kcenon::network::interfaces::i_protocol_server
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Member Functions
auto setup_internal_callbacks () -> void
Sets up internal callbacks to bridge QUIC callbacks to i_protocol_server callbacks.
auto get_or_create_wrapper (std::shared_ptr< session::quic_session > session) -> std::shared_ptr< quic_session_wrapper >
Creates or retrieves a session wrapper for a QUIC session.
auto remove_wrapper (const std::string &session_id) -> void
Removes a session wrapper.
Private Attributes
std::string server_id_
std::shared_ptr< core::messaging_quic_server > server_
std::atomic< bool > is_running_ {false}
std::string cert_path_
std::string key_path_
std::vector< std::string > alpn_protocols_
std::optional< std::string > ca_cert_path_
bool require_client_cert_ {false}
uint64_t max_idle_timeout_ms_ {30000}
size_t max_connections_ {10000}
std::mutex sessions_mutex_
std::unordered_map< std::string, std::shared_ptr< quic_session_wrapper > > sessions_
std::mutex callbacks_mutex_
connection_callback_t connection_callback_
disconnection_callback_t disconnection_callback_
receive_callback_t receive_callback_
error_callback_t error_callback_
Additional Inherited Members
Public Types inherited from kcenon::network::interfaces::i_protocol_server
using connection_callback_t = std::function<void(std::shared_ptr<i_session>)>
Callback type for new connections.
using disconnection_callback_t = std::function<void(std::string_view)>
Callback type for disconnections (session_id)
using receive_callback_t = std::function<void(std::string_view, const std::vector<uint8_t>&)>
Callback type for received data (session_id, data)
using error_callback_t = std::function<void(std::string_view, std::error_code)>
Callback type for errors (session_id, error)
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps messaging_quic_server to implement i_protocol_server.
This adapter bridges the QUIC server implementation with the unified i_protocol_server interface. It allows quic_facade to return i_protocol_server without modifying the existing messaging_quic_server class.
Design Rationale
The adapter pattern is used because:
QUIC's i_quic_server has additional methods (multi-stream, broadcast)
QUIC always uses TLS 1.3, requiring certificate configuration
For QUIC-specific features, users should use messaging_quic_server directly
TLS Configuration
QUIC requires TLS certificates. Configure via:
set_cert_path() for server certificate
set_key_path() for private key These MUST be called before start().
Message Handling
Receives data from clients on default stream
For multi-stream operations, use messaging_quic_server directly
Thread Safety
Thread-safe. All methods can be called from any thread.
See also
i_protocol_server
messaging_quic_server
Definition at line 87 of file quic_server_adapter.h.
Constructor & Destructor Documentation
quic_server_adapter() [1/3]
kcenon::network::internal::adapters::quic_server_adapter::quic_server_adapter (std::string_view server_id) explicit
Constructs an adapter with a unique server ID.
Parameters
server_id Unique identifier for this server
Definition at line 83 of file quic_server_adapter.cpp.
    : server_id_(server_id)
    , server_(std::make_shared<core::messaging_quic_server>(server_id))
{
    setup_internal_callbacks();
}
References setup_internal_callbacks().
~quic_server_adapter()
kcenon::network::internal::adapters::quic_server_adapter::~quic_server_adapter () override
Destructor ensures proper cleanup.
Definition at line 90 of file quic_server_adapter.cpp.
{
    if (server_ && is_running_.load(std::memory_order_acquire))
    {
        (void)server_->stop();
    }
}
References is_running_, and server_.
quic_server_adapter() [2/3]
kcenon::network::internal::adapters::quic_server_adapter::quic_server_adapter (const quic_server_adapter &) delete
quic_server_adapter() [3/3]
kcenon::network::internal::adapters::quic_server_adapter::quic_server_adapter (quic_server_adapter &&) delete
Member Function Documentation
connection_count()
auto kcenon::network::internal::adapters::quic_server_adapter::connection_count () const -> size_t nodiscard override virtual
Gets the number of active client connections.
Returns
The count of currently connected clients.
Definition of "Active"
A connection is considered active if:
Connection is established (handshake complete if applicable)
Session has not been closed
No fatal errors have occurred on the session
Protocol-Specific Notes
TCP/WebSocket/QUIC: Count of established connections
UDP: Count of unique peer endpoints seen recently
HTTP: Count of active persistent connections or requests
Thread Safety
Thread-safe. Uses atomic operations for accurate count.
Performance
O(1) operation. Does not iterate through connections.
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 210 of file quic_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(sessions_mutex_);
    return sessions_.size();
}
References sessions_, and sessions_mutex_.
get_or_create_wrapper()
auto kcenon::network::internal::adapters::quic_server_adapter::get_or_create_wrapper (std::shared_ptr< session::quic_session > session) -> std::shared_ptr<quic_session_wrapper> private
Creates or retrieves a session wrapper for a QUIC session.
Definition at line 322 of file quic_server_adapter.cpp.
{
    const std::string session_id = session->session_id();
    std::lock_guard<std::mutex> lock(sessions_mutex_);
    auto it = sessions_.find(session_id);
    if (it != sessions_.end())
    {
        return it->second;
    }
    auto wrapper = std::make_shared<quic_session_wrapper>(session_id, session);
    sessions_[session_id] = wrapper;
    return wrapper;
}
is_running()
auto kcenon::network::internal::adapters::quic_server_adapter::is_running () const -> bool nodiscard override virtual
Checks if the component is currently running.
Returns
true if the component is active, false otherwise.
This method must be thread-safe and use atomic operations for the running state.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 141 of file quic_server_adapter.cpp.
{
    return is_running_.load(std::memory_order_acquire);
}
References is_running_.
operator=() [1/2]
quic_server_adapter & kcenon::network::internal::adapters::quic_server_adapter::operator= (const quic_server_adapter &) delete
operator=() [2/2]
quic_server_adapter & kcenon::network::internal::adapters::quic_server_adapter::operator= (quic_server_adapter &&) delete
remove_wrapper()
auto kcenon::network::internal::adapters::quic_server_adapter::remove_wrapper (const std::string & session_id) -> void private
Removes a session wrapper.
Definition at line 340 of file quic_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(sessions_mutex_);
    sessions_.erase(session_id);
}
set_alpn_protocols()
auto kcenon::network::internal::adapters::quic_server_adapter::set_alpn_protocols (const std::vector< std::string > & protocols) -> void
Sets the ALPN protocols for negotiation.
Parameters
protocols List of protocol identifiers (e.g., {"h3", "hq-29"})
Definition at line 112 of file quic_server_adapter.cpp.
{
    alpn_protocols_ = protocols;
}
set_ca_cert_path()
auto kcenon::network::internal::adapters::quic_server_adapter::set_ca_cert_path (std::string_view path) -> void
Sets CA certificate path for client verification.
Parameters
path Path to CA certificate file (PEM format)
Definition at line 117 of file quic_server_adapter.cpp.
{
    ca_cert_path_ = std::string(path);
}
set_cert_path()
auto kcenon::network::internal::adapters::quic_server_adapter::set_cert_path (std::string_view path) -> void
Sets the server certificate path.
Parameters
path Path to server certificate file (PEM format)
REQUIRED: Must be called before start().
Definition at line 102 of file quic_server_adapter.cpp.
{
    cert_path_ = std::string(path);
}
set_connection_callback()
auto kcenon::network::internal::adapters::quic_server_adapter::set_connection_callback (connection_callback_t callback) -> void override virtual
Sets the callback for new connections.
Parameters
callback The callback function.
Callback Parameters
session: Shared pointer to the new session object
Callback Behavior
Called when:
TCP: After accept() and initial handshake complete
WebSocket: After HTTP upgrade handshake succeeds
UDP: After first datagram received from new peer
QUIC: After connection establishment handshake
HTTP: After request line and headers parsed (HTTP/1.1)
Session Object
The session object allows:
Sending data to the specific client
Retrieving session metadata (ID, remote endpoint)
Closing the session individually
Thread Safety
The callback may be invoked from I/O threads. If the callback accesses shared state, it must be thread-safe.
Example
server->set_connection_callback([](std::shared_ptr<i_session> session) {
    std::cout << "New client: " << session->id() << std::endl;
    // Send welcome message
    session->send({0x01, 0x02, 0x03});
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 216 of file quic_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    connection_callback_ = std::move(callback);
}
set_disconnection_callback()
auto kcenon::network::internal::adapters::quic_server_adapter::set_disconnection_callback (disconnection_callback_t callback) -> void override virtual
Sets the callback for disconnections.
Parameters
callback The callback function.
Callback Parameters
session_id: String identifier of the disconnected session
Callback Behavior
Called when:
Client closes connection gracefully
Connection lost due to network error
Server closes the session
Timeout or keepalive failure
Clean-up Responsibility
The callback is the appropriate place to:
Remove session from application state
Log disconnection events
Release session-specific resources
Thread Safety
The callback may be invoked from I/O threads. Session cleanup code must be thread-safe.
Example
server->set_disconnection_callback([](std::string_view session_id) {
    std::cout << "Client disconnected: " << session_id << std::endl;
    // Remove from session map
    sessions.erase(std::string(session_id));
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 222 of file quic_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    disconnection_callback_ = std::move(callback);
}
set_error_callback()
auto kcenon::network::internal::adapters::quic_server_adapter::set_error_callback (error_callback_t callback) -> void override virtual
Sets the callback for errors.
Parameters
callback The callback function.
Callback Parameters
session_id: String identifier of the affected session (may be empty for server-level errors)
error: std::error_code describing the error
Error Categories
Connection errors: Reset, timeout, refused
Protocol errors: Invalid handshake, malformed data
System errors: Out of memory, file descriptor limits
Application errors: Send queue full, rate limit exceeded
Error Handling Strategy
The callback should:
Log the error for diagnostics
Decide whether to close the session
Update error metrics/statistics
Notify monitoring systems if critical
Automatic Disconnection
Some errors trigger automatic session closure:
Connection reset (ECONNRESET)
Protocol violations
Fatal security errors
For these, disconnection_callback will also be invoked.
Thread Safety
The callback may be invoked from I/O threads. Error handling code must be thread-safe.
Example
server->set_error_callback([](std::string_view session_id,
                               std::error_code error) {
    std::cerr << "Error on session " << session_id << ": "
              << error.message() << std::endl;
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 234 of file quic_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    error_callback_ = std::move(callback);
}
set_key_path()
auto kcenon::network::internal::adapters::quic_server_adapter::set_key_path (std::string_view path) -> void
Sets the server private key path.
Parameters
path Path to private key file (PEM format)
REQUIRED: Must be called before start().
Definition at line 107 of file quic_server_adapter.cpp.
{
    key_path_ = std::string(path);
}
set_max_connections()
auto kcenon::network::internal::adapters::quic_server_adapter::set_max_connections (size_t max) -> void
Sets maximum number of concurrent connections.
Parameters
max Maximum connections (default: 10000)
Definition at line 132 of file quic_server_adapter.cpp.
{
    max_connections_ = max;
}
set_max_idle_timeout()
auto kcenon::network::internal::adapters::quic_server_adapter::set_max_idle_timeout (uint64_t timeout_ms) -> void
Sets max idle timeout in milliseconds.
Parameters
timeout_ms Maximum idle timeout (default: 30000)
Definition at line 127 of file quic_server_adapter.cpp.
{
    max_idle_timeout_ms_ = timeout_ms;
}
set_receive_callback()
auto kcenon::network::internal::adapters::quic_server_adapter::set_receive_callback (receive_callback_t callback) -> void override virtual
Sets the callback for received data.
Parameters
callback The callback function.
Callback Parameters
session_id: String identifier of the sending session
data: Vector of bytes received
Data Ownership
The data vector is passed by const reference. If the callback needs to retain the data, it must copy it. The data is valid only for the duration of the callback.
Protocol-Specific Notes
TCP: May deliver partial messages (stream-based)
UDP: Delivers complete datagrams (message boundaries preserved)
WebSocket: Delivers complete messages (frame assembled)
QUIC: Delivers complete messages (stream data)
Thread Safety
The callback may be invoked from I/O threads. Multiple callbacks may execute concurrently for different sessions.
Example
server->set_receive_callback([](std::string_view session_id,
                                 const std::vector<uint8_t>& data) {
    std::cout << "Received " << data.size() << " bytes from "
              << session_id << std::endl;
    // Process data...
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 228 of file quic_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    receive_callback_ = std::move(callback);
}
set_require_client_cert()
auto kcenon::network::internal::adapters::quic_server_adapter::set_require_client_cert (bool require) -> void
Sets whether to require client certificate (mutual TLS)
Parameters
require True to require client cert, false otherwise
Definition at line 122 of file quic_server_adapter.cpp.
{
    require_client_cert_ = require;
}
setup_internal_callbacks()
auto kcenon::network::internal::adapters::quic_server_adapter::setup_internal_callbacks () -> void private
Sets up internal callbacks to bridge QUIC callbacks to i_protocol_server callbacks.
Definition at line 244 of file quic_server_adapter.cpp.
{
    if (!server_)
    {
        return;
    }
    // Bridge connection callback using the legacy callback type (takes quic_session directly)
    core::messaging_quic_server::connection_callback_t conn_cb =
        [this](std::shared_ptr<session::quic_session> quic_sess) {
            if (!quic_sess)
            {
                return;
            }
            auto wrapper = get_or_create_wrapper(quic_sess);
            connection_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = connection_callback_;
            }
            if (callback_copy)
            {
                callback_copy(wrapper);
            }
        };
    server_->set_connection_callback(conn_cb);
    // Bridge disconnection callback
    server_->set_disconnection_callback(
        [this](std::string_view session_id) {
            disconnection_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = disconnection_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session_id);
            }
            remove_wrapper(std::string(session_id));
        });
    // Bridge receive callback
    server_->set_receive_callback(
        [this](std::string_view session_id, const std::vector<uint8_t>& data) {
            receive_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = receive_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session_id, data);
            }
        });
    // Bridge error callback
    server_->set_error_callback(
        [this](std::string_view session_id, std::error_code ec) {
            error_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = error_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session_id, ec);
            }
        });
}
Referenced by quic_server_adapter().
start()
auto kcenon::network::internal::adapters::quic_server_adapter::start (uint16_t port) -> VoidResult nodiscard override virtual
Starts the server and begins listening for connections.
Parameters
port The port number to listen on.
Returns
VoidResult indicating success or failure.
Behavior
Binds to the specified port on all interfaces (0.0.0.0/::)
Begins accepting incoming connections
Initializes protocol-specific resources
Invokes connection_callback for each new client
Error Conditions
Returns error if already running
Returns error if port is already in use (EADDRINUSE)
Returns error if port binding fails (permission, invalid port)
Returns error if underlying protocol initialization fails
Protocol-Specific Notes
TCP/WebSocket/QUIC: Creates listening socket
UDP: Creates datagram socket, begins receiving
HTTP: May create connection pool or thread pool
Port Range
Valid ports: 1-65535
Privileged ports (< 1024) may require elevated permissions
Port 0 requests OS to assign an available port
Thread Safety
Thread-safe. Only one start operation can succeed at a time. Subsequent calls while running will return an error.
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 158 of file quic_server_adapter.cpp.
{
    if (!server_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Server not initialized",
            "quic_server_adapter::start"
        );
    }
    // Build configuration
    core::quic_server_config config;
    config.cert_file = cert_path_;
    config.key_file = key_path_;
    config.ca_cert_file = ca_cert_path_;
    config.require_client_cert = require_client_cert_;
    config.alpn_protocols = alpn_protocols_;
    config.max_idle_timeout_ms = max_idle_timeout_ms_;
    config.max_connections = max_connections_;
    auto result = server_->start_server(port, config);
    if (result.is_ok())
    {
        is_running_.store(true, std::memory_order_release);
    }
    return result;
}
References config, kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::internal_error.
stop()
auto kcenon::network::internal::adapters::quic_server_adapter::stop () -> VoidResult nodiscard override virtual
Stops the server and closes all connections.
Returns
VoidResult indicating success or failure.
Behavior
Stops accepting new connections
Closes all active client sessions gracefully
Invokes disconnection_callback for each session
Cancels all pending operations
Releases protocol-specific resources
Error Conditions
Returns error if not running
Graceful Shutdown
The stop operation attempts to:
Stop accepting new connections immediately
Close existing connections gracefully (protocol-dependent)
Wait for pending operations to complete (with timeout)
Force-close remaining connections if timeout expires
Protocol-Specific Notes
TCP: Sends FIN to all clients, waits for ACK
WebSocket: Sends close frame to all clients
UDP: Stops receiving, no client "close" needed
QUIC: Sends CONNECTION_CLOSE to all clients
Thread Safety
Thread-safe. Safe to call from any thread including callbacks. The method blocks until shutdown is complete.
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 187 of file quic_server_adapter.cpp.
{
    if (!server_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Server not initialized",
            "quic_server_adapter::stop"
        );
    }
    auto result = server_->stop_server();
    is_running_.store(false, std::memory_order_release);
    // Clear tracked sessions on stop
    {
        std::lock_guard<std::mutex> lock(sessions_mutex_);
        sessions_.clear();
    }
    return result;
}
References kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::internal_error.
wait_for_stop()
auto kcenon::network::internal::adapters::quic_server_adapter::wait_for_stop () -> void override virtual
Blocks until the component has stopped.
This method should be used to synchronize shutdown operations. It returns immediately if the component is not running.
Thread Safety
Safe to call from any thread. Uses internal synchronization.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 146 of file quic_server_adapter.cpp.
{
    if (server_)
    {
        server_->wait_for_stop();
    }
}
Member Data Documentation
alpn_protocols_
std::vector<std::string> kcenon::network::internal::adapters::quic_server_adapter::alpn_protocols_ private
Definition at line 200 of file quic_server_adapter.h.
ca_cert_path_
std::optional<std::string> kcenon::network::internal::adapters::quic_server_adapter::ca_cert_path_ private
Definition at line 201 of file quic_server_adapter.h.
callbacks_mutex_
std::mutex kcenon::network::internal::adapters::quic_server_adapter::callbacks_mutex_ mutable private
Definition at line 211 of file quic_server_adapter.h.
cert_path_
std::string kcenon::network::internal::adapters::quic_server_adapter::cert_path_ private
Definition at line 198 of file quic_server_adapter.h.
connection_callback_
connection_callback_t kcenon::network::internal::adapters::quic_server_adapter::connection_callback_ private
Definition at line 212 of file quic_server_adapter.h.
disconnection_callback_
disconnection_callback_t kcenon::network::internal::adapters::quic_server_adapter::disconnection_callback_ private
Definition at line 213 of file quic_server_adapter.h.
error_callback_
error_callback_t kcenon::network::internal::adapters::quic_server_adapter::error_callback_ private
Definition at line 215 of file quic_server_adapter.h.
is_running_
std::atomic<bool> kcenon::network::internal::adapters::quic_server_adapter::is_running_ {false} private
Definition at line 195 of file quic_server_adapter.h.
{false};
Referenced by is_running(), and ~quic_server_adapter().
key_path_
std::string kcenon::network::internal::adapters::quic_server_adapter::key_path_ private
Definition at line 199 of file quic_server_adapter.h.
max_connections_
size_t kcenon::network::internal::adapters::quic_server_adapter::max_connections_ {10000} private
Definition at line 204 of file quic_server_adapter.h.
{10000};
max_idle_timeout_ms_
uint64_t kcenon::network::internal::adapters::quic_server_adapter::max_idle_timeout_ms_ {30000} private
Definition at line 203 of file quic_server_adapter.h.
{30000};
receive_callback_
receive_callback_t kcenon::network::internal::adapters::quic_server_adapter::receive_callback_ private
Definition at line 214 of file quic_server_adapter.h.
require_client_cert_
bool kcenon::network::internal::adapters::quic_server_adapter::require_client_cert_ {false} private
Definition at line 202 of file quic_server_adapter.h.
{false};
server_
std::shared_ptr<core::messaging_quic_server> kcenon::network::internal::adapters::quic_server_adapter::server_ private
Definition at line 194 of file quic_server_adapter.h.
Referenced by ~quic_server_adapter().
server_id_
std::string kcenon::network::internal::adapters::quic_server_adapter::server_id_ private
Definition at line 193 of file quic_server_adapter.h.
sessions_
std::unordered_map<std::string, std::shared_ptr<quic_session_wrapper> > kcenon::network::internal::adapters::quic_server_adapter::sessions_ private
Definition at line 208 of file quic_server_adapter.h.
Referenced by connection_count().
sessions_mutex_
std::mutex kcenon::network::internal::adapters::quic_server_adapter::sessions_mutex_ mutable private
Definition at line 207 of file quic_server_adapter.h.
Referenced by connection_count().
The documentation for this class was generated from the following files:
src/internal/adapters/quic_server_adapter.h
src/adapters/quic_server_adapter.cpp