Network System: kcenon::network::core::reliable_udp_client Class Reference
kcenon::network::core::reliable_udp_client Class Reference export
module kcenon.network
A UDP client with optional reliability layer for configurable delivery guarantees.
#include <reliable_udp_client.h>
Classes
class impl
Public Member Functions
reliable_udp_client (std::string_view client_id, reliability_mode mode=reliability_mode::reliable_ordered)
Constructs a reliable UDP client with specified mode.
~reliable_udp_client () noexcept
Destructor. Automatically stops the client if running.
auto start_client (std::string_view host, uint16_t port) -> VoidResult
Starts the client and connects to the target endpoint.
auto stop_client () -> VoidResult
Stops the client and releases resources.
auto send_packet (std::vector< uint8_t > &&data) -> VoidResult
Sends a packet with reliability handling based on mode.
auto wait_for_stop () -> void
Blocks until the client is stopped.
auto set_receive_callback (std::function< void(const std::vector< uint8_t > &)> callback) -> void
Sets callback for received data.
auto set_error_callback (std::function< void(std::error_code)> callback) -> void
Sets callback for connection errors.
auto set_congestion_window (size_t packets) -> void
Sets the congestion window size (maximum unacknowledged packets).
auto set_max_retries (size_t retries) -> void
Sets maximum retransmission attempts before giving up.
auto set_retransmission_timeout (uint32_t timeout_ms) -> void
Sets retransmission timeout in milliseconds.
auto get_stats () const -> reliable_udp_stats
Returns current connection statistics.
auto is_running () const -> bool
Checks if client is currently running.
auto client_id () const -> const std::string &
Returns the client identifier.
auto mode () const -> reliability_mode
Returns the current reliability mode.
reliable_udp_client (std::string_view client_id)
Construct a reliable UDP client.
virtual ~reliable_udp_client () noexcept
Destructor.
reliable_udp_client (const reliable_udp_client &)=delete
reliable_udp_client & operator= (const reliable_udp_client &)=delete
reliable_udp_client (reliable_udp_client &&) noexcept
reliable_udp_client & operator= (reliable_udp_client &&) noexcept
bool start_client (std::string_view remote_host, uint16_t remote_port)
Start the client.
void stop_client ()
Stop the client.
bool send_reliable (std::span< const uint8_t > data)
Send data with reliable delivery.
bool send_unreliable (std::span< const uint8_t > data)
Send data unreliably (fire and forget)
bool is_connected () const noexcept
Check if the client is connected.
bool is_running () const noexcept
Check if the client is running.
std::string_view client_id () const noexcept
Get the client identifier.
void set_connection_callback (connection_callback callback)
Set connection callback.
void set_disconnection_callback (disconnection_callback callback)
Set disconnection callback.
void set_data_callback (data_callback callback)
Set data received callback.
void set_error_callback (error_callback callback)
Set error callback.
void set_retransmit_timeout (std::chrono::milliseconds timeout)
Set retransmission timeout.
void set_max_retransmit_attempts (size_t max_attempts)
Set maximum retransmission attempts.
std::chrono::milliseconds get_rtt () const noexcept
Get current round-trip time estimate.
double get_packet_loss_rate () const noexcept
Get packet loss rate.
Private Attributes
std::unique_ptr< impl > pimpl_
Detailed Description
A UDP client with optional reliability layer for configurable delivery guarantees.
A reliable UDP client with acknowledgment and retransmission.
Thread Safety
All public methods are thread-safe
Internal state is protected by mutexes
Callbacks may be invoked from internal threads
Key Features
Selective Acknowledgment (SACK): Efficient ACK mechanism
Packet Retransmission: Automatic retry for lost packets
In-order Delivery: Optional sequence guarantee
Congestion Control: Sliding window flow control
Flexible Modes: Choose reliability vs performance trade-off
Reliability Modes
unreliable: Pure UDP, no overhead (use for non-critical data)
reliable_ordered: Like TCP - all packets arrive in order
reliable_unordered: All packets arrive, order doesn't matter
sequenced: Latest packets only, old ones dropped (real-time)
Usage Example
// Create reliable ordered UDP client
auto client = std::make_shared<reliable_udp_client>(
    "GameClient",
    reliability_mode::reliable_ordered
);
// Set receive callback
client->set_receive_callback([](const std::vector<uint8_t>& data) {
    std::cout << "Received " << data.size() << " bytes\n";
});
// Start client
auto result = client->start_client("game-server.example.com", 7777);
if (!result) {
    std::cerr << "Failed to start: " << result.error().message << "\n";
    return -1;
}
// Send data with automatic reliability handling
std::vector<uint8_t> game_state = {...};
client->send_packet(std::move(game_state));
// Get statistics
auto stats = client->get_stats();
std::cout << "RTT: " << stats.average_rtt_ms << " ms\n";
This class provides reliable delivery semantics on top of UDP, implementing acknowledgment, retransmission, and ordering.
Thread Safety
All public methods are thread-safe.
Key Features
Guaranteed delivery with acknowledgments
Automatic retransmission on timeout
Sequence number based ordering
Congestion control
import kcenon.network;
auto client = std::make_unique<kcenon::network::core::reliable_udp_client>("rudp_client");
client->start_client("localhost", 8080);
client->send_reliable(data); // Guaranteed delivery
Definition at line 356 of file udp.cppm.
Constructor & Destructor Documentation
reliable_udp_client() [1/4]
kcenon::network::core::reliable_udp_client::reliable_udp_client (std::string_view client_id, reliability_mode mode = reliability_mode::reliable_ordered)
Constructs a reliable UDP client with specified mode.
Parameters
client_id Unique identifier for this client instance.
mode Reliability mode (default: reliable_ordered).
Definition at line 683 of file reliable_udp_client.cpp.
        : pimpl_(std::make_unique<impl>(client_id, mode))
    {
    }
~reliable_udp_client() [1/2]
kcenon::network::core::reliable_udp_client::~reliable_udp_client () default noexcept
Destructor. Automatically stops the client if running.
reliable_udp_client() [2/4]
kcenon::network::core::reliable_udp_client::reliable_udp_client (std::string_view client_id) explicit export
Construct a reliable UDP client.
Parameters
client_id A string identifier for this client instance
~reliable_udp_client() [2/2]
virtual kcenon::network::core::reliable_udp_client::~reliable_udp_client () export virtual noexcept
Destructor.
reliable_udp_client() [3/4]
kcenon::network::core::reliable_udp_client::reliable_udp_client (const reliable_udp_client &) export delete
reliable_udp_client() [4/4]
kcenon::network::core::reliable_udp_client::reliable_udp_client (reliable_udp_client &&) export noexcept
Member Function Documentation
client_id() [1/2]
auto kcenon::network::core::reliable_udp_client::client_id () const -> const std::string&
Returns the client identifier.
Returns
Client ID string.
Definition at line 738 of file reliable_udp_client.cpp.
    {
        return pimpl_->client_id();
    }
References kcenon::network::core::reliable_udp_client::impl::client_id(), and pimpl_.
client_id() [2/2]
std::string_view kcenon::network::core::reliable_udp_client::client_id () const export noexcept
Get the client identifier.
Returns
Client ID string
get_packet_loss_rate()
double kcenon::network::core::reliable_udp_client::get_packet_loss_rate () const export noexcept
Get packet loss rate.
Returns
Packet loss rate (0.0 to 1.0)
get_rtt()
std::chrono::milliseconds kcenon::network::core::reliable_udp_client::get_rtt () const export noexcept
Get current round-trip time estimate.
Returns
RTT in milliseconds
get_stats()
auto kcenon::network::core::reliable_udp_client::get_stats () const -> reliable_udp_stats
Returns current connection statistics.
Returns
Statistics structure with counters and metrics.
Definition at line 731 of file reliable_udp_client.cpp.
    {
        return pimpl_->get_stats();
    }
References kcenon::network::core::reliable_udp_client::impl::get_stats(), and pimpl_.
is_connected()
bool kcenon::network::core::reliable_udp_client::is_connected () const export noexcept
Check if the client is connected.
Returns
true if connected, false otherwise
is_running() [1/2]
auto kcenon::network::core::reliable_udp_client::is_running () const -> bool
Checks if client is currently running.
Returns
true if running, false otherwise.
Definition at line 736 of file reliable_udp_client.cpp.
{ return pimpl_->is_running(); }
References kcenon::network::core::reliable_udp_client::impl::is_running(), and pimpl_.
is_running() [2/2]
bool kcenon::network::core::reliable_udp_client::is_running () const export noexcept
Check if the client is running.
Returns
true if running, false otherwise
mode()
auto kcenon::network::core::reliable_udp_client::mode () const -> reliability_mode
Returns the current reliability mode.
Returns
Reliability mode.
Definition at line 743 of file reliable_udp_client.cpp.
{ return pimpl_->mode(); }
References kcenon::network::core::reliable_udp_client::impl::mode(), and pimpl_.
operator=() [1/2]
reliable_udp_client & kcenon::network::core::reliable_udp_client::operator= (const reliable_udp_client &) export delete
operator=() [2/2]
reliable_udp_client & kcenon::network::core::reliable_udp_client::operator= (reliable_udp_client &&) export noexcept
send_packet()
auto kcenon::network::core::reliable_udp_client::send_packet (std::vector< uint8_t > && data) -> VoidResult
Sends a packet with reliability handling based on mode.
Parameters
data Packet data to send (moved for efficiency).
Returns
Result<void> - Success if packet queued/sent, error otherwise.
Behavior varies by reliability mode:
unreliable: Immediate send, no tracking
reliable_ordered: Queued, retransmitted until ACK, delivered in order
reliable_unordered: Retransmitted until ACK, no ordering
sequenced: Immediate send with sequence number, old packets dropped
Definition at line 697 of file reliable_udp_client.cpp.
    {
        return pimpl_->send_packet(std::move(data));
    }
send_reliable()
bool kcenon::network::core::reliable_udp_client::send_reliable (std::span< const uint8_t > data) export
Send data with reliable delivery.
Parameters
data The data to send
Returns
true if data was queued for reliable delivery
send_unreliable()
bool kcenon::network::core::reliable_udp_client::send_unreliable (std::span< const uint8_t > data) export
Send data unreliably (fire and forget)
Parameters
data The data to send
Returns
true if data was sent
set_congestion_window()
auto kcenon::network::core::reliable_udp_client::set_congestion_window (size_t packets) -> void
Sets the congestion window size (maximum unacknowledged packets).
Parameters
packets Number of packets (default: 32).
Larger window = higher throughput but more memory usage. Smaller window = lower throughput but better for constrained networks.
Definition at line 716 of file reliable_udp_client.cpp.
    {
        pimpl_->set_congestion_window(packets);
    }
set_connection_callback()
void kcenon::network::core::reliable_udp_client::set_connection_callback (connection_callback callback) export
Set connection callback.
Parameters
callback Function to call when connected
set_data_callback()
void kcenon::network::core::reliable_udp_client::set_data_callback (data_callback callback) export
Set data received callback.
Parameters
callback Function to call when data is received
set_disconnection_callback()
void kcenon::network::core::reliable_udp_client::set_disconnection_callback (disconnection_callback callback) export
Set disconnection callback.
Parameters
callback Function to call when disconnected
set_error_callback() [1/2]
void kcenon::network::core::reliable_udp_client::set_error_callback (error_callback callback) export
Set error callback.
Parameters
callback Function to call on errors
set_error_callback() [2/2]
auto kcenon::network::core::reliable_udp_client::set_error_callback (std::function< void(std::error_code)> callback) -> void
Sets callback for connection errors.
Parameters
callback Function called when errors occur.
Definition at line 710 of file reliable_udp_client.cpp.
    {
        pimpl_->set_error_callback(std::move(callback));
    }
set_max_retransmit_attempts()
void kcenon::network::core::reliable_udp_client::set_max_retransmit_attempts (size_t max_attempts) export
Set maximum retransmission attempts.
Parameters
max_attempts Maximum number of retransmission attempts
set_max_retries()
auto kcenon::network::core::reliable_udp_client::set_max_retries (size_t retries) -> void
Sets maximum retransmission attempts before giving up.
Parameters
retries Number of retries (default: 5).
Only applies to reliable modes. After max retries, packet is dropped and error callback is invoked.
Definition at line 721 of file reliable_udp_client.cpp.
    {
        pimpl_->set_max_retries(retries);
    }
set_receive_callback()
auto kcenon::network::core::reliable_udp_client::set_receive_callback (std::function< void(const std::vector< uint8_t > &)> callback) -> void
Sets callback for received data.
Parameters
callback Function called when data is received and processed.
In reliable_ordered mode, data is delivered in order. In other modes, data is delivered as it arrives.
Definition at line 704 of file reliable_udp_client.cpp.
    {
        pimpl_->set_receive_callback(std::move(callback));
    }
set_retransmission_timeout()
auto kcenon::network::core::reliable_udp_client::set_retransmission_timeout (uint32_t timeout_ms) -> void
Sets retransmission timeout in milliseconds.
Parameters
timeout_ms Timeout value (default: 200ms).
Dynamically adjusted based on measured RTT.
Definition at line 726 of file reliable_udp_client.cpp.
    {
        pimpl_->set_retransmission_timeout(timeout_ms);
    }
set_retransmit_timeout()
void kcenon::network::core::reliable_udp_client::set_retransmit_timeout (std::chrono::milliseconds timeout) export
Set retransmission timeout.
Parameters
timeout Timeout duration
start_client() [1/2]
auto kcenon::network::core::reliable_udp_client::start_client (std::string_view host, uint16_t port) -> VoidResult
Starts the client and connects to the target endpoint.
Parameters
host Target hostname or IP address.
port Target port number.
Returns
Result<void> - Success or error with details.
Creates underlying UDP socket, starts receive loop, and initializes reliability mechanisms based on the configured mode.
Definition at line 690 of file reliable_udp_client.cpp.
    {
        return pimpl_->start_client(host, port);
    }
start_client() [2/2]
bool kcenon::network::core::reliable_udp_client::start_client (std::string_view remote_host, uint16_t remote_port) export
Start the client.
Parameters
remote_host The remote host address
remote_port The remote port number
Returns
true if started successfully
stop_client() [1/2]
void kcenon::network::core::reliable_udp_client::stop_client () export
Stop the client.
stop_client() [2/2]
auto kcenon::network::core::reliable_udp_client::stop_client () -> VoidResult
Stops the client and releases resources.
Returns
Result<void> - Success or error with details.
Flushes pending packets, stops timers, and closes socket.
Definition at line 695 of file reliable_udp_client.cpp.
{ return pimpl_->stop_client(); }
wait_for_stop()
auto kcenon::network::core::reliable_udp_client::wait_for_stop () -> void
Blocks until the client is stopped.
Definition at line 702 of file reliable_udp_client.cpp.
{ pimpl_->wait_for_stop(); }
Member Data Documentation
pimpl_
std::unique_ptr< impl > kcenon::network::core::reliable_udp_client::pimpl_ export private
Implementation (PIMPL idiom)
Definition at line 223 of file reliable_udp_client.h.
Referenced by client_id(), get_stats(), is_running(), and mode().
The documentation for this class was generated from the following files:
src/internal/experimental/reliable_udp_client.h
src/modules/udp.cppm
src/experimental/reliable_udp_client.cpp