Network System: kcenon::network::utils::callback_manager< CallbackTypes > Class Template Reference
kcenon::network::utils::callback_manager< CallbackTypes > Class Template Reference
Thread-safe callback storage and invocation utility.
#include <callback_manager.h>
Public Member Functions
callback_manager ()=default
Default constructor.
~callback_manager ()=default
Destructor.
callback_manager (const callback_manager &)=delete
callback_manager & operator= (const callback_manager &)=delete
callback_manager (callback_manager &&) noexcept=default
callback_manager & operator= (callback_manager &&) noexcept=default
template<std::size_t Index>
auto set (std::tuple_element_t< Index, std::tuple< CallbackTypes... > > callback) -> void
Sets a callback at the specified index.
template<typename T >
auto set (T callback) -> void
Sets a callback by type.
template<std::size_t Index>
auto get () const -> std::tuple_element_t< Index, std::tuple< CallbackTypes... > >
Gets a callback at the specified index.
template<typename T >
auto get () const -> T
Gets a callback by type.
template<std::size_t Index, typename... Args>
auto invoke (Args &&... args) -> void
Invokes a callback at the specified index if set.
template<typename T , typename... Args>
auto invoke (Args &&... args) -> void
Invokes a callback by type if set.
template<std::size_t Index, typename... Args>
auto invoke_if (bool condition, Args &&... args) -> void
Invokes a callback conditionally.
auto clear () -> void
Clears all callbacks.
template<std::size_t Index>
auto clear () -> void
Clears a specific callback.
Private Attributes
std::mutex mutex_
std::tuple< CallbackTypes... > callbacks_
Detailed Description
template<typename... CallbackTypes>
class kcenon::network::utils::callback_manager< CallbackTypes >
Thread-safe callback storage and invocation utility.
This template class provides a centralized way to store and invoke multiple callback types with thread safety. It replaces the repeated callback handling code in CRTP base classes.
Template Parameters
CallbackTypes The callback function types to manage.
Thread Safety
Setting callbacks is protected by mutex
Invocation copies the callback under lock, then invokes outside lock
This prevents deadlocks when callbacks trigger other operations
Usage Example
using my_callbacks = callback_manager<
    std::function<void(std::vector<uint8_t>&&)>,  // receive
    std::function<void()>,                        // connected
    std::function<void()>                         // disconnected
>;
my_callbacks callbacks;
callbacks.set<0>([](auto&& data) { process(data); });
callbacks.invoke<0>(std::move(data));
Definition at line 61 of file callback_manager.h.
Constructor & Destructor Documentation
callback_manager() [1/3]
template<typename... CallbackTypes> kcenon::network::utils::callback_manager< CallbackTypes >::callback_manager () default
Default constructor.
~callback_manager()
template<typename... CallbackTypes> kcenon::network::utils::callback_manager< CallbackTypes >::~callback_manager () default
Destructor.
callback_manager() [2/3]
template<typename... CallbackTypes> kcenon::network::utils::callback_manager< CallbackTypes >::callback_manager (const callback_manager< CallbackTypes > &) delete
callback_manager() [3/3]
template<typename... CallbackTypes> kcenon::network::utils::callback_manager< CallbackTypes >::callback_manager (callback_manager< CallbackTypes > &&) default noexcept
Member Function Documentation
clear() [1/2]
template<typename... CallbackTypes> auto kcenon::network::utils::callback_manager< CallbackTypes >::clear () -> void inline
Clears all callbacks.
Definition at line 183 of file callback_manager.h.
        {
            std::lock_guard lock(mutex_);
            callbacks_ = std::tuple<CallbackTypes...>{};
        }
References kcenon::network::utils::callback_manager< CallbackTypes >::callbacks_, and kcenon::network::utils::callback_manager< CallbackTypes >::mutex_.
clear() [2/2]
template<typename... CallbackTypes> template<std::size_t Index> auto kcenon::network::utils::callback_manager< CallbackTypes >::clear () -> void inline
Clears a specific callback.
Template Parameters
Index The index of the callback to clear.
Definition at line 194 of file callback_manager.h.
        {
            std::lock_guard lock(mutex_);
            std::get<Index>(callbacks_) = {};
        }
References kcenon::network::utils::callback_manager< CallbackTypes >::callbacks_, and kcenon::network::utils::callback_manager< CallbackTypes >::mutex_.
get() [1/2]
template<typename... CallbackTypes> template<std::size_t Index> auto kcenon::network::utils::callback_manager< CallbackTypes >::get () const -> std::tuple_element_t<Index, std::tuple<CallbackTypes...>> inline nodiscard
Gets a callback at the specified index.
Template Parameters
Index The index of the callback type.
Returns
The callback function (may be empty).
Definition at line 110 of file callback_manager.h.
        {
            std::lock_guard lock(mutex_);
            return std::get<Index>(callbacks_);
        }
References kcenon::network::utils::callback_manager< CallbackTypes >::callbacks_, and kcenon::network::utils::callback_manager< CallbackTypes >::mutex_.
Referenced by kcenon::network::core::messaging_server::get_connection_callback(), kcenon::network::core::secure_messaging_server::get_connection_callback(), kcenon::network::core::messaging_server::get_disconnection_callback(), kcenon::network::core::secure_messaging_server::get_disconnection_callback(), kcenon::network::core::messaging_server::get_error_callback(), kcenon::network::core::messaging_udp_client::get_error_callback(), kcenon::network::core::messaging_udp_server::get_error_callback(), kcenon::network::core::secure_messaging_server::get_error_callback(), kcenon::network::core::messaging_server::get_receive_callback(), kcenon::network::core::messaging_udp_client::get_receive_callback(), kcenon::network::core::messaging_udp_server::get_receive_callback(), kcenon::network::core::secure_messaging_server::get_receive_callback(), and kcenon::network::utils::callback_manager< CallbackTypes >::invoke().
get() [2/2]
template<typename... CallbackTypes> template<typename T > auto kcenon::network::utils::callback_manager< CallbackTypes >::get () const -> T inline nodiscard
Gets a callback by type.
Template Parameters
T The callback type.
Returns
The callback function (may be empty).
Definition at line 122 of file callback_manager.h.
        {
            std::lock_guard lock(mutex_);
            return std::get<T>(callbacks_);
        }
References kcenon::network::utils::callback_manager< CallbackTypes >::callbacks_, and kcenon::network::utils::callback_manager< CallbackTypes >::mutex_.
invoke() [1/2]
template<typename... CallbackTypes> template<std::size_t Index, typename... Args> auto kcenon::network::utils::callback_manager< CallbackTypes >::invoke (Args &&... args) -> void inline
Invokes a callback at the specified index if set.
Template Parameters
Index The index of the callback type.
Args The argument types.
Parameters
args The arguments to pass to the callback.
Thread Safety
The callback is copied under lock, then invoked without lock. This prevents deadlocks if the callback triggers set() calls.
Definition at line 139 of file callback_manager.h.
        {
            auto callback = get<Index>();
            if (callback)
            {
                callback(std::forward<Args>(args)...);
            }
        }
References kcenon::network::utils::callback_manager< CallbackTypes >::get().
Referenced by kcenon::network::utils::callback_manager< CallbackTypes >::invoke_if().
invoke() [2/2]
template<typename... CallbackTypes> template<typename T , typename... Args> auto kcenon::network::utils::callback_manager< CallbackTypes >::invoke (Args &&... args) -> void inline
Invokes a callback by type if set.
Template Parameters
T The callback type.
Args The argument types.
Parameters
args The arguments to pass to the callback.
Definition at line 155 of file callback_manager.h.
        {
            auto callback = get<T>();
            if (callback)
            {
                callback(std::forward<Args>(args)...);
            }
        }
References kcenon::network::utils::callback_manager< CallbackTypes >::get().
invoke_if()
template<typename... CallbackTypes> template<std::size_t Index, typename... Args> auto kcenon::network::utils::callback_manager< CallbackTypes >::invoke_if (bool condition, Args &&... args) -> void inline
Invokes a callback conditionally.
Template Parameters
Index The index of the callback type.
Args The argument types.
Parameters
condition If false, the callback is not invoked.
args The arguments to pass to the callback.
Definition at line 172 of file callback_manager.h.
        {
            if (condition)
            {
                invoke<Index>(std::forward<Args>(args)...);
            }
        }
References kcenon::network::utils::callback_manager< CallbackTypes >::invoke().
operator=() [1/2]
template<typename... CallbackTypes> callback_manager & kcenon::network::utils::callback_manager< CallbackTypes >::operator= (callback_manager< CallbackTypes > &&) default noexcept
operator=() [2/2]
template<typename... CallbackTypes> callback_manager & kcenon::network::utils::callback_manager< CallbackTypes >::operator= (const callback_manager< CallbackTypes > &) delete
set() [1/2]
template<typename... CallbackTypes> template<std::size_t Index> auto kcenon::network::utils::callback_manager< CallbackTypes >::set (std::tuple_element_t< Index, std::tuple< CallbackTypes... > > callback) -> void inline
Sets a callback at the specified index.
Template Parameters
Index The index of the callback type.
Parameters
callback The callback function to store.
Definition at line 86 of file callback_manager.h.
        {
            std::lock_guard lock(mutex_);
            std::get<Index>(callbacks_) = std::move(callback);
        }
References kcenon::network::utils::callback_manager< CallbackTypes >::callbacks_, and kcenon::network::utils::callback_manager< CallbackTypes >::mutex_.
set() [2/2]
template<typename... CallbackTypes> template<typename T > auto kcenon::network::utils::callback_manager< CallbackTypes >::set (T callback) -> void inline
Sets a callback by type.
Template Parameters
T The callback type (must be unique in CallbackTypes).
Parameters
callback The callback function to store.
Definition at line 98 of file callback_manager.h.
        {
            std::lock_guard lock(mutex_);
            std::get<T>(callbacks_) = std::move(callback);
        }
References kcenon::network::utils::callback_manager< CallbackTypes >::callbacks_, and kcenon::network::utils::callback_manager< CallbackTypes >::mutex_.
Member Data Documentation
callbacks_
template<typename... CallbackTypes> std::tuple<CallbackTypes...> kcenon::network::utils::callback_manager< CallbackTypes >::callbacks_ private
Definition at line 202 of file callback_manager.h.
Referenced by kcenon::network::utils::callback_manager< CallbackTypes >::clear(), kcenon::network::utils::callback_manager< CallbackTypes >::get(), kcenon::network::utils::callback_manager< CallbackTypes >::get(), kcenon::network::utils::callback_manager< CallbackTypes >::set(), and kcenon::network::utils::callback_manager< CallbackTypes >::set().
mutex_
template<typename... CallbackTypes> std::mutex kcenon::network::utils::callback_manager< CallbackTypes >::mutex_ mutable private
Definition at line 201 of file callback_manager.h.
Referenced by kcenon::network::utils::callback_manager< CallbackTypes >::clear(), kcenon::network::utils::callback_manager< CallbackTypes >::get(), kcenon::network::utils::callback_manager< CallbackTypes >::get(), kcenon::network::utils::callback_manager< CallbackTypes >::set(), and kcenon::network::utils::callback_manager< CallbackTypes >::set().
The documentation for this class was generated from the following file:
include/kcenon/network/detail/utils/callback_manager.h