Network System: kcenon::network::core::ws_session_manager Class Reference
kcenon::network::core::ws_session_manager Class Reference
Thread-safe WebSocket session lifecycle management.
#include <ws_session_manager.h>
Public Types
using ws_connection_ptr = std::shared_ptr<ws_connection>
using base_type = session_manager_base<ws_connection>
Public Types inherited from kcenon::network::core::session_manager_base< ws_connection >
using session_ptr
using traits
using info_type
Public Member Functions
ws_session_manager (const session_config &config=session_config())
Constructs a WebSocket session manager.
auto add_connection (ws_connection_ptr conn, const std::string &conn_id="") -> std::string
Adds a connection to the manager.
auto remove_connection (const std::string &conn_id) -> bool
Removes a connection from the manager.
auto get_connection (const std::string &conn_id) const -> ws_connection_ptr
Gets a connection by ID.
auto get_all_connections () const -> std::vector< ws_connection_ptr >
Gets all active connections.
auto get_all_connection_ids () const -> std::vector< std::string >
Gets all connection IDs.
auto get_connection_count () const -> size_t
Gets the current connection count.
auto clear_all_connections () -> void
Clears all connections.
Public Member Functions inherited from kcenon::network::core::session_manager_base< ws_connection >
session_manager_base (const session_config &config=session_config())
Constructs a session manager with the given configuration.
session_manager_base (const session_manager_base &)=delete
session_manager_base (session_manager_base &&)=delete
session_manager_base & operator= (const session_manager_base &)=delete
session_manager_base & operator= (session_manager_base &&)=delete
virtual ~session_manager_base ()=default
auto can_accept_connection () const -> bool
Check if new connection can be accepted.
auto is_backpressure_active () const -> bool
Check if backpressure should be applied.
auto add_session (session_ptr session, const std::string &session_id="") -> bool
Add a session to the manager.
auto add_session_with_id (session_ptr session, const std::string &session_id="") -> std::string
Add a session and return the assigned ID.
auto remove_session (const std::string &session_id) -> bool
Remove session by ID.
auto get_session (const std::string &session_id) const -> session_ptr
Get session by ID.
auto get_all_sessions () const -> std::vector< session_ptr >
Get all active sessions.
auto get_all_session_ids () const -> std::vector< std::string >
Get all session IDs.
auto update_activity (const std::string &session_id) -> std::enable_if_t< session_traits< T >::has_activity_tracking, void >
Update session activity timestamp.
auto get_idle_duration (const std::string &session_id) const -> std::enable_if_t< session_traits< T >::has_activity_tracking, std::optional< std::chrono::milliseconds > >
Get idle duration for a session.
auto cleanup_idle_sessions () -> std::enable_if_t< session_traits< T >::has_activity_tracking, size_t >
Cleanup idle sessions that exceeded idle_timeout.
auto clear_all_sessions () -> void
Clear all sessions.
auto stop_all_sessions () -> void
Stop all sessions gracefully.
auto get_session_count () const -> size_t
Get current session count.
auto get_total_accepted () const -> uint64_t
Get total accepted connections.
auto get_total_rejected () const -> uint64_t
Get total rejected connections.
auto get_total_cleaned_up () const -> uint64_t
Get total cleaned up sessions.
auto get_utilization () const -> double
Get current session utilization.
auto set_max_sessions (size_t max_sessions) -> void
Set maximum sessions.
auto get_config () const -> const session_config &
Get current configuration.
auto get_stats () const -> stats
Get comprehensive statistics.
Static Public Member Functions
static auto generate_connection_id () -> std::string
Generates a unique connection ID.
Static Public Member Functions inherited from kcenon::network::core::session_manager_base< ws_connection >
static auto generate_id () -> std::string
Generate a unique session ID.
Additional Inherited Members
Protected Attributes inherited from kcenon::network::core::session_manager_base< ws_connection >
session_config config_
std::shared_mutex sessions_mutex_
std::unordered_map< std::string, info_type > active_sessions_
std::atomic< size_t > session_count_
std::atomic< uint64_t > total_accepted_
std::atomic< uint64_t > total_rejected_
std::atomic< uint64_t > total_cleaned_up_
Detailed Description
Thread-safe WebSocket session lifecycle management.
This class extends session_manager_base<ws_connection> to provide WebSocket-specific connection management while leveraging the unified template implementation for common functionality.
Features:
Thread-safe connection tracking
Connection limit enforcement
Backpressure signaling
Connection metrics
Automatic connection ID generation
Thread Safety:
All public methods are thread-safe
Uses shared_mutex for concurrent reads and exclusive writes
Atomic counters for metrics
Usage Example:
session_config config;
config.max_sessions = 1000;
auto manager = std::make_shared<ws_session_manager>(config);
// Check before accepting new connection
if (manager->can_accept_connection()) {
    auto conn = create_ws_connection();
    auto conn_id = manager->add_connection(conn);
    if (!conn_id.empty()) {
        // Connection accepted
    }
}
Definition at line 50 of file ws_session_manager.h.
Member Typedef Documentation
base_type
using kcenon::network::core::ws_session_manager::base_type = session_manager_base<ws_connection>
Definition at line 53 of file ws_session_manager.h.
ws_connection_ptr
using kcenon::network::core::ws_session_manager::ws_connection_ptr = std::shared_ptr<ws_connection>
Definition at line 52 of file ws_session_manager.h.
Constructor & Destructor Documentation
ws_session_manager()
kcenon::network::core::ws_session_manager::ws_session_manager (const session_config & config = session_config()) inline explicit
Constructs a WebSocket session manager.
Parameters
config Session management configuration
Definition at line 60 of file ws_session_manager.h.
        : base_type(config) {}
References config.
Member Function Documentation
add_connection()
auto kcenon::network::core::ws_session_manager::add_connection (ws_connection_ptr conn, const std::string & conn_id = "") -> std::string inline
Adds a connection to the manager.
Thread-safe operation that adds a connection with automatic or provided ID. If max_sessions limit is reached, the connection is rejected.
Parameters
conn Connection to add
conn_id Optional connection ID (auto-generated if empty)
Returns
Connection ID that was used (empty string if rejected)
Definition at line 78 of file ws_session_manager.h.
                     {
        return add_session_with_id(std::move(conn), conn_id);
    }
References kcenon::network::core::session_manager_base< ws_connection >::add_session_with_id().
clear_all_connections()
auto kcenon::network::core::ws_session_manager::clear_all_connections () -> void inline
Clears all connections.
Thread-safe operation that removes all connections.
Definition at line 144 of file ws_session_manager.h.
{ clear_all_sessions(); }
References kcenon::network::core::session_manager_base< ws_connection >::clear_all_sessions().
generate_connection_id()
static auto kcenon::network::core::ws_session_manager::generate_connection_id () -> std::string inline static
Generates a unique connection ID.
This is a static method that can be used to generate IDs externally.
Returns
Generated connection ID
Definition at line 153 of file ws_session_manager.h.
{ return generate_id(); }
References kcenon::network::core::session_manager_base< ws_connection >::generate_id().
get_all_connection_ids()
auto kcenon::network::core::ws_session_manager::get_all_connection_ids () const -> std::vector<std::string> inline nodiscard
Gets all connection IDs.
Thread-safe operation that returns a list of all connection IDs.
Returns
Vector of connection IDs
Definition at line 126 of file ws_session_manager.h.
{
        return get_all_session_ids();
    }
References kcenon::network::core::session_manager_base< ws_connection >::get_all_session_ids().
get_all_connections()
auto kcenon::network::core::ws_session_manager::get_all_connections () const -> std::vector<ws_connection_ptr> inline nodiscard
Gets all active connections.
Thread-safe operation that returns a snapshot of all connections.
Returns
Vector of all active connections
Definition at line 115 of file ws_session_manager.h.
{
        return get_all_sessions();
    }
References kcenon::network::core::session_manager_base< ws_connection >::get_all_sessions().
get_connection()
auto kcenon::network::core::ws_session_manager::get_connection (const std::string & conn_id) const -> ws_connection_ptr inline nodiscard
Gets a connection by ID.
Thread-safe read operation.
Parameters
conn_id Connection ID to lookup
Returns
Shared pointer to connection, or nullptr if not found
Definition at line 103 of file ws_session_manager.h.
{
        return get_session(conn_id);
    }
References kcenon::network::core::session_manager_base< ws_connection >::get_session().
get_connection_count()
auto kcenon::network::core::ws_session_manager::get_connection_count () const -> size_t inline nodiscard
Gets the current connection count.
Returns
Number of active connections
Definition at line 135 of file ws_session_manager.h.
{
        return get_session_count();
    }
References kcenon::network::core::session_manager_base< ws_connection >::get_session_count().
remove_connection()
auto kcenon::network::core::ws_session_manager::remove_connection (const std::string & conn_id) -> bool inline
Removes a connection from the manager.
Thread-safe operation that removes a connection by ID.
Parameters
conn_id Connection ID to remove
Returns
True if connection was found and removed
Definition at line 91 of file ws_session_manager.h.
{
        return remove_session(conn_id);
    }
References kcenon::network::core::session_manager_base< ws_connection >::remove_session().
The documentation for this class was generated from the following file:
src/internal/core/ws_session_manager.h