Network System: kcenon::network::integration::basic_container::impl Class Reference
kcenon::network::integration::basic_container::impl Class Reference
Public Member Functions
impl ()=default
std::vector< uint8_t > serialize (const std::any &data) const
std::any deserialize (const std::vector< uint8_t > &bytes) const
void set_serializer (std::function< std::vector< uint8_t >(const std::any &)> serializer)
void set_deserializer (std::function< std::any(const std::vector< uint8_t > &)> deserializer)
Private Attributes
std::function< std::vector< uint8_t >(const std::any &)> custom_serializer_
std::function< std::any(const std::vector< uint8_t > &)> custom_deserializer_
Detailed Description
Definition at line 77 of file container_integration.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::integration::basic_container::impl::impl () default
Member Function Documentation
deserialize()
std::any kcenon::network::integration::basic_container::impl::deserialize (const std::vector< uint8_t > & bytes) const inline
Definition at line 112 of file container_integration.cpp.
{
        if (custom_deserializer_) {
            return custom_deserializer_(bytes);
        }
        // Default deserialization - assume string for simplicity
        if (!bytes.empty()) {
            return std::any(std::string(bytes.begin(), bytes.end()));
        }
        return std::any{};
    }
Referenced by kcenon::network::integration::basic_container::deserialize().
serialize()
std::vector< uint8_t > kcenon::network::integration::basic_container::impl::serialize (const std::any & data) const inline
Definition at line 81 of file container_integration.cpp.
{
        if (custom_serializer_) {
            return custom_serializer_(data);
        }
        // Default serialization for common types
        try {
            if (data.type() == typeid(std::string)) {
                auto str = std::any_cast<std::string>(data);
                return std::vector<uint8_t>(str.begin(), str.end());
            } else if (data.type() == typeid(int)) {
                auto val = std::any_cast<int>(data);
                std::vector<uint8_t> bytes(sizeof(int));
                std::memcpy(bytes.data(), &val, sizeof(int));
                return bytes;
            } else if (data.type() == typeid(double)) {
                auto val = std::any_cast<double>(data);
                std::vector<uint8_t> bytes(sizeof(double));
                std::memcpy(bytes.data(), &val, sizeof(double));
                return bytes;
            } else if (data.type() == typeid(bool)) {
                auto val = std::any_cast<bool>(data);
                return {static_cast<uint8_t>(val ? 1 : 0)};
            }
        } catch (const std::bad_any_cast&) {
            // Return empty vector on error
        }
        return {};
    }
Referenced by kcenon::network::integration::basic_container::serialize().
set_deserializer()
void kcenon::network::integration::basic_container::impl::set_deserializer (std::function< std::any(const std::vector< uint8_t > &)> deserializer) inline
Definition at line 131 of file container_integration.cpp.
      {
        custom_deserializer_ = deserializer;
    }
Referenced by kcenon::network::integration::basic_container::set_deserializer().
set_serializer()
void kcenon::network::integration::basic_container::impl::set_serializer (std::function< std::vector< uint8_t >(const std::any &)> serializer) inline
Definition at line 125 of file container_integration.cpp.
      {
        custom_serializer_ = serializer;
    }
Referenced by kcenon::network::integration::basic_container::set_serializer().
Member Data Documentation
custom_deserializer_
std::function<std::any(const std::vector<uint8_t>&)> kcenon::network::integration::basic_container::impl::custom_deserializer_ private
Definition at line 139 of file container_integration.cpp.
custom_serializer_
std::function<std::vector<uint8_t>(const std::any&)> kcenon::network::integration::basic_container::impl::custom_serializer_ private
Definition at line 138 of file container_integration.cpp.
The documentation for this class was generated from the following file:
src/integration/container_integration.cpp