Network System: kcenon::network::metrics::metric_reporter Class Reference
kcenon::network::metrics::metric_reporter Class Reference
Helper class for reporting network metrics.
#include <network_metrics.h>
Static Public Member Functions
static void report_connection_accepted ()
Report a new connection accepted.
static void report_connection_failed (const std::string &reason)
Report a failed connection attempt.
static void report_bytes_sent (size_t bytes)
Report bytes sent.
static void report_bytes_received (size_t bytes)
Report bytes received.
static void report_latency (double ms)
Report network latency.
static void report_error (const std::string &error_type)
Report a network error.
static void report_timeout ()
Report a timeout.
static void report_active_connections (size_t count)
Report active connections count.
static void report_session_duration (double ms)
Report session duration.
static void record_latency (double ms)
Record latency to internal histogram.
static void record_connection_time (double ms)
Record connection time to internal histogram.
static void record_request_duration (double ms)
Record request duration to internal histogram.
static auto get_latency_p50 () -> double
Get latency 50th percentile (median)
static auto get_latency_p95 () -> double
Get latency 95th percentile.
static auto get_latency_p99 () -> double
Get latency 99th percentile.
static auto get_connection_time_p99 () -> double
Get connection time 99th percentile.
static auto get_request_duration_p99 () -> double
Get request duration 99th percentile.
static auto get_all_histograms () -> std::map< std::string, histogram_snapshot >
Get all histogram snapshots for export.
static void reset_histograms ()
Reset all histogram data.
Detailed Description
Helper class for reporting network metrics.
This class provides convenient methods to report network-related metrics to the monitoring system (if available).
Definition at line 95 of file network_metrics.h.
Member Function Documentation
get_all_histograms()
auto kcenon::network::metrics::metric_reporter::get_all_histograms () -> std::map<std::string, histogram_snapshot> static
Get all histogram snapshots for export.
Returns
Map of histogram name to snapshot
Definition at line 283 of file network_metrics.cpp.
{
    auto& storage = histogram_storage::instance();
    std::map<std::string, histogram_snapshot> result;
    result[metric_names::LATENCY_HISTOGRAM] =
        storage.latency.snapshot({{"metric", "latency"}});
    result[metric_names::CONNECTION_TIME_HISTOGRAM] =
        storage.connection_time.snapshot({{"metric", "connection_time"}});
    result[metric_names::REQUEST_DURATION_HISTOGRAM] =
        storage.request_duration.snapshot({{"metric", "request_duration"}});
    return result;
}
References kcenon::network::metrics::metric_names::CONNECTION_TIME_HISTOGRAM, kcenon::network::metrics::metric_names::LATENCY_HISTOGRAM, and kcenon::network::metrics::metric_names::REQUEST_DURATION_HISTOGRAM.
get_connection_time_p99()
auto kcenon::network::metrics::metric_reporter::get_connection_time_p99 () -> double static
Get connection time 99th percentile.
Returns
Estimated p99 connection time in milliseconds
Definition at line 271 of file network_metrics.cpp.
{
    auto& storage = histogram_storage::instance();
    return storage.connection_time.p99();
}
get_latency_p50()
auto kcenon::network::metrics::metric_reporter::get_latency_p50 () -> double static
Get latency 50th percentile (median)
Returns
Estimated median latency in milliseconds
Definition at line 253 of file network_metrics.cpp.
{
    auto& storage = histogram_storage::instance();
    return storage.latency.p50();
}
get_latency_p95()
auto kcenon::network::metrics::metric_reporter::get_latency_p95 () -> double static
Get latency 95th percentile.
Returns
Estimated p95 latency in milliseconds
Definition at line 259 of file network_metrics.cpp.
{
    auto& storage = histogram_storage::instance();
    return storage.latency.p95();
}
get_latency_p99()
auto kcenon::network::metrics::metric_reporter::get_latency_p99 () -> double static
Get latency 99th percentile.
Returns
Estimated p99 latency in milliseconds
Definition at line 265 of file network_metrics.cpp.
{
    auto& storage = histogram_storage::instance();
    return storage.latency.p99();
}
get_request_duration_p99()
auto kcenon::network::metrics::metric_reporter::get_request_duration_p99 () -> double static
Get request duration 99th percentile.
Returns
Estimated p99 request duration in milliseconds
Definition at line 277 of file network_metrics.cpp.
{
    auto& storage = histogram_storage::instance();
    return storage.request_duration.p99();
}
record_connection_time()
void kcenon::network::metrics::metric_reporter::record_connection_time (double ms) static
Record connection time to internal histogram.
Parameters
ms Connection time in milliseconds
Definition at line 225 of file network_metrics.cpp.
{
    auto& storage = histogram_storage::instance();
    storage.connection_time.record(ms);
#if KCENON_WITH_COMMON_SYSTEM
    publish_metric(metric_names::CONNECTION_TIME_HISTOGRAM, ms,
                   events::network_metric_type::histogram);
#endif
    integration::monitoring_integration_manager::instance().report_histogram(
        metric_names::CONNECTION_TIME_HISTOGRAM, ms);
}
References kcenon::network::metrics::metric_names::CONNECTION_TIME_HISTOGRAM, kcenon::network::events::histogram, kcenon::network::integration::monitoring_integration_manager::instance(), and kcenon::network::integration::monitoring_integration_manager::report_histogram().
record_latency()
void kcenon::network::metrics::metric_reporter::record_latency (double ms) static
Record latency to internal histogram.
Parameters
ms Latency in milliseconds
Records latency to a sliding histogram for percentile calculations. Also reports to the traditional monitoring integration.
Definition at line 215 of file network_metrics.cpp.
{
    // Record to sliding histogram for percentile calculations
    auto& storage = histogram_storage::instance();
    storage.latency.record(ms);
    // Also report to traditional monitoring integration
    report_latency(ms);
}
References report_latency().
record_request_duration()
void kcenon::network::metrics::metric_reporter::record_request_duration (double ms) static
Record request duration to internal histogram.
Parameters
ms Request duration in milliseconds
Definition at line 239 of file network_metrics.cpp.
{
    auto& storage = histogram_storage::instance();
    storage.request_duration.record(ms);
#if KCENON_WITH_COMMON_SYSTEM
    publish_metric(metric_names::REQUEST_DURATION_HISTOGRAM, ms,
                   events::network_metric_type::histogram);
#endif
    integration::monitoring_integration_manager::instance().report_histogram(
        metric_names::REQUEST_DURATION_HISTOGRAM, ms);
}
References kcenon::network::events::histogram, kcenon::network::integration::monitoring_integration_manager::instance(), kcenon::network::integration::monitoring_integration_manager::report_histogram(), and kcenon::network::metrics::metric_names::REQUEST_DURATION_HISTOGRAM.
report_active_connections()
void kcenon::network::metrics::metric_reporter::report_active_connections (size_t count) static
Report active connections count.
Parameters
count Number of active connections
Definition at line 187 of file network_metrics.cpp.
{
    auto count_value = static_cast<double>(count);
#if KCENON_WITH_COMMON_SYSTEM
    publish_metric(metric_names::CONNECTIONS_ACTIVE, count_value,
                   events::network_metric_type::gauge);
#endif
    integration::monitoring_integration_manager::instance().report_gauge(
        metric_names::CONNECTIONS_ACTIVE, count_value);
}
References kcenon::network::metrics::metric_names::CONNECTIONS_ACTIVE, kcenon::network::events::gauge, kcenon::network::integration::monitoring_integration_manager::instance(), and kcenon::network::integration::monitoring_integration_manager::report_gauge().
Referenced by kcenon::network::core::messaging_server::on_accept(), and kcenon::network::core::messaging_quic_server::on_session_close().
report_bytes_received()
void kcenon::network::metrics::metric_reporter::report_bytes_received (size_t bytes) static
Report bytes received.
Parameters
bytes Number of bytes received
Definition at line 136 of file network_metrics.cpp.
{
    auto byte_value = static_cast<double>(bytes);
#if KCENON_WITH_COMMON_SYSTEM
    publish_metric(metric_names::BYTES_RECEIVED, byte_value,
                   events::network_metric_type::counter);
    publish_metric(metric_names::PACKETS_RECEIVED, 1.0,
                   events::network_metric_type::counter);
#endif
    integration::monitoring_integration_manager::instance().report_counter(
        metric_names::BYTES_RECEIVED, byte_value);
    integration::monitoring_integration_manager::instance().report_counter(
        metric_names::PACKETS_RECEIVED, 1.0);
}
References kcenon::network::metrics::metric_names::BYTES_RECEIVED, kcenon::network::events::counter, kcenon::network::integration::monitoring_integration_manager::instance(), kcenon::network::metrics::metric_names::PACKETS_RECEIVED, and kcenon::network::integration::monitoring_integration_manager::report_counter().
Referenced by kcenon::network::session::messaging_session::on_receive(), and kcenon::network::session::quic_session::on_stream_data().
report_bytes_sent()
void kcenon::network::metrics::metric_reporter::report_bytes_sent (size_t bytes) static
Report bytes sent.
Parameters
bytes Number of bytes sent
Definition at line 119 of file network_metrics.cpp.
{
    auto byte_value = static_cast<double>(bytes);
#if KCENON_WITH_COMMON_SYSTEM
    publish_metric(metric_names::BYTES_SENT, byte_value,
                   events::network_metric_type::counter);
    publish_metric(metric_names::PACKETS_SENT, 1.0,
                   events::network_metric_type::counter);
#endif
    integration::monitoring_integration_manager::instance().report_counter(
        metric_names::BYTES_SENT, byte_value);
    integration::monitoring_integration_manager::instance().report_counter(
        metric_names::PACKETS_SENT, 1.0);
}
References kcenon::network::metrics::metric_names::BYTES_SENT, kcenon::network::events::counter, kcenon::network::integration::monitoring_integration_manager::instance(), kcenon::network::metrics::metric_names::PACKETS_SENT, and kcenon::network::integration::monitoring_integration_manager::report_counter().
Referenced by kcenon::network::session::quic_session::send(), kcenon::network::session::quic_session::send_on_stream(), and kcenon::network::session::messaging_session::send_packet().
report_connection_accepted()
void kcenon::network::metrics::metric_reporter::report_connection_accepted () static
Report a new connection accepted.
Definition at line 93 of file network_metrics.cpp.
{
#if KCENON_WITH_COMMON_SYSTEM
    // Publish via EventBus for external consumers (e.g., monitoring_system)
    publish_metric(metric_names::CONNECTIONS_TOTAL, 1.0,
                   events::network_metric_type::counter,
                   {{"event", "accepted"}});
#endif
    // Report to local monitoring integration
    integration::monitoring_integration_manager::instance().report_counter(
        metric_names::CONNECTIONS_TOTAL, 1.0);
}
References kcenon::network::metrics::metric_names::CONNECTIONS_TOTAL, kcenon::network::events::counter, kcenon::network::integration::monitoring_integration_manager::instance(), and kcenon::network::integration::monitoring_integration_manager::report_counter().
Referenced by kcenon::network::core::messaging_server::on_accept().
report_connection_failed()
void kcenon::network::metrics::metric_reporter::report_connection_failed (const std::string & reason) static
Report a failed connection attempt.
Parameters
reason Reason for the failure
Definition at line 107 of file network_metrics.cpp.
{
#if KCENON_WITH_COMMON_SYSTEM
    publish_metric(metric_names::CONNECTIONS_FAILED, 1.0,
                   events::network_metric_type::counter,
                   {{"reason", reason}});
#endif
    integration::monitoring_integration_manager::instance().report_counter(
        metric_names::CONNECTIONS_FAILED, 1.0, {{"reason", reason}});
}
References kcenon::network::metrics::metric_names::CONNECTIONS_FAILED, kcenon::network::events::counter, kcenon::network::integration::monitoring_integration_manager::instance(), and kcenon::network::integration::monitoring_integration_manager::report_counter().
Referenced by kcenon::network::core::messaging_server::on_accept().
report_error()
void kcenon::network::metrics::metric_reporter::report_error (const std::string & error_type) static
Report a network error.
Parameters
error_type Type of error
Definition at line 164 of file network_metrics.cpp.
{
#if KCENON_WITH_COMMON_SYSTEM
    publish_metric(metric_names::ERRORS_TOTAL, 1.0,
                   events::network_metric_type::counter,
                   {{"error_type", error_type}});
#endif
    integration::monitoring_integration_manager::instance().report_counter(
        metric_names::ERRORS_TOTAL, 1.0, {{"error_type", error_type}});
}
References kcenon::network::events::counter, kcenon::network::metrics::metric_names::ERRORS_TOTAL, kcenon::network::integration::monitoring_integration_manager::instance(), and kcenon::network::integration::monitoring_integration_manager::report_counter().
report_latency()
void kcenon::network::metrics::metric_reporter::report_latency (double ms) static
Report network latency.
Parameters
ms Latency in milliseconds
Definition at line 153 of file network_metrics.cpp.
{
#if KCENON_WITH_COMMON_SYSTEM
    publish_metric(metric_names::LATENCY_MS, ms,
                   events::network_metric_type::histogram);
#endif
    integration::monitoring_integration_manager::instance().report_histogram(
        metric_names::LATENCY_MS, ms);
}
References kcenon::network::events::histogram, kcenon::network::integration::monitoring_integration_manager::instance(), kcenon::network::metrics::metric_names::LATENCY_MS, and kcenon::network::integration::monitoring_integration_manager::report_histogram().
Referenced by record_latency().
report_session_duration()
void kcenon::network::metrics::metric_reporter::report_session_duration (double ms) static
Report session duration.
Parameters
ms Duration in milliseconds
Definition at line 200 of file network_metrics.cpp.
{
#if KCENON_WITH_COMMON_SYSTEM
    publish_metric(metric_names::SESSION_DURATION_MS, ms,
                   events::network_metric_type::histogram);
#endif
    integration::monitoring_integration_manager::instance().report_histogram(
        metric_names::SESSION_DURATION_MS, ms);
}
References kcenon::network::events::histogram, kcenon::network::integration::monitoring_integration_manager::instance(), kcenon::network::integration::monitoring_integration_manager::report_histogram(), and kcenon::network::metrics::metric_names::SESSION_DURATION_MS.
report_timeout()
void kcenon::network::metrics::metric_reporter::report_timeout () static
Report a timeout.
Definition at line 176 of file network_metrics.cpp.
{
#if KCENON_WITH_COMMON_SYSTEM
    publish_metric(metric_names::TIMEOUTS_TOTAL, 1.0,
                   events::network_metric_type::counter);
#endif
    integration::monitoring_integration_manager::instance().report_counter(
        metric_names::TIMEOUTS_TOTAL, 1.0);
}
References kcenon::network::events::counter, kcenon::network::integration::monitoring_integration_manager::instance(), kcenon::network::integration::monitoring_integration_manager::report_counter(), and kcenon::network::metrics::metric_names::TIMEOUTS_TOTAL.
reset_histograms()
void kcenon::network::metrics::metric_reporter::reset_histograms () static
Reset all histogram data.
Clears all histogram observations. Useful for testing or when starting a new measurement period.
Definition at line 298 of file network_metrics.cpp.
{
    auto& storage = histogram_storage::instance();
    storage.latency.reset();
    storage.connection_time.reset();
    storage.request_duration.reset();
}
The documentation for this class was generated from the following files:
include/kcenon/network/detail/metrics/network_metrics.h
src/metrics/network_metrics.cpp