Network System: kcenon::network::integration::container_manager::impl Class Reference
kcenon::network::integration::container_manager::impl Class Reference
Public Member Functions
impl ()=default
void register_container (const std::string &name, std::shared_ptr< container_interface > container)
std::shared_ptr< container_interface > get_container (const std::string &name) const
void set_default_container (std::shared_ptr< container_interface > container)
std::shared_ptr< container_interface > get_default_container ()
std::vector< uint8_t > serialize (const std::any &data)
std::any deserialize (const std::vector< uint8_t > &bytes)
std::vector< std::string > list_containers () const
Private Attributes
std::mutex mutex_
std::unordered_map< std::string, std::shared_ptr< container_interface > > containers_
std::shared_ptr< container_interface > default_container_
Detailed Description
Definition at line 177 of file container_integration.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::integration::container_manager::impl::impl () default
Member Function Documentation
deserialize()
std::any kcenon::network::integration::container_manager::impl::deserialize (const std::vector< uint8_t > & bytes) inline
Definition at line 219 of file container_integration.cpp.
{
        return get_default_container()->deserialize(bytes);
    }
References get_default_container().
Referenced by kcenon::network::integration::container_manager::deserialize().
get_container()
std::shared_ptr< container_interface > kcenon::network::integration::container_manager::impl::get_container (const std::string & name) const inline
Definition at line 189 of file container_integration.cpp.
            {
        std::unique_lock<std::mutex> lock(mutex_);
        auto it = containers_.find(name);
        if (it != containers_.end()) {
            return it->second;
        }
        return nullptr;
    }
References containers_, and mutex_.
Referenced by kcenon::network::integration::container_manager::get_container().
get_default_container()
std::shared_ptr< container_interface > kcenon::network::integration::container_manager::impl::get_default_container () inline
Definition at line 207 of file container_integration.cpp.
{
        std::unique_lock<std::mutex> lock(mutex_);
        if (!default_container_) {
            default_container_ = std::make_shared<basic_container>();
        }
        return default_container_;
    }
References default_container_, and mutex_.
Referenced by deserialize(), kcenon::network::integration::container_manager::get_default_container(), and serialize().
list_containers()
std::vector< std::string > kcenon::network::integration::container_manager::impl::list_containers () const inline
Definition at line 223 of file container_integration.cpp.
{
        std::unique_lock<std::mutex> lock(mutex_);
        std::vector<std::string> names;
        names.reserve(containers_.size());
        for (const auto& [name, _] : containers_) {
            names.push_back(name);
        }
        return names;
    }
References containers_, and mutex_.
Referenced by kcenon::network::integration::container_manager::list_containers().
register_container()
void kcenon::network::integration::container_manager::impl::register_container (const std::string & name, std::shared_ptr< container_interface > container) inline
Definition at line 181 of file container_integration.cpp.
      {
        std::unique_lock<std::mutex> lock(mutex_);
        containers_[name] = container;
    }
References containers_, and mutex_.
Referenced by kcenon::network::integration::container_manager::register_container().
serialize()
std::vector< uint8_t > kcenon::network::integration::container_manager::impl::serialize (const std::any & data) inline
Definition at line 215 of file container_integration.cpp.
{
        return get_default_container()->serialize(data);
    }
References get_default_container().
Referenced by kcenon::network::integration::container_manager::serialize().
set_default_container()
void kcenon::network::integration::container_manager::impl::set_default_container (std::shared_ptr< container_interface > container) inline
Definition at line 200 of file container_integration.cpp.
      {
        std::unique_lock<std::mutex> lock(mutex_);
        default_container_ = container;
    }
References default_container_, and mutex_.
Referenced by kcenon::network::integration::container_manager::set_default_container().
Member Data Documentation
containers_
std::unordered_map<std::string, std::shared_ptr<container_interface> > kcenon::network::integration::container_manager::impl::containers_ private
Definition at line 235 of file container_integration.cpp.
Referenced by get_container(), list_containers(), and register_container().
default_container_
std::shared_ptr<container_interface> kcenon::network::integration::container_manager::impl::default_container_ private
Definition at line 236 of file container_integration.cpp.
Referenced by get_default_container(), and set_default_container().
mutex_
std::mutex kcenon::network::integration::container_manager::impl::mutex_ mutable private
Definition at line 234 of file container_integration.cpp.
Referenced by get_container(), get_default_container(), list_containers(), register_container(), and set_default_container().
The documentation for this class was generated from the following file:
src/integration/container_integration.cpp