Network System: kcenon::network::core::secure_messaging_server Class Reference
kcenon::network::core::secure_messaging_server Class Reference export
module kcenon.network
A secure server class that manages incoming TLS/SSL encrypted TCP connections, creating secure_session instances for each accepted socket.
#include <secure_messaging_server.h>
Public Types
using connection_callback_t = std::function< void(std::shared_ptr< session::secure_session >)>
Callback type for new connection.
using disconnection_callback_t = std::function< void(const std::string &)>
Callback type for disconnection.
using receive_callback_t = std::function< void(std::shared_ptr< session::secure_session >, const std::vector< uint8_t > &)>
Callback type for received data.
using error_callback_t = std::function< void(std::shared_ptr< session::secure_session >, std::error_code)>
Callback type for errors.
using client_connected_callback = std::function< void(const std::string &session_id)>
Callback type for secure client connection events.
using client_disconnected_callback = std::function< void(const std::string &session_id)>
Callback type for client disconnection events.
using client_data_callback = std::function< void(const std::string &session_id, std::span< const uint8_t > data)>
Callback type for client data events.
Public Member Functions
secure_messaging_server (std::string_view server_id, const std::string &cert_file, const std::string &key_file)
Constructs a secure_messaging_server with SSL/TLS support.
~secure_messaging_server () noexcept
Destructor. If the server is still running, stop_server() is invoked.
secure_messaging_server (const secure_messaging_server &)=delete
secure_messaging_server & operator= (const secure_messaging_server &)=delete
secure_messaging_server (secure_messaging_server &&)=delete
secure_messaging_server & operator= (secure_messaging_server &&)=delete
auto start_server (unsigned short port) -> VoidResult
Starts the server on the specified port.
auto stop_server () -> VoidResult
Stops the server and closes all connections.
auto wait_for_stop () -> void
Blocks until stop_server() is called.
auto is_running () const noexcept -> bool
Check if the server is currently running.
auto server_id () const -> const std::string &
Returns the server identifier.
auto set_connection_callback (connection_callback_t callback) -> void
Sets the callback for new client connections.
auto set_disconnection_callback (disconnection_callback_t callback) -> void
Sets the callback for client disconnections.
auto set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received messages.
auto set_error_callback (error_callback_t callback) -> void
Sets the callback for session errors.
secure_messaging_server (std::string_view server_id, const ssl_config &config)
Construct a secure server with SSL configuration.
virtual ~secure_messaging_server () noexcept
Destructor.
secure_messaging_server (const secure_messaging_server &)=delete
secure_messaging_server & operator= (const secure_messaging_server &)=delete
secure_messaging_server (secure_messaging_server &&) noexcept
secure_messaging_server & operator= (secure_messaging_server &&) noexcept
bool start_server (uint16_t port, int backlog=128)
Start the secure server.
bool start_server (std::string_view address, uint16_t port, int backlog=128)
Start the secure server on a specific interface.
void stop_server ()
Stop the server.
bool wait_for_stop (std::chrono::milliseconds timeout=std::chrono::milliseconds(5000))
Wait for the server to stop.
bool send_to (std::string_view session_id, std::span< const uint8_t > data)
Send encrypted data to a specific client.
void broadcast (std::span< const uint8_t > data)
Broadcast encrypted data to all connected clients.
void disconnect (std::string_view session_id)
Disconnect a specific client.
bool is_running () const noexcept
Check if the server is running.
size_t client_count () const noexcept
Get the number of connected clients.
std::string_view server_id () const noexcept
Get the server identifier.
void set_client_connected_callback (client_connected_callback callback)
Set client connected callback.
void set_client_disconnected_callback (client_disconnected_callback callback)
Set client disconnected callback.
void set_client_data_callback (client_data_callback callback)
Set client data callback.
void set_error_callback (error_callback callback)
Set error callback.
std::optional< std::string > get_peer_certificate_subject (std::string_view session_id) const
Get peer certificate for a session.
Private Types
using callback_index = tcp_server_callback
Callback index type alias for clarity.
using callbacks_t = utils::callback_manager< connection_callback_t, disconnection_callback_t, receive_callback_t, error_callback_t >
Callback manager type for this server.
Private Member Functions
auto do_start_impl (unsigned short port) -> VoidResult
Secure TCP-specific implementation of server start.
auto do_stop_impl () -> VoidResult
Secure TCP-specific implementation of server stop.
auto get_connection_callback () const -> connection_callback_t
Gets a copy of the connection callback.
auto get_disconnection_callback () const -> disconnection_callback_t
Gets a copy of the disconnection callback.
auto get_receive_callback () const -> receive_callback_t
Gets a copy of the receive callback.
auto get_error_callback () const -> error_callback_t
Gets a copy of the error callback.
auto invoke_connection_callback (std::shared_ptr< session::secure_session > session) -> void
Invokes the connection callback with the given session.
auto do_accept () -> void
Initiates an asynchronous accept operation (async_accept).
auto on_accept (std::error_code ec, asio::ip::tcp::socket socket) -> void
Handler called when an asynchronous accept finishes.
auto cleanup_dead_sessions () -> void
Removes stopped sessions from the sessions vector.
auto start_cleanup_timer () -> void
Starts a periodic timer that triggers session cleanup.
Private Attributes
std::string server_id_
utils::lifecycle_manager lifecycle_
callbacks_t callbacks_
std::unique_ptr< asio::io_context > io_context_
std::unique_ptr< asio::executor_work_guard< asio::io_context::executor_type > > work_guard_
std::unique_ptr< asio::ip::tcp::acceptor > acceptor_
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::future< void > io_context_future_
std::unique_ptr< asio::ssl::context > ssl_context_
std::vector< std::shared_ptr< kcenon::network::session::secure_session > > sessions_
Holds all active secure sessions.
std::mutex sessions_mutex_
Mutex protecting access to sessions_ vector.
std::unique_ptr< asio::steady_timer > cleanup_timer_
Timer for periodic cleanup of stopped sessions.
std::unique_ptr< impl > pimpl_
Detailed Description
A secure server class that manages incoming TLS/SSL encrypted TCP connections, creating secure_session instances for each accepted socket.
An SSL/TLS encrypted TCP server.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling.
Thread Safety
All public methods are thread-safe.
Internal state (is_running_, sessions_) is protected by atomics and mutex.
Background thread runs io_context.run() independently.
Multiple sessions can be active concurrently without blocking each other.
Sessions vector is protected by sessions_mutex_ for thread-safe cleanup.
Key Responsibilities
Maintains an asio::io_context and tcp::acceptor to listen on a specified port.
Maintains an asio::ssl::context for TLS/SSL encryption.
For each incoming connection, performs SSL handshake and instantiates a secure_session to handle encrypted communication.
Allows external control via start_server(), stop_server(), and wait_for_stop().
Thread Model
A single background thread calls io_context.run() to process I/O events.
Each accepted connection runs asynchronously; thus multiple sessions can be active concurrently without blocking each other.
Usage Example
auto server = std::make_shared<secure_messaging_server>(
    "SecureServerID", "server.crt", "server.key");
server->start_server(5555);
// ... do work ...
server->stop_server();
This class provides a secure TCP server with SSL/TLS encryption, supporting multiple encrypted client connections.
Thread Safety
All public methods are thread-safe.
Key Features
TLS 1.2/1.3 support
Client certificate verification
Session resumption
ALPN negotiation
import kcenon.network;
using namespace kcenon::network::core;
ssl_config config;
config.certificate_path = "/path/to/server.pem";
config.private_key_path = "/path/to/server.key";
auto server = std::make_unique<secure_messaging_server>("secure_server", config);
server->start_server(443);
Definition at line 116 of file secure_messaging_server.h.
Member Typedef Documentation
callback_index
using kcenon::network::core::secure_messaging_server::callback_index = tcp_server_callback private
Callback index type alias for clarity.
Definition at line 331 of file secure_messaging_server.h.
callbacks_t
using kcenon::network::core::secure_messaging_server::callbacks_t = utils::callback_manager< connection_callback_t, disconnection_callback_t, receive_callback_t, error_callback_t > private
Callback manager type for this server.
Definition at line 334 of file secure_messaging_server.h.
client_connected_callback
using kcenon::network::core::secure_messaging_server::client_connected_callback = std::function<void(const std::string& session_id)> export
Callback type for secure client connection events.
Definition at line 307 of file ssl.cppm.
client_data_callback
using kcenon::network::core::secure_messaging_server::client_data_callback = std::function<void(const std::string& session_id, std::span<const uint8_t> data)> export
Callback type for client data events.
Definition at line 317 of file ssl.cppm.
client_disconnected_callback
using kcenon::network::core::secure_messaging_server::client_disconnected_callback = std::function<void(const std::string& session_id)> export
Callback type for client disconnection events.
Definition at line 312 of file ssl.cppm.
connection_callback_t
using kcenon::network::core::secure_messaging_server::connection_callback_t = std::function<void(std::shared_ptr<session::secure_session>)>
Callback type for new connection.
Definition at line 121 of file secure_messaging_server.h.
disconnection_callback_t
using kcenon::network::core::secure_messaging_server::disconnection_callback_t = std::function<void(const std::string&)>
Callback type for disconnection.
Definition at line 123 of file secure_messaging_server.h.
error_callback_t
using kcenon::network::core::secure_messaging_server::error_callback_t = std::function<void(std::shared_ptr<session::secure_session>, std::error_code)>
Callback type for errors.
Definition at line 128 of file secure_messaging_server.h.
receive_callback_t
using kcenon::network::core::secure_messaging_server::receive_callback_t = std::function<void(std::shared_ptr<session::secure_session>, const std::vector<uint8_t>&)>
Callback type for received data.
Definition at line 125 of file secure_messaging_server.h.
Constructor & Destructor Documentation
secure_messaging_server() [1/6]
kcenon::network::core::secure_messaging_server::secure_messaging_server (std::string_view server_id, const std::string & cert_file, const std::string & key_file)
Constructs a secure_messaging_server with SSL/TLS support.
Parameters
server_id A descriptive identifier for this server instance
cert_file Path to the SSL certificate file (.crt or .pem)
key_file Path to the SSL private key file (.key or .pem)
Definition at line 50 of file secure_messaging_server.cpp.
        : server_id_(server_id)
    {
        // Initialize SSL context with TLS 1.3 support (TICKET-009: TLS 1.3 only by default)
        ssl_context_ = std::make_unique<asio::ssl::context>(
            asio::ssl::context::tls_server);
        // Set SSL context options - disable all legacy protocols
        ssl_context_->set_options(
            asio::ssl::context::default_workarounds |
            asio::ssl::context::no_sslv2 |
            asio::ssl::context::no_sslv3 |
            asio::ssl::context::no_tlsv1 |
            asio::ssl::context::no_tlsv1_1 |
            asio::ssl::context::single_dh_use);
        // Enforce TLS 1.3 minimum version using native OpenSSL handle.
        // This prevents protocol downgrade attacks (CVSS 7.5).
        //
        // NOTE: This TLS 1.3-only policy is intentionally stricter than the
        // BCP 195 basic profile used in pacs_system (which allows TLS 1.2).
        // Rationale:
        //   - network_system handles internal service-to-service messaging
        //     where all endpoints are under our control and support TLS 1.3.
        //   - pacs_system must interoperate with legacy DICOM equipment that
        //     may only support TLS 1.2, hence the broader BCP 195 profile.
        // See: pacs_system/src/security/tls_policy.cpp  bcp195_basic_profile()
        SSL_CTX* native_ctx = ssl_context_->native_handle();
        if (native_ctx)
        {
            // Set minimum protocol version to TLS 1.3 (security hardening)
            SSL_CTX_set_min_proto_version(native_ctx, TLS1_3_VERSION);
            SSL_CTX_set_max_proto_version(native_ctx, TLS1_3_VERSION);
            // Set strong cipher suites for TLS 1.3
            SSL_CTX_set_ciphersuites(native_ctx,
                "TLS_AES_256_GCM_SHA384:"
                "TLS_CHACHA20_POLY1305_SHA256:"
                "TLS_AES_128_GCM_SHA256");
        }
        // Load certificate and private key
        try
        {
            ssl_context_->use_certificate_chain_file(cert_file);
            ssl_context_->use_private_key_file(key_file, asio::ssl::context::pem);
            NETWORK_LOG_INFO("[secure_messaging_server] SSL context initialized with TLS 1.3 only, cert: " +
                cert_file + ", key: " + key_file);
        }
        catch (const std::exception& e)
        {
            NETWORK_LOG_ERROR("[secure_messaging_server] Failed to load SSL certificates: " +
                std::string(e.what()));
            throw;
        }
    }
References NETWORK_LOG_ERROR, NETWORK_LOG_INFO, and ssl_context_.
~secure_messaging_server() [1/2]
kcenon::network::core::secure_messaging_server::~secure_messaging_server () noexcept
Destructor. If the server is still running, stop_server() is invoked.
Definition at line 110 of file secure_messaging_server.cpp.
    {
        if (lifecycle_.is_running())
        {
            (void)stop_server();
        }
    }
References kcenon::network::utils::lifecycle_manager::is_running(), lifecycle_, and stop_server().
secure_messaging_server() [2/6]
kcenon::network::core::secure_messaging_server::secure_messaging_server (const secure_messaging_server &) delete
secure_messaging_server() [3/6]
kcenon::network::core::secure_messaging_server::secure_messaging_server (secure_messaging_server &&) delete
secure_messaging_server() [4/6]
kcenon::network::core::secure_messaging_server::secure_messaging_server (std::string_view server_id, const ssl_config & config) explicit export
Construct a secure server with SSL configuration.
Parameters
server_id A string identifier for this server instance
config SSL/TLS configuration
~secure_messaging_server() [2/2]
virtual kcenon::network::core::secure_messaging_server::~secure_messaging_server () export virtual noexcept
Destructor.
secure_messaging_server() [5/6]
kcenon::network::core::secure_messaging_server::secure_messaging_server (const secure_messaging_server &) export delete
secure_messaging_server() [6/6]
kcenon::network::core::secure_messaging_server::secure_messaging_server (secure_messaging_server &&) export noexcept
Member Function Documentation
broadcast()
void kcenon::network::core::secure_messaging_server::broadcast (std::span< const uint8_t > data) export
Broadcast encrypted data to all connected clients.
Parameters
data The data to broadcast
cleanup_dead_sessions()
auto kcenon::network::core::secure_messaging_server::cleanup_dead_sessions () -> void private
Removes stopped sessions from the sessions vector.
Thread-safe: Protected by sessions_mutex_.
Definition at line 524 of file secure_messaging_server.cpp.
    {
        std::lock_guard<std::mutex> lock(sessions_mutex_);
        // Remove sessions that have been stopped
        sessions_.erase(
            std::remove_if(sessions_.begin(), sessions_.end(),
                [](const auto& session) {
                    return session && session->is_stopped();
                }),
            sessions_.end()
        );
        NETWORK_LOG_DEBUG("[secure_messaging_server] Cleaned up dead sessions. Active: " +
            std::to_string(sessions_.size()));
#if KCENON_WITH_COMMON_SYSTEM
        // Update active connections metric after cleanup
        if (monitor_) {
            monitor_->record_metric("active_connections", static_cast<double>(sessions_.size()));
        }
#endif
    }
References NETWORK_LOG_DEBUG.
client_count()
size_t kcenon::network::core::secure_messaging_server::client_count () const export noexcept
Get the number of connected clients.
Returns
Number of connected clients
disconnect()
void kcenon::network::core::secure_messaging_server::disconnect (std::string_view session_id) export
Disconnect a specific client.
Parameters
session_id The client's session ID to disconnect
do_accept()
auto kcenon::network::core::secure_messaging_server::do_accept () -> void private
Initiates an asynchronous accept operation (async_accept).
On success, on_accept() is invoked with a newly accepted tcp::socket.
Definition at line 430 of file secure_messaging_server.cpp.
    {
        auto self = shared_from_this();
        acceptor_->async_accept(
            [this, self](std::error_code ec, tcp::socket sock)
            { on_accept(ec, std::move(sock)); });
    }
do_start_impl()
auto kcenon::network::core::secure_messaging_server::do_start_impl (unsigned short port) -> VoidResult private
Secure TCP-specific implementation of server start.
Parameters
port The TCP port to bind and listen on.
Returns
Result<void> - Success if server started, or error with code:
error_codes::network_system::bind_failed if port binding failed
error_codes::common_errors::internal_error for other failures
Definition at line 247 of file secure_messaging_server.cpp.
    {
        try
        {
            // Create io_context and acceptor
            io_context_ = std::make_unique<asio::io_context>();
            // Create work guard to keep io_context running
            work_guard_ = std::make_unique<asio::executor_work_guard<asio::io_context::executor_type>>(
                asio::make_work_guard(*io_context_)
            );
            acceptor_ = std::make_unique<tcp::acceptor>(
                *io_context_, tcp::endpoint(tcp::v4(), port));
            // Create cleanup timer
            cleanup_timer_ = std::make_unique<asio::steady_timer>(*io_context_);
            // Begin accepting connections
            do_accept();
            // Start periodic cleanup timer
            start_cleanup_timer();
            // Get thread pool from network context
            thread_pool_ = network_context::instance().get_thread_pool();
            if (!thread_pool_) {
                // Fallback: create a temporary thread pool if network_context is not initialized
                NETWORK_LOG_WARN("[secure_messaging_server] network_context not initialized, creating temporary thread pool");
                thread_pool_ = std::make_shared<integration::basic_thread_pool>(std::thread::hardware_concurrency());
            }
            // Start io_context on thread pool
            io_context_future_ = thread_pool_->submit(
                [this]()
                {
                    try
                    {
                        NETWORK_LOG_DEBUG("[secure_messaging_server] io_context started");
                        io_context_->run();
                        NETWORK_LOG_DEBUG("[secure_messaging_server] io_context stopped");
                    }
                    catch (const std::exception& e)
                    {
                        NETWORK_LOG_ERROR("[secure_messaging_server] Exception in io_context: " +
                                          std::string(e.what()));
                    }
                });
            NETWORK_LOG_INFO("[secure_messaging_server] Started listening on port " +
                std::to_string(port) + " (TLS/SSL enabled)");
            return ok();
        }
        catch (const std::system_error& e)
        {
            // Check for specific error codes
            if (e.code() == asio::error::address_in_use ||
                e.code() == std::errc::address_in_use)
            {
                return error_void(
                    error_codes::network_system::bind_failed,
                    "Failed to bind to port: address already in use",
                    "secure_messaging_server::do_start_impl",
                    "Port: " + std::to_string(port)
                );
            }
            else if (e.code() == asio::error::access_denied ||
                     e.code() == std::errc::permission_denied)
            {
                return error_void(
                    error_codes::network_system::bind_failed,
                    "Failed to bind to port: permission denied",
                    "secure_messaging_server::do_start_impl",
                    "Port: " + std::to_string(port)
                );
            }
            return error_void(
                error_codes::common_errors::internal_error,
                "Failed to start secure server: " + std::string(e.what()),
                "secure_messaging_server::do_start_impl",
                "Port: " + std::to_string(port)
            );
        }
        catch (const std::exception& e)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                "Failed to start secure server: " + std::string(e.what()),
                "secure_messaging_server::do_start_impl",
                "Port: " + std::to_string(port)
            );
        }
    }
References kcenon::network::error_codes::network_system::bind_failed, kcenon::network::error_void(), kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_DEBUG, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, NETWORK_LOG_WARN, and kcenon::network::ok().
do_stop_impl()
auto kcenon::network::core::secure_messaging_server::do_stop_impl () -> VoidResult private
Secure TCP-specific implementation of server stop.
Returns
Result<void> - Success if server stopped, or error with code:
error_codes::common_errors::internal_error for failures
Definition at line 340 of file secure_messaging_server.cpp.
    {
        try
        {
            // Step 1: Cancel and close the acceptor to stop accepting new connections
            if (acceptor_)
            {
                asio::error_code ec;
                // Cancel pending async_accept operations to prevent memory leaks
                acceptor_->cancel(ec);
                if (acceptor_->is_open())
                {
                    acceptor_->close(ec);
                }
            }
            // Cancel cleanup timer
            if (cleanup_timer_)
            {
                cleanup_timer_->cancel();
            }
            // Step 2: Stop all active sessions (close sockets, stop reading)
            // NOTE: Do NOT clear sessions here - they may still be referenced by
            // pending async callbacks. We must wait for io_context to finish first.
            {
                std::lock_guard<std::mutex> lock(sessions_mutex_);
                for (auto& sess : sessions_)
                {
                    if (sess)
                    {
                        sess->stop_session();
                    }
                }
            }
            // Step 3: Release work guard to allow io_context to finish
            if (work_guard_)
            {
                work_guard_.reset();
            }
            // Step 4: Stop io_context (this cancels all remaining pending operations)
            if (io_context_)
            {
                io_context_->stop();
            }
            // Step 5: Wait for io_context task to complete
            // This ensures all pending async callbacks have finished executing
            if (io_context_future_.valid())
            {
                try {
                    io_context_future_.wait();
                } catch (const std::exception& e) {
                    NETWORK_LOG_ERROR("[secure_messaging_server] Exception while waiting for io_context: " +
                                      std::string(e.what()));
                }
            }
            // Step 6: NOW it's safe to clear sessions - all async operations are done
            {
                std::lock_guard<std::mutex> lock(sessions_mutex_);
                sessions_.clear();
            }
            // Step 7: Release resources explicitly to ensure cleanup
            acceptor_.reset();
            cleanup_timer_.reset();
            thread_pool_.reset();
            io_context_.reset();
            NETWORK_LOG_INFO("[secure_messaging_server] Stopped.");
            return ok();
        }
        catch (const std::exception& e)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                "Failed to stop secure server: " + std::string(e.what()),
                "secure_messaging_server::do_stop_impl",
                "Server ID: " + server_id_
            );
        }
    }
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, and kcenon::network::ok().
get_connection_callback()
auto kcenon::network::core::secure_messaging_server::get_connection_callback () const -> connection_callback_t private
Gets a copy of the connection callback.
Returns
Copy of the connection callback (may be empty).
Definition at line 217 of file secure_messaging_server.cpp.
    {
        return callbacks_.get<to_index(callback_index::connection)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
get_disconnection_callback()
auto kcenon::network::core::secure_messaging_server::get_disconnection_callback () const -> disconnection_callback_t private
Gets a copy of the disconnection callback.
Returns
Copy of the disconnection callback (may be empty).
Definition at line 222 of file secure_messaging_server.cpp.
    {
        return callbacks_.get<to_index(callback_index::disconnection)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
get_error_callback()
auto kcenon::network::core::secure_messaging_server::get_error_callback () const -> error_callback_t private
Gets a copy of the error callback.
Returns
Copy of the error callback (may be empty).
Definition at line 232 of file secure_messaging_server.cpp.
    {
        return callbacks_.get<to_index(callback_index::error)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
get_peer_certificate_subject()
std::optional< std::string > kcenon::network::core::secure_messaging_server::get_peer_certificate_subject (std::string_view session_id) const export
Get peer certificate for a session.
Parameters
session_id The session ID
Returns
Certificate subject name, or empty if not available
get_receive_callback()
auto kcenon::network::core::secure_messaging_server::get_receive_callback () const -> receive_callback_t private
Gets a copy of the receive callback.
Returns
Copy of the receive callback (may be empty).
Definition at line 227 of file secure_messaging_server.cpp.
    {
        return callbacks_.get<to_index(callback_index::receive)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
invoke_connection_callback()
auto kcenon::network::core::secure_messaging_server::invoke_connection_callback (std::shared_ptr< session::secure_session > session) -> void private
Invokes the connection callback with the given session.
Parameters
session The newly connected session.
Definition at line 237 of file secure_messaging_server.cpp.
    {
        callbacks_.invoke<to_index(callback_index::connection)>(session);
    }
References kcenon::network::to_index().
is_running() [1/2]
bool kcenon::network::core::secure_messaging_server::is_running () const export noexcept
Check if the server is running.
Returns
true if running
is_running() [2/2]
auto kcenon::network::core::secure_messaging_server::is_running () const -> bool noexcept
Check if the server is currently running.
Returns
true if running, false otherwise.
Definition at line 179 of file secure_messaging_server.cpp.
    {
        return lifecycle_.is_running();
    }
References kcenon::network::utils::lifecycle_manager::is_running(), and lifecycle_.
on_accept()
auto kcenon::network::core::secure_messaging_server::on_accept (std::error_code ec, asio::ip::tcp::socket socket) -> void private
Handler called when an asynchronous accept finishes.
Parameters
ec The std::error_code indicating success or error.
socket The newly accepted tcp::socket.
If ec is successful and is_running_ is still true, a secure_session is created and stored, then do_accept() is invoked again to accept the next connection.
Definition at line 438 of file secure_messaging_server.cpp.
    {
        if (!is_running())
        {
            return;
        }
        if (ec)
        {
            NETWORK_LOG_ERROR("[secure_messaging_server] Accept error: " + ec.message());
#if KCENON_WITH_COMMON_SYSTEM
            // Record connection error
            connection_errors_.fetch_add(1, std::memory_order_relaxed);
            if (monitor_) {
                monitor_->record_metric("connection_errors", static_cast<double>(connection_errors_.load()));
            }
#endif
            return;
        }
        // Cleanup dead sessions before adding new one
        cleanup_dead_sessions();
        // Create a new secure_session
        auto new_session = std::make_shared<kcenon::network::session::secure_session>(
            std::move(socket), *ssl_context_, server_id_);
        // Set up session callbacks
        auto self = shared_from_this();
        auto receive_cb = get_receive_callback();
        auto disconnection_cb = get_disconnection_callback();
        auto error_cb = get_error_callback();
        if (receive_cb)
        {
            new_session->set_receive_callback(
                [this, self, new_session, receive_cb](const std::vector<uint8_t>& data)
                {
                    receive_cb(new_session, data);
                });
        }
        if (disconnection_cb)
        {
            new_session->set_disconnection_callback(
                [this, self, new_session, disconnection_cb](const std::string& session_id)
                {
                    disconnection_cb(session_id);
                });
        }
        if (error_cb)
        {
            new_session->set_error_callback(
                [this, self, new_session, error_cb](std::error_code err)
                {
                    error_cb(new_session, err);
                });
        }
        // Track it in our sessions_ vector (protected by mutex)
        {
            std::lock_guard<std::mutex> lock(sessions_mutex_);
            sessions_.push_back(new_session);
        }
        // Start the session (this will trigger SSL handshake)
        new_session->start_session();
        // Invoke connection callback
        invoke_connection_callback(new_session);
#if KCENON_WITH_COMMON_SYSTEM
        // Record active connections metric
        {
            std::lock_guard<std::mutex> lock(sessions_mutex_);
            if (monitor_) {
                monitor_->record_metric("active_connections", static_cast<double>(sessions_.size()));
            }
        }
#endif
        // Accept next connection
        do_accept();
    }
References NETWORK_LOG_ERROR.
operator=() [1/4]
secure_messaging_server & kcenon::network::core::secure_messaging_server::operator= (const secure_messaging_server &) delete
operator=() [2/4]
secure_messaging_server & kcenon::network::core::secure_messaging_server::operator= (const secure_messaging_server &) export delete
operator=() [3/4]
secure_messaging_server & kcenon::network::core::secure_messaging_server::operator= (secure_messaging_server &&) export noexcept
operator=() [4/4]
secure_messaging_server & kcenon::network::core::secure_messaging_server::operator= (secure_messaging_server &&) delete
send_to()
bool kcenon::network::core::secure_messaging_server::send_to (std::string_view session_id, std::span< const uint8_t > data) export
Send encrypted data to a specific client.
Parameters
session_id The target client's session ID
data The data to send
Returns
true if data was queued for sending
server_id() [1/2]
auto kcenon::network::core::secure_messaging_server::server_id () const -> const std::string&
Returns the server identifier.
Returns
The server_id string.
Definition at line 184 of file secure_messaging_server.cpp.
    {
        return server_id_;
    }
References server_id_.
server_id() [2/2]
std::string_view kcenon::network::core::secure_messaging_server::server_id () const export noexcept
Get the server identifier.
Returns
Server ID string
set_client_connected_callback()
void kcenon::network::core::secure_messaging_server::set_client_connected_callback (client_connected_callback callback) export
Set client connected callback.
Parameters
callback Function to call when a client connects and TLS handshake completes
set_client_data_callback()
void kcenon::network::core::secure_messaging_server::set_client_data_callback (client_data_callback callback) export
Set client data callback.
Parameters
callback Function to call when decrypted data is received
set_client_disconnected_callback()
void kcenon::network::core::secure_messaging_server::set_client_disconnected_callback (client_disconnected_callback callback) export
Set client disconnected callback.
Parameters
callback Function to call when a client disconnects
set_connection_callback()
auto kcenon::network::core::secure_messaging_server::set_connection_callback (connection_callback_t callback) -> void
Sets the callback for new client connections.
Parameters
callback Function called when a client connects.
Definition at line 193 of file secure_messaging_server.cpp.
    {
        callbacks_.set<to_index(callback_index::connection)>(std::move(callback));
    }
References kcenon::network::to_index().
set_disconnection_callback()
auto kcenon::network::core::secure_messaging_server::set_disconnection_callback (disconnection_callback_t callback) -> void
Sets the callback for client disconnections.
Parameters
callback Function called when a client disconnects.
Definition at line 198 of file secure_messaging_server.cpp.
    {
        callbacks_.set<to_index(callback_index::disconnection)>(std::move(callback));
    }
References kcenon::network::to_index().
set_error_callback() [1/2]
void kcenon::network::core::secure_messaging_server::set_error_callback (error_callback callback) export
Set error callback.
Parameters
callback Function to call on errors
set_error_callback() [2/2]
auto kcenon::network::core::secure_messaging_server::set_error_callback (error_callback_t callback) -> void
Sets the callback for session errors.
Parameters
callback Function called when an error occurs on a session.
Definition at line 208 of file secure_messaging_server.cpp.
    {
        callbacks_.set<to_index(callback_index::error)>(std::move(callback));
    }
References kcenon::network::to_index().
set_receive_callback()
auto kcenon::network::core::secure_messaging_server::set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received messages.
Parameters
callback Function called when data is received from a client.
Definition at line 203 of file secure_messaging_server.cpp.
    {
        callbacks_.set<to_index(callback_index::receive)>(std::move(callback));
    }
References kcenon::network::to_index().
start_cleanup_timer()
auto kcenon::network::core::secure_messaging_server::start_cleanup_timer () -> void private
Starts a periodic timer that triggers session cleanup.
The cleanup timer runs every 30 seconds and calls cleanup_dead_sessions() to remove stopped sessions from the vector.
Definition at line 548 of file secure_messaging_server.cpp.
    {
        if (!cleanup_timer_ || !is_running())
        {
            return;
        }
        // Schedule cleanup every 30 seconds
        cleanup_timer_->expires_after(std::chrono::seconds(30));
        auto self = shared_from_this();
        cleanup_timer_->async_wait(
            [this, self](const std::error_code& ec)
            {
                if (!ec && is_running())
                {
                    cleanup_dead_sessions();
                    start_cleanup_timer(); // Reschedule
                }
            }
        );
    }
start_server() [1/3]
bool kcenon::network::core::secure_messaging_server::start_server (std::string_view address, uint16_t port, int backlog = 128) export
Start the secure server on a specific interface.
Parameters
address The interface address to bind to
port The port to listen on
backlog The listen backlog size
Returns
true if server started successfully
start_server() [2/3]
bool kcenon::network::core::secure_messaging_server::start_server (uint16_t port, int backlog = 128) export
Start the secure server.
Parameters
port The port to listen on
backlog The listen backlog size
Returns
true if server started successfully
start_server() [3/3]
auto kcenon::network::core::secure_messaging_server::start_server (unsigned short port) -> VoidResult
Starts the server on the specified port.
Parameters
port The port to listen on.
Returns
Result<void> - Success if server started, or error with code:
error_codes::network_system::server_already_running if already running
error_codes::network_system::bind_failed if port binding failed
error_codes::common_errors::internal_error for other failures
Definition at line 122 of file secure_messaging_server.cpp.
    {
        if (lifecycle_.is_running())
        {
            return error_void(
                error_codes::network_system::server_already_running,
                "Server is already running",
                "secure_messaging_server::start_server");
        }
        if (!lifecycle_.try_start())
        {
            return error_void(
                error_codes::network_system::server_already_running,
                "Server is already starting",
                "secure_messaging_server::start_server");
        }
        // Call implementation
        auto result = do_start_impl(port);
        if (result.is_err())
        {
            lifecycle_.mark_stopped();
        }
        return result;
    }
References kcenon::network::error_void(), and kcenon::network::error_codes::network_system::server_already_running.
stop_server() [1/2]
void kcenon::network::core::secure_messaging_server::stop_server () export
Stop the server.
stop_server() [2/2]
auto kcenon::network::core::secure_messaging_server::stop_server () -> VoidResult
Stops the server and closes all connections.
Returns
Result<void> - Success if server stopped, or error with code:
error_codes::network_system::server_not_started if not running
error_codes::common_errors::internal_error for other failures
Definition at line 150 of file secure_messaging_server.cpp.
    {
        if (!lifecycle_.is_running())
        {
            return error_void(
                error_codes::network_system::server_not_started,
                "Server is not running",
                "secure_messaging_server::stop_server");
        }
        if (!lifecycle_.prepare_stop())
        {
            return ok(); // Already stopping
        }
        // Call implementation
        auto result = do_stop_impl();
        // Signal stop completion
        lifecycle_.mark_stopped();
        return result;
    }
References kcenon::network::error_void(), kcenon::network::ok(), and kcenon::network::error_codes::network_system::server_not_started.
Referenced by ~secure_messaging_server().
wait_for_stop() [1/2]
auto kcenon::network::core::secure_messaging_server::wait_for_stop () -> void
Blocks until stop_server() is called.
Definition at line 174 of file secure_messaging_server.cpp.
    {
        lifecycle_.wait_for_stop();
    }
wait_for_stop() [2/2]
bool kcenon::network::core::secure_messaging_server::wait_for_stop (std::chrono::milliseconds timeout = std::chrono::milliseconds(5000)) export
Wait for the server to stop.
Parameters
timeout Maximum wait time
Returns
true if stopped within timeout
Member Data Documentation
acceptor_
std::unique_ptr<asio::ip::tcp::acceptor> kcenon::network::core::secure_messaging_server::acceptor_ private
Acceptor to listen for new connections.
Definition at line 354 of file secure_messaging_server.h.
callbacks_
callbacks_t kcenon::network::core::secure_messaging_server::callbacks_ private
Callback manager.
Definition at line 347 of file secure_messaging_server.h.
Referenced by get_connection_callback(), get_disconnection_callback(), get_error_callback(), and get_receive_callback().
cleanup_timer_
std::unique_ptr<asio::steady_timer> kcenon::network::core::secure_messaging_server::cleanup_timer_ private
Timer for periodic cleanup of stopped sessions.
Definition at line 377 of file secure_messaging_server.h.
io_context_
std::unique_ptr<asio::io_context> kcenon::network::core::secure_messaging_server::io_context_ private
The I/O context for async ops.
Definition at line 350 of file secure_messaging_server.h.
io_context_future_
std::future<void> kcenon::network::core::secure_messaging_server::io_context_future_ private
Future for io_context run task.
Definition at line 359 of file secure_messaging_server.h.
lifecycle_
utils::lifecycle_manager kcenon::network::core::secure_messaging_server::lifecycle_ private
Lifecycle state manager.
Definition at line 346 of file secure_messaging_server.h.
Referenced by is_running(), and ~secure_messaging_server().
pimpl_
std::unique_ptr<impl> kcenon::network::core::secure_messaging_server::pimpl_ export private
Definition at line 439 of file ssl.cppm.
server_id_
std::string kcenon::network::core::secure_messaging_server::server_id_ private
Server identifier.
Definition at line 345 of file secure_messaging_server.h.
Referenced by server_id().
sessions_
std::vector<std::shared_ptr<kcenon::network::session::secure_session> > kcenon::network::core::secure_messaging_server::sessions_ private
Holds all active secure sessions.
Definition at line 367 of file secure_messaging_server.h.
sessions_mutex_
std::mutex kcenon::network::core::secure_messaging_server::sessions_mutex_ private
Mutex protecting access to sessions_ vector.
Definition at line 372 of file secure_messaging_server.h.
ssl_context_
std::unique_ptr<asio::ssl::context> kcenon::network::core::secure_messaging_server::ssl_context_ private
SSL context for encryption.
Definition at line 362 of file secure_messaging_server.h.
Referenced by secure_messaging_server().
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::secure_messaging_server::thread_pool_ private
Thread pool for async operations.
Definition at line 357 of file secure_messaging_server.h.
work_guard_
std::unique_ptr<asio::executor_work_guard<asio::io_context::executor_type> > kcenon::network::core::secure_messaging_server::work_guard_ private
Keeps io_context running.
Definition at line 352 of file secure_messaging_server.h.
The documentation for this class was generated from the following files:
src/internal/core/secure_messaging_server.h
src/modules/ssl.cppm
src/core/secure_messaging_server.cpp