Network System: kcenon::network::core::messaging_quic_client Class Reference
kcenon::network::core::messaging_quic_client Class Reference
A QUIC client that provides reliable, multiplexed communication.
#include <quic_client.h>
Public Types
using receive_callback_t = std::function<void(const std::vector<uint8_t>&)>
Callback type for received data.
using stream_receive_callback_t = std::function<void(uint64_t, const std::vector<uint8_t>&, bool)>
Callback type for stream data (stream_id, data, fin)
using connected_callback_t = std::function<void()>
Callback type for connection established.
using disconnected_callback_t = std::function<void()>
Callback type for disconnection.
using error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Public Types inherited from kcenon::network::interfaces::i_quic_client
using receive_callback_t = std::function<void(const std::vector<uint8_t>&)>
Callback type for received data on default stream.
using stream_callback_t = std::function<void(uint64_t, const std::vector<uint8_t>&, bool)>
Callback type for stream data (stream_id, data, is_fin)
using connected_callback_t = std::function<void()>
Callback type for connection established.
using disconnected_callback_t = std::function<void()>
Callback type for disconnection.
using error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
using session_ticket_callback_t
Callback type for session ticket received (for 0-RTT resumption)
using early_data_callback_t = std::function<std::vector<uint8_t>()>
Callback type for early data production.
using early_data_accepted_callback_t = std::function<void(bool accepted)>
Callback type for early data acceptance notification.
Public Member Functions
messaging_quic_client (std::string_view client_id)
Constructs a QUIC client with a given identifier.
~messaging_quic_client () noexcept override
Destructor; automatically calls stop_client() if running.
messaging_quic_client (const messaging_quic_client &)=delete
messaging_quic_client & operator= (const messaging_quic_client &)=delete
messaging_quic_client (messaging_quic_client &&)=delete
messaging_quic_client & operator= (messaging_quic_client &&)=delete
auto start_client (std::string_view host, unsigned short port) -> VoidResult
Starts the client with default configuration.
auto start_client (std::string_view host, unsigned short port, const quic_client_config &config) -> VoidResult
Starts the client with TLS configuration.
auto stop_client () -> VoidResult
Stops the client and releases all resources.
auto client_id () const -> const std::string &
Returns the client identifier.
auto send_packet (std::vector< uint8_t > &&data) -> VoidResult
Send data on the default stream (stream 0).
auto send_packet (std::string_view data) -> VoidResult
Send string data on the default stream.
auto stats () const -> quic_connection_stats
Get connection statistics.
auto is_running () const -> bool override
Checks if the client is currently running.
auto wait_for_stop () -> void override
Blocks until stop() is called.
auto start (std::string_view host, uint16_t port) -> VoidResult override
Starts the QUIC client connecting to the specified server.
auto stop () -> VoidResult override
Stops the QUIC client.
auto is_connected () const -> bool override
Checks if the client is connected (interface version).
auto is_handshake_complete () const -> bool override
Checks if TLS handshake is complete (interface version).
auto send (std::vector< uint8_t > &&data) -> VoidResult override
Sends data on the default stream (interface version).
auto create_stream () -> Result< uint64_t > override
Creates a new bidirectional stream (interface version).
auto create_unidirectional_stream () -> Result< uint64_t > override
Creates a new unidirectional stream (interface version).
auto send_on_stream (uint64_t stream_id, std::vector< uint8_t > &&data, bool fin=false) -> VoidResult override
Sends data on a specific stream (interface version).
auto close_stream (uint64_t stream_id) -> VoidResult override
Closes a stream (interface version).
auto set_alpn_protocols (const std::vector< std::string > &protocols) -> void override
Sets the ALPN protocols for negotiation (interface version).
auto alpn_protocol () const -> std::optional< std::string > override
Gets the negotiated ALPN protocol (interface version).
auto is_early_data_accepted () const -> bool override
Checks if early data was accepted (interface version).
auto set_receive_callback (interfaces::i_quic_client::receive_callback_t callback) -> void override
Sets the callback for received data on default stream (interface version).
auto set_stream_callback (interfaces::i_quic_client::stream_callback_t callback) -> void override
Sets the callback for stream data (interface version).
auto set_connected_callback (interfaces::i_quic_client::connected_callback_t callback) -> void override
Sets the callback for connection established (interface version).
auto set_disconnected_callback (interfaces::i_quic_client::disconnected_callback_t callback) -> void override
Sets the callback for disconnection (interface version).
auto set_error_callback (interfaces::i_quic_client::error_callback_t callback) -> void override
Sets the callback for errors (interface version).
auto set_session_ticket_callback (interfaces::i_quic_client::session_ticket_callback_t callback) -> void override
Sets the callback for session tickets (interface version).
auto set_early_data_callback (interfaces::i_quic_client::early_data_callback_t callback) -> void override
Sets the callback for early data production (interface version).
auto set_early_data_accepted_callback (interfaces::i_quic_client::early_data_accepted_callback_t callback) -> void override
Sets the callback for early data acceptance notification (interface version).
auto set_stream_receive_callback (stream_receive_callback_t callback) -> void
Sets the callback for stream data reception (all streams, legacy version).
Public Member Functions inherited from kcenon::network::interfaces::i_quic_client
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Types
using callback_index = quic_client_callback
Callback index type alias for clarity.
using callbacks_t
Callback manager type for this client.
Private Member Functions
auto do_start_impl (std::string_view host, unsigned short port) -> VoidResult
QUIC-specific implementation of client start.
auto do_stop_impl () -> VoidResult
QUIC-specific implementation of client stop.
auto do_connect (std::string_view host, unsigned short port) -> void
Internal connection implementation.
auto on_connect () -> void
Callback invoked when connection is established.
auto on_stream_data (uint64_t stream_id, std::span< const uint8_t > data, bool fin) -> void
Callback for receiving stream data.
auto on_error (std::error_code ec) -> void
Callback for handling errors.
auto on_close (uint64_t error_code, const std::string &reason) -> void
Callback for connection close.
auto get_socket () const -> std::shared_ptr< internal::quic_socket >
Get the internal socket with mutex protection.
auto invoke_receive_callback (const std::vector< uint8_t > &data) -> void
Invokes the receive callback.
auto invoke_stream_receive_callback (uint64_t stream_id, const std::vector< uint8_t > &data, bool fin) -> void
Invokes the stream receive callback.
auto invoke_connected_callback () -> void
Invokes the connected callback.
auto invoke_disconnected_callback () -> void
Invokes the disconnected callback.
auto invoke_error_callback (std::error_code ec) -> void
Invokes the error callback.
Private Attributes
std::string client_id_
utils::lifecycle_manager lifecycle_
callbacks_t callbacks_
std::atomic< bool > is_connected_ {false}
std::unique_ptr< asio::io_context > io_context_
I/O context.
std::unique_ptr< asio::executor_work_guard< asio::io_context::executor_type > > work_guard_
Keeps io_context running.
std::shared_ptr< integration::thread_pool_interface > thread_pool_
Thread pool for async ops.
std::future< void > io_context_future_
Future for io_context run.
std::mutex socket_mutex_
Protects socket_ from data races.
std::shared_ptr< internal::quic_socket > socket_
The QUIC socket.
quic_client_config config_
Client configuration.
uint64_t default_stream_id_ {0}
Default stream for send_packet()
std::atomic< bool > handshake_complete_ {false}
TLS handshake status.
interfaces::i_quic_client::session_ticket_callback_t session_ticket_cb_
Session ticket callback.
interfaces::i_quic_client::early_data_callback_t early_data_cb_
Early data production callback.
interfaces::i_quic_client::early_data_accepted_callback_t early_data_accepted_cb_
Early data acceptance callback.
std::atomic< bool > early_data_accepted_ {false}
Early data acceptance status.
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
A QUIC client that provides reliable, multiplexed communication.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling. It also implements the i_quic_client interface for composition-based usage.
Overview
Implements a QUIC (RFC 9000) client with an API consistent with the existing TCP-based messaging_client, while exposing QUIC-specific features like multiple concurrent streams and 0-RTT.
Thread Safety
All public methods are thread-safe.
Socket access is protected by internal locking.
Atomic flags prevent race conditions.
Callbacks are invoked on I/O threads; implementations should be safe.
Key Features
Uses asio::io_context in a dedicated thread for I/O events.
Supports multiple concurrent streams (QUIC-specific).
Provides start_client(), stop_client(), and wait_for_stop() for lifecycle control.
Full Result<T> error handling for all fallible operations.
Interface Compliance
This class implements interfaces::i_quic_client for composition-based usage.
Comparison with messaging_client (TCP)
Feature messaging_client (TCP) messaging_quic_client
start_client() ✓ ✓
stop_client() ✓ ✓
send_packet() ✓ ✓
set_receive_callback() ✓ ✓
create_stream() ✗ ✓ (QUIC specific)
send_on_stream() ✗ ✓ (QUIC specific)
0-RTT ✗ ✓ (QUIC specific)
Definition at line 148 of file quic_client.h.
Member Typedef Documentation
callback_index
using kcenon::network::core::messaging_quic_client::callback_index = quic_client_callback private
Callback index type alias for clarity.
Definition at line 549 of file quic_client.h.
callbacks_t
using kcenon::network::core::messaging_quic_client::callbacks_t private
Initial value:
 utils::callback_manager<
            receive_callback_t,
            stream_receive_callback_t,
            connected_callback_t,
            disconnected_callback_t,
            error_callback_t
        >
Callback manager type for this client.
Definition at line 552 of file quic_client.h.
connected_callback_t
using kcenon::network::core::messaging_quic_client::connected_callback_t = std::function<void()>
Callback type for connection established.
Definition at line 158 of file quic_client.h.
disconnected_callback_t
using kcenon::network::core::messaging_quic_client::disconnected_callback_t = std::function<void()>
Callback type for disconnection.
Definition at line 160 of file quic_client.h.
error_callback_t
using kcenon::network::core::messaging_quic_client::error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Definition at line 162 of file quic_client.h.
receive_callback_t
using kcenon::network::core::messaging_quic_client::receive_callback_t = std::function<void(const std::vector<uint8_t>&)>
Callback type for received data.
Definition at line 154 of file quic_client.h.
stream_receive_callback_t
using kcenon::network::core::messaging_quic_client::stream_receive_callback_t = std::function<void(uint64_t, const std::vector<uint8_t>&, bool)>
Callback type for stream data (stream_id, data, fin)
Definition at line 156 of file quic_client.h.
Constructor & Destructor Documentation
messaging_quic_client() [1/3]
kcenon::network::core::messaging_quic_client::messaging_quic_client (std::string_view client_id) explicit
Constructs a QUIC client with a given identifier.
Parameters
client_id A string identifier for logging/debugging.
Definition at line 16 of file quic_client.cpp.
    : client_id_(client_id)
{
}
~messaging_quic_client()
kcenon::network::core::messaging_quic_client::~messaging_quic_client () override noexcept
Destructor; automatically calls stop_client() if running.
Definition at line 21 of file quic_client.cpp.
{
    if (lifecycle_.is_running())
    {
        (void)stop_client(); // Ignore result in destructor
    }
}
References kcenon::network::utils::lifecycle_manager::is_running(), lifecycle_, and stop_client().
messaging_quic_client() [2/3]
kcenon::network::core::messaging_quic_client::messaging_quic_client (const messaging_quic_client &) delete
messaging_quic_client() [3/3]
kcenon::network::core::messaging_quic_client::messaging_quic_client (messaging_quic_client &&) delete
Member Function Documentation
alpn_protocol()
auto kcenon::network::core::messaging_quic_client::alpn_protocol () const -> std::optional<std::string> nodiscard override virtual
Gets the negotiated ALPN protocol (interface version).
Returns
Protocol string if negotiated, empty optional otherwise.
Implements i_quic_client::alpn_protocol().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 457 of file quic_client.cpp.
{
    // TODO: Implement ALPN negotiation result retrieval
    return std::nullopt;
}
client_id()
auto kcenon::network::core::messaging_quic_client::client_id () const -> const std::string& nodiscard
Returns the client identifier.
Returns
The client_id string.
Definition at line 29 of file quic_client.cpp.
{
    return client_id_;
}
References client_id_.
close_stream()
auto kcenon::network::core::messaging_quic_client::close_stream (uint64_t stream_id) -> VoidResult nodiscard override virtual
Closes a stream (interface version).
Parameters
stream_id The stream to close.
Returns
VoidResult indicating success or failure.
Implements i_quic_client::close_stream().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 436 of file quic_client.cpp.
{
    auto local_socket = get_socket();
    if (!local_socket)
    {
        return error_void(
            error_codes::network_system::connection_closed,
            "Client is not connected",
            "messaging_quic_client::close_stream",
            "Client ID: " + client_id_);
    }
    return local_socket->close_stream(stream_id);
}
References kcenon::network::error_codes::network_system::connection_closed, and kcenon::network::error_void().
create_stream()
auto kcenon::network::core::messaging_quic_client::create_stream () -> Result<uint64_t> nodiscard override virtual
Creates a new bidirectional stream (interface version).
Returns
Stream ID or error.
Implements i_quic_client::create_stream().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 347 of file quic_client.cpp.
{
    auto local_socket = get_socket();
    if (!local_socket)
    {
        return error<uint64_t>(
            error_codes::network_system::connection_closed,
            "Client is not connected",
            "messaging_quic_client::create_stream",
            "Client ID: " + client_id_);
    }
    return local_socket->create_stream(false);
}
References kcenon::network::error_codes::network_system::connection_closed, and kcenon::network::error.
create_unidirectional_stream()
auto kcenon::network::core::messaging_quic_client::create_unidirectional_stream () -> Result<uint64_t> nodiscard override virtual
Creates a new unidirectional stream (interface version).
Returns
Stream ID or error.
Implements i_quic_client::create_unidirectional_stream().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 362 of file quic_client.cpp.
{
    auto local_socket = get_socket();
    if (!local_socket)
    {
        return error<uint64_t>(
            error_codes::network_system::connection_closed,
            "Client is not connected",
            "messaging_quic_client::create_unidirectional_stream",
            "Client ID: " + client_id_);
    }
    return local_socket->create_stream(true);
}
References kcenon::network::error_codes::network_system::connection_closed, and kcenon::network::error.
do_connect()
auto kcenon::network::core::messaging_quic_client::do_connect (std::string_view host, unsigned short port) -> void private
Internal connection implementation.
Definition at line 474 of file quic_client.cpp.
{
    auto resolver = std::make_shared<asio::ip::udp::resolver>(*io_context_);
    auto self = shared_from_this();
    NETWORK_LOG_INFO("[messaging_quic_client] Starting async resolve for " +
                     std::string(host) + ":" + std::to_string(port));
    resolver->async_resolve(
        std::string(host),
        std::to_string(port),
        [this, self, resolver, host_str = std::string(host)](
            std::error_code ec,
            asio::ip::udp::resolver::results_type results) {
            NETWORK_LOG_INFO("[messaging_quic_client] Resolve callback invoked");
            if (ec)
            {
                NETWORK_LOG_ERROR("[messaging_quic_client] Resolve error: " +
                                  ec.message());
                on_error(ec);
                return;
            }
            if (results.empty())
            {
                NETWORK_LOG_ERROR("[messaging_quic_client] No endpoints resolved");
                on_error(asio::error::host_not_found);
                return;
            }
            NETWORK_LOG_INFO("[messaging_quic_client] Resolve successful, creating socket");
            try
            {
                auto endpoint = *results.begin();
                // Create UDP socket
                asio::ip::udp::socket udp_socket(*io_context_, asio::ip::udp::v4());
                // Create QUIC socket as client
                auto quic_sock = std::make_shared<internal::quic_socket>(
                    std::move(udp_socket),
                    internal::quic_role::client);
                // Set callbacks
                quic_sock->set_stream_data_callback(
                    [this, self](uint64_t stream_id,
                                 std::span<const uint8_t> data,
                                 bool fin) {
                        on_stream_data(stream_id, data, fin);
                    });
                quic_sock->set_connected_callback([this, self]() {
                    on_connect();
                });
                quic_sock->set_error_callback([this, self](std::error_code err) {
                    on_error(err);
                });
                quic_sock->set_close_callback(
                    [this, self](uint64_t error_code, const std::string& reason) {
                        on_close(error_code, reason);
                    });
                // Store socket
                {
                    std::lock_guard<std::mutex> lock(socket_mutex_);
                    socket_ = quic_sock;
                }
                // Connect to server
                auto connect_result = quic_sock->connect(endpoint, host_str);
                if (connect_result.is_err())
                {
                    NETWORK_LOG_ERROR("[messaging_quic_client] Connect failed: " +
                                      connect_result.error().message);
                    on_error(std::make_error_code(std::errc::connection_refused));
                    return;
                }
                // Start receive loop
                quic_sock->start_receive();
                NETWORK_LOG_INFO("[messaging_quic_client] Connection initiated");
            }
            catch (const std::exception& e)
            {
                NETWORK_LOG_ERROR("[messaging_quic_client] Exception during connect: " +
                                  std::string(e.what()));
                on_error(std::make_error_code(std::errc::connection_refused));
            }
        });
}
References kcenon::network::internal::client, NETWORK_LOG_ERROR, and NETWORK_LOG_INFO.
do_start_impl()
auto kcenon::network::core::messaging_quic_client::do_start_impl (std::string_view host, unsigned short port) -> VoidResult private
QUIC-specific implementation of client start.
Parameters
host The server hostname or IP address.
port The server port number.
Returns
VoidResult - Success if client started, or error with code.
Definition at line 129 of file quic_client.cpp.
{
    try
    {
        {
            std::lock_guard<std::mutex> lock(socket_mutex_);
            socket_.reset();
        }
        io_context_ = std::make_unique<asio::io_context>();
        work_guard_ = std::make_unique<
            asio::executor_work_guard<asio::io_context::executor_type>>(
            asio::make_work_guard(*io_context_));
        thread_pool_ = network_context::instance().get_thread_pool();
        if (!thread_pool_)
        {
            thread_pool_ = std::make_shared<integration::basic_thread_pool>(2);
        }
        io_context_future_ = thread_pool_->submit([this]() {
            try
            {
                NETWORK_LOG_INFO(
                    "[messaging_quic_client] Starting io_context on thread pool");
                io_context_->run();
                NETWORK_LOG_INFO("[messaging_quic_client] io_context stopped");
            }
            catch (const std::exception& e)
            {
                NETWORK_LOG_ERROR("[messaging_quic_client] Exception in io_context: " +
                                  std::string(e.what()));
            }
        });
        do_connect(host, port);
        NETWORK_LOG_INFO("[messaging_quic_client] started. ID=" + client_id_ +
                         " target=" + std::string(host) + ":" +
                         std::to_string(port));
        return ok();
    }
    catch (const std::exception& e)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Failed to start client: " + std::string(e.what()),
            "messaging_quic_client::do_start_impl",
            "Client ID: " + client_id_ + ", Host: " + std::string(host));
    }
}
References kcenon::network::error_void(), kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, kcenon::network::ok(), and kcenon::network::integration::thread_pool_interface::submit().
do_stop_impl()
auto kcenon::network::core::messaging_quic_client::do_stop_impl () -> VoidResult private
QUIC-specific implementation of client stop.
Returns
VoidResult - Success if client stopped, or error with code.
Definition at line 183 of file quic_client.cpp.
{
    try
    {
        std::shared_ptr<internal::quic_socket> local_socket;
        {
            std::lock_guard<std::mutex> lock(socket_mutex_);
            local_socket = std::move(socket_);
        }
        if (local_socket)
        {
            local_socket->stop_receive();
            auto close_result = local_socket->close();
            if (close_result.is_err())
            {
                NETWORK_LOG_WARN("[messaging_quic_client] Close error: " +
                                 close_result.error().message);
            }
        }
        if (work_guard_)
        {
            work_guard_.reset();
        }
        if (io_context_)
        {
            io_context_->stop();
        }
        if (io_context_future_.valid())
        {
            io_context_future_.wait();
        }
        thread_pool_.reset();
        io_context_.reset();
        handshake_complete_.store(false);
        NETWORK_LOG_INFO("[messaging_quic_client] stopped.");
        return ok();
    }
    catch (const std::exception& e)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Failed to stop client: " + std::string(e.what()),
            "messaging_quic_client::do_stop_impl",
            "Client ID: " + client_id_);
    }
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_INFO, NETWORK_LOG_WARN, and kcenon::network::ok().
get_socket()
auto kcenon::network::core::messaging_quic_client::get_socket () const -> std::shared_ptr<internal::quic_socket> private
Get the internal socket with mutex protection.
Definition at line 649 of file quic_client.cpp.
{
    std::lock_guard<std::mutex> lock(socket_mutex_);
    return socket_;
}
References socket_, and socket_mutex_.
Referenced by is_handshake_complete().
invoke_connected_callback()
auto kcenon::network::core::messaging_quic_client::invoke_connected_callback () -> void private
Invokes the connected callback.
Definition at line 672 of file quic_client.cpp.
{
    callbacks_.invoke<to_index(callback_index::connected)>();
}
References kcenon::network::to_index().
invoke_disconnected_callback()
auto kcenon::network::core::messaging_quic_client::invoke_disconnected_callback () -> void private
Invokes the disconnected callback.
Definition at line 677 of file quic_client.cpp.
{
    callbacks_.invoke<to_index(callback_index::disconnected)>();
}
References kcenon::network::to_index().
invoke_error_callback()
auto kcenon::network::core::messaging_quic_client::invoke_error_callback (std::error_code ec) -> void private
Invokes the error callback.
Parameters
ec The error code.
Definition at line 682 of file quic_client.cpp.
{
    callbacks_.invoke<to_index(callback_index::error)>(ec);
}
References kcenon::network::to_index().
invoke_receive_callback()
auto kcenon::network::core::messaging_quic_client::invoke_receive_callback (const std::vector< uint8_t > & data) -> void private
Invokes the receive callback.
Parameters
data The received data.
Definition at line 660 of file quic_client.cpp.
{
    callbacks_.invoke<to_index(callback_index::receive)>(data);
}
References kcenon::network::to_index().
invoke_stream_receive_callback()
auto kcenon::network::core::messaging_quic_client::invoke_stream_receive_callback (uint64_t stream_id, const std::vector< uint8_t > & data, bool fin) -> void private
Invokes the stream receive callback.
Parameters
stream_id The stream ID.
data The received data.
fin Whether this is the final data on the stream.
Definition at line 665 of file quic_client.cpp.
{
    callbacks_.invoke<to_index(callback_index::stream_receive)>(stream_id, data, fin);
}
References kcenon::network::to_index().
is_connected()
auto kcenon::network::core::messaging_quic_client::is_connected () const -> bool nodiscard override virtual
Checks if the client is connected (interface version).
Returns
true if connected, false otherwise.
Implements i_quic_client::is_connected().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 233 of file quic_client.cpp.
{
    return is_connected_.load(std::memory_order_acquire);
}
References is_connected_.
is_early_data_accepted()
auto kcenon::network::core::messaging_quic_client::is_early_data_accepted () const -> bool nodiscard override virtual
Checks if early data was accepted (interface version).
Returns
true if accepted, false otherwise.
Implements i_quic_client::is_early_data_accepted().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 463 of file quic_client.cpp.
{
    return early_data_accepted_.load();
}
References early_data_accepted_.
is_handshake_complete()
auto kcenon::network::core::messaging_quic_client::is_handshake_complete () const -> bool nodiscard override virtual
Checks if TLS handshake is complete (interface version).
Returns
true if handshake is done, false otherwise.
Implements i_quic_client::is_handshake_complete().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 238 of file quic_client.cpp.
{
    auto local_socket = get_socket();
    if (!local_socket)
    {
        return false;
    }
    return local_socket->is_handshake_complete();
}
References get_socket().
is_running()
auto kcenon::network::core::messaging_quic_client::is_running () const -> bool nodiscard override virtual
Checks if the client is currently running.
Returns
true if running, false otherwise.
Implements i_network_component::is_running().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 34 of file quic_client.cpp.
{
    return lifecycle_.is_running();
}
References kcenon::network::utils::lifecycle_manager::is_running(), and lifecycle_.
on_close()
auto kcenon::network::core::messaging_quic_client::on_close (uint64_t error_code, const std::string & reason) -> void private
Callback for connection close.
Definition at line 634 of file quic_client.cpp.
{
    NETWORK_LOG_INFO("[messaging_quic_client] Connection closed. Error code: " +
                     std::to_string(error_code) + ", reason: " + reason);
    if (is_connected())
    {
        // Invoke disconnected callback
        invoke_disconnected_callback();
    }
    is_connected_.store(false, std::memory_order_release);
}
References NETWORK_LOG_INFO.
on_connect()
auto kcenon::network::core::messaging_quic_client::on_connect () -> void private
Callback invoked when connection is established.
Definition at line 570 of file quic_client.cpp.
{
    NETWORK_LOG_INFO("[messaging_quic_client] Connected successfully.");
    is_connected_.store(true, std::memory_order_release);
    handshake_complete_.store(true);
    // Create default stream for send_packet()
    auto local_socket = get_socket();
    if (local_socket)
    {
        auto stream_result = local_socket->create_stream(false);
        if (stream_result.is_ok())
        {
            default_stream_id_ = stream_result.value();
            NETWORK_LOG_DEBUG("[messaging_quic_client] Default stream created: " +
                              std::to_string(default_stream_id_));
        }
    }
    // Invoke connected callback
    invoke_connected_callback();
}
References NETWORK_LOG_DEBUG, and NETWORK_LOG_INFO.
on_error()
auto kcenon::network::core::messaging_quic_client::on_error (std::error_code ec) -> void private
Callback for handling errors.
Definition at line 618 of file quic_client.cpp.
{
    NETWORK_LOG_ERROR("[messaging_quic_client] Error: " + ec.message());
    // Invoke error callback
    invoke_error_callback(ec);
    if (is_connected())
    {
        // Invoke disconnected callback
        invoke_disconnected_callback();
    }
    is_connected_.store(false, std::memory_order_release);
}
References NETWORK_LOG_ERROR.
on_stream_data()
auto kcenon::network::core::messaging_quic_client::on_stream_data (uint64_t stream_id, std::span< const uint8_t > data, bool fin) -> void private
Callback for receiving stream data.
Definition at line 593 of file quic_client.cpp.
{
    if (!is_connected())
    {
        return;
    }
    NETWORK_LOG_DEBUG("[messaging_quic_client] Received " +
                      std::to_string(data.size()) +
                      " bytes on stream " + std::to_string(stream_id));
    std::vector<uint8_t> data_copy(data.begin(), data.end());
    // Invoke stream receive callback
    invoke_stream_receive_callback(stream_id, data_copy, fin);
    // Also invoke default receive callback for default stream
    if (stream_id == default_stream_id_)
    {
        invoke_receive_callback(data_copy);
    }
}
References NETWORK_LOG_DEBUG.
operator=() [1/2]
messaging_quic_client & kcenon::network::core::messaging_quic_client::operator= (const messaging_quic_client &) delete
operator=() [2/2]
messaging_quic_client & kcenon::network::core::messaging_quic_client::operator= (messaging_quic_client &&) delete
send()
auto kcenon::network::core::messaging_quic_client::send (std::vector< uint8_t > && data) -> VoidResult nodiscard override virtual
Sends data on the default stream (interface version).
Parameters
data The data to send.
Returns
VoidResult indicating success or failure.
Implements i_quic_client::send().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 342 of file quic_client.cpp.
{
    return send_packet(std::move(data));
}
send_on_stream()
auto kcenon::network::core::messaging_quic_client::send_on_stream (uint64_t stream_id, std::vector< uint8_t > && data, bool fin = false) -> VoidResult nodiscard override virtual
Sends data on a specific stream (interface version).
Parameters
stream_id The target stream ID.
data The data to send.
fin True if this is the final data on the stream.
Returns
VoidResult indicating success or failure.
Implements i_quic_client::send_on_stream().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 377 of file quic_client.cpp.
{
    // Create tracing span for stream send operation
    auto span = tracing::is_tracing_enabled()
        ? std::make_optional(tracing::trace_context::create_span("quic.stream.send"))
        : std::nullopt;
    if (span)
    {
        span->set_attribute("net.transport", "quic")
             .set_attribute("message.size", static_cast<int64_t>(data.size()))
             .set_attribute("quic.stream_id", static_cast<int64_t>(stream_id))
             .set_attribute("quic.fin", fin)
             .set_attribute("client.id", client_id_);
    }
    if (data.empty())
    {
        if (span)
        {
            span->set_error("Data cannot be empty");
        }
        return error_void(
            error_codes::common_errors::invalid_argument,
            "Data cannot be empty",
            "messaging_quic_client::send_on_stream",
            "Client ID: " + client_id_);
    }
    auto local_socket = get_socket();
    if (!local_socket)
    {
        if (span)
        {
            span->set_error("Client is not connected");
        }
        return error_void(
            error_codes::network_system::connection_closed,
            "Client is not connected",
            "messaging_quic_client::send_on_stream",
            "Client ID: " + client_id_);
    }
    auto result = local_socket->send_stream_data(stream_id, std::move(data), fin);
    if (span)
    {
        if (result.is_err())
        {
            span->set_error(result.error().message);
        }
        else
        {
            span->set_status(tracing::span_status::ok);
        }
    }
    return result;
}
References kcenon::network::error_codes::network_system::connection_closed, kcenon::network::tracing::trace_context::create_span(), kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, kcenon::network::tracing::is_tracing_enabled(), and kcenon::network::tracing::ok.
send_packet() [1/2]
auto kcenon::network::core::messaging_quic_client::send_packet (std::string_view data) -> VoidResult nodiscard
Send string data on the default stream.
Parameters
data String to send.
Returns
VoidResult indicating success or error.
auto result = client->send_packet("Hello QUIC!");
Definition at line 317 of file quic_client.cpp.
{
    if (data.empty())
    {
        return error_void(
            error_codes::common_errors::invalid_argument,
            "Data cannot be empty",
            "messaging_quic_client::send_packet",
            "Client ID: " + client_id_);
    }
    std::vector<uint8_t> byte_data(data.begin(), data.end());
    return send_packet(std::move(byte_data));
}
References kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::invalid_argument.
send_packet() [2/2]
auto kcenon::network::core::messaging_quic_client::send_packet (std::vector< uint8_t > && data) -> VoidResult nodiscard
Send data on the default stream (stream 0).
Parameters
data Data to send (moved for efficiency).
Returns
VoidResult indicating success or error.
Errors
connection_closed if not connected
invalid_argument if data is empty
send_failed for other failures
std::vector<uint8_t> data = {1, 2, 3, 4};
auto result = client->send_packet(std::move(data));
Definition at line 248 of file quic_client.cpp.
{
    // Create tracing span for send operation
    auto span = tracing::is_tracing_enabled()
        ? std::make_optional(tracing::trace_context::create_span("quic.client.send"))
        : std::nullopt;
    if (span)
    {
        span->set_attribute("net.transport", "quic")
             .set_attribute("message.size", static_cast<int64_t>(data.size()))
             .set_attribute("quic.stream_id", static_cast<int64_t>(default_stream_id_))
             .set_attribute("client.id", client_id_);
    }
    if (!is_running())
    {
        if (span)
        {
            span->set_error("Client is not running");
        }
        return error_void(
            error_codes::network_system::connection_closed,
            "Client is not running",
            "messaging_quic_client::send_packet",
            "Client ID: " + client_id_);
    }
    if (data.empty())
    {
        if (span)
        {
            span->set_error("Data cannot be empty");
        }
        return error_void(
            error_codes::common_errors::invalid_argument,
            "Data cannot be empty",
            "messaging_quic_client::send_packet",
            "Client ID: " + client_id_);
    }
    auto local_socket = get_socket();
    if (!is_connected() || !local_socket)
    {
        if (span)
        {
            span->set_error("Client is not connected");
        }
        return error_void(
            error_codes::network_system::connection_closed,
            "Client is not connected",
            "messaging_quic_client::send_packet",
            "Client ID: " + client_id_);
    }
    auto result = local_socket->send_stream_data(default_stream_id_, std::move(data));
    if (span)
    {
        if (result.is_err())
        {
            span->set_error(result.error().message);
        }
        else
        {
            span->set_status(tracing::span_status::ok);
        }
    }
    return result;
}
References kcenon::network::error_codes::network_system::connection_closed, kcenon::network::tracing::trace_context::create_span(), kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, kcenon::network::tracing::is_tracing_enabled(), and kcenon::network::tracing::ok.
set_alpn_protocols()
auto kcenon::network::core::messaging_quic_client::set_alpn_protocols (const std::vector< std::string > & protocols) -> void override virtual
Sets the ALPN protocols for negotiation (interface version).
Parameters
protocols List of protocol identifiers.
Implements i_quic_client::set_alpn_protocols().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 451 of file quic_client.cpp.
{
    config_.alpn_protocols = protocols;
}
set_connected_callback()
auto kcenon::network::core::messaging_quic_client::set_connected_callback (interfaces::i_quic_client::connected_callback_t callback) -> void override virtual
Sets the callback for connection established (interface version).
Parameters
callback The callback function.
Implements i_quic_client::set_connected_callback().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 712 of file quic_client.cpp.
{
    callbacks_.set<to_index(callback_index::connected)>(std::move(callback));
}
References kcenon::network::to_index().
set_disconnected_callback()
auto kcenon::network::core::messaging_quic_client::set_disconnected_callback (interfaces::i_quic_client::disconnected_callback_t callback) -> void override virtual
Sets the callback for disconnection (interface version).
Parameters
callback The callback function.
Implements i_quic_client::set_disconnected_callback().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 718 of file quic_client.cpp.
{
    callbacks_.set<to_index(callback_index::disconnected)>(std::move(callback));
}
References kcenon::network::to_index().
set_early_data_accepted_callback()
auto kcenon::network::core::messaging_quic_client::set_early_data_accepted_callback (interfaces::i_quic_client::early_data_accepted_callback_t callback) -> void override virtual
Sets the callback for early data acceptance notification (interface version).
Parameters
callback The callback function.
Implements i_quic_client::set_early_data_accepted_callback().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 742 of file quic_client.cpp.
{
    early_data_accepted_cb_ = std::move(callback);
}
set_early_data_callback()
auto kcenon::network::core::messaging_quic_client::set_early_data_callback (interfaces::i_quic_client::early_data_callback_t callback) -> void override virtual
Sets the callback for early data production (interface version).
Parameters
callback The callback function.
Implements i_quic_client::set_early_data_callback().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 736 of file quic_client.cpp.
{
    early_data_cb_ = std::move(callback);
}
set_error_callback()
auto kcenon::network::core::messaging_quic_client::set_error_callback (interfaces::i_quic_client::error_callback_t callback) -> void override virtual
Sets the callback for errors (interface version).
Parameters
callback The callback function.
Implements i_quic_client::set_error_callback().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 724 of file quic_client.cpp.
{
    callbacks_.set<to_index(callback_index::error)>(std::move(callback));
}
References kcenon::network::to_index().
set_receive_callback()
auto kcenon::network::core::messaging_quic_client::set_receive_callback (interfaces::i_quic_client::receive_callback_t callback) -> void override virtual
Sets the callback for received data on default stream (interface version).
Parameters
callback The callback function.
Implements i_quic_client::set_receive_callback().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 700 of file quic_client.cpp.
{
    callbacks_.set<to_index(callback_index::receive)>(std::move(callback));
}
References kcenon::network::to_index().
set_session_ticket_callback()
auto kcenon::network::core::messaging_quic_client::set_session_ticket_callback (interfaces::i_quic_client::session_ticket_callback_t callback) -> void override virtual
Sets the callback for session tickets (interface version).
Parameters
callback The callback function.
Implements i_quic_client::set_session_ticket_callback().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 730 of file quic_client.cpp.
{
    session_ticket_cb_ = std::move(callback);
}
set_stream_callback()
auto kcenon::network::core::messaging_quic_client::set_stream_callback (interfaces::i_quic_client::stream_callback_t callback) -> void override virtual
Sets the callback for stream data (interface version).
Parameters
callback The callback function.
Implements i_quic_client::set_stream_callback().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 706 of file quic_client.cpp.
{
    callbacks_.set<to_index(callback_index::stream_receive)>(std::move(callback));
}
References kcenon::network::to_index().
set_stream_receive_callback()
auto kcenon::network::core::messaging_quic_client::set_stream_receive_callback (stream_receive_callback_t callback) -> void
Sets the callback for stream data reception (all streams, legacy version).
Parameters
callback Function called with stream ID, data, and FIN flag.
Note
This is kept for backward compatibility. New code should use set_stream_callback() from the i_quic_client interface.
Definition at line 691 of file quic_client.cpp.
{
    callbacks_.set<to_index(callback_index::stream_receive)>(std::move(callback));
}
References kcenon::network::to_index().
start()
auto kcenon::network::core::messaging_quic_client::start (std::string_view host, uint16_t port) -> VoidResult nodiscard override virtual
Starts the QUIC client connecting to the specified server.
Parameters
host The server hostname or IP address.
port The server port number.
Returns
VoidResult indicating success or failure.
Implements i_quic_client::start(). Delegates to start_client().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 332 of file quic_client.cpp.
{
    return start_client(host, port);
}
start_client() [1/2]
auto kcenon::network::core::messaging_quic_client::start_client (std::string_view host, unsigned short port) -> VoidResult nodiscard
Starts the client with default configuration.
Parameters
host Server hostname or IP address.
port Server port number.
Returns
VoidResult indicating success or error.
Definition at line 44 of file quic_client.cpp.
{
    // Use default config
    return start_client(host, port, quic_client_config{});
}
start_client() [2/2]
auto kcenon::network::core::messaging_quic_client::start_client (std::string_view host, unsigned short port, const quic_client_config & config) -> VoidResult nodiscard
Starts the client with TLS configuration.
Parameters
host Server hostname or IP address.
port Server port number.
config QUIC client configuration.
Returns
VoidResult indicating success or error.
Definition at line 51 of file quic_client.cpp.
{
    // Create tracing span for client start operation
    auto span = tracing::is_tracing_enabled()
        ? std::make_optional(tracing::trace_context::create_span("quic.client.start"))
        : std::nullopt;
    if (span)
    {
        span->set_attribute("net.peer.name", host)
             .set_attribute("net.peer.port", static_cast<int64_t>(port))
             .set_attribute("net.transport", "quic")
             .set_attribute("client.id", client_id_);
    }
    if (lifecycle_.is_running())
    {
        if (span)
        {
            span->set_error("QUIC client is already running");
        }
        return error_void(
            error_codes::common_errors::already_exists,
            "QUIC client is already running",
            "messaging_quic_client::start_client");
    }
    if (host.empty())
    {
        if (span)
        {
            span->set_error("Host cannot be empty");
        }
        return error_void(
            error_codes::common_errors::invalid_argument,
            "Host cannot be empty",
            "messaging_quic_client::start_client");
    }
    config_ = config;
    lifecycle_.set_running();
    is_connected_.store(false);
    auto result = do_start_impl(host, port);
    if (result.is_err())
    {
        lifecycle_.mark_stopped();
        if (span)
        {
            span->set_error(result.error().message);
        }
    }
    else
    {
        if (span)
        {
            span->set_status(tracing::span_status::ok);
        }
    }
    return result;
}
References kcenon::network::error_codes::common_errors::already_exists, config, kcenon::network::tracing::trace_context::create_span(), kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, kcenon::network::tracing::is_tracing_enabled(), and kcenon::network::tracing::ok.
stats()
auto kcenon::network::core::messaging_quic_client::stats () const -> quic_connection_stats nodiscard
Get connection statistics.
Returns
Current connection stats.
Definition at line 468 of file quic_client.cpp.
{
    // TODO: Implement connection statistics retrieval
    return quic_connection_stats{};
}
stop()
auto kcenon::network::core::messaging_quic_client::stop () -> VoidResult nodiscard override virtual
Stops the QUIC client.
Returns
VoidResult indicating success or failure.
Implements i_quic_client::stop(). Delegates to stop_client().
Implements kcenon::network::interfaces::i_quic_client.
Definition at line 337 of file quic_client.cpp.
{
    return stop_client();
}
stop_client()
auto kcenon::network::core::messaging_quic_client::stop_client () -> VoidResult nodiscard
Stops the client and releases all resources.
Returns
Result<void> - Success if client stopped, or error with code.
Definition at line 115 of file quic_client.cpp.
{
    if (!lifecycle_.prepare_stop())
    {
        return ok(); // Already stopped or not running
    }
    is_connected_.store(false);
    auto result = do_stop_impl();
    lifecycle_.mark_stopped();
    return result;
}
References kcenon::network::ok().
Referenced by ~messaging_quic_client().
wait_for_stop()
auto kcenon::network::core::messaging_quic_client::wait_for_stop () -> void override virtual
Blocks until stop() is called.
Implements i_network_component::wait_for_stop().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 39 of file quic_client.cpp.
{
    lifecycle_.wait_for_stop();
}
Member Data Documentation
callbacks_
callbacks_t kcenon::network::core::messaging_quic_client::callbacks_ private
Callback manager.
Definition at line 566 of file quic_client.h.
client_id_
std::string kcenon::network::core::messaging_quic_client::client_id_ private
Client identifier.
Definition at line 564 of file quic_client.h.
Referenced by client_id().
config_
quic_client_config kcenon::network::core::messaging_quic_client::config_ private
Client configuration.
Definition at line 579 of file quic_client.h.
default_stream_id_
uint64_t kcenon::network::core::messaging_quic_client::default_stream_id_ {0} private
Default stream for send_packet()
Definition at line 580 of file quic_client.h.
{0};
early_data_accepted_
std::atomic<bool> kcenon::network::core::messaging_quic_client::early_data_accepted_ {false} private
Early data acceptance status.
Definition at line 588 of file quic_client.h.
{false};
Referenced by is_early_data_accepted().
early_data_accepted_cb_
interfaces::i_quic_client::early_data_accepted_callback_t kcenon::network::core::messaging_quic_client::early_data_accepted_cb_ private
Early data acceptance callback.
Definition at line 587 of file quic_client.h.
early_data_cb_
interfaces::i_quic_client::early_data_callback_t kcenon::network::core::messaging_quic_client::early_data_cb_ private
Early data production callback.
Definition at line 586 of file quic_client.h.
handshake_complete_
std::atomic<bool> kcenon::network::core::messaging_quic_client::handshake_complete_ {false} private
TLS handshake status.
Definition at line 582 of file quic_client.h.
{false};
io_context_
std::unique_ptr<asio::io_context> kcenon::network::core::messaging_quic_client::io_context_ private
I/O context.
Definition at line 569 of file quic_client.h.
io_context_future_
std::future<void> kcenon::network::core::messaging_quic_client::io_context_future_ private
Future for io_context run.
Definition at line 574 of file quic_client.h.
is_connected_
std::atomic<bool> kcenon::network::core::messaging_quic_client::is_connected_ {false} private
True if connected to remote.
Definition at line 567 of file quic_client.h.
{false};
Referenced by is_connected().
lifecycle_
utils::lifecycle_manager kcenon::network::core::messaging_quic_client::lifecycle_ private
Lifecycle state manager.
Definition at line 565 of file quic_client.h.
Referenced by is_running(), and ~messaging_quic_client().
session_ticket_cb_
interfaces::i_quic_client::session_ticket_callback_t kcenon::network::core::messaging_quic_client::session_ticket_cb_ private
Session ticket callback.
Definition at line 585 of file quic_client.h.
socket_
std::shared_ptr<internal::quic_socket> kcenon::network::core::messaging_quic_client::socket_ private
The QUIC socket.
Definition at line 577 of file quic_client.h.
Referenced by get_socket().
socket_mutex_
std::mutex kcenon::network::core::messaging_quic_client::socket_mutex_ mutable private
Protects socket_ from data races.
Definition at line 576 of file quic_client.h.
Referenced by get_socket().
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::messaging_quic_client::thread_pool_ private
Thread pool for async ops.
Definition at line 573 of file quic_client.h.
work_guard_
std::unique_ptr<asio::executor_work_guard<asio::io_context::executor_type> > kcenon::network::core::messaging_quic_client::work_guard_ private
Keeps io_context running.
Definition at line 571 of file quic_client.h.
The documentation for this class was generated from the following files:
src/internal/experimental/quic_client.h
src/experimental/quic_client.cpp