Network System: kcenon::network::connection_limiter Class Reference
kcenon::network::connection_limiter Class Reference
Connection count limiter.
#include <rate_limiter.h>
Public Member Functions
connection_limiter (size_t max_connections=1000)
Construct connection limiter.
bool can_accept () const noexcept
Check if a new connection can be accepted.
bool try_accept () noexcept
Try to accept a connection.
void on_connect () noexcept
Register a new connection.
void on_disconnect () noexcept
Unregister a connection.
size_t current () const noexcept
Get current connection count.
size_t max () const noexcept
Get maximum connection limit.
void set_max (size_t max_connections) noexcept
Set maximum connection limit.
size_t available () const noexcept
Get available connection slots.
bool at_capacity () const noexcept
Check if at capacity.
Private Attributes
size_t max_connections_
std::atomic< size_t > current_connections_
Detailed Description
Connection count limiter.
Limits the number of concurrent connections to prevent resource exhaustion attacks.
Thread Safety
This class is thread-safe. All public methods can be called from multiple threads concurrently.
Definition at line 330 of file rate_limiter.h.
Constructor & Destructor Documentation
connection_limiter()
kcenon::network::connection_limiter::connection_limiter (size_t max_connections = 1000) inline explicit
Construct connection limiter.
Parameters
max_connections Maximum allowed concurrent connections
Definition at line 336 of file rate_limiter.h.
        : max_connections_(max_connections)
        , current_connections_(0) {}
Member Function Documentation
at_capacity()
bool kcenon::network::connection_limiter::at_capacity () const inline noexcept
Check if at capacity.
Returns
true if at maximum connections
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 422 of file rate_limiter.h.
{
        return current_connections_.load(std::memory_order_acquire) >= max_connections_;
    }
References current_connections_, and max_connections_.
available()
size_t kcenon::network::connection_limiter::available () const inline noexcept
Get available connection slots.
Returns
Number of available slots
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 413 of file rate_limiter.h.
{
        size_t current = current_connections_.load(std::memory_order_acquire);
        return (current < max_connections_) ? (max_connections_ - current) : 0;
    }
References current(), current_connections_, and max_connections_.
can_accept()
bool kcenon::network::connection_limiter::can_accept () const inline noexcept
Check if a new connection can be accepted.
Returns
true if connection can be accepted
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 344 of file rate_limiter.h.
{
        return current_connections_.load(std::memory_order_acquire) < max_connections_;
    }
References current_connections_, and max_connections_.
Referenced by kcenon::network::per_client_connection_limiter::try_accept().
current()
size_t kcenon::network::connection_limiter::current () const inline noexcept
Get current connection count.
Returns
Current number of connections
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 389 of file rate_limiter.h.
{
        return current_connections_.load(std::memory_order_acquire);
    }
References current_connections_.
Referenced by available(), kcenon::network::per_client_connection_limiter::total_connections(), and try_accept().
max()
size_t kcenon::network::connection_limiter::max () const inline noexcept
Get maximum connection limit.
Returns
Maximum allowed connections
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 397 of file rate_limiter.h.
{
        return max_connections_;
    }
References max_connections_.
on_connect()
void kcenon::network::connection_limiter::on_connect () inline noexcept
Register a new connection.
Note
Use try_accept() instead when possible to atomically check and increment.
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 370 of file rate_limiter.h.
{
        current_connections_.fetch_add(1, std::memory_order_release);
    }
References current_connections_.
on_disconnect()
void kcenon::network::connection_limiter::on_disconnect () inline noexcept
Unregister a connection.
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 377 of file rate_limiter.h.
{
        size_t prev = current_connections_.fetch_sub(1, std::memory_order_release);
        // Prevent underflow (shouldn't happen in correct usage)
        if (prev == 0) {
            current_connections_.fetch_add(1, std::memory_order_release);
        }
    }
References current_connections_.
Referenced by kcenon::network::connection_guard::release(), and kcenon::network::per_client_connection_limiter::release().
set_max()
void kcenon::network::connection_limiter::set_max (size_t max_connections) inline noexcept
Set maximum connection limit.
Parameters
max_connections New maximum
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 405 of file rate_limiter.h.
{
        max_connections_ = max_connections;
    }
References max_connections_.
try_accept()
bool kcenon::network::connection_limiter::try_accept () inline noexcept
Try to accept a connection.
Returns
true if connection was accepted, false if limit reached
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 352 of file rate_limiter.h.
{
        size_t current = current_connections_.load(std::memory_order_acquire);
        while (current < max_connections_) {
            if (current_connections_.compare_exchange_weak(
                    current, current + 1,
                    std::memory_order_acq_rel,
                    std::memory_order_acquire)) {
                return true;
            }
        }
        return false;
    }
References current(), current_connections_, and max_connections_.
Referenced by kcenon::network::per_client_connection_limiter::try_accept().
Member Data Documentation
current_connections_
std::atomic<size_t> kcenon::network::connection_limiter::current_connections_ private
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 428 of file rate_limiter.h.
Referenced by at_capacity(), available(), can_accept(), current(), on_connect(), on_disconnect(), and try_accept().
max_connections_
size_t kcenon::network::connection_limiter::max_connections_ private
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 427 of file rate_limiter.h.
Referenced by at_capacity(), available(), can_accept(), max(), set_max(), and try_accept().
The documentation for this class was generated from the following file:
src/internal/utils/rate_limiter.h