Network System: kcenon::network::protocols::quic::packet_builder Class Reference
kcenon::network::protocols::quic::packet_builder Class Reference
Builder for QUIC packet headers (RFC 9000 Section 17)
#include <packet.h>
Static Public Member Functions
static auto build_initial (const connection_id &dest_cid, const connection_id &src_cid, const std::vector< uint8_t > &token, uint64_t packet_number, uint32_t version=quic_version::version_1) -> std::vector< uint8_t >
Build an Initial packet header.
static auto build_handshake (const connection_id &dest_cid, const connection_id &src_cid, uint64_t packet_number, uint32_t version=quic_version::version_1) -> std::vector< uint8_t >
Build a Handshake packet header.
static auto build_zero_rtt (const connection_id &dest_cid, const connection_id &src_cid, uint64_t packet_number, uint32_t version=quic_version::version_1) -> std::vector< uint8_t >
Build a 0-RTT packet header.
static auto build_retry (const connection_id &dest_cid, const connection_id &src_cid, const std::vector< uint8_t > &token, const std::array< uint8_t, 16 > &integrity_tag, uint32_t version=quic_version::version_1) -> std::vector< uint8_t >
Build a Retry packet header.
static auto build_short (const connection_id &dest_cid, uint64_t packet_number, bool key_phase=false, bool spin_bit=false) -> std::vector< uint8_t >
Build a Short Header (1-RTT) packet.
static auto build (const long_header &header) -> std::vector< uint8_t >
Build a long header from a header structure.
static auto build (const short_header &header) -> std::vector< uint8_t >
Build a short header from a header structure.
Static Private Member Functions
static void append_bytes (std::vector< uint8_t > &buffer, std::span< const uint8_t > data)
Helper to append bytes to buffer.
Detailed Description
Builder for QUIC packet headers (RFC 9000 Section 17)
Builds raw bytes from QUIC packet header structures. Note that header protection must be applied after building.
Definition at line 299 of file packet.h.
Member Function Documentation
append_bytes()
void kcenon::network::protocols::quic::packet_builder::append_bytes (std::vector< uint8_t > & buffer, std::span< const uint8_t > data) static private
Helper to append bytes to buffer.
Definition at line 417 of file packet.cpp.
{
    buffer.insert(buffer.end(), data.begin(), data.end());
}
build() [1/2]
auto kcenon::network::protocols::quic::packet_builder::build (const long_header & header) -> std::vector<uint8_t> static nodiscard
Build a long header from a header structure.
Parameters
header Long header structure
Returns
Serialized header bytes
Definition at line 611 of file packet.cpp.
{
    auto ptype = header.type();
    switch (ptype)
    {
        case packet_type::initial:
            return build_initial(header.dest_conn_id, header.src_conn_id,
                                 header.token, header.packet_number, header.version);
        case packet_type::handshake:
            return build_handshake(header.dest_conn_id, header.src_conn_id,
                                   header.packet_number, header.version);
        case packet_type::zero_rtt:
            return build_zero_rtt(header.dest_conn_id, header.src_conn_id,
                                  header.packet_number, header.version);
        case packet_type::retry:
            return build_retry(header.dest_conn_id, header.src_conn_id,
                               header.token, header.retry_integrity_tag, header.version);
        default:
            return {};
    }
}
References kcenon::network::protocols::quic::handshake, kcenon::network::protocols::quic::initial, kcenon::network::protocols::quic::retry, and kcenon::network::protocols::quic::zero_rtt.
build() [2/2]
auto kcenon::network::protocols::quic::packet_builder::build (const short_header & header) -> std::vector<uint8_t> static nodiscard
Build a short header from a header structure.
Parameters
header Short header structure
Returns
Serialized header bytes
Definition at line 633 of file packet.cpp.
{
    return build_short(header.dest_conn_id, header.packet_number,
                       header.key_phase(), header.spin_bit());
}
build_handshake()
auto kcenon::network::protocols::quic::packet_builder::build_handshake (const connection_id & dest_cid, const connection_id & src_cid, uint64_t packet_number, uint32_t version = quic_version::version_1) -> std::vector<uint8_t> static nodiscard
Build a Handshake packet header.
Parameters
dest_cid Destination Connection ID
src_cid Source Connection ID
packet_number Packet number
version QUIC version (default: version 1)
Returns
Serialized header bytes
Definition at line 467 of file packet.cpp.
{
    std::vector<uint8_t> buffer;
    size_t pn_len = packet_number::encoded_length(packet_num, 0);
    // First byte: Long header (1) + Fixed bit (1) + Type (10) + Reserved (00) + PN Length
    uint8_t first_byte = header_form_long | fixed_bit |
                         (static_cast<uint8_t>(packet_type::handshake) << long_packet_type_shift) |
                         static_cast<uint8_t>(pn_len - 1);
    buffer.push_back(first_byte);
    // Version
    buffer.push_back(static_cast<uint8_t>(version >> 24));
    buffer.push_back(static_cast<uint8_t>(version >> 16));
    buffer.push_back(static_cast<uint8_t>(version >> 8));
    buffer.push_back(static_cast<uint8_t>(version));
    // DCID
    buffer.push_back(static_cast<uint8_t>(dest_cid.length()));
    append_bytes(buffer, dest_cid.data());
    // SCID
    buffer.push_back(static_cast<uint8_t>(src_cid.length()));
    append_bytes(buffer, src_cid.data());
    // Packet number
    auto [pn_bytes, _] = packet_number::encode(packet_num, 0);
    append_bytes(buffer, pn_bytes);
    return buffer;
}
References kcenon::network::protocols::quic::packet_number::encode(), kcenon::network::protocols::quic::packet_number::encoded_length(), kcenon::network::protocols::quic::handshake, and kcenon::network::version().
Referenced by kcenon::network::protocols::quic::connection::build_packet(), and kcenon::network::internal::quic_socket::send_packet().
build_initial()
auto kcenon::network::protocols::quic::packet_builder::build_initial (const connection_id & dest_cid, const connection_id & src_cid, const std::vector< uint8_t > & token, uint64_t packet_number, uint32_t version = quic_version::version_1) -> std::vector<uint8_t> static nodiscard
Build an Initial packet header.
Parameters
dest_cid Destination Connection ID
src_cid Source Connection ID
token Token for address validation (empty for client initial)
packet_number Packet number
version QUIC version (default: version 1)
Returns
Serialized header bytes
Definition at line 423 of file packet.cpp.
{
    std::vector<uint8_t> buffer;
    // Calculate packet number length
    size_t pn_len = packet_number::encoded_length(packet_num, 0);
    // First byte: Long header (1) + Fixed bit (1) + Type (00) + Reserved (00) + PN Length
    uint8_t first_byte = header_form_long | fixed_bit |
                         (static_cast<uint8_t>(packet_type::initial) << long_packet_type_shift) |
                         static_cast<uint8_t>(pn_len - 1);
    buffer.push_back(first_byte);
    // Version (4 bytes, big-endian)
    buffer.push_back(static_cast<uint8_t>(version >> 24));
    buffer.push_back(static_cast<uint8_t>(version >> 16));
    buffer.push_back(static_cast<uint8_t>(version >> 8));
    buffer.push_back(static_cast<uint8_t>(version));
    // DCID Length + DCID
    buffer.push_back(static_cast<uint8_t>(dest_cid.length()));
    append_bytes(buffer, dest_cid.data());
    // SCID Length + SCID
    buffer.push_back(static_cast<uint8_t>(src_cid.length()));
    append_bytes(buffer, src_cid.data());
    // Token Length (varint) + Token
    auto token_len_encoded = varint::encode(token.size());
    append_bytes(buffer, token_len_encoded);
    append_bytes(buffer, token);
    // Packet number (placeholder - actual encoding done separately)
    auto [pn_bytes, _] = packet_number::encode(packet_num, 0);
    append_bytes(buffer, pn_bytes);
    return buffer;
}
References kcenon::network::protocols::quic::packet_number::encode(), kcenon::network::protocols::quic::varint::encode(), kcenon::network::protocols::quic::packet_number::encoded_length(), kcenon::network::protocols::quic::initial, and kcenon::network::version().
Referenced by kcenon::network::protocols::quic::connection::build_packet(), and kcenon::network::internal::quic_socket::send_packet().
build_retry()
auto kcenon::network::protocols::quic::packet_builder::build_retry (const connection_id & dest_cid, const connection_id & src_cid, const std::vector< uint8_t > & token, const std::array< uint8_t, 16 > & integrity_tag, uint32_t version = quic_version::version_1) -> std::vector<uint8_t> static nodiscard
Build a Retry packet header.
Parameters
dest_cid Destination Connection ID
src_cid Source Connection ID
token Retry token
integrity_tag Retry Integrity Tag (16 bytes)
version QUIC version (default: version 1)
Returns
Serialized header bytes
Definition at line 541 of file packet.cpp.
{
    std::vector<uint8_t> buffer;
    // First byte: Long header (1) + Fixed bit (1) + Type (11) + Unused (0000)
    uint8_t first_byte = header_form_long | fixed_bit |
                         (static_cast<uint8_t>(packet_type::retry) << long_packet_type_shift);
    buffer.push_back(first_byte);
    // Version
    buffer.push_back(static_cast<uint8_t>(version >> 24));
    buffer.push_back(static_cast<uint8_t>(version >> 16));
    buffer.push_back(static_cast<uint8_t>(version >> 8));
    buffer.push_back(static_cast<uint8_t>(version));
    // DCID
    buffer.push_back(static_cast<uint8_t>(dest_cid.length()));
    append_bytes(buffer, dest_cid.data());
    // SCID
    buffer.push_back(static_cast<uint8_t>(src_cid.length()));
    append_bytes(buffer, src_cid.data());
    // Retry Token
    append_bytes(buffer, token);
    // Retry Integrity Tag
    buffer.insert(buffer.end(), integrity_tag.begin(), integrity_tag.end());
    return buffer;
}
References kcenon::network::protocols::quic::retry, and kcenon::network::version().
build_short()
auto kcenon::network::protocols::quic::packet_builder::build_short (const connection_id & dest_cid, uint64_t packet_number, bool key_phase = false, bool spin_bit = false) -> std::vector<uint8_t> static nodiscard
Build a Short Header (1-RTT) packet.
Parameters
dest_cid Destination Connection ID
packet_number Packet number
key_phase Key phase bit
spin_bit Spin bit for latency measurement
Returns
Serialized header bytes
Definition at line 578 of file packet.cpp.
{
    std::vector<uint8_t> buffer;
    size_t pn_len = packet_number::encoded_length(packet_num, 0);
    // First byte: Short header (0) + Fixed bit (1) + Spin + Reserved (00) + Key Phase + PN Length
    uint8_t first_byte = fixed_bit;  // Header form = 0
    if (spin_bit)
    {
        first_byte |= spin_bit_mask;
    }
    if (key_phase)
    {
        first_byte |= key_phase_mask;
    }
    first_byte |= static_cast<uint8_t>(pn_len - 1);
    buffer.push_back(first_byte);
    // DCID (no length field for short header)
    append_bytes(buffer, dest_cid.data());
    // Packet number
    auto [pn_bytes, _] = packet_number::encode(packet_num, 0);
    append_bytes(buffer, pn_bytes);
    return buffer;
}
References kcenon::network::protocols::quic::packet_number::encode(), and kcenon::network::protocols::quic::packet_number::encoded_length().
Referenced by kcenon::network::protocols::quic::connection::build_packet(), and kcenon::network::internal::quic_socket::send_packet().
build_zero_rtt()
auto kcenon::network::protocols::quic::packet_builder::build_zero_rtt (const connection_id & dest_cid, const connection_id & src_cid, uint64_t packet_number, uint32_t version = quic_version::version_1) -> std::vector<uint8_t> static nodiscard
Build a 0-RTT packet header.
Parameters
dest_cid Destination Connection ID
src_cid Source Connection ID
packet_number Packet number
version QUIC version (default: version 1)
Returns
Serialized header bytes
Definition at line 504 of file packet.cpp.
{
    std::vector<uint8_t> buffer;
    size_t pn_len = packet_number::encoded_length(packet_num, 0);
    // First byte: Long header (1) + Fixed bit (1) + Type (01) + Reserved (00) + PN Length
    uint8_t first_byte = header_form_long | fixed_bit |
                         (static_cast<uint8_t>(packet_type::zero_rtt) << long_packet_type_shift) |
                         static_cast<uint8_t>(pn_len - 1);
    buffer.push_back(first_byte);
    // Version
    buffer.push_back(static_cast<uint8_t>(version >> 24));
    buffer.push_back(static_cast<uint8_t>(version >> 16));
    buffer.push_back(static_cast<uint8_t>(version >> 8));
    buffer.push_back(static_cast<uint8_t>(version));
    // DCID
    buffer.push_back(static_cast<uint8_t>(dest_cid.length()));
    append_bytes(buffer, dest_cid.data());
    // SCID
    buffer.push_back(static_cast<uint8_t>(src_cid.length()));
    append_bytes(buffer, src_cid.data());
    // Packet number
    auto [pn_bytes, _] = packet_number::encode(packet_num, 0);
    append_bytes(buffer, pn_bytes);
    return buffer;
}
References kcenon::network::protocols::quic::packet_number::encode(), kcenon::network::protocols::quic::packet_number::encoded_length(), kcenon::network::version(), and kcenon::network::protocols::quic::zero_rtt.
The documentation for this class was generated from the following files:
src/internal/protocols/quic/packet.h
src/protocols/quic/packet.cpp