Network System: kcenon::network::core::unified_session_manager Class Reference
kcenon::network::core::unified_session_manager Class Reference
Type-erased session manager that handles any session type.
#include <unified_session_manager.h>
Classes
class impl
PIMPL implementation hiding all template-related code.
struct stats
Comprehensive session manager statistics.
Public Member Functions
unified_session_manager ()
Constructs a unified session manager with default configuration.
unified_session_manager (const unified_session_config &config)
Constructs a unified session manager with custom configuration.
~unified_session_manager ()
unified_session_manager (const unified_session_manager &)=delete
unified_session_manager & operator= (const unified_session_manager &)=delete
unified_session_manager (unified_session_manager &&)=delete
unified_session_manager & operator= (unified_session_manager &&)=delete
auto can_accept_connection () const -> bool
Check if new connection can be accepted.
auto is_backpressure_active () const -> bool
Check if backpressure should be applied.
template<typename SessionType >
auto add_session (std::shared_ptr< SessionType > session, const std::string &session_id="") -> bool
Add a session using type erasure.
auto add_session (session_handle handle, const std::string &session_id="") -> bool
Add a pre-wrapped session_handle.
template<typename SessionType >
auto add_session_with_id (std::shared_ptr< SessionType > session, const std::string &session_id="") -> std::string
Add a session and return the assigned ID.
auto remove_session (const std::string &session_id) -> bool
Remove session by ID.
auto get_session (const std::string &session_id) -> session_handle *
Get session handle by ID (non-owning reference)
auto get_session (const std::string &session_id) const -> const session_handle *
Get session handle by ID (const version)
auto with_session (const std::string &session_id, const std::function< void(session_handle &)> &callback) -> bool
Execute a callback with a session (safer than get_session)
auto has_session (const std::string &session_id) const -> bool
Check if a session exists.
auto get_all_session_ids () const -> std::vector< std::string >
Get all session IDs.
auto for_each (const std::function< void(session_handle &)> &callback) -> void
Execute a callback for each session.
auto for_each (const std::function< void(const session_handle &)> &callback) const -> void
Execute a callback for each session (const version)
auto broadcast (std::vector< uint8_t > data) -> size_t
Broadcast data to all connected sessions.
auto update_activity (const std::string &session_id) -> bool
Update activity timestamp for a session.
auto cleanup_idle_sessions () -> size_t
Cleanup idle sessions that exceeded idle_timeout.
auto clear_all_sessions () -> void
Clear all sessions.
auto stop_all_sessions () -> void
Stop all sessions (alias for clear_all_sessions)
auto get_session_count () const -> size_t
Get current session count.
auto get_total_accepted () const -> uint64_t
Get total accepted connections.
auto get_total_rejected () const -> uint64_t
Get total rejected connections.
auto get_total_cleaned_up () const -> uint64_t
Get total cleaned up sessions.
auto get_utilization () const -> double
Get current session utilization.
auto set_max_sessions (size_t max_sessions) -> void
Set maximum sessions.
auto get_config () const -> const unified_session_config &
Get current configuration.
auto get_stats () const -> stats
Get comprehensive statistics.
Static Public Member Functions
static auto generate_id (const std::string &prefix="session_") -> std::string
Generate a unique session ID.
Private Member Functions
auto add_session_impl (session_handle handle, const std::string &session_id) -> bool
auto add_session_with_id_impl (session_handle handle, const std::string &session_id) -> std::string
auto increment_rejected () -> void
Private Attributes
std::unique_ptr< impl > impl_
Detailed Description
Type-erased session manager that handles any session type.
This class replaces the template-based session_manager_base<SessionType> with a single, non-template implementation using Type Erasure.
Benefits
Reduced compilation time: No template instantiation in user code
Smaller binary size: Single implementation instead of per-type
Simpler API: Single class handles all session types
Heterogeneous storage: Different session types in same manager
Usage Example
unified_session_manager manager;
// Add any session type
auto tcp = std::make_shared<tcp_session>(...);
manager.add_session(tcp, "tcp_1");
auto ws = std::make_shared<ws_session>(...);
manager.add_session(ws, "ws_1");
// Type recovery when needed
if (auto handle = manager.get_session("tcp_1")) {
    if (auto* tcp_ptr = handle->as<tcp_session>()) {
        tcp_ptr->set_tcp_nodelay(true);  // Protocol-specific
    }
}
// Iteration over all sessions
manager.for_each([](session_handle& handle) {
    if (handle.is_connected()) {
        handle.send(make_ping_packet());
    }
});
Thread Safety
All methods are thread-safe using shared_mutex for concurrent reads and exclusive writes.
See also
session_handle
session_concept
Definition at line 84 of file unified_session_manager.h.
Constructor & Destructor Documentation
unified_session_manager() [1/4]
kcenon::network::core::unified_session_manager::unified_session_manager ()
Constructs a unified session manager with default configuration.
Definition at line 328 of file unified_session_manager.cpp.
    : impl_(std::make_unique<impl>(unified_session_config{})) {}
unified_session_manager() [2/4]
kcenon::network::core::unified_session_manager::unified_session_manager (const unified_session_config & config) explicit
Constructs a unified session manager with custom configuration.
Parameters
config Session management configuration
Definition at line 331 of file unified_session_manager.cpp.
    : impl_(std::make_unique<impl>(config)) {}
References config.
~unified_session_manager()
kcenon::network::core::unified_session_manager::~unified_session_manager () default
unified_session_manager() [3/4]
kcenon::network::core::unified_session_manager::unified_session_manager (const unified_session_manager &) delete
unified_session_manager() [4/4]
kcenon::network::core::unified_session_manager::unified_session_manager (unified_session_manager &&) delete
Member Function Documentation
add_session() [1/2]
auto kcenon::network::core::unified_session_manager::add_session (session_handle handle, const std::string & session_id = "") -> bool
Add a pre-wrapped session_handle.
Parameters
handle The session handle to add
session_id Session ID (auto-generated if empty)
Returns
true if added, false if rejected
Definition at line 344 of file unified_session_manager.cpp.
{
    return impl_->add_session(std::move(handle), session_id);
}
add_session() [2/2]
template<typename SessionType > auto kcenon::network::core::unified_session_manager::add_session (std::shared_ptr< SessionType > session, const std::string & session_id = "") -> bool inline
Add a session using type erasure.
Template Parameters
SessionType The concrete session type
Parameters
session Shared pointer to the session
session_id Session ID (auto-generated if empty)
Returns
true if added, false if rejected (limit reached)
This template method is the entry point that converts a concrete session type into the type-erased session_handle.
Definition at line 136 of file unified_session_manager.h.
{
        if (!can_accept_connection()) {
            increment_rejected();
            return false;
        }
        auto handle = session_handle(std::move(session));
        return add_session_impl(std::move(handle), session_id);
    }
References add_session_impl(), can_accept_connection(), and increment_rejected().
add_session_impl()
auto kcenon::network::core::unified_session_manager::add_session_impl (session_handle handle, const std::string & session_id) -> bool private
Definition at line 448 of file unified_session_manager.cpp.
            {
    return impl_->add_session(std::move(handle), session_id);
}
Referenced by add_session().
add_session_with_id()
template<typename SessionType > auto kcenon::network::core::unified_session_manager::add_session_with_id (std::shared_ptr< SessionType > session, const std::string & session_id = "") -> std::string inline
Add a session and return the assigned ID.
Template Parameters
SessionType The concrete session type
Parameters
session Shared pointer to the session
session_id Session ID (auto-generated if empty)
Returns
Session ID if added, empty string if rejected
Definition at line 164 of file unified_session_manager.h.
{
        if (!can_accept_connection()) {
            increment_rejected();
            return "";
        }
        auto handle = session_handle(std::move(session));
        return add_session_with_id_impl(std::move(handle), session_id);
    }
References add_session_with_id_impl(), can_accept_connection(), and increment_rejected().
add_session_with_id_impl()
auto kcenon::network::core::unified_session_manager::add_session_with_id_impl (session_handle handle, const std::string & session_id) -> std::string private
Definition at line 454 of file unified_session_manager.cpp.
{
    return impl_->add_session_with_id(std::move(handle), session_id);
}
Referenced by add_session_with_id().
broadcast()
auto kcenon::network::core::unified_session_manager::broadcast (std::vector< uint8_t > data) -> size_t
Broadcast data to all connected sessions.
Parameters
data Data to send (will be moved)
Returns
Number of sessions that received the data
Definition at line 389 of file unified_session_manager.cpp.
{
    return impl_->broadcast(std::move(data));
}
can_accept_connection()
auto kcenon::network::core::unified_session_manager::can_accept_connection () const -> bool nodiscard
Check if new connection can be accepted.
Returns
true if under max_sessions limit
Definition at line 336 of file unified_session_manager.cpp.
{
    return impl_->can_accept_connection();
}
References kcenon::network::core::unified_session_manager::impl::can_accept_connection(), and impl_.
Referenced by add_session(), and add_session_with_id().
cleanup_idle_sessions()
auto kcenon::network::core::unified_session_manager::cleanup_idle_sessions () -> size_t
Cleanup idle sessions that exceeded idle_timeout.
Returns
Number of sessions cleaned up
Definition at line 398 of file unified_session_manager.cpp.
{
    return impl_->cleanup_idle_sessions();
}
clear_all_sessions()
auto kcenon::network::core::unified_session_manager::clear_all_sessions () -> void
Clear all sessions.
Calls stop() on each session before removal.
Definition at line 402 of file unified_session_manager.cpp.
{
    impl_->clear_all_sessions();
}
for_each() [1/2]
auto kcenon::network::core::unified_session_manager::for_each (const std::function< void(const session_handle &)> & callback) const -> void
Execute a callback for each session (const version)
Parameters
callback Function to execute with each session handle
Definition at line 384 of file unified_session_manager.cpp.
{
    impl_->for_each_const(callback);
}
for_each() [2/2]
auto kcenon::network::core::unified_session_manager::for_each (const std::function< void(session_handle &)> & callback) -> void
Execute a callback for each session.
Parameters
callback Function to execute with each session handle
Callback receives a mutable reference to allow session operations. Iteration is performed under read lock for concurrent safety.
Definition at line 379 of file unified_session_manager.cpp.
{
    impl_->for_each_mutable(callback);
}
generate_id()
auto kcenon::network::core::unified_session_manager::generate_id (const std::string & prefix = "session_") -> std::string static
Generate a unique session ID.
Parameters
prefix Optional prefix for the ID
Returns
Generated unique ID
Definition at line 443 of file unified_session_manager.cpp.
                 {
    return impl::generate_id(prefix);
}
get_all_session_ids()
auto kcenon::network::core::unified_session_manager::get_all_session_ids () const -> std::vector<std::string> nodiscard
Get all session IDs.
Returns
Vector of session IDs
Definition at line 374 of file unified_session_manager.cpp.
{
    return impl_->get_all_session_ids();
}
References kcenon::network::core::unified_session_manager::impl::get_all_session_ids(), and impl_.
get_config()
auto kcenon::network::core::unified_session_manager::get_config () const -> const unified_session_config& nodiscard
Get current configuration.
Returns
Reference to session configuration
Definition at line 434 of file unified_session_manager.cpp.
{
    return impl_->get_config();
}
References kcenon::network::core::unified_session_manager::impl::get_config(), and impl_.
get_session() [1/2]
auto kcenon::network::core::unified_session_manager::get_session (const std::string & session_id) -> session_handle* nodiscard
Get session handle by ID (non-owning reference)
Parameters
session_id Session ID to lookup
Returns
Pointer to session_handle, or nullptr if not found
The returned pointer is valid only while the session exists in the manager. Use with_session() for safer access patterns.
Definition at line 353 of file unified_session_manager.cpp.
                       {
    return impl_->get_session(session_id);
}
get_session() [2/2]
auto kcenon::network::core::unified_session_manager::get_session (const std::string & session_id) const -> const session_handle* nodiscard
Get session handle by ID (const version)
Parameters
session_id Session ID to lookup
Returns
Const pointer to session_handle, or nullptr if not found
Definition at line 358 of file unified_session_manager.cpp.
{
    return impl_->get_session(session_id);
}
get_session_count()
auto kcenon::network::core::unified_session_manager::get_session_count () const -> size_t nodiscard
Get current session count.
Returns
Number of active sessions
Definition at line 410 of file unified_session_manager.cpp.
{
    return impl_->get_session_count();
}
References kcenon::network::core::unified_session_manager::impl::get_session_count(), and impl_.
get_stats()
auto kcenon::network::core::unified_session_manager::get_stats () const -> stats nodiscard
Get comprehensive statistics.
Returns
Stats struct with all metrics
Definition at line 439 of file unified_session_manager.cpp.
{
    return impl_->get_stats();
}
References kcenon::network::core::unified_session_manager::impl::get_stats(), and impl_.
get_total_accepted()
auto kcenon::network::core::unified_session_manager::get_total_accepted () const -> uint64_t nodiscard
Get total accepted connections.
Returns
Total number of accepted connections
Definition at line 414 of file unified_session_manager.cpp.
{
    return impl_->get_total_accepted();
}
References kcenon::network::core::unified_session_manager::impl::get_total_accepted(), and impl_.
get_total_cleaned_up()
auto kcenon::network::core::unified_session_manager::get_total_cleaned_up () const -> uint64_t nodiscard
Get total cleaned up sessions.
Returns
Total sessions removed due to idle timeout
Definition at line 422 of file unified_session_manager.cpp.
{
    return impl_->get_total_cleaned_up();
}
References kcenon::network::core::unified_session_manager::impl::get_total_cleaned_up(), and impl_.
get_total_rejected()
auto kcenon::network::core::unified_session_manager::get_total_rejected () const -> uint64_t nodiscard
Get total rejected connections.
Returns
Total number of rejected connections
Definition at line 418 of file unified_session_manager.cpp.
{
    return impl_->get_total_rejected();
}
References kcenon::network::core::unified_session_manager::impl::get_total_rejected(), and impl_.
get_utilization()
auto kcenon::network::core::unified_session_manager::get_utilization () const -> double nodiscard
Get current session utilization.
Returns
Utilization ratio (0.0 to 1.0)
Definition at line 426 of file unified_session_manager.cpp.
{
    return impl_->get_utilization();
}
References kcenon::network::core::unified_session_manager::impl::get_utilization(), and impl_.
has_session()
auto kcenon::network::core::unified_session_manager::has_session (const std::string & session_id) const -> bool nodiscard
Check if a session exists.
Parameters
session_id Session ID to check
Returns
true if session exists
Definition at line 369 of file unified_session_manager.cpp.
            {
    return impl_->has_session(session_id);
}
increment_rejected()
auto kcenon::network::core::unified_session_manager::increment_rejected () -> void private
Definition at line 459 of file unified_session_manager.cpp.
{
    impl_->increment_rejected();
}
Referenced by add_session(), and add_session_with_id().
is_backpressure_active()
auto kcenon::network::core::unified_session_manager::is_backpressure_active () const -> bool nodiscard
Check if backpressure should be applied.
Returns
true if session count exceeds backpressure threshold
Definition at line 340 of file unified_session_manager.cpp.
{
    return impl_->is_backpressure_active();
}
References impl_, and kcenon::network::core::unified_session_manager::impl::is_backpressure_active().
operator=() [1/2]
unified_session_manager & kcenon::network::core::unified_session_manager::operator= (const unified_session_manager &) delete
operator=() [2/2]
unified_session_manager & kcenon::network::core::unified_session_manager::operator= (unified_session_manager &&) delete
remove_session()
auto kcenon::network::core::unified_session_manager::remove_session (const std::string & session_id) -> bool
Remove session by ID.
Parameters
session_id Session ID to remove
Returns
true if removed, false if not found
Definition at line 349 of file unified_session_manager.cpp.
{
    return impl_->remove_session(session_id);
}
set_max_sessions()
auto kcenon::network::core::unified_session_manager::set_max_sessions (size_t max_sessions) -> void
Set maximum sessions.
Parameters
max_sessions New maximum session limit
Definition at line 430 of file unified_session_manager.cpp.
{
    impl_->set_max_sessions(max_sessions);
}
stop_all_sessions()
auto kcenon::network::core::unified_session_manager::stop_all_sessions () -> void
Stop all sessions (alias for clear_all_sessions)
Definition at line 406 of file unified_session_manager.cpp.
{
    impl_->clear_all_sessions();
}
update_activity()
auto kcenon::network::core::unified_session_manager::update_activity (const std::string & session_id) -> bool
Update activity timestamp for a session.
Parameters
session_id Session ID to update
Returns
true if session found and updated
Definition at line 393 of file unified_session_manager.cpp.
            {
    return impl_->update_activity(session_id);
}
with_session()
auto kcenon::network::core::unified_session_manager::with_session (const std::string & session_id, const std::function< void(session_handle &)> & callback) -> bool
Execute a callback with a session (safer than get_session)
Parameters
session_id Session ID to lookup
callback Function to execute with the session
Returns
true if session found and callback executed
This method is safer than get_session() because it holds the lock during callback execution, preventing the session from being removed.
Definition at line 363 of file unified_session_manager.cpp.
{
    return impl_->with_session(session_id, callback);
}
Member Data Documentation
impl_
std::unique_ptr<impl> kcenon::network::core::unified_session_manager::impl_ private
Definition at line 373 of file unified_session_manager.h.
Referenced by can_accept_connection(), get_all_session_ids(), get_config(), get_session_count(), get_stats(), get_total_accepted(), get_total_cleaned_up(), get_total_rejected(), get_utilization(), and is_backpressure_active().
The documentation for this class was generated from the following files:
src/internal/core/unified_session_manager.h
src/core/unified_session_manager.cpp