Network System: kcenon::network::integration::messaging_bridge Class Reference
kcenon::network::integration::messaging_bridge Class Reference
Bridge class for messaging_system compatibility implementing INetworkBridge.
#include <messaging_bridge.h>
Classes
class impl
Public Member Functions
messaging_bridge ()
Default constructor.
~messaging_bridge () override
Destructor.
VoidResult initialize (const BridgeConfig &config) override
Initialize the bridge with configuration.
VoidResult shutdown () override
Shutdown the bridge.
bool is_initialized () const override
Check if the bridge is initialized.
BridgeMetrics get_metrics () const override
Get current metrics.
std::shared_ptr< kcenon::network::core::messaging_server > create_server (const std::string &server_id)
Create a messaging server with messaging_system compatible API.
std::shared_ptr< kcenon::network::core::messaging_client > create_client (const std::string &client_id)
Create a messaging client with messaging_system compatible API.
void set_thread_pool_interface (std::shared_ptr< thread_pool_interface > pool)
Set thread pool using the integration interface.
std::shared_ptr< thread_pool_interface > get_thread_pool_interface () const
Get the thread pool interface.
void reset_metrics ()
Reset performance metrics.
Public Member Functions inherited from kcenon::network::integration::INetworkBridge
virtual ~INetworkBridge ()=default
Private Attributes
std::unique_ptr< impl > pimpl_
Detailed Description
Bridge class for messaging_system compatibility implementing INetworkBridge.
This class provides a compatibility layer that allows existing messaging_system code to work with the new independent network_system without modification.
Lifecycle:
Create using constructor or factory methods
Call initialize() with configuration
Use create_server() and create_client() to create messaging components
Call shutdown() before destruction
Thread Safety:
initialize() and shutdown() are not thread-safe (single-threaded usage)
get_metrics() is thread-safe for concurrent queries
create_server() and create_client() are thread-safe after initialization
Definition at line 67 of file messaging_bridge.h.
Constructor & Destructor Documentation
messaging_bridge()
kcenon::network::integration::messaging_bridge::messaging_bridge ()
Default constructor.
Definition at line 63 of file messaging_bridge.cpp.
                                   : pimpl_(std::make_unique<impl>()) {
    pimpl_->metrics_.start_time = std::chrono::steady_clock::now();
}
References kcenon::network::integration::messaging_bridge::impl::metrics_, pimpl_, and kcenon::network::integration::messaging_bridge::impl::internal_metrics::start_time.
~messaging_bridge()
kcenon::network::integration::messaging_bridge::~messaging_bridge () override
Destructor.
Automatically calls shutdown() if initialized
Definition at line 67 of file messaging_bridge.cpp.
{
    if (is_initialized()) {
        shutdown();
    }
}
References is_initialized(), and shutdown().
Member Function Documentation
create_client()
std::shared_ptr< kcenon::network::core::messaging_client > kcenon::network::integration::messaging_bridge::create_client (const std::string & client_id)
Create a messaging client with messaging_system compatible API.
Parameters
client_id Unique identifier for the client
Returns
Shared pointer to the created client
Definition at line 144 of file messaging_bridge.cpp.
  {
    return std::make_shared<kcenon::network::core::messaging_client>(client_id);
}
create_server()
std::shared_ptr< kcenon::network::core::messaging_server > kcenon::network::integration::messaging_bridge::create_server (const std::string & server_id)
Create a messaging server with messaging_system compatible API.
Parameters
server_id Unique identifier for the server
Returns
Shared pointer to the created server
Definition at line 138 of file messaging_bridge.cpp.
  {
    return std::make_shared<kcenon::network::core::messaging_server>(server_id);
}
get_metrics()
BridgeMetrics kcenon::network::integration::messaging_bridge::get_metrics () const override virtual
Get current metrics.
Returns
Bridge metrics including messaging statistics
Custom Metrics:
"messages_sent": Total messages sent
"messages_received": Total messages received
"bytes_sent": Total bytes sent
"bytes_received": Total bytes received
"connections_active": Number of active connections
"avg_latency_ms": Average message latency in milliseconds
Thread Safety: Safe to call concurrently
Implements kcenon::network::integration::INetworkBridge.
Definition at line 120 of file messaging_bridge.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->metrics_mutex_);
    // Update bridge metrics from performance metrics
    pimpl_->bridge_metrics_.is_healthy = pimpl_->initialized_.load();
    pimpl_->bridge_metrics_.last_activity = std::chrono::steady_clock::now();
    pimpl_->bridge_metrics_.custom_metrics["messages_sent"] = static_cast<double>(pimpl_->metrics_.messages_sent);
    pimpl_->bridge_metrics_.custom_metrics["messages_received"] = static_cast<double>(pimpl_->metrics_.messages_received);
    pimpl_->bridge_metrics_.custom_metrics["bytes_sent"] = static_cast<double>(pimpl_->metrics_.bytes_sent);
    pimpl_->bridge_metrics_.custom_metrics["bytes_received"] = static_cast<double>(pimpl_->metrics_.bytes_received);
    pimpl_->bridge_metrics_.custom_metrics["connections_active"] = static_cast<double>(pimpl_->metrics_.connections_active);
    pimpl_->bridge_metrics_.custom_metrics["avg_latency_ms"] = static_cast<double>(pimpl_->metrics_.avg_latency.count());
    return pimpl_->bridge_metrics_;
}
References kcenon::network::integration::messaging_bridge::impl::internal_metrics::avg_latency, kcenon::network::integration::messaging_bridge::impl::bridge_metrics_, kcenon::network::integration::messaging_bridge::impl::internal_metrics::bytes_received, kcenon::network::integration::messaging_bridge::impl::internal_metrics::bytes_sent, kcenon::network::integration::messaging_bridge::impl::internal_metrics::connections_active, kcenon::network::integration::BridgeMetrics::custom_metrics, kcenon::network::integration::messaging_bridge::impl::initialized_, kcenon::network::integration::BridgeMetrics::is_healthy, kcenon::network::integration::BridgeMetrics::last_activity, kcenon::network::integration::messaging_bridge::impl::internal_metrics::messages_received, kcenon::network::integration::messaging_bridge::impl::internal_metrics::messages_sent, kcenon::network::integration::messaging_bridge::impl::metrics_, kcenon::network::integration::messaging_bridge::impl::metrics_mutex_, and pimpl_.
get_thread_pool_interface()
std::shared_ptr< thread_pool_interface > kcenon::network::integration::messaging_bridge::get_thread_pool_interface () const
Get the thread pool interface.
Returns
Current thread pool interface
Definition at line 184 of file messaging_bridge.cpp.
{
    if (!pimpl_->thread_pool_interface_) {
        // Return the global thread integration manager's pool
        return thread_integration_manager::instance().get_thread_pool();
    }
    return pimpl_->thread_pool_interface_;
}
References kcenon::network::integration::thread_integration_manager::get_thread_pool(), kcenon::network::integration::thread_integration_manager::instance(), pimpl_, and kcenon::network::integration::messaging_bridge::impl::thread_pool_interface_.
initialize()
VoidResult kcenon::network::integration::messaging_bridge::initialize (const BridgeConfig & config) override virtual
Initialize the bridge with configuration.
Parameters
config Configuration parameters
Returns
ok() on success, error_info on failure
Configuration Properties:
"enabled": "true" or "false" (default: "true")
"server_id": Default server identifier (optional)
"client_id": Default client identifier (optional)
Error Conditions:
Already initialized
Invalid configuration
Example:
BridgeConfig config;
config.integration_name = "messaging_system";
config.properties["enabled"] = "true";
auto result = bridge->initialize(config);
if (result.is_err()) {
    std::cerr << "Init failed: " << result.error().message << std::endl;
}
Implements kcenon::network::integration::INetworkBridge.
Definition at line 75 of file messaging_bridge.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->metrics_mutex_);
    if (pimpl_->initialized_.load()) {
        return error_void(
            error_codes::common_errors::already_exists,
            "messaging_bridge already initialized",
            "messaging_bridge::initialize");
    }
    // Process configuration properties
    auto enabled_it = config.properties.find("enabled");
    if (enabled_it != config.properties.end() && enabled_it->second == "false") {
        return error_void(
            error_codes::common_errors::invalid_argument,
            "Bridge is disabled in configuration",
            "messaging_bridge::initialize");
    }
    // Initialize bridge metrics
    pimpl_->bridge_metrics_.is_healthy = true;
    pimpl_->bridge_metrics_.last_activity = std::chrono::steady_clock::now();
    pimpl_->bridge_metrics_.custom_metrics.clear();
    pimpl_->initialized_.store(true);
    return ok();
}
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::integration::messaging_bridge::impl::bridge_metrics_, config, kcenon::network::integration::BridgeMetrics::custom_metrics, kcenon::network::error_void(), kcenon::network::integration::messaging_bridge::impl::initialized_, kcenon::network::error_codes::common_errors::invalid_argument, kcenon::network::integration::BridgeMetrics::is_healthy, kcenon::network::integration::BridgeMetrics::last_activity, kcenon::network::integration::messaging_bridge::impl::metrics_mutex_, kcenon::network::ok(), and pimpl_.
is_initialized()
bool kcenon::network::integration::messaging_bridge::is_initialized () const override virtual
Check if the bridge is initialized.
Returns
true if initialized and ready, false otherwise
Implements kcenon::network::integration::INetworkBridge.
Definition at line 116 of file messaging_bridge.cpp.
{
    return pimpl_->initialized_.load();
}
References kcenon::network::integration::messaging_bridge::impl::initialized_, and pimpl_.
Referenced by ~messaging_bridge().
reset_metrics()
void kcenon::network::integration::messaging_bridge::reset_metrics ()
Reset performance metrics.
Definition at line 172 of file messaging_bridge.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->metrics_mutex_);
    pimpl_->metrics_ = impl::internal_metrics{};
    pimpl_->metrics_.start_time = std::chrono::steady_clock::now();
}
References kcenon::network::integration::messaging_bridge::impl::metrics_, kcenon::network::integration::messaging_bridge::impl::metrics_mutex_, pimpl_, and kcenon::network::integration::messaging_bridge::impl::internal_metrics::start_time.
set_thread_pool_interface()
void kcenon::network::integration::messaging_bridge::set_thread_pool_interface (std::shared_ptr< thread_pool_interface > pool)
Set thread pool using the integration interface.
Parameters
pool Thread pool interface implementation
Definition at line 178 of file messaging_bridge.cpp.
  {
    pimpl_->thread_pool_interface_ = pool;
}
References pimpl_, and kcenon::network::integration::messaging_bridge::impl::thread_pool_interface_.
shutdown()
VoidResult kcenon::network::integration::messaging_bridge::shutdown () override virtual
Shutdown the bridge.
Returns
ok() on success, error_info on failure
Shuts down the bridge and releases resources. This method is idempotent - multiple calls are safe.
Implements kcenon::network::integration::INetworkBridge.
Definition at line 103 of file messaging_bridge.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->metrics_mutex_);
    if (!pimpl_->initialized_.load()) {
        return ok(); // Already shut down, idempotent
    }
    pimpl_->initialized_.store(false);
    pimpl_->bridge_metrics_.is_healthy = false;
    return ok();
}
References kcenon::network::integration::messaging_bridge::impl::bridge_metrics_, kcenon::network::integration::messaging_bridge::impl::initialized_, kcenon::network::integration::BridgeMetrics::is_healthy, kcenon::network::integration::messaging_bridge::impl::metrics_mutex_, kcenon::network::ok(), and pimpl_.
Referenced by ~messaging_bridge().
Member Data Documentation
pimpl_
std::unique_ptr<impl> kcenon::network::integration::messaging_bridge::pimpl_ private
Definition at line 211 of file messaging_bridge.h.
Referenced by get_metrics(), get_thread_pool_interface(), initialize(), is_initialized(), messaging_bridge(), reset_metrics(), set_thread_pool_interface(), and shutdown().
The documentation for this class was generated from the following files:
src/internal/integration/messaging_bridge.h
src/integration/messaging_bridge.cpp