Network System: kcenon::network::protocols::quic::packet_protection Class Reference
kcenon::network::protocols::quic::packet_protection Class Reference
QUIC packet protection (encryption/decryption) (RFC 9001 Section 5)
#include <crypto.h>
Static Public Member Functions
static auto protect (const quic_keys &keys, std::span< const uint8_t > header, std::span< const uint8_t > payload, uint64_t packet_number) -> Result< std::vector< uint8_t > >
Protect (encrypt) a QUIC packet.
static auto unprotect (const quic_keys &keys, std::span< const uint8_t > packet, size_t header_length, uint64_t packet_number) -> Result< std::pair< std::vector< uint8_t >, std::vector< uint8_t > > >
Unprotect (decrypt) a QUIC packet.
static auto protect_header (const quic_keys &keys, std::span< uint8_t > header, size_t pn_offset, size_t pn_length, std::span< const uint8_t > sample) -> VoidResult
Apply header protection.
static auto unprotect_header (const quic_keys &keys, std::span< uint8_t > header, size_t pn_offset, std::span< const uint8_t > sample) -> Result< std::pair< uint8_t, size_t > >
Remove header protection.
static auto generate_hp_mask (std::span< const uint8_t > hp_key, std::span< const uint8_t > sample) -> Result< std::array< uint8_t, 5 > >
Generate header protection mask using AES-ECB.
Static Private Member Functions
static auto make_nonce (std::span< const uint8_t > iv, uint64_t packet_number) -> std::array< uint8_t, aead_iv_size >
Construct nonce from IV and packet number.
Detailed Description
QUIC packet protection (encryption/decryption) (RFC 9001 Section 5)
Provides AEAD encryption for packet payloads and header protection to prevent linkability attacks.
Definition at line 173 of file crypto.h.
Member Function Documentation
generate_hp_mask()
auto kcenon::network::protocols::quic::packet_protection::generate_hp_mask (std::span< const uint8_t > hp_key, std::span< const uint8_t > sample) -> Result<std::array<uint8_t, 5>> static
Generate header protection mask using AES-ECB.
Parameters
hp_key Header protection key
sample 16-byte sample from ciphertext
Returns
5-byte mask or error
Definition at line 626 of file crypto.cpp.
{
    if (sample.size() < hp_sample_size)
    {
        return error<std::array<uint8_t, 5>>(
            -1, "Sample too short for HP mask", "quic::packet_protection");
    }
    std::array<uint8_t, 16> mask_full{};
    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();
    if (!ctx)
    {
        return error<std::array<uint8_t, 5>>(
            -1, "Failed to create cipher context", "quic::packet_protection");
    }
    int ret = EVP_EncryptInit_ex(ctx, EVP_aes_128_ecb(), nullptr,
                                  hp_key.data(), nullptr);
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::array<uint8_t, 5>>(
            -1, "AES-ECB init failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    EVP_CIPHER_CTX_set_padding(ctx, 0);
    int len;
    ret = EVP_EncryptUpdate(ctx, mask_full.data(), &len,
                            sample.data(), hp_sample_size);
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::array<uint8_t, 5>>(
            -1, "AES-ECB encrypt failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    EVP_CIPHER_CTX_free(ctx);
    // Return first 5 bytes of the mask
    std::array<uint8_t, 5> mask{};
    std::copy(mask_full.begin(), mask_full.begin() + 5, mask.begin());
    return ok(std::move(mask));
}
References kcenon::network::protocols::quic::hp_sample_size, and kcenon::network::ok().
make_nonce()
auto kcenon::network::protocols::quic::packet_protection::make_nonce (std::span< const uint8_t > iv, uint64_t packet_number) -> std::array<uint8_t, aead_iv_size> static private
Construct nonce from IV and packet number.
Parameters
iv Initialization vector
packet_number Packet number
Returns
Nonce for AEAD
Definition at line 436 of file crypto.cpp.
{
    std::array<uint8_t, aead_iv_size> nonce{};
    std::copy(iv.begin(), iv.end(), nonce.begin());
    // XOR packet number into the rightmost bytes of the IV
    for (size_t i = 0; i < 8; ++i)
    {
        nonce[aead_iv_size - 1 - i] ^=
            static_cast<uint8_t>((packet_number >> (i * 8)) & 0xFF);
    }
    return nonce;
}
References kcenon::network::protocols::quic::aead_iv_size.
protect()
auto kcenon::network::protocols::quic::packet_protection::protect (const quic_keys & keys, std::span< const uint8_t > header, std::span< const uint8_t > payload, uint64_t packet_number) -> Result<std::vector<uint8_t>> static
Protect (encrypt) a QUIC packet.
Parameters
keys Encryption keys for the current level
header Packet header (will be used as AAD)
payload Plaintext payload to encrypt
packet_number Packet number (used for nonce derivation)
Returns
Protected packet (header + encrypted payload + tag) or error
Definition at line 453 of file crypto.cpp.
{
    auto nonce = make_nonce(keys.iv, packet_number);
    // Create output buffer: header + ciphertext + tag
    std::vector<uint8_t> output;
    output.reserve(header.size() + payload.size() + aead_tag_size);
    output.insert(output.end(), header.begin(), header.end());
    output.resize(output.size() + payload.size() + aead_tag_size);
    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();
    if (!ctx)
    {
        return error<std::vector<uint8_t>>(
            -1, "Failed to create cipher context", "quic::packet_protection");
    }
    int ret = EVP_EncryptInit_ex(ctx, EVP_aes_128_gcm(), nullptr,
                                  keys.key.data(), nonce.data());
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::vector<uint8_t>>(
            -1, "AES-GCM encrypt init failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    // Set AAD (header)
    int len;
    ret = EVP_EncryptUpdate(ctx, nullptr, &len, header.data(),
                            static_cast<int>(header.size()));
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::vector<uint8_t>>(
            -1, "AES-GCM AAD update failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    // Encrypt payload
    ret = EVP_EncryptUpdate(ctx, output.data() + header.size(), &len,
                            payload.data(), static_cast<int>(payload.size()));
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::vector<uint8_t>>(
            -1, "AES-GCM encrypt failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    int ciphertext_len = len;
    ret = EVP_EncryptFinal_ex(ctx, output.data() + header.size() + len, &len);
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::vector<uint8_t>>(
            -1, "AES-GCM encrypt final failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    ciphertext_len += len;
    // Get tag
    ret = EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_GET_TAG, aead_tag_size,
                              output.data() + header.size() + ciphertext_len);
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::vector<uint8_t>>(
            -1, "AES-GCM get tag failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    EVP_CIPHER_CTX_free(ctx);
    output.resize(header.size() + ciphertext_len + aead_tag_size);
    return ok(std::move(output));
}
References kcenon::network::protocols::quic::aead_tag_size, and kcenon::network::ok().
Referenced by kcenon::network::protocols::quic::connection::build_packet(), and kcenon::network::internal::quic_socket::send_packet().
protect_header()
auto kcenon::network::protocols::quic::packet_protection::protect_header (const quic_keys & keys, std::span< uint8_t > header, size_t pn_offset, size_t pn_length, std::span< const uint8_t > sample) -> VoidResult static
Apply header protection.
Parameters
keys Keys containing the HP key
header Header bytes (modified in place)
pn_offset Offset of packet number in header
pn_length Length of packet number (1-4)
sample Sample from encrypted payload (16 bytes)
Returns
Success or error
Definition at line 677 of file crypto.cpp.
{
    auto mask_result = generate_hp_mask(keys.hp_key, sample);
    if (mask_result.is_err())
    {
        return error_void(mask_result.error().code,
                         mask_result.error().message,
                         get_error_source(mask_result.error()));
    }
    auto& mask = mask_result.value();
    // Apply mask to first byte
    if ((header[0] & 0x80) != 0)
    {
        // Long header: mask lower 4 bits
        header[0] ^= (mask[0] & 0x0F);
    }
    else
    {
        // Short header: mask lower 5 bits
        header[0] ^= (mask[0] & 0x1F);
    }
    // Apply mask to packet number
    for (size_t i = 0; i < pn_length; ++i)
    {
        header[pn_offset + i] ^= mask[1 + i];
    }
    return ok();
}
References kcenon::network::error_void(), kcenon::network::get_error_source(), and kcenon::network::ok().
unprotect()
auto kcenon::network::protocols::quic::packet_protection::unprotect (const quic_keys & keys, std::span< const uint8_t > packet, size_t header_length, uint64_t packet_number) -> Result<std::pair<std::vector<uint8_t>, std::vector<uint8_t>>> static
Unprotect (decrypt) a QUIC packet.
Parameters
keys Decryption keys for the current level
packet Full packet data (header + encrypted payload + tag)
header_length Length of the header (including packet number)
packet_number Decoded packet number
Returns
Pair of (header, decrypted payload) or error
Definition at line 536 of file crypto.cpp.
{
    if (packet.size() < header_length + aead_tag_size)
    {
        return error<std::pair<std::vector<uint8_t>, std::vector<uint8_t>>>(
            -1, "Packet too short for decryption", "quic::packet_protection");
    }
    auto nonce = make_nonce(keys.iv, packet_number);
    auto header = packet.subspan(0, header_length);
    auto ciphertext = packet.subspan(header_length,
                                     packet.size() - header_length - aead_tag_size);
    auto tag = packet.subspan(packet.size() - aead_tag_size, aead_tag_size);
    std::vector<uint8_t> plaintext(ciphertext.size());
    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();
    if (!ctx)
    {
        return error<std::pair<std::vector<uint8_t>, std::vector<uint8_t>>>(
            -1, "Failed to create cipher context", "quic::packet_protection");
    }
    int ret = EVP_DecryptInit_ex(ctx, EVP_aes_128_gcm(), nullptr,
                                  keys.key.data(), nonce.data());
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::pair<std::vector<uint8_t>, std::vector<uint8_t>>>(
            -1, "AES-GCM decrypt init failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    // Set AAD (header)
    int len;
    ret = EVP_DecryptUpdate(ctx, nullptr, &len, header.data(),
                            static_cast<int>(header.size()));
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::pair<std::vector<uint8_t>, std::vector<uint8_t>>>(
            -1, "AES-GCM AAD update failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    // Decrypt ciphertext
    ret = EVP_DecryptUpdate(ctx, plaintext.data(), &len,
                            ciphertext.data(), static_cast<int>(ciphertext.size()));
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::pair<std::vector<uint8_t>, std::vector<uint8_t>>>(
            -1, "AES-GCM decrypt failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    int plaintext_len = len;
    // Set expected tag
    ret = EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, aead_tag_size,
                              const_cast<uint8_t*>(tag.data()));
    if (ret != 1)
    {
        EVP_CIPHER_CTX_free(ctx);
        return error<std::pair<std::vector<uint8_t>, std::vector<uint8_t>>>(
            -1, "AES-GCM set tag failed", "quic::packet_protection",
            get_openssl_error_string());
    }
    ret = EVP_DecryptFinal_ex(ctx, plaintext.data() + len, &len);
    EVP_CIPHER_CTX_free(ctx);
    if (ret != 1)
    {
        return error<std::pair<std::vector<uint8_t>, std::vector<uint8_t>>>(
            -1, "AES-GCM authentication failed", "quic::packet_protection");
    }
    plaintext_len += len;
    plaintext.resize(plaintext_len);
    std::vector<uint8_t> header_copy(header.begin(), header.end());
    return ok(std::make_pair(std::move(header_copy), std::move(plaintext)));
}
References kcenon::network::protocols::quic::aead_tag_size, and kcenon::network::ok().
Referenced by kcenon::network::internal::quic_socket::handle_packet().
unprotect_header()
auto kcenon::network::protocols::quic::packet_protection::unprotect_header (const quic_keys & keys, std::span< uint8_t > header, size_t pn_offset, std::span< const uint8_t > sample) -> Result<std::pair<uint8_t, size_t>> static
Remove header protection.
Parameters
keys Keys containing the HP key
header Header bytes (modified in place)
pn_offset Offset of packet number in header
sample Sample from encrypted payload (16 bytes)
Returns
Pair of (first_byte_unprotected, pn_length) or error
Definition at line 715 of file crypto.cpp.
{
    auto mask_result = generate_hp_mask(keys.hp_key, sample);
    if (mask_result.is_err())
    {
        return error<std::pair<uint8_t, size_t>>(
            mask_result.error().code,
            mask_result.error().message,
            get_error_source(mask_result.error()));
    }
    auto& mask = mask_result.value();
    // Unmask first byte
    if ((header[0] & 0x80) != 0)
    {
        // Long header
        header[0] ^= (mask[0] & 0x0F);
    }
    else
    {
        // Short header
        header[0] ^= (mask[0] & 0x1F);
    }
    // Get packet number length from first byte
    size_t pn_length = (header[0] & 0x03) + 1;
    // Unmask packet number
    for (size_t i = 0; i < pn_length; ++i)
    {
        header[pn_offset + i] ^= mask[1 + i];
    }
    return ok(std::make_pair(header[0], pn_length));
}
References kcenon::network::get_error_source(), and kcenon::network::ok().
Referenced by kcenon::network::internal::quic_socket::handle_packet().
The documentation for this class was generated from the following files:
src/internal/protocols/quic/crypto.h
src/protocols/quic/crypto.cpp