Network System: kcenon::network::integration::container_manager Class Reference
kcenon::network::integration::container_manager Class Reference
Manager for container system integration.
#include <container_integration.h>
Classes
class impl
Public Member Functions
void register_container (const std::string &name, std::shared_ptr< container_interface > container)
Register a container implementation.
std::shared_ptr< container_interface > get_container (const std::string &name) const
Get a registered container.
void set_default_container (std::shared_ptr< container_interface > container)
Set default container.
std::shared_ptr< container_interface > get_default_container ()
Get default container.
std::vector< uint8_t > serialize (const std::any &data)
Serialize using default container.
std::any deserialize (const std::vector< uint8_t > &bytes)
Deserialize using default container.
std::vector< std::string > list_containers () const
Get list of registered container names.
Static Public Member Functions
static container_manager & instance ()
Get the singleton instance.
Private Member Functions
container_manager ()
~container_manager ()
Private Attributes
std::unique_ptr< impl > pimpl_
Detailed Description
Manager for container system integration.
This class manages the integration between network_system and container implementations.
Definition at line 155 of file container_integration.h.
Constructor & Destructor Documentation
container_manager()
kcenon::network::integration::container_manager::container_manager () private
Definition at line 244 of file container_integration.cpp.
    : pimpl_(std::make_unique<impl>()) {
}
~container_manager()
kcenon::network::integration::container_manager::~container_manager () private default
Member Function Documentation
deserialize()
std::any kcenon::network::integration::container_manager::deserialize (const std::vector< uint8_t > & bytes)
Deserialize using default container.
Parameters
bytes Bytes to deserialize
Returns
Deserialized data
Definition at line 277 of file container_integration.cpp.
{
    return pimpl_->deserialize(bytes);
}
References kcenon::network::integration::container_manager::impl::deserialize(), and pimpl_.
get_container()
std::shared_ptr< container_interface > kcenon::network::integration::container_manager::get_container (const std::string & name) const
Get a registered container.
Parameters
name Container name
Returns
Container implementation or nullptr if not found
Definition at line 257 of file container_integration.cpp.
        {
    return pimpl_->get_container(name);
}
References kcenon::network::integration::container_manager::impl::get_container(), and pimpl_.
get_default_container()
std::shared_ptr< container_interface > kcenon::network::integration::container_manager::get_default_container ()
Get default container.
Returns
Default container (creates basic container if none set)
Definition at line 269 of file container_integration.cpp.
{
    return pimpl_->get_default_container();
}
References kcenon::network::integration::container_manager::impl::get_default_container(), and pimpl_.
instance()
container_manager & kcenon::network::integration::container_manager::instance () static
Get the singleton instance.
Returns
Reference to the singleton instance
Definition at line 239 of file container_integration.cpp.
{
    static container_manager instance;
    return instance;
}
References instance().
Referenced by instance().
list_containers()
std::vector< std::string > kcenon::network::integration::container_manager::list_containers () const
Get list of registered container names.
Returns
Vector of container names
Definition at line 281 of file container_integration.cpp.
{
    return pimpl_->list_containers();
}
References kcenon::network::integration::container_manager::impl::list_containers(), and pimpl_.
register_container()
void kcenon::network::integration::container_manager::register_container (const std::string & name, std::shared_ptr< container_interface > container)
Register a container implementation.
Parameters
name Container name
container Container implementation
Definition at line 250 of file container_integration.cpp.
  {
    pimpl_->register_container(name, container);
}
References pimpl_, and kcenon::network::integration::container_manager::impl::register_container().
serialize()
std::vector< uint8_t > kcenon::network::integration::container_manager::serialize (const std::any & data)
Serialize using default container.
Parameters
data Data to serialize
Returns
Serialized bytes
Definition at line 273 of file container_integration.cpp.
{
    return pimpl_->serialize(data);
}
References pimpl_, and kcenon::network::integration::container_manager::impl::serialize().
set_default_container()
void kcenon::network::integration::container_manager::set_default_container (std::shared_ptr< container_interface > container)
Set default container.
Parameters
container Default container to use
Definition at line 263 of file container_integration.cpp.
  {
    pimpl_->set_default_container(container);
}
References pimpl_, and kcenon::network::integration::container_manager::impl::set_default_container().
Member Data Documentation
pimpl_
std::unique_ptr<impl> kcenon::network::integration::container_manager::pimpl_ private
Definition at line 221 of file container_integration.h.
Referenced by deserialize(), get_container(), get_default_container(), list_containers(), register_container(), serialize(), and set_default_container().
The documentation for this class was generated from the following files:
src/internal/integration/container_integration.h
src/integration/container_integration.cpp