Network System: kcenon::network::core::messaging_ws_client Class Reference
kcenon::network::core::messaging_ws_client Class Reference
High-level WebSocket client with automatic connection management.
#include <websocket_client.h>
Public Types
using message_callback_t = std::function< void(const internal::ws_message &)>
Callback type for WebSocket messages.
using text_message_callback_t = std::function< void(const std::string &)>
Callback type for text messages.
using binary_message_callback_t = std::function< void(const std::vector< uint8_t > &)>
Callback type for binary messages.
using connected_callback_t = std::function< void()>
Callback type for connection established.
using disconnected_callback_t = std::function< void(internal::ws_close_code, const std::string &)>
Callback type for disconnection with close code.
using error_callback_t = std::function< void(std::error_code)>
Callback type for errors.
Public Types inherited from kcenon::network::interfaces::i_websocket_client
using text_callback_t = std::function< void(const std::string &)>
Callback type for text messages.
using binary_callback_t = std::function< void(const std::vector< uint8_t > &)>
Callback type for binary messages.
using connected_callback_t = std::function< void()>
Callback type for connection established.
using disconnected_callback_t = std::function< void(uint16_t code, std::string_view reason)>
Callback type for disconnection (with close code and reason)
using error_callback_t = std::function< void(std::error_code)>
Callback type for errors.
using send_callback_t = std::function< void(std::error_code, std::size_t)>
Callback type for send completion.
Public Member Functions
messaging_ws_client (std::string_view client_id)
Constructs a WebSocket client.
~messaging_ws_client () noexcept override
Destructor. Automatically stops the client if still running.
messaging_ws_client (const messaging_ws_client &)=delete
messaging_ws_client & operator= (const messaging_ws_client &)=delete
messaging_ws_client (messaging_ws_client &&)=delete
messaging_ws_client & operator= (messaging_ws_client &&)=delete
auto start_client (const ws_client_config &config) -> VoidResult
Starts the client with full configuration.
auto start_client (std::string_view host, uint16_t port, std::string_view path="/") -> VoidResult
Starts the client by connecting to the WebSocket server.
auto stop_client () -> VoidResult
Stops the client and releases all resources.
auto client_id () const -> const std::string &
Returns the client identifier.
auto send_ping (std::vector< uint8_t > &&payload={}) -> VoidResult
Sends a ping frame.
auto is_running () const -> bool override
Checks if the client is currently running.
auto wait_for_stop () -> void override
Blocks until stop() is called.
auto start (std::string_view host, uint16_t port, std::string_view path="/") -> VoidResult override
Starts the WebSocket client connecting to the specified endpoint.
auto stop () -> VoidResult override
Stops the WebSocket client.
auto is_connected () const -> bool override
Checks if the WebSocket connection is established.
auto send_text (std::string &&message, interfaces::i_websocket_client::send_callback_t handler=nullptr) -> VoidResult override
Sends a text message (interface version).
auto send_binary (std::vector< uint8_t > &&data, interfaces::i_websocket_client::send_callback_t handler=nullptr) -> VoidResult override
Sends a binary message (interface version).
auto ping (std::vector< uint8_t > &&payload={}) -> VoidResult override
Sends a ping frame (interface version).
auto close (uint16_t code=1000, std::string_view reason="") -> VoidResult override
Closes the WebSocket connection gracefully (interface version).
auto set_text_callback (interfaces::i_websocket_client::text_callback_t callback) -> void override
Sets the callback for text messages (interface version).
auto set_binary_callback (interfaces::i_websocket_client::binary_callback_t callback) -> void override
Sets the callback for binary messages (interface version).
auto set_connected_callback (interfaces::i_websocket_client::connected_callback_t callback) -> void override
Sets the callback for connection established (interface version).
auto set_disconnected_callback (interfaces::i_websocket_client::disconnected_callback_t callback) -> void override
Sets the callback for disconnection (interface version).
auto set_error_callback (interfaces::i_websocket_client::error_callback_t callback) -> void override
Sets the callback for errors (interface version).
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Types
using callback_index = ws_client_callback
Callback index type alias for clarity.
using callbacks_t = utils::callback_manager< message_callback_t, text_message_callback_t, binary_message_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t >
Callback manager type for this client.
Private Member Functions
auto do_start_impl (std::string_view host, uint16_t port, std::string_view path) -> VoidResult
WebSocket-specific implementation of client start.
auto do_stop_impl () -> VoidResult
WebSocket-specific implementation of client stop.
auto do_connect () -> void
Initiates async connection to the server.
auto on_message (const internal::ws_message &msg) -> void
Handles received WebSocket messages.
auto on_ping (const std::vector< uint8_t > &payload) -> void
Handles ping frames.
auto on_close (internal::ws_close_code code, const std::string &reason) -> void
Handles connection close.
auto on_error (std::error_code ec) -> void
Handles errors.
auto invoke_message_callback (const internal::ws_message &msg) -> void
Invokes the message callback.
auto invoke_connected_callback () -> void
Invokes the connected callback.
auto invoke_disconnected_callback (internal::ws_close_code code, const std::string &reason) -> void
Invokes the disconnected callback.
auto invoke_error_callback (std::error_code ec) -> void
Invokes the error callback.
Private Attributes
std::string client_id_
utils::lifecycle_manager lifecycle_
callbacks_t callbacks_
std::atomic< bool > is_connected_ {false}
ws_client_config config_
std::unique_ptr< asio::io_context > io_context_
std::unique_ptr< asio::executor_work_guard< asio::io_context::executor_type > > work_guard_
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::future< void > io_context_future_
std::shared_ptr< internal::websocket_socket > ws_socket_
std::mutex ws_socket_mutex_
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
High-level WebSocket client with automatic connection management.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling. It also implements the i_websocket_client interface for composition-based usage.
It handles:
Asynchronous connection and handshake
Message sending and receiving (text and binary)
Ping/pong keepalive
Graceful disconnection
Event-driven callbacks
Thread Safety:
All public methods are thread-safe
Callbacks are invoked from the internal I/O thread
Message sending can be called from any thread
Interface Compliance
This class implements interfaces::i_websocket_client for composition-based usage.
Usage Example:
auto client = std::make_shared<messaging_ws_client>("my_client");
client->set_connected_callback([]() {
    std::cout << "Connected!" << std::endl;
});
client->set_text_message_callback([](const std::string& msg) {
    std::cout << "Received: " << msg << std::endl;
});
client->start_client("example.com", 80, "/ws");
client->send_text("Hello, WebSocket!");
Definition at line 124 of file websocket_client.h.
Member Typedef Documentation
binary_message_callback_t
using kcenon::network::core::messaging_ws_client::binary_message_callback_t = std::function<void(const std::vector<uint8_t>&)>
Callback type for binary messages.
Definition at line 134 of file websocket_client.h.
callback_index
using kcenon::network::core::messaging_ws_client::callback_index = ws_client_callback private
Callback index type alias for clarity.
Definition at line 413 of file websocket_client.h.
callbacks_t
using kcenon::network::core::messaging_ws_client::callbacks_t = utils::callback_manager< message_callback_t, text_message_callback_t, binary_message_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t > private
Callback manager type for this client.
Definition at line 416 of file websocket_client.h.
connected_callback_t
using kcenon::network::core::messaging_ws_client::connected_callback_t = std::function<void()>
Callback type for connection established.
Definition at line 136 of file websocket_client.h.
disconnected_callback_t
using kcenon::network::core::messaging_ws_client::disconnected_callback_t = std::function<void(internal::ws_close_code, const std::string&)>
Callback type for disconnection with close code.
Definition at line 138 of file websocket_client.h.
error_callback_t
using kcenon::network::core::messaging_ws_client::error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Definition at line 140 of file websocket_client.h.
message_callback_t
using kcenon::network::core::messaging_ws_client::message_callback_t = std::function<void(const internal::ws_message&)>
Callback type for WebSocket messages.
Definition at line 130 of file websocket_client.h.
text_message_callback_t
using kcenon::network::core::messaging_ws_client::text_message_callback_t = std::function<void(const std::string&)>
Callback type for text messages.
Definition at line 132 of file websocket_client.h.
Constructor & Destructor Documentation
messaging_ws_client() [1/3]
kcenon::network::core::messaging_ws_client::messaging_ws_client (std::string_view client_id) explicit
Constructs a WebSocket client.
Parameters
client_id A unique identifier for this client instance.
Definition at line 44 of file websocket_client.cpp.
        : client_id_(client_id)
    {
    }
~messaging_ws_client()
kcenon::network::core::messaging_ws_client::~messaging_ws_client () override noexcept
Destructor. Automatically stops the client if still running.
Definition at line 49 of file websocket_client.cpp.
    {
        if (lifecycle_.is_running())
        {
            (void)stop_client();
        }
    }
References kcenon::network::utils::lifecycle_manager::is_running(), lifecycle_, and stop_client().
messaging_ws_client() [2/3]
kcenon::network::core::messaging_ws_client::messaging_ws_client (const messaging_ws_client &) delete
messaging_ws_client() [3/3]
kcenon::network::core::messaging_ws_client::messaging_ws_client (messaging_ws_client &&) delete
Member Function Documentation
client_id()
auto kcenon::network::core::messaging_ws_client::client_id () const -> const std::string&
Returns the client identifier.
Returns
The client_id string.
Definition at line 114 of file websocket_client.cpp.
    {
        return client_id_;
    }
References client_id_.
close()
auto kcenon::network::core::messaging_ws_client::close (uint16_t code = 1000, std::string_view reason = "") -> VoidResult override virtual
Closes the WebSocket connection gracefully (interface version).
Parameters
code The close status code.
reason Optional human-readable reason.
Returns
VoidResult indicating success or failure.
Implements i_websocket_client::close().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 199 of file websocket_client.cpp.
    {
        std::lock_guard<std::mutex> lock(ws_socket_mutex_);
        if (!ws_socket_)
        {
            return error_void(error_codes::network_system::connection_closed,
                              "WebSocket not connected");
        }
        ws_socket_->async_close(static_cast<internal::ws_close_code>(code),
                                std::string(reason), [](std::error_code) {});
        return ok();
    }
References kcenon::network::error_codes::network_system::connection_closed, kcenon::network::error_void(), and kcenon::network::ok().
do_connect()
auto kcenon::network::core::messaging_ws_client::do_connect () -> void private
Initiates async connection to the server.
Definition at line 358 of file websocket_client.cpp.
    {
        tcp::resolver resolver(*io_context_);
        auto endpoints = resolver.resolve(config_.host, std::to_string(config_.port));
        auto socket = std::make_shared<tcp::socket>(*io_context_);
        asio::async_connect(
            *socket, endpoints,
            [this, socket](std::error_code ec, tcp::endpoint)
            {
                if (ec)
                {
                    NETWORK_LOG_ERROR("[messaging_ws_client] Connection failed: " +
                                      ec.message());
                    invoke_error_callback(ec);
                    return;
                }
                // Wrap in tcp_socket
                auto tcp_sock = std::make_shared<internal::tcp_socket>(std::move(*socket));
                // Wrap in websocket_socket
                {
                    std::lock_guard<std::mutex> lock(ws_socket_mutex_);
                    ws_socket_ = std::make_shared<internal::websocket_socket>(tcp_sock, true);
                    // Set WebSocket callbacks
                    ws_socket_->set_message_callback(
                        [this](const internal::ws_message& msg) { on_message(msg); });
                    ws_socket_->set_ping_callback(
                        [this](const std::vector<uint8_t>& payload) { on_ping(payload); });
                    ws_socket_->set_close_callback(
                        [this](internal::ws_close_code code, const std::string& reason)
                        { on_close(code, reason); });
                    ws_socket_->set_error_callback(
                        [this](std::error_code ec) { on_error(ec); });
                    // Perform handshake
                    ws_socket_->async_handshake(
                        config_.host, config_.path, config_.port,
                        [this](std::error_code ec)
{
                            if (ec)
{
                                NETWORK_LOG_ERROR(
                                    "[messaging_ws_client] Handshake failed: " + ec.message());
                                invoke_error_callback(ec);
                                return;
                            }
                            is_connected_.store(true, std::memory_order_release);
                            NETWORK_LOG_INFO(
                                "[messaging_ws_client] Connected (ID: " +
                                client_id_ + ")");
                            // Start reading frames
                            ws_socket_->start_read();
                            // Invoke connected callback
                            invoke_connected_callback();
                        });
                }
            });
    }
References NETWORK_LOG_ERROR, and NETWORK_LOG_INFO.
do_start_impl()
auto kcenon::network::core::messaging_ws_client::do_start_impl (std::string_view host, uint16_t port, std::string_view path) -> VoidResult private
WebSocket-specific implementation of client start.
Parameters
host The server hostname or IP address.
port The server port number.
path The WebSocket path.
Returns
Result<void> - Success if client started, or error with code.
Definition at line 259 of file websocket_client.cpp.
    {
        try
        {
            // Store config if not already set
            if (config_.host.empty())
            {
                config_.host = std::string(host);
                config_.port = port;
                config_.path = std::string(path);
            }
            // Create io_context and work guard
            io_context_ = std::make_unique<asio::io_context>();
            work_guard_ = std::make_unique<
                asio::executor_work_guard<asio::io_context::executor_type>>(
                asio::make_work_guard(*io_context_));
            // Get thread pool from network context
            thread_pool_ = network_context::instance().get_thread_pool();
            if (!thread_pool_) {
                // Fallback: create a temporary thread pool if network_context is not initialized
                NETWORK_LOG_WARN("[messaging_ws_client] network_context not initialized, creating temporary thread pool");
                thread_pool_ = std::make_shared<integration::basic_thread_pool>(std::thread::hardware_concurrency());
            }
            // Start io_context on thread pool
            io_context_future_ = thread_pool_->submit([this]() {
                try {
                    NETWORK_LOG_DEBUG("[messaging_ws_client] io_context started");
                    io_context_->run();
                    NETWORK_LOG_DEBUG("[messaging_ws_client] io_context stopped");
                } catch (const std::exception& e) {
                    NETWORK_LOG_ERROR("[messaging_ws_client] Exception in io_context: " +
                                      std::string(e.what()));
                }
            });
            // Start async connection
            do_connect();
            NETWORK_LOG_INFO("[messaging_ws_client] Client started (ID: " +
                             client_id_ + ")");
            return ok();
        }
        catch (const std::exception& e)
        {
            return error_void(error_codes::network_system::connection_failed,
                              std::string("Failed to start client: ") + e.what());
        }
    }
References kcenon::network::error_codes::network_system::connection_failed, kcenon::network::error_void(), kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), NETWORK_LOG_DEBUG, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, NETWORK_LOG_WARN, and kcenon::network::ok().
do_stop_impl()
auto kcenon::network::core::messaging_ws_client::do_stop_impl () -> VoidResult private
WebSocket-specific implementation of client stop.
Returns
Result<void> - Success if client stopped, or error with code.
Definition at line 313 of file websocket_client.cpp.
    {
        try
        {
            // Close WebSocket connection
            {
                std::lock_guard<std::mutex> lock(ws_socket_mutex_);
                if (ws_socket_ && ws_socket_->is_open())
                {
                    ws_socket_->async_close(
                        internal::ws_close_code::normal, "",
                        [](std::error_code) {});
                }
            }
            // Stop io_context
            work_guard_.reset();
            if (io_context_)
            {
                io_context_->stop();
            }
            // Wait for io_context task to complete
            if (io_context_future_.valid())
            {
                try {
                    io_context_future_.wait();
                } catch (const std::exception& e) {
                    NETWORK_LOG_ERROR("[messaging_ws_client] Exception while waiting for io_context: " +
                                      std::string(e.what()));
                }
            }
            NETWORK_LOG_INFO("[messaging_ws_client] Client stopped (ID: " +
                             client_id_ + ")");
            return ok();
        }
        catch (const std::exception& e)
        {
            return error_void(error_codes::common_errors::internal_error,
                              std::string("Failed to stop client: ") + e.what());
        }
    }
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, kcenon::network::internal::normal, and kcenon::network::ok().
invoke_connected_callback()
auto kcenon::network::core::messaging_ws_client::invoke_connected_callback () -> void private
Invokes the connected callback.
Definition at line 479 of file websocket_client.cpp.
    {
        callbacks_.invoke<to_index(callback_index::connected)>();
    }
References kcenon::network::to_index().
invoke_disconnected_callback()
auto kcenon::network::core::messaging_ws_client::invoke_disconnected_callback (internal::ws_close_code code, const std::string & reason) -> void private
Invokes the disconnected callback.
Parameters
code The close code.
reason The close reason.
Definition at line 484 of file websocket_client.cpp.
    {
        callbacks_.invoke<to_index(callback_index::disconnected)>(code, reason);
    }
References kcenon::network::to_index().
invoke_error_callback()
auto kcenon::network::core::messaging_ws_client::invoke_error_callback (std::error_code ec) -> void private
Invokes the error callback.
Parameters
ec The error code.
Definition at line 490 of file websocket_client.cpp.
    {
        callbacks_.invoke<to_index(callback_index::error)>(ec);
    }
References kcenon::network::to_index().
invoke_message_callback()
auto kcenon::network::core::messaging_ws_client::invoke_message_callback (const internal::ws_message & msg) -> void private
Invokes the message callback.
Parameters
msg The received message.
Definition at line 465 of file websocket_client.cpp.
    {
        callbacks_.invoke<to_index(callback_index::message)>(msg);
        if (msg.type == internal::ws_message_type::text)
        {
            callbacks_.invoke<to_index(callback_index::text_message)>(msg.as_text());
        }
        else if (msg.type == internal::ws_message_type::binary)
        {
            callbacks_.invoke<to_index(callback_index::binary_message)>(msg.as_binary());
        }
    }
References kcenon::network::internal::binary, kcenon::network::internal::text, and kcenon::network::to_index().
is_connected()
auto kcenon::network::core::messaging_ws_client::is_connected () const -> bool override virtual
Checks if the WebSocket connection is established.
Returns
true if connected, false otherwise.
Implements i_websocket_client::is_connected().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 148 of file websocket_client.cpp.
    {
        return is_connected_.load(std::memory_order_relaxed);
    }
References is_connected_.
is_running()
auto kcenon::network::core::messaging_ws_client::is_running () const -> bool override virtual
Checks if the client is currently running.
Returns
true if running, false otherwise.
Implements i_network_component::is_running().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 123 of file websocket_client.cpp.
    {
        return lifecycle_.is_running();
    }
References kcenon::network::utils::lifecycle_manager::is_running(), and lifecycle_.
on_close()
auto kcenon::network::core::messaging_ws_client::on_close (internal::ws_close_code code, const std::string & reason) -> void private
Handles connection close.
Definition at line 445 of file websocket_client.cpp.
    {
        is_connected_.store(false, std::memory_order_release);
        NETWORK_LOG_INFO("[messaging_ws_client] Connection closed (ID: " +
                         client_id_ + ")");
        invoke_disconnected_callback(code, reason);
    }
References NETWORK_LOG_INFO.
on_error()
auto kcenon::network::core::messaging_ws_client::on_error (std::error_code ec) -> void private
Handles errors.
Definition at line 455 of file websocket_client.cpp.
    {
        NETWORK_LOG_ERROR("[messaging_ws_client] Error: " + ec.message());
        invoke_error_callback(ec);
    }
References NETWORK_LOG_ERROR.
on_message()
auto kcenon::network::core::messaging_ws_client::on_message (const internal::ws_message & msg) -> void private
Handles received WebSocket messages.
Definition at line 427 of file websocket_client.cpp.
    {
        invoke_message_callback(msg);
    }
on_ping()
auto kcenon::network::core::messaging_ws_client::on_ping (const std::vector< uint8_t > & payload) -> void private
Handles ping frames.
Definition at line 432 of file websocket_client.cpp.
    {
        if (config_.auto_pong)
        {
            std::lock_guard<std::mutex> lock(ws_socket_mutex_);
            if (ws_socket_)
            {
                ws_socket_->async_send_ping(std::vector<uint8_t>(payload),
                                            [](std::error_code) {});
            }
        }
    }
operator=() [1/2]
messaging_ws_client & kcenon::network::core::messaging_ws_client::operator= (const messaging_ws_client &) delete
operator=() [2/2]
messaging_ws_client & kcenon::network::core::messaging_ws_client::operator= (messaging_ws_client &&) delete
ping()
auto kcenon::network::core::messaging_ws_client::ping (std::vector< uint8_t > && payload = {}) -> VoidResult override virtual
Sends a ping frame (interface version).
Parameters
payload Optional payload data (max 125 bytes).
Returns
VoidResult indicating success or failure.
Implements i_websocket_client::ping(). Delegates to send_ping().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 194 of file websocket_client.cpp.
    {
        return send_ping(std::move(payload));
    }
send_binary()
auto kcenon::network::core::messaging_ws_client::send_binary (std::vector< uint8_t > && data, interfaces::i_websocket_client::send_callback_t handler = nullptr) -> VoidResult override virtual
Sends a binary message (interface version).
Parameters
data The binary data to send.
handler Optional completion handler.
Returns
VoidResult indicating success or failure.
Implements i_websocket_client::send_binary().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 167 of file websocket_client.cpp.
    {
        std::lock_guard<std::mutex> lock(ws_socket_mutex_);
        if (!ws_socket_)
        {
            return error_void(error_codes::network_system::connection_closed,
                              "WebSocket not connected");
        }
        return ws_socket_->async_send_binary(std::move(data), std::move(handler));
    }
References kcenon::network::error_codes::network_system::connection_closed, and kcenon::network::error_void().
send_ping()
auto kcenon::network::core::messaging_ws_client::send_ping (std::vector< uint8_t > && payload = {}) -> VoidResult
Sends a ping frame.
Parameters
payload Optional payload data (max 125 bytes).
Returns
VoidResult indicating success.
Definition at line 181 of file websocket_client.cpp.
    {
        std::lock_guard<std::mutex> lock(ws_socket_mutex_);
        if (!ws_socket_)
        {
            return error_void(error_codes::network_system::connection_closed,
                              "WebSocket not connected");
        }
        ws_socket_->async_send_ping(std::move(payload), [](std::error_code) {});
        return ok();
    }
References kcenon::network::error_codes::network_system::connection_closed, kcenon::network::error_void(), and kcenon::network::ok().
send_text()
auto kcenon::network::core::messaging_ws_client::send_text (std::string && message, interfaces::i_websocket_client::send_callback_t handler = nullptr) -> VoidResult override virtual
Sends a text message (interface version).
Parameters
message The text message to send.
handler Optional completion handler.
Returns
VoidResult indicating success or failure.
Implements i_websocket_client::send_text().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 153 of file websocket_client.cpp.
    {
        std::lock_guard<std::mutex> lock(ws_socket_mutex_);
        if (!ws_socket_)
        {
            return error_void(error_codes::network_system::connection_closed,
                              "WebSocket not connected");
        }
        return ws_socket_->async_send_text(std::move(message), std::move(handler));
    }
References kcenon::network::error_codes::network_system::connection_closed, kcenon::network::error_void(), and kcenon::network::message.
set_binary_callback()
auto kcenon::network::core::messaging_ws_client::set_binary_callback (interfaces::i_websocket_client::binary_callback_t callback) -> void override virtual
Sets the callback for binary messages (interface version).
Parameters
callback The callback function.
Implements i_websocket_client::set_binary_callback().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 223 of file websocket_client.cpp.
    {
        callbacks_.set<to_index(callback_index::binary_message)>(std::move(callback));
    }
References kcenon::network::to_index().
set_connected_callback()
auto kcenon::network::core::messaging_ws_client::set_connected_callback (interfaces::i_websocket_client::connected_callback_t callback) -> void override virtual
Sets the callback for connection established (interface version).
Parameters
callback The callback function.
Implements i_websocket_client::set_connected_callback().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 229 of file websocket_client.cpp.
    {
        callbacks_.set<to_index(callback_index::connected)>(std::move(callback));
    }
References kcenon::network::to_index().
set_disconnected_callback()
auto kcenon::network::core::messaging_ws_client::set_disconnected_callback (interfaces::i_websocket_client::disconnected_callback_t callback) -> void override virtual
Sets the callback for disconnection (interface version).
Parameters
callback The callback function.
Implements i_websocket_client::set_disconnected_callback().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 235 of file websocket_client.cpp.
    {
        // Adapt interface callback to internal callback type
        if (callback) {
            callbacks_.set<to_index(callback_index::disconnected)>(
                [callback = std::move(callback)](internal::ws_close_code code, const std::string& reason) {
                    callback(static_cast<uint16_t>(code), reason);
                });
        } else {
            callbacks_.set<to_index(callback_index::disconnected)>(disconnected_callback_t{});
        }
    }
References kcenon::network::to_index().
set_error_callback()
auto kcenon::network::core::messaging_ws_client::set_error_callback (interfaces::i_websocket_client::error_callback_t callback) -> void override virtual
Sets the callback for errors (interface version).
Parameters
callback The callback function.
Implements i_websocket_client::set_error_callback().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 249 of file websocket_client.cpp.
    {
        callbacks_.set<to_index(callback_index::error)>(std::move(callback));
    }
References kcenon::network::to_index().
set_text_callback()
auto kcenon::network::core::messaging_ws_client::set_text_callback (interfaces::i_websocket_client::text_callback_t callback) -> void override virtual
Sets the callback for text messages (interface version).
Parameters
callback The callback function.
Implements i_websocket_client::set_text_callback().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 217 of file websocket_client.cpp.
    {
        callbacks_.set<to_index(callback_index::text_message)>(std::move(callback));
    }
References kcenon::network::to_index().
start()
auto kcenon::network::core::messaging_ws_client::start (std::string_view host, uint16_t port, std::string_view path = "/") -> VoidResult override virtual
Starts the WebSocket client connecting to the specified endpoint.
Parameters
host The server hostname or IP address.
port The server port number.
path The WebSocket path (default: "/").
Returns
VoidResult indicating success or failure.
Implements i_websocket_client::start(). Delegates to start_client().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 137 of file websocket_client.cpp.
    {
        return start_client(host, port, path);
    }
start_client() [1/2]
auto kcenon::network::core::messaging_ws_client::start_client (const ws_client_config & config) -> VoidResult
Starts the client with full configuration.
Parameters
config The client configuration.
Returns
VoidResult indicating success or error.
Definition at line 61 of file websocket_client.cpp.
    {
        config_ = config;
        return start_client(config.host, config.port, config.path);
    }
References config.
start_client() [2/2]
auto kcenon::network::core::messaging_ws_client::start_client (std::string_view host, uint16_t port, std::string_view path = "/") -> VoidResult
Starts the client by connecting to the WebSocket server.
Parameters
host The remote hostname or IP address.
port The remote port number.
path The WebSocket path (default: "/").
Returns
Result<void> - Success if client started, or error with code.
Definition at line 67 of file websocket_client.cpp.
    {
        if (lifecycle_.is_running())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "WebSocket client is already running",
                "messaging_ws_client");
        }
        if (host.empty())
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Host cannot be empty",
                "messaging_ws_client");
        }
        lifecycle_.set_running();
        is_connected_.store(false);
        auto result = do_start_impl(host, port, path);
        if (result.is_err())
        {
            lifecycle_.mark_stopped();
        }
        return result;
    }
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::invalid_argument.
stop()
auto kcenon::network::core::messaging_ws_client::stop () -> VoidResult override virtual
Stops the WebSocket client.
Returns
VoidResult indicating success or failure.
Implements i_websocket_client::stop(). Delegates to stop_client().
Implements kcenon::network::interfaces::i_websocket_client.
Definition at line 143 of file websocket_client.cpp.
    {
        return stop_client();
    }
stop_client()
auto kcenon::network::core::messaging_ws_client::stop_client () -> VoidResult
Stops the client and releases all resources.
Returns
Result<void> - Success if client stopped, or error with code.
Definition at line 98 of file websocket_client.cpp.
    {
        if (!lifecycle_.prepare_stop())
        {
            return ok();
        }
        is_connected_.store(false);
        auto result = do_stop_impl();
        lifecycle_.mark_stopped();
        return result;
    }
References kcenon::network::ok().
Referenced by ~messaging_ws_client().
wait_for_stop()
auto kcenon::network::core::messaging_ws_client::wait_for_stop () -> void override virtual
Blocks until stop() is called.
Implements i_network_component::wait_for_stop().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 128 of file websocket_client.cpp.
    {
        lifecycle_.wait_for_stop();
    }
Member Data Documentation
callbacks_
callbacks_t kcenon::network::core::messaging_ws_client::callbacks_ private
Callback manager.
Definition at line 431 of file websocket_client.h.
client_id_
std::string kcenon::network::core::messaging_ws_client::client_id_ private
Client identifier.
Definition at line 429 of file websocket_client.h.
Referenced by client_id().
config_
ws_client_config kcenon::network::core::messaging_ws_client::config_ private
Client configuration.
Definition at line 434 of file websocket_client.h.
io_context_
std::unique_ptr<asio::io_context> kcenon::network::core::messaging_ws_client::io_context_ private
ASIO I/O context.
Definition at line 436 of file websocket_client.h.
io_context_future_
std::future<void> kcenon::network::core::messaging_ws_client::io_context_future_ private
Future for io_context run task.
Definition at line 440 of file websocket_client.h.
is_connected_
std::atomic<bool> kcenon::network::core::messaging_ws_client::is_connected_ {false} private
True if connected to remote.
Definition at line 432 of file websocket_client.h.
{false};
Referenced by is_connected().
lifecycle_
utils::lifecycle_manager kcenon::network::core::messaging_ws_client::lifecycle_ private
Lifecycle state manager.
Definition at line 430 of file websocket_client.h.
Referenced by is_running(), and ~messaging_ws_client().
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::messaging_ws_client::thread_pool_ private
Thread pool for async operations.
Definition at line 439 of file websocket_client.h.
work_guard_
std::unique_ptr<asio::executor_work_guard<asio::io_context::executor_type> > kcenon::network::core::messaging_ws_client::work_guard_ private
Work guard.
Definition at line 437 of file websocket_client.h.
ws_socket_
std::shared_ptr<internal::websocket_socket> kcenon::network::core::messaging_ws_client::ws_socket_ private
WebSocket wrapper.
Definition at line 442 of file websocket_client.h.
ws_socket_mutex_
std::mutex kcenon::network::core::messaging_ws_client::ws_socket_mutex_ private
Protects ws_socket_.
Definition at line 443 of file websocket_client.h.
The documentation for this class was generated from the following files:
src/internal/http/websocket_client.h
src/http/websocket_client.cpp