Network System: kcenon::network::protocols::http2::http2_server_connection Class Reference
kcenon::network::protocols::http2::http2_server_connection Class Reference
Represents a single HTTP/2 connection on the server side.
#include <http2_server.h>
Public Member Functions
http2_server_connection (uint64_t connection_id, asio::ip::tcp::socket socket, const http2_settings &settings, http2_server::request_handler_t request_handler, http2_server::error_handler_t error_handler)
Construct server connection with plain socket.
http2_server_connection (uint64_t connection_id, std::unique_ptr< asio::ssl::stream< asio::ip::tcp::socket > > socket, const http2_settings &settings, http2_server::request_handler_t request_handler, http2_server::error_handler_t error_handler)
Construct server connection with TLS socket.
~http2_server_connection ()
Destructor.
http2_server_connection (const http2_server_connection &)=delete
http2_server_connection & operator= (const http2_server_connection &)=delete
http2_server_connection (http2_server_connection &&)=delete
http2_server_connection & operator= (http2_server_connection &&)=delete
auto start () -> VoidResult
Start connection handling.
auto stop () -> VoidResult
Stop connection.
auto is_alive () const -> bool
Check if connection is alive.
auto connection_id () const -> uint64_t
Get connection identifier.
auto stream_count () const -> size_t
Get number of active streams.
Private Member Functions
auto read_connection_preface () -> void
auto send_settings () -> VoidResult
auto handle_settings_frame (const settings_frame &frame) -> VoidResult
auto send_settings_ack () -> VoidResult
auto start_reading () -> void
auto read_frame_header () -> void
auto read_frame_payload (uint32_t length) -> void
auto send_frame (const frame &f) -> VoidResult
auto process_frame (std::unique_ptr< frame > f) -> VoidResult
auto get_or_create_stream (uint32_t stream_id) -> http2_stream *
auto close_stream (uint32_t stream_id) -> void
auto handle_headers_frame (const headers_frame &f) -> VoidResult
auto handle_data_frame (const data_frame &f) -> VoidResult
auto handle_rst_stream_frame (const rst_stream_frame &f) -> VoidResult
auto handle_ping_frame (const ping_frame &f) -> VoidResult
auto handle_goaway_frame (const goaway_frame &f) -> VoidResult
auto handle_window_update_frame (const window_update_frame &f) -> VoidResult
auto dispatch_request (uint32_t stream_id) -> void
Private Attributes
uint64_t connection_id_
Connection identifier.
bool use_tls_
TLS mode flag.
std::unique_ptr< asio::ip::tcp::socket > plain_socket_
std::unique_ptr< asio::ssl::stream< asio::ip::tcp::socket > > tls_socket_
std::atomic< bool > is_alive_ {true}
std::atomic< bool > preface_received_ {false}
std::atomic< bool > goaway_sent_ {false}
std::mutex streams_mutex_
std::map< uint32_t, http2_stream > streams_
uint32_t last_stream_id_ {0}
http2_settings local_settings_
http2_settings remote_settings_
hpack_encoder encoder_
hpack_decoder decoder_
int32_t connection_window_size_ {65535}
http2_server::request_handler_t request_handler_
http2_server::error_handler_t error_handler_
std::vector< uint8_t > read_buffer_
std::array< uint8_t, 9 > frame_header_buffer_
Detailed Description
Represents a single HTTP/2 connection on the server side.
Handles frame parsing, stream management, and HPACK encoding/decoding for a single client connection.
Definition at line 273 of file http2_server.h.
Constructor & Destructor Documentation
http2_server_connection() [1/4]
kcenon::network::protocols::http2::http2_server_connection::http2_server_connection (uint64_t connection_id, asio::ip::tcp::socket socket, const http2_settings & settings, http2_server::request_handler_t request_handler, http2_server::error_handler_t error_handler)
Construct server connection with plain socket.
Parameters
connection_id Unique connection identifier
socket TCP socket
settings Server HTTP/2 settings
request_handler Request callback
error_handler Error callback
Definition at line 400 of file http2_server.cpp.
        : connection_id_(connection_id)
        , use_tls_(false)
        , plain_socket_(std::make_unique<asio::ip::tcp::socket>(std::move(socket)))
        , local_settings_(settings)
        , encoder_(settings.header_table_size)
        , decoder_(settings.header_table_size)
        , request_handler_(std::move(request_handler))
        , error_handler_(std::move(error_handler))
        , frame_header_buffer_{}
    {
    }
References kcenon::network::protocols::http2::header_table_size, and kcenon::network::protocols::http2::settings.
http2_server_connection() [2/4]
kcenon::network::protocols::http2::http2_server_connection::http2_server_connection (uint64_t connection_id, std::unique_ptr< asio::ssl::stream< asio::ip::tcp::socket > > socket, const http2_settings & settings, http2_server::request_handler_t request_handler, http2_server::error_handler_t error_handler)
Construct server connection with TLS socket.
Parameters
connection_id Unique connection identifier
socket TLS socket
settings Server HTTP/2 settings
request_handler Request callback
error_handler Error callback
Definition at line 418 of file http2_server.cpp.
        : connection_id_(connection_id)
        , use_tls_(true)
        , tls_socket_(std::move(socket))
        , local_settings_(settings)
        , encoder_(settings.header_table_size)
        , decoder_(settings.header_table_size)
        , request_handler_(std::move(request_handler))
        , error_handler_(std::move(error_handler))
        , frame_header_buffer_{}
    {
    }
~http2_server_connection()
kcenon::network::protocols::http2::http2_server_connection::~http2_server_connection ()
Destructor.
Definition at line 436 of file http2_server.cpp.
    {
        stop();
    }
References stop().
http2_server_connection() [3/4]
kcenon::network::protocols::http2::http2_server_connection::http2_server_connection (const http2_server_connection &) delete
http2_server_connection() [4/4]
kcenon::network::protocols::http2::http2_server_connection::http2_server_connection (http2_server_connection &&) delete
Member Function Documentation
close_stream()
auto kcenon::network::protocols::http2::http2_server_connection::close_stream (uint32_t stream_id) -> void private
Definition at line 787 of file http2_server.cpp.
    {
        std::lock_guard<std::mutex> lock(streams_mutex_);
        streams_.erase(stream_id);
    }
connection_id()
auto kcenon::network::protocols::http2::http2_server_connection::connection_id () const -> uint64_t nodiscard
Get connection identifier.
Returns
Connection ID
Definition at line 472 of file http2_server.cpp.
    {
        return connection_id_;
    }
References connection_id_.
dispatch_request()
auto kcenon::network::protocols::http2::http2_server_connection::dispatch_request (uint32_t stream_id) -> void private
Definition at line 918 of file http2_server.cpp.
    {
        if (!request_handler_) {
            return;
        }
        http2_stream* stream = nullptr;
        {
            std::lock_guard<std::mutex> lock(streams_mutex_);
            auto it = streams_.find(stream_id);
            if (it == streams_.end()) {
                return;
            }
            stream = &it->second;
        }
        // Create request from headers
        auto request = http2_request::from_headers(stream->request_headers);
        request.body = stream->request_body;
        // Create server stream for response
        auto encoder_ptr = std::make_shared<hpack_encoder>(encoder_);
        auto weak_this = weak_from_this();
        http2_server_stream server_stream(
            stream_id,
            std::move(request),
            encoder_ptr,
            [weak_this](const frame& f) -> VoidResult {
                auto self = weak_this.lock();
                if (!self) {
                    return error_void(
                        error_codes::common_errors::internal_error,
                        "Connection closed",
                        "http2_server_stream");
                }
                return self->send_frame(f);
            },
            remote_settings_.max_frame_size);
        // Call request handler
        try {
            request_handler_(server_stream, server_stream.request());
        } catch (const std::exception& e) {
            if (error_handler_) {
                error_handler_(std::string("Request handler exception: ") + e.what());
            }
        }
        // Close stream after handler completes
        close_stream(stream_id);
    }
References kcenon::network::error_void(), kcenon::network::protocols::http2::http2_request::from_headers(), kcenon::network::error_codes::common_errors::internal_error, kcenon::network::protocols::http2::http2_stream::request_body, and kcenon::network::protocols::http2::http2_stream::request_headers.
get_or_create_stream()
auto kcenon::network::protocols::http2::http2_server_connection::get_or_create_stream (uint32_t stream_id) -> http2_stream* private
Definition at line 764 of file http2_server.cpp.
    {
        std::lock_guard<std::mutex> lock(streams_mutex_);
        auto it = streams_.find(stream_id);
        if (it != streams_.end()) {
            return &it->second;
        }
        // Create new stream
        http2_stream stream;
        stream.stream_id = stream_id;
        stream.state = stream_state::open;
        stream.window_size = static_cast<int32_t>(local_settings_.initial_window_size);
        auto [iter, inserted] = streams_.emplace(stream_id, std::move(stream));
        if (stream_id > last_stream_id_) {
            last_stream_id_ = stream_id;
        }
        return &iter->second;
    }
References kcenon::network::protocols::http2::open, kcenon::network::protocols::http2::http2_stream::state, kcenon::network::protocols::http2::http2_stream::stream_id, and kcenon::network::protocols::http2::http2_stream::window_size.
handle_data_frame()
auto kcenon::network::protocols::http2::http2_server_connection::handle_data_frame (const data_frame & f) -> VoidResult private
Definition at line 834 of file http2_server.cpp.
    {
        uint32_t stream_id = f.header().stream_id;
        std::lock_guard<std::mutex> lock(streams_mutex_);
        auto it = streams_.find(stream_id);
        if (it == streams_.end()) {
            // Stream doesn't exist
            rst_stream_frame rst(stream_id, static_cast<uint32_t>(error_code::stream_closed));
            return send_frame(rst);
        }
        auto& stream = it->second;
        auto data = f.data();
        stream.request_body.insert(stream.request_body.end(), data.begin(), data.end());
        // Send WINDOW_UPDATE if needed
        size_t data_size = data.size();
        if (data_size > 0) {
            // Update connection window
            window_update_frame conn_wu(0, static_cast<uint32_t>(data_size));
            send_frame(conn_wu);
            // Update stream window
            window_update_frame stream_wu(stream_id, static_cast<uint32_t>(data_size));
            send_frame(stream_wu);
        }
        if (f.is_end_stream()) {
            stream.state = stream_state::half_closed_remote;
            stream.body_complete = true;
            // Need to unlock before dispatching
            lock.~lock_guard();
            dispatch_request(stream_id);
        }
        return ok();
    }
References kcenon::network::protocols::http2::data, kcenon::network::protocols::http2::half_closed_remote, kcenon::network::ok(), and kcenon::network::protocols::http2::stream_closed.
handle_goaway_frame()
auto kcenon::network::protocols::http2::http2_server_connection::handle_goaway_frame (const goaway_frame & f) -> VoidResult private
Definition at line 891 of file http2_server.cpp.
    {
        // Client is closing connection
        stop();
        return ok();
    }
References kcenon::network::ok().
handle_headers_frame()
auto kcenon::network::protocols::http2::http2_server_connection::handle_headers_frame (const headers_frame & f) -> VoidResult private
Definition at line 793 of file http2_server.cpp.
    {
        uint32_t stream_id = f.header().stream_id;
        auto* stream = get_or_create_stream(stream_id);
        if (!stream) {
            return error_void(
                error_codes::common_errors::internal_error,
                "Failed to create stream",
                "http2_server_connection");
        }
        // Decode headers
        auto header_block = f.header_block();
        std::vector<uint8_t> block_data(header_block.begin(), header_block.end());
        auto headers_result = decoder_.decode(block_data);
        if (headers_result.is_err()) {
            // Send GOAWAY with COMPRESSION_ERROR
            goaway_frame goaway(last_stream_id_,
                static_cast<uint32_t>(error_code::compression_error));
            send_frame(goaway);
            stop();
            return error_void(
                headers_result.error().code,
                headers_result.error().message,
                "http2_server_connection");
        }
        stream->request_headers = headers_result.value();
        if (f.is_end_stream()) {
            stream->state = stream_state::half_closed_remote;
            dispatch_request(stream_id);
        } else if (f.is_end_headers()) {
            stream->headers_complete = true;
        }
        return ok();
    }
References kcenon::network::protocols::http2::compression_error, kcenon::network::error_void(), kcenon::network::protocols::http2::goaway, kcenon::network::protocols::http2::half_closed_remote, kcenon::network::error_codes::common_errors::internal_error, and kcenon::network::ok().
handle_ping_frame()
auto kcenon::network::protocols::http2::http2_server_connection::handle_ping_frame (const ping_frame & f) -> VoidResult private
Definition at line 880 of file http2_server.cpp.
    {
        if (f.is_ack()) {
            return ok();
        }
        // Send PING ACK
        ping_frame ack(f.opaque_data(), true);
        return send_frame(ack);
    }
References kcenon::network::ok().
handle_rst_stream_frame()
auto kcenon::network::protocols::http2::http2_server_connection::handle_rst_stream_frame (const rst_stream_frame & f) -> VoidResult private
Definition at line 874 of file http2_server.cpp.
    {
        close_stream(f.header().stream_id);
        return ok();
    }
References kcenon::network::ok().
handle_settings_frame()
auto kcenon::network::protocols::http2::http2_server_connection::handle_settings_frame (const settings_frame & frame) -> VoidResult private
Definition at line 547 of file http2_server.cpp.
    {
        if (frame.is_ack()) {
            // Settings acknowledgment received
            return ok();
        }
        // Apply peer settings
        for (const auto& param : frame.settings()) {
            switch (static_cast<setting_identifier>(param.identifier)) {
                case setting_identifier::header_table_size:
                    remote_settings_.header_table_size = param.value;
                    encoder_.set_max_table_size(param.value);
                    break;
                case setting_identifier::enable_push:
                    remote_settings_.enable_push = (param.value != 0);
                    break;
                case setting_identifier::max_concurrent_streams:
                    remote_settings_.max_concurrent_streams = param.value;
                    break;
                case setting_identifier::initial_window_size:
                    remote_settings_.initial_window_size = param.value;
                    break;
                case setting_identifier::max_frame_size:
                    remote_settings_.max_frame_size = param.value;
                    break;
                case setting_identifier::max_header_list_size:
                    remote_settings_.max_header_list_size = param.value;
                    break;
            }
        }
        // Send ACK
        return send_settings_ack();
    }
References kcenon::network::protocols::http2::enable_push, kcenon::network::protocols::http2::header_table_size, kcenon::network::protocols::http2::initial_window_size, kcenon::network::protocols::http2::max_concurrent_streams, kcenon::network::protocols::http2::max_frame_size, kcenon::network::protocols::http2::max_header_list_size, and kcenon::network::ok().
handle_window_update_frame()
auto kcenon::network::protocols::http2::http2_server_connection::handle_window_update_frame (const window_update_frame & f) -> VoidResult private
Definition at line 898 of file http2_server.cpp.
    {
        uint32_t stream_id = f.header().stream_id;
        int32_t increment = static_cast<int32_t>(f.window_size_increment());
        if (stream_id == 0) {
            // Connection-level flow control
            connection_window_size_ += increment;
        } else {
            // Stream-level flow control
            std::lock_guard<std::mutex> lock(streams_mutex_);
            auto it = streams_.find(stream_id);
            if (it != streams_.end()) {
                it->second.window_size += increment;
            }
        }
        return ok();
    }
References kcenon::network::ok().
is_alive()
auto kcenon::network::protocols::http2::http2_server_connection::is_alive () const -> bool nodiscard
Check if connection is alive.
Returns
True if connection is active
Definition at line 467 of file http2_server.cpp.
    {
        return is_alive_;
    }
References is_alive_.
operator=() [1/2]
http2_server_connection & kcenon::network::protocols::http2::http2_server_connection::operator= (const http2_server_connection &) delete
operator=() [2/2]
http2_server_connection & kcenon::network::protocols::http2::http2_server_connection::operator= (http2_server_connection &&) delete
process_frame()
auto kcenon::network::protocols::http2::http2_server_connection::process_frame (std::unique_ptr< frame > f) -> VoidResult private
Definition at line 702 of file http2_server.cpp.
    {
        auto& header = f->header();
        switch (header.type) {
            case frame_type::settings: {
                auto* settings_f = dynamic_cast<settings_frame*>(f.get());
                if (settings_f) {
                    return handle_settings_frame(*settings_f);
                }
                break;
            }
            case frame_type::headers: {
                auto* headers_f = dynamic_cast<headers_frame*>(f.get());
                if (headers_f) {
                    return handle_headers_frame(*headers_f);
                }
                break;
            }
            case frame_type::data: {
                auto* data_f = dynamic_cast<data_frame*>(f.get());
                if (data_f) {
                    return handle_data_frame(*data_f);
                }
                break;
            }
            case frame_type::rst_stream: {
                auto* rst_f = dynamic_cast<rst_stream_frame*>(f.get());
                if (rst_f) {
                    return handle_rst_stream_frame(*rst_f);
                }
                break;
            }
            case frame_type::ping: {
                auto* ping_f = dynamic_cast<ping_frame*>(f.get());
                if (ping_f) {
                    return handle_ping_frame(*ping_f);
                }
                break;
            }
            case frame_type::goaway: {
                auto* goaway_f = dynamic_cast<goaway_frame*>(f.get());
                if (goaway_f) {
                    return handle_goaway_frame(*goaway_f);
                }
                break;
            }
            case frame_type::window_update: {
                auto* wu_f = dynamic_cast<window_update_frame*>(f.get());
                if (wu_f) {
                    return handle_window_update_frame(*wu_f);
                }
                break;
            }
            default:
                // Ignore unknown frame types
                break;
        }
        return ok();
    }
References kcenon::network::protocols::http2::data, kcenon::network::protocols::http2::goaway, kcenon::network::protocols::http2::headers, kcenon::network::ok(), kcenon::network::protocols::http2::ping, kcenon::network::protocols::http2::rst_stream, kcenon::network::protocols::http2::settings, and kcenon::network::protocols::http2::window_update.
read_connection_preface()
auto kcenon::network::protocols::http2::http2_server_connection::read_connection_preface () -> void private
Definition at line 483 of file http2_server.cpp.
    {
        constexpr size_t PREFACE_SIZE = 24; // "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"
        auto buffer = std::make_shared<std::vector<uint8_t>>(PREFACE_SIZE);
        auto read_handler = [this, buffer](std::error_code ec, std::size_t bytes_read) {
            if (ec || bytes_read != 24) {
                if (error_handler_) {
                    error_handler_("Failed to read connection preface");
                }
                stop();
                return;
            }
            // Verify preface
            const std::string expected = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n";
            if (std::string(buffer->begin(), buffer->end()) != expected) {
                if (error_handler_) {
                    error_handler_("Invalid connection preface");
                }
                stop();
                return;
            }
            preface_received_ = true;
            // Send our SETTINGS frame
            auto result = send_settings();
            if (result.is_err()) {
                if (error_handler_) {
                    error_handler_("Failed to send settings");
                }
                stop();
                return;
            }
            // Start reading frames
            start_reading();
        };
        if (use_tls_) {
            asio::async_read(*tls_socket_, asio::buffer(*buffer), read_handler);
        } else {
            asio::async_read(*plain_socket_, asio::buffer(*buffer), read_handler);
        }
    }
read_frame_header()
auto kcenon::network::protocols::http2::http2_server_connection::read_frame_header () -> void private
Definition at line 594 of file http2_server.cpp.
    {
        if (!is_alive_) {
            return;
        }
        auto read_handler = [this](std::error_code ec, std::size_t bytes_read) {
            if (ec || bytes_read != 9) {
                if (ec != asio::error::eof && ec != asio::error::operation_aborted) {
                    if (error_handler_) {
                        error_handler_(std::string("Read error: ") + ec.message());
                    }
                }
                stop();
                return;
            }
            auto header_result = frame_header::parse(frame_header_buffer_);
            if (header_result.is_err()) {
                if (error_handler_) {
                    error_handler_("Failed to parse frame header");
                }
                stop();
                return;
            }
            auto header = header_result.value();
            if (header.length > 0) {
                read_frame_payload(header.length);
            } else {
                // Process frame with empty payload
                auto frame_result = frame::parse(frame_header_buffer_);
                if (frame_result.is_ok()) {
                    process_frame(std::move(frame_result.value()));
                }
                read_frame_header();
            }
        };
        if (use_tls_) {
            asio::async_read(*tls_socket_, asio::buffer(frame_header_buffer_), read_handler);
        } else {
            asio::async_read(*plain_socket_, asio::buffer(frame_header_buffer_), read_handler);
        }
    }
References kcenon::network::protocols::http2::frame::parse(), and kcenon::network::protocols::http2::frame_header::parse().
read_frame_payload()
auto kcenon::network::protocols::http2::http2_server_connection::read_frame_payload (uint32_t length) -> void private
Definition at line 640 of file http2_server.cpp.
    {
        if (!is_alive_) {
            return;
        }
        read_buffer_.resize(9 + length);
        std::copy(frame_header_buffer_.begin(), frame_header_buffer_.end(), read_buffer_.begin());
        auto payload_buffer = asio::buffer(read_buffer_.data() + 9, length);
        auto read_handler = [this](std::error_code ec, std::size_t /*bytes_read*/) {
            if (ec) {
                if (ec != asio::error::eof && ec != asio::error::operation_aborted) {
                    if (error_handler_) {
                        error_handler_(std::string("Read payload error: ") + ec.message());
                    }
                }
                stop();
                return;
            }
            auto frame_result = frame::parse(read_buffer_);
            if (frame_result.is_ok()) {
                process_frame(std::move(frame_result.value()));
            } else {
                if (error_handler_) {
                    error_handler_("Failed to parse frame");
                }
            }
            read_frame_header();
        };
        if (use_tls_) {
            asio::async_read(*tls_socket_, payload_buffer, read_handler);
        } else {
            asio::async_read(*plain_socket_, payload_buffer, read_handler);
        }
    }
References kcenon::network::protocols::http2::frame::parse().
send_frame()
auto kcenon::network::protocols::http2::http2_server_connection::send_frame (const frame & f) -> VoidResult private
Definition at line 681 of file http2_server.cpp.
    {
        auto data = f.serialize();
        std::error_code ec;
        if (use_tls_) {
            asio::write(*tls_socket_, asio::buffer(data), ec);
        } else {
            asio::write(*plain_socket_, asio::buffer(data), ec);
        }
        if (ec) {
            return error_void(
                error_codes::network_system::send_failed,
                std::string("Failed to send frame: ") + ec.message(),
                "http2_server_connection");
        }
        return ok();
    }
References kcenon::network::protocols::http2::data, kcenon::network::error_void(), kcenon::network::ok(), and kcenon::network::error_codes::network_system::send_failed.
send_settings()
auto kcenon::network::protocols::http2::http2_server_connection::send_settings () -> VoidResult private
Definition at line 530 of file http2_server.cpp.
    {
        std::vector<setting_parameter> params = {
            {static_cast<uint16_t>(setting_identifier::max_concurrent_streams),
             local_settings_.max_concurrent_streams},
            {static_cast<uint16_t>(setting_identifier::initial_window_size),
             local_settings_.initial_window_size},
            {static_cast<uint16_t>(setting_identifier::max_frame_size),
             local_settings_.max_frame_size},
            {static_cast<uint16_t>(setting_identifier::header_table_size),
             local_settings_.header_table_size},
        };
        settings_frame frame(params, false);
        return send_frame(frame);
    }
References kcenon::network::protocols::http2::header_table_size, kcenon::network::protocols::http2::initial_window_size, kcenon::network::protocols::http2::max_concurrent_streams, and kcenon::network::protocols::http2::max_frame_size.
send_settings_ack()
auto kcenon::network::protocols::http2::http2_server_connection::send_settings_ack () -> VoidResult private
Definition at line 583 of file http2_server.cpp.
    {
        settings_frame frame({}, true);
        return send_frame(frame);
    }
start()
auto kcenon::network::protocols::http2::http2_server_connection::start () -> VoidResult
Start connection handling.
Returns
Success or error
Definition at line 441 of file http2_server.cpp.
    {
        // Read connection preface from client
        read_connection_preface();
        return ok();
    }
References kcenon::network::ok().
start_reading()
auto kcenon::network::protocols::http2::http2_server_connection::start_reading () -> void private
Definition at line 589 of file http2_server.cpp.
    {
        read_frame_header();
    }
stop()
auto kcenon::network::protocols::http2::http2_server_connection::stop () -> VoidResult
Stop connection.
Returns
Success or error
Definition at line 448 of file http2_server.cpp.
    {
        if (!is_alive_) {
            return ok();
        }
        is_alive_ = false;
        // Close socket
        std::error_code ec;
        if (use_tls_ && tls_socket_) {
            tls_socket_->lowest_layer().close(ec);
        } else if (plain_socket_) {
            plain_socket_->close(ec);
        }
        return ok();
    }
References kcenon::network::ok().
Referenced by ~http2_server_connection().
stream_count()
auto kcenon::network::protocols::http2::http2_server_connection::stream_count () const -> size_t nodiscard
Get number of active streams.
Returns
Stream count
Definition at line 477 of file http2_server.cpp.
    {
        std::lock_guard<std::mutex> lock(const_cast<std::mutex&>(streams_mutex_));
        return streams_.size();
    }
References streams_, and streams_mutex_.
Member Data Documentation
connection_id_
uint64_t kcenon::network::protocols::http2::http2_server_connection::connection_id_ private
Connection identifier.
Definition at line 374 of file http2_server.h.
Referenced by connection_id().
connection_window_size_
int32_t kcenon::network::protocols::http2::http2_server_connection::connection_window_size_ {65535} private
Definition at line 400 of file http2_server.h.
{65535};
decoder_
hpack_decoder kcenon::network::protocols::http2::http2_server_connection::decoder_ private
Definition at line 397 of file http2_server.h.
encoder_
hpack_encoder kcenon::network::protocols::http2::http2_server_connection::encoder_ private
Definition at line 396 of file http2_server.h.
error_handler_
http2_server::error_handler_t kcenon::network::protocols::http2::http2_server_connection::error_handler_ private
Definition at line 404 of file http2_server.h.
frame_header_buffer_
std::array<uint8_t, 9> kcenon::network::protocols::http2::http2_server_connection::frame_header_buffer_ private
Definition at line 408 of file http2_server.h.
goaway_sent_
std::atomic<bool> kcenon::network::protocols::http2::http2_server_connection::goaway_sent_ {false} private
Definition at line 384 of file http2_server.h.
{false};
is_alive_
std::atomic<bool> kcenon::network::protocols::http2::http2_server_connection::is_alive_ {true} private
Definition at line 382 of file http2_server.h.
{true};
Referenced by is_alive().
last_stream_id_
uint32_t kcenon::network::protocols::http2::http2_server_connection::last_stream_id_ {0} private
Definition at line 389 of file http2_server.h.
{0};
local_settings_
http2_settings kcenon::network::protocols::http2::http2_server_connection::local_settings_ private
Definition at line 392 of file http2_server.h.
plain_socket_
std::unique_ptr<asio::ip::tcp::socket> kcenon::network::protocols::http2::http2_server_connection::plain_socket_ private
Definition at line 378 of file http2_server.h.
preface_received_
std::atomic<bool> kcenon::network::protocols::http2::http2_server_connection::preface_received_ {false} private
Definition at line 383 of file http2_server.h.
{false};
read_buffer_
std::vector<uint8_t> kcenon::network::protocols::http2::http2_server_connection::read_buffer_ private
Definition at line 407 of file http2_server.h.
remote_settings_
http2_settings kcenon::network::protocols::http2::http2_server_connection::remote_settings_ private
Definition at line 393 of file http2_server.h.
request_handler_
http2_server::request_handler_t kcenon::network::protocols::http2::http2_server_connection::request_handler_ private
Definition at line 403 of file http2_server.h.
streams_
std::map<uint32_t, http2_stream> kcenon::network::protocols::http2::http2_server_connection::streams_ private
Definition at line 388 of file http2_server.h.
Referenced by stream_count().
streams_mutex_
std::mutex kcenon::network::protocols::http2::http2_server_connection::streams_mutex_ private
Definition at line 387 of file http2_server.h.
Referenced by stream_count().
tls_socket_
std::unique_ptr<asio::ssl::stream<asio::ip::tcp::socket> > kcenon::network::protocols::http2::http2_server_connection::tls_socket_ private
Definition at line 379 of file http2_server.h.
use_tls_
bool kcenon::network::protocols::http2::http2_server_connection::use_tls_ private
TLS mode flag.
Definition at line 375 of file http2_server.h.
The documentation for this class was generated from the following files:
src/internal/protocols/http2/http2_server.h
src/protocols/http2/http2_server.cpp