Network System: kcenon::network::protocols::grpc::grpc_client::impl Class Reference
kcenon::network::protocols::grpc::grpc_client::impl Class Reference
Public Member Functions
impl (std::string target, grpc_channel_config config)
~impl ()
auto connect () -> VoidResult
auto disconnect () -> void
auto is_connected () const -> bool
auto wait_for_connected (std::chrono::milliseconds timeout) -> bool
auto target () const -> const std::string &
auto call_raw (const std::string &method, const std::vector< uint8_t > &request, const call_options &options) -> Result< grpc_message >
auto call_raw_async (const std::string &method, const std::vector< uint8_t > &request, std::function< void(Result< grpc_message >)> callback, const call_options &options) -> void
auto server_stream_raw (const std::string &method, const std::vector< uint8_t > &request, const call_options &options) -> Result< std::unique_ptr< grpc_client::server_stream_reader > >
auto client_stream_raw (const std::string &method, const call_options &options) -> Result< std::unique_ptr< grpc_client::client_stream_writer > >
auto bidi_stream_raw (const std::string &method, const call_options &options) -> Result< std::unique_ptr< grpc_client::bidi_stream > >
Private Attributes
std::string target_
std::string host_
grpc_channel_config config_
std::shared_ptr< http2::http2_client > http2_client_
std::atomic< bool > connected_
std::mutex mutex_
Detailed Description
Definition at line 1006 of file client.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::protocols::grpc::grpc_client::impl::impl (std::string target, grpc_channel_config config) inline explicit
Definition at line 1009 of file client.cpp.
        : target_(std::move(target))
        , config_(std::move(config))
        , connected_(false)
    {
    }
References config.
~impl()
kcenon::network::protocols::grpc::grpc_client::impl::~impl () inline
Definition at line 1016 of file client.cpp.
    {
        disconnect();
    }
References disconnect().
Member Function Documentation
bidi_stream_raw()
auto kcenon::network::protocols::grpc::grpc_client::impl::bidi_stream_raw (const std::string & method, const call_options & options) -> Result<std::unique_ptr<grpc_client::bidi_stream>> inline
Definition at line 1533 of file client.cpp.
    {
        if (!is_connected())
        {
            return error<std::unique_ptr<grpc_client::bidi_stream>>(
                error_codes::network_system::connection_failed,
                "Not connected to server",
                "grpc::client");
        }
        // Validate method format
        if (method.empty() || method[0] != '/')
        {
            return error<std::unique_ptr<grpc_client::bidi_stream>>(
                error_codes::common_errors::invalid_argument,
                "Invalid method format",
                "grpc::client",
                "Method must start with '/'");
        }
        // Build gRPC headers
        std::vector<http2::http_header> headers;
        headers.emplace_back("content-type", std::string(grpc_content_type));
        headers.emplace_back("te", "trailers");
        headers.emplace_back("grpc-accept-encoding",
                             std::string(compression::identity) + "," +
                             compression::gzip + "," + compression::deflate);
        // Add timeout header if deadline is set
        if (options.deadline.has_value())
        {
            auto now = std::chrono::system_clock::now();
            auto remaining = std::chrono::duration_cast<std::chrono::milliseconds>(
                options.deadline.value() - now);
            if (remaining.count() > 0)
            {
                headers.emplace_back("grpc-timeout",
                                     format_timeout(static_cast<uint64_t>(remaining.count())));
            }
        }
        // Add custom metadata
        for (const auto& [key, value] : options.metadata)
        {
            headers.emplace_back(key, value);
        }
        // Create the bidi stream as shared_ptr for callback capture
        auto bidi = std::make_shared<bidi_stream_impl>(http2_client_, 0);
        // Start streaming request
        auto stream_result = http2_client_->start_stream(
            method,
            headers,
            [bidi](std::vector<uint8_t> data) { bidi->on_data(data); },
            [bidi](std::vector<http2::http_header> hdrs) { bidi->on_headers(hdrs); },
            [bidi](int status) { bidi->on_complete(status); });
        if (stream_result.is_err())
        {
            const auto& err = stream_result.error();
            return error<std::unique_ptr<grpc_client::bidi_stream>>(
                err.code, err.message, "grpc::client", get_error_details(err));
        }
        // Create actual bidi stream with proper stream ID
        auto actual_bidi = std::make_shared<bidi_stream_impl>(http2_client_, stream_result.value());
        struct shared_bidi_holder : public grpc_client::bidi_stream {
            std::shared_ptr<bidi_stream_impl> impl;
            explicit shared_bidi_holder(std::shared_ptr<bidi_stream_impl> p) : impl(std::move(p)) {}
            auto write(const std::vector<uint8_t>& message) -> VoidResult override { return impl->write(message); }
            auto read() -> Result<grpc_message> override { return impl->read(); }
            auto writes_done() -> VoidResult override { return impl->writes_done(); }
            auto finish() -> grpc_status override { return impl->finish(); }
        };
        return ok(std::unique_ptr<grpc_client::bidi_stream>(
            new shared_bidi_holder(actual_bidi)));
    }
References kcenon::network::error_codes::network_system::connection_failed, kcenon::network::protocols::grpc::compression::deflate, kcenon::network::error, kcenon::network::protocols::grpc::format_timeout(), kcenon::network::get_error_details(), kcenon::network::protocols::grpc::grpc_content_type, kcenon::network::protocols::grpc::compression::gzip, http2_client_, kcenon::network::protocols::grpc::compression::identity, kcenon::network::error_codes::common_errors::invalid_argument, is_connected(), kcenon::network::message, and kcenon::network::protocols::grpc::ok.
call_raw()
auto kcenon::network::protocols::grpc::grpc_client::impl::call_raw (const std::string & method, const std::vector< uint8_t > & request, const call_options & options) -> Result<grpc_message> inline
Definition at line 1146 of file client.cpp.
    {
        auto span = tracing::is_tracing_enabled()
            ? std::make_optional(tracing::trace_context::create_span("grpc.client.call"))
            : std::nullopt;
        if (span)
        {
            span->set_attribute("rpc.system", "grpc")
                 .set_attribute("rpc.method", method)
                 .set_attribute("rpc.grpc.target", target_)
                 .set_attribute("rpc.request.size", static_cast<int64_t>(request.size()));
        }
        if (!is_connected())
        {
            if (span)
            {
                span->set_error("Not connected to server");
            }
            return error<grpc_message>(
                error_codes::network_system::connection_failed,
                "Not connected to server",
                "grpc::client");
        }
        // Validate method format
        if (method.empty() || method[0] != '/')
        {
            if (span)
            {
                span->set_error("Invalid method format");
            }
            return error<grpc_message>(
                error_codes::common_errors::invalid_argument,
                "Invalid method format",
                "grpc::client",
                "Method must start with '/'");
        }
        // Check deadline
        if (options.deadline.has_value())
        {
            if (std::chrono::system_clock::now() > options.deadline.value())
            {
                if (span)
                {
                    span->set_error("Deadline exceeded before call started")
                         .set_attribute("rpc.grpc.status_code", static_cast<int64_t>(status_code::deadline_exceeded));
                }
                return error<grpc_message>(
                    static_cast<int>(status_code::deadline_exceeded),
                    "Deadline exceeded before call started",
                    "grpc::client");
            }
        }
        // Build gRPC headers
        std::vector<http2::http_header> headers;
        headers.emplace_back(header_names::content_type, grpc_content_type);
        headers.emplace_back(header_names::te, "trailers");
        headers.emplace_back(header_names::grpc_accept_encoding,
                             std::string(compression::identity) + "," +
                             compression::gzip + "," + compression::deflate);
        // Add timeout header if deadline is set
        if (options.deadline.has_value())
        {
            auto now = std::chrono::system_clock::now();
            auto remaining = std::chrono::duration_cast<std::chrono::milliseconds>(
                options.deadline.value() - now);
            if (remaining.count() > 0)
            {
                headers.emplace_back(header_names::grpc_timeout,
                                     format_timeout(static_cast<uint64_t>(remaining.count())));
            }
        }
        // Add custom metadata
        for (const auto& [key, value] : options.metadata)
        {
            headers.emplace_back(key, value);
        }
        // Serialize request with gRPC framing
        grpc_message request_msg{std::vector<uint8_t>{request.begin(), request.end()}};
        auto serialized_request = request_msg.serialize();
        // Send HTTP/2 POST request
        auto response_result = http2_client_->post(method, serialized_request, headers);
        if (response_result.is_err())
        {
            const auto& err = response_result.error();
            if (span)
            {
                span->set_error(err.message);
            }
            return error<grpc_message>(err.code, err.message, "grpc::client",
                                       get_error_details(err));
        }
        const auto& response = response_result.value();
        // Check HTTP status - gRPC always uses 200 OK for successful transport
        if (response.status_code != 200)
        {
            if (span)
            {
                span->set_error("HTTP error: " + std::to_string(response.status_code))
                     .set_attribute("http.status_code", static_cast<int64_t>(response.status_code));
            }
            return error<grpc_message>(
                static_cast<int>(status_code::unavailable),
                "HTTP error: " + std::to_string(response.status_code),
                "grpc::client");
        }
        // Extract gRPC status from trailers/headers
        status_code grpc_status = status_code::ok;
        std::string grpc_message_str;
        for (const auto& header : response.headers)
        {
            if (header.name == trailer_names::grpc_status)
            {
                int status_int = 0;
                auto [ptr, ec] = std::from_chars(
                    header.value.data(),
                    header.value.data() + header.value.size(),
                    status_int);
                if (ec == std::errc())
                {
                    grpc_status = static_cast<status_code>(status_int);
                }
            }
            else if (header.name == trailer_names::grpc_message)
            {
                grpc_message_str = header.value;
            }
        }
        // Check gRPC status
        if (grpc_status != status_code::ok)
        {
            if (span)
            {
                span->set_error(grpc_message_str.empty() ?
                    std::string(status_code_to_string(grpc_status)) : grpc_message_str)
                     .set_attribute("rpc.grpc.status_code", static_cast<int64_t>(grpc_status));
            }
            return error<grpc_message>(
                static_cast<int>(grpc_status),
                grpc_message_str.empty() ?
                    std::string(status_code_to_string(grpc_status)) : grpc_message_str,
                "grpc::client");
        }
        // Parse response message
        if (response.body.empty())
        {
            // Empty response is valid for some RPCs
            if (span)
            {
                span->set_attribute("rpc.response.size", static_cast<int64_t>(0))
                     .set_attribute("rpc.grpc.status_code", static_cast<int64_t>(0));
            }
            return ok(grpc_message{});
        }
        auto parse_result = grpc_message::parse(response.body);
        if (parse_result.is_err())
        {
            const auto& err = parse_result.error();
            if (span)
            {
                span->set_error(err.message);
            }
            return error<grpc_message>(err.code, err.message, "grpc::client",
                                       get_error_details(err));
        }
        if (span)
        {
            span->set_attribute("rpc.response.size", static_cast<int64_t>(parse_result.value().data.size()))
                 .set_attribute("rpc.grpc.status_code", static_cast<int64_t>(0));
        }
        return ok(std::move(parse_result.value()));
    }
References kcenon::network::error_codes::network_system::connection_failed, kcenon::network::protocols::grpc::header_names::content_type, kcenon::network::tracing::trace_context::create_span(), kcenon::network::protocols::grpc::deadline_exceeded, kcenon::network::protocols::grpc::compression::deflate, kcenon::network::error, kcenon::network::protocols::grpc::format_timeout(), kcenon::network::get_error_details(), kcenon::network::protocols::grpc::header_names::grpc_accept_encoding, kcenon::network::protocols::grpc::grpc_content_type, kcenon::network::protocols::grpc::trailer_names::grpc_message, kcenon::network::protocols::grpc::trailer_names::grpc_status, kcenon::network::protocols::grpc::header_names::grpc_timeout, kcenon::network::protocols::grpc::compression::gzip, http2_client_, kcenon::network::protocols::grpc::compression::identity, kcenon::network::error_codes::common_errors::invalid_argument, is_connected(), kcenon::network::tracing::is_tracing_enabled(), kcenon::network::protocols::grpc::ok, kcenon::network::protocols::grpc::grpc_message::parse(), kcenon::network::protocols::grpc::grpc_message::serialize(), kcenon::network::protocols::grpc::status_code_to_string(), target_, kcenon::network::protocols::grpc::header_names::te, and kcenon::network::protocols::grpc::unavailable.
Referenced by call_raw_async().
call_raw_async()
auto kcenon::network::protocols::grpc::grpc_client::impl::call_raw_async (const std::string & method, const std::vector< uint8_t > & request, std::function< void(Result< grpc_message >)> callback, const call_options & options) -> void inline
Definition at line 1336 of file client.cpp.
    {
        // Execute asynchronously using thread pool
        integration::thread_integration_manager::instance().submit_task(
            [this, method, request, callback, options]() {
                auto result = call_raw(method, request, options);
                if (callback)
                {
                    callback(std::move(result));
                }
            });
    }
References call_raw(), kcenon::network::integration::thread_integration_manager::instance(), and kcenon::network::integration::thread_integration_manager::submit_task().
client_stream_raw()
auto kcenon::network::protocols::grpc::grpc_client::impl::client_stream_raw (const std::string & method, const call_options & options) -> Result<std::unique_ptr<grpc_client::client_stream_writer>> inline
Definition at line 1446 of file client.cpp.
    {
        if (!is_connected())
        {
            return error<std::unique_ptr<grpc_client::client_stream_writer>>(
                error_codes::network_system::connection_failed,
                "Not connected to server",
                "grpc::client");
        }
        // Validate method format
        if (method.empty() || method[0] != '/')
        {
            return error<std::unique_ptr<grpc_client::client_stream_writer>>(
                error_codes::common_errors::invalid_argument,
                "Invalid method format",
                "grpc::client",
                "Method must start with '/'");
        }
        // Build gRPC headers
        std::vector<http2::http_header> headers;
        headers.emplace_back("content-type", std::string(grpc_content_type));
        headers.emplace_back("te", "trailers");
        headers.emplace_back("grpc-accept-encoding",
                             std::string(compression::identity) + "," +
                             compression::gzip + "," + compression::deflate);
        // Add timeout header if deadline is set
        if (options.deadline.has_value())
        {
            auto now = std::chrono::system_clock::now();
            auto remaining = std::chrono::duration_cast<std::chrono::milliseconds>(
                options.deadline.value() - now);
            if (remaining.count() > 0)
            {
                headers.emplace_back("grpc-timeout",
                                     format_timeout(static_cast<uint64_t>(remaining.count())));
            }
        }
        // Add custom metadata
        for (const auto& [key, value] : options.metadata)
        {
            headers.emplace_back(key, value);
        }
        // Create the writer as shared_ptr for callback capture
        auto stream_id_holder = std::make_shared<uint32_t>(0);
        auto writer = std::make_shared<client_stream_writer_impl>(http2_client_, 0);
        // Start streaming request
        auto stream_result = http2_client_->start_stream(
            method,
            headers,
            [writer](std::vector<uint8_t> data) { writer->on_data(data); },
            [writer](std::vector<http2::http_header> hdrs) { writer->on_headers(hdrs); },
            [writer](int status) { writer->on_complete(status); });
        if (stream_result.is_err())
        {
            const auto& err = stream_result.error();
            return error<std::unique_ptr<grpc_client::client_stream_writer>>(
                err.code, err.message, "grpc::client", get_error_details(err));
        }
        // Update the writer with actual stream ID
        auto actual_writer = std::make_shared<client_stream_writer_impl>(http2_client_, stream_result.value());
        // Re-register callbacks with actual writer
        // Note: This is a simplified implementation - in production, you'd want
        // to properly update the stream callbacks
        struct shared_writer_holder : public grpc_client::client_stream_writer {
            std::shared_ptr<client_stream_writer_impl> impl;
            explicit shared_writer_holder(std::shared_ptr<client_stream_writer_impl> p) : impl(std::move(p)) {}
            auto write(const std::vector<uint8_t>& message) -> VoidResult override { return impl->write(message); }
            auto writes_done() -> VoidResult override { return impl->writes_done(); }
            auto finish() -> Result<grpc_message> override { return impl->finish(); }
        };
        return ok(std::unique_ptr<grpc_client::client_stream_writer>(
            new shared_writer_holder(actual_writer)));
    }
References kcenon::network::error_codes::network_system::connection_failed, kcenon::network::protocols::grpc::compression::deflate, kcenon::network::error, kcenon::network::protocols::grpc::format_timeout(), kcenon::network::get_error_details(), kcenon::network::protocols::grpc::grpc_content_type, kcenon::network::protocols::grpc::compression::gzip, http2_client_, kcenon::network::protocols::grpc::compression::identity, kcenon::network::error_codes::common_errors::invalid_argument, is_connected(), kcenon::network::message, and kcenon::network::protocols::grpc::ok.
connect()
auto kcenon::network::protocols::grpc::grpc_client::impl::connect () -> VoidResult inline
Definition at line 1021 of file client.cpp.
    {
        auto span = tracing::is_tracing_enabled()
            ? std::make_optional(tracing::trace_context::create_span("grpc.client.connect"))
            : std::nullopt;
        if (span)
        {
            span->set_attribute("rpc.system", "grpc")
                 .set_attribute("rpc.grpc.target", target_)
                 .set_attribute("net.transport", "tcp");
        }
        std::lock_guard<std::mutex> lock(mutex_);
        if (connected_.load())
        {
            if (span)
            {
                span->set_attribute("grpc.client.already_connected", true);
            }
            return ok();
        }
        // Parse target address
        auto colon_pos = target_.find(':');
        if (colon_pos == std::string::npos)
        {
            if (span)
            {
                span->set_error("Invalid target address format");
            }
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Invalid target address format",
                "grpc::client",
                "Expected format: host:port");
        }
        host_ = target_.substr(0, colon_pos);
        auto port_str = target_.substr(colon_pos + 1);
        unsigned short port = 0;
        auto [ptr, ec] = std::from_chars(
            port_str.data(),
            port_str.data() + port_str.size(),
            port);
        if (ec != std::errc())
        {
            if (span)
            {
                span->set_error("Invalid port number");
            }
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Invalid port number",
                "grpc::client");
        }
        if (span)
        {
            span->set_attribute("net.peer.name", host_)
                 .set_attribute("net.peer.port", static_cast<int64_t>(port));
        }
        // Create HTTP/2 client
        http2_client_ = std::make_shared<http2::http2_client>("grpc-client");
        http2_client_->set_timeout(config_.default_timeout);
        // Connect using HTTP/2
        auto result = http2_client_->connect(host_, port);
        if (result.is_err())
        {
            const auto& err = result.error();
            if (span)
            {
                span->set_error(err.message);
            }
            return error_void(err.code, err.message, "grpc::client",
                              get_error_details(err));
        }
        connected_.store(true);
        return ok();
    }
References config_, connected_, kcenon::network::tracing::trace_context::create_span(), kcenon::network::protocols::grpc::grpc_channel_config::default_timeout, kcenon::network::error_void(), kcenon::network::get_error_details(), host_, http2_client_, kcenon::network::error_codes::common_errors::invalid_argument, kcenon::network::tracing::is_tracing_enabled(), mutex_, kcenon::network::protocols::grpc::ok, and target_.
disconnect()
auto kcenon::network::protocols::grpc::grpc_client::impl::disconnect () -> void inline
Definition at line 1107 of file client.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (http2_client_ && connected_.load())
        {
            http2_client_->disconnect();
        }
        connected_.store(false);
        http2_client_.reset();
    }
References connected_, http2_client_, and mutex_.
Referenced by ~impl().
is_connected()
auto kcenon::network::protocols::grpc::grpc_client::impl::is_connected () const -> bool inline
Definition at line 1120 of file client.cpp.
    {
        return connected_.load() && http2_client_ && http2_client_->is_connected();
    }
References connected_, and http2_client_.
Referenced by bidi_stream_raw(), call_raw(), client_stream_raw(), kcenon::network::protocols::grpc::grpc_client::is_connected(), server_stream_raw(), and wait_for_connected().
server_stream_raw()
auto kcenon::network::protocols::grpc::grpc_client::impl::server_stream_raw (const std::string & method, const std::vector< uint8_t > & request, const call_options & options) -> Result<std::unique_ptr<grpc_client::server_stream_reader>> inline
Definition at line 1352 of file client.cpp.
    {
        if (!is_connected())
        {
            return error<std::unique_ptr<grpc_client::server_stream_reader>>(
                error_codes::network_system::connection_failed,
                "Not connected to server",
                "grpc::client");
        }
        // Validate method format
        if (method.empty() || method[0] != '/')
        {
            return error<std::unique_ptr<grpc_client::server_stream_reader>>(
                error_codes::common_errors::invalid_argument,
                "Invalid method format",
                "grpc::client",
                "Method must start with '/'");
        }
        // Build gRPC headers
        std::vector<http2::http_header> headers;
        headers.emplace_back("content-type", std::string(grpc_content_type));
        headers.emplace_back("te", "trailers");
        headers.emplace_back("grpc-accept-encoding",
                             std::string(compression::identity) + "," +
                             compression::gzip + "," + compression::deflate);
        // Add timeout header if deadline is set
        if (options.deadline.has_value())
        {
            auto now = std::chrono::system_clock::now();
            auto remaining = std::chrono::duration_cast<std::chrono::milliseconds>(
                options.deadline.value() - now);
            if (remaining.count() > 0)
            {
                headers.emplace_back("grpc-timeout",
                                     format_timeout(static_cast<uint64_t>(remaining.count())));
            }
        }
        // Add custom metadata
        for (const auto& [key, value] : options.metadata)
        {
            headers.emplace_back(key, value);
        }
        // Create the reader as shared_ptr for callback capture
        auto reader = std::make_shared<server_stream_reader_impl>(http2_client_, 0);
        // Start streaming request
        auto stream_result = http2_client_->start_stream(
            method,
            headers,
            [reader](std::vector<uint8_t> data) { reader->on_data(data); },
            [reader](std::vector<http2::http_header> hdrs) { reader->on_headers(hdrs); },
            [reader](int status) { reader->on_complete(status); });
        if (stream_result.is_err())
        {
            const auto& err = stream_result.error();
            return error<std::unique_ptr<grpc_client::server_stream_reader>>(
                err.code, err.message, "grpc::client", get_error_details(err));
        }
        // Send the request with gRPC framing
        grpc_message request_msg{std::vector<uint8_t>(request)};
        auto serialized = request_msg.serialize();
        auto write_result = http2_client_->write_stream(stream_result.value(), serialized, true);
        if (write_result.is_err())
        {
            const auto& err = write_result.error();
            return error<std::unique_ptr<grpc_client::server_stream_reader>>(
                err.code, err.message, "grpc::client", get_error_details(err));
        }
        // Return the reader wrapped in a shared_ptr-owning unique_ptr wrapper
        // Use a custom deleter that captures the shared_ptr to extend lifetime
        struct shared_holder : public grpc_client::server_stream_reader {
            std::shared_ptr<server_stream_reader_impl> impl;
            explicit shared_holder(std::shared_ptr<server_stream_reader_impl> p) : impl(std::move(p)) {}
            auto read() -> Result<grpc_message> override { return impl->read(); }
            auto has_more() const -> bool override { return impl->has_more(); }
            auto finish() -> grpc_status override { return impl->finish(); }
        };
        return ok(std::unique_ptr<grpc_client::server_stream_reader>(
            new shared_holder(reader)));
    }
References kcenon::network::error_codes::network_system::connection_failed, kcenon::network::protocols::grpc::compression::deflate, kcenon::network::error, kcenon::network::protocols::grpc::format_timeout(), kcenon::network::get_error_details(), kcenon::network::protocols::grpc::grpc_content_type, kcenon::network::protocols::grpc::compression::gzip, http2_client_, kcenon::network::protocols::grpc::compression::identity, kcenon::network::error_codes::common_errors::invalid_argument, is_connected(), kcenon::network::protocols::grpc::ok, and kcenon::network::protocols::grpc::grpc_message::serialize().
target()
auto kcenon::network::protocols::grpc::grpc_client::impl::target () const -> const std::string& inline
Definition at line 1141 of file client.cpp.
    {
        return target_;
    }
References target_.
Referenced by kcenon::network::protocols::grpc::grpc_client::target().
wait_for_connected()
auto kcenon::network::protocols::grpc::grpc_client::impl::wait_for_connected (std::chrono::milliseconds timeout) -> bool inline
Definition at line 1125 of file client.cpp.
    {
        auto deadline = std::chrono::steady_clock::now() + timeout;
        while (std::chrono::steady_clock::now() < deadline)
        {
            if (is_connected())
            {
                return true;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
        }
        return is_connected();
    }
References is_connected().
Member Data Documentation
config_
grpc_channel_config kcenon::network::protocols::grpc::grpc_client::impl::config_ private
Definition at line 1619 of file client.cpp.
Referenced by connect().
connected_
std::atomic<bool> kcenon::network::protocols::grpc::grpc_client::impl::connected_ private
Definition at line 1621 of file client.cpp.
Referenced by connect(), disconnect(), and is_connected().
host_
std::string kcenon::network::protocols::grpc::grpc_client::impl::host_ private
Definition at line 1618 of file client.cpp.
Referenced by connect().
http2_client_
std::shared_ptr<http2::http2_client> kcenon::network::protocols::grpc::grpc_client::impl::http2_client_ private
Definition at line 1620 of file client.cpp.
Referenced by bidi_stream_raw(), call_raw(), client_stream_raw(), connect(), disconnect(), is_connected(), and server_stream_raw().
mutex_
std::mutex kcenon::network::protocols::grpc::grpc_client::impl::mutex_ mutable private
Definition at line 1622 of file client.cpp.
Referenced by connect(), and disconnect().
target_
std::string kcenon::network::protocols::grpc::grpc_client::impl::target_ private
Definition at line 1617 of file client.cpp.
Referenced by call_raw(), connect(), and target().
The documentation for this class was generated from the following file:
src/protocols/grpc/client.cpp