Network System: kcenon::network::unified::adapters::udp_connection_adapter Class Reference
kcenon::network::unified::adapters::udp_connection_adapter Class Reference
Adapter that wraps messaging_udp_client to implement i_connection.
#include <udp_connection_adapter.h>
Public Member Functions
udp_connection_adapter (std::string_view connection_id)
Constructs an adapter with a unique connection ID.
~udp_connection_adapter () override
Destructor ensures proper cleanup.
udp_connection_adapter (const udp_connection_adapter &)=delete
udp_connection_adapter & operator= (const udp_connection_adapter &)=delete
udp_connection_adapter (udp_connection_adapter &&)=delete
udp_connection_adapter & operator= (udp_connection_adapter &&)=delete
auto send (std::span< const std::byte > data) -> VoidResult override
Sends raw data to the remote endpoint.
auto send (std::vector< uint8_t > &&data) -> VoidResult override
Sends data from a uint8_t vector.
auto is_connected () const noexcept -> bool override
Checks if the transport is currently connected.
auto id () const noexcept -> std::string_view override
Gets the unique identifier for this transport/connection.
auto remote_endpoint () const noexcept -> endpoint_info override
Gets the remote endpoint information.
auto local_endpoint () const noexcept -> endpoint_info override
Gets the local endpoint information.
auto connect (const endpoint_info &endpoint) -> VoidResult override
Connects to a remote endpoint using host/port.
auto connect (std::string_view url) -> VoidResult override
Connects to a remote endpoint using URL.
auto close () noexcept -> void override
Closes the connection gracefully.
auto set_callbacks (connection_callbacks callbacks) -> void override
Sets all connection callbacks at once.
auto set_options (connection_options options) -> void override
Sets connection options.
auto set_timeout (std::chrono::milliseconds timeout) -> void override
Sets the connection timeout.
auto is_connecting () const noexcept -> bool override
Checks if the connection is in the process of connecting.
auto wait_for_stop () -> void override
Blocks until the component has stopped.
Public Member Functions inherited from kcenon::network::unified::i_connection
~i_connection () override=default
Virtual destructor.
i_connection (const i_connection &)=delete
i_connection & operator= (const i_connection &)=delete
i_connection (i_connection &&)=default
i_connection & operator= (i_connection &&)=default
Public Member Functions inherited from kcenon::network::unified::i_transport
virtual ~i_transport ()=default
Virtual destructor for proper cleanup of derived classes.
i_transport (const i_transport &)=delete
i_transport & operator= (const i_transport &)=delete
i_transport (i_transport &&)=default
i_transport & operator= (i_transport &&)=default
Private Member Functions
auto setup_internal_callbacks () -> void
Sets up internal callbacks to bridge to unified callbacks.
Private Attributes
std::string connection_id_
std::shared_ptr< core::messaging_udp_client > client_
std::mutex callbacks_mutex_
connection_callbacks callbacks_
std::mutex endpoint_mutex_
endpoint_info remote_endpoint_
endpoint_info local_endpoint_
std::atomic< bool > is_connecting_ {false}
connection_options options_
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::unified::i_connection
i_connection ()=default
Default constructor (only for derived classes)
Protected Member Functions inherited from kcenon::network::unified::i_transport
i_transport ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps messaging_udp_client to implement i_connection.
This adapter bridges the existing UDP client implementation with the new unified interface. Note that UDP is connectionless - "connect" simply sets the target endpoint, and the connection is considered "connected" when the client is running.
Thread Safety
Thread-safe. All methods can be called from any thread.
Ownership
The adapter owns the underlying client via shared_ptr for proper RAII.
UDP Semantics
connect() sets target endpoint and starts the client
is_connected() returns true when client is running
send() sends datagrams to the configured target endpoint
Data arrives via on_data callback
Definition at line 38 of file udp_connection_adapter.h.
Constructor & Destructor Documentation
udp_connection_adapter() [1/3]
kcenon::network::unified::adapters::udp_connection_adapter::udp_connection_adapter (std::string_view connection_id) explicit
Constructs an adapter with a unique connection ID.
Parameters
connection_id Unique identifier for this connection
Definition at line 12 of file udp_connection_adapter.cpp.
    : connection_id_(connection_id)
    , client_(std::make_shared<core::messaging_udp_client>(connection_id))
{
    setup_internal_callbacks();
}
References setup_internal_callbacks().
~udp_connection_adapter()
kcenon::network::unified::adapters::udp_connection_adapter::~udp_connection_adapter () override
Destructor ensures proper cleanup.
Definition at line 19 of file udp_connection_adapter.cpp.
{
    close();
}
References close().
udp_connection_adapter() [2/3]
kcenon::network::unified::adapters::udp_connection_adapter::udp_connection_adapter (const udp_connection_adapter &) delete
udp_connection_adapter() [3/3]
kcenon::network::unified::adapters::udp_connection_adapter::udp_connection_adapter (udp_connection_adapter &&) delete
Member Function Documentation
close()
auto kcenon::network::unified::adapters::udp_connection_adapter::close () -> void override virtual noexcept
Closes the connection gracefully.
Behavior
Initiates graceful shutdown
Pending sends may be completed before close
Triggers on_disconnected callback when fully closed
Thread Safety
Thread-safe. Safe to call multiple times.
Note
After close(), is_connected() returns false and send() returns error.
Implements kcenon::network::unified::i_connection.
Definition at line 148 of file udp_connection_adapter.cpp.
{
    if (client_ && client_->is_running()) {
        (void)client_->stop_client();
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_disconnected) {
            callbacks_.on_disconnected();
        }
    }
    is_connecting_ = false;
}
References callbacks_, callbacks_mutex_, client_, is_connecting_, and kcenon::network::unified::connection_callbacks::on_disconnected.
Referenced by ~udp_connection_adapter().
connect() [1/2]
auto kcenon::network::unified::adapters::udp_connection_adapter::connect (const endpoint_info & endpoint) -> VoidResult nodiscard override virtual
Connects to a remote endpoint using host/port.
Parameters
endpoint The remote endpoint to connect to
Returns
VoidResult indicating success or failure
Behavior
Initiates connection to the specified endpoint
May block until connection is established (sync mode)
May return immediately and notify via callback (async mode)
Error Conditions
Returns error if already connected
Returns error if connection fails
Returns error if host resolution fails
Returns error if connection timeout expires
Thread Safety
Thread-safe. Only one connect operation can succeed at a time.
Implements kcenon::network::unified::i_connection.
Definition at line 74 of file udp_connection_adapter.cpp.
{
    if (!client_) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "Client is not initialized"
        );
    }
    if (client_->is_running()) {
        return error_void(
            static_cast<int>(std::errc::already_connected),
            "Already running"
        );
    }
    {
        std::lock_guard lock(endpoint_mutex_);
        remote_endpoint_ = endpoint;
    }
    is_connecting_ = true;
    auto result = client_->start_client(endpoint.host, endpoint.port);
    if (result.is_ok()) {
        is_connecting_ = false;
        // For UDP, we're immediately "connected" once started
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_connected) {
            callbacks_.on_connected();
        }
    } else {
        is_connecting_ = false;
    }
    return result;
}
References kcenon::network::error_void().
connect() [2/2]
auto kcenon::network::unified::adapters::udp_connection_adapter::connect (std::string_view url) -> VoidResult nodiscard override virtual
Connects to a remote endpoint using URL.
Parameters
url The URL to connect to (e.g., "wss://example.com/ws")
Returns
VoidResult indicating success or failure
This overload is primarily for URL-based protocols like WebSocket and HTTP. For socket-based protocols, use the endpoint_info overload.
Error Conditions
Same as connect(endpoint_info) plus:
Returns error if URL is malformed
Returns error if protocol is not supported
Implements kcenon::network::unified::i_connection.
Definition at line 112 of file udp_connection_adapter.cpp.
{
    // Parse URL for UDP: expect format "udp://host:port" or just "host:port"
    std::string url_str(url);
    // Remove udp:// prefix if present
    const std::string udp_prefix = "udp://";
    if (url_str.substr(0, udp_prefix.size()) == udp_prefix) {
        url_str = url_str.substr(udp_prefix.size());
    }
    // Find the last colon for port separation
    auto colon_pos = url_str.rfind(':');
    if (colon_pos == std::string::npos) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "URL must contain port number (format: host:port)"
        );
    }
    std::string host = url_str.substr(0, colon_pos);
    std::string port_str = url_str.substr(colon_pos + 1);
    uint16_t port = 0;
    try {
        port = static_cast<uint16_t>(std::stoi(port_str));
    } catch (...) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "Invalid port number in URL"
        );
    }
    return connect(endpoint_info{host, port});
}
References kcenon::network::error_void().
id()
auto kcenon::network::unified::adapters::udp_connection_adapter::id () const -> std::string_view nodiscard override virtual noexcept
Gets the unique identifier for this transport/connection.
Returns
A string view of the transport ID
The ID is unique within the application and remains constant for the lifetime of the transport instance.
Implements kcenon::network::unified::i_transport.
Definition at line 57 of file udp_connection_adapter.cpp.
{
    return connection_id_;
}
References connection_id_.
is_connected()
auto kcenon::network::unified::adapters::udp_connection_adapter::is_connected () const -> bool nodiscard override virtual noexcept
Checks if the transport is currently connected.
Returns
true if connected and ready to send/receive, false otherwise
Thread Safety
Thread-safe. Uses atomic operations internally.
Note
A false return may indicate:
Connection not yet established
Connection closed by remote peer
Connection closed locally
Network error occurred
Implements kcenon::network::unified::i_transport.
Definition at line 51 of file udp_connection_adapter.cpp.
{
    // For UDP, "connected" means the client is running with a target endpoint
    return client_ && client_->is_running();
}
References client_.
is_connecting()
auto kcenon::network::unified::adapters::udp_connection_adapter::is_connecting () const -> bool nodiscard override virtual noexcept
Checks if the connection is in the process of connecting.
Returns
true if connect() was called but not yet completed
Implements kcenon::network::unified::i_connection.
Definition at line 182 of file udp_connection_adapter.cpp.
{
    return is_connecting_.load();
}
References is_connecting_.
local_endpoint()
auto kcenon::network::unified::adapters::udp_connection_adapter::local_endpoint () const -> endpoint_info nodiscard override virtual noexcept
Gets the local endpoint information.
Returns
endpoint_info of the local side
Returns valid information only when connected/listening. Returns empty endpoint_info if not bound.
Implements kcenon::network::unified::i_transport.
Definition at line 68 of file udp_connection_adapter.cpp.
{
    std::lock_guard lock(endpoint_mutex_);
    return local_endpoint_;
}
References endpoint_mutex_, and local_endpoint_.
operator=() [1/2]
udp_connection_adapter & kcenon::network::unified::adapters::udp_connection_adapter::operator= (const udp_connection_adapter &) delete
operator=() [2/2]
udp_connection_adapter & kcenon::network::unified::adapters::udp_connection_adapter::operator= (udp_connection_adapter &&) delete
remote_endpoint()
auto kcenon::network::unified::adapters::udp_connection_adapter::remote_endpoint () const -> endpoint_info nodiscard override virtual noexcept
Gets the remote endpoint information.
Returns
endpoint_info of the remote peer
Returns valid information only when connected. Returns empty endpoint_info if not connected.
Implements kcenon::network::unified::i_transport.
Definition at line 62 of file udp_connection_adapter.cpp.
{
    std::lock_guard lock(endpoint_mutex_);
    return remote_endpoint_;
}
References endpoint_mutex_, and remote_endpoint_.
send() [1/2]
auto kcenon::network::unified::adapters::udp_connection_adapter::send (std::span< const std::byte > data) -> VoidResult nodiscard override virtual
Sends raw data to the remote endpoint.
Parameters
data The data to send as a span of bytes
Returns
VoidResult indicating success or failure
Error Conditions
Returns error if not connected
Returns error if send operation fails
Returns error if data size exceeds protocol limits
Thread Safety
Thread-safe. Multiple sends may be queued internally.
Performance Note
Data is typically copied to an internal send buffer. For zero-copy sends, see protocol-specific implementations.
Implements kcenon::network::unified::i_transport.
Definition at line 24 of file udp_connection_adapter.cpp.
{
    if (!client_ || !client_->is_running()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "UDP client is not running"
        );
    }
    std::vector<uint8_t> buffer(data.size());
    std::memcpy(buffer.data(), data.data(), data.size());
    return client_->send(std::move(buffer));
}
References kcenon::network::error_void().
send() [2/2]
auto kcenon::network::unified::adapters::udp_connection_adapter::send (std::vector< uint8_t > && data) -> VoidResult nodiscard override virtual
Sends data from a uint8_t vector.
Parameters
data The data to send as a vector of uint8_t
Returns
VoidResult indicating success or failure
Convenience overload for compatibility with existing code using std::vector<uint8_t>.
Implements kcenon::network::unified::i_transport.
Definition at line 39 of file udp_connection_adapter.cpp.
{
    if (!client_ || !client_->is_running()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "UDP client is not running"
        );
    }
    return client_->send(std::move(data));
}
References kcenon::network::error_void().
set_callbacks()
auto kcenon::network::unified::adapters::udp_connection_adapter::set_callbacks (connection_callbacks callbacks) -> void override virtual
Sets all connection callbacks at once.
Parameters
callbacks The callback structure with handlers
Replaces all previously set callbacks. Empty callback functions in the structure will clear the corresponding handler.
Thread Safety
Thread-safe, but callbacks may be invoked from I/O threads.
Implements kcenon::network::unified::i_connection.
Definition at line 161 of file udp_connection_adapter.cpp.
{
    {
        std::lock_guard lock(callbacks_mutex_);
        callbacks_ = std::move(callbacks);
    }
    // Re-setup internal callbacks to use the new user callbacks
    setup_internal_callbacks();
}
set_options()
auto kcenon::network::unified::adapters::udp_connection_adapter::set_options (connection_options options) -> void override virtual
Sets connection options.
Parameters
options The configuration options
Some options may only be effective before connect() is called.
Thread Safety
Thread-safe. Changes may not affect in-flight operations.
Implements kcenon::network::unified::i_connection.
Definition at line 172 of file udp_connection_adapter.cpp.
{
    options_ = options;
}
set_timeout()
auto kcenon::network::unified::adapters::udp_connection_adapter::set_timeout (std::chrono::milliseconds timeout) -> void override virtual
Sets the connection timeout.
Parameters
timeout Timeout duration (0 = no timeout)
Shorthand for setting just the connect_timeout option.
Implements kcenon::network::unified::i_connection.
Definition at line 177 of file udp_connection_adapter.cpp.
{
    options_.connect_timeout = timeout;
}
setup_internal_callbacks()
auto kcenon::network::unified::adapters::udp_connection_adapter::setup_internal_callbacks () -> void private
Sets up internal callbacks to bridge to unified callbacks.
Definition at line 194 of file udp_connection_adapter.cpp.
{
    if (!client_) {
        return;
    }
    // Bridge receive callback
    client_->set_receive_callback(
        [this](const std::vector<uint8_t>& data,
               const interfaces::i_udp_client::endpoint_info& sender) {
            // Update local endpoint information if we receive from the expected target
            {
                std::lock_guard ep_lock(endpoint_mutex_);
                // Note: local_endpoint_ would require socket info which isn't easily available
            }
            std::lock_guard lock(callbacks_mutex_);
            if (callbacks_.on_data) {
                std::span<const std::byte> byte_span(
                    reinterpret_cast<const std::byte*>(data.data()),
                    data.size()
                );
                callbacks_.on_data(byte_span);
            }
        });
    // Bridge error callback
    client_->set_error_callback([this](std::error_code ec) {
        is_connecting_ = false;
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_error) {
            callbacks_.on_error(ec);
        }
    });
}
Referenced by udp_connection_adapter().
wait_for_stop()
auto kcenon::network::unified::adapters::udp_connection_adapter::wait_for_stop () -> void override virtual
Blocks until the component has stopped.
Waits for all pending operations to complete and the connection to be fully closed.
Thread Safety
Safe to call from any thread. Uses internal synchronization.
Implements kcenon::network::unified::i_connection.
Definition at line 187 of file udp_connection_adapter.cpp.
{
    if (client_) {
        client_->wait_for_stop();
    }
}
Member Data Documentation
callbacks_
connection_callbacks kcenon::network::unified::adapters::udp_connection_adapter::callbacks_ private
Definition at line 91 of file udp_connection_adapter.h.
Referenced by close().
callbacks_mutex_
std::mutex kcenon::network::unified::adapters::udp_connection_adapter::callbacks_mutex_ mutable private
Definition at line 90 of file udp_connection_adapter.h.
Referenced by close().
client_
std::shared_ptr<core::messaging_udp_client> kcenon::network::unified::adapters::udp_connection_adapter::client_ private
Definition at line 88 of file udp_connection_adapter.h.
Referenced by close(), and is_connected().
connection_id_
std::string kcenon::network::unified::adapters::udp_connection_adapter::connection_id_ private
Definition at line 87 of file udp_connection_adapter.h.
Referenced by id().
endpoint_mutex_
std::mutex kcenon::network::unified::adapters::udp_connection_adapter::endpoint_mutex_ mutable private
Definition at line 93 of file udp_connection_adapter.h.
Referenced by local_endpoint(), and remote_endpoint().
is_connecting_
std::atomic<bool> kcenon::network::unified::adapters::udp_connection_adapter::is_connecting_ {false} private
Definition at line 97 of file udp_connection_adapter.h.
{false};
Referenced by close(), and is_connecting().
local_endpoint_
endpoint_info kcenon::network::unified::adapters::udp_connection_adapter::local_endpoint_ private
Definition at line 95 of file udp_connection_adapter.h.
Referenced by local_endpoint().
options_
connection_options kcenon::network::unified::adapters::udp_connection_adapter::options_ private
Definition at line 98 of file udp_connection_adapter.h.
remote_endpoint_
endpoint_info kcenon::network::unified::adapters::udp_connection_adapter::remote_endpoint_ private
Definition at line 94 of file udp_connection_adapter.h.
Referenced by remote_endpoint().
The documentation for this class was generated from the following files:
src/internal/unified/adapters/udp_connection_adapter.h
src/unified/adapters/udp_connection_adapter.cpp