Network System: kcenon::network::internal::adapters::http_client_adapter Class Reference
kcenon::network::internal::adapters::http_client_adapter Class Reference
Adapter that wraps http_client to implement i_protocol_client.
#include <http_client_adapter.h>
Public Member Functions
http_client_adapter (std::string_view client_id, std::chrono::milliseconds timeout=std::chrono::seconds(30))
Constructs an adapter with timeout configuration.
~http_client_adapter () override
Destructor ensures proper cleanup.
http_client_adapter (const http_client_adapter &)=delete
http_client_adapter & operator= (const http_client_adapter &)=delete
http_client_adapter (http_client_adapter &&)=delete
http_client_adapter & operator= (http_client_adapter &&)=delete
auto set_path (std::string_view path) -> void
Sets the HTTP path for requests.
auto set_use_ssl (bool use_ssl) -> void
Sets whether to use HTTPS.
auto is_running () const -> bool override
Checks if the component is currently running.
auto wait_for_stop () -> void override
Blocks until the component has stopped.
auto start (std::string_view host, uint16_t port) -> VoidResult override
Starts the client and connects to the specified server.
auto stop () -> VoidResult override
Stops the client and closes the connection.
auto send (std::vector< uint8_t > &&data) -> VoidResult override
Sends data to the connected server.
auto is_connected () const -> bool override
Checks if the client is connected to the server.
auto set_observer (std::shared_ptr< interfaces::connection_observer > observer) -> void override
Sets the connection observer for unified event handling.
auto set_receive_callback (receive_callback_t callback) -> void override
Sets the callback for received data.
auto set_connected_callback (connected_callback_t callback) -> void override
Sets the callback for connection established.
auto set_disconnected_callback (disconnected_callback_t callback) -> void override
Sets the callback for disconnection.
auto set_error_callback (error_callback_t callback) -> void override
Sets the callback for errors.
Public Member Functions inherited from kcenon::network::interfaces::i_protocol_client
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Member Functions
auto build_url () const -> std::string
Builds the full URL from stored components.
auto notify_receive (const std::vector< uint8_t > &data) -> void
Notifies observers/callbacks of received data.
auto notify_error (std::error_code ec) -> void
Notifies observers/callbacks of errors.
Private Attributes
std::string client_id_
std::chrono::milliseconds timeout_
std::shared_ptr< core::http_client > client_
std::string host_
uint16_t port_ {0}
std::string path_ {"/"}
bool use_ssl_ {false}
std::atomic< bool > is_running_ {false}
std::mutex callbacks_mutex_
std::shared_ptr< interfaces::connection_observer > observer_
receive_callback_t receive_callback_
connected_callback_t connected_callback_
disconnected_callback_t disconnected_callback_
error_callback_t error_callback_
Additional Inherited Members
Public Types inherited from kcenon::network::interfaces::i_protocol_client
using receive_callback_t = std::function<void(const std::vector<uint8_t>&)>
Callback type for received data.
using connected_callback_t = std::function<void()>
Callback type for connection established.
using disconnected_callback_t = std::function<void()>
Callback type for disconnection.
using error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps http_client to implement i_protocol_client.
This adapter bridges the HTTP client implementation with the unified i_protocol_client interface. It allows http_facade to return i_protocol_client without modifying the existing http_client class.
Design Rationale
The adapter pattern is used because:
HTTP uses request/response paradigm vs streaming i_protocol_client interface
HTTP is stateless while i_protocol_client assumes connection state
HTTP operations (GET, POST, etc.) don't map directly to send()
Connection Semantics
Since HTTP is stateless:
start(host, port) stores the base URL for subsequent requests
is_connected() returns true when base URL is configured
send() performs an HTTP POST request with binary data
Received response body is delivered via receive callback
Path Handling
The path is configured via set_path() before sending
Default path is "/" if not configured
Each send() uses the configured path
Thread Safety
Thread-safe. All methods can be called from any thread.
See also
i_protocol_client
http_client
Definition at line 53 of file http_client_adapter.h.
Constructor & Destructor Documentation
http_client_adapter() [1/3]
kcenon::network::internal::adapters::http_client_adapter::http_client_adapter (std::string_view client_id, std::chrono::milliseconds timeout = std::chrono::seconds(30)) explicit
Constructs an adapter with timeout configuration.
Parameters
client_id Unique identifier for this client
timeout Request timeout (default: 30 seconds)
Definition at line 19 of file http_client_adapter.cpp.
    : client_id_(client_id)
    , timeout_(timeout)
    , client_(std::make_shared<core::http_client>(timeout))
{
}
~http_client_adapter()
kcenon::network::internal::adapters::http_client_adapter::~http_client_adapter () override
Destructor ensures proper cleanup.
Definition at line 28 of file http_client_adapter.cpp.
{
    is_running_.store(false, std::memory_order_release);
}
References is_running_.
http_client_adapter() [2/3]
kcenon::network::internal::adapters::http_client_adapter::http_client_adapter (const http_client_adapter &) delete
http_client_adapter() [3/3]
kcenon::network::internal::adapters::http_client_adapter::http_client_adapter (http_client_adapter &&) delete
Member Function Documentation
build_url()
auto kcenon::network::internal::adapters::http_client_adapter::build_url () const -> std::string nodiscard private
Builds the full URL from stored components.
Definition at line 221 of file http_client_adapter.cpp.
{
    std::ostringstream oss;
    oss << (use_ssl_ ? "https://" : "http://")
        << host_ << ":" << port_ << path_;
    return oss.str();
}
References host_, path_, port_, and use_ssl_.
is_connected()
auto kcenon::network::internal::adapters::http_client_adapter::is_connected () const -> bool nodiscard override virtual
Checks if the client is connected to the server.
Returns
true if connected, false otherwise.
Connection States
Not started: is_running() == false, is_connected() == false
Starting/Connecting: is_running() == true, is_connected() == false
Connected: is_running() == true, is_connected() == true
Disconnected: is_running() == true, is_connected() == false
Stopped: is_running() == false, is_connected() == false
Protocol-Specific Notes
TCP/WebSocket/QUIC: Returns true only when connection is established
UDP: Returns true when target endpoint is set (no actual "connection")
HTTP: Returns true if connection pool has active connections
Thread Safety
Thread-safe. Uses atomic operations for state checking.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 182 of file http_client_adapter.cpp.
{
    return is_running_.load(std::memory_order_acquire) && !host_.empty();
}
References host_, and is_running_.
is_running()
auto kcenon::network::internal::adapters::http_client_adapter::is_running () const -> bool nodiscard override virtual
Checks if the component is currently running.
Returns
true if the component is active, false otherwise.
This method must be thread-safe and use atomic operations for the running state.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 51 of file http_client_adapter.cpp.
{
    return is_running_.load(std::memory_order_acquire);
}
References is_running_.
notify_error()
auto kcenon::network::internal::adapters::http_client_adapter::notify_error (std::error_code ec) -> void private
Notifies observers/callbacks of errors.
Definition at line 249 of file http_client_adapter.cpp.
{
    std::shared_ptr<interfaces::connection_observer> observer_copy;
    error_callback_t callback_copy;
    {
        std::lock_guard<std::mutex> lock(callbacks_mutex_);
        observer_copy = observer_;
        callback_copy = error_callback_;
    }
    if (observer_copy)
    {
        observer_copy->on_error(ec);
    }
    if (callback_copy)
    {
        callback_copy(ec);
    }
}
notify_receive()
auto kcenon::network::internal::adapters::http_client_adapter::notify_receive (const std::vector< uint8_t > & data) -> void private
Notifies observers/callbacks of received data.
Definition at line 229 of file http_client_adapter.cpp.
{
    std::shared_ptr<interfaces::connection_observer> observer_copy;
    receive_callback_t callback_copy;
    {
        std::lock_guard<std::mutex> lock(callbacks_mutex_);
        observer_copy = observer_;
        callback_copy = receive_callback_;
    }
    if (observer_copy)
    {
        observer_copy->on_receive(data);
    }
    if (callback_copy)
    {
        callback_copy(data);
    }
}
operator=() [1/2]
http_client_adapter & kcenon::network::internal::adapters::http_client_adapter::operator= (const http_client_adapter &) delete
operator=() [2/2]
http_client_adapter & kcenon::network::internal::adapters::http_client_adapter::operator= (http_client_adapter &&) delete
send()
auto kcenon::network::internal::adapters::http_client_adapter::send (std::vector< uint8_t > && data) -> VoidResult nodiscard override virtual
Sends data to the connected server.
Parameters
data The data to send.
Returns
VoidResult indicating success or failure.
Behavior
Queues data for transmission
May block if send queue is full (protocol-dependent)
Data is moved, not copied
Error Conditions
Returns error if not connected
Returns error if send buffer is full
Returns error if underlying protocol send fails
Protocol-Specific Notes
TCP: Stream-based, may fragment data
UDP: Datagram-based, preserves message boundaries
WebSocket: Frame-based, preserves message boundaries
HTTP: Typically request/response, may queue
Thread Safety
Thread-safe. Multiple sends may be queued concurrently. Send operations are serialized internally.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 140 of file http_client_adapter.cpp.
{
    if (!client_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Client not initialized",
            "http_client_adapter::send"
        );
    }
    if (!is_running_.load(std::memory_order_acquire))
    {
        return error_void(
            error_codes::common_errors::invalid_argument,
            "Client is not running - call start() first",
            "http_client_adapter::send"
        );
    }
    // Build the full URL
    const std::string url = build_url();
    // Perform HTTP POST request with the binary data
    auto result = client_->post(url, data);
    if (result.is_err())
    {
        notify_error(std::make_error_code(std::errc::io_error));
        return error_void(
            error_codes::common_errors::internal_error,
            "HTTP POST request failed: " + result.error().message,
            "http_client_adapter::send"
        );
    }
    // Notify receive callback with response body
    const auto& response = result.value();
    notify_receive(response.body);
    return ok();
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, kcenon::network::error_codes::common_errors::invalid_argument, and kcenon::network::ok().
set_connected_callback()
auto kcenon::network::internal::adapters::http_client_adapter::set_connected_callback (connected_callback_t callback) -> void override virtual
Sets the callback for connection established.
Parameters
callback The callback function.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 199 of file http_client_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    connected_callback_ = std::move(callback);
}
set_disconnected_callback()
auto kcenon::network::internal::adapters::http_client_adapter::set_disconnected_callback (disconnected_callback_t callback) -> void override virtual
Sets the callback for disconnection.
Parameters
callback The callback function.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 205 of file http_client_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    disconnected_callback_ = std::move(callback);
}
set_error_callback()
auto kcenon::network::internal::adapters::http_client_adapter::set_error_callback (error_callback_t callback) -> void override virtual
Sets the callback for errors.
Parameters
callback The callback function.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 211 of file http_client_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    error_callback_ = std::move(callback);
}
set_observer()
auto kcenon::network::internal::adapters::http_client_adapter::set_observer (std::shared_ptr< interfaces::connection_observer > observer) -> void override virtual
Sets the connection observer for unified event handling.
Parameters
observer The observer instance (shared ownership).
The observer receives all connection events through a single interface:
on_connected(): Connection established
on_disconnected(): Connection lost or closed
on_receive(data): Data received from server
on_error(error_code): Error occurred
Recommended Pattern
This is the preferred method for event handling as it:
Centralizes all event handling in one place
Provides consistent interface across all protocols
Enables easier testing through mock observers
Usage
class my_observer : public connection_observer {
    void on_connected() override { // handle connect
    }
    void on_receive(const std::vector<uint8_t>& data) override {
        // handle data
    }
    // ... implement other methods
};
client->set_observer(std::make_shared<my_observer>());
Thread Safety
Thread-safe. Observer methods may be invoked from I/O threads. Observer must be thread-safe if shared across multiple clients.
See also
connection_observer
callback_adapter
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 187 of file http_client_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    observer_ = std::move(observer);
}
set_path()
auto kcenon::network::internal::adapters::http_client_adapter::set_path (std::string_view path) -> void
Sets the HTTP path for requests.
Parameters
path The HTTP path (e.g., "/api/data", "/submit")
Can be changed between send() calls to target different endpoints. Default path is "/" if not set.
Definition at line 37 of file http_client_adapter.cpp.
{
    path_ = std::string(path);
}
set_receive_callback()
auto kcenon::network::internal::adapters::http_client_adapter::set_receive_callback (receive_callback_t callback) -> void override virtual
Sets the callback for received data.
Parameters
callback The callback function.
Thread Safety
Thread-safe. The callback may be invoked from I/O threads. Callback must be thread-safe if it accesses shared state.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 193 of file http_client_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    receive_callback_ = std::move(callback);
}
set_use_ssl()
auto kcenon::network::internal::adapters::http_client_adapter::set_use_ssl (bool use_ssl) -> void
Sets whether to use HTTPS.
Parameters
use_ssl true for HTTPS, false for HTTP
Must be called before start() or between connections. Default is false (HTTP).
Definition at line 42 of file http_client_adapter.cpp.
{
    use_ssl_ = use_ssl;
}
start()
auto kcenon::network::internal::adapters::http_client_adapter::start (std::string_view host, uint16_t port) -> VoidResult nodiscard override virtual
Starts the client and connects to the specified server.
Parameters
host The server hostname or IP address.
port The server port number.
Returns
VoidResult indicating success or failure.
Behavior
Creates the underlying protocol-specific connection
Resolves hostname to IP address if needed
Establishes connection with the server
Begins receiving data (for connection-oriented protocols)
Invokes connected callback/observer on success
Error Conditions
Returns error if already running
Returns error if host resolution fails
Returns error if connection establishment fails
Returns error if underlying protocol initialization fails
Protocol-Specific Notes
TCP/WebSocket/QUIC: Establishes stateful connection
UDP: Sets default target endpoint, does not "connect" in traditional sense
HTTP: May establish connection pool or persistent connection
Thread Safety
Thread-safe. Only one start operation can succeed at a time. Subsequent calls while running will return an error.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 65 of file http_client_adapter.cpp.
{
    if (!client_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Client not initialized",
            "http_client_adapter::start"
        );
    }
    // Store the connection details for building URLs
    host_ = std::string(host);
    port_ = port;
    is_running_.store(true, std::memory_order_release);
    // Notify connected callback (HTTP is "connected" when we have a target)
    {
        std::shared_ptr<interfaces::connection_observer> observer_copy;
        connected_callback_t callback_copy;
        {
            std::lock_guard<std::mutex> lock(callbacks_mutex_);
            observer_copy = observer_;
            callback_copy = connected_callback_;
        }
        if (observer_copy)
        {
            observer_copy->on_connected();
        }
        if (callback_copy)
        {
            callback_copy();
        }
    }
    return ok();
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, and kcenon::network::ok().
stop()
auto kcenon::network::internal::adapters::http_client_adapter::stop () -> VoidResult nodiscard override virtual
Stops the client and closes the connection.
Returns
VoidResult indicating success or failure.
Behavior
Cancels all pending operations
Closes the connection gracefully if possible
Invokes disconnected callback/observer
Releases protocol-specific resources
Error Conditions
Returns error if not running
Protocol-Specific Notes
TCP: Sends FIN, waits for graceful close
WebSocket: Sends close frame with status code
UDP: Stops receiving, no "close" required
QUIC: Sends CONNECTION_CLOSE frame
Thread Safety
Thread-safe. Safe to call from any thread including callbacks. Pending operations will be cancelled and cleaned up.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 104 of file http_client_adapter.cpp.
{
    if (!is_running_.load(std::memory_order_acquire))
    {
        return error_void(
            error_codes::common_errors::invalid_argument,
            "Client is not running",
            "http_client_adapter::stop"
        );
    }
    is_running_.store(false, std::memory_order_release);
    // Notify disconnected callback
    {
        std::shared_ptr<interfaces::connection_observer> observer_copy;
        disconnected_callback_t callback_copy;
        {
            std::lock_guard<std::mutex> lock(callbacks_mutex_);
            observer_copy = observer_;
            callback_copy = disconnected_callback_;
        }
        if (observer_copy)
        {
            observer_copy->on_disconnected();
        }
        if (callback_copy)
        {
            callback_copy();
        }
    }
    return ok();
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, and kcenon::network::ok().
wait_for_stop()
auto kcenon::network::internal::adapters::http_client_adapter::wait_for_stop () -> void override virtual
Blocks until the component has stopped.
This method should be used to synchronize shutdown operations. It returns immediately if the component is not running.
Thread Safety
Safe to call from any thread. Uses internal synchronization.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 56 of file http_client_adapter.cpp.
{
    // HTTP client is stateless, nothing to wait for
}
Member Data Documentation
callbacks_mutex_
std::mutex kcenon::network::internal::adapters::http_client_adapter::callbacks_mutex_ mutable private
Definition at line 148 of file http_client_adapter.h.
client_
std::shared_ptr<core::http_client> kcenon::network::internal::adapters::http_client_adapter::client_ private
Definition at line 138 of file http_client_adapter.h.
client_id_
std::string kcenon::network::internal::adapters::http_client_adapter::client_id_ private
Definition at line 136 of file http_client_adapter.h.
connected_callback_
connected_callback_t kcenon::network::internal::adapters::http_client_adapter::connected_callback_ private
Definition at line 151 of file http_client_adapter.h.
disconnected_callback_
disconnected_callback_t kcenon::network::internal::adapters::http_client_adapter::disconnected_callback_ private
Definition at line 152 of file http_client_adapter.h.
error_callback_
error_callback_t kcenon::network::internal::adapters::http_client_adapter::error_callback_ private
Definition at line 153 of file http_client_adapter.h.
host_
std::string kcenon::network::internal::adapters::http_client_adapter::host_ private
Definition at line 141 of file http_client_adapter.h.
Referenced by build_url(), and is_connected().
is_running_
std::atomic<bool> kcenon::network::internal::adapters::http_client_adapter::is_running_ {false} private
Definition at line 146 of file http_client_adapter.h.
{false};
Referenced by is_connected(), is_running(), and ~http_client_adapter().
observer_
std::shared_ptr<interfaces::connection_observer> kcenon::network::internal::adapters::http_client_adapter::observer_ private
Definition at line 149 of file http_client_adapter.h.
path_
std::string kcenon::network::internal::adapters::http_client_adapter::path_ {"/"} private
Definition at line 143 of file http_client_adapter.h.
{"/"};
Referenced by build_url().
port_
uint16_t kcenon::network::internal::adapters::http_client_adapter::port_ {0} private
Definition at line 142 of file http_client_adapter.h.
{0};
Referenced by build_url().
receive_callback_
receive_callback_t kcenon::network::internal::adapters::http_client_adapter::receive_callback_ private
Definition at line 150 of file http_client_adapter.h.
timeout_
std::chrono::milliseconds kcenon::network::internal::adapters::http_client_adapter::timeout_ private
Definition at line 137 of file http_client_adapter.h.
use_ssl_
bool kcenon::network::internal::adapters::http_client_adapter::use_ssl_ {false} private
Definition at line 144 of file http_client_adapter.h.
{false};
Referenced by build_url().
The documentation for this class was generated from the following files:
src/internal/adapters/http_client_adapter.h
src/adapters/http_client_adapter.cpp