Network System: kcenon::network::core::messaging_quic_server Class Reference
kcenon::network::core::messaging_quic_server Class Reference
A QUIC server that manages incoming client connections.
#include <quic_server.h>
Public Types
using connection_callback_t = std::function<void(std::shared_ptr<session::quic_session>)>
Callback type for new connections.
using disconnection_callback_t = std::function<void(std::shared_ptr<session::quic_session>)>
Callback type for disconnections.
using receive_callback_t
Callback type for received data (session, data)
using stream_receive_callback_t
Callback type for stream data (session, stream_id, data, fin)
using error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Public Types inherited from kcenon::network::interfaces::i_quic_server
using connection_callback_t = std::function<void(std::shared_ptr<i_quic_session>)>
Callback type for new connections.
using disconnection_callback_t = std::function<void(std::string_view)>
Callback type for disconnections (session_id)
using receive_callback_t = std::function<void(std::string_view, const std::vector<uint8_t>&)>
Callback type for default stream data (session_id, data)
using stream_callback_t
Callback type for stream data (session_id, stream_id, data, is_fin)
using error_callback_t = std::function<void(std::string_view, std::error_code)>
Callback type for errors (session_id, error)
Public Member Functions
messaging_quic_server (std::string_view server_id)
Constructs a QUIC server with a given identifier.
~messaging_quic_server () noexcept override
Destructor; automatically calls stop_server() if running.
messaging_quic_server (const messaging_quic_server &)=delete
messaging_quic_server & operator= (const messaging_quic_server &)=delete
messaging_quic_server (messaging_quic_server &&)=delete
messaging_quic_server & operator= (messaging_quic_server &&)=delete
auto start_server (unsigned short port) -> VoidResult
Start the server with default configuration.
auto start_server (unsigned short port, const quic_server_config &config) -> VoidResult
Start the server with TLS configuration.
auto stop_server () -> VoidResult
Stops the server and releases all resources.
auto server_id () const -> const std::string &
Returns the server identifier.
auto sessions () const -> std::vector< std::shared_ptr< session::quic_session > >
Get all active sessions.
auto get_session (const std::string &session_id) -> std::shared_ptr< session::quic_session >
Get a session by its ID.
auto session_count () const -> size_t
Get the number of active sessions.
auto disconnect_session (const std::string &session_id, uint64_t error_code=0) -> VoidResult
Disconnect a specific session.
auto disconnect_all (uint64_t error_code=0) -> void
Disconnect all active sessions.
auto broadcast (std::vector< uint8_t > &&data) -> VoidResult
Send data to all connected clients.
auto multicast (const std::vector< std::string > &session_ids, std::vector< uint8_t > &&data) -> VoidResult
Send data to specific sessions.
auto is_running () const -> bool override
Checks if the server is currently running.
auto wait_for_stop () -> void override
Blocks until stop() is called.
auto start (uint16_t port) -> VoidResult override
Starts the QUIC server on the specified port.
auto stop () -> VoidResult override
Stops the QUIC server.
auto connection_count () const -> size_t override
Gets the number of active QUIC connections (interface version).
auto set_connection_callback (interfaces::i_quic_server::connection_callback_t callback) -> void override
Sets the callback for new connections (interface version).
auto set_disconnection_callback (interfaces::i_quic_server::disconnection_callback_t callback) -> void override
Sets the callback for disconnections (interface version).
auto set_receive_callback (interfaces::i_quic_server::receive_callback_t callback) -> void override
Sets the callback for received data on default stream (interface version).
auto set_stream_callback (interfaces::i_quic_server::stream_callback_t callback) -> void override
Sets the callback for stream data (interface version).
auto set_error_callback (interfaces::i_quic_server::error_callback_t callback) -> void override
Sets the callback for errors (interface version).
auto set_connection_callback (connection_callback_t callback) -> void
Sets the callback for new connections (legacy version).
auto set_disconnection_callback (disconnection_callback_t callback) -> void
Sets the callback for disconnections (legacy version).
auto set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received data (legacy version).
auto set_stream_receive_callback (stream_receive_callback_t callback) -> void
Sets the callback for stream data reception (legacy version).
auto set_error_callback (error_callback_t callback) -> void
Sets the callback for errors (legacy version).
Public Member Functions inherited from kcenon::network::interfaces::i_quic_server
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Types
using callback_index = quic_server_callback
Callback index type alias for clarity.
using callbacks_t
Callback manager type for this server.
Private Member Functions
auto do_start_impl (unsigned short port) -> VoidResult
QUIC-specific implementation of server start.
auto do_stop_impl () -> VoidResult
QUIC-specific implementation of server stop.
auto start_receive () -> void
auto handle_packet (std::span< const uint8_t > data, const asio::ip::udp::endpoint &from) -> void
auto find_or_create_session (const protocols::quic::connection_id &dcid, const asio::ip::udp::endpoint &endpoint) -> std::shared_ptr< session::quic_session >
auto generate_session_id () -> std::string
auto on_session_close (const std::string &session_id) -> void
auto start_cleanup_timer () -> void
auto cleanup_dead_sessions () -> void
auto invoke_connection_callback (std::shared_ptr< session::quic_session > session) -> void
Invokes the connection callback.
auto invoke_disconnection_callback (std::shared_ptr< session::quic_session > session) -> void
Invokes the disconnection callback.
auto invoke_receive_callback (std::shared_ptr< session::quic_session > session, const std::vector< uint8_t > &data) -> void
Invokes the receive callback.
auto invoke_stream_receive_callback (std::shared_ptr< session::quic_session > session, uint64_t stream_id, const std::vector< uint8_t > &data, bool fin) -> void
Invokes the stream receive callback.
auto invoke_error_callback (std::error_code ec) -> void
Invokes the error callback.
Private Attributes
std::string server_id_
utils::lifecycle_manager lifecycle_
callbacks_t callbacks_
std::unique_ptr< asio::io_context > io_context_
std::unique_ptr< asio::executor_work_guard< asio::io_context::executor_type > > work_guard_
std::unique_ptr< asio::ip::udp::socket > udp_socket_
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::future< void > io_context_future_
quic_server_config config_
std::shared_mutex sessions_mutex_
std::map< std::string, std::shared_ptr< session::quic_session > > sessions_
std::array< uint8_t, 65536 > recv_buffer_
asio::ip::udp::endpoint recv_endpoint_
std::unique_ptr< asio::steady_timer > cleanup_timer_
std::atomic< uint64_t > session_counter_ {0}
interfaces::i_quic_server::error_callback_t interface_error_cb_
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
A QUIC server that manages incoming client connections.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling. It also implements the i_quic_server interface for composition-based usage.
Overview
Implements a QUIC (RFC 9000) server with an API consistent with the existing TCP-based messaging_server, while exposing QUIC-specific features like multiple concurrent streams and 0-RTT.
Thread Safety
All public methods are thread-safe.
Session map is protected by shared_mutex for concurrent read access.
Atomic flags prevent race conditions.
Callbacks are invoked on I/O threads; implementations should be safe.
Key Features
Uses asio::io_context for UDP I/O operations.
Manages multiple QUIC sessions concurrently.
Supports broadcast/multicast to connected clients.
Provides session lifecycle callbacks.
Interface Compliance
This class implements interfaces::i_quic_server for composition-based usage.
Comparison with messaging_server (TCP)
Feature messaging_server (TCP) messaging_quic_server
start_server() ✓ ✓
stop_server() ✓ ✓
broadcast() ✗ ✓
multicast() ✗ ✓
TLS configuration ✗ ✓ (required)
Session management Basic Advanced
Definition at line 142 of file quic_server.h.
Member Typedef Documentation
callback_index
using kcenon::network::core::messaging_quic_server::callback_index = quic_server_callback private
Callback index type alias for clarity.
Definition at line 491 of file quic_server.h.
callbacks_t
using kcenon::network::core::messaging_quic_server::callbacks_t private
Initial value:
 utils::callback_manager<
            connection_callback_t,
            disconnection_callback_t,
            receive_callback_t,
            stream_receive_callback_t,
            error_callback_t
        >
Callback manager type for this server.
Definition at line 494 of file quic_server.h.
connection_callback_t
using kcenon::network::core::messaging_quic_server::connection_callback_t = std::function<void(std::shared_ptr<session::quic_session>)>
Callback type for new connections.
Definition at line 148 of file quic_server.h.
disconnection_callback_t
using kcenon::network::core::messaging_quic_server::disconnection_callback_t = std::function<void(std::shared_ptr<session::quic_session>)>
Callback type for disconnections.
Definition at line 150 of file quic_server.h.
error_callback_t
using kcenon::network::core::messaging_quic_server::error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Definition at line 160 of file quic_server.h.
receive_callback_t
using kcenon::network::core::messaging_quic_server::receive_callback_t
Initial value:
 std::function<void(std::shared_ptr<session::quic_session>,
                                                       const std::vector<uint8_t>&)>
Callback type for received data (session, data)
Definition at line 152 of file quic_server.h.
stream_receive_callback_t
using kcenon::network::core::messaging_quic_server::stream_receive_callback_t
Initial value:
 std::function<void(std::shared_ptr<session::quic_session>,
                                                              uint64_t,
                                                              const std::vector<uint8_t>&,
                                                              bool)>
Callback type for stream data (session, stream_id, data, fin)
Definition at line 155 of file quic_server.h.
Constructor & Destructor Documentation
messaging_quic_server() [1/3]
kcenon::network::core::messaging_quic_server::messaging_quic_server (std::string_view server_id) explicit
Constructs a QUIC server with a given identifier.
Parameters
server_id A string identifier for logging/debugging.
Definition at line 22 of file quic_server.cpp.
    : server_id_(server_id)
{
}
~messaging_quic_server()
kcenon::network::core::messaging_quic_server::~messaging_quic_server () override noexcept
Destructor; automatically calls stop_server() if running.
Definition at line 27 of file quic_server.cpp.
{
    if (lifecycle_.is_running())
    {
        (void)stop_server(); // Ignore result in destructor
    }
}
References kcenon::network::utils::lifecycle_manager::is_running(), lifecycle_, and stop_server().
messaging_quic_server() [2/3]
kcenon::network::core::messaging_quic_server::messaging_quic_server (const messaging_quic_server &) delete
messaging_quic_server() [3/3]
kcenon::network::core::messaging_quic_server::messaging_quic_server (messaging_quic_server &&) delete
Member Function Documentation
broadcast()
auto kcenon::network::core::messaging_quic_server::broadcast (std::vector< uint8_t > && data) -> VoidResult nodiscard
Send data to all connected clients.
Parameters
data Data to broadcast (moved for efficiency).
Returns
VoidResult indicating success or error.
Definition at line 347 of file quic_server.cpp.
{
    auto sessions_list = sessions();
    for (auto& session : sessions_list)
    {
        if (session && session->is_active())
        {
            std::vector<uint8_t> data_copy(data);
            auto result = session->send(std::move(data_copy));
            if (result.is_err())
            {
                NETWORK_LOG_WARN("[messaging_quic_server] Failed to send to session "
                                 + session->session_id() + ": "
                                 + result.error().message);
            }
        }
    }
    return ok();
}
References NETWORK_LOG_WARN, and kcenon::network::ok().
cleanup_dead_sessions()
auto kcenon::network::core::messaging_quic_server::cleanup_dead_sessions () -> void private
Definition at line 671 of file quic_server.cpp.
{
    std::vector<std::string> dead_session_ids;
    {
        std::shared_lock<std::shared_mutex> lock(sessions_mutex_);
        for (const auto& [id, session] : sessions_)
        {
            if (!session || !session->is_active())
            {
                dead_session_ids.push_back(id);
            }
        }
    }
    for (const auto& id : dead_session_ids)
    {
        on_session_close(id);
    }
    if (!dead_session_ids.empty())
    {
        NETWORK_LOG_DEBUG(
            "[messaging_quic_server] Cleaned up "
            + std::to_string(dead_session_ids.size())
            + " dead sessions. Active: " + std::to_string(session_count()));
    }
}
References NETWORK_LOG_DEBUG.
connection_count()
auto kcenon::network::core::messaging_quic_server::connection_count () const -> size_t nodiscard override virtual
Gets the number of active QUIC connections (interface version).
Returns
The count of currently connected clients.
Implements i_quic_server::connection_count().
Implements kcenon::network::interfaces::i_quic_server.
Definition at line 114 of file quic_server.cpp.
{
    return session_count();
}
References session_count().
disconnect_all()
auto kcenon::network::core::messaging_quic_server::disconnect_all (uint64_t error_code = 0) -> void
Disconnect all active sessions.
Parameters
error_code Application error code (0 for no error).
Definition at line 324 of file quic_server.cpp.
{
    std::vector<std::shared_ptr<session::quic_session>> sessions_to_close;
    {
        std::unique_lock<std::shared_mutex> lock(sessions_mutex_);
        sessions_to_close.reserve(sessions_.size());
        for (auto& [id, session] : sessions_)
        {
            sessions_to_close.push_back(session);
        }
        sessions_.clear();
    }
    for (auto& session : sessions_to_close)
    {
        if (session)
        {
            auto result = session->close(error_code);
            (void)result;
        }
    }
}
disconnect_session()
auto kcenon::network::core::messaging_quic_server::disconnect_session (const std::string & session_id, uint64_t error_code = 0) -> VoidResult nodiscard
Disconnect a specific session.
Parameters
session_id Session to disconnect.
error_code Application error code (0 for no error).
Returns
VoidResult indicating success or error.
Definition at line 298 of file quic_server.cpp.
{
    std::shared_ptr<session::quic_session> session;
    {
        std::unique_lock<std::shared_mutex> lock(sessions_mutex_);
        auto it = sessions_.find(session_id);
        if (it == sessions_.end())
        {
            return error_void(error_codes::common_errors::not_found,
                              "Session not found",
                              "messaging_quic_server::disconnect_session",
                              "Session ID: " + session_id);
        }
        session = it->second;
        sessions_.erase(it);
    }
    if (session)
    {
        return session->close(error_code);
    }
    return ok();
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::not_found, and kcenon::network::ok().
do_start_impl()
auto kcenon::network::core::messaging_quic_server::do_start_impl (unsigned short port) -> VoidResult private
QUIC-specific implementation of server start.
Parameters
port The UDP port to listen on.
Returns
VoidResult - Success if server started, or error with code.
Definition at line 119 of file quic_server.cpp.
{
    try
    {
        // Create io_context
        io_context_ = std::make_unique<asio::io_context>();
        work_guard_ = std::make_unique<
            asio::executor_work_guard<asio::io_context::executor_type>>(
            asio::make_work_guard(*io_context_));
        // Create UDP socket
        udp_socket_ = std::make_unique<asio::ip::udp::socket>(
            *io_context_,
            asio::ip::udp::endpoint(asio::ip::udp::v4(), port));
        // Create cleanup timer
        cleanup_timer_ = std::make_unique<asio::steady_timer>(*io_context_);
        // Start receiving packets
        start_receive();
        // Start periodic cleanup timer
        start_cleanup_timer();
        // Get thread pool from network context
        thread_pool_ = network_context::instance().get_thread_pool();
        if (!thread_pool_)
        {
            thread_pool_ = std::make_shared<integration::basic_thread_pool>(2);
        }
        // Submit io_context run task to thread pool
        io_context_future_ = thread_pool_->submit(
            [this]()
            {
                try
                {
                    NETWORK_LOG_INFO(
                        "[messaging_quic_server] Starting io_context on thread pool");
                    io_context_->run();
                    NETWORK_LOG_INFO(
                        "[messaging_quic_server] io_context stopped");
                }
                catch (const std::exception& e)
                {
                    NETWORK_LOG_ERROR(
                        "[messaging_quic_server] Exception in io_context: "
                        + std::string(e.what()));
                }
            });
        NETWORK_LOG_INFO("[messaging_quic_server] Started listening on port "
                         + std::to_string(port));
        return ok();
    }
    catch (const std::system_error& e)
    {
        if (e.code() == asio::error::address_in_use ||
            e.code() == std::errc::address_in_use)
        {
            return error_void(error_codes::network_system::bind_failed,
                              "Failed to bind to port: address already in use",
                              "messaging_quic_server::do_start_impl",
                              "Port: " + std::to_string(port));
        }
        else if (e.code() == asio::error::access_denied ||
                 e.code() == std::errc::permission_denied)
        {
            return error_void(error_codes::network_system::bind_failed,
                              "Failed to bind to port: permission denied",
                              "messaging_quic_server::do_start_impl",
                              "Port: " + std::to_string(port));
        }
        return error_void(error_codes::common_errors::internal_error,
                          "Failed to start server: " + std::string(e.what()),
                          "messaging_quic_server::do_start_impl",
                          "Port: " + std::to_string(port));
    }
    catch (const std::exception& e)
    {
        return error_void(error_codes::common_errors::internal_error,
                          "Failed to start server: " + std::string(e.what()),
                          "messaging_quic_server::do_start_impl",
                          "Port: " + std::to_string(port));
    }
}
References kcenon::network::error_codes::network_system::bind_failed, kcenon::network::error_void(), kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, kcenon::network::ok(), and kcenon::network::integration::thread_pool_interface::submit().
do_stop_impl()
auto kcenon::network::core::messaging_quic_server::do_stop_impl () -> VoidResult private
QUIC-specific implementation of server stop.
Returns
VoidResult - Success if server stopped, or error with code.
Definition at line 207 of file quic_server.cpp.
{
    try
    {
        // Cancel cleanup timer
        if (cleanup_timer_)
        {
            cleanup_timer_->cancel();
        }
        // Close UDP socket
        if (udp_socket_)
        {
            asio::error_code ec;
            udp_socket_->cancel(ec);
            if (udp_socket_->is_open())
            {
                udp_socket_->close(ec);
            }
        }
        // Stop all sessions
        disconnect_all(0);
        // Release work guard
        if (work_guard_)
        {
            work_guard_.reset();
        }
        // Stop io_context
        if (io_context_)
        {
            io_context_->stop();
        }
        // Wait for io_context task
        if (io_context_future_.valid())
        {
            io_context_future_.wait();
        }
        // Release resources
        udp_socket_.reset();
        cleanup_timer_.reset();
        thread_pool_.reset();
        io_context_.reset();
        NETWORK_LOG_INFO("[messaging_quic_server] Stopped.");
        return ok();
    }
    catch (const std::exception& e)
    {
        return error_void(error_codes::common_errors::internal_error,
                          "Failed to stop server: " + std::string(e.what()),
                          "messaging_quic_server::do_stop_impl",
                          "Server ID: " + server_id_);
    }
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_INFO, and kcenon::network::ok().
find_or_create_session()
auto kcenon::network::core::messaging_quic_server::find_or_create_session (const protocols::quic::connection_id & dcid, const asio::ip::udp::endpoint & endpoint) -> std::shared_ptr<session::quic_session> private
Definition at line 483 of file quic_server.cpp.
{
    // First, check existing sessions
    {
        std::shared_lock<std::shared_mutex> lock(sessions_mutex_);
        for (const auto& [id, session] : sessions_)
        {
            if (session->matches_connection_id(dcid))
            {
                return session;
            }
        }
    }
    // Check connection limit
    if (session_count() >= config_.max_connections)
    {
        NETWORK_LOG_WARN(
            "[messaging_quic_server] Connection limit reached, rejecting new connection");
        return nullptr;
    }
    // Create new session for this connection
    auto session_id = generate_session_id();
    // Create QUIC socket for the new session
    asio::ip::udp::socket session_socket(
        *io_context_, asio::ip::udp::endpoint(asio::ip::udp::v4(), 0));
    session_socket.connect(endpoint);
    auto quic_socket = std::make_shared<internal::quic_socket>(
        std::move(session_socket), internal::quic_role::server);
    // Accept the connection with TLS config
    if (!config_.cert_file.empty() && !config_.key_file.empty())
    {
        auto accept_result =
            quic_socket->accept(config_.cert_file, config_.key_file);
        if (accept_result.is_err())
        {
            NETWORK_LOG_ERROR(
                "[messaging_quic_server] Failed to accept connection: "
                + accept_result.error().message);
            return nullptr;
        }
    }
    auto session =
        std::make_shared<session::quic_session>(quic_socket, session_id);
    // Set up session callbacks
    auto self = weak_from_this();
    session->set_receive_callback(
        [self, session_id](const std::vector<uint8_t>& data)
        {
            if (auto server = self.lock())
            {
                auto sess = server->get_session(session_id);
                if (sess)
                {
                    server->invoke_receive_callback(sess, data);
                }
            }
        });
    session->set_stream_receive_callback(
        [self, session_id](uint64_t stream_id,
                           const std::vector<uint8_t>& data,
                           bool fin)
        {
            if (auto server = self.lock())
            {
                auto sess = server->get_session(session_id);
                if (sess)
                {
                    server->invoke_stream_receive_callback(sess, stream_id, data, fin);
                }
            }
        });
    session->set_close_callback(
        [self, session_id]()
        {
            if (auto server = self.lock())
            {
                server->on_session_close(session_id);
            }
        });
    // Add session to map
    {
        std::unique_lock<std::shared_mutex> lock(sessions_mutex_);
        sessions_[session_id] = session;
    }
    // Start the session
    session->start_session();
    // Report metrics
    metrics::metric_reporter::report_connection_accepted();
    metrics::metric_reporter::report_active_connections(session_count());
    // Invoke connection callback
    invoke_connection_callback(session);
#if KCENON_WITH_COMMON_SYSTEM
    if (monitor_)
    {
        monitor_->record_metric("active_connections",
                                static_cast<double>(session_count()));
    }
#endif
    NETWORK_LOG_INFO("[messaging_quic_server] New session created: "
                     + session_id + " from " + endpoint.address().to_string());
    return session;
}
References NETWORK_LOG_ERROR, NETWORK_LOG_INFO, NETWORK_LOG_WARN, kcenon::network::metrics::metric_reporter::report_active_connections(), kcenon::network::metrics::metric_reporter::report_connection_accepted(), and kcenon::network::internal::server.
generate_session_id()
auto kcenon::network::core::messaging_quic_server::generate_session_id () -> std::string private
Definition at line 606 of file quic_server.cpp.
{
    auto counter = session_counter_.fetch_add(1);
    std::ostringstream oss;
    oss << server_id_ << "-" << counter;
    return oss.str();
}
get_session()
auto kcenon::network::core::messaging_quic_server::get_session (const std::string & session_id) -> std::shared_ptr<session::quic_session> nodiscard
Get a session by its ID.
Parameters
session_id Session identifier.
Returns
Session pointer or nullptr if not found.
Definition at line 280 of file quic_server.cpp.
{
    std::shared_lock<std::shared_mutex> lock(sessions_mutex_);
    auto it = sessions_.find(session_id);
    if (it != sessions_.end())
    {
        return it->second;
    }
    return nullptr;
}
handle_packet()
auto kcenon::network::core::messaging_quic_server::handle_packet (std::span< const uint8_t > data, const asio::ip::udp::endpoint & from) -> void private
Definition at line 443 of file quic_server.cpp.
{
    if (data.empty())
    {
        return;
    }
    // Parse packet header to get destination connection ID
    auto header_result = protocols::quic::packet_parser::parse_header(data);
    if (header_result.is_err())
    {
        NETWORK_LOG_DEBUG("[messaging_quic_server] Invalid packet from "
                          + from.address().to_string());
        return;
    }
    // Extract destination connection ID from header
    protocols::quic::connection_id dcid;
    std::visit(
        [&dcid](auto&& hdr)
        {
            dcid = hdr.dest_conn_id;
        },
        header_result.value().first);
    // Find or create session for this connection
    auto session = find_or_create_session(dcid, from);
    if (!session)
    {
        NETWORK_LOG_DEBUG(
            "[messaging_quic_server] Could not find or create session for packet");
        return;
    }
    // Delegate packet handling to session
    session->handle_packet(data);
}
References NETWORK_LOG_DEBUG, and kcenon::network::protocols::quic::packet_parser::parse_header().
invoke_connection_callback()
auto kcenon::network::core::messaging_quic_server::invoke_connection_callback (std::shared_ptr< session::quic_session > session) -> void private
Invokes the connection callback.
Parameters
session The new session.
Definition at line 704 of file quic_server.cpp.
{
    callbacks_.invoke<to_index(callback_index::connection)>(session);
}
References kcenon::network::to_index().
invoke_disconnection_callback()
auto kcenon::network::core::messaging_quic_server::invoke_disconnection_callback (std::shared_ptr< session::quic_session > session) -> void private
Invokes the disconnection callback.
Parameters
session The disconnected session.
Definition at line 710 of file quic_server.cpp.
{
    callbacks_.invoke<to_index(callback_index::disconnection)>(session);
}
References kcenon::network::to_index().
invoke_error_callback()
auto kcenon::network::core::messaging_quic_server::invoke_error_callback (std::error_code ec) -> void private
Invokes the error callback.
Parameters
ec The error code.
Definition at line 732 of file quic_server.cpp.
{
    callbacks_.invoke<to_index(callback_index::error)>(ec);
}
References kcenon::network::to_index().
invoke_receive_callback()
auto kcenon::network::core::messaging_quic_server::invoke_receive_callback (std::shared_ptr< session::quic_session > session, const std::vector< uint8_t > & data) -> void private
Invokes the receive callback.
Parameters
session The session that received data.
data The received data.
Definition at line 716 of file quic_server.cpp.
{
    callbacks_.invoke<to_index(callback_index::receive)>(session, data);
}
References kcenon::network::to_index().
invoke_stream_receive_callback()
auto kcenon::network::core::messaging_quic_server::invoke_stream_receive_callback (std::shared_ptr< session::quic_session > session, uint64_t stream_id, const std::vector< uint8_t > & data, bool fin) -> void private
Invokes the stream receive callback.
Parameters
session The session that received data.
stream_id The stream ID.
data The received data.
fin Whether this is the final data on the stream.
Definition at line 723 of file quic_server.cpp.
{
    callbacks_.invoke<to_index(callback_index::stream_receive)>(session, stream_id, data, fin);
}
References kcenon::network::to_index().
is_running()
auto kcenon::network::core::messaging_quic_server::is_running () const -> bool nodiscard override virtual
Checks if the server is currently running.
Returns
true if running, false otherwise.
Implements i_network_component::is_running().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 40 of file quic_server.cpp.
{
    return lifecycle_.is_running();
}
References kcenon::network::utils::lifecycle_manager::is_running(), and lifecycle_.
multicast()
auto kcenon::network::core::messaging_quic_server::multicast (const std::vector< std::string > & session_ids, std::vector< uint8_t > && data) -> VoidResult nodiscard
Send data to specific sessions.
Parameters
session_ids List of session IDs to send to.
data Data to send (moved for efficiency).
Returns
VoidResult indicating success or error.
Definition at line 368 of file quic_server.cpp.
{
    for (const auto& session_id : session_ids)
    {
        auto session = get_session(session_id);
        if (session && session->is_active())
        {
            std::vector<uint8_t> data_copy(data);
            auto result = session->send(std::move(data_copy));
            if (result.is_err())
            {
                NETWORK_LOG_WARN("[messaging_quic_server] Failed to send to session "
                                 + session_id + ": " + result.error().message);
            }
        }
    }
    return ok();
}
References NETWORK_LOG_WARN, and kcenon::network::ok().
on_session_close()
auto kcenon::network::core::messaging_quic_server::on_session_close (const std::string & session_id) -> void private
Definition at line 614 of file quic_server.cpp.
{
    std::shared_ptr<session::quic_session> session;
    {
        std::unique_lock<std::shared_mutex> lock(sessions_mutex_);
        auto it = sessions_.find(session_id);
        if (it != sessions_.end())
        {
            session = it->second;
            sessions_.erase(it);
        }
    }
    if (session)
    {
        // Report metrics
        metrics::metric_reporter::report_active_connections(session_count());
        // Invoke disconnection callback
        invoke_disconnection_callback(session);
#if KCENON_WITH_COMMON_SYSTEM
        if (monitor_)
        {
            monitor_->record_metric("active_connections",
                                    static_cast<double>(session_count()));
        }
#endif
        NETWORK_LOG_INFO("[messaging_quic_server] Session closed: "
                         + session_id);
    }
}
References NETWORK_LOG_INFO, and kcenon::network::metrics::metric_reporter::report_active_connections().
operator=() [1/2]
messaging_quic_server & kcenon::network::core::messaging_quic_server::operator= (const messaging_quic_server &) delete
operator=() [2/2]
messaging_quic_server & kcenon::network::core::messaging_quic_server::operator= (messaging_quic_server &&) delete
server_id()
auto kcenon::network::core::messaging_quic_server::server_id () const -> const std::string& nodiscard
Returns the server identifier.
Returns
The server_id string.
Definition at line 35 of file quic_server.cpp.
{
    return server_id_;
}
References server_id_.
session_count()
auto kcenon::network::core::messaging_quic_server::session_count () const -> size_t nodiscard
Get the number of active sessions.
Returns
Session count.
Definition at line 292 of file quic_server.cpp.
{
    std::shared_lock<std::shared_mutex> lock(sessions_mutex_);
    return sessions_.size();
}
References sessions_, and sessions_mutex_.
Referenced by connection_count().
sessions()
auto kcenon::network::core::messaging_quic_server::sessions () const -> std::vector<std::shared_ptr<session::quic_session>> nodiscard
Get all active sessions.
Returns
Vector of session pointers.
Definition at line 267 of file quic_server.cpp.
{
    std::shared_lock<std::shared_mutex> lock(sessions_mutex_);
    std::vector<std::shared_ptr<session::quic_session>> result;
    result.reserve(sessions_.size());
    for (const auto& [id, session] : sessions_)
    {
        result.push_back(session);
    }
    return result;
}
References sessions_, and sessions_mutex_.
set_connection_callback() [1/2]
auto kcenon::network::core::messaging_quic_server::set_connection_callback (connection_callback_t callback) -> void
Sets the callback for new connections (legacy version).
Parameters
callback Function called when a client connects.
Definition at line 741 of file quic_server.cpp.
{
    callbacks_.set<to_index(callback_index::connection)>(std::move(callback));
}
References kcenon::network::to_index().
set_connection_callback() [2/2]
auto kcenon::network::core::messaging_quic_server::set_connection_callback (interfaces::i_quic_server::connection_callback_t callback) -> void override virtual
Sets the callback for new connections (interface version).
Parameters
callback The callback function.
Implements i_quic_server::set_connection_callback().
Implements kcenon::network::interfaces::i_quic_server.
Definition at line 770 of file quic_server.cpp.
{
    // Convert callback to internal type (quic_session to i_quic_session)
    set_connection_callback(
        [cb = std::move(callback)](std::shared_ptr<session::quic_session> session) {
            if (cb && session)
            {
                // quic_session implements i_quic_session, so we can pass it directly
                cb(session);
            }
        });
}
set_disconnection_callback() [1/2]
auto kcenon::network::core::messaging_quic_server::set_disconnection_callback (disconnection_callback_t callback) -> void
Sets the callback for disconnections (legacy version).
Parameters
callback Function called when a client disconnects.
Definition at line 746 of file quic_server.cpp.
{
    callbacks_.set<to_index(callback_index::disconnection)>(std::move(callback));
}
References kcenon::network::to_index().
set_disconnection_callback() [2/2]
auto kcenon::network::core::messaging_quic_server::set_disconnection_callback (interfaces::i_quic_server::disconnection_callback_t callback) -> void override virtual
Sets the callback for disconnections (interface version).
Parameters
callback The callback function.
Implements i_quic_server::set_disconnection_callback().
Implements kcenon::network::interfaces::i_quic_server.
Definition at line 784 of file quic_server.cpp.
{
    set_disconnection_callback(
        [cb = std::move(callback)](std::shared_ptr<session::quic_session> session) {
            if (cb && session)
            {
                cb(session->session_id());
            }
        });
}
set_error_callback() [1/2]
auto kcenon::network::core::messaging_quic_server::set_error_callback (error_callback_t callback) -> void
Sets the callback for errors (legacy version).
Parameters
callback Function called when an error occurs.
Definition at line 761 of file quic_server.cpp.
{
    callbacks_.set<to_index(callback_index::error)>(std::move(callback));
}
References kcenon::network::to_index().
set_error_callback() [2/2]
auto kcenon::network::core::messaging_quic_server::set_error_callback (interfaces::i_quic_server::error_callback_t callback) -> void override virtual
Sets the callback for errors (interface version).
Parameters
callback The callback function.
Implements i_quic_server::set_error_callback().
Implements kcenon::network::interfaces::i_quic_server.
Definition at line 824 of file quic_server.cpp.
{
    // Store the interface callback and wrap it for base class
    // Note: Base class error_callback_t only takes error_code, not session
    // We need to store the interface callback separately and invoke it from
    // the receive side where we have session context
    interface_error_cb_ = std::move(callback);
}
set_receive_callback() [1/2]
auto kcenon::network::core::messaging_quic_server::set_receive_callback (interfaces::i_quic_server::receive_callback_t callback) -> void override virtual
Sets the callback for received data on default stream (interface version).
Parameters
callback The callback function.
Implements i_quic_server::set_receive_callback().
Implements kcenon::network::interfaces::i_quic_server.
Definition at line 796 of file quic_server.cpp.
{
    set_receive_callback(
        [cb = std::move(callback)](std::shared_ptr<session::quic_session> session,
                                    const std::vector<uint8_t>& data) {
            if (cb && session)
            {
                cb(session->session_id(), data);
            }
        });
}
set_receive_callback() [2/2]
auto kcenon::network::core::messaging_quic_server::set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received data (legacy version).
Parameters
callback Function called when data is received.
Definition at line 751 of file quic_server.cpp.
{
    callbacks_.set<to_index(callback_index::receive)>(std::move(callback));
}
References kcenon::network::to_index().
set_stream_callback()
auto kcenon::network::core::messaging_quic_server::set_stream_callback (interfaces::i_quic_server::stream_callback_t callback) -> void override virtual
Sets the callback for stream data (interface version).
Parameters
callback The callback function.
Implements i_quic_server::set_stream_callback().
Implements kcenon::network::interfaces::i_quic_server.
Definition at line 809 of file quic_server.cpp.
{
    set_stream_receive_callback(
        [cb = std::move(callback)](std::shared_ptr<session::quic_session> session,
                                    uint64_t stream_id,
                                    const std::vector<uint8_t>& data,
                                    bool fin) {
            if (cb && session)
            {
                cb(session->session_id(), stream_id, data, fin);
            }
        });
}
set_stream_receive_callback()
auto kcenon::network::core::messaging_quic_server::set_stream_receive_callback (stream_receive_callback_t callback) -> void
Sets the callback for stream data reception (legacy version).
Parameters
callback Function called with session, stream ID, data, and FIN flag.
Note
This is kept for backward compatibility. New code should use set_stream_callback() from the i_quic_server interface.
Definition at line 756 of file quic_server.cpp.
{
    callbacks_.set<to_index(callback_index::stream_receive)>(std::move(callback));
}
References kcenon::network::to_index().
start()
auto kcenon::network::core::messaging_quic_server::start (uint16_t port) -> VoidResult nodiscard override virtual
Starts the QUIC server on the specified port.
Parameters
port The port number to listen on.
Returns
VoidResult indicating success or failure.
Implements i_quic_server::start(). Delegates to start_server().
Implements kcenon::network::interfaces::i_quic_server.
Definition at line 104 of file quic_server.cpp.
{
    return start_server(port);
}
start_cleanup_timer()
auto kcenon::network::core::messaging_quic_server::start_cleanup_timer () -> void private
Definition at line 649 of file quic_server.cpp.
{
    if (!cleanup_timer_ || !is_running())
    {
        return;
    }
    // Schedule cleanup every 30 seconds
    cleanup_timer_->expires_after(std::chrono::seconds(30));
    auto self = shared_from_this();
    cleanup_timer_->async_wait(
        [this, self](const std::error_code& ec)
        {
            if (!ec && is_running())
            {
                cleanup_dead_sessions();
                start_cleanup_timer(); // Reschedule
            }
        });
}
start_receive()
auto kcenon::network::core::messaging_quic_server::start_receive () -> void private
Definition at line 403 of file quic_server.cpp.
{
    if (!is_running() || !udp_socket_)
    {
        return;
    }
    auto self = shared_from_this();
    udp_socket_->async_receive_from(
        asio::buffer(recv_buffer_),
        recv_endpoint_,
        [this, self](std::error_code ec, std::size_t bytes_received)
        {
            if (!is_running())
            {
                return;
            }
            if (ec)
            {
                if (ec != asio::error::operation_aborted)
                {
                    NETWORK_LOG_ERROR(
                        "[messaging_quic_server] Receive error: " + ec.message());
                    invoke_error_callback(ec);
                }
                return;
            }
            // Handle the received packet
            std::span<const uint8_t> packet_data(recv_buffer_.data(),
                                                 bytes_received);
            handle_packet(packet_data, recv_endpoint_);
            // Continue receiving
            start_receive();
        });
}
References NETWORK_LOG_ERROR.
start_server() [1/2]
auto kcenon::network::core::messaging_quic_server::start_server (unsigned short port) -> VoidResult nodiscard
Start the server with default configuration.
Parameters
port UDP port to listen on.
Returns
VoidResult indicating success or error.
Definition at line 50 of file quic_server.cpp.
{
    // Use default config with no TLS (for development/testing only)
    return start_server(port, quic_server_config{});
}
start_server() [2/2]
auto kcenon::network::core::messaging_quic_server::start_server (unsigned short port, const quic_server_config & config) -> VoidResult nodiscard
Start the server with TLS configuration.
Parameters
port UDP port to listen on.
config Server configuration with TLS settings.
Returns
VoidResult indicating success or error.
Definition at line 56 of file quic_server.cpp.
{
    if (lifecycle_.is_running())
    {
        return error_void(
            error_codes::network_system::server_already_running,
            "QUIC server is already running",
            "messaging_quic_server::start_server");
    }
    config_ = config;
    lifecycle_.set_running();
    auto result = do_start_impl(port);
    if (result.is_err())
    {
        lifecycle_.mark_stopped();
    }
    return result;
}
References config, kcenon::network::error_void(), and kcenon::network::error_codes::network_system::server_already_running.
stop()
auto kcenon::network::core::messaging_quic_server::stop () -> VoidResult nodiscard override virtual
Stops the QUIC server.
Returns
VoidResult indicating success or failure.
Implements i_quic_server::stop(). Delegates to stop_server().
Implements kcenon::network::interfaces::i_quic_server.
Definition at line 109 of file quic_server.cpp.
{
    return stop_server();
}
stop_server()
auto kcenon::network::core::messaging_quic_server::stop_server () -> VoidResult nodiscard
Stops the server and releases all resources.
Returns
Result<void> - Success if server stopped, or error with code.
Definition at line 80 of file quic_server.cpp.
{
    if (!lifecycle_.is_running())
    {
        return error_void(
            error_codes::network_system::server_not_started,
            "QUIC server is not running",
            "messaging_quic_server::stop_server");
    }
    if (!lifecycle_.prepare_stop())
    {
        return error_void(
            error_codes::network_system::server_not_started,
            "QUIC server is already stopping",
            "messaging_quic_server::stop_server");
    }
    auto result = do_stop_impl();
    lifecycle_.mark_stopped();
    return result;
}
References kcenon::network::error_void(), and kcenon::network::error_codes::network_system::server_not_started.
Referenced by ~messaging_quic_server().
wait_for_stop()
auto kcenon::network::core::messaging_quic_server::wait_for_stop () -> void override virtual
Blocks until stop() is called.
Implements i_network_component::wait_for_stop().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 45 of file quic_server.cpp.
{
    lifecycle_.wait_for_stop();
}
Member Data Documentation
callbacks_
callbacks_t kcenon::network::core::messaging_quic_server::callbacks_ private
Callback manager.
Definition at line 508 of file quic_server.h.
cleanup_timer_
std::unique_ptr<asio::steady_timer> kcenon::network::core::messaging_quic_server::cleanup_timer_ private
Definition at line 528 of file quic_server.h.
config_
quic_server_config kcenon::network::core::messaging_quic_server::config_ private
Definition at line 517 of file quic_server.h.
interface_error_cb_
interfaces::i_quic_server::error_callback_t kcenon::network::core::messaging_quic_server::interface_error_cb_ private
Definition at line 534 of file quic_server.h.
io_context_
std::unique_ptr<asio::io_context> kcenon::network::core::messaging_quic_server::io_context_ private
Definition at line 510 of file quic_server.h.
io_context_future_
std::future<void> kcenon::network::core::messaging_quic_server::io_context_future_ private
Definition at line 515 of file quic_server.h.
lifecycle_
utils::lifecycle_manager kcenon::network::core::messaging_quic_server::lifecycle_ private
Lifecycle state manager.
Definition at line 507 of file quic_server.h.
Referenced by is_running(), and ~messaging_quic_server().
recv_buffer_
std::array<uint8_t, 65536> kcenon::network::core::messaging_quic_server::recv_buffer_ private
Definition at line 524 of file quic_server.h.
recv_endpoint_
asio::ip::udp::endpoint kcenon::network::core::messaging_quic_server::recv_endpoint_ private
Definition at line 525 of file quic_server.h.
server_id_
std::string kcenon::network::core::messaging_quic_server::server_id_ private
Server identifier.
Definition at line 506 of file quic_server.h.
Referenced by server_id().
session_counter_
std::atomic<uint64_t> kcenon::network::core::messaging_quic_server::session_counter_ {0} private
Definition at line 531 of file quic_server.h.
{0};
sessions_
std::map<std::string, std::shared_ptr<session::quic_session> > kcenon::network::core::messaging_quic_server::sessions_ private
Definition at line 521 of file quic_server.h.
Referenced by session_count(), and sessions().
sessions_mutex_
std::shared_mutex kcenon::network::core::messaging_quic_server::sessions_mutex_ mutable private
Definition at line 520 of file quic_server.h.
Referenced by session_count(), and sessions().
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::messaging_quic_server::thread_pool_ private
Definition at line 514 of file quic_server.h.
udp_socket_
std::unique_ptr<asio::ip::udp::socket> kcenon::network::core::messaging_quic_server::udp_socket_ private
Definition at line 513 of file quic_server.h.
work_guard_
std::unique_ptr<asio::executor_work_guard<asio::io_context::executor_type> > kcenon::network::core::messaging_quic_server::work_guard_ private
Definition at line 512 of file quic_server.h.
The documentation for this class was generated from the following files:
src/internal/experimental/quic_server.h
src/experimental/quic_server.cpp