Network System: kcenon::network::protocols::quic::connection_id_manager Class Reference
kcenon::network::protocols::quic::connection_id_manager Class Reference
Manages peer connection IDs for QUIC connections (RFC 9000 Section 5.1)
#include <connection_id_manager.h>
Public Member Functions
connection_id_manager (uint64_t active_cid_limit=8)
Construct a connection ID manager.
~connection_id_manager ()=default
connection_id_manager (const connection_id_manager &)=delete
auto operator= (const connection_id_manager &) -> connection_id_manager &=delete
connection_id_manager (connection_id_manager &&)=default
auto operator= (connection_id_manager &&) -> connection_id_manager &=default
void set_initial_peer_cid (const connection_id &cid)
Set the initial peer connection ID (from Initial packet)
auto add_peer_cid (const connection_id &cid, uint64_t sequence, uint64_t retire_prior_to, const std::array< uint8_t, 16 > &reset_token) -> VoidResult
Add a new peer connection ID from NEW_CONNECTION_ID frame.
auto get_active_peer_cid () const -> const connection_id &
Get the currently active peer connection ID.
auto rotate_peer_cid () -> VoidResult
Rotate to a new peer connection ID.
auto available_peer_cids () const -> size_t
Get the number of available (non-retired, non-active) peer CIDs.
auto is_stateless_reset_token (const std::array< uint8_t, 16 > &token) const -> bool
Check if a stateless reset token matches any stored CID.
void retire_cids_prior_to (uint64_t prior_to)
Retire CIDs with sequence numbers less than the given value.
auto get_pending_retire_frames () -> std::vector< retire_connection_id_frame >
Get pending RETIRE_CONNECTION_ID frames to send.
void clear_pending_retire_frames ()
Clear the pending retire frames queue.
auto retire_peer_cid (uint64_t sequence) -> VoidResult
Mark a specific CID sequence as retired.
auto largest_retire_prior_to () const -> uint64_t
Get the largest retire_prior_to value received.
auto peer_cid_count () const -> size_t
Get the current number of peer CIDs (including retired)
auto active_cid_limit () const -> uint64_t
Get the active connection ID limit.
void set_active_cid_limit (uint64_t limit)
Set the active connection ID limit.
auto has_peer_cid (const connection_id &cid) const -> bool
Check if a given CID matches any stored peer CID.
Private Member Functions
auto find_by_sequence (uint64_t sequence) -> std::vector< connection_id_entry >::iterator
Find an entry by sequence number.
auto count_active_cids () const -> size_t
Count non-retired CIDs.
Private Attributes
uint64_t active_cid_limit_
Maximum number of active CIDs.
std::vector< connection_id_entry > peer_cids_
Peer connection IDs.
size_t active_index_ {0}
Index of the currently active peer CID.
uint64_t largest_retire_prior_to_ {0}
Largest retire_prior_to value received.
std::vector< retire_connection_id_frame > pending_retire_frames_
Pending RETIRE_CONNECTION_ID frames to send.
Static Private Attributes
static const connection_id empty_cid_ {}
Empty CID for error cases.
Detailed Description
Manages peer connection IDs for QUIC connections (RFC 9000 Section 5.1)
This class handles:
Storage of connection IDs received via NEW_CONNECTION_ID frames
Tracking sequence numbers and retire_prior_to values
Connection ID rotation for path migration
Generation of RETIRE_CONNECTION_ID frames
Stateless reset token validation
RFC 9000 Section 5.1 Requirements:
Endpoints must store connection IDs provided by peer
Must track sequence numbers and retire_prior_to values
Must support Connection ID rotation for path migration
Must honor retire_prior_to in NEW_CONNECTION_ID frames
Definition at line 103 of file connection_id_manager.h.
Constructor & Destructor Documentation
connection_id_manager() [1/3]
kcenon::network::protocols::quic::connection_id_manager::connection_id_manager (uint64_t active_cid_limit = 8) explicit
Construct a connection ID manager.
Parameters
active_cid_limit Maximum number of active CIDs (from transport params)
Definition at line 47 of file connection_id_manager.cpp.
    : active_cid_limit_(active_cid_limit)
{
}
~connection_id_manager()
kcenon::network::protocols::quic::connection_id_manager::~connection_id_manager () default
connection_id_manager() [2/3]
kcenon::network::protocols::quic::connection_id_manager::connection_id_manager (const connection_id_manager &) delete
connection_id_manager() [3/3]
kcenon::network::protocols::quic::connection_id_manager::connection_id_manager (connection_id_manager &&) default
Member Function Documentation
active_cid_limit()
auto kcenon::network::protocols::quic::connection_id_manager::active_cid_limit () const -> uint64_t inline
Get the active connection ID limit.
Definition at line 226 of file connection_id_manager.h.
{ return active_cid_limit_; }
References active_cid_limit_.
add_peer_cid()
auto kcenon::network::protocols::quic::connection_id_manager::add_peer_cid (const connection_id & cid, uint64_t sequence, uint64_t retire_prior_to, const std::array< uint8_t, 16 > & reset_token) -> VoidResult
Add a new peer connection ID from NEW_CONNECTION_ID frame.
Parameters
cid The connection ID
sequence The sequence number for this CID
retire_prior_to CIDs below this sequence should be retired
reset_token Stateless reset token (16 bytes)
Returns
Success or error
Definition at line 70 of file connection_id_manager.cpp.
{
    // RFC 9000 Section 19.15: retire_prior_to must be <= sequence
    if (retire_prior_to > sequence)
    {
        return error_void(cid_manager_error::invalid_retire_prior_to,
                          "retire_prior_to exceeds sequence number",
                          "connection_id_manager");
    }
    // Check for duplicate sequence number
    auto it = find_by_sequence(sequence);
    if (it != peer_cids_.end())
    {
        // RFC 9000: If a NEW_CONNECTION_ID frame is received with a sequence
        // number already seen, it must be ignored if identical, or a protocol
        // error if different.
        if (it->cid == cid && it->stateless_reset_token == reset_token)
        {
            // Identical frame, ignore
            return ok();
        }
        return error_void(cid_manager_error::duplicate_sequence,
                          "Duplicate sequence number with different CID",
                          "connection_id_manager");
    }
    // Check active CID limit (count non-retired CIDs)
    auto active_count = count_active_cids();
    if (active_count >= active_cid_limit_)
    {
        return error_void(cid_manager_error::active_cid_limit_exceeded,
                          "Active connection ID limit exceeded",
                          "connection_id_manager");
    }
    // Add the new CID
    connection_id_entry entry;
    entry.cid = cid;
    entry.sequence_number = sequence;
    entry.stateless_reset_token = reset_token;
    entry.retired = false;
    peer_cids_.push_back(entry);
    // Process retire_prior_to
    if (retire_prior_to > largest_retire_prior_to_)
    {
        retire_cids_prior_to(retire_prior_to);
        largest_retire_prior_to_ = retire_prior_to;
    }
    return ok();
}
References kcenon::network::protocols::quic::cid_manager_error::active_cid_limit_exceeded, kcenon::network::protocols::quic::connection_id_entry::cid, kcenon::network::protocols::quic::cid_manager_error::duplicate_sequence, kcenon::network::error_void(), kcenon::network::protocols::quic::cid_manager_error::invalid_retire_prior_to, kcenon::network::ok(), kcenon::network::protocols::quic::connection_id_entry::retired, kcenon::network::protocols::quic::connection_id_entry::sequence_number, and kcenon::network::protocols::quic::connection_id_entry::stateless_reset_token.
available_peer_cids()
auto kcenon::network::protocols::quic::connection_id_manager::available_peer_cids () const -> size_t
Get the number of available (non-retired, non-active) peer CIDs.
Definition at line 163 of file connection_id_manager.cpp.
{
    size_t count = 0;
    for (size_t i = 0; i < peer_cids_.size(); ++i)
    {
        if (i != active_index_ && !peer_cids_[i].retired)
        {
            ++count;
        }
    }
    return count;
}
References active_index_, and peer_cids_.
clear_pending_retire_frames()
void kcenon::network::protocols::quic::connection_id_manager::clear_pending_retire_frames ()
Clear the pending retire frames queue.
Called after the frames have been successfully sent and acknowledged.
Definition at line 229 of file connection_id_manager.cpp.
{
    pending_retire_frames_.clear();
}
References pending_retire_frames_.
count_active_cids()
auto kcenon::network::protocols::quic::connection_id_manager::count_active_cids () const -> size_t private
Count non-retired CIDs.
Definition at line 280 of file connection_id_manager.cpp.
{
    return static_cast<size_t>(std::count_if(
        peer_cids_.begin(), peer_cids_.end(),
        [](const connection_id_entry& entry) { return !entry.retired; }));
}
References peer_cids_.
find_by_sequence()
auto kcenon::network::protocols::quic::connection_id_manager::find_by_sequence (uint64_t sequence) -> std::vector<connection_id_entry>::iterator private
Find an entry by sequence number.
Definition at line 272 of file connection_id_manager.cpp.
{
    return std::find_if(peer_cids_.begin(), peer_cids_.end(),
                        [sequence](const connection_id_entry& entry)
                        { return entry.sequence_number == sequence; });
}
get_active_peer_cid()
auto kcenon::network::protocols::quic::connection_id_manager::get_active_peer_cid () const -> const connection_id&
Get the currently active peer connection ID.
Returns
Reference to the active CID
Definition at line 129 of file connection_id_manager.cpp.
{
    if (peer_cids_.empty() || active_index_ >= peer_cids_.size())
    {
        return empty_cid_;
    }
    return peer_cids_[active_index_].cid;
}
References active_index_, empty_cid_, and peer_cids_.
Referenced by kcenon::network::protocols::quic::connection::active_peer_cid().
get_pending_retire_frames()
auto kcenon::network::protocols::quic::connection_id_manager::get_pending_retire_frames () -> std::vector<retire_connection_id_frame>
Get pending RETIRE_CONNECTION_ID frames to send.
Returns
Vector of frames for retired CIDs that need acknowledgment
Definition at line 223 of file connection_id_manager.cpp.
{
    return pending_retire_frames_;
}
has_peer_cid()
auto kcenon::network::protocols::quic::connection_id_manager::has_peer_cid (const connection_id & cid) const -> bool
Check if a given CID matches any stored peer CID.
Parameters
cid The connection ID to check
Returns
True if the CID is known
Definition at line 261 of file connection_id_manager.cpp.
{
    return std::any_of(peer_cids_.begin(), peer_cids_.end(),
                       [&cid](const connection_id_entry& entry)
                       { return entry.cid == cid && !entry.retired; });
}
is_stateless_reset_token()
auto kcenon::network::protocols::quic::connection_id_manager::is_stateless_reset_token (const std::array< uint8_t, 16 > & token) const -> bool
Check if a stateless reset token matches any stored CID.
Parameters
token The 16-byte token to check
Returns
True if the token matches a stored CID's reset token
Definition at line 176 of file connection_id_manager.cpp.
{
    for (const auto& entry : peer_cids_)
    {
        if (entry.stateless_reset_token == token)
        {
            return true;
        }
    }
    return false;
}
largest_retire_prior_to()
auto kcenon::network::protocols::quic::connection_id_manager::largest_retire_prior_to () const -> uint64_t inline
Get the largest retire_prior_to value received.
Definition at line 213 of file connection_id_manager.h.
    {
        return largest_retire_prior_to_;
    }
References largest_retire_prior_to_.
operator=() [1/2]
auto kcenon::network::protocols::quic::connection_id_manager::operator= (connection_id_manager &&) -> connection_id_manager &=default default
operator=() [2/2]
auto kcenon::network::protocols::quic::connection_id_manager::operator= (const connection_id_manager &) -> connection_id_manager &=delete delete
peer_cid_count()
auto kcenon::network::protocols::quic::connection_id_manager::peer_cid_count () const -> size_t inline
Get the current number of peer CIDs (including retired)
Definition at line 221 of file connection_id_manager.h.
{ return peer_cids_.size(); }
References peer_cids_.
Referenced by kcenon::network::protocols::quic::connection::active_peer_cid().
retire_cids_prior_to()
void kcenon::network::protocols::quic::connection_id_manager::retire_cids_prior_to (uint64_t prior_to)
Retire CIDs with sequence numbers less than the given value.
Parameters
prior_to Sequence number threshold
Called when processing a NEW_CONNECTION_ID frame with retire_prior_to.
Definition at line 193 of file connection_id_manager.cpp.
{
    for (auto& entry : peer_cids_)
    {
        if (!entry.retired && entry.sequence_number < prior_to)
        {
            entry.retired = true;
            // Queue RETIRE_CONNECTION_ID frame
            retire_connection_id_frame frame;
            frame.sequence_number = entry.sequence_number;
            pending_retire_frames_.push_back(frame);
            // If this was the active CID, we need to switch
            if (&entry == &peer_cids_[active_index_])
            {
                // Find a new active CID
                for (size_t i = 0; i < peer_cids_.size(); ++i)
                {
                    if (!peer_cids_[i].retired)
                    {
                        active_index_ = i;
                        break;
                    }
                }
            }
        }
    }
}
References active_index_, peer_cids_, pending_retire_frames_, and kcenon::network::protocols::quic::retire_connection_id_frame::sequence_number.
retire_peer_cid()
auto kcenon::network::protocols::quic::connection_id_manager::retire_peer_cid (uint64_t sequence) -> VoidResult
Mark a specific CID sequence as retired.
Parameters
sequence The sequence number to retire
Returns
Success or error if sequence not found
Definition at line 234 of file connection_id_manager.cpp.
{
    auto it = find_by_sequence(sequence);
    if (it == peer_cids_.end())
    {
        return error_void(cid_manager_error::cid_not_found,
                          "Connection ID sequence not found",
                          "connection_id_manager");
    }
    if (!it->retired)
    {
        it->retired = true;
        // Queue RETIRE_CONNECTION_ID frame
        retire_connection_id_frame frame;
        frame.sequence_number = sequence;
        pending_retire_frames_.push_back(frame);
    }
    return ok();
}
References kcenon::network::protocols::quic::cid_manager_error::cid_not_found, kcenon::network::error_void(), kcenon::network::ok(), and kcenon::network::protocols::quic::retire_connection_id_frame::sequence_number.
rotate_peer_cid()
auto kcenon::network::protocols::quic::connection_id_manager::rotate_peer_cid () -> VoidResult
Rotate to a new peer connection ID.
Returns
Success or error if no unused CID is available
This is used during path migration or proactive rotation. The current CID is marked for retirement and a new one is selected.
Definition at line 139 of file connection_id_manager.cpp.
{
    // Find an unused, non-retired CID
    for (size_t i = 0; i < peer_cids_.size(); ++i)
    {
        if (i != active_index_ && !peer_cids_[i].retired)
        {
            // Mark the old CID for retirement
            if (active_index_ < peer_cids_.size())
            {
                auto old_seq = peer_cids_[active_index_].sequence_number;
                (void)retire_peer_cid(old_seq);
            }
            active_index_ = i;
            return ok();
        }
    }
    return error_void(cid_manager_error::no_available_cid,
                      "No available connection ID for rotation",
                      "connection_id_manager");
}
References kcenon::network::error_void(), kcenon::network::protocols::quic::cid_manager_error::no_available_cid, and kcenon::network::ok().
set_active_cid_limit()
void kcenon::network::protocols::quic::connection_id_manager::set_active_cid_limit (uint64_t limit) inline
Set the active connection ID limit.
Parameters
limit New limit (from transport parameters)
Definition at line 232 of file connection_id_manager.h.
{ active_cid_limit_ = limit; }
References active_cid_limit_.
Referenced by kcenon::network::protocols::quic::connection::apply_remote_params().
set_initial_peer_cid()
void kcenon::network::protocols::quic::connection_id_manager::set_initial_peer_cid (const connection_id & cid)
Set the initial peer connection ID (from Initial packet)
Parameters
cid The initial connection ID
This is called when processing the first packet from the peer. The initial CID has an implicit sequence number of 0.
Definition at line 56 of file connection_id_manager.cpp.
{
    // Initial CID has sequence number 0 and no stateless reset token
    connection_id_entry entry;
    entry.cid = cid;
    entry.sequence_number = 0;
    entry.stateless_reset_token.fill(0);
    entry.retired = false;
    peer_cids_.clear();
    peer_cids_.push_back(entry);
    active_index_ = 0;
}
References active_index_, kcenon::network::protocols::quic::connection_id_entry::cid, peer_cids_, kcenon::network::protocols::quic::connection_id_entry::retired, kcenon::network::protocols::quic::connection_id_entry::sequence_number, and kcenon::network::protocols::quic::connection_id_entry::stateless_reset_token.
Referenced by kcenon::network::protocols::quic::connection::connection().
Member Data Documentation
active_cid_limit_
uint64_t kcenon::network::protocols::quic::connection_id_manager::active_cid_limit_ private
Maximum number of active CIDs.
Definition at line 243 of file connection_id_manager.h.
Referenced by active_cid_limit(), and set_active_cid_limit().
active_index_
size_t kcenon::network::protocols::quic::connection_id_manager::active_index_ {0} private
Index of the currently active peer CID.
Definition at line 249 of file connection_id_manager.h.
{0};
Referenced by available_peer_cids(), get_active_peer_cid(), retire_cids_prior_to(), and set_initial_peer_cid().
empty_cid_
const connection_id kcenon::network::protocols::quic::connection_id_manager::empty_cid_ {} static private
Empty CID for error cases.
Definition at line 258 of file connection_id_manager.h.
Referenced by get_active_peer_cid().
largest_retire_prior_to_
uint64_t kcenon::network::protocols::quic::connection_id_manager::largest_retire_prior_to_ {0} private
Largest retire_prior_to value received.
Definition at line 252 of file connection_id_manager.h.
{0};
Referenced by largest_retire_prior_to().
peer_cids_
std::vector<connection_id_entry> kcenon::network::protocols::quic::connection_id_manager::peer_cids_ private
Peer connection IDs.
Definition at line 246 of file connection_id_manager.h.
Referenced by available_peer_cids(), count_active_cids(), get_active_peer_cid(), peer_cid_count(), retire_cids_prior_to(), and set_initial_peer_cid().
pending_retire_frames_
std::vector<retire_connection_id_frame> kcenon::network::protocols::quic::connection_id_manager::pending_retire_frames_ private
Pending RETIRE_CONNECTION_ID frames to send.
Definition at line 255 of file connection_id_manager.h.
Referenced by clear_pending_retire_frames(), and retire_cids_prior_to().
The documentation for this class was generated from the following files:
src/internal/protocols/quic/connection_id_manager.h
src/protocols/quic/connection_id_manager.cpp