Network System: kcenon::network::unified::adapters::udp_listener_adapter Class Reference
kcenon::network::unified::adapters::udp_listener_adapter Class Reference
Adapter that wraps messaging_udp_server to implement i_listener.
#include <udp_listener_adapter.h>
Public Member Functions
udp_listener_adapter (std::string_view listener_id)
Constructs an adapter with a unique listener ID.
~udp_listener_adapter () override
Destructor ensures proper cleanup.
udp_listener_adapter (const udp_listener_adapter &)=delete
udp_listener_adapter & operator= (const udp_listener_adapter &)=delete
udp_listener_adapter (udp_listener_adapter &&)=delete
udp_listener_adapter & operator= (udp_listener_adapter &&)=delete
auto start (const endpoint_info &bind_address) -> VoidResult override
Starts listening for incoming connections.
auto start (uint16_t port) -> VoidResult override
Starts listening on a specific port (all interfaces)
auto stop () noexcept -> void override
Stops listening and closes all connections.
auto set_callbacks (listener_callbacks callbacks) -> void override
Sets all listener callbacks at once.
auto set_accept_callback (accept_callback_t callback) -> void override
Sets the accept callback for new connections.
auto is_listening () const noexcept -> bool override
Checks if the listener is currently listening.
auto local_endpoint () const noexcept -> endpoint_info override
Gets the local endpoint the listener is bound to.
auto connection_count () const noexcept -> size_t override
Gets the number of active connections.
auto send_to (std::string_view connection_id, std::span< const std::byte > data) -> VoidResult override
Sends data to a specific connection.
auto broadcast (std::span< const std::byte > data) -> VoidResult override
Broadcasts data to all connected clients.
auto close_connection (std::string_view connection_id) noexcept -> void override
Closes a specific connection.
auto wait_for_stop () -> void override
Blocks until the listener has stopped.
Public Member Functions inherited from kcenon::network::unified::i_listener
virtual ~i_listener ()=default
Virtual destructor.
i_listener (const i_listener &)=delete
i_listener & operator= (const i_listener &)=delete
i_listener (i_listener &&)=default
i_listener & operator= (i_listener &&)=default
Private Member Functions
auto setup_internal_callbacks () -> void
Sets up internal callbacks to bridge to unified callbacks.
Static Private Member Functions
static auto make_connection_id (const std::string &address, uint16_t port) -> std::string
Generates a connection ID from an endpoint.
static auto parse_connection_id (std::string_view connection_id) -> std::optional< endpoint_info >
Parses a connection ID back to endpoint info.
Private Attributes
std::string listener_id_
std::shared_ptr< core::messaging_udp_server > server_
std::mutex callbacks_mutex_
listener_callbacks callbacks_
accept_callback_t accept_callback_
std::mutex endpoint_mutex_
endpoint_info local_endpoint_
std::mutex connections_mutex_
std::unordered_map< std::string, endpoint_info > known_endpoints_
Additional Inherited Members
Public Types inherited from kcenon::network::unified::i_listener
using accept_callback_t = std::function< void(std::unique_ptr< i_connection >)>
Callback for accepted connections.
Protected Member Functions inherited from kcenon::network::unified::i_listener
i_listener ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps messaging_udp_server to implement i_listener.
This adapter bridges the existing UDP server implementation with the new unified interface. Note that UDP is connectionless - there are no real "connections" to accept. Instead, we track unique remote endpoints that send data to us.
Thread Safety
Thread-safe. All methods can be called from any thread.
Ownership
The adapter owns the underlying server via shared_ptr for proper RAII.
UDP Semantics
start() binds to a local port and begins receiving datagrams
Each unique sender endpoint is tracked as a virtual "connection"
on_accept callback is triggered when a new endpoint sends data
send_to() and broadcast() send datagrams to specific/all endpoints
Definition at line 67 of file udp_listener_adapter.h.
Constructor & Destructor Documentation
udp_listener_adapter() [1/3]
kcenon::network::unified::adapters::udp_listener_adapter::udp_listener_adapter (std::string_view listener_id) explicit
Constructs an adapter with a unique listener ID.
Parameters
listener_id Unique identifier for this listener
Definition at line 41 of file udp_listener_adapter.cpp.
    : listener_id_(listener_id)
    , server_(std::make_shared<core::messaging_udp_server>(listener_id))
{
    setup_internal_callbacks();
}
References setup_internal_callbacks().
~udp_listener_adapter()
kcenon::network::unified::adapters::udp_listener_adapter::~udp_listener_adapter () override
Destructor ensures proper cleanup.
Definition at line 48 of file udp_listener_adapter.cpp.
{
    stop();
}
References stop().
udp_listener_adapter() [2/3]
kcenon::network::unified::adapters::udp_listener_adapter::udp_listener_adapter (const udp_listener_adapter &) delete
udp_listener_adapter() [3/3]
kcenon::network::unified::adapters::udp_listener_adapter::udp_listener_adapter (udp_listener_adapter &&) delete
Member Function Documentation
broadcast()
auto kcenon::network::unified::adapters::udp_listener_adapter::broadcast (std::span< const std::byte > data) -> VoidResult override virtual
Broadcasts data to all connected clients.
Parameters
data The data to send to all connections
Returns
VoidResult indicating success or failure
Behavior
Sends data to all currently connected clients
Returns success if at least one send succeeded
Failures on individual connections are logged but don't fail the call
Implements kcenon::network::unified::i_listener.
Definition at line 168 of file udp_listener_adapter.cpp.
{
    if (!server_ || !server_->is_running()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "Server is not running"
        );
    }
    std::vector<std::pair<std::string, endpoint_info>> endpoints_copy;
    {
        std::lock_guard lock(connections_mutex_);
        endpoints_copy.reserve(known_endpoints_.size());
        for (const auto& [id, ep] : known_endpoints_) {
            endpoints_copy.emplace_back(id, ep);
        }
    }
    if (endpoints_copy.empty()) {
        return ok();  // No endpoints to broadcast to
    }
    VoidResult last_result = ok();
    for (const auto& [conn_id, ep] : endpoints_copy) {
        auto result = send_to(conn_id, data);
        if (!result.is_ok()) {
            last_result = result;  // Return last error if any failed
        }
    }
    return last_result;
}
References kcenon::network::error_void(), and kcenon::network::ok().
close_connection()
auto kcenon::network::unified::adapters::udp_listener_adapter::close_connection (std::string_view connection_id) -> void override virtual noexcept
Closes a specific connection.
Parameters
connection_id The ID of the connection to close
Triggers the on_disconnect callback for the connection.
Implements kcenon::network::unified::i_listener.
Definition at line 201 of file udp_listener_adapter.cpp.
{
    std::string conn_id_str(connection_id);
    {
        std::lock_guard lock(connections_mutex_);
        known_endpoints_.erase(conn_id_str);
    }
    std::lock_guard lock(callbacks_mutex_);
    if (callbacks_.on_disconnect) {
        callbacks_.on_disconnect(connection_id);
    }
}
connection_count()
auto kcenon::network::unified::adapters::udp_listener_adapter::connection_count () const -> size_t override virtual noexcept
Gets the number of active connections.
Returns
The count of currently connected clients
Implements kcenon::network::unified::i_listener.
Definition at line 134 of file udp_listener_adapter.cpp.
{
    std::lock_guard lock(connections_mutex_);
    return known_endpoints_.size();
}
References connections_mutex_, and known_endpoints_.
is_listening()
auto kcenon::network::unified::adapters::udp_listener_adapter::is_listening () const -> bool override virtual noexcept
Checks if the listener is currently listening.
Returns
true if listening for connections, false otherwise
Implements kcenon::network::unified::i_listener.
Definition at line 123 of file udp_listener_adapter.cpp.
{
    return server_ && server_->is_running();
}
References server_.
local_endpoint()
auto kcenon::network::unified::adapters::udp_listener_adapter::local_endpoint () const -> endpoint_info override virtual noexcept
Gets the local endpoint the listener is bound to.
Returns
endpoint_info of the local binding
Returns valid information only when listening. Returns empty endpoint_info if not bound.
Implements kcenon::network::unified::i_listener.
Definition at line 128 of file udp_listener_adapter.cpp.
{
    std::lock_guard lock(endpoint_mutex_);
    return local_endpoint_;
}
References endpoint_mutex_, and local_endpoint_.
make_connection_id()
auto kcenon::network::unified::adapters::udp_listener_adapter::make_connection_id (const std::string & address, uint16_t port) -> std::string static private
Generates a connection ID from an endpoint.
Definition at line 277 of file udp_listener_adapter.cpp.
{
    std::ostringstream oss;
    oss << address << ":" << port;
    return oss.str();
}
operator=() [1/2]
udp_listener_adapter & kcenon::network::unified::adapters::udp_listener_adapter::operator= (const udp_listener_adapter &) delete
operator=() [2/2]
udp_listener_adapter & kcenon::network::unified::adapters::udp_listener_adapter::operator= (udp_listener_adapter &&) delete
parse_connection_id()
auto kcenon::network::unified::adapters::udp_listener_adapter::parse_connection_id (std::string_view connection_id) -> std::optional<endpoint_info> static private
Parses a connection ID back to endpoint info.
Definition at line 284 of file udp_listener_adapter.cpp.
{
    std::string conn_str(connection_id);
    auto colon_pos = conn_str.rfind(':');
    if (colon_pos == std::string::npos) {
        return std::nullopt;
    }
    std::string host = conn_str.substr(0, colon_pos);
    std::string port_str = conn_str.substr(colon_pos + 1);
    uint16_t port = 0;
    try {
        port = static_cast<uint16_t>(std::stoi(port_str));
    } catch (...) {
        return std::nullopt;
    }
    return endpoint_info{host, port};
}
send_to()
auto kcenon::network::unified::adapters::udp_listener_adapter::send_to (std::string_view connection_id, std::span< const std::byte > data) -> VoidResult override virtual
Sends data to a specific connection.
Parameters
connection_id The ID of the target connection
data The data to send
Returns
VoidResult indicating success or failure
Error Conditions
Returns error if connection_id not found
Returns error if send fails
Implements kcenon::network::unified::i_listener.
Definition at line 140 of file udp_listener_adapter.cpp.
{
    if (!server_ || !server_->is_running()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "Server is not running"
        );
    }
    auto ep_opt = parse_connection_id(connection_id);
    if (!ep_opt) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "Invalid connection ID format"
        );
    }
    interfaces::i_udp_server::endpoint_info target_ep;
    target_ep.address = ep_opt->host;
    target_ep.port = ep_opt->port;
    std::vector<uint8_t> buffer(data.size());
    std::memcpy(buffer.data(), data.data(), data.size());
    return server_->send_to(target_ep, std::move(buffer));
}
References kcenon::network::interfaces::i_udp_client::endpoint_info::address, kcenon::network::error_void(), and kcenon::network::interfaces::i_udp_client::endpoint_info::port.
set_accept_callback()
auto kcenon::network::unified::adapters::udp_listener_adapter::set_accept_callback (accept_callback_t callback) -> void override virtual
Sets the accept callback for new connections.
Parameters
callback Called when a connection is accepted
This callback receives ownership of the connection object. If set, the on_accept callback in listener_callbacks is not called.
Thread Safety
Thread-safe. Callback invoked from I/O thread.
Implements kcenon::network::unified::i_listener.
Definition at line 117 of file udp_listener_adapter.cpp.
{
    std::lock_guard lock(callbacks_mutex_);
    accept_callback_ = std::move(callback);
}
set_callbacks()
auto kcenon::network::unified::adapters::udp_listener_adapter::set_callbacks (listener_callbacks callbacks) -> void override virtual
Sets all listener callbacks at once.
Parameters
callbacks The callback structure with handlers
Replaces all previously set callbacks.
Thread Safety
Thread-safe, but callbacks are invoked from I/O threads.
Implements kcenon::network::unified::i_listener.
Definition at line 108 of file udp_listener_adapter.cpp.
{
    {
        std::lock_guard lock(callbacks_mutex_);
        callbacks_ = std::move(callbacks);
    }
    setup_internal_callbacks();
}
setup_internal_callbacks()
auto kcenon::network::unified::adapters::udp_listener_adapter::setup_internal_callbacks () -> void private
Sets up internal callbacks to bridge to unified callbacks.
Definition at line 223 of file udp_listener_adapter.cpp.
{
    if (!server_) {
        return;
    }
    // Bridge receive callback - also handles "connection" tracking for UDP
    server_->set_receive_callback(
        [this](const std::vector<uint8_t>& data,
               const interfaces::i_udp_server::endpoint_info& sender) {
            std::string conn_id = make_connection_id(sender.address, sender.port);
            bool is_new_endpoint = false;
            {
                std::lock_guard lock(connections_mutex_);
                if (known_endpoints_.find(conn_id) == known_endpoints_.end()) {
                    known_endpoints_[conn_id] = endpoint_info{sender.address, sender.port};
                    is_new_endpoint = true;
                }
            }
            // If this is a new endpoint, trigger on_accept
            if (is_new_endpoint) {
                std::lock_guard lock(callbacks_mutex_);
                if (callbacks_.on_accept) {
                    callbacks_.on_accept(conn_id);
                }
                // Note: accept_callback_ with unique_ptr<i_connection> doesn't make
                // sense for UDP since there's no real connection object to hand over
            }
            // Forward data to callback
            {
                std::lock_guard lock(callbacks_mutex_);
                if (callbacks_.on_data) {
                    std::span<const std::byte> byte_span(
                        reinterpret_cast<const std::byte*>(data.data()),
                        data.size()
                    );
                    callbacks_.on_data(conn_id, byte_span);
                }
            }
        });
    // Bridge error callback
    server_->set_error_callback([this](std::error_code ec) {
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_error) {
            // For server-level errors, use empty connection ID
            callbacks_.on_error("", ec);
        }
    });
}
References kcenon::network::interfaces::i_udp_client::endpoint_info::address, and kcenon::network::interfaces::i_udp_client::endpoint_info::port.
Referenced by udp_listener_adapter().
start() [1/2]
auto kcenon::network::unified::adapters::udp_listener_adapter::start (const endpoint_info & bind_address) -> VoidResult override virtual
Starts listening for incoming connections.
Parameters
bind_address The local address to bind to
Returns
VoidResult indicating success or failure
Behavior
Binds to the specified local address
Begins accepting incoming connections
Accepted connections are delivered via callbacks
Error Conditions
Returns error if already listening
Returns error if bind fails (e.g., address in use)
Returns error if listen fails
Thread Safety
Thread-safe. Only one start operation can succeed at a time.
Implements kcenon::network::unified::i_listener.
Definition at line 53 of file udp_listener_adapter.cpp.
{
    if (!server_) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "Server is not initialized"
        );
    }
    if (server_->is_running()) {
        return error_void(
            static_cast<int>(std::errc::already_connected),
            "Already listening"
        );
    }
    {
        std::lock_guard lock(endpoint_mutex_);
        local_endpoint_ = bind_address;
    }
    // Clear known endpoints when starting fresh
    {
        std::lock_guard lock(connections_mutex_);
        known_endpoints_.clear();
    }
    return server_->start_server(bind_address.port);
}
References kcenon::network::error_void().
start() [2/2]
auto kcenon::network::unified::adapters::udp_listener_adapter::start (uint16_t port) -> VoidResult override virtual
Starts listening on a specific port (all interfaces)
Parameters
port The port number to listen on
Returns
VoidResult indicating success or failure
Convenience overload that binds to all interfaces (0.0.0.0 / ::).
Implements kcenon::network::unified::i_listener.
Definition at line 83 of file udp_listener_adapter.cpp.
{
    return start(endpoint_info{"0.0.0.0", port});
}
stop()
auto kcenon::network::unified::adapters::udp_listener_adapter::stop () -> void override virtual noexcept
Stops listening and closes all connections.
Behavior
Stops accepting new connections
Closes all active connections
Triggers on_disconnect callback for each connection
Thread Safety
Thread-safe. Safe to call multiple times.
Implements kcenon::network::unified::i_listener.
Definition at line 88 of file udp_listener_adapter.cpp.
{
    if (server_ && server_->is_running()) {
        // Notify disconnection for all known endpoints
        {
            std::lock_guard cb_lock(callbacks_mutex_);
            std::lock_guard conn_lock(connections_mutex_);
            if (callbacks_.on_disconnect) {
                for (const auto& [conn_id, _] : known_endpoints_) {
                    callbacks_.on_disconnect(conn_id);
                }
            }
            known_endpoints_.clear();
        }
        (void)server_->stop_server();
    }
}
References callbacks_, callbacks_mutex_, connections_mutex_, known_endpoints_, kcenon::network::unified::listener_callbacks::on_disconnect, and server_.
Referenced by ~udp_listener_adapter().
wait_for_stop()
auto kcenon::network::unified::adapters::udp_listener_adapter::wait_for_stop () -> void override virtual
Blocks until the listener has stopped.
Waits for all connections to close and the listener to fully stop.
Thread Safety
Safe to call from any thread.
Implements kcenon::network::unified::i_listener.
Definition at line 216 of file udp_listener_adapter.cpp.
{
    if (server_) {
        server_->wait_for_stop();
    }
}
Member Data Documentation
accept_callback_
accept_callback_t kcenon::network::unified::adapters::udp_listener_adapter::accept_callback_ private
Definition at line 125 of file udp_listener_adapter.h.
callbacks_
listener_callbacks kcenon::network::unified::adapters::udp_listener_adapter::callbacks_ private
Definition at line 124 of file udp_listener_adapter.h.
Referenced by stop().
callbacks_mutex_
std::mutex kcenon::network::unified::adapters::udp_listener_adapter::callbacks_mutex_ mutable private
Definition at line 123 of file udp_listener_adapter.h.
Referenced by stop().
connections_mutex_
std::mutex kcenon::network::unified::adapters::udp_listener_adapter::connections_mutex_ mutable private
Definition at line 131 of file udp_listener_adapter.h.
Referenced by connection_count(), and stop().
endpoint_mutex_
std::mutex kcenon::network::unified::adapters::udp_listener_adapter::endpoint_mutex_ mutable private
Definition at line 127 of file udp_listener_adapter.h.
Referenced by local_endpoint().
known_endpoints_
std::unordered_map<std::string, endpoint_info> kcenon::network::unified::adapters::udp_listener_adapter::known_endpoints_ private
Definition at line 132 of file udp_listener_adapter.h.
Referenced by connection_count(), and stop().
listener_id_
std::string kcenon::network::unified::adapters::udp_listener_adapter::listener_id_ private
Definition at line 120 of file udp_listener_adapter.h.
local_endpoint_
endpoint_info kcenon::network::unified::adapters::udp_listener_adapter::local_endpoint_ private
Definition at line 128 of file udp_listener_adapter.h.
Referenced by local_endpoint().
server_
std::shared_ptr<core::messaging_udp_server> kcenon::network::unified::adapters::udp_listener_adapter::server_ private
Definition at line 121 of file udp_listener_adapter.h.
Referenced by is_listening(), and stop().
The documentation for this class was generated from the following files:
src/internal/unified/adapters/udp_listener_adapter.h
src/unified/adapters/udp_listener_adapter.cpp