Network System: kcenon::network::integration::logger_integration_manager::impl Class Reference
kcenon::network::integration::logger_integration_manager::impl Class Reference
Public Member Functions
impl ()
void set_logger (std::shared_ptr< logger_interface > logger)
std::shared_ptr< logger_interface > get_logger ()
void log (log_level level, const std::string &message)
void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function)
Private Attributes
std::mutex mutex_
std::shared_ptr< logger_interface > logger_
Detailed Description
Definition at line 228 of file logger_integration.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::integration::logger_integration_manager::impl::impl () inline
Definition at line 230 of file logger_integration.cpp.
           {
#if KCENON_WITH_COMMON_SYSTEM
        // Use common_system_logger_adapter by default
        // It delegates to GlobalLoggerRegistry which provides NullLogger fallback
        logger_ = std::make_shared<common_system_logger_adapter>();
#else
        // Use basic_logger for standalone operation
        logger_ = std::make_shared<basic_logger>();
#endif
    }
References logger_.
Member Function Documentation
get_logger()
std::shared_ptr< logger_interface > kcenon::network::integration::logger_integration_manager::impl::get_logger () inline
Definition at line 246 of file logger_integration.cpp.
{
        std::lock_guard<std::mutex> lock(mutex_);
        if (!logger_) {
#if KCENON_WITH_COMMON_SYSTEM
            logger_ = std::make_shared<common_system_logger_adapter>();
#else
            logger_ = std::make_shared<basic_logger>();
#endif
        }
        return logger_;
    }
References logger_, and mutex_.
Referenced by kcenon::network::integration::logger_integration_manager::get_logger(), log(), and log().
log() [1/2]
void kcenon::network::integration::logger_integration_manager::impl::log (log_level level, const std::string & message) inline
Definition at line 258 of file logger_integration.cpp.
{
#if KCENON_WITH_COMMON_SYSTEM
        // Delegate directly to common_system's GlobalLoggerRegistry
        auto common_logger = kcenon::common::interfaces::get_logger();
        if (common_logger) {
            common_logger->log(to_common_level(level), message);
        }
#else
        auto logger = get_logger();
        if (logger) {
            logger->log(level, message);
        }
#endif
    }
References get_logger(), and kcenon::network::message.
Referenced by kcenon::network::integration::logger_integration_manager::log(), and kcenon::network::integration::logger_integration_manager::log().
log() [2/2]
void kcenon::network::integration::logger_integration_manager::impl::log (log_level level, const std::string & message, const std::string & file, int line, const std::string & function) inline
Definition at line 273 of file logger_integration.cpp.
{
#if KCENON_WITH_COMMON_SYSTEM
        // Delegate directly to common_system's GlobalLoggerRegistry
        // Use log_entry API for common_system v3.0.0 compatibility
        auto common_logger = kcenon::common::interfaces::get_logger();
        if (common_logger) {
            kcenon::common::interfaces::log_entry entry;
            entry.level = to_common_level(level);
            entry.message = message;
            entry.file = file;
            entry.line = line;
            entry.function = function;
            entry.timestamp = std::chrono::system_clock::now();
            common_logger->log(entry);
        }
#else
        auto logger = get_logger();
        if (logger) {
            logger->log(level, message, file, line, function);
        }
#endif
    }
References get_logger(), and kcenon::network::message.
set_logger()
void kcenon::network::integration::logger_integration_manager::impl::set_logger (std::shared_ptr< logger_interface > logger) inline
Definition at line 241 of file logger_integration.cpp.
{
        std::lock_guard<std::mutex> lock(mutex_);
        logger_ = logger;
    }
References logger_, and mutex_.
Referenced by kcenon::network::integration::logger_integration_manager::set_logger().
Member Data Documentation
logger_
std::shared_ptr<logger_interface> kcenon::network::integration::logger_integration_manager::impl::logger_ private
Definition at line 299 of file logger_integration.cpp.
Referenced by get_logger(), impl(), and set_logger().
mutex_
std::mutex kcenon::network::integration::logger_integration_manager::impl::mutex_ mutable private
Definition at line 298 of file logger_integration.cpp.
Referenced by get_logger(), and set_logger().
The documentation for this class was generated from the following file:
src/integration/logger_integration.cpp