Network System: kcenon::network::core::messaging_udp_client Class Reference
kcenon::network::core::messaging_udp_client Class Reference export
module kcenon.network
A UDP client that sends datagrams to a target endpoint and can receive responses.
#include <messaging_udp_client.h>
Public Types
using receive_callback_t
Callback type for received datagrams with sender endpoint.
using error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
using udp_data_callback
Callback type for UDP data reception.
Public Types inherited from kcenon::network::interfaces::i_udp_client
using receive_callback_t
Callback type for received data (includes sender endpoint)
using error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
using send_callback_t = std::function<void(std::error_code, std::size_t)>
Callback type for send completion.
Public Member Functions
messaging_udp_client (std::string_view client_id)
Constructs a messaging_udp_client with an identifier.
~messaging_udp_client () noexcept override
Destructor. Automatically calls stop_client() if the client is still running.
messaging_udp_client (const messaging_udp_client &)=delete
messaging_udp_client & operator= (const messaging_udp_client &)=delete
messaging_udp_client (messaging_udp_client &&)=delete
messaging_udp_client & operator= (messaging_udp_client &&)=delete
auto start_client (std::string_view host, uint16_t port) -> VoidResult
Starts the client by resolving target host and port.
auto stop_client () -> VoidResult
Stops the client and releases all resources.
auto client_id () const -> const std::string &
Returns the client identifier.
auto is_running () const -> bool override
Checks if the client is currently running.
auto wait_for_stop () -> void override
Blocks until stop_client() is called.
auto start (std::string_view host, uint16_t port) -> VoidResult override
Starts the UDP client targeting the specified endpoint.
auto stop () -> VoidResult override
Stops the UDP client.
auto send (std::vector< uint8_t > &&data, interfaces::i_udp_client::send_callback_t handler=nullptr) -> VoidResult override
Sends a datagram to the configured target endpoint.
auto set_target (std::string_view host, uint16_t port) -> VoidResult override
Changes the target endpoint for future sends.
auto set_receive_callback (interfaces::i_udp_client::receive_callback_t callback) -> void override
Sets the callback for received datagrams (interface version).
auto set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received datagrams (legacy version).
auto set_error_callback (error_callback_t callback) -> void override
Sets the callback for errors.
messaging_udp_client (std::string_view client_id)
Construct a UDP client with a given client_id.
virtual ~messaging_udp_client () noexcept
Destructor - automatically stops the client if running.
messaging_udp_client (const messaging_udp_client &)=delete
messaging_udp_client & operator= (const messaging_udp_client &)=delete
messaging_udp_client (messaging_udp_client &&) noexcept
messaging_udp_client & operator= (messaging_udp_client &&) noexcept
bool start_client (std::string_view remote_host, uint16_t remote_port, uint16_t local_port=0)
Start the client and bind to an endpoint.
void stop_client ()
Stop the client.
bool send_packet (std::span< const uint8_t > data)
Send a datagram to the configured remote endpoint.
bool send_packet (std::string_view data)
Send a string datagram to the configured remote endpoint.
bool send_to (std::span< const uint8_t > data, std::string_view host, uint16_t port)
Send a datagram to a specific endpoint.
bool is_running () const noexcept
Check if the client is running.
std::string_view client_id () const noexcept
Get the client identifier.
void set_data_callback (udp_data_callback callback)
Set data received callback.
void set_error_callback (error_callback callback)
Set error callback.
bool join_multicast_group (std::string_view multicast_address)
Enable multicast reception.
bool leave_multicast_group (std::string_view multicast_address)
Leave multicast group.
Public Member Functions inherited from kcenon::network::interfaces::i_udp_client
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Types
using callback_index = udp_client_callback
Callback index type alias for clarity.
using callbacks_t
Callback manager type for this client.
Private Member Functions
auto do_start_impl (std::string_view host, uint16_t port) -> VoidResult
UDP-specific implementation of client start.
auto do_stop_impl () -> VoidResult
UDP-specific implementation of client stop.
auto invoke_receive_callback (const std::vector< uint8_t > &data, const asio::ip::udp::endpoint &endpoint) -> void
Invokes the receive callback with the given data and endpoint.
auto invoke_error_callback (std::error_code ec) -> void
Invokes the error callback with the given error code.
auto get_receive_callback () const -> receive_callback_t
Gets a copy of the receive callback.
auto get_error_callback () const -> error_callback_t
Gets a copy of the error callback.
Private Attributes
std::string client_id_
utils::lifecycle_manager lifecycle_
callbacks_t callbacks_
std::unique_ptr< asio::io_context > io_context_
std::shared_ptr< internal::udp_socket > socket_
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::future< void > io_context_future_
std::mutex endpoint_mutex_
asio::ip::udp::endpoint target_endpoint_
std::mutex socket_mutex_
std::unique_ptr< impl > pimpl_
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
A UDP client that sends datagrams to a target endpoint and can receive responses.
A UDP client for datagram messaging.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling. It also implements the i_udp_client interface for composition-based usage.
Thread Safety
All public methods are thread-safe.
Socket access is protected by socket_mutex_.
Atomic flags prevent race conditions.
send_packet() can be called from any thread safely.
Key Characteristics
Connectionless: No persistent connection, each send is independent.
Target endpoint: Configured at start, can be changed via set_target().
Bidirectional: Can both send and receive datagrams.
Stateless: No built-in acknowledgment or reliability.
Interface Compliance
This class implements interfaces::i_udp_client for composition-based usage.
Usage Example
auto client = std::make_shared<messaging_udp_client>("UDPClient");
// Set callback to handle received datagrams (using interface callback)
client->set_receive_callback(
    [](const std::vector<uint8_t>& data,
       const interfaces::i_udp_client::endpoint_info& sender) {
        std::cout << "Received " << data.size() << " bytes from "
                  << sender.address << ":" << sender.port << "\n";
    });
// Start client targeting localhost:5555
auto result = client->start_client("localhost", 5555);
if (!result) {
    std::cerr << "Failed to start client: " << result.error().message << "\n";
    return -1;
}
// Send a datagram using send()
std::vector<uint8_t> data = {0x01, 0x02, 0x03};
client->send(std::move(data),
    [](std::error_code ec, std::size_t bytes) {
        if (!ec) {
            std::cout << "Sent " << bytes << " bytes\n";
        }
    });
// Stop client
client->stop_client();
This class provides a UDP client that sends and receives datagrams to/from a remote endpoint. Unlike TCP, UDP is connectionless and does not guarantee delivery order or reliability.
Thread Safety
All public methods are thread-safe.
Socket access is protected by internal mutex.
Key Features
Connectionless datagram messaging
Low latency for real-time applications
Multicast support
Optional reliable delivery layer
import kcenon.network;
auto client = std::make_unique<kcenon::network::core::messaging_udp_client>("udp_client");
client->set_data_callback([](std::span<const uint8_t> data,
                              const std::string& from_addr,
                              uint16_t from_port) {
    std::cout << "Received from " << from_addr << ":" << from_port << std::endl;
});
client->start_client("localhost", 8080);
Definition at line 80 of file udp.cppm.
Member Typedef Documentation
callback_index
using kcenon::network::core::messaging_udp_client::callback_index = udp_client_callback private
Callback index type alias for clarity.
Definition at line 293 of file messaging_udp_client.h.
callbacks_t
using kcenon::network::core::messaging_udp_client::callbacks_t private
Initial value:
 utils::callback_manager<
            receive_callback_t,
            error_callback_t
        >
Callback manager type for this client.
Definition at line 296 of file messaging_udp_client.h.
error_callback_t
using kcenon::network::core::messaging_udp_client::error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Definition at line 103 of file messaging_udp_client.h.
receive_callback_t
using kcenon::network::core::messaging_udp_client::receive_callback_t
Initial value:
 std::function<void(const std::vector<uint8_t>&,
                                                      const asio::ip::udp::endpoint&)>
Callback type for received datagrams with sender endpoint.
Definition at line 100 of file messaging_udp_client.h.
udp_data_callback
using kcenon::network::core::messaging_udp_client::udp_data_callback export
Initial value:
 std::function<void(
        std::span<const uint8_t> data,
        const std::string& from_address,
        uint16_t from_port)>
Callback type for UDP data reception.
Definition at line 85 of file udp.cppm.
Constructor & Destructor Documentation
messaging_udp_client() [1/6]
kcenon::network::core::messaging_udp_client::messaging_udp_client (std::string_view client_id) explicit
Constructs a messaging_udp_client with an identifier.
Parameters
client_id A string identifier for this client instance.
Definition at line 14 of file messaging_udp_client.cpp.
        : client_id_(client_id)
    {
    }
~messaging_udp_client() [1/2]
kcenon::network::core::messaging_udp_client::~messaging_udp_client () override noexcept
Destructor. Automatically calls stop_client() if the client is still running.
Definition at line 19 of file messaging_udp_client.cpp.
    {
        if (lifecycle_.is_running())
        {
            (void)stop_client();
        }
    }
References kcenon::network::utils::lifecycle_manager::is_running(), lifecycle_, and stop_client().
messaging_udp_client() [2/6]
kcenon::network::core::messaging_udp_client::messaging_udp_client (const messaging_udp_client &) delete
messaging_udp_client() [3/6]
kcenon::network::core::messaging_udp_client::messaging_udp_client (messaging_udp_client &&) delete
messaging_udp_client() [4/6]
kcenon::network::core::messaging_udp_client::messaging_udp_client (std::string_view client_id) explicit export
Construct a UDP client with a given client_id.
Parameters
client_id A string identifier for this client instance
~messaging_udp_client() [2/2]
virtual kcenon::network::core::messaging_udp_client::~messaging_udp_client () export virtual noexcept
Destructor - automatically stops the client if running.
messaging_udp_client() [5/6]
kcenon::network::core::messaging_udp_client::messaging_udp_client (const messaging_udp_client &) export delete
messaging_udp_client() [6/6]
kcenon::network::core::messaging_udp_client::messaging_udp_client (messaging_udp_client &&) export noexcept
Member Function Documentation
client_id() [1/2]
auto kcenon::network::core::messaging_udp_client::client_id () const -> const std::string& nodiscard
Returns the client identifier.
Returns
The client_id string.
Definition at line 75 of file messaging_udp_client.cpp.
    {
        return client_id_;
    }
References client_id_.
client_id() [2/2]
std::string_view kcenon::network::core::messaging_udp_client::client_id () const export noexcept
Get the client identifier.
Returns
Client ID string
do_start_impl()
auto kcenon::network::core::messaging_udp_client::do_start_impl (std::string_view host, uint16_t port) -> VoidResult private
UDP-specific implementation of client start.
Parameters
host The target hostname or IP address.
port The target port number.
Returns
Result<void> - Success if client started, or error with code.
Creates io_context, resolves target, creates socket, and starts worker thread.
Definition at line 223 of file messaging_udp_client.cpp.
    {
        try
        {
            // Create io_context
            io_context_ = std::make_unique<asio::io_context>();
            // Resolve target endpoint
            udp::resolver resolver(*io_context_);
            auto endpoints = resolver.resolve(udp::v4(), std::string(host), std::to_string(port));
            if (endpoints.empty())
            {
                return error_void(
                    error_codes::common_errors::internal_error,
                    "Failed to resolve host",
                    "messaging_udp_client::do_start_impl",
                    "Host: " + std::string(host)
                );
            }
            {
                std::lock_guard<std::mutex> lock(endpoint_mutex_);
                target_endpoint_ = *endpoints.begin();
            }
            // Create UDP socket (bind to any port)
            asio::ip::udp::socket raw_socket(*io_context_, udp::endpoint(udp::v4(), 0));
            // Wrap in our udp_socket
            socket_ = std::make_shared<internal::udp_socket>(std::move(raw_socket));
            // Set callbacks to socket
            auto receive_cb = get_receive_callback();
            if (receive_cb)
            {
                socket_->set_receive_callback(std::move(receive_cb));
            }
            auto error_cb = get_error_callback();
            if (error_cb)
            {
                socket_->set_error_callback(std::move(error_cb));
            }
            // Start receiving
            socket_->start_receive();
            // Get thread pool from network context
            thread_pool_ = network_context::instance().get_thread_pool();
            if (!thread_pool_) {
                // Fallback: create a temporary thread pool if network_context is not initialized
                NETWORK_LOG_WARN("[messaging_udp_client] network_context not initialized, creating temporary thread pool");
                thread_pool_ = std::make_shared<integration::basic_thread_pool>(std::thread::hardware_concurrency());
            }
            // Start io_context on thread pool
            io_context_future_ = thread_pool_->submit(
                [this]()
                {
                    try
                    {
                        NETWORK_LOG_DEBUG("[messaging_udp_client] io_context started");
                        io_context_->run();
                        NETWORK_LOG_DEBUG("[messaging_udp_client] io_context stopped");
                    }
                    catch (const std::exception& e)
                    {
                        NETWORK_LOG_ERROR(std::string("Worker thread exception: ") + e.what());
                    }
                });
            NETWORK_LOG_INFO("UDP client started targeting " + std::string(host) + ":" + std::to_string(port));
            return ok();
        }
        catch (const std::system_error& e)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                std::string("Failed to create UDP socket: ") + e.what(),
                "messaging_udp_client::do_start_impl",
                "Host: " + std::string(host) + ":" + std::to_string(port)
            );
        }
        catch (const std::exception& e)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                std::string("Failed to start UDP client: ") + e.what(),
                "messaging_udp_client::do_start_impl",
                "Host: " + std::string(host) + ":" + std::to_string(port)
            );
        }
    }
References kcenon::network::error_void(), kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_DEBUG, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, NETWORK_LOG_WARN, kcenon::network::ok(), and kcenon::network::integration::thread_pool_interface::submit().
do_stop_impl()
auto kcenon::network::core::messaging_udp_client::do_stop_impl () -> VoidResult private
UDP-specific implementation of client stop.
Returns
Result<void> - Success if client stopped, or error with code.
Stops receiving, closes socket, and releases resources.
Definition at line 319 of file messaging_udp_client.cpp.
    {
        try
        {
            // Stop receiving
            if (socket_)
            {
                socket_->stop_receive();
            }
            // Stop io_context
            if (io_context_)
            {
                io_context_->stop();
            }
            // Wait for io_context task to complete
            if (io_context_future_.valid())
            {
                try {
                    io_context_future_.wait();
                } catch (const std::exception& e) {
                    NETWORK_LOG_ERROR("[messaging_udp_client] Exception while waiting for io_context: " +
                                      std::string(e.what()));
                }
            }
            // Clean up
            socket_.reset();
            io_context_.reset();
            NETWORK_LOG_INFO("UDP client stopped");
            return ok();
        }
        catch (const std::exception& e)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                std::string("Failed to stop UDP client: ") + e.what(),
                "messaging_udp_client::do_stop_impl",
                ""
            );
        }
    }
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, and kcenon::network::ok().
get_error_callback()
auto kcenon::network::core::messaging_udp_client::get_error_callback () const -> error_callback_t nodiscard private
Gets a copy of the error callback.
Returns
Copy of the error callback (may be empty).
Definition at line 386 of file messaging_udp_client.cpp.
    {
        return callbacks_.get<to_index(callback_index::error)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
get_receive_callback()
auto kcenon::network::core::messaging_udp_client::get_receive_callback () const -> receive_callback_t nodiscard private
Gets a copy of the receive callback.
Returns
Copy of the receive callback (may be empty).
Definition at line 381 of file messaging_udp_client.cpp.
    {
        return callbacks_.get<to_index(callback_index::receive)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
invoke_error_callback()
auto kcenon::network::core::messaging_udp_client::invoke_error_callback (std::error_code ec) -> void private
Invokes the error callback with the given error code.
Parameters
ec The error code.
Definition at line 376 of file messaging_udp_client.cpp.
    {
        callbacks_.invoke<to_index(callback_index::error)>(ec);
    }
References kcenon::network::to_index().
invoke_receive_callback()
auto kcenon::network::core::messaging_udp_client::invoke_receive_callback (const std::vector< uint8_t > & data, const asio::ip::udp::endpoint & endpoint) -> void private
Invokes the receive callback with the given data and endpoint.
Parameters
data The received data.
endpoint The sender's endpoint.
Definition at line 369 of file messaging_udp_client.cpp.
    {
        callbacks_.invoke<to_index(callback_index::receive)>(data, endpoint);
    }
References kcenon::network::to_index().
is_running() [1/2]
auto kcenon::network::core::messaging_udp_client::is_running () const -> bool nodiscard override virtual
Checks if the client is currently running.
Returns
true if running, false otherwise.
Implements i_network_component::is_running().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 84 of file messaging_udp_client.cpp.
    {
        return lifecycle_.is_running();
    }
References kcenon::network::utils::lifecycle_manager::is_running(), and lifecycle_.
is_running() [2/2]
bool kcenon::network::core::messaging_udp_client::is_running () const export virtual noexcept
Check if the client is running.
Returns
true if running, false otherwise
Implements kcenon::network::interfaces::i_network_component.
join_multicast_group()
bool kcenon::network::core::messaging_udp_client::join_multicast_group (std::string_view multicast_address) export
Enable multicast reception.
Parameters
multicast_address The multicast group address
Returns
true if joined successfully
leave_multicast_group()
bool kcenon::network::core::messaging_udp_client::leave_multicast_group (std::string_view multicast_address) export
Leave multicast group.
Parameters
multicast_address The multicast group address
Returns
true if left successfully
operator=() [1/4]
messaging_udp_client & kcenon::network::core::messaging_udp_client::operator= (const messaging_udp_client &) delete
operator=() [2/4]
messaging_udp_client & kcenon::network::core::messaging_udp_client::operator= (const messaging_udp_client &) export delete
operator=() [3/4]
messaging_udp_client & kcenon::network::core::messaging_udp_client::operator= (messaging_udp_client &&) export noexcept
operator=() [4/4]
messaging_udp_client & kcenon::network::core::messaging_udp_client::operator= (messaging_udp_client &&) delete
send()
auto kcenon::network::core::messaging_udp_client::send (std::vector< uint8_t > && data, interfaces::i_udp_client::send_callback_t handler = nullptr) -> VoidResult nodiscard override virtual
Sends a datagram to the configured target endpoint.
Parameters
data The data to send.
handler Optional completion handler.
Returns
VoidResult indicating success or failure.
Implements i_udp_client::send().
Implements kcenon::network::interfaces::i_udp_client.
Definition at line 108 of file messaging_udp_client.cpp.
    {
        if (!lifecycle_.is_running())
        {
            return error_void(
                error_codes::common_errors::internal_error,
                "UDP client is not running",
                "messaging_udp_client::send",
                ""
            );
        }
        std::lock_guard<std::mutex> socket_lock(socket_mutex_);
        if (!socket_)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                "Socket not available",
                "messaging_udp_client::send",
                ""
            );
        }
        std::lock_guard<std::mutex> endpoint_lock(endpoint_mutex_);
        socket_->async_send_to(std::move(data), target_endpoint_, std::move(handler));
        return ok();
    }
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, and kcenon::network::ok().
send_packet() [1/2]
bool kcenon::network::core::messaging_udp_client::send_packet (std::span< const uint8_t > data) export
Send a datagram to the configured remote endpoint.
Parameters
data The data to send
Returns
true if data was sent
send_packet() [2/2]
bool kcenon::network::core::messaging_udp_client::send_packet (std::string_view data) export
Send a string datagram to the configured remote endpoint.
Parameters
data The string data to send
Returns
true if data was sent
send_to()
bool kcenon::network::core::messaging_udp_client::send_to (std::span< const uint8_t > data, std::string_view host, uint16_t port) export
Send a datagram to a specific endpoint.
Parameters
data The data to send
host The target host address
port The target port number
Returns
true if data was sent
set_data_callback()
void kcenon::network::core::messaging_udp_client::set_data_callback (udp_data_callback callback) export
Set data received callback.
Parameters
callback Function to call when data is received
set_error_callback() [1/2]
void kcenon::network::core::messaging_udp_client::set_error_callback (error_callback callback) export
Set error callback.
Parameters
callback Function to call on errors
set_error_callback() [2/2]
auto kcenon::network::core::messaging_udp_client::set_error_callback (error_callback_t callback) -> void override virtual
Sets the callback for errors.
Parameters
callback The callback function.
Implements i_udp_client::set_error_callback(). Also compatible with legacy error_callback_t (same signature).
Implements kcenon::network::interfaces::i_udp_client.
Definition at line 214 of file messaging_udp_client.cpp.
    {
        callbacks_.set<to_index(callback_index::error)>(std::move(callback));
    }
References kcenon::network::to_index().
set_receive_callback() [1/2]
auto kcenon::network::core::messaging_udp_client::set_receive_callback (interfaces::i_udp_client::receive_callback_t callback) -> void override virtual
Sets the callback for received datagrams (interface version).
Parameters
callback The callback function with endpoint_info.
Implements i_udp_client::set_receive_callback().
Implements kcenon::network::interfaces::i_udp_client.
Definition at line 185 of file messaging_udp_client.cpp.
    {
        if (!callback)
        {
            // Clear the callback
            callbacks_.set<to_index(callback_index::receive)>(nullptr);
            return;
        }
        // Adapt the interface callback to the internal callback type
        // Convert asio::ip::udp::endpoint to endpoint_info
        callbacks_.set<to_index(callback_index::receive)>(
            [callback = std::move(callback)](
                const std::vector<uint8_t>& data,
                const asio::ip::udp::endpoint& endpoint)
            {
                interfaces::i_udp_client::endpoint_info info;
                info.address = endpoint.address().to_string();
                info.port = endpoint.port();
                callback(data, info);
            });
    }
References kcenon::network::to_index().
set_receive_callback() [2/2]
auto kcenon::network::core::messaging_udp_client::set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received datagrams (legacy version).
Parameters
callback The callback function with asio endpoint.
This overload maintains backward compatibility with code using asio::ip::udp::endpoint directly.
Definition at line 209 of file messaging_udp_client.cpp.
    {
        callbacks_.set<to_index(callback_index::receive)>(std::move(callback));
    }
References kcenon::network::to_index().
set_target()
auto kcenon::network::core::messaging_udp_client::set_target (std::string_view host, uint16_t port) -> VoidResult nodiscard override virtual
Changes the target endpoint for future sends.
Parameters
host The new target hostname or IP address.
port The new target port number.
Returns
VoidResult indicating success or failure.
Implements i_udp_client::set_target().
Implements kcenon::network::interfaces::i_udp_client.
Definition at line 139 of file messaging_udp_client.cpp.
    {
        if (!lifecycle_.is_running())
        {
            return error_void(
                error_codes::common_errors::internal_error,
                "UDP client is not running",
                "messaging_udp_client::set_target",
                ""
            );
        }
        try
        {
            // Resolve new target endpoint
            udp::resolver resolver(*io_context_);
            auto endpoints = resolver.resolve(udp::v4(), std::string(host), std::to_string(port));
            if (endpoints.empty())
            {
                return error_void(
                    error_codes::common_errors::internal_error,
                    "Failed to resolve host",
                    "messaging_udp_client::set_target",
                    "Host: " + std::string(host)
                );
            }
            std::lock_guard<std::mutex> lock(endpoint_mutex_);
            target_endpoint_ = *endpoints.begin();
            NETWORK_LOG_INFO("Target updated to " + std::string(host) + ":" + std::to_string(port));
            return ok();
        }
        catch (const std::exception& e)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                std::string("Failed to set target: ") + e.what(),
                "messaging_udp_client::set_target",
                "Host: " + std::string(host) + ":" + std::to_string(port)
            );
        }
    }
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_INFO, and kcenon::network::ok().
start()
auto kcenon::network::core::messaging_udp_client::start (std::string_view host, uint16_t port) -> VoidResult nodiscard override virtual
Starts the UDP client targeting the specified endpoint.
Parameters
host The target hostname or IP address.
port The target port number.
Returns
VoidResult indicating success or failure.
Implements i_udp_client::start(). Delegates to start_client().
Implements kcenon::network::interfaces::i_udp_client.
Definition at line 98 of file messaging_udp_client.cpp.
    {
        return start_client(host, port);
    }
start_client() [1/2]
auto kcenon::network::core::messaging_udp_client::start_client (std::string_view host, uint16_t port) -> VoidResult nodiscard
Starts the client by resolving target host and port.
Parameters
host The target hostname or IP address.
port The target port number.
Returns
Result<void> - Success if client started, or error with code:
error_codes::common_errors::already_exists if already running
error_codes::common_errors::invalid_argument if empty host
error_codes::common_errors::internal_error for other failures
Definition at line 31 of file messaging_udp_client.cpp.
    {
        if (lifecycle_.is_running())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "UDP client is already running",
                "messaging_udp_client::start_client");
        }
        if (host.empty())
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Host cannot be empty",
                "messaging_udp_client::start_client");
        }
        // Mark as running before starting
        lifecycle_.set_running();
        auto result = do_start_impl(host, port);
        if (result.is_err())
        {
            lifecycle_.mark_stopped();
        }
        return result;
    }
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::invalid_argument.
start_client() [2/2]
bool kcenon::network::core::messaging_udp_client::start_client (std::string_view remote_host, uint16_t remote_port, uint16_t local_port = 0) export
Start the client and bind to an endpoint.
Parameters
remote_host The remote host address
remote_port The remote port number
local_port Optional local port to bind (0 for any)
Returns
true if started successfully
stop()
auto kcenon::network::core::messaging_udp_client::stop () -> VoidResult nodiscard override virtual
Stops the UDP client.
Returns
VoidResult indicating success or failure.
Implements i_udp_client::stop(). Delegates to stop_client().
Implements kcenon::network::interfaces::i_udp_client.
Definition at line 103 of file messaging_udp_client.cpp.
    {
        return stop_client();
    }
stop_client() [1/2]
void kcenon::network::core::messaging_udp_client::stop_client () export
Stop the client.
stop_client() [2/2]
auto kcenon::network::core::messaging_udp_client::stop_client () -> VoidResult nodiscard
Stops the client and releases all resources.
Returns
Result<void> - Success if client stopped, or error with code:
error_codes::common_errors::internal_error for failures
Definition at line 61 of file messaging_udp_client.cpp.
    {
        if (!lifecycle_.prepare_stop())
        {
            return ok();  // Not running or already stopping
        }
        auto result = do_stop_impl();
        lifecycle_.mark_stopped();
        return result;
    }
References kcenon::network::ok().
Referenced by ~messaging_udp_client().
wait_for_stop()
auto kcenon::network::core::messaging_udp_client::wait_for_stop () -> void override virtual
Blocks until stop_client() is called.
Implements i_network_component::wait_for_stop().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 89 of file messaging_udp_client.cpp.
    {
        lifecycle_.wait_for_stop();
    }
Member Data Documentation
callbacks_
callbacks_t kcenon::network::core::messaging_udp_client::callbacks_ private
Callback manager.
Definition at line 307 of file messaging_udp_client.h.
Referenced by get_error_callback(), and get_receive_callback().
client_id_
std::string kcenon::network::core::messaging_udp_client::client_id_ private
Client identifier.
Definition at line 305 of file messaging_udp_client.h.
Referenced by client_id().
endpoint_mutex_
std::mutex kcenon::network::core::messaging_udp_client::endpoint_mutex_ private
Protects target_endpoint_.
Definition at line 315 of file messaging_udp_client.h.
io_context_
std::unique_ptr<asio::io_context> kcenon::network::core::messaging_udp_client::io_context_ private
ASIO I/O context.
Definition at line 309 of file messaging_udp_client.h.
io_context_future_
std::future<void> kcenon::network::core::messaging_udp_client::io_context_future_ private
Future for io_context run task.
Definition at line 313 of file messaging_udp_client.h.
lifecycle_
utils::lifecycle_manager kcenon::network::core::messaging_udp_client::lifecycle_ private
Lifecycle state manager.
Definition at line 306 of file messaging_udp_client.h.
Referenced by is_running(), and ~messaging_udp_client().
pimpl_
std::unique_ptr<impl> kcenon::network::core::messaging_udp_client::pimpl_ export private
Definition at line 184 of file udp.cppm.
socket_
std::shared_ptr<internal::udp_socket> kcenon::network::core::messaging_udp_client::socket_ private
UDP socket wrapper.
Definition at line 310 of file messaging_udp_client.h.
socket_mutex_
std::mutex kcenon::network::core::messaging_udp_client::socket_mutex_ mutable private
Protects socket access.
Definition at line 318 of file messaging_udp_client.h.
target_endpoint_
asio::ip::udp::endpoint kcenon::network::core::messaging_udp_client::target_endpoint_ private
Target endpoint for sends.
Definition at line 316 of file messaging_udp_client.h.
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::messaging_udp_client::thread_pool_ private
Thread pool for async operations.
Definition at line 312 of file messaging_udp_client.h.
The documentation for this class was generated from the following files:
src/internal/core/messaging_udp_client.h
src/modules/udp.cppm
src/core/messaging_udp_client.cpp