Network System: kcenon::network::connection_guard Class Reference
kcenon::network::connection_guard Class Reference
RAII guard for connection limiting.
#include <rate_limiter.h>
Public Member Functions
connection_guard (connection_limiter &limiter)
Construct guard and try to accept connection.
connection_guard (const connection_guard &)=delete
Non-copyable.
connection_guard & operator= (const connection_guard &)=delete
connection_guard (connection_guard &&other) noexcept
Movable.
connection_guard & operator= (connection_guard &&other) noexcept
~connection_guard ()
bool accepted () const noexcept
Check if connection was accepted.
operator bool () const noexcept
Explicit bool conversion.
void release () noexcept
Release the connection early.
Private Attributes
connection_limiter * limiter_
bool accepted_
Detailed Description
RAII guard for connection limiting.
Automatically registers/unregisters connection on construction/destruction.
Definition at line 411 of file rate_limiter.h.
Constructor & Destructor Documentation
connection_guard() [1/3]
kcenon::network::connection_guard::connection_guard (connection_limiter & limiter) inline explicit
Construct guard and try to accept connection.
Parameters
limiter Connection limiter
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 417 of file rate_limiter.h.
        : limiter_(&limiter)
        , accepted_(limiter.try_accept()) {}
connection_guard() [2/3]
kcenon::network::connection_guard::connection_guard (const connection_guard &) delete
Non-copyable.
connection_guard() [3/3]
kcenon::network::connection_guard::connection_guard (connection_guard && other) inline noexcept
Movable.
Definition at line 426 of file rate_limiter.h.
        : limiter_(other.limiter_)
        , accepted_(other.accepted_) {
        other.accepted_ = false;
    }
~connection_guard()
kcenon::network::connection_guard::~connection_guard () inline
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 442 of file rate_limiter.h.
{
        release();
    }
References release().
Member Function Documentation
accepted()
bool kcenon::network::connection_guard::accepted () const inline nodiscard noexcept
Check if connection was accepted.
Returns
true if connection was successfully accepted
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 450 of file rate_limiter.h.
{
        return accepted_;
    }
References accepted_.
operator bool()
kcenon::network::connection_guard::operator bool () const inline explicit noexcept
Explicit bool conversion.
Definition at line 457 of file rate_limiter.h.
{
        return accepted_;
    }
References accepted_.
operator=() [1/2]
connection_guard & kcenon::network::connection_guard::operator= (connection_guard && other) inline noexcept
Definition at line 432 of file rate_limiter.h.
{
        if (this != &other) {
            release();
            limiter_ = other.limiter_;
            accepted_ = other.accepted_;
            other.accepted_ = false;
        }
        return *this;
    }
References accepted_, limiter_, and release().
operator=() [2/2]
connection_guard & kcenon::network::connection_guard::operator= (const connection_guard &) delete
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
release()
void kcenon::network::connection_guard::release () inline noexcept
Release the connection early.
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 464 of file rate_limiter.h.
{
        if (accepted_ && limiter_) {
            limiter_->on_disconnect();
            accepted_ = false;
        }
    }
References accepted_, limiter_, and kcenon::network::connection_limiter::on_disconnect().
Referenced by operator=(), and ~connection_guard().
Member Data Documentation
accepted_
bool kcenon::network::connection_guard::accepted_ private
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 473 of file rate_limiter.h.
Referenced by accepted(), operator bool(), operator=(), and release().
limiter_
connection_limiter* kcenon::network::connection_guard::limiter_ private
Examples
/home/runner/work/network_system/network_system/src/internal/utils/rate_limiter.h.
Definition at line 472 of file rate_limiter.h.
Referenced by operator=(), and release().
The documentation for this class was generated from the following file:
src/internal/utils/rate_limiter.h