Network System: kcenon::network::internal::adapters::ws_server_adapter Class Reference
kcenon::network::internal::adapters::ws_server_adapter Class Reference
Adapter that wraps messaging_ws_server to implement i_protocol_server.
#include <ws_server_adapter.h>
Public Member Functions
ws_server_adapter (std::string_view server_id)
Constructs an adapter with a unique server ID.
~ws_server_adapter () override
Destructor ensures proper cleanup.
ws_server_adapter (const ws_server_adapter &)=delete
ws_server_adapter & operator= (const ws_server_adapter &)=delete
ws_server_adapter (ws_server_adapter &&)=delete
ws_server_adapter & operator= (ws_server_adapter &&)=delete
auto set_path (std::string_view path) -> void
Sets the WebSocket path for accepting connections.
auto is_running () const -> bool override
Checks if the component is currently running.
auto wait_for_stop () -> void override
Blocks until the component has stopped.
auto start (uint16_t port) -> VoidResult override
Starts the server and begins listening for connections.
auto stop () -> VoidResult override
Stops the server and closes all connections.
auto connection_count () const -> size_t override
Gets the number of active client connections.
auto set_connection_callback (connection_callback_t callback) -> void override
Sets the callback for new connections.
auto set_disconnection_callback (disconnection_callback_t callback) -> void override
Sets the callback for disconnections.
auto set_receive_callback (receive_callback_t callback) -> void override
Sets the callback for received data.
auto set_error_callback (error_callback_t callback) -> void override
Sets the callback for errors.
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Member Functions
auto setup_internal_callbacks () -> void
Sets up internal callbacks to bridge WebSocket callbacks to i_protocol_server callbacks.
auto get_or_create_session (std::shared_ptr< core::ws_connection > connection) -> std::shared_ptr< interfaces::i_session >
Gets or creates a session wrapper for the given connection.
Private Attributes
std::string server_id_
std::string path_ {"/"}
std::shared_ptr< core::messaging_ws_server > server_
std::mutex callbacks_mutex_
connection_callback_t connection_callback_
disconnection_callback_t disconnection_callback_
receive_callback_t receive_callback_
error_callback_t error_callback_
std::mutex sessions_mutex_
std::unordered_map< std::string, std::shared_ptr< ws_session_wrapper > > sessions_
Additional Inherited Members
Public Types inherited from kcenon::network::interfaces::i_protocol_server
using connection_callback_t = std::function< void(std::shared_ptr< i_session >)>
Callback type for new connections.
using disconnection_callback_t = std::function< void(std::string_view)>
Callback type for disconnections (session_id)
using receive_callback_t = std::function< void(std::string_view, const std::vector< uint8_t > &)>
Callback type for received data (session_id, data)
using error_callback_t = std::function< void(std::string_view, std::error_code)>
Callback type for errors (session_id, error)
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps messaging_ws_server to implement i_protocol_server.
This adapter bridges the WebSocket server implementation with the unified i_protocol_server interface. It allows websocket_facade to return i_protocol_server without modifying the existing messaging_ws_server class.
Design Rationale
The adapter pattern is used because:
WebSocket's i_websocket_server has different callback signatures
WebSocket has text/binary message distinction not present in i_protocol_server
WebSocket disconnection includes close code and reason
Path Handling
Since i_protocol_server::start() only takes port:
The path is configured via set_path() before calling start()
Default path is "/" if not configured
Session Management
Each ws_connection is wrapped in ws_session_wrapper
Sessions are tracked for the lifetime of the connection
connection_callback receives wrapped sessions
Thread Safety
Thread-safe. All methods can be called from any thread.
See also
i_protocol_server
messaging_ws_server
Definition at line 104 of file ws_server_adapter.h.
Constructor & Destructor Documentation
ws_server_adapter() [1/3]
kcenon::network::internal::adapters::ws_server_adapter::ws_server_adapter (std::string_view server_id) explicit
Constructs an adapter with a unique server ID.
Parameters
server_id Unique identifier for this server
Definition at line 90 of file ws_server_adapter.cpp.
    : server_id_(server_id)
    , server_(std::make_shared<core::messaging_ws_server>(std::string(server_id)))
{
    setup_internal_callbacks();
}
References setup_internal_callbacks().
~ws_server_adapter()
kcenon::network::internal::adapters::ws_server_adapter::~ws_server_adapter () override
Destructor ensures proper cleanup.
Definition at line 97 of file ws_server_adapter.cpp.
{
    if (server_ && server_->is_running())
    {
        (void)server_->stop();
    }
}
References server_.
ws_server_adapter() [2/3]
kcenon::network::internal::adapters::ws_server_adapter::ws_server_adapter (const ws_server_adapter &) delete
ws_server_adapter() [3/3]
kcenon::network::internal::adapters::ws_server_adapter::ws_server_adapter (ws_server_adapter &&) delete
Member Function Documentation
connection_count()
auto kcenon::network::internal::adapters::ws_server_adapter::connection_count () const -> size_t override virtual
Gets the number of active client connections.
Returns
The count of currently connected clients.
Definition of "Active"
A connection is considered active if:
Connection is established (handshake complete if applicable)
Session has not been closed
No fatal errors have occurred on the session
Protocol-Specific Notes
TCP/WebSocket/QUIC: Count of established connections
UDP: Count of unique peer endpoints seen recently
HTTP: Count of active persistent connections or requests
Thread Safety
Thread-safe. Uses atomic operations for accurate count.
Performance
O(1) operation. Does not iterate through connections.
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 172 of file ws_server_adapter.cpp.
{
    return server_ ? server_->connection_count() : 0;
}
References server_.
get_or_create_session()
auto kcenon::network::internal::adapters::ws_server_adapter::get_or_create_session (std::shared_ptr< core::ws_connection > connection) -> std::shared_ptr<interfaces::i_session> private
Gets or creates a session wrapper for the given connection.
Definition at line 292 of file ws_server_adapter.cpp.
{
    std::string session_id(connection->id());
    std::lock_guard<std::mutex> lock(sessions_mutex_);
    auto it = sessions_.find(session_id);
    if (it != sessions_.end())
    {
        return it->second;
    }
    // Create new session wrapper
    auto session = std::make_shared<ws_session_wrapper>(connection);
    sessions_[session_id] = session;
    return session;
}
is_running()
auto kcenon::network::internal::adapters::ws_server_adapter::is_running () const -> bool override virtual
Checks if the component is currently running.
Returns
true if the component is active, false otherwise.
This method must be thread-safe and use atomic operations for the running state.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 118 of file ws_server_adapter.cpp.
{
    return server_ && server_->is_running();
}
References server_.
operator=() [1/2]
ws_server_adapter & kcenon::network::internal::adapters::ws_server_adapter::operator= (const ws_server_adapter &) delete
operator=() [2/2]
ws_server_adapter & kcenon::network::internal::adapters::ws_server_adapter::operator= (ws_server_adapter &&) delete
set_connection_callback()
auto kcenon::network::internal::adapters::ws_server_adapter::set_connection_callback (connection_callback_t callback) -> void override virtual
Sets the callback for new connections.
Parameters
callback The callback function.
Callback Parameters
session: Shared pointer to the new session object
Callback Behavior
Called when:
TCP: After accept() and initial handshake complete
WebSocket: After HTTP upgrade handshake succeeds
UDP: After first datagram received from new peer
QUIC: After connection establishment handshake
HTTP: After request line and headers parsed (HTTP/1.1)
Session Object
The session object allows:
Sending data to the specific client
Retrieving session metadata (ID, remote endpoint)
Closing the session individually
Thread Safety
The callback may be invoked from I/O threads. If the callback accesses shared state, it must be thread-safe.
Example
server->set_connection_callback([](std::shared_ptr<i_session> session) {
    std::cout << "New client: " << session->id() << std::endl;
    // Send welcome message
    session->send({0x01, 0x02, 0x03});
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 177 of file ws_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    connection_callback_ = std::move(callback);
}
set_disconnection_callback()
auto kcenon::network::internal::adapters::ws_server_adapter::set_disconnection_callback (disconnection_callback_t callback) -> void override virtual
Sets the callback for disconnections.
Parameters
callback The callback function.
Callback Parameters
session_id: String identifier of the disconnected session
Callback Behavior
Called when:
Client closes connection gracefully
Connection lost due to network error
Server closes the session
Timeout or keepalive failure
Clean-up Responsibility
The callback is the appropriate place to:
Remove session from application state
Log disconnection events
Release session-specific resources
Thread Safety
The callback may be invoked from I/O threads. Session cleanup code must be thread-safe.
Example
server->set_disconnection_callback([](std::string_view session_id) {
    std::cout << "Client disconnected: " << session_id << std::endl;
    // Remove from session map
    sessions.erase(std::string(session_id));
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 183 of file ws_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    disconnection_callback_ = std::move(callback);
}
set_error_callback()
auto kcenon::network::internal::adapters::ws_server_adapter::set_error_callback (error_callback_t callback) -> void override virtual
Sets the callback for errors.
Parameters
callback The callback function.
Callback Parameters
session_id: String identifier of the affected session (may be empty for server-level errors)
error: std::error_code describing the error
Error Categories
Connection errors: Reset, timeout, refused
Protocol errors: Invalid handshake, malformed data
System errors: Out of memory, file descriptor limits
Application errors: Send queue full, rate limit exceeded
Error Handling Strategy
The callback should:
Log the error for diagnostics
Decide whether to close the session
Update error metrics/statistics
Notify monitoring systems if critical
Automatic Disconnection
Some errors trigger automatic session closure:
Connection reset (ECONNRESET)
Protocol violations
Fatal security errors
For these, disconnection_callback will also be invoked.
Thread Safety
The callback may be invoked from I/O threads. Error handling code must be thread-safe.
Example
server->set_error_callback([](std::string_view session_id,
                               std::error_code error) {
    std::cerr << "Error on session " << session_id << ": "
              << error.message() << std::endl;
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 195 of file ws_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    error_callback_ = std::move(callback);
}
set_path()
auto kcenon::network::internal::adapters::ws_server_adapter::set_path (std::string_view path) -> void
Sets the WebSocket path for accepting connections.
Parameters
path The WebSocket path (e.g., "/ws", "/chat")
Must be called before start() if a non-default path is needed. Default path is "/" if not set.
Definition at line 109 of file ws_server_adapter.cpp.
{
    path_ = std::string(path);
}
set_receive_callback()
auto kcenon::network::internal::adapters::ws_server_adapter::set_receive_callback (receive_callback_t callback) -> void override virtual
Sets the callback for received data.
Parameters
callback The callback function.
Callback Parameters
session_id: String identifier of the sending session
data: Vector of bytes received
Data Ownership
The data vector is passed by const reference. If the callback needs to retain the data, it must copy it. The data is valid only for the duration of the callback.
Protocol-Specific Notes
TCP: May deliver partial messages (stream-based)
UDP: Delivers complete datagrams (message boundaries preserved)
WebSocket: Delivers complete messages (frame assembled)
QUIC: Delivers complete messages (stream data)
Thread Safety
The callback may be invoked from I/O threads. Multiple callbacks may execute concurrently for different sessions.
Example
server->set_receive_callback([](std::string_view session_id,
                                 const std::vector<uint8_t>& data) {
    std::cout << "Received " << data.size() << " bytes from "
              << session_id << std::endl;
    // Process data...
});
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 189 of file ws_server_adapter.cpp.
{
    std::lock_guard<std::mutex> lock(callbacks_mutex_);
    receive_callback_ = std::move(callback);
}
setup_internal_callbacks()
auto kcenon::network::internal::adapters::ws_server_adapter::setup_internal_callbacks () -> void private
Sets up internal callbacks to bridge WebSocket callbacks to i_protocol_server callbacks.
Definition at line 205 of file ws_server_adapter.cpp.
{
    if (!server_)
    {
        return;
    }
    // Bridge WebSocket connection callback
    server_->set_connection_callback(
        [this](std::shared_ptr<interfaces::i_websocket_session> ws_session)
        {
            // Cast to ws_connection for our wrapper
            auto ws_conn = std::dynamic_pointer_cast<core::ws_connection>(ws_session);
            if (!ws_conn)
            {
                return;
            }
            auto session = get_or_create_session(ws_conn);
            connection_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = connection_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session);
            }
        });
    // Bridge WebSocket disconnection callback (ignore close code and reason)
    server_->set_disconnection_callback(
        [this](std::string_view session_id, uint16_t /* code */, std::string_view /* reason */)
        {
            // Remove from tracked sessions
            {
                std::lock_guard<std::mutex> lock(sessions_mutex_);
                sessions_.erase(std::string(session_id));
            }
            disconnection_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = disconnection_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session_id);
            }
        });
    // Bridge WebSocket binary message callback
    server_->set_binary_callback(
        [this](std::string_view session_id, const std::vector<uint8_t>& data)
        {
            receive_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = receive_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session_id, data);
            }
        });
    // Bridge WebSocket error callback
    server_->set_error_callback(
        [this](std::string_view session_id, std::error_code ec)
        {
            error_callback_t callback_copy;
            {
                std::lock_guard<std::mutex> lock(callbacks_mutex_);
                callback_copy = error_callback_;
            }
            if (callback_copy)
            {
                callback_copy(session_id, ec);
            }
        });
}
Referenced by ws_server_adapter().
start()
auto kcenon::network::internal::adapters::ws_server_adapter::start (uint16_t port) -> VoidResult override virtual
Starts the server and begins listening for connections.
Parameters
port The port number to listen on.
Returns
VoidResult indicating success or failure.
Behavior
Binds to the specified port on all interfaces (0.0.0.0/::)
Begins accepting incoming connections
Initializes protocol-specific resources
Invokes connection_callback for each new client
Error Conditions
Returns error if already running
Returns error if port is already in use (EADDRINUSE)
Returns error if port binding fails (permission, invalid port)
Returns error if underlying protocol initialization fails
Protocol-Specific Notes
TCP/WebSocket/QUIC: Creates listening socket
UDP: Creates datagram socket, begins receiving
HTTP: May create connection pool or thread pool
Port Range
Valid ports: 1-65535
Privileged ports (< 1024) may require elevated permissions
Port 0 requests OS to assign an available port
Thread Safety
Thread-safe. Only one start operation can succeed at a time. Subsequent calls while running will return an error.
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 135 of file ws_server_adapter.cpp.
{
    if (!server_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Server not initialized",
            "ws_server_adapter::start"
        );
    }
    // Use the stored path (set via set_path, or default "/")
    return server_->start_server(port, path_);
}
References kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::internal_error.
stop()
auto kcenon::network::internal::adapters::ws_server_adapter::stop () -> VoidResult override virtual
Stops the server and closes all connections.
Returns
VoidResult indicating success or failure.
Behavior
Stops accepting new connections
Closes all active client sessions gracefully
Invokes disconnection_callback for each session
Cancels all pending operations
Releases protocol-specific resources
Error Conditions
Returns error if not running
Graceful Shutdown
The stop operation attempts to:
Stop accepting new connections immediately
Close existing connections gracefully (protocol-dependent)
Wait for pending operations to complete (with timeout)
Force-close remaining connections if timeout expires
Protocol-Specific Notes
TCP: Sends FIN to all clients, waits for ACK
WebSocket: Sends close frame to all clients
UDP: Stops receiving, no client "close" needed
QUIC: Sends CONNECTION_CLOSE to all clients
Thread Safety
Thread-safe. Safe to call from any thread including callbacks. The method blocks until shutdown is complete.
Implements kcenon::network::interfaces::i_protocol_server.
Definition at line 150 of file ws_server_adapter.cpp.
{
    if (!server_)
    {
        return error_void(
            error_codes::common_errors::internal_error,
            "Server not initialized",
            "ws_server_adapter::stop"
        );
    }
    auto result = server_->stop();
    // Clear tracked sessions on stop
    {
        std::lock_guard<std::mutex> lock(sessions_mutex_);
        sessions_.clear();
    }
    return result;
}
References kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::internal_error.
wait_for_stop()
auto kcenon::network::internal::adapters::ws_server_adapter::wait_for_stop () -> void override virtual
Blocks until the component has stopped.
This method should be used to synchronize shutdown operations. It returns immediately if the component is not running.
Thread Safety
Safe to call from any thread. Uses internal synchronization.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 123 of file ws_server_adapter.cpp.
{
    if (server_)
    {
        server_->wait_for_stop();
    }
}
Member Data Documentation
callbacks_mutex_
std::mutex kcenon::network::internal::adapters::ws_server_adapter::callbacks_mutex_ mutable private
Definition at line 172 of file ws_server_adapter.h.
connection_callback_
connection_callback_t kcenon::network::internal::adapters::ws_server_adapter::connection_callback_ private
Definition at line 173 of file ws_server_adapter.h.
disconnection_callback_
disconnection_callback_t kcenon::network::internal::adapters::ws_server_adapter::disconnection_callback_ private
Definition at line 174 of file ws_server_adapter.h.
error_callback_
error_callback_t kcenon::network::internal::adapters::ws_server_adapter::error_callback_ private
Definition at line 176 of file ws_server_adapter.h.
path_
std::string kcenon::network::internal::adapters::ws_server_adapter::path_ {"/"} private
Definition at line 169 of file ws_server_adapter.h.
{"/"}; // Default WebSocket path
receive_callback_
receive_callback_t kcenon::network::internal::adapters::ws_server_adapter::receive_callback_ private
Definition at line 175 of file ws_server_adapter.h.
server_
std::shared_ptr<core::messaging_ws_server> kcenon::network::internal::adapters::ws_server_adapter::server_ private
Definition at line 170 of file ws_server_adapter.h.
Referenced by connection_count(), is_running(), and ~ws_server_adapter().
server_id_
std::string kcenon::network::internal::adapters::ws_server_adapter::server_id_ private
Definition at line 168 of file ws_server_adapter.h.
sessions_
std::unordered_map<std::string, std::shared_ptr<ws_session_wrapper> > kcenon::network::internal::adapters::ws_server_adapter::sessions_ private
Definition at line 179 of file ws_server_adapter.h.
sessions_mutex_
std::mutex kcenon::network::internal::adapters::ws_server_adapter::sessions_mutex_ mutable private
Definition at line 178 of file ws_server_adapter.h.
The documentation for this class was generated from the following files:
src/internal/adapters/ws_server_adapter.h
src/adapters/ws_server_adapter.cpp