Network System: kcenon::network::protocols::http2::frame Class Reference
kcenon::network::protocols::http2::frame Class Reference
Base class for HTTP/2 frames.
#include <frame.h>
Public Member Functions
frame ()=default
Default constructor.
frame (const frame_header &hdr, std::vector< uint8_t > payload)
Construct frame with header and payload.
auto serialize () const -> std::vector< uint8_t >
Serialize frame to bytes.
auto header () const -> const frame_header &
Get frame header.
auto payload () const -> std::span< const uint8_t >
Get frame payload.
virtual ~frame ()=default
Virtual destructor.
Static Public Member Functions
static auto parse (std::span< const uint8_t > data) -> Result< std::unique_ptr< frame > >
Parse frame from raw bytes.
Protected Attributes
frame_header header_
Frame header.
std::vector< uint8_t > payload_
Frame payload.
Detailed Description
Base class for HTTP/2 frames.
Represents a generic HTTP/2 frame with header and payload. Specific frame types inherit from this base class.
Definition at line 109 of file frame.h.
Constructor & Destructor Documentation
frame() [1/2]
kcenon::network::protocols::http2::frame::frame () default
Default constructor.
frame() [2/2]
kcenon::network::protocols::http2::frame::frame (const frame_header & hdr, std::vector< uint8_t > payload)
Construct frame with header and payload.
Parameters
hdr Frame header
payload Frame payload data
Definition at line 117 of file frame.cpp.
        : header_(hdr), payload_(std::move(payload))
    {
    }
~frame()
virtual kcenon::network::protocols::http2::frame::~frame () virtual default
Virtual destructor.
Member Function Documentation
header()
auto kcenon::network::protocols::http2::frame::header () const -> const frame_header&
Get frame header.
Returns
Const reference to frame header
Definition at line 208 of file frame.cpp.
    {
        return header_;
    }
References header_.
parse()
auto kcenon::network::protocols::http2::frame::parse (std::span< const uint8_t > data) -> Result<std::unique_ptr<frame>> static
Parse frame from raw bytes.
Parameters
data Raw byte data (header + payload)
Returns
Result containing parsed frame or error
Definition at line 122 of file frame.cpp.
    {
        auto header_result = frame_header::parse(data);
        if (header_result.is_err())
        {
            return header_result.error();
        }
        const auto& header = header_result.value();
        if (data.size() < frame_header_size + header.length)
        {
            return error_info(3, "Insufficient data for frame payload", "http2");
        }
        auto payload_span = data.subspan(frame_header_size, header.length);
        std::vector<uint8_t> payload(payload_span.begin(), payload_span.end());
        std::unique_ptr<frame> result_frame;
        switch (header.type)
        {
            case frame_type::data:
            {
                auto parsed = data_frame::parse(header, payload);
                if (parsed.is_err()) return parsed.error();
                result_frame = std::move(parsed.value());
                break;
            }
            case frame_type::headers:
            {
                auto parsed = headers_frame::parse(header, payload);
                if (parsed.is_err()) return parsed.error();
                result_frame = std::move(parsed.value());
                break;
            }
            case frame_type::settings:
            {
                auto parsed = settings_frame::parse(header, payload);
                if (parsed.is_err()) return parsed.error();
                result_frame = std::move(parsed.value());
                break;
            }
            case frame_type::rst_stream:
            {
                auto parsed = rst_stream_frame::parse(header, payload);
                if (parsed.is_err()) return parsed.error();
                result_frame = std::move(parsed.value());
                break;
            }
            case frame_type::ping:
            {
                auto parsed = ping_frame::parse(header, payload);
                if (parsed.is_err()) return parsed.error();
                result_frame = std::move(parsed.value());
                break;
            }
            case frame_type::goaway:
            {
                auto parsed = goaway_frame::parse(header, payload);
                if (parsed.is_err()) return parsed.error();
                result_frame = std::move(parsed.value());
                break;
            }
            case frame_type::window_update:
            {
                auto parsed = window_update_frame::parse(header, payload);
                if (parsed.is_err()) return parsed.error();
                result_frame = std::move(parsed.value());
                break;
            }
            default:
                result_frame = std::make_unique<frame>(header, std::move(payload));
                break;
        }
        return std::move(result_frame);
    }
References kcenon::network::protocols::http2::data, kcenon::network::protocols::http2::goaway, kcenon::network::protocols::http2::headers, kcenon::network::protocols::http2::data_frame::parse(), kcenon::network::protocols::http2::goaway_frame::parse(), kcenon::network::protocols::http2::headers_frame::parse(), kcenon::network::protocols::http2::ping_frame::parse(), kcenon::network::protocols::http2::rst_stream_frame::parse(), kcenon::network::protocols::http2::settings_frame::parse(), kcenon::network::protocols::http2::window_update_frame::parse(), kcenon::network::protocols::http2::frame_header::parse(), kcenon::network::protocols::http2::ping, kcenon::network::protocols::http2::rst_stream, kcenon::network::protocols::http2::settings, and kcenon::network::protocols::http2::window_update.
Referenced by kcenon::network::protocols::http2::http2_client::read_frame(), kcenon::network::protocols::http2::http2_server_connection::read_frame_header(), and kcenon::network::protocols::http2::http2_server_connection::read_frame_payload().
payload()
auto kcenon::network::protocols::http2::frame::payload () const -> std::span<const uint8_t>
Get frame payload.
Returns
Span of payload bytes
Definition at line 213 of file frame.cpp.
    {
        return payload_;
    }
References payload_.
serialize()
auto kcenon::network::protocols::http2::frame::serialize () const -> std::vector<uint8_t>
Serialize frame to bytes.
Returns
Byte vector containing serialized frame (header + payload)
Definition at line 201 of file frame.cpp.
    {
        auto result = header_.serialize();
        result.insert(result.end(), payload_.begin(), payload_.end());
        return result;
    }
References header_, payload_, and kcenon::network::protocols::http2::frame_header::serialize().
Member Data Documentation
header_
frame_header kcenon::network::protocols::http2::frame::header_ protected
Frame header.
Definition at line 155 of file frame.h.
Referenced by kcenon::network::protocols::http2::data_frame::data_frame(), kcenon::network::protocols::http2::goaway_frame::goaway_frame(), header(), kcenon::network::protocols::http2::headers_frame::headers_frame(), kcenon::network::protocols::http2::settings_frame::is_ack(), kcenon::network::protocols::http2::ping_frame::is_ack(), kcenon::network::protocols::http2::headers_frame::is_end_headers(), kcenon::network::protocols::http2::data_frame::is_end_stream(), kcenon::network::protocols::http2::headers_frame::is_end_stream(), kcenon::network::protocols::http2::data_frame::is_padded(), kcenon::network::protocols::http2::ping_frame::ping_frame(), kcenon::network::protocols::http2::rst_stream_frame::rst_stream_frame(), serialize(), kcenon::network::protocols::http2::settings_frame::settings_frame(), and kcenon::network::protocols::http2::window_update_frame::window_update_frame().
payload_
std::vector<uint8_t> kcenon::network::protocols::http2::frame::payload_ protected
Frame payload.
Definition at line 156 of file frame.h.
Referenced by kcenon::network::protocols::http2::data_frame::data_frame(), kcenon::network::protocols::http2::goaway_frame::goaway_frame(), kcenon::network::protocols::http2::headers_frame::headers_frame(), payload(), kcenon::network::protocols::http2::ping_frame::ping_frame(), kcenon::network::protocols::http2::rst_stream_frame::rst_stream_frame(), serialize(), kcenon::network::protocols::http2::settings_frame::settings_frame(), and kcenon::network::protocols::http2::window_update_frame::window_update_frame().
The documentation for this class was generated from the following files:
src/internal/protocols/http2/frame.h
src/protocols/http2/frame.cpp