Network System: kcenon::network::core::messaging_ws_server Class Reference
kcenon::network::core::messaging_ws_server Class Reference
High-level WebSocket server with connection management.
#include <websocket_server.h>
Public Types
using connection_callback_t = std::function<void(std::shared_ptr<ws_connection>)>
Callback type for new connections.
using disconnection_callback_t = std::function<void(const std::string&, internal::ws_close_code, const std::string&)>
Callback type for disconnections.
using message_callback_t = std::function<void(std::shared_ptr<ws_connection>, const internal::ws_message&)>
Callback type for WebSocket messages.
using text_message_callback_t = std::function<void(std::shared_ptr<ws_connection>, const std::string&)>
Callback type for text messages.
using binary_message_callback_t = std::function<void(std::shared_ptr<ws_connection>, const std::vector<uint8_t>&)>
Callback type for binary messages.
using error_callback_t = std::function<void(const std::string&, std::error_code)>
Callback type for errors.
Public Types inherited from kcenon::network::interfaces::i_websocket_server
using connection_callback_t = std::function<void(std::shared_ptr<i_websocket_session>)>
Callback type for new connections.
using disconnection_callback_t
Callback type for disconnections (with close code and reason)
using text_callback_t = std::function<void(std::string_view, const std::string&)>
Callback type for text messages (session_id, message)
using binary_callback_t = std::function<void(std::string_view, const std::vector<uint8_t>&)>
Callback type for binary messages (session_id, data)
using error_callback_t = std::function<void(std::string_view, std::error_code)>
Callback type for errors (session_id, error)
Public Member Functions
messaging_ws_server (std::string_view server_id)
Constructs a WebSocket server.
~messaging_ws_server () noexcept override
Destructor. Automatically stops the server if still running.
messaging_ws_server (const messaging_ws_server &)=delete
messaging_ws_server & operator= (const messaging_ws_server &)=delete
messaging_ws_server (messaging_ws_server &&)=delete
messaging_ws_server & operator= (messaging_ws_server &&)=delete
auto start_server (const ws_server_config &config) -> VoidResult
Starts the server with full configuration.
auto start_server (uint16_t port, std::string_view path="/") -> VoidResult
Starts the server on the specified port.
auto stop_server () -> VoidResult
Stops the server and releases all resources.
auto server_id () const -> const std::string &
Returns the server identifier.
auto broadcast_text (const std::string &message) -> void
Broadcasts a text message to all connected clients.
auto broadcast_binary (const std::vector< uint8_t > &data) -> void
Broadcasts a binary message to all connected clients.
auto get_connection (const std::string &connection_id) -> std::shared_ptr< ws_connection >
Gets a connection by ID.
auto get_all_connections () -> std::vector< std::string >
Gets all connection IDs.
auto is_running () const -> bool override
Checks if the server is currently running.
auto wait_for_stop () -> void override
Blocks until stop() is called.
auto start (uint16_t port) -> VoidResult override
Starts the WebSocket server on the specified port.
auto stop () -> VoidResult override
Stops the WebSocket server.
auto connection_count () const -> size_t override
Gets the number of active WebSocket connections.
auto set_connection_callback (interfaces::i_websocket_server::connection_callback_t callback) -> void override
Sets the callback for new connections (interface version).
auto set_disconnection_callback (interfaces::i_websocket_server::disconnection_callback_t callback) -> void override
Sets the callback for disconnections (interface version).
auto set_text_callback (interfaces::i_websocket_server::text_callback_t callback) -> void override
Sets the callback for text messages (interface version).
auto set_binary_callback (interfaces::i_websocket_server::binary_callback_t callback) -> void override
Sets the callback for binary messages (interface version).
auto set_error_callback (interfaces::i_websocket_server::error_callback_t callback) -> void override
Sets the callback for errors (interface version).
Public Member Functions inherited from kcenon::network::interfaces::i_websocket_server
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Types
using callback_index = ws_server_callback
Callback index type alias for clarity.
using callbacks_t
Callback manager type for this server.
Private Member Functions
auto do_start_impl (uint16_t port, std::string_view path) -> VoidResult
WebSocket-specific implementation of server start.
auto do_stop_impl () -> VoidResult
WebSocket-specific implementation of server stop.
auto do_accept () -> void
Starts accepting new connections.
auto handle_new_connection (std::shared_ptr< asio::ip::tcp::socket > socket) -> void
Handles a new connection.
auto on_message (std::shared_ptr< ws_connection > conn, const internal::ws_message &msg) -> void
Handles received WebSocket messages.
auto on_close (const std::string &conn_id, internal::ws_close_code code, const std::string &reason) -> void
Handles connection close.
auto on_error (const std::string &conn_id, std::error_code ec) -> void
Handles errors.
auto invoke_connection_callback (std::shared_ptr< ws_connection > conn) -> void
Invokes the connection callback.
auto invoke_disconnection_callback (const std::string &conn_id, internal::ws_close_code code, const std::string &reason) -> void
Invokes the disconnection callback.
auto invoke_message_callback (std::shared_ptr< ws_connection > conn, const internal::ws_message &msg) -> void
Invokes the message callback.
auto invoke_error_callback (const std::string &conn_id, std::error_code ec) -> void
Invokes the error callback.
Private Attributes
std::string server_id_
utils::lifecycle_manager lifecycle_
callbacks_t callbacks_
ws_server_config config_
std::unique_ptr< asio::io_context > io_context_
std::unique_ptr< asio::executor_work_guard< asio::io_context::executor_type > > work_guard_
std::unique_ptr< asio::ip::tcp::acceptor > acceptor_
std::mutex acceptor_mutex_
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::future< void > io_context_future_
std::shared_ptr< ws_session_manager > session_mgr_
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
High-level WebSocket server with connection management.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling. It also implements the i_websocket_server interface for composition-based usage.
It handles:
Accepting incoming connections
Connection management (tracking, limits)
Message broadcasting
Per-connection message handling
Graceful shutdown
Event-driven callbacks
Thread Safety:
All public methods are thread-safe
Callbacks are invoked from the internal I/O thread
Broadcast operations are thread-safe
Interface Compliance
This class implements interfaces::i_websocket_server for composition-based usage.
Usage Example:
auto server = std::make_shared<messaging_ws_server>("my_server");
server->set_connection_callback([](auto conn) {
    std::cout << "Client connected: " << conn->connection_id() << std::endl;
});
server->set_text_message_callback([](auto conn, const std::string& msg) {
    std::cout << "Received: " << msg << std::endl;
    conn->send_text("Echo: " + msg);
});
server->start_server(8080, "/ws");
Definition at line 208 of file websocket_server.h.
Member Typedef Documentation
binary_message_callback_t
using kcenon::network::core::messaging_ws_server::binary_message_callback_t = std::function<void(std::shared_ptr<ws_connection>, const std::vector<uint8_t>&)>
Callback type for binary messages.
Definition at line 222 of file websocket_server.h.
callback_index
using kcenon::network::core::messaging_ws_server::callback_index = ws_server_callback private
Callback index type alias for clarity.
Definition at line 468 of file websocket_server.h.
callbacks_t
using kcenon::network::core::messaging_ws_server::callbacks_t private
Initial value:
 utils::callback_manager<
            connection_callback_t,
            disconnection_callback_t,
            message_callback_t,
            text_message_callback_t,
            binary_message_callback_t,
            error_callback_t
        >
Callback manager type for this server.
Definition at line 471 of file websocket_server.h.
connection_callback_t
using kcenon::network::core::messaging_ws_server::connection_callback_t = std::function<void(std::shared_ptr<ws_connection>)>
Callback type for new connections.
Definition at line 214 of file websocket_server.h.
disconnection_callback_t
using kcenon::network::core::messaging_ws_server::disconnection_callback_t = std::function<void(const std::string&, internal::ws_close_code, const std::string&)>
Callback type for disconnections.
Definition at line 216 of file websocket_server.h.
error_callback_t
using kcenon::network::core::messaging_ws_server::error_callback_t = std::function<void(const std::string&, std::error_code)>
Callback type for errors.
Definition at line 224 of file websocket_server.h.
message_callback_t
using kcenon::network::core::messaging_ws_server::message_callback_t = std::function<void(std::shared_ptr<ws_connection>, const internal::ws_message&)>
Callback type for WebSocket messages.
Definition at line 218 of file websocket_server.h.
text_message_callback_t
using kcenon::network::core::messaging_ws_server::text_message_callback_t = std::function<void(std::shared_ptr<ws_connection>, const std::string&)>
Callback type for text messages.
Definition at line 220 of file websocket_server.h.
Constructor & Destructor Documentation
messaging_ws_server() [1/3]
kcenon::network::core::messaging_ws_server::messaging_ws_server (std::string_view server_id) explicit
Constructs a WebSocket server.
Parameters
server_id A unique identifier for this server instance.
Definition at line 166 of file websocket_server.cpp.
        : server_id_(server_id)
    {
    }
~messaging_ws_server()
kcenon::network::core::messaging_ws_server::~messaging_ws_server () override noexcept
Destructor. Automatically stops the server if still running.
Definition at line 171 of file websocket_server.cpp.
    {
        if (lifecycle_.is_running())
        {
            (void)stop_server();
        }
    }
References kcenon::network::utils::lifecycle_manager::is_running(), lifecycle_, and stop_server().
messaging_ws_server() [2/3]
kcenon::network::core::messaging_ws_server::messaging_ws_server (const messaging_ws_server &) delete
messaging_ws_server() [3/3]
kcenon::network::core::messaging_ws_server::messaging_ws_server (messaging_ws_server &&) delete
Member Function Documentation
broadcast_binary()
auto kcenon::network::core::messaging_ws_server::broadcast_binary (const std::vector< uint8_t > & data) -> void
Broadcasts a binary message to all connected clients.
Parameters
data The binary data to broadcast.
Definition at line 480 of file websocket_server.cpp.
    {
        if (!session_mgr_)
        {
            return;
        }
        auto conns = session_mgr_->get_all_connections();
        for (auto& conn : conns)
        {
            (void)conn->send_binary(std::vector<uint8_t>(data));
        }
    }
broadcast_text()
auto kcenon::network::core::messaging_ws_server::broadcast_text (const std::string & message) -> void
Broadcasts a text message to all connected clients.
Parameters
message The text message to broadcast.
Definition at line 466 of file websocket_server.cpp.
    {
        if (!session_mgr_)
        {
            return;
        }
        auto conns = session_mgr_->get_all_connections();
        for (auto& conn : conns)
        {
            (void)conn->send_text(std::string(message));
        }
    }
References kcenon::network::message.
connection_count()
auto kcenon::network::core::messaging_ws_server::connection_count () const -> size_t nodiscard override virtual
Gets the number of active WebSocket connections.
Returns
The count of currently connected clients.
Implements i_websocket_server::connection_count().
Implements kcenon::network::interfaces::i_websocket_server.
Definition at line 257 of file websocket_server.cpp.
    {
        if (!session_mgr_)
        {
            return 0;
        }
        return session_mgr_->get_connection_count();
    }
References session_mgr_.
do_accept()
auto kcenon::network::core::messaging_ws_server::do_accept () -> void private
Starts accepting new connections.
Definition at line 513 of file websocket_server.cpp.
    {
        // Lock to prevent race with do_stop_impl() closing the acceptor
        std::lock_guard<std::mutex> lock(acceptor_mutex_);
        // Early return if server is stopping or acceptor is invalid
        if (!lifecycle_.is_running() || !acceptor_ || !acceptor_->is_open())
        {
            return;
        }
        auto socket = std::make_shared<tcp::socket>(*io_context_);
        acceptor_->async_accept(*socket,
                                [this, socket](std::error_code ec)
{
                                    if (!ec)
{
                                        handle_new_connection(socket);
                                    }
                                    else
{
                                        NETWORK_LOG_ERROR(
                                            "[messaging_ws_server] Accept error: " +
                                            ec.message());
                                    }
                                    // Continue accepting
                                    if (lifecycle_.is_running())
{
                                        do_accept();
                                    }
                                });
    }
References NETWORK_LOG_ERROR.
do_start_impl()
auto kcenon::network::core::messaging_ws_server::do_start_impl (uint16_t port, std::string_view path) -> VoidResult private
WebSocket-specific implementation of server start.
Parameters
port The port number to listen on.
path The WebSocket path.
Returns
Result<void> - Success if server started, or error with code.
Definition at line 349 of file websocket_server.cpp.
    {
        try
        {
            // Store config if not already set
            if (config_.port == 0 || config_.port != port)
            {
                config_.port = port;
                config_.path = std::string(path);
            }
            // Create session manager
            session_config sess_config;
            sess_config.max_sessions = config_.max_connections;
            session_mgr_ = std::make_shared<ws_session_manager>(sess_config);
            // Create io_context and work guard
            io_context_ = std::make_unique<asio::io_context>();
            work_guard_ = std::make_unique<
                asio::executor_work_guard<asio::io_context::executor_type>>(
                asio::make_work_guard(*io_context_));
            // Create acceptor
            acceptor_ = std::make_unique<tcp::acceptor>(
                *io_context_, tcp::endpoint(tcp::v4(), config_.port));
            // Get thread pool from network context
            thread_pool_ = network_context::instance().get_thread_pool();
            if (!thread_pool_) {
                // Fallback: create a temporary thread pool if network_context is not initialized
                NETWORK_LOG_WARN("[messaging_ws_server] network_context not initialized, creating temporary thread pool");
                thread_pool_ = std::make_shared<integration::basic_thread_pool>(std::thread::hardware_concurrency());
            }
            // Start io_context on thread pool
            io_context_future_ = thread_pool_->submit([this]() {
                try {
                    NETWORK_LOG_DEBUG("[messaging_ws_server] io_context started");
                    io_context_->run();
                    NETWORK_LOG_DEBUG("[messaging_ws_server] io_context stopped");
                } catch (const std::exception& e) {
                    NETWORK_LOG_ERROR("[messaging_ws_server] Exception in io_context: " +
                                      std::string(e.what()));
                }
            });
            // Start accepting connections
            do_accept();
            NETWORK_LOG_INFO("[messaging_ws_server] Server started on port " +
                             std::to_string(config_.port) + " (ID: " +
                             server_id_ + ")");
            return ok();
        }
        catch (const std::exception& e)
        {
            return error_void(error_codes::network_system::bind_failed,
                              std::string("Failed to start server: ") + e.what());
        }
    }
References kcenon::network::error_codes::network_system::bind_failed, kcenon::network::error_void(), kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), kcenon::network::core::session_config::max_sessions, NETWORK_LOG_DEBUG, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, NETWORK_LOG_WARN, kcenon::network::ok(), and kcenon::network::integration::thread_pool_interface::submit().
do_stop_impl()
auto kcenon::network::core::messaging_ws_server::do_stop_impl () -> VoidResult private
WebSocket-specific implementation of server stop.
Returns
Result<void> - Success if server stopped, or error with code.
Definition at line 411 of file websocket_server.cpp.
    {
        try
        {
            // Close all connections
            if (session_mgr_)
            {
                auto conns = session_mgr_->get_all_connections();
                for (auto& conn : conns)
                {
                    conn->close();
                }
                session_mgr_->clear_all_connections();
            }
            // Stop acceptor
            // Lock to prevent race with do_accept() accessing the acceptor
            {
                std::lock_guard<std::mutex> lock(acceptor_mutex_);
                if (acceptor_)
                {
                    acceptor_->close();
                }
            }
            // Stop io_context
            work_guard_.reset();
            if (io_context_)
            {
                io_context_->stop();
            }
            // Wait for io_context task to complete
            if (io_context_future_.valid())
            {
                try {
                    io_context_future_.wait();
                } catch (const std::exception& e) {
                    NETWORK_LOG_ERROR("[messaging_ws_server] Exception while waiting for io_context: " +
                                      std::string(e.what()));
                }
            }
            NETWORK_LOG_INFO("[messaging_ws_server] Server stopped (ID: " +
                             server_id_ + ")");
            return ok();
        }
        catch (const std::exception& e)
        {
            return error_void(error_codes::common_errors::internal_error,
                              std::string("Failed to stop server: ") + e.what());
        }
    }
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, and kcenon::network::ok().
get_all_connections()
auto kcenon::network::core::messaging_ws_server::get_all_connections () -> std::vector<std::string>
Gets all connection IDs.
Returns
Vector of connection identifiers.
Definition at line 504 of file websocket_server.cpp.
    {
        if (!session_mgr_)
        {
            return {};
        }
        return session_mgr_->get_all_connection_ids();
    }
get_connection()
auto kcenon::network::core::messaging_ws_server::get_connection (const std::string & connection_id) -> std::shared_ptr<ws_connection>
Gets a connection by ID.
Parameters
connection_id The connection identifier.
Returns
Shared pointer to connection, or nullptr if not found.
Definition at line 494 of file websocket_server.cpp.
    {
        if (!session_mgr_)
        {
            return nullptr;
        }
        return session_mgr_->get_connection(connection_id);
    }
handle_new_connection()
auto kcenon::network::core::messaging_ws_server::handle_new_connection (std::shared_ptr< asio::ip::tcp::socket > socket) -> void private
Handles a new connection.
Definition at line 548 of file websocket_server.cpp.
    {
        // Check connection limit using session manager
        if (!session_mgr_ || !session_mgr_->can_accept_connection())
        {
            NETWORK_LOG_WARN("[messaging_ws_server] Connection limit reached");
            return;
        }
        // Generate connection ID
        auto remote_ep = socket->remote_endpoint();
        std::string conn_id = remote_ep.address().to_string() + ":" +
                              std::to_string(remote_ep.port());
        std::string remote_addr = conn_id;
        // Wrap in tcp_socket
        auto tcp_sock = std::make_shared<internal::tcp_socket>(std::move(*socket));
        // Wrap in websocket_socket
        auto ws_socket =
            std::make_shared<internal::websocket_socket>(tcp_sock, false);
        // Create connection wrapper
        auto conn_impl = std::make_shared<ws_connection_impl>(conn_id, ws_socket, remote_addr, config_.path);
        auto conn = std::make_shared<ws_connection>(conn_impl);
        // Set WebSocket callbacks
        ws_socket->set_message_callback(
            [this, conn](const internal::ws_message& msg)
            { on_message(conn, msg); });
        ws_socket->set_ping_callback(
            [this, ws_socket](const std::vector<uint8_t>& payload)
            {
                if (config_.auto_pong)
                {
                    ws_socket->async_send_ping(std::vector<uint8_t>(payload),
                                               [](std::error_code) {});
                }
            });
        ws_socket->set_close_callback(
            [this, conn_id](internal::ws_close_code code,
                            const std::string& reason)
            { on_close(conn_id, code, reason); });
        ws_socket->set_error_callback(
            [this, conn_id](std::error_code ec) { on_error(conn_id, ec); });
        // Accept WebSocket handshake
        ws_socket->async_accept(
            [this, conn_id, conn](std::error_code ec)
            {
                if (ec)
                {
                    NETWORK_LOG_ERROR("[messaging_ws_server] Handshake failed: " +
                                      ec.message());
                    return;
                }
                // Add to session manager
                auto added_id = session_mgr_->add_connection(conn, conn_id);
                if (added_id.empty())
                {
                    NETWORK_LOG_WARN(
                        "[messaging_ws_server] Failed to add connection");
                    return;
                }
                NETWORK_LOG_INFO("[messaging_ws_server] Client connected: " +
                                 conn_id);
                // Start reading frames
                auto ws_sock = conn->get_impl()->get_socket();
                if (ws_sock)
                {
                    ws_sock->start_read();
                }
                // Invoke connection callback
                invoke_connection_callback(conn);
            });
    }
References NETWORK_LOG_ERROR, NETWORK_LOG_INFO, and NETWORK_LOG_WARN.
invoke_connection_callback()
auto kcenon::network::core::messaging_ws_server::invoke_connection_callback (std::shared_ptr< ws_connection > conn) -> void private
Invokes the connection callback.
Parameters
conn The new connection.
Definition at line 670 of file websocket_server.cpp.
    {
        callbacks_.invoke<to_index(callback_index::connection)>(conn);
    }
References kcenon::network::to_index().
invoke_disconnection_callback()
auto kcenon::network::core::messaging_ws_server::invoke_disconnection_callback (const std::string & conn_id, internal::ws_close_code code, const std::string & reason) -> void private
Invokes the disconnection callback.
Parameters
conn_id The connection ID.
code The close code.
reason The close reason.
Definition at line 675 of file websocket_server.cpp.
    {
        callbacks_.invoke<to_index(callback_index::disconnection)>(conn_id, code, reason);
    }
References kcenon::network::to_index().
invoke_error_callback()
auto kcenon::network::core::messaging_ws_server::invoke_error_callback (const std::string & conn_id, std::error_code ec) -> void private
Invokes the error callback.
Parameters
conn_id The connection ID.
ec The error code.
Definition at line 697 of file websocket_server.cpp.
    {
        callbacks_.invoke<to_index(callback_index::error)>(conn_id, ec);
    }
References kcenon::network::to_index().
invoke_message_callback()
auto kcenon::network::core::messaging_ws_server::invoke_message_callback (std::shared_ptr< ws_connection > conn, const internal::ws_message & msg) -> void private
Invokes the message callback.
Parameters
conn The connection that received the message.
msg The received message.
Definition at line 682 of file websocket_server.cpp.
    {
        callbacks_.invoke<to_index(callback_index::message)>(conn, msg);
        if (msg.type == internal::ws_message_type::text)
        {
            callbacks_.invoke<to_index(callback_index::text_message)>(conn, msg.as_text());
        }
        else if (msg.type == internal::ws_message_type::binary)
        {
            callbacks_.invoke<to_index(callback_index::binary_message)>(conn, msg.as_binary());
        }
    }
References kcenon::network::internal::binary, kcenon::network::internal::text, and kcenon::network::to_index().
is_running()
auto kcenon::network::core::messaging_ws_server::is_running () const -> bool nodiscard override virtual
Checks if the server is currently running.
Returns
true if running, false otherwise.
Implements i_network_component::is_running().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 233 of file websocket_server.cpp.
    {
        return lifecycle_.is_running();
    }
References kcenon::network::utils::lifecycle_manager::is_running(), and lifecycle_.
on_close()
auto kcenon::network::core::messaging_ws_server::on_close (const std::string & conn_id, internal::ws_close_code code, const std::string & reason) -> void private
Handles connection close.
Definition at line 638 of file websocket_server.cpp.
    {
        // Remove from session manager
        if (session_mgr_)
        {
            auto conn = session_mgr_->get_connection(conn_id);
            if (conn)
            {
                conn->get_impl()->invalidate();
            }
            session_mgr_->remove_connection(conn_id);
        }
        NETWORK_LOG_INFO("[messaging_ws_server] Client disconnected: " + conn_id);
        invoke_disconnection_callback(conn_id, code, reason);
    }
References NETWORK_LOG_INFO.
on_error()
auto kcenon::network::core::messaging_ws_server::on_error (const std::string & conn_id, std::error_code ec) -> void private
Handles errors.
Definition at line 658 of file websocket_server.cpp.
    {
        NETWORK_LOG_ERROR("[messaging_ws_server] Connection error (" + conn_id +
                          "): " + ec.message());
        invoke_error_callback(conn_id, ec);
    }
References NETWORK_LOG_ERROR.
on_message()
auto kcenon::network::core::messaging_ws_server::on_message (std::shared_ptr< ws_connection > conn, const internal::ws_message & msg) -> void private
Handles received WebSocket messages.
Definition at line 632 of file websocket_server.cpp.
    {
        invoke_message_callback(conn, msg);
    }
operator=() [1/2]
messaging_ws_server & kcenon::network::core::messaging_ws_server::operator= (const messaging_ws_server &) delete
operator=() [2/2]
messaging_ws_server & kcenon::network::core::messaging_ws_server::operator= (messaging_ws_server &&) delete
server_id()
auto kcenon::network::core::messaging_ws_server::server_id () const -> const std::string& nodiscard
Returns the server identifier.
Returns
The server_id string.
Definition at line 224 of file websocket_server.cpp.
    {
        return server_id_;
    }
References server_id_.
set_binary_callback()
auto kcenon::network::core::messaging_ws_server::set_binary_callback (interfaces::i_websocket_server::binary_callback_t callback) -> void override virtual
Sets the callback for binary messages (interface version).
Parameters
callback The callback function.
Implements i_websocket_server::set_binary_callback().
Implements kcenon::network::interfaces::i_websocket_server.
Definition at line 316 of file websocket_server.cpp.
    {
        // Adapt interface callback to internal callback type
        if (callback) {
            callbacks_.set<to_index(callback_index::binary_message)>(
                [callback = std::move(callback)](std::shared_ptr<ws_connection> conn,
                                                 const std::vector<uint8_t>& data) {
                    callback(conn->id(), data);
                });
        } else {
            callbacks_.set<to_index(callback_index::binary_message)>(binary_message_callback_t{});
        }
    }
References kcenon::network::to_index().
set_connection_callback()
auto kcenon::network::core::messaging_ws_server::set_connection_callback (interfaces::i_websocket_server::connection_callback_t callback) -> void override virtual
Sets the callback for new connections (interface version).
Parameters
callback The callback function.
Implements i_websocket_server::set_connection_callback().
Implements kcenon::network::interfaces::i_websocket_server.
Definition at line 270 of file websocket_server.cpp.
    {
        // Adapt interface callback to internal callback type
        if (callback) {
            callbacks_.set<to_index(callback_index::connection)>(
                [callback = std::move(callback)](std::shared_ptr<ws_connection> conn) {
                    // ws_connection already implements i_websocket_session
                    callback(conn);
                });
        } else {
            callbacks_.set<to_index(callback_index::connection)>(connection_callback_t{});
        }
    }
References kcenon::network::to_index().
set_disconnection_callback()
auto kcenon::network::core::messaging_ws_server::set_disconnection_callback (interfaces::i_websocket_server::disconnection_callback_t callback) -> void override virtual
Sets the callback for disconnections (interface version).
Parameters
callback The callback function.
Implements i_websocket_server::set_disconnection_callback().
Implements kcenon::network::interfaces::i_websocket_server.
Definition at line 285 of file websocket_server.cpp.
    {
        // Adapt interface callback to internal callback type
        if (callback) {
            callbacks_.set<to_index(callback_index::disconnection)>(
                [callback = std::move(callback)](const std::string& session_id,
                                                 internal::ws_close_code code,
                                                 const std::string& reason) {
                    callback(session_id, static_cast<uint16_t>(code), reason);
                });
        } else {
            callbacks_.set<to_index(callback_index::disconnection)>(disconnection_callback_t{});
        }
    }
References kcenon::network::to_index().
set_error_callback()
auto kcenon::network::core::messaging_ws_server::set_error_callback (interfaces::i_websocket_server::error_callback_t callback) -> void override virtual
Sets the callback for errors (interface version).
Parameters
callback The callback function.
Implements i_websocket_server::set_error_callback().
Implements kcenon::network::interfaces::i_websocket_server.
Definition at line 331 of file websocket_server.cpp.
    {
        // Interface and legacy types are compatible
        if (callback) {
            callbacks_.set<to_index(callback_index::error)>(
                [callback = std::move(callback)](const std::string& session_id, std::error_code ec) {
                    callback(session_id, ec);
                });
        } else {
            callbacks_.set<to_index(callback_index::error)>(error_callback_t{});
        }
    }
References kcenon::network::to_index().
set_text_callback()
auto kcenon::network::core::messaging_ws_server::set_text_callback (interfaces::i_websocket_server::text_callback_t callback) -> void override virtual
Sets the callback for text messages (interface version).
Parameters
callback The callback function.
Implements i_websocket_server::set_text_callback().
Implements kcenon::network::interfaces::i_websocket_server.
Definition at line 301 of file websocket_server.cpp.
    {
        // Adapt interface callback to internal callback type
        if (callback) {
            callbacks_.set<to_index(callback_index::text_message)>(
                [callback = std::move(callback)](std::shared_ptr<ws_connection> conn,
                                                 const std::string& message) {
                    callback(conn->id(), message);
                });
        } else {
            callbacks_.set<to_index(callback_index::text_message)>(text_message_callback_t{});
        }
    }
References kcenon::network::message, and kcenon::network::to_index().
start()
auto kcenon::network::core::messaging_ws_server::start (uint16_t port) -> VoidResult nodiscard override virtual
Starts the WebSocket server on the specified port.
Parameters
port The port number to listen on.
Returns
VoidResult indicating success or failure.
Implements i_websocket_server::start(). Delegates to start_server().
Implements kcenon::network::interfaces::i_websocket_server.
Definition at line 247 of file websocket_server.cpp.
    {
        return start_server(port);
    }
start_server() [1/2]
auto kcenon::network::core::messaging_ws_server::start_server (const ws_server_config & config) -> VoidResult nodiscard
Starts the server with full configuration.
Parameters
config The server configuration.
Returns
VoidResult indicating success or error.
Definition at line 183 of file websocket_server.cpp.
    {
        config_ = config;
        return start_server(config.port, config.path);
    }
References config.
start_server() [2/2]
auto kcenon::network::core::messaging_ws_server::start_server (uint16_t port, std::string_view path = "/") -> VoidResult nodiscard
Starts the server on the specified port.
Parameters
port The port number to listen on.
path The WebSocket path (default: "/").
Returns
Result<void> - Success if server started, or error with code.
Definition at line 189 of file websocket_server.cpp.
    {
        if (lifecycle_.is_running())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "WebSocket server is already running",
                "messaging_ws_server");
        }
        lifecycle_.set_running();
        auto result = do_start_impl(port, path);
        if (result.is_err())
        {
            lifecycle_.mark_stopped();
        }
        return result;
    }
References kcenon::network::error_codes::common_errors::already_exists, and kcenon::network::error_void().
stop()
auto kcenon::network::core::messaging_ws_server::stop () -> VoidResult nodiscard override virtual
Stops the WebSocket server.
Returns
VoidResult indicating success or failure.
Implements i_websocket_server::stop(). Delegates to stop_server().
Implements kcenon::network::interfaces::i_websocket_server.
Definition at line 252 of file websocket_server.cpp.
    {
        return stop_server();
    }
stop_server()
auto kcenon::network::core::messaging_ws_server::stop_server () -> VoidResult nodiscard
Stops the server and releases all resources.
Returns
Result<void> - Success if server stopped, or error with code.
Definition at line 210 of file websocket_server.cpp.
    {
        if (!lifecycle_.prepare_stop())
        {
            return ok();
        }
        auto result = do_stop_impl();
        lifecycle_.mark_stopped();
        return result;
    }
References kcenon::network::ok().
Referenced by ~messaging_ws_server().
wait_for_stop()
auto kcenon::network::core::messaging_ws_server::wait_for_stop () -> void override virtual
Blocks until stop() is called.
Implements i_network_component::wait_for_stop().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 238 of file websocket_server.cpp.
    {
        lifecycle_.wait_for_stop();
    }
Member Data Documentation
acceptor_
std::unique_ptr<asio::ip::tcp::acceptor> kcenon::network::core::messaging_ws_server::acceptor_ private
TCP acceptor.
Definition at line 492 of file websocket_server.h.
acceptor_mutex_
std::mutex kcenon::network::core::messaging_ws_server::acceptor_mutex_ mutable private
Mutex protecting acceptor_ access.
Definition at line 493 of file websocket_server.h.
callbacks_
callbacks_t kcenon::network::core::messaging_ws_server::callbacks_ private
Callback manager.
Definition at line 486 of file websocket_server.h.
config_
ws_server_config kcenon::network::core::messaging_ws_server::config_ private
Server configuration.
Definition at line 488 of file websocket_server.h.
io_context_
std::unique_ptr<asio::io_context> kcenon::network::core::messaging_ws_server::io_context_ private
ASIO I/O context.
Definition at line 490 of file websocket_server.h.
io_context_future_
std::future<void> kcenon::network::core::messaging_ws_server::io_context_future_ private
Future for io_context run task.
Definition at line 496 of file websocket_server.h.
lifecycle_
utils::lifecycle_manager kcenon::network::core::messaging_ws_server::lifecycle_ private
Lifecycle state manager.
Definition at line 485 of file websocket_server.h.
Referenced by is_running(), and ~messaging_ws_server().
server_id_
std::string kcenon::network::core::messaging_ws_server::server_id_ private
Server identifier.
Definition at line 484 of file websocket_server.h.
Referenced by server_id().
session_mgr_
std::shared_ptr<ws_session_manager> kcenon::network::core::messaging_ws_server::session_mgr_ private
Session manager.
Definition at line 498 of file websocket_server.h.
Referenced by connection_count().
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::messaging_ws_server::thread_pool_ private
Thread pool for async operations.
Definition at line 495 of file websocket_server.h.
work_guard_
std::unique_ptr<asio::executor_work_guard<asio::io_context::executor_type> > kcenon::network::core::messaging_ws_server::work_guard_ private
Work guard.
Definition at line 491 of file websocket_server.h.
The documentation for this class was generated from the following files:
src/internal/http/websocket_server.h
src/http/websocket_server.cpp