Network System: kcenon::network::Result< T > Class Template Reference
kcenon::network::Result< T > Class Template Reference
#include <result_types.h>
Public Member Functions
Result (const T &val)
Result (T &&val)
Result (const simple_error &err)
bool is_ok () const
bool is_err () const
const T & value () const
T & value ()
const simple_error & error () const
operator bool () const
Static Public Member Functions
template<typename U = T>
static Result< T > ok (U &&value)
static Result< T > err (const simple_error &error)
static Result< T > err (int code, const std::string &message, const std::string &source="")
Private Attributes
std::variant< T, simple_error > data_
Detailed Description
template<typename T>
class kcenon::network::Result< T >
Examples
/home/runner/work/network_system/network_system/include/kcenon/network/types/result.h.
Definition at line 142 of file result_types.h.
Constructor & Destructor Documentation
Result() [1/3]
template<typename T > kcenon::network::Result< T >::Result (const T & val) inline
Definition at line 144 of file result_types.h.
: data_(val) {}
Result() [2/3]
template<typename T > kcenon::network::Result< T >::Result (T && val) inline
Definition at line 145 of file result_types.h.
: data_(std::forward<T>(val)) {}
Result() [3/3]
template<typename T > kcenon::network::Result< T >::Result (const simple_error & err) inline
Definition at line 146 of file result_types.h.
: data_(err) {}
Member Function Documentation
err() [1/2]
template<typename T > static Result< T > kcenon::network::Result< T >::err (const simple_error & error) inline static
Definition at line 154 of file result_types.h.
{
            return Result<T>(error);
        }
References kcenon::network::Result< T >::error().
Referenced by kcenon::network::core::session_handle::send(), and kcenon::network::core::session_model< SessionType >::send().
err() [2/2]
template<typename T > static Result< T > kcenon::network::Result< T >::err (int code, const std::string & message, const std::string & source = "") inline static
Definition at line 158 of file result_types.h.
{
            return Result<T>(simple_error(code, message, source));
        }
References kcenon::network::message.
error()
template<typename T > const simple_error & kcenon::network::Result< T >::error () const inline
Definition at line 168 of file result_types.h.
{ return std::get<simple_error>(data_); }
References kcenon::network::Result< T >::data_.
Referenced by kcenon::network::Result< T >::err().
is_err()
template<typename T > bool kcenon::network::Result< T >::is_err () const inline
Definition at line 163 of file result_types.h.
{ return !is_ok(); }
References kcenon::network::Result< T >::is_ok().
Referenced by kcenon::network::protocols::grpc::service_registry::impl::configure_server().
is_ok()
template<typename T > bool kcenon::network::Result< T >::is_ok () const inline
Definition at line 162 of file result_types.h.
{ return std::holds_alternative<T>(data_); }
References kcenon::network::Result< T >::data_.
Referenced by kcenon::network::Result< T >::is_err(), and kcenon::network::Result< T >::operator bool().
ok()
template<typename T > template<typename U = T> static Result< T > kcenon::network::Result< T >::ok (U && value) inline static
Definition at line 150 of file result_types.h.
{
            return Result<T>(std::forward<U>(value));
        }
References kcenon::network::Result< T >::value().
Referenced by kcenon::network::core::session_model< SessionType >::send().
operator bool()
template<typename T > kcenon::network::Result< T >::operator bool () const inline
Definition at line 170 of file result_types.h.
{ return is_ok(); }
References kcenon::network::Result< T >::is_ok().
value() [1/2]
template<typename T > T & kcenon::network::Result< T >::value () inline
Definition at line 166 of file result_types.h.
{ return std::get<T>(data_); }
References kcenon::network::Result< T >::data_.
value() [2/2]
template<typename T > const T & kcenon::network::Result< T >::value () const inline
Definition at line 165 of file result_types.h.
{ return std::get<T>(data_); }
References kcenon::network::Result< T >::data_.
Referenced by kcenon::network::Result< T >::ok().
Member Data Documentation
data_
template<typename T > std::variant<T, simple_error> kcenon::network::Result< T >::data_ private
Definition at line 173 of file result_types.h.
Referenced by kcenon::network::Result< T >::error(), kcenon::network::Result< T >::is_ok(), kcenon::network::Result< T >::value(), and kcenon::network::Result< T >::value().
The documentation for this class was generated from the following file:
include/kcenon/network/detail/utils/result_types.h