Network System: kcenon::network::integration::basic_logger::impl Class Reference
kcenon::network::integration::basic_logger::impl Class Reference
Public Member Functions
impl (log_level min_level)
void log (log_level level, const std::string &message)
void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function)
bool is_level_enabled (log_level level) const
void flush ()
void set_min_level (log_level level)
log_level get_min_level () const
Private Attributes
std::mutex mutex_
std::atomic< int > min_level_
Detailed Description
Definition at line 124 of file logger_integration.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::integration::basic_logger::impl::impl (log_level min_level) inline explicit
Definition at line 126 of file logger_integration.cpp.
: min_level_(static_cast<int>(min_level)) {}
Member Function Documentation
flush()
void kcenon::network::integration::basic_logger::impl::flush () inline
Definition at line 172 of file logger_integration.cpp.
                 {
        std::lock_guard<std::mutex> lock(mutex_);
        std::fflush(stdout);
        std::fflush(stderr);
    }
Referenced by kcenon::network::integration::basic_logger::flush().
get_min_level()
log_level kcenon::network::integration::basic_logger::impl::get_min_level () const inline
Definition at line 182 of file logger_integration.cpp.
{
        return static_cast<log_level>(min_level_.load());
    }
Referenced by kcenon::network::integration::basic_logger::get_min_level().
is_level_enabled()
bool kcenon::network::integration::basic_logger::impl::is_level_enabled (log_level level) const inline
Definition at line 168 of file logger_integration.cpp.
{
        return static_cast<int>(level) >= min_level_;
    }
Referenced by kcenon::network::integration::basic_logger::is_level_enabled().
log() [1/2]
void kcenon::network::integration::basic_logger::impl::log (log_level level, const std::string & message) inline
Definition at line 128 of file logger_integration.cpp.
{
        if (static_cast<int>(level) < min_level_) return;
        std::lock_guard<std::mutex> lock(mutex_);
        auto timestamp = get_timestamp();
        std::ostringstream oss;
        oss << "[" << timestamp << "] "
            << "[" << level_to_string(level) << "] "
            << "[network_system] "
            << message;
        auto* target = (level >= log_level::error) ? stderr : stdout;
        const auto& record = oss.str();
        std::fwrite(record.data(), 1, record.size(), target);
        std::fputc('\n', target);
        std::fflush(target);
    }
References kcenon::network::integration::get_timestamp(), kcenon::network::integration::level_to_string(), and kcenon::network::message.
Referenced by kcenon::network::integration::basic_logger::log(), and kcenon::network::integration::basic_logger::log().
log() [2/2]
void kcenon::network::integration::basic_logger::impl::log (log_level level, const std::string & message, const std::string & file, int line, const std::string & function) inline
Definition at line 147 of file logger_integration.cpp.
{
        if (static_cast<int>(level) < min_level_) return;
        std::lock_guard<std::mutex> lock(mutex_);
        auto timestamp = get_timestamp();
        std::ostringstream oss;
        oss << "[" << timestamp << "] "
            << "[" << level_to_string(level) << "] "
            << "[network_system] "
            << message
            << " (" << file << ":" << line << " in " << function << ")";
        auto* target = (level >= log_level::error) ? stderr : stdout;
        const auto& record = oss.str();
        std::fwrite(record.data(), 1, record.size(), target);
        std::fputc('\n', target);
        std::fflush(target);
    }
References kcenon::network::integration::get_timestamp(), kcenon::network::integration::level_to_string(), and kcenon::network::message.
set_min_level()
void kcenon::network::integration::basic_logger::impl::set_min_level (log_level level) inline
Definition at line 178 of file logger_integration.cpp.
{
        min_level_ = static_cast<int>(level);
    }
Referenced by kcenon::network::integration::basic_logger::set_min_level().
Member Data Documentation
min_level_
std::atomic<int> kcenon::network::integration::basic_logger::impl::min_level_ private
Definition at line 188 of file logger_integration.cpp.
mutex_
std::mutex kcenon::network::integration::basic_logger::impl::mutex_ mutable private
Definition at line 187 of file logger_integration.cpp.
The documentation for this class was generated from the following file:
src/integration/logger_integration.cpp