Network System: kcenon::network::unified::adapters::ws_listener_adapter Class Reference
kcenon::network::unified::adapters::ws_listener_adapter Class Reference
Adapter that wraps messaging_ws_server to implement i_listener.
#include <ws_listener_adapter.h>
Public Member Functions
ws_listener_adapter (std::string_view listener_id)
Constructs an adapter with a unique listener ID.
~ws_listener_adapter () override
Destructor ensures proper cleanup.
ws_listener_adapter (const ws_listener_adapter &)=delete
ws_listener_adapter & operator= (const ws_listener_adapter &)=delete
ws_listener_adapter (ws_listener_adapter &&)=delete
ws_listener_adapter & operator= (ws_listener_adapter &&)=delete
auto start (const endpoint_info &bind_address) -> VoidResult override
Starts listening for incoming connections.
auto start (uint16_t port) -> VoidResult override
Starts listening on a specific port (all interfaces)
auto stop () noexcept -> void override
Stops listening and closes all connections.
auto set_callbacks (listener_callbacks callbacks) -> void override
Sets all listener callbacks at once.
auto set_accept_callback (accept_callback_t callback) -> void override
Sets the accept callback for new connections.
auto is_listening () const noexcept -> bool override
Checks if the listener is currently listening.
auto local_endpoint () const noexcept -> endpoint_info override
Gets the local endpoint the listener is bound to.
auto connection_count () const noexcept -> size_t override
Gets the number of active connections.
auto send_to (std::string_view connection_id, std::span< const std::byte > data) -> VoidResult override
Sends data to a specific connection.
auto broadcast (std::span< const std::byte > data) -> VoidResult override
Broadcasts data to all connected clients.
auto close_connection (std::string_view connection_id) noexcept -> void override
Closes a specific connection.
auto wait_for_stop () -> void override
Blocks until the listener has stopped.
auto set_path (std::string_view path) -> void
Sets the WebSocket path for the server.
Public Member Functions inherited from kcenon::network::unified::i_listener
virtual ~i_listener ()=default
Virtual destructor.
i_listener (const i_listener &)=delete
i_listener & operator= (const i_listener &)=delete
i_listener (i_listener &&)=default
i_listener & operator= (i_listener &&)=default
Private Member Functions
auto setup_internal_callbacks () -> void
Sets up internal callbacks to bridge to unified callbacks.
Private Attributes
std::string listener_id_
std::shared_ptr< core::messaging_ws_server > server_
std::string ws_path_ = "/"
std::mutex callbacks_mutex_
listener_callbacks callbacks_
accept_callback_t accept_callback_
std::mutex endpoint_mutex_
endpoint_info local_endpoint_
std::mutex connections_mutex_
std::unordered_map< std::string, std::shared_ptr< core::ws_connection > > connections_
Additional Inherited Members
Public Types inherited from kcenon::network::unified::i_listener
using accept_callback_t = std::function<void(std::unique_ptr<i_connection>)>
Callback for accepted connections.
Protected Member Functions inherited from kcenon::network::unified::i_listener
i_listener ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps messaging_ws_server to implement i_listener.
This adapter bridges the existing WebSocket server implementation with the new unified interface, enabling protocol factory functions to return i_listener while using the battle-tested underlying implementation.
Thread Safety
Thread-safe. All methods can be called from any thread.
Connection Management
Accepted WebSocket connections are tracked internally and can be accessed via send_to(), broadcast(), and close_connection() methods.
Definition at line 33 of file ws_listener_adapter.h.
Constructor & Destructor Documentation
ws_listener_adapter() [1/3]
kcenon::network::unified::adapters::ws_listener_adapter::ws_listener_adapter (std::string_view listener_id) explicit
Constructs an adapter with a unique listener ID.
Parameters
listener_id Unique identifier for this listener
Definition at line 12 of file ws_listener_adapter.cpp.
    : listener_id_(listener_id)
    , server_(std::make_shared<core::messaging_ws_server>(listener_id))
{
    setup_internal_callbacks();
}
References setup_internal_callbacks().
~ws_listener_adapter()
kcenon::network::unified::adapters::ws_listener_adapter::~ws_listener_adapter () override
Destructor ensures proper cleanup.
Definition at line 19 of file ws_listener_adapter.cpp.
{
    stop();
}
References stop().
ws_listener_adapter() [2/3]
kcenon::network::unified::adapters::ws_listener_adapter::ws_listener_adapter (const ws_listener_adapter &) delete
ws_listener_adapter() [3/3]
kcenon::network::unified::adapters::ws_listener_adapter::ws_listener_adapter (ws_listener_adapter &&) delete
Member Function Documentation
broadcast()
auto kcenon::network::unified::adapters::ws_listener_adapter::broadcast (std::span< const std::byte > data) -> VoidResult nodiscard override virtual
Broadcasts data to all connected clients.
Parameters
data The data to send to all connections
Returns
VoidResult indicating success or failure
Behavior
Sends data to all currently connected clients
Returns success if at least one send succeeded
Failures on individual connections are logged but don't fail the call
Implements kcenon::network::unified::i_listener.
Definition at line 140 of file ws_listener_adapter.cpp.
{
    if (!server_ || !server_->is_running()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "Server is not running"
        );
    }
    std::vector<uint8_t> buffer(data.size());
    std::memcpy(buffer.data(), data.data(), data.size());
    server_->broadcast_binary(buffer);
    return ok();
}
References kcenon::network::error_void(), and kcenon::network::ok().
close_connection()
auto kcenon::network::unified::adapters::ws_listener_adapter::close_connection (std::string_view connection_id) -> void override virtual noexcept
Closes a specific connection.
Parameters
connection_id The ID of the connection to close
Triggers the on_disconnect callback for the connection.
Implements kcenon::network::unified::i_listener.
Definition at line 156 of file ws_listener_adapter.cpp.
{
    std::shared_ptr<core::ws_connection> conn;
    {
        std::lock_guard lock(connections_mutex_);
        auto it = connections_.find(std::string(connection_id));
        if (it != connections_.end()) {
            conn = it->second;
            connections_.erase(it);
        }
    }
    if (conn) {
        conn->close();
    }
}
connection_count()
auto kcenon::network::unified::adapters::ws_listener_adapter::connection_count () const -> size_t nodiscard override virtual noexcept
Gets the number of active connections.
Returns
The count of currently connected clients
Implements kcenon::network::unified::i_listener.
Definition at line 105 of file ws_listener_adapter.cpp.
{
    std::lock_guard lock(connections_mutex_);
    return connections_.size();
}
References connections_, and connections_mutex_.
is_listening()
auto kcenon::network::unified::adapters::ws_listener_adapter::is_listening () const -> bool nodiscard override virtual noexcept
Checks if the listener is currently listening.
Returns
true if listening for connections, false otherwise
Implements kcenon::network::unified::i_listener.
Definition at line 94 of file ws_listener_adapter.cpp.
{
    return server_ && server_->is_running();
}
References server_.
local_endpoint()
auto kcenon::network::unified::adapters::ws_listener_adapter::local_endpoint () const -> endpoint_info nodiscard override virtual noexcept
Gets the local endpoint the listener is bound to.
Returns
endpoint_info of the local binding
Returns valid information only when listening. Returns empty endpoint_info if not bound.
Implements kcenon::network::unified::i_listener.
Definition at line 99 of file ws_listener_adapter.cpp.
{
    std::lock_guard lock(endpoint_mutex_);
    return local_endpoint_;
}
References endpoint_mutex_, and local_endpoint_.
operator=() [1/2]
ws_listener_adapter & kcenon::network::unified::adapters::ws_listener_adapter::operator= (const ws_listener_adapter &) delete
operator=() [2/2]
ws_listener_adapter & kcenon::network::unified::adapters::ws_listener_adapter::operator= (ws_listener_adapter &&) delete
send_to()
auto kcenon::network::unified::adapters::ws_listener_adapter::send_to (std::string_view connection_id, std::span< const std::byte > data) -> VoidResult nodiscard override virtual
Sends data to a specific connection.
Parameters
connection_id The ID of the target connection
data The data to send
Returns
VoidResult indicating success or failure
Error Conditions
Returns error if connection_id not found
Returns error if send fails
Implements kcenon::network::unified::i_listener.
Definition at line 111 of file ws_listener_adapter.cpp.
{
    std::shared_ptr<core::ws_connection> conn;
    {
        std::lock_guard lock(connections_mutex_);
        auto it = connections_.find(std::string(connection_id));
        if (it == connections_.end()) {
            return error_void(
                static_cast<int>(std::errc::no_such_device_or_address),
                "Connection not found: " + std::string(connection_id)
            );
        }
        conn = it->second;
    }
    if (!conn || !conn->is_connected()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "Connection is no longer valid"
        );
    }
    std::vector<uint8_t> buffer(data.size());
    std::memcpy(buffer.data(), data.data(), data.size());
    return conn->send_binary(std::move(buffer));
}
References kcenon::network::error_void().
set_accept_callback()
auto kcenon::network::unified::adapters::ws_listener_adapter::set_accept_callback (accept_callback_t callback) -> void override virtual
Sets the accept callback for new connections.
Parameters
callback Called when a connection is accepted
This callback receives ownership of the connection object. If set, the on_accept callback in listener_callbacks is not called.
Thread Safety
Thread-safe. Callback invoked from I/O thread.
Implements kcenon::network::unified::i_listener.
Definition at line 88 of file ws_listener_adapter.cpp.
{
    std::lock_guard lock(callbacks_mutex_);
    accept_callback_ = std::move(callback);
}
set_callbacks()
auto kcenon::network::unified::adapters::ws_listener_adapter::set_callbacks (listener_callbacks callbacks) -> void override virtual
Sets all listener callbacks at once.
Parameters
callbacks The callback structure with handlers
Replaces all previously set callbacks.
Thread Safety
Thread-safe, but callbacks are invoked from I/O threads.
Implements kcenon::network::unified::i_listener.
Definition at line 78 of file ws_listener_adapter.cpp.
{
    {
        std::lock_guard lock(callbacks_mutex_);
        callbacks_ = std::move(callbacks);
    }
    setup_internal_callbacks();
}
set_path()
auto kcenon::network::unified::adapters::ws_listener_adapter::set_path (std::string_view path) -> void
Sets the WebSocket path for the server.
Parameters
path The WebSocket path to handle (e.g., "/ws", "/socket.io")
Definition at line 180 of file ws_listener_adapter.cpp.
{
    ws_path_ = std::string(path);
}
setup_internal_callbacks()
auto kcenon::network::unified::adapters::ws_listener_adapter::setup_internal_callbacks () -> void private
Sets up internal callbacks to bridge to unified callbacks.
Definition at line 185 of file ws_listener_adapter.cpp.
{
    if (!server_) {
        return;
    }
    // Bridge connection callback
    server_->set_connection_callback(
        [this](std::shared_ptr<interfaces::i_websocket_session> session) {
            if (!session) {
                return;
            }
            // Use the session's ID as connection ID
            std::string conn_id(session->id());
            // Try to get the actual ws_connection from server
            auto ws_conn = server_->get_connection(conn_id);
            if (ws_conn) {
                std::lock_guard lock(connections_mutex_);
                connections_[conn_id] = ws_conn;
            }
            // Call user callbacks
            {
                std::lock_guard lock(callbacks_mutex_);
                if (callbacks_.on_accept) {
                    callbacks_.on_accept(conn_id);
                }
            }
        });
    // Bridge disconnection callback
    server_->set_disconnection_callback(
        [this](std::string_view session_id, uint16_t /*code*/, std::string_view /*reason*/) {
            std::string conn_id(session_id);
            {
                std::lock_guard lock(connections_mutex_);
                connections_.erase(conn_id);
            }
            {
                std::lock_guard lock(callbacks_mutex_);
                if (callbacks_.on_disconnect) {
                    callbacks_.on_disconnect(conn_id);
                }
            }
        });
    // Bridge binary message callback
    server_->set_binary_callback(
        [this](std::string_view session_id, const std::vector<uint8_t>& data) {
            std::string conn_id(session_id);
            std::lock_guard lock(callbacks_mutex_);
            if (callbacks_.on_data) {
                std::span<const std::byte> byte_span(
                    reinterpret_cast<const std::byte*>(data.data()),
                    data.size()
                );
                callbacks_.on_data(conn_id, byte_span);
            }
        });
    // Also bridge text messages as binary data for unified interface
    server_->set_text_callback(
        [this](std::string_view session_id, const std::string& text) {
            std::string conn_id(session_id);
            std::lock_guard lock(callbacks_mutex_);
            if (callbacks_.on_data) {
                std::span<const std::byte> byte_span(
                    reinterpret_cast<const std::byte*>(text.data()),
                    text.size()
                );
                callbacks_.on_data(conn_id, byte_span);
            }
        });
    // Bridge error callback
    server_->set_error_callback(
        [this](std::string_view session_id, std::error_code ec) {
            std::string conn_id(session_id);
            std::lock_guard lock(callbacks_mutex_);
            if (callbacks_.on_error) {
                callbacks_.on_error(conn_id, ec);
            }
        });
}
Referenced by ws_listener_adapter().
start() [1/2]
auto kcenon::network::unified::adapters::ws_listener_adapter::start (const endpoint_info & bind_address) -> VoidResult nodiscard override virtual
Starts listening for incoming connections.
Parameters
bind_address The local address to bind to
Returns
VoidResult indicating success or failure
Behavior
Binds to the specified local address
Begins accepting incoming connections
Accepted connections are delivered via callbacks
Error Conditions
Returns error if already listening
Returns error if bind fails (e.g., address in use)
Returns error if listen fails
Thread Safety
Thread-safe. Only one start operation can succeed at a time.
Implements kcenon::network::unified::i_listener.
Definition at line 24 of file ws_listener_adapter.cpp.
{
    if (!server_) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "Server is not initialized"
        );
    }
    if (server_->is_running()) {
        return error_void(
            static_cast<int>(std::errc::already_connected),
            "Already listening"
        );
    }
    {
        std::lock_guard lock(endpoint_mutex_);
        local_endpoint_ = bind_address;
    }
    {
        std::lock_guard lock(connections_mutex_);
        connections_.clear();
    }
    return server_->start_server(bind_address.port, ws_path_);
}
References kcenon::network::error_void().
start() [2/2]
auto kcenon::network::unified::adapters::ws_listener_adapter::start (uint16_t port) -> VoidResult nodiscard override virtual
Starts listening on a specific port (all interfaces)
Parameters
port The port number to listen on
Returns
VoidResult indicating success or failure
Convenience overload that binds to all interfaces (0.0.0.0 / ::).
Implements kcenon::network::unified::i_listener.
Definition at line 53 of file ws_listener_adapter.cpp.
{
    return start(endpoint_info{"0.0.0.0", port});
}
stop()
auto kcenon::network::unified::adapters::ws_listener_adapter::stop () -> void override virtual noexcept
Stops listening and closes all connections.
Behavior
Stops accepting new connections
Closes all active connections
Triggers on_disconnect callback for each connection
Thread Safety
Thread-safe. Safe to call multiple times.
Implements kcenon::network::unified::i_listener.
Definition at line 58 of file ws_listener_adapter.cpp.
{
    if (server_ && server_->is_running()) {
        // Notify disconnection for all connections
        {
            std::lock_guard cb_lock(callbacks_mutex_);
            std::lock_guard conn_lock(connections_mutex_);
            if (callbacks_.on_disconnect) {
                for (const auto& [conn_id, _] : connections_) {
                    callbacks_.on_disconnect(conn_id);
                }
            }
            connections_.clear();
        }
        (void)server_->stop_server();
    }
}
References callbacks_, callbacks_mutex_, connections_, connections_mutex_, kcenon::network::unified::listener_callbacks::on_disconnect, and server_.
Referenced by ~ws_listener_adapter().
wait_for_stop()
auto kcenon::network::unified::adapters::ws_listener_adapter::wait_for_stop () -> void override virtual
Blocks until the listener has stopped.
Waits for all connections to close and the listener to fully stop.
Thread Safety
Safe to call from any thread.
Implements kcenon::network::unified::i_listener.
Definition at line 173 of file ws_listener_adapter.cpp.
{
    if (server_) {
        server_->wait_for_stop();
    }
}
Member Data Documentation
accept_callback_
accept_callback_t kcenon::network::unified::adapters::ws_listener_adapter::accept_callback_ private
Definition at line 92 of file ws_listener_adapter.h.
callbacks_
listener_callbacks kcenon::network::unified::adapters::ws_listener_adapter::callbacks_ private
Definition at line 91 of file ws_listener_adapter.h.
Referenced by stop().
callbacks_mutex_
std::mutex kcenon::network::unified::adapters::ws_listener_adapter::callbacks_mutex_ mutable private
Definition at line 90 of file ws_listener_adapter.h.
Referenced by stop().
connections_
std::unordered_map<std::string, std::shared_ptr<core::ws_connection> > kcenon::network::unified::adapters::ws_listener_adapter::connections_ private
Definition at line 99 of file ws_listener_adapter.h.
Referenced by connection_count(), and stop().
connections_mutex_
std::mutex kcenon::network::unified::adapters::ws_listener_adapter::connections_mutex_ mutable private
Definition at line 98 of file ws_listener_adapter.h.
Referenced by connection_count(), and stop().
endpoint_mutex_
std::mutex kcenon::network::unified::adapters::ws_listener_adapter::endpoint_mutex_ mutable private
Definition at line 94 of file ws_listener_adapter.h.
Referenced by local_endpoint().
listener_id_
std::string kcenon::network::unified::adapters::ws_listener_adapter::listener_id_ private
Definition at line 86 of file ws_listener_adapter.h.
local_endpoint_
endpoint_info kcenon::network::unified::adapters::ws_listener_adapter::local_endpoint_ private
Definition at line 95 of file ws_listener_adapter.h.
Referenced by local_endpoint().
server_
std::shared_ptr<core::messaging_ws_server> kcenon::network::unified::adapters::ws_listener_adapter::server_ private
Definition at line 87 of file ws_listener_adapter.h.
Referenced by is_listening(), and stop().
ws_path_
std::string kcenon::network::unified::adapters::ws_listener_adapter::ws_path_ = "/" private
Definition at line 88 of file ws_listener_adapter.h.
The documentation for this class was generated from the following files:
src/internal/unified/adapters/ws_listener_adapter.h
src/unified/adapters/ws_listener_adapter.cpp