Network System: kcenon::network::protocols::quic::loss_detector Class Reference
kcenon::network::protocols::quic::loss_detector Class Reference
QUIC loss detection (RFC 9002 Section 6)
#include <loss_detector.h>
Classes
struct space_state
Per packet-number-space state (RFC 9002 Appendix A.1)
Public Member Functions
loss_detector (rtt_estimator &rtt)
Constructor.
auto on_packet_sent (const sent_packet &packet) -> void
Record a sent packet.
auto on_ack_received (const ack_frame &ack, encryption_level level, std::chrono::steady_clock::time_point recv_time) -> loss_detection_result
Process received ACK frame (RFC 9002 Section 6)
auto next_timeout () const -> std::optional< std::chrono::steady_clock::time_point >
Get the time of the next scheduled timeout.
auto on_timeout () -> loss_detection_result
Handle timeout expiry (RFC 9002 Section 6.2)
auto largest_acked (encryption_level level) const noexcept -> uint64_t
Get the largest acknowledged packet number for a space.
auto pto_count () const noexcept -> uint32_t
Get the current PTO count.
auto reset_pto_count () noexcept -> void
Reset PTO count to zero.
auto has_unacked_packets (encryption_level level) const -> bool
Check if there are any unacked packets in the given space.
auto bytes_in_flight (encryption_level level) const -> size_t
Get bytes in flight for a packet number space.
auto total_bytes_in_flight () const -> size_t
Get total bytes in flight across all spaces.
auto discard_space (encryption_level level) -> void
Discard packet number space (e.g., after handshake keys discarded)
auto set_handshake_confirmed (bool confirmed) noexcept -> void
Set handshake confirmed status.
auto get_ecn_tracker () noexcept -> class ecn_tracker &
Get the ECN tracker.
auto get_ecn_tracker () const noexcept -> const class ecn_tracker &
Get the ECN tracker (const)
Private Member Functions
auto space_index (encryption_level level) const noexcept -> size_t
Get space index from encryption level.
auto detect_lost_packets (encryption_level level, std::chrono::steady_clock::time_point now) -> std::vector< sent_packet >
Detect lost packets (RFC 9002 Section 6.1)
auto set_loss_detection_timer () -> void
Set loss detection timer (RFC 9002 Section 6.2)
auto get_loss_time_and_space () const -> std::pair< std::chrono::steady_clock::time_point, encryption_level >
Get loss time and space (RFC 9002 Appendix A.8)
auto get_pto_time_and_space () const -> std::pair< std::chrono::steady_clock::time_point, encryption_level >
Get PTO time and space (RFC 9002 Appendix A.8)
Private Attributes
rtt_estimator & rtt_
Reference to RTT estimator.
class ecn_tracker ecn_tracker_
ECN tracker for ECN feedback processing.
std::array< space_state, 3 > spaces_
Per packet-number-space state (Initial, Handshake, Application)
uint32_t pto_count_ {0}
Number of times PTO has expired without receiving an ACK.
bool handshake_confirmed_ {false}
True if the handshake is confirmed.
std::chrono::steady_clock::time_point loss_detection_timer_
Scheduled loss detection timeout.
bool timer_armed_ {false}
True if loss detection timer is armed.
Static Private Attributes
static constexpr uint32_t kPacketThreshold = 3
Packet threshold (RFC 9002 Section 6.1.1)
static constexpr double kTimeThreshold = 9.0 / 8.0
Time threshold multiplier (RFC 9002 Section 6.1.2)
static constexpr auto kGranularity = std::chrono::milliseconds{1}
Timer granularity (RFC 9002 Section 6.1.2)
Detailed Description
QUIC loss detection (RFC 9002 Section 6)
Implements packet loss detection using both packet number threshold and time threshold algorithms as specified in RFC 9002.
Definition at line 118 of file loss_detector.h.
Constructor & Destructor Documentation
loss_detector()
kcenon::network::protocols::quic::loss_detector::loss_detector (rtt_estimator & rtt) explicit
Constructor.
Parameters
rtt Reference to RTT estimator (must outlive this object)
Definition at line 41 of file loss_detector.cpp.
    : rtt_(rtt)
    , ecn_tracker_{}
    , spaces_{}
    , pto_count_{0}
    , handshake_confirmed_{false}
    , loss_detection_timer_{}
    , timer_armed_{false}
{
}
Member Function Documentation
bytes_in_flight()
auto kcenon::network::protocols::quic::loss_detector::bytes_in_flight (encryption_level level) const -> size_t
Get bytes in flight for a packet number space.
Parameters
level Encryption level
Returns
Bytes in flight
Definition at line 517 of file loss_detector.cpp.
{
    auto idx = space_index(level);
    return spaces_[idx].bytes_in_flight;
}
detect_lost_packets()
auto kcenon::network::protocols::quic::loss_detector::detect_lost_packets (encryption_level level, std::chrono::steady_clock::time_point now) -> std::vector<sent_packet> private
Detect lost packets (RFC 9002 Section 6.1)
Definition at line 251 of file loss_detector.cpp.
{
    auto idx = space_index(level);
    auto& space = spaces_[idx];
    std::vector<sent_packet> lost;
    if (!space.largest_acked_set)
    {
        return lost;
    }
    // Calculate loss delay (RFC 9002 Section 6.1.2)
    auto smoothed = rtt_.smoothed_rtt();
    auto min_rtt = rtt_.min_rtt();
    if (min_rtt == std::chrono::microseconds::max())
    {
        min_rtt = smoothed;
    }
    auto max_rtt = std::max(smoothed, min_rtt);
    auto loss_delay_us = static_cast<int64_t>(
        kTimeThreshold * static_cast<double>(max_rtt.count()));
    auto granularity_us = std::chrono::duration_cast<std::chrono::microseconds>(
        kGranularity).count();
    auto loss_delay = std::chrono::microseconds{
        std::max(loss_delay_us, granularity_us)};
    auto lost_send_time = now - loss_delay;
    // Reset loss time for this space
    space.loss_time = std::chrono::steady_clock::time_point{};
    for (auto it = space.sent_packets.begin(); it != space.sent_packets.end();)
    {
        auto& [pn, packet] = *it;
        if (pn > space.largest_acked)
        {
            ++it;
            continue;
        }
        // Check if packet is lost by packet threshold or time threshold
        bool time_lost = packet.sent_time <= lost_send_time;
        bool reorder_lost = (space.largest_acked >= pn + kPacketThreshold);
        if (time_lost || reorder_lost)
        {
            if (packet.in_flight)
            {
                space.bytes_in_flight -= packet.sent_bytes;
            }
            lost.push_back(std::move(packet));
            it = space.sent_packets.erase(it);
        }
        else
        {
            // This packet might be lost later by time threshold
            auto potential_loss_time = packet.sent_time + loss_delay;
            if (space.loss_time == std::chrono::steady_clock::time_point{} ||
                potential_loss_time < space.loss_time)
            {
                space.loss_time = potential_loss_time;
            }
            ++it;
        }
    }
    return lost;
}
discard_space()
auto kcenon::network::protocols::quic::loss_detector::discard_space (encryption_level level) -> void
Discard packet number space (e.g., after handshake keys discarded)
Parameters
level Encryption level to discard
Definition at line 533 of file loss_detector.cpp.
{
    auto idx = space_index(level);
    spaces_[idx] = space_state{};
    set_loss_detection_timer();
}
get_ecn_tracker() [1/2]
auto kcenon::network::protocols::quic::loss_detector::get_ecn_tracker () const -> const class ecn_tracker& inline noexcept
Get the ECN tracker (const)
Returns
Const reference to the ECN tracker
Definition at line 230 of file loss_detector.h.
    {
        return ecn_tracker_;
    }
References ecn_tracker_.
get_ecn_tracker() [2/2]
auto kcenon::network::protocols::quic::loss_detector::get_ecn_tracker () -> class ecn_tracker& inline noexcept
Get the ECN tracker.
Returns
Reference to the ECN tracker
Definition at line 221 of file loss_detector.h.
    {
        return ecn_tracker_;
    }
References ecn_tracker_.
get_loss_time_and_space()
auto kcenon::network::protocols::quic::loss_detector::get_loss_time_and_space () const -> std::pair<std::chrono::steady_clock::time_point, encryption_level> private
Get loss time and space (RFC 9002 Appendix A.8)
Definition at line 361 of file loss_detector.cpp.
{
    auto earliest_loss_time = std::chrono::steady_clock::time_point::max();
    auto earliest_level = encryption_level::initial;
    for (size_t i = 0; i < spaces_.size(); ++i)
    {
        auto& space = spaces_[i];
        if (space.loss_time != std::chrono::steady_clock::time_point{} &&
            space.loss_time < earliest_loss_time)
        {
            earliest_loss_time = space.loss_time;
            switch (i)
            {
            case 0:
                earliest_level = encryption_level::initial;
                break;
            case 1:
                earliest_level = encryption_level::handshake;
                break;
            case 2:
                earliest_level = encryption_level::application;
                break;
            }
        }
    }
    if (earliest_loss_time == std::chrono::steady_clock::time_point::max())
    {
        earliest_loss_time = std::chrono::steady_clock::time_point{};
    }
    return {earliest_loss_time, earliest_level};
}
get_pto_time_and_space()
auto kcenon::network::protocols::quic::loss_detector::get_pto_time_and_space () const -> std::pair<std::chrono::steady_clock::time_point, encryption_level> private
Get PTO time and space (RFC 9002 Appendix A.8)
Definition at line 397 of file loss_detector.cpp.
{
    auto pto_duration = rtt_.pto() * (1 << pto_count_);  // Exponential backoff
    auto earliest_pto_time = std::chrono::steady_clock::time_point::max();
    auto earliest_level = encryption_level::application;
    for (size_t i = 0; i < spaces_.size(); ++i)
    {
        auto& space = spaces_[i];
        // Skip spaces with no ack-eliciting packets
        bool has_ack_eliciting = false;
        for (const auto& [pn, pkt] : space.sent_packets)
        {
            if (pkt.ack_eliciting)
            {
                has_ack_eliciting = true;
                break;
            }
        }
        if (!has_ack_eliciting)
        {
            continue;
        }
        // Don't include application space if handshake not confirmed
        if (i == 2 && !handshake_confirmed_)
        {
            continue;
        }
        auto pto_time = space.time_of_last_ack_eliciting + pto_duration;
        if (pto_time < earliest_pto_time)
        {
            earliest_pto_time = pto_time;
            switch (i)
            {
            case 0:
                earliest_level = encryption_level::initial;
                break;
            case 1:
                earliest_level = encryption_level::handshake;
                break;
            case 2:
                earliest_level = encryption_level::application;
                break;
            }
        }
    }
    if (earliest_pto_time == std::chrono::steady_clock::time_point::max())
    {
        earliest_pto_time = std::chrono::steady_clock::time_point{};
    }
    return {earliest_pto_time, earliest_level};
}
has_unacked_packets()
auto kcenon::network::protocols::quic::loss_detector::has_unacked_packets (encryption_level level) const -> bool
Check if there are any unacked packets in the given space.
Parameters
level Encryption level
Returns
True if there are unacked packets
Definition at line 511 of file loss_detector.cpp.
{
    auto idx = space_index(level);
    return !spaces_[idx].sent_packets.empty();
}
largest_acked()
auto kcenon::network::protocols::quic::loss_detector::largest_acked (encryption_level level) const -> uint64_t noexcept
Get the largest acknowledged packet number for a space.
Parameters
level Encryption level (maps to packet number space)
Returns
Largest acknowledged packet number
Definition at line 505 of file loss_detector.cpp.
{
    auto idx = space_index(level);
    return spaces_[idx].largest_acked;
}
next_timeout()
auto kcenon::network::protocols::quic::loss_detector::next_timeout () const -> std::optional<std::chrono::steady_clock::time_point>
Get the time of the next scheduled timeout.
Returns
Next timeout time point, or nullopt if no timer is set
Definition at line 323 of file loss_detector.cpp.
{
    if (!timer_armed_)
    {
        return std::nullopt;
    }
    return loss_detection_timer_;
}
Referenced by kcenon::network::protocols::quic::connection::next_timeout(), and kcenon::network::protocols::quic::connection::on_timeout().
on_ack_received()
auto kcenon::network::protocols::quic::loss_detector::on_ack_received (const ack_frame & ack, encryption_level level, std::chrono::steady_clock::time_point recv_time) -> loss_detection_result
Process received ACK frame (RFC 9002 Section 6)
Parameters
ack ACK frame received from peer
level Encryption level of the ACK
recv_time Time the ACK was received
Returns
Loss detection result with acked and lost packets
Definition at line 90 of file loss_detector.cpp.
{
    loss_detection_result result;
    auto idx = space_index(level);
    auto& space = spaces_[idx];
    auto largest_newly_acked = ack.largest_acknowledged;
    if (!space.largest_acked_set || largest_newly_acked > space.largest_acked)
    {
        space.largest_acked = largest_newly_acked;
        space.largest_acked_set = true;
    }
    // Process the ACK ranges to find newly acknowledged packets
    // First range starts at largest_acknowledged and goes back ack_range_count
    uint64_t current_pn = ack.largest_acknowledged;
    size_t first_range_count = ack.ranges.empty() ? 0 : ack.ranges[0].length;
    // Process first ack block (largest_acknowledged down to largest - first_range)
    for (uint64_t i = 0; i <= first_range_count && current_pn > 0; ++i)
    {
        auto it = space.sent_packets.find(current_pn - i);
        if (it != space.sent_packets.end())
        {
            auto& pkt = it->second;
            if (pkt.in_flight)
            {
                space.bytes_in_flight -= pkt.sent_bytes;
            }
            result.acked_packets.push_back(std::move(pkt));
            space.sent_packets.erase(it);
        }
    }
    // Also check largest_acknowledged itself
    {
        auto it = space.sent_packets.find(ack.largest_acknowledged);
        if (it != space.sent_packets.end())
        {
            auto& pkt = it->second;
            if (pkt.in_flight)
            {
                space.bytes_in_flight -= pkt.sent_bytes;
            }
            result.acked_packets.push_back(std::move(pkt));
            space.sent_packets.erase(it);
        }
    }
    // Process additional ACK ranges
    current_pn = ack.largest_acknowledged;
    if (!ack.ranges.empty())
    {
        current_pn -= ack.ranges[0].length + 1;  // After first range
    }
    for (size_t r = 1; r < ack.ranges.size(); ++r)
    {
        // Skip the gap
        auto gap = ack.ranges[r].gap;
        if (current_pn >= gap + 2)
        {
            current_pn -= gap + 2;
        }
        else
        {
            break;
        }
        // Process this range
        auto range_len = ack.ranges[r].length;
        for (uint64_t i = 0; i <= range_len && current_pn > 0; ++i)
        {
            auto it = space.sent_packets.find(current_pn - i);
            if (it != space.sent_packets.end())
            {
                auto& pkt = it->second;
                if (pkt.in_flight)
                {
                    space.bytes_in_flight -= pkt.sent_bytes;
                }
                result.acked_packets.push_back(std::move(pkt));
                space.sent_packets.erase(it);
            }
        }
        if (current_pn >= range_len + 1)
        {
            current_pn -= range_len + 1;
        }
        else
        {
            break;
        }
    }
    // Update RTT if we got a sample from the largest acknowledged packet
    if (!result.acked_packets.empty())
    {
        // Find the largest acked packet to compute RTT
        auto largest_it = std::find_if(
            result.acked_packets.begin(),
            result.acked_packets.end(),
            [largest_newly_acked](const sent_packet& p) {
                return p.packet_number == largest_newly_acked;
            });
        if (largest_it != result.acked_packets.end())
        {
            auto latest_rtt = std::chrono::duration_cast<std::chrono::microseconds>(
                recv_time - largest_it->sent_time);
            auto ack_delay_us = std::chrono::microseconds{
                static_cast<int64_t>(ack.ack_delay)};  // Encoded value
            rtt_.update(latest_rtt, ack_delay_us, handshake_confirmed_);
        }
        // Reset PTO count since we got an ACK
        pto_count_ = 0;
    }
    // Detect lost packets
    auto lost = detect_lost_packets(level, recv_time);
    if (!lost.empty())
    {
        result.event = loss_detection_event::packet_lost;
        result.lost_packets = std::move(lost);
    }
    // Process ECN counts if present (RFC 9000 Section 13.4, RFC 9002 Section 7.1)
    if (ack.ecn && !result.acked_packets.empty())
    {
        // Find the earliest sent time among acked packets for congestion recovery tracking
        auto earliest_sent_time = result.acked_packets[0].sent_time;
        for (const auto& pkt : result.acked_packets)
        {
            if (pkt.sent_time < earliest_sent_time)
            {
                earliest_sent_time = pkt.sent_time;
            }
        }
        auto ecn_signal = ecn_tracker_.process_ecn_counts(
            *ack.ecn,
            result.acked_packets.size(),
            earliest_sent_time);
        result.ecn_signal = ecn_signal;
        if (ecn_signal == ecn_result::congestion_signal)
        {
            result.ecn_congestion_sent_time = ecn_tracker_.last_congestion_sent_time();
        }
    }
    set_loss_detection_timer();
    return result;
}
References kcenon::network::protocols::quic::ack, kcenon::network::protocols::quic::loss_detection_result::acked_packets, kcenon::network::protocols::quic::congestion_signal, kcenon::network::protocols::quic::loss_detection_result::ecn_congestion_sent_time, kcenon::network::protocols::quic::loss_detection_result::ecn_signal, kcenon::network::protocols::quic::loss_detection_result::event, kcenon::network::protocols::quic::loss_detection_result::lost_packets, and kcenon::network::protocols::quic::packet_lost.
on_packet_sent()
auto kcenon::network::protocols::quic::loss_detector::on_packet_sent (const sent_packet & packet) -> void
Record a sent packet.
Parameters
packet Information about the sent packet
Definition at line 70 of file loss_detector.cpp.
{
    auto idx = space_index(packet.level);
    auto& space = spaces_[idx];
    space.sent_packets[packet.packet_number] = packet;
    if (packet.in_flight)
    {
        space.bytes_in_flight += packet.sent_bytes;
    }
    if (packet.ack_eliciting)
    {
        space.time_of_last_ack_eliciting = packet.sent_time;
    }
    set_loss_detection_timer();
}
on_timeout()
auto kcenon::network::protocols::quic::loss_detector::on_timeout () -> loss_detection_result
Handle timeout expiry (RFC 9002 Section 6.2)
Returns
Loss detection result
Definition at line 333 of file loss_detector.cpp.
{
    loss_detection_result result;
    auto now = std::chrono::steady_clock::now();
    auto [loss_time, loss_level] = get_loss_time_and_space();
    if (loss_time != std::chrono::steady_clock::time_point{} && loss_time <= now)
    {
        // Time threshold loss detection
        auto lost = detect_lost_packets(loss_level, now);
        if (!lost.empty())
        {
            result.event = loss_detection_event::packet_lost;
            result.lost_packets = std::move(lost);
        }
    }
    else
    {
        // PTO timeout
        result.event = loss_detection_event::pto_expired;
        ++pto_count_;
    }
    set_loss_detection_timer();
    return result;
}
References kcenon::network::protocols::quic::loss_detection_result::event, and kcenon::network::protocols::quic::loss_detection_result::lost_packets.
Referenced by kcenon::network::protocols::quic::connection::on_timeout().
pto_count()
auto kcenon::network::protocols::quic::loss_detector::pto_count () const -> uint32_t inline noexcept
Get the current PTO count.
Returns
Number of times PTO has fired without receiving an ACK
Definition at line 169 of file loss_detector.h.
    {
        return pto_count_;
    }
References pto_count_.
reset_pto_count()
auto kcenon::network::protocols::quic::loss_detector::reset_pto_count () -> void inline noexcept
Reset PTO count to zero.
Definition at line 177 of file loss_detector.h.
    {
        pto_count_ = 0;
    }
References pto_count_.
set_handshake_confirmed()
auto kcenon::network::protocols::quic::loss_detector::set_handshake_confirmed (bool confirmed) -> void inline noexcept
Set handshake confirmed status.
Parameters
confirmed True if handshake is confirmed
Definition at line 212 of file loss_detector.h.
    {
        handshake_confirmed_ = confirmed;
    }
References handshake_confirmed_.
set_loss_detection_timer()
auto kcenon::network::protocols::quic::loss_detector::set_loss_detection_timer () -> void private
Set loss detection timer (RFC 9002 Section 6.2)
Definition at line 457 of file loss_detector.cpp.
{
    auto [loss_time, loss_level] = get_loss_time_and_space();
    if (loss_time != std::chrono::steady_clock::time_point{})
    {
        // Time threshold loss detection timer
        loss_detection_timer_ = loss_time;
        timer_armed_ = true;
        return;
    }
    // Check if there are any ack-eliciting packets in flight
    bool any_ack_eliciting = false;
    for (const auto& space : spaces_)
    {
        for (const auto& [pn, pkt] : space.sent_packets)
        {
            if (pkt.ack_eliciting)
            {
                any_ack_eliciting = true;
                break;
            }
        }
        if (any_ack_eliciting)
        {
            break;
        }
    }
    if (!any_ack_eliciting)
    {
        timer_armed_ = false;
        return;
    }
    auto [pto_time, pto_level] = get_pto_time_and_space();
    if (pto_time != std::chrono::steady_clock::time_point{})
    {
        loss_detection_timer_ = pto_time;
        timer_armed_ = true;
    }
    else
    {
        timer_armed_ = false;
    }
}
space_index()
auto kcenon::network::protocols::quic::loss_detector::space_index (encryption_level level) const -> size_t private noexcept
Get space index from encryption level.
Definition at line 52 of file loss_detector.cpp.
{
    // Map encryption levels to packet number spaces:
    // Initial -> 0, Handshake -> 1, Zero-RTT/Application -> 2
    switch (level)
    {
    case encryption_level::initial:
        return 0;
    case encryption_level::handshake:
        return 1;
    case encryption_level::zero_rtt:
    case encryption_level::application:
        return 2;
    default:
        return 2;
    }
}
References kcenon::network::protocols::quic::application, kcenon::network::protocols::quic::handshake, kcenon::network::protocols::quic::initial, and kcenon::network::protocols::quic::zero_rtt.
total_bytes_in_flight()
auto kcenon::network::protocols::quic::loss_detector::total_bytes_in_flight () const -> size_t
Get total bytes in flight across all spaces.
Returns
Total bytes in flight
Definition at line 523 of file loss_detector.cpp.
{
    size_t total = 0;
    for (const auto& space : spaces_)
    {
        total += space.bytes_in_flight;
    }
    return total;
}
Member Data Documentation
ecn_tracker_
class ecn_tracker kcenon::network::protocols::quic::loss_detector::ecn_tracker_ private
ECN tracker for ECN feedback processing.
Definition at line 284 of file loss_detector.h.
Referenced by get_ecn_tracker(), and get_ecn_tracker().
handshake_confirmed_
bool kcenon::network::protocols::quic::loss_detector::handshake_confirmed_ {false} private
True if the handshake is confirmed.
Definition at line 293 of file loss_detector.h.
{false};
Referenced by set_handshake_confirmed().
kGranularity
constexpr auto kcenon::network::protocols::quic::loss_detector::kGranularity = std::chrono::milliseconds{1} static constexpr private
Timer granularity (RFC 9002 Section 6.1.2)
Definition at line 308 of file loss_detector.h.
{1};
kPacketThreshold
constexpr uint32_t kcenon::network::protocols::quic::loss_detector::kPacketThreshold = 3 static constexpr private
Packet threshold (RFC 9002 Section 6.1.1)
Definition at line 302 of file loss_detector.h.
kTimeThreshold
constexpr double kcenon::network::protocols::quic::loss_detector::kTimeThreshold = 9.0 / 8.0 static constexpr private
Time threshold multiplier (RFC 9002 Section 6.1.2)
Definition at line 305 of file loss_detector.h.
loss_detection_timer_
std::chrono::steady_clock::time_point kcenon::network::protocols::quic::loss_detector::loss_detection_timer_ private
Scheduled loss detection timeout.
Definition at line 296 of file loss_detector.h.
pto_count_
uint32_t kcenon::network::protocols::quic::loss_detector::pto_count_ {0} private
Number of times PTO has expired without receiving an ACK.
Definition at line 290 of file loss_detector.h.
{0};
Referenced by pto_count(), and reset_pto_count().
rtt_
rtt_estimator& kcenon::network::protocols::quic::loss_detector::rtt_ private
Reference to RTT estimator.
Definition at line 281 of file loss_detector.h.
spaces_
std::array<space_state, 3> kcenon::network::protocols::quic::loss_detector::spaces_ private
Per packet-number-space state (Initial, Handshake, Application)
Definition at line 287 of file loss_detector.h.
timer_armed_
bool kcenon::network::protocols::quic::loss_detector::timer_armed_ {false} private
True if loss detection timer is armed.
Definition at line 299 of file loss_detector.h.
{false};
The documentation for this class was generated from the following files:
src/internal/protocols/quic/loss_detector.h
src/protocols/quic/loss_detector.cpp