Network System: kcenon::network::integration::basic_logger Class Reference
kcenon::network::integration::basic_logger Class Reference
Basic console logger implementation for standalone use.
#include <logger_integration.h>
Classes
class impl
Public Member Functions
basic_logger (log_level min_level=log_level::info)
Constructor with minimum log level.
~basic_logger () override
void log (log_level level, const std::string &message) override
Log a message with specified level.
void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function) override
Log a message with source location information.
bool is_level_enabled (log_level level) const override
Check if a log level is enabled.
void flush () override
Flush any buffered log messages.
void set_min_level (log_level level)
Set minimum log level.
log_level get_min_level () const
Get current minimum log level.
Public Member Functions inherited from kcenon::network::integration::logger_interface
virtual ~logger_interface ()=default
virtual ~logger_interface ()=default
virtual void info (std::string_view message)=0
Log an informational message.
virtual void warning (std::string_view message)=0
Log a warning message.
virtual void error (std::string_view message)=0
Log an error message.
virtual void debug (std::string_view message)=0
Log a debug message.
Private Attributes
std::unique_ptr< impl > pimpl_
Detailed Description
Basic console logger implementation for standalone use.
This provides a simple logger implementation for when common_system or logger_system is not available.
Definition at line 151 of file logger_integration.h.
Constructor & Destructor Documentation
basic_logger()
kcenon::network::integration::basic_logger::basic_logger (log_level min_level = log_level::info) explicit
Constructor with minimum log level.
Parameters
min_level Minimum level to log (default: info)
Definition at line 191 of file logger_integration.cpp.
    : pimpl_(std::make_unique<impl>(min_level)) {}
~basic_logger()
kcenon::network::integration::basic_logger::~basic_logger () override default
Member Function Documentation
flush()
void kcenon::network::integration::basic_logger::flush () override virtual
Flush any buffered log messages.
Implements kcenon::network::integration::logger_interface.
Definition at line 209 of file logger_integration.cpp.
{
    pimpl_->flush();
}
References kcenon::network::integration::basic_logger::impl::flush(), and pimpl_.
get_min_level()
log_level kcenon::network::integration::basic_logger::get_min_level () const
Get current minimum log level.
Returns
Current minimum level
Definition at line 217 of file logger_integration.cpp.
{
    return pimpl_->get_min_level();
}
References kcenon::network::integration::basic_logger::impl::get_min_level(), and pimpl_.
is_level_enabled()
bool kcenon::network::integration::basic_logger::is_level_enabled (log_level level) const override virtual
Check if a log level is enabled.
Parameters
level Log level to check
Returns
true if the level is enabled
Implements kcenon::network::integration::logger_interface.
Definition at line 205 of file logger_integration.cpp.
{
    return pimpl_->is_level_enabled(level);
}
References kcenon::network::integration::basic_logger::impl::is_level_enabled(), and pimpl_.
log() [1/2]
void kcenon::network::integration::basic_logger::log (log_level level, const std::string & message) override virtual
Log a message with specified level.
Parameters
level Log severity level
message Message to log
Implements kcenon::network::integration::logger_interface.
Definition at line 196 of file logger_integration.cpp.
{
    pimpl_->log(level, message);
}
References kcenon::network::integration::basic_logger::impl::log(), kcenon::network::message, and pimpl_.
log() [2/2]
void kcenon::network::integration::basic_logger::log (log_level level, const std::string & message, const std::string & file, int line, const std::string & function) override virtual
Log a message with source location information.
Parameters
level Log severity level
message Message to log
file Source file name
line Line number
function Function name
Implements kcenon::network::integration::logger_interface.
Definition at line 200 of file logger_integration.cpp.
{
    pimpl_->log(level, message, file, line, function);
}
References kcenon::network::integration::basic_logger::impl::log(), kcenon::network::message, and pimpl_.
set_min_level()
void kcenon::network::integration::basic_logger::set_min_level (log_level level)
Set minimum log level.
Parameters
level New minimum level
Definition at line 213 of file logger_integration.cpp.
{
    pimpl_->set_min_level(level);
}
References pimpl_, and kcenon::network::integration::basic_logger::impl::set_min_level().
Member Data Documentation
pimpl_
std::unique_ptr<impl> kcenon::network::integration::basic_logger::pimpl_ private
Definition at line 183 of file logger_integration.h.
Referenced by flush(), get_min_level(), is_level_enabled(), log(), log(), and set_min_level().
The documentation for this class was generated from the following files:
src/internal/integration/logger_integration.h
src/integration/logger_integration.cpp