Network System: kcenon::network::protocols::http2::dynamic_table Class Reference
kcenon::network::protocols::http2::dynamic_table Class Reference
HPACK dynamic table for header compression.
#include <hpack.h>
Public Member Functions
dynamic_table (size_t max_size=4096)
Construct dynamic table with max size.
auto insert (std::string_view name, std::string_view value) -> void
Insert header at beginning of table.
auto get (size_t index) const -> std::optional< http_header >
Get header by dynamic table index.
auto find (std::string_view name, std::string_view value="") const -> std::optional< size_t >
Find header in dynamic table.
auto set_max_size (size_t size) -> void
Set maximum table size.
auto current_size () const -> size_t
Get current table size.
auto max_size () const -> size_t
Get maximum table size.
auto entry_count () const -> size_t
Get number of entries.
auto clear () -> void
Clear all entries.
Private Member Functions
auto evict_to_size (size_t target_size) -> void
Private Attributes
std::deque< http_header > entries_
size_t current_size_ = 0
size_t max_size_
Detailed Description
HPACK dynamic table for header compression.
The dynamic table maintains recently used headers for compression. Entries are added at the beginning and evicted from the end when the table exceeds max_size.
Definition at line 111 of file hpack.h.
Constructor & Destructor Documentation
dynamic_table()
kcenon::network::protocols::http2::dynamic_table::dynamic_table (size_t max_size = 4096) explicit
Construct dynamic table with max size.
Parameters
max_size Maximum table size in bytes (default 4096)
Definition at line 138 of file hpack.cpp.
        : max_size_(max_size)
    {
    }
Member Function Documentation
clear()
auto kcenon::network::protocols::http2::dynamic_table::clear () -> void
Clear all entries.
Definition at line 203 of file hpack.cpp.
    {
        entries_.clear();
        current_size_ = 0;
    }
current_size()
auto kcenon::network::protocols::http2::dynamic_table::current_size () const -> size_t
Get current table size.
Returns
Current size in bytes
Definition at line 188 of file hpack.cpp.
    {
        return current_size_;
    }
References current_size_.
Referenced by kcenon::network::protocols::http2::hpack_encoder::table_size(), and kcenon::network::protocols::http2::hpack_decoder::table_size().
entry_count()
auto kcenon::network::protocols::http2::dynamic_table::entry_count () const -> size_t
Get number of entries.
Returns
Entry count
Definition at line 198 of file hpack.cpp.
    {
        return entries_.size();
    }
References entries_.
evict_to_size()
auto kcenon::network::protocols::http2::dynamic_table::evict_to_size (size_t target_size) -> void private
Definition at line 209 of file hpack.cpp.
    {
        while (current_size_ > target_size && !entries_.empty())
        {
            current_size_ -= entries_.back().size();
            entries_.pop_back();
        }
    }
find()
auto kcenon::network::protocols::http2::dynamic_table::find (std::string_view name, std::string_view value = "") const -> std::optional<size_t>
Find header in dynamic table.
Parameters
name Header name
value Header value (empty to match name only)
Returns
Dynamic table index if found, or empty
Definition at line 165 of file hpack.cpp.
    {
        for (size_t i = 0; i < entries_.size(); ++i)
        {
            const auto& entry = entries_[i];
            if (entry.name == name)
            {
                if (value.empty() || entry.value == value)
                {
                    return i;
                }
            }
        }
        return std::nullopt;
    }
get()
auto kcenon::network::protocols::http2::dynamic_table::get (size_t index) const -> std::optional<http_header>
Get header by dynamic table index.
Parameters
index Dynamic table index (0-based)
Returns
Header if found
Definition at line 156 of file hpack.cpp.
    {
        if (index >= entries_.size())
        {
            return std::nullopt;
        }
        return entries_[index];
    }
insert()
auto kcenon::network::protocols::http2::dynamic_table::insert (std::string_view name, std::string_view value) -> void
Insert header at beginning of table.
Parameters
name Header name
value Header value
Definition at line 143 of file hpack.cpp.
    {
        http_header header{std::string(name), std::string(value)};
        size_t entry_size = header.size();
        // Evict entries if needed
        evict_to_size(max_size_ - entry_size);
        // Insert at beginning
        entries_.push_front(std::move(header));
        current_size_ += entry_size;
    }
References kcenon::network::protocols::http2::http_header::size().
max_size()
auto kcenon::network::protocols::http2::dynamic_table::max_size () const -> size_t
Get maximum table size.
Returns
Maximum size in bytes
Definition at line 193 of file hpack.cpp.
    {
        return max_size_;
    }
References max_size_.
set_max_size()
auto kcenon::network::protocols::http2::dynamic_table::set_max_size (size_t size) -> void
Set maximum table size.
Parameters
size New maximum size in bytes
Definition at line 182 of file hpack.cpp.
    {
        max_size_ = size;
        evict_to_size(max_size_);
    }
Member Data Documentation
current_size_
size_t kcenon::network::protocols::http2::dynamic_table::current_size_ = 0 private
Definition at line 176 of file hpack.h.
Referenced by current_size().
entries_
std::deque<http_header> kcenon::network::protocols::http2::dynamic_table::entries_ private
Definition at line 175 of file hpack.h.
Referenced by entry_count().
max_size_
size_t kcenon::network::protocols::http2::dynamic_table::max_size_ private
Definition at line 177 of file hpack.h.
Referenced by max_size().
The documentation for this class was generated from the following files:
src/internal/protocols/http2/hpack.h
src/protocols/http2/hpack.cpp