Network System: kcenon::network::internal::http_error_response Class Reference
kcenon::network::internal::http_error_response Class Reference
Builder for HTTP error responses.
#include <http_error.h>
Static Public Member Functions
static auto build_json_error (const http_error &error) -> http_response
Build JSON format error response (RFC 7807)
static auto build_html_error (const http_error &error) -> http_response
Build HTML format error response.
static auto make_error (http_error_code code, const std::string &detail="", const std::string &request_id="") -> http_error
Create http_error from error code.
Detailed Description
Builder for HTTP error responses.
Supports building error responses in JSON and HTML formats. Follows RFC 7807 (Problem Details for HTTP APIs) for JSON format.
Definition at line 180 of file http_error.h.
Member Function Documentation
build_html_error()
auto kcenon::network::internal::http_error_response::build_html_error (const http_error & error) -> http_response static
Build HTML format error response.
Parameters
error Error details
Returns
HTTP response with HTML body
Definition at line 221 of file http_error.cpp.
{
    http_response response;
    response.status_code = error.status_code();
    response.status_message = std::string(get_error_status_text(error.code));
    std::ostringstream html;
    html << "<!DOCTYPE html>\n";
    html << "<html lang=\"en\">\n";
    html << "<head>\n";
    html << "  <meta charset=\"utf-8\">\n";
    html << "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
    html << "  <title>" << response.status_code << " " << escape_html_string(response.status_message)
         << "</title>\n";
    html << "  <style>\n";
    html << "    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; "
         << "margin: 40px auto; max-width: 650px; line-height: 1.6; color: #333; padding: 0 10px; }\n";
    html << "    h1 { color: #c00; border-bottom: 2px solid #eee; padding-bottom: 10px; }\n";
    html << "    .detail { background: #f9f9f9; padding: 15px; border-radius: 5px; }\n";
    html << "    .meta { color: #666; font-size: 0.9em; margin-top: 20px; }\n";
    html << "  </style>\n";
    html << "</head>\n";
    html << "<body>\n";
    html << "  <h1>" << response.status_code << " " << escape_html_string(response.status_message)
         << "</h1>\n";
    if (!error.message.empty())
    {
        html << "  <p>" << escape_html_string(error.message) << "</p>\n";
    }
    if (!error.detail.empty())
    {
        html << "  <div class=\"detail\">\n";
        html << "    <strong>Details:</strong> " << escape_html_string(error.detail) << "\n";
        html << "  </div>\n";
    }
    html << "  <div class=\"meta\">\n";
    if (!error.request_id.empty())
    {
        html << "    <p>Request ID: " << escape_html_string(error.request_id) << "</p>\n";
    }
    html << "    <p><em>NetworkSystem HTTP Server</em></p>\n";
    html << "  </div>\n";
    html << "</body>\n";
    html << "</html>\n";
    response.set_body_string(html.str());
    response.set_header("Content-Type", "text/html; charset=utf-8");
    return response;
}
References kcenon::network::protocols::quic::error, kcenon::network::internal::escape_html_string(), kcenon::network::internal::get_error_status_text(), kcenon::network::internal::http_response::set_body_string(), kcenon::network::internal::http_response::set_header(), kcenon::network::internal::http_response::status_code, and kcenon::network::internal::http_response::status_message.
Referenced by kcenon::network::core::http_server::build_error_response().
build_json_error()
auto kcenon::network::internal::http_error_response::build_json_error (const http_error & error) -> http_response static
Build JSON format error response (RFC 7807)
Parameters
error Error details
Returns
HTTP response with JSON body
Definition at line 181 of file http_error.cpp.
{
    http_response response;
    response.status_code = error.status_code();
    response.status_message = std::string(get_error_status_text(error.code));
    // Build RFC 7807 compliant JSON response
    std::ostringstream json;
    json << "{\n";
    json << "  \"type\": \"about:blank\",\n";
    json << "  \"title\": \"" << escape_json_string(response.status_message) << "\",\n";
    json << "  \"status\": " << response.status_code << ",\n";
    json << "  \"detail\": \"" << escape_json_string(error.detail.empty() ? error.message : error.detail)
         << "\"";
    if (!error.request_id.empty())
    {
        json << ",\n  \"instance\": \"" << escape_json_string(error.request_id) << "\"";
    }
    // Add timestamp
    auto time_t_val = std::chrono::system_clock::to_time_t(error.timestamp);
    std::tm tm_val{};
#ifdef _WIN32
    gmtime_s(&tm_val, &time_t_val);
#else
    gmtime_r(&time_t_val, &tm_val);
#endif
    char time_buf[32];
    std::strftime(time_buf, sizeof(time_buf), "%Y-%m-%dT%H:%M:%SZ", &tm_val);
    json << ",\n  \"timestamp\": \"" << time_buf << "\"";
    json << "\n}\n";
    response.set_body_string(json.str());
    response.set_header("Content-Type", "application/problem+json; charset=utf-8");
    return response;
}
References kcenon::network::protocols::quic::error, kcenon::network::internal::escape_json_string(), kcenon::network::internal::get_error_status_text(), kcenon::network::internal::http_response::set_body_string(), kcenon::network::internal::http_response::set_header(), kcenon::network::internal::http_response::status_code, and kcenon::network::internal::http_response::status_message.
Referenced by kcenon::network::core::http_server::build_error_response().
make_error()
auto kcenon::network::internal::http_error_response::make_error (http_error_code code, const std::string & detail = "", const std::string & request_id = "") -> http_error static
Create http_error from error code.
Parameters
code HTTP error code
detail Optional detailed message
request_id Optional request ID
Returns
Constructed http_error
Definition at line 275 of file http_error.cpp.
{
    http_error error;
    error.code = code;
    error.message = std::string(get_error_status_text(code));
    error.detail = detail;
    error.request_id = request_id;
    error.timestamp = std::chrono::system_clock::now();
    return error;
}
References kcenon::network::internal::http_error::code, kcenon::network::protocols::quic::error, and kcenon::network::internal::get_error_status_text().
Referenced by kcenon::network::core::http_server::create_error_response().
The documentation for this class was generated from the following files:
src/internal/http/http_error.h
src/internal/http_error.cpp