Network System: kcenon::network::core::messaging_udp_server Class Reference
kcenon::network::core::messaging_udp_server Class Reference export
module kcenon.network
A UDP server that receives datagrams and routes them based on sender endpoint.
#include <messaging_udp_server.h>
Public Types
using receive_callback_t
Callback type for received datagrams with sender endpoint.
using error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
using udp_data_callback
Callback type for UDP data reception.
Public Types inherited from kcenon::network::interfaces::i_udp_server
using endpoint_info = i_udp_client::endpoint_info
Reuse endpoint_info from i_udp_client.
using receive_callback_t
Callback type for received data (includes sender endpoint)
using error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
using send_callback_t = std::function<void(std::error_code, std::size_t)>
Callback type for send completion.
Public Member Functions
messaging_udp_server (std::string_view server_id)
Constructs a messaging_udp_server with an identifier.
~messaging_udp_server () noexcept override
Destructor. If the server is still running, stop_server() is invoked.
messaging_udp_server (const messaging_udp_server &)=delete
messaging_udp_server & operator= (const messaging_udp_server &)=delete
messaging_udp_server (messaging_udp_server &&)=delete
messaging_udp_server & operator= (messaging_udp_server &&)=delete
auto start_server (uint16_t port) -> VoidResult
Starts the server on the specified port.
auto stop_server () -> VoidResult
Stops the server and releases all resources.
auto server_id () const -> const std::string &
Returns the server identifier.
auto is_running () const -> bool override
Checks if the server is currently running.
auto wait_for_stop () -> void override
Blocks until stop_server() is called.
auto start (uint16_t port) -> VoidResult override
Starts the UDP server on the specified port.
auto stop () -> VoidResult override
Stops the UDP server.
auto send_to (const interfaces::i_udp_server::endpoint_info &endpoint, std::vector< uint8_t > &&data, interfaces::i_udp_server::send_callback_t handler=nullptr) -> VoidResult override
Sends a datagram to the specified endpoint.
auto set_receive_callback (interfaces::i_udp_server::receive_callback_t callback) -> void override
Sets the callback for received datagrams (interface version).
auto set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received datagrams (legacy version).
auto set_error_callback (error_callback_t callback) -> void override
Sets the callback for errors.
messaging_udp_server (std::string_view server_id)
Construct a UDP server with a given server_id.
virtual ~messaging_udp_server () noexcept
Destructor - automatically stops the server if running.
messaging_udp_server (const messaging_udp_server &)=delete
messaging_udp_server & operator= (const messaging_udp_server &)=delete
messaging_udp_server (messaging_udp_server &&) noexcept
messaging_udp_server & operator= (messaging_udp_server &&) noexcept
bool start_server (uint16_t port)
Start the server on a specified port.
bool start_server (std::string_view address, uint16_t port)
Start the server on a specific interface.
void stop_server ()
Stop the server.
bool send_to (std::span< const uint8_t > data, std::string_view host, uint16_t port)
Send a datagram to a specific endpoint.
bool send_to (std::string_view data, std::string_view host, uint16_t port)
Send a string datagram to a specific endpoint.
bool broadcast (std::span< const uint8_t > data, uint16_t port)
Broadcast data to all endpoints on the network.
bool is_running () const noexcept
Check if the server is running.
std::string_view server_id () const noexcept
Get the server identifier.
void set_data_callback (udp_data_callback callback)
Set data received callback.
void set_error_callback (error_callback callback)
Set error callback.
bool join_multicast_group (std::string_view multicast_address)
Enable multicast reception.
Public Member Functions inherited from kcenon::network::interfaces::i_udp_server
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Types
using callback_index = udp_server_callback
Callback index type alias for clarity.
using callbacks_t
Callback manager type for this server.
Private Member Functions
auto do_start_impl (uint16_t port) -> VoidResult
UDP-specific implementation of server start.
auto do_stop_impl () -> VoidResult
UDP-specific implementation of server stop.
auto invoke_receive_callback (const std::vector< uint8_t > &data, const asio::ip::udp::endpoint &endpoint) -> void
Invokes the receive callback with the given data and endpoint.
auto invoke_error_callback (std::error_code ec) -> void
Invokes the error callback with the given error code.
auto get_receive_callback () const -> receive_callback_t
Gets a copy of the receive callback.
auto get_error_callback () const -> error_callback_t
Gets a copy of the error callback.
Private Attributes
std::string server_id_
utils::lifecycle_manager lifecycle_
callbacks_t callbacks_
std::unique_ptr< asio::io_context > io_context_
std::shared_ptr< internal::udp_socket > socket_
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::future< void > io_context_future_
std::unique_ptr< impl > pimpl_
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
A UDP server that receives datagrams and routes them based on sender endpoint.
A UDP server for handling datagrams from multiple endpoints.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling. It also implements the i_udp_server interface for composition-based usage.
Thread Safety
All public methods are thread-safe.
Internal state is protected by atomics and mutex.
Background thread runs io_context.run() independently.
Callbacks are invoked on ASIO worker thread.
Key Characteristics
Connectionless: No persistent sessions, each datagram is independent.
Endpoint-based routing: Each received datagram includes sender endpoint.
No session management: Unlike TCP server, UDP server doesn't maintain sessions.
Stateless: Application layer must handle state if needed.
Interface Compliance
This class implements interfaces::i_udp_server for composition-based usage.
Usage Example
auto server = std::make_shared<messaging_udp_server>("UDPServer");
// Set callback to handle received datagrams (using interface callback)
server->set_receive_callback(
    [server](const std::vector<uint8_t>& data,
             const interfaces::i_udp_server::endpoint_info& sender) {
        std::cout << "Received " << data.size() << " bytes from "
                  << sender.address << ":" << sender.port << "\n";
        // Send response using send_to()
        std::vector<uint8_t> response = {0x01, 0x02, 0x03};
        server->send_to(sender, std::move(response),
            [](std::error_code ec, std::size_t bytes) {
                if (!ec) {
                    std::cout << "Sent " << bytes << " bytes\n";
                }
            });
    });
// Start server on port 5555
auto result = server->start_server(5555);
if (!result) {
    std::cerr << "Failed to start server: " << result.error().message << "\n";
    return -1;
}
// Stop server
server->stop_server();
This class provides a UDP server that listens for incoming datagrams and can respond to multiple remote endpoints.
Thread Safety
All public methods are thread-safe.
Key Features
Multiple endpoint support
Multicast support
Broadcast support
import kcenon.network;
auto server = std::make_unique<kcenon::network::core::messaging_udp_server>("udp_server");
server->set_data_callback([&server](std::span<const uint8_t> data,
                                      const std::string& from_addr,
                                      uint16_t from_port) {
    // Echo back
    server->send_to(data, from_addr, from_port);
});
server->start_server(8080);
Definition at line 219 of file udp.cppm.
Member Typedef Documentation
callback_index
using kcenon::network::core::messaging_udp_server::callback_index = udp_server_callback private
Callback index type alias for clarity.
Definition at line 281 of file messaging_udp_server.h.
callbacks_t
using kcenon::network::core::messaging_udp_server::callbacks_t private
Initial value:
 utils::callback_manager<
            receive_callback_t,
            error_callback_t
        >
Callback manager type for this server.
Definition at line 284 of file messaging_udp_server.h.
error_callback_t
using kcenon::network::core::messaging_udp_server::error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Definition at line 102 of file messaging_udp_server.h.
receive_callback_t
using kcenon::network::core::messaging_udp_server::receive_callback_t
Initial value:
 std::function<void(const std::vector<uint8_t>&,
                                                      const asio::ip::udp::endpoint&)>
Callback type for received datagrams with sender endpoint.
Definition at line 99 of file messaging_udp_server.h.
udp_data_callback
using kcenon::network::core::messaging_udp_server::udp_data_callback export
Initial value:
 std::function<void(
        std::span<const uint8_t> data,
        const std::string& from_address,
        uint16_t from_port)>
Callback type for UDP data reception.
Definition at line 224 of file udp.cppm.
Constructor & Destructor Documentation
messaging_udp_server() [1/6]
kcenon::network::core::messaging_udp_server::messaging_udp_server (std::string_view server_id) explicit
Constructs a messaging_udp_server with an identifier.
Parameters
server_id A descriptive identifier for this server instance.
Definition at line 14 of file messaging_udp_server.cpp.
        : server_id_(server_id)
    {
    }
~messaging_udp_server() [1/2]
kcenon::network::core::messaging_udp_server::~messaging_udp_server () override noexcept
Destructor. If the server is still running, stop_server() is invoked.
Definition at line 19 of file messaging_udp_server.cpp.
    {
        if (lifecycle_.is_running())
        {
            (void)stop_server();
        }
    }
References kcenon::network::utils::lifecycle_manager::is_running(), lifecycle_, and stop_server().
messaging_udp_server() [2/6]
kcenon::network::core::messaging_udp_server::messaging_udp_server (const messaging_udp_server &) delete
messaging_udp_server() [3/6]
kcenon::network::core::messaging_udp_server::messaging_udp_server (messaging_udp_server &&) delete
messaging_udp_server() [4/6]
kcenon::network::core::messaging_udp_server::messaging_udp_server (std::string_view server_id) explicit export
Construct a UDP server with a given server_id.
Parameters
server_id A string identifier for this server instance
~messaging_udp_server() [2/2]
virtual kcenon::network::core::messaging_udp_server::~messaging_udp_server () export virtual noexcept
Destructor - automatically stops the server if running.
messaging_udp_server() [5/6]
kcenon::network::core::messaging_udp_server::messaging_udp_server (const messaging_udp_server &) export delete
messaging_udp_server() [6/6]
kcenon::network::core::messaging_udp_server::messaging_udp_server (messaging_udp_server &&) export noexcept
Member Function Documentation
broadcast()
bool kcenon::network::core::messaging_udp_server::broadcast (std::span< const uint8_t > data, uint16_t port) export
Broadcast data to all endpoints on the network.
Parameters
data The data to broadcast
port The target port number
Returns
true if data was sent
do_start_impl()
auto kcenon::network::core::messaging_udp_server::do_start_impl (uint16_t port) -> VoidResult private
UDP-specific implementation of server start.
Parameters
port The UDP port to bind and listen on.
Returns
Result<void> - Success if server started, or error with code.
Creates io_context, binds socket, and starts worker thread.
Definition at line 185 of file messaging_udp_server.cpp.
    {
        try
        {
            // Create io_context
            io_context_ = std::make_unique<asio::io_context>();
            // Create and bind UDP socket
            asio::ip::udp::socket raw_socket(*io_context_, udp::endpoint(udp::v4(), port));
            // Wrap in our udp_socket
            socket_ = std::make_shared<internal::udp_socket>(std::move(raw_socket));
            // Set callbacks to socket
            auto receive_cb = get_receive_callback();
            if (receive_cb)
            {
                socket_->set_receive_callback(std::move(receive_cb));
            }
            auto error_cb = get_error_callback();
            if (error_cb)
            {
                socket_->set_error_callback(std::move(error_cb));
            }
            // Start receiving
            socket_->start_receive();
            // Get thread pool from network context
            thread_pool_ = network_context::instance().get_thread_pool();
            if (!thread_pool_) {
                // Fallback: create a temporary thread pool if network_context is not initialized
                NETWORK_LOG_WARN("[messaging_udp_server] network_context not initialized, creating temporary thread pool");
                thread_pool_ = std::make_shared<integration::basic_thread_pool>(std::thread::hardware_concurrency());
            }
            // Start io_context on thread pool
            io_context_future_ = thread_pool_->submit(
                [this]()
                {
                    try
                    {
                        NETWORK_LOG_DEBUG("[messaging_udp_server] io_context started");
                        io_context_->run();
                        NETWORK_LOG_DEBUG("[messaging_udp_server] io_context stopped");
                    }
                    catch (const std::exception& e)
                    {
                        NETWORK_LOG_ERROR(std::string("Worker thread exception: ") + e.what());
                    }
                });
            NETWORK_LOG_INFO("UDP server started on port " + std::to_string(port));
            return ok();
        }
        catch (const std::system_error& e)
        {
            return error_void(
                error_codes::network_system::bind_failed,
                std::string("Failed to bind UDP socket: ") + e.what(),
                "messaging_udp_server::do_start_impl",
                "Port: " + std::to_string(port)
            );
        }
        catch (const std::exception& e)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                std::string("Failed to start UDP server: ") + e.what(),
                "messaging_udp_server::do_start_impl",
                "Port: " + std::to_string(port)
            );
        }
    }
References kcenon::network::error_codes::network_system::bind_failed, kcenon::network::error_void(), kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_DEBUG, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, NETWORK_LOG_WARN, kcenon::network::ok(), and kcenon::network::integration::thread_pool_interface::submit().
do_stop_impl()
auto kcenon::network::core::messaging_udp_server::do_stop_impl () -> VoidResult private
UDP-specific implementation of server stop.
Returns
Result<void> - Success if server stopped, or error with code.
Stops receiving, closes socket, and releases resources.
Definition at line 262 of file messaging_udp_server.cpp.
    {
        try
        {
            // Stop receiving
            if (socket_)
            {
                socket_->stop_receive();
            }
            // Stop io_context
            if (io_context_)
            {
                io_context_->stop();
            }
            // Join worker thread
            if (io_context_future_.valid())
            {
                try {
                    io_context_future_.wait();
                } catch (const std::exception& e) {
                    NETWORK_LOG_ERROR("[messaging_udp_server] Exception while waiting for io_context: " +
                                      std::string(e.what()));
                }
            }
            // Clean up
            socket_.reset();
            io_context_.reset();
            NETWORK_LOG_INFO("UDP server stopped");
            return ok();
        }
        catch (const std::exception& e)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                std::string("Failed to stop UDP server: ") + e.what(),
                "messaging_udp_server::do_stop_impl",
                ""
            );
        }
    }
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_ERROR, NETWORK_LOG_INFO, and kcenon::network::ok().
get_error_callback()
auto kcenon::network::core::messaging_udp_server::get_error_callback () const -> error_callback_t nodiscard private
Gets a copy of the error callback.
Returns
Copy of the error callback (may be empty).
Definition at line 329 of file messaging_udp_server.cpp.
    {
        return callbacks_.get<to_index(callback_index::error)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
get_receive_callback()
auto kcenon::network::core::messaging_udp_server::get_receive_callback () const -> receive_callback_t nodiscard private
Gets a copy of the receive callback.
Returns
Copy of the receive callback (may be empty).
Definition at line 324 of file messaging_udp_server.cpp.
    {
        return callbacks_.get<to_index(callback_index::receive)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
invoke_error_callback()
auto kcenon::network::core::messaging_udp_server::invoke_error_callback (std::error_code ec) -> void private
Invokes the error callback with the given error code.
Parameters
ec The error code.
Definition at line 319 of file messaging_udp_server.cpp.
    {
        callbacks_.invoke<to_index(callback_index::error)>(ec);
    }
References kcenon::network::to_index().
invoke_receive_callback()
auto kcenon::network::core::messaging_udp_server::invoke_receive_callback (const std::vector< uint8_t > & data, const asio::ip::udp::endpoint & endpoint) -> void private
Invokes the receive callback with the given data and endpoint.
Parameters
data The received data.
endpoint The sender's endpoint.
Definition at line 312 of file messaging_udp_server.cpp.
    {
        callbacks_.invoke<to_index(callback_index::receive)>(data, endpoint);
    }
References kcenon::network::to_index().
is_running() [1/2]
auto kcenon::network::core::messaging_udp_server::is_running () const -> bool nodiscard override virtual
Checks if the server is currently running.
Returns
true if running, false otherwise.
Implements i_network_component::is_running().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 76 of file messaging_udp_server.cpp.
    {
        return lifecycle_.is_running();
    }
References kcenon::network::utils::lifecycle_manager::is_running(), and lifecycle_.
is_running() [2/2]
bool kcenon::network::core::messaging_udp_server::is_running () const export virtual noexcept
Check if the server is running.
Returns
true if running, false otherwise
Implements kcenon::network::interfaces::i_network_component.
join_multicast_group()
bool kcenon::network::core::messaging_udp_server::join_multicast_group (std::string_view multicast_address) export
Enable multicast reception.
Parameters
multicast_address The multicast group address
Returns
true if joined successfully
operator=() [1/4]
messaging_udp_server & kcenon::network::core::messaging_udp_server::operator= (const messaging_udp_server &) delete
operator=() [2/4]
messaging_udp_server & kcenon::network::core::messaging_udp_server::operator= (const messaging_udp_server &) export delete
operator=() [3/4]
messaging_udp_server & kcenon::network::core::messaging_udp_server::operator= (messaging_udp_server &&) export noexcept
operator=() [4/4]
messaging_udp_server & kcenon::network::core::messaging_udp_server::operator= (messaging_udp_server &&) delete
send_to() [1/3]
auto kcenon::network::core::messaging_udp_server::send_to (const interfaces::i_udp_server::endpoint_info & endpoint, std::vector< uint8_t > && data, interfaces::i_udp_server::send_callback_t handler = nullptr) -> VoidResult nodiscard override virtual
Sends a datagram to the specified endpoint.
Parameters
endpoint The target endpoint.
data The data to send.
handler Optional completion handler.
Returns
VoidResult indicating success or failure.
Implements i_udp_server::send_to().
Implements kcenon::network::interfaces::i_udp_server.
Definition at line 100 of file messaging_udp_server.cpp.
    {
        if (!lifecycle_.is_running())
        {
            return error_void(
                error_codes::network_system::server_not_started,
                "UDP server is not running",
                "messaging_udp_server::send_to",
                ""
            );
        }
        if (!socket_)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                "Socket not available",
                "messaging_udp_server::send_to",
                ""
            );
        }
        try
        {
            // Convert endpoint_info to asio::ip::udp::endpoint
            asio::ip::udp::endpoint asio_endpoint(
                asio::ip::make_address(endpoint.address),
                endpoint.port
            );
            socket_->async_send_to(std::move(data), asio_endpoint, std::move(handler));
            return ok();
        }
        catch (const std::exception& e)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                std::string("Failed to send datagram: ") + e.what(),
                "messaging_udp_server::send_to",
                "Target: " + endpoint.address + ":" + std::to_string(endpoint.port)
            );
        }
    }
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, kcenon::network::ok(), and kcenon::network::error_codes::network_system::server_not_started.
send_to() [2/3]
bool kcenon::network::core::messaging_udp_server::send_to (std::span< const uint8_t > data, std::string_view host, uint16_t port) export
Send a datagram to a specific endpoint.
Parameters
data The data to send
host The target host address
port The target port number
Returns
true if data was sent
send_to() [3/3]
bool kcenon::network::core::messaging_udp_server::send_to (std::string_view data, std::string_view host, uint16_t port) export
Send a string datagram to a specific endpoint.
Parameters
data The string data to send
host The target host address
port The target port number
Returns
true if data was sent
server_id() [1/2]
auto kcenon::network::core::messaging_udp_server::server_id () const -> const std::string& nodiscard
Returns the server identifier.
Returns
The server_id string.
Definition at line 67 of file messaging_udp_server.cpp.
    {
        return server_id_;
    }
References server_id_.
server_id() [2/2]
std::string_view kcenon::network::core::messaging_udp_server::server_id () const export noexcept
Get the server identifier.
Returns
Server ID string
set_data_callback()
void kcenon::network::core::messaging_udp_server::set_data_callback (udp_data_callback callback) export
Set data received callback.
Parameters
callback Function to call when data is received
set_error_callback() [1/2]
void kcenon::network::core::messaging_udp_server::set_error_callback (error_callback callback) export
Set error callback.
Parameters
callback Function to call on errors
set_error_callback() [2/2]
auto kcenon::network::core::messaging_udp_server::set_error_callback (error_callback_t callback) -> void override virtual
Sets the callback for errors.
Parameters
callback The callback function.
Implements i_udp_server::set_error_callback(). Also compatible with legacy error_callback_t (same signature).
Implements kcenon::network::interfaces::i_udp_server.
Definition at line 176 of file messaging_udp_server.cpp.
    {
        callbacks_.set<to_index(callback_index::error)>(std::move(callback));
    }
References kcenon::network::to_index().
set_receive_callback() [1/2]
auto kcenon::network::core::messaging_udp_server::set_receive_callback (interfaces::i_udp_server::receive_callback_t callback) -> void override virtual
Sets the callback for received datagrams (interface version).
Parameters
callback The callback function with endpoint_info.
Implements i_udp_server::set_receive_callback().
Implements kcenon::network::interfaces::i_udp_server.
Definition at line 147 of file messaging_udp_server.cpp.
    {
        if (!callback)
        {
            // Clear the callback
            callbacks_.set<to_index(callback_index::receive)>(nullptr);
            return;
        }
        // Adapt the interface callback to the internal callback type
        // Convert asio::ip::udp::endpoint to endpoint_info
        callbacks_.set<to_index(callback_index::receive)>(
            [callback = std::move(callback)](
                const std::vector<uint8_t>& data,
                const asio::ip::udp::endpoint& endpoint)
            {
                interfaces::i_udp_server::endpoint_info info;
                info.address = endpoint.address().to_string();
                info.port = endpoint.port();
                callback(data, info);
            });
    }
References kcenon::network::to_index().
set_receive_callback() [2/2]
auto kcenon::network::core::messaging_udp_server::set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received datagrams (legacy version).
Parameters
callback The callback function with asio endpoint.
This overload maintains backward compatibility with code using asio::ip::udp::endpoint directly.
Definition at line 171 of file messaging_udp_server.cpp.
    {
        callbacks_.set<to_index(callback_index::receive)>(std::move(callback));
    }
References kcenon::network::to_index().
start()
auto kcenon::network::core::messaging_udp_server::start (uint16_t port) -> VoidResult nodiscard override virtual
Starts the UDP server on the specified port.
Parameters
port The port number to bind to.
Returns
VoidResult indicating success or failure.
Implements i_udp_server::start(). Delegates to start_server().
Implements kcenon::network::interfaces::i_udp_server.
Definition at line 90 of file messaging_udp_server.cpp.
    {
        return start_server(port);
    }
start_server() [1/3]
bool kcenon::network::core::messaging_udp_server::start_server (std::string_view address, uint16_t port) export
Start the server on a specific interface.
Parameters
address The interface address to bind to
port The port to listen on
Returns
true if server started successfully
start_server() [2/3]
bool kcenon::network::core::messaging_udp_server::start_server (uint16_t port) export
Start the server on a specified port.
Parameters
port The port to listen on
Returns
true if server started successfully
start_server() [3/3]
auto kcenon::network::core::messaging_udp_server::start_server (uint16_t port) -> VoidResult nodiscard
Starts the server on the specified port.
Parameters
port The UDP port to bind and listen on.
Returns
Result<void> - Success if server started, or error with code:
error_codes::network_system::server_already_running if already running
error_codes::network_system::bind_failed if port binding failed
error_codes::common_errors::internal_error for other failures
Definition at line 31 of file messaging_udp_server.cpp.
    {
        if (lifecycle_.is_running())
        {
            return error_void(
                error_codes::network_system::server_already_running,
                "UDP server is already running",
                "messaging_udp_server::start_server");
        }
        // Mark as running before starting
        lifecycle_.set_running();
        auto result = do_start_impl(port);
        if (result.is_err())
        {
            lifecycle_.mark_stopped();
        }
        return result;
    }
References kcenon::network::error_void(), and kcenon::network::error_codes::network_system::server_already_running.
stop()
auto kcenon::network::core::messaging_udp_server::stop () -> VoidResult nodiscard override virtual
Stops the UDP server.
Returns
VoidResult indicating success or failure.
Implements i_udp_server::stop(). Delegates to stop_server().
Implements kcenon::network::interfaces::i_udp_server.
Definition at line 95 of file messaging_udp_server.cpp.
    {
        return stop_server();
    }
stop_server() [1/2]
void kcenon::network::core::messaging_udp_server::stop_server () export
Stop the server.
stop_server() [2/2]
auto kcenon::network::core::messaging_udp_server::stop_server () -> VoidResult nodiscard
Stops the server and releases all resources.
Returns
Result<void> - Success if server stopped, or error with code:
error_codes::common_errors::internal_error for failures
Definition at line 53 of file messaging_udp_server.cpp.
    {
        if (!lifecycle_.prepare_stop())
        {
            return ok();  // Not running or already stopping
        }
        auto result = do_stop_impl();
        lifecycle_.mark_stopped();
        return result;
    }
References kcenon::network::ok().
Referenced by ~messaging_udp_server().
wait_for_stop()
auto kcenon::network::core::messaging_udp_server::wait_for_stop () -> void override virtual
Blocks until stop_server() is called.
Implements i_network_component::wait_for_stop().
Implements kcenon::network::interfaces::i_network_component.
Definition at line 81 of file messaging_udp_server.cpp.
    {
        lifecycle_.wait_for_stop();
    }
Member Data Documentation
callbacks_
callbacks_t kcenon::network::core::messaging_udp_server::callbacks_ private
Callback manager.
Definition at line 295 of file messaging_udp_server.h.
Referenced by get_error_callback(), and get_receive_callback().
io_context_
std::unique_ptr<asio::io_context> kcenon::network::core::messaging_udp_server::io_context_ private
ASIO I/O context.
Definition at line 297 of file messaging_udp_server.h.
io_context_future_
std::future<void> kcenon::network::core::messaging_udp_server::io_context_future_ private
Future for io_context run task.
Definition at line 301 of file messaging_udp_server.h.
lifecycle_
utils::lifecycle_manager kcenon::network::core::messaging_udp_server::lifecycle_ private
Lifecycle state manager.
Definition at line 294 of file messaging_udp_server.h.
Referenced by is_running(), and ~messaging_udp_server().
pimpl_
std::unique_ptr<impl> kcenon::network::core::messaging_udp_server::pimpl_ export private
Definition at line 325 of file udp.cppm.
server_id_
std::string kcenon::network::core::messaging_udp_server::server_id_ private
Server identifier.
Definition at line 293 of file messaging_udp_server.h.
Referenced by server_id().
socket_
std::shared_ptr<internal::udp_socket> kcenon::network::core::messaging_udp_server::socket_ private
UDP socket wrapper.
Definition at line 298 of file messaging_udp_server.h.
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::messaging_udp_server::thread_pool_ private
Thread pool for async operations.
Definition at line 300 of file messaging_udp_server.h.
The documentation for this class was generated from the following files:
src/internal/core/messaging_udp_server.h
src/modules/udp.cppm
src/core/messaging_udp_server.cpp