Network System: kcenon::network::protocols::quic::hkdf Class Reference
kcenon::network::protocols::quic::hkdf Class Reference
HKDF (HMAC-based Key Derivation Function) utilities (RFC 5869)
#include <crypto.h>
Static Public Member Functions
static auto extract (std::span< const uint8_t > salt, std::span< const uint8_t > ikm) -> Result< std::array< uint8_t, secret_size > >
HKDF-Extract function.
static auto expand (std::span< const uint8_t > prk, std::span< const uint8_t > info, size_t length) -> Result< std::vector< uint8_t > >
HKDF-Expand function.
static auto expand_label (std::span< const uint8_t > secret, const std::string &label, std::span< const uint8_t > context, size_t length) -> Result< std::vector< uint8_t > >
HKDF-Expand-Label function (TLS 1.3 style)
Detailed Description
HKDF (HMAC-based Key Derivation Function) utilities (RFC 5869)
Used for deriving QUIC keys from secrets.
Definition at line 87 of file crypto.h.
Member Function Documentation
expand()
auto kcenon::network::protocols::quic::hkdf::expand (std::span< const uint8_t > prk, std::span< const uint8_t > info, size_t length) -> Result<std::vector<uint8_t>> static
HKDF-Expand function.
Parameters
prk Pseudorandom key from Extract
info Context and application specific information
length Desired output length
Returns
Output keying material (OKM) or error
Definition at line 152 of file crypto.cpp.
{
    std::vector<uint8_t> okm(length);
    EVP_PKEY_CTX* pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_HKDF, nullptr);
    if (!pctx)
    {
        return error<std::vector<uint8_t>>(
            -1, "Failed to create HKDF context", "quic::hkdf");
    }
    int ret = EVP_PKEY_derive_init(pctx);
    if (ret <= 0)
    {
        EVP_PKEY_CTX_free(pctx);
        return error<std::vector<uint8_t>>(
            -1, "HKDF derive init failed", "quic::hkdf", get_openssl_error_string());
    }
    ret = EVP_PKEY_CTX_set_hkdf_md(pctx, EVP_sha256());
    if (ret <= 0)
    {
        EVP_PKEY_CTX_free(pctx);
        return error<std::vector<uint8_t>>(
            -1, "HKDF set md failed", "quic::hkdf", get_openssl_error_string());
    }
    ret = EVP_PKEY_CTX_hkdf_mode(pctx, EVP_PKEY_HKDEF_MODE_EXPAND_ONLY);
    if (ret <= 0)
    {
        EVP_PKEY_CTX_free(pctx);
        return error<std::vector<uint8_t>>(
            -1, "HKDF set mode failed", "quic::hkdf", get_openssl_error_string());
    }
    ret = EVP_PKEY_CTX_set1_hkdf_key(pctx, prk.data(),
                                      static_cast<int>(prk.size()));
    if (ret <= 0)
    {
        EVP_PKEY_CTX_free(pctx);
        return error<std::vector<uint8_t>>(
            -1, "HKDF set key failed", "quic::hkdf", get_openssl_error_string());
    }
    ret = EVP_PKEY_CTX_add1_hkdf_info(pctx, info.data(),
                                       static_cast<int>(info.size()));
    if (ret <= 0)
    {
        EVP_PKEY_CTX_free(pctx);
        return error<std::vector<uint8_t>>(
            -1, "HKDF set info failed", "quic::hkdf", get_openssl_error_string());
    }
    ret = EVP_PKEY_derive(pctx, okm.data(), &length);
    EVP_PKEY_CTX_free(pctx);
    if (ret <= 0)
    {
        return error<std::vector<uint8_t>>(
            -1, "HKDF expand failed", "quic::hkdf", get_openssl_error_string());
    }
    okm.resize(length);
    return ok(std::move(okm));
}
References kcenon::network::ok().
expand_label()
auto kcenon::network::protocols::quic::hkdf::expand_label (std::span< const uint8_t > secret, const std::string & label, std::span< const uint8_t > context, size_t length) -> Result<std::vector<uint8_t>> static
HKDF-Expand-Label function (TLS 1.3 style)
Parameters
secret Secret to expand
label Label string (without "tls13 " prefix)
context Context data (usually empty for QUIC)
length Desired output length
Returns
Output keying material or error
Definition at line 221 of file crypto.cpp.
{
    // TLS 1.3 HKDF-Expand-Label structure:
    // struct {
    //     uint16 length;
    //     opaque label<7..255> = "tls13 " + Label;
    //     opaque context<0..255>;
    // } HkdfLabel;
    const std::string prefix = "tls13 ";
    std::vector<uint8_t> hkdf_label;
    hkdf_label.reserve(2 + 1 + prefix.size() + label.size() + 1 + context.size());
    // Length (2 bytes, big-endian)
    hkdf_label.push_back(static_cast<uint8_t>((length >> 8) & 0xFF));
    hkdf_label.push_back(static_cast<uint8_t>(length & 0xFF));
    // Label length (1 byte) + "tls13 " + label
    size_t label_len = prefix.size() + label.size();
    hkdf_label.push_back(static_cast<uint8_t>(label_len));
    for (char c : prefix)
    {
        hkdf_label.push_back(static_cast<uint8_t>(c));
    }
    for (char c : label)
    {
        hkdf_label.push_back(static_cast<uint8_t>(c));
    }
    // Context length (1 byte) + context
    hkdf_label.push_back(static_cast<uint8_t>(context.size()));
    hkdf_label.insert(hkdf_label.end(), context.begin(), context.end());
    return expand(secret, hkdf_label, length);
}
Referenced by kcenon::network::protocols::quic::initial_keys::derive(), kcenon::network::protocols::quic::initial_keys::derive_keys(), kcenon::network::protocols::quic::quic_crypto::derive_zero_rtt_keys(), and kcenon::network::protocols::quic::quic_crypto::update_keys().
extract()
auto kcenon::network::protocols::quic::hkdf::extract (std::span< const uint8_t > salt, std::span< const uint8_t > ikm) -> Result<std::array<uint8_t, secret_size>> static
HKDF-Extract function.
Parameters
salt Salt value (non-secret random value)
ikm Input keying material
Returns
Pseudorandom key (PRK) or error
Definition at line 84 of file crypto.cpp.
{
    std::array<uint8_t, secret_size> prk{};
    size_t prk_len = prk.size();
    EVP_PKEY_CTX* pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_HKDF, nullptr);
    if (!pctx)
    {
        return error<std::array<uint8_t, secret_size>>(
            -1, "Failed to create HKDF context", "quic::hkdf");
    }
    int ret = EVP_PKEY_derive_init(pctx);
    if (ret <= 0)
    {
        EVP_PKEY_CTX_free(pctx);
        return error<std::array<uint8_t, secret_size>>(
            -1, "HKDF derive init failed", "quic::hkdf", get_openssl_error_string());
    }
    ret = EVP_PKEY_CTX_set_hkdf_md(pctx, EVP_sha256());
    if (ret <= 0)
    {
        EVP_PKEY_CTX_free(pctx);
        return error<std::array<uint8_t, secret_size>>(
            -1, "HKDF set md failed", "quic::hkdf", get_openssl_error_string());
    }
    ret = EVP_PKEY_CTX_set1_hkdf_salt(pctx, salt.data(),
                                       static_cast<int>(salt.size()));
    if (ret <= 0)
    {
        EVP_PKEY_CTX_free(pctx);
        return error<std::array<uint8_t, secret_size>>(
            -1, "HKDF set salt failed", "quic::hkdf", get_openssl_error_string());
    }
    ret = EVP_PKEY_CTX_set1_hkdf_key(pctx, ikm.data(),
                                      static_cast<int>(ikm.size()));
    if (ret <= 0)
    {
        EVP_PKEY_CTX_free(pctx);
        return error<std::array<uint8_t, secret_size>>(
            -1, "HKDF set key failed", "quic::hkdf", get_openssl_error_string());
    }
    ret = EVP_PKEY_CTX_hkdf_mode(pctx, EVP_PKEY_HKDEF_MODE_EXTRACT_ONLY);
    if (ret <= 0)
    {
        EVP_PKEY_CTX_free(pctx);
        return error<std::array<uint8_t, secret_size>>(
            -1, "HKDF set mode failed", "quic::hkdf", get_openssl_error_string());
    }
    ret = EVP_PKEY_derive(pctx, prk.data(), &prk_len);
    EVP_PKEY_CTX_free(pctx);
    if (ret <= 0)
    {
        return error<std::array<uint8_t, secret_size>>(
            -1, "HKDF extract failed", "quic::hkdf", get_openssl_error_string());
    }
    return ok(std::move(prk));
}
References kcenon::network::ok().
Referenced by kcenon::network::protocols::quic::initial_keys::derive(), and kcenon::network::protocols::quic::quic_crypto::derive_zero_rtt_keys().
The documentation for this class was generated from the following files:
src/internal/protocols/quic/crypto.h
src/protocols/quic/crypto.cpp