Network System: kcenon::network::integration::basic_monitoring::impl Class Reference
kcenon::network::integration::basic_monitoring::impl Class Reference
Public Member Functions
impl (bool enable_logging)
void report_counter (const std::string &name, double value, const std::map< std::string, std::string > &labels)
void report_gauge (const std::string &name, double value, const std::map< std::string, std::string > &labels)
void report_histogram (const std::string &name, double value, const std::map< std::string, std::string > &labels)
void report_health (const std::string &connection_id, bool is_alive, double response_time_ms, size_t missed_heartbeats, double packet_loss_rate)
void set_logging_enabled (bool enabled)
bool is_logging_enabled () const
Private Attributes
bool logging_enabled_
Detailed Description
Definition at line 20 of file monitoring_integration.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::integration::basic_monitoring::impl::impl (bool enable_logging) inline explicit
Definition at line 23 of file monitoring_integration.cpp.
: logging_enabled_(enable_logging) {}
Member Function Documentation
is_logging_enabled()
bool kcenon::network::integration::basic_monitoring::impl::is_logging_enabled () const inline
Definition at line 114 of file monitoring_integration.cpp.
{ return logging_enabled_; }
References logging_enabled_.
Referenced by kcenon::network::integration::basic_monitoring::is_logging_enabled().
report_counter()
void kcenon::network::integration::basic_monitoring::impl::report_counter (const std::string & name, double value, const std::map< std::string, std::string > & labels) inline
Definition at line 25 of file monitoring_integration.cpp.
        {
            if (!logging_enabled_)
                return;
            std::ostringstream oss;
            oss << "[MONITORING] Counter: " << name << " = " << value;
            if (!labels.empty())
            {
                oss << " {";
                bool first = true;
                for (const auto& [key, val] : labels)
                {
                    if (!first)
                        oss << ", ";
                    oss << key << "=" << val;
                    first = false;
                }
                oss << "}";
            }
            NETWORK_LOG_DEBUG(oss.str());
        }
References logging_enabled_, and NETWORK_LOG_DEBUG.
Referenced by kcenon::network::integration::basic_monitoring::report_counter().
report_gauge()
void kcenon::network::integration::basic_monitoring::impl::report_gauge (const std::string & name, double value, const std::map< std::string, std::string > & labels) inline
Definition at line 49 of file monitoring_integration.cpp.
        {
            if (!logging_enabled_)
                return;
            std::ostringstream oss;
            oss << "[MONITORING] Gauge: " << name << " = " << value;
            if (!labels.empty())
            {
                oss << " {";
                bool first = true;
                for (const auto& [key, val] : labels)
                {
                    if (!first)
                        oss << ", ";
                    oss << key << "=" << val;
                    first = false;
                }
                oss << "}";
            }
            NETWORK_LOG_DEBUG(oss.str());
        }
References logging_enabled_, and NETWORK_LOG_DEBUG.
Referenced by kcenon::network::integration::basic_monitoring::report_gauge().
report_health()
void kcenon::network::integration::basic_monitoring::impl::report_health (const std::string & connection_id, bool is_alive, double response_time_ms, size_t missed_heartbeats, double packet_loss_rate) inline
Definition at line 97 of file monitoring_integration.cpp.
        {
            if (!logging_enabled_)
                return;
            std::ostringstream oss;
            oss << "[MONITORING] Health: " << connection_id << " - alive=" << is_alive
                << ", response_time=" << response_time_ms << "ms"
                << ", missed_heartbeats=" << missed_heartbeats
                << ", packet_loss=" << (packet_loss_rate * 100.0) << "%";
            NETWORK_LOG_DEBUG(oss.str());
        }
References logging_enabled_, and NETWORK_LOG_DEBUG.
Referenced by kcenon::network::integration::basic_monitoring::report_health().
report_histogram()
void kcenon::network::integration::basic_monitoring::impl::report_histogram (const std::string & name, double value, const std::map< std::string, std::string > & labels) inline
Definition at line 73 of file monitoring_integration.cpp.
        {
            if (!logging_enabled_)
                return;
            std::ostringstream oss;
            oss << "[MONITORING] Histogram: " << name << " = " << value;
            if (!labels.empty())
            {
                oss << " {";
                bool first = true;
                for (const auto& [key, val] : labels)
                {
                    if (!first)
                        oss << ", ";
                    oss << key << "=" << val;
                    first = false;
                }
                oss << "}";
            }
            NETWORK_LOG_DEBUG(oss.str());
        }
References logging_enabled_, and NETWORK_LOG_DEBUG.
Referenced by kcenon::network::integration::basic_monitoring::report_histogram().
set_logging_enabled()
void kcenon::network::integration::basic_monitoring::impl::set_logging_enabled (bool enabled) inline
Definition at line 112 of file monitoring_integration.cpp.
{ logging_enabled_ = enabled; }
References enabled, and logging_enabled_.
Referenced by kcenon::network::integration::basic_monitoring::set_logging_enabled().
Member Data Documentation
logging_enabled_
bool kcenon::network::integration::basic_monitoring::impl::logging_enabled_ private
Definition at line 117 of file monitoring_integration.cpp.
Referenced by is_logging_enabled(), report_counter(), report_gauge(), report_health(), report_histogram(), and set_logging_enabled().
The documentation for this class was generated from the following file:
src/integration/monitoring_integration.cpp