Network System: kcenon::network::unified::adapters::ws_connection_adapter Class Reference
kcenon::network::unified::adapters::ws_connection_adapter Class Reference
Adapter that wraps messaging_ws_client to implement i_connection.
#include <ws_connection_adapter.h>
Public Member Functions
ws_connection_adapter (std::string_view connection_id)
Constructs an adapter with a unique connection ID.
~ws_connection_adapter () override
Destructor ensures proper cleanup.
ws_connection_adapter (const ws_connection_adapter &)=delete
ws_connection_adapter & operator= (const ws_connection_adapter &)=delete
ws_connection_adapter (ws_connection_adapter &&)=delete
ws_connection_adapter & operator= (ws_connection_adapter &&)=delete
auto send (std::span< const std::byte > data) -> VoidResult override
Sends raw data to the remote endpoint.
auto send (std::vector< uint8_t > &&data) -> VoidResult override
Sends data from a uint8_t vector.
auto is_connected () const noexcept -> bool override
Checks if the transport is currently connected.
auto id () const noexcept -> std::string_view override
Gets the unique identifier for this transport/connection.
auto remote_endpoint () const noexcept -> endpoint_info override
Gets the remote endpoint information.
auto local_endpoint () const noexcept -> endpoint_info override
Gets the local endpoint information.
auto connect (const endpoint_info &endpoint) -> VoidResult override
Connects to a remote endpoint using host/port.
auto connect (std::string_view url) -> VoidResult override
Connects to a remote endpoint using URL.
auto close () noexcept -> void override
Closes the connection gracefully.
auto set_callbacks (connection_callbacks callbacks) -> void override
Sets all connection callbacks at once.
auto set_options (connection_options options) -> void override
Sets connection options.
auto set_timeout (std::chrono::milliseconds timeout) -> void override
Sets the connection timeout.
auto is_connecting () const noexcept -> bool override
Checks if the connection is in the process of connecting.
auto wait_for_stop () -> void override
Blocks until the component has stopped.
auto set_path (std::string_view path) -> void
Sets the WebSocket path for endpoint-based connections.
Public Member Functions inherited from kcenon::network::unified::i_connection
~i_connection () override=default
Virtual destructor.
i_connection (const i_connection &)=delete
i_connection & operator= (const i_connection &)=delete
i_connection (i_connection &&)=default
i_connection & operator= (i_connection &&)=default
Public Member Functions inherited from kcenon::network::unified::i_transport
virtual ~i_transport ()=default
Virtual destructor for proper cleanup of derived classes.
i_transport (const i_transport &)=delete
i_transport & operator= (const i_transport &)=delete
i_transport (i_transport &&)=default
i_transport & operator= (i_transport &&)=default
Private Member Functions
auto setup_internal_callbacks () -> void
Sets up internal callbacks to bridge to unified callbacks.
Static Private Member Functions
static auto parse_websocket_url (std::string_view url, std::string &host, uint16_t &port, std::string &path, bool &secure) -> bool
Parses a WebSocket URL into components.
Private Attributes
std::string connection_id_
std::shared_ptr< core::messaging_ws_client > client_
std::string ws_path_ = "/"
std::mutex callbacks_mutex_
connection_callbacks callbacks_
std::mutex endpoint_mutex_
endpoint_info remote_endpoint_
endpoint_info local_endpoint_
std::atomic< bool > is_connecting_ {false}
connection_options options_
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::unified::i_connection
i_connection ()=default
Default constructor (only for derived classes)
Protected Member Functions inherited from kcenon::network::unified::i_transport
i_transport ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps messaging_ws_client to implement i_connection.
This adapter bridges the existing WebSocket client implementation with the new unified interface, enabling protocol factory functions to return i_connection while using the battle-tested underlying implementation.
Thread Safety
Thread-safe. All methods can be called from any thread.
Ownership
The adapter owns the underlying client via shared_ptr for proper RAII.
WebSocket Semantics
connect() accepts WebSocket URLs (ws://, wss://) or endpoint_info with path
is_connected() returns true after successful WebSocket handshake
send() sends binary WebSocket frames
Data arrives via on_data callback
Definition at line 65 of file ws_connection_adapter.h.
Constructor & Destructor Documentation
ws_connection_adapter() [1/3]
kcenon::network::unified::adapters::ws_connection_adapter::ws_connection_adapter (std::string_view connection_id) explicit
Constructs an adapter with a unique connection ID.
Parameters
connection_id Unique identifier for this connection
Definition at line 41 of file ws_connection_adapter.cpp.
    : connection_id_(connection_id)
    , client_(std::make_shared<core::messaging_ws_client>(connection_id))
{
    setup_internal_callbacks();
}
References setup_internal_callbacks().
~ws_connection_adapter()
kcenon::network::unified::adapters::ws_connection_adapter::~ws_connection_adapter () override
Destructor ensures proper cleanup.
Definition at line 48 of file ws_connection_adapter.cpp.
{
    close();
}
References close().
ws_connection_adapter() [2/3]
kcenon::network::unified::adapters::ws_connection_adapter::ws_connection_adapter (const ws_connection_adapter &) delete
ws_connection_adapter() [3/3]
kcenon::network::unified::adapters::ws_connection_adapter::ws_connection_adapter (ws_connection_adapter &&) delete
Member Function Documentation
close()
auto kcenon::network::unified::adapters::ws_connection_adapter::close () -> void override virtual noexcept
Closes the connection gracefully.
Behavior
Initiates graceful shutdown
Pending sends may be completed before close
Triggers on_disconnected callback when fully closed
Thread Safety
Thread-safe. Safe to call multiple times.
Note
After close(), is_connected() returns false and send() returns error.
Implements kcenon::network::unified::i_connection.
Definition at line 184 of file ws_connection_adapter.cpp.
{
    if (client_ && client_->is_running()) {
        (void)client_->stop();
    }
    is_connecting_ = false;
}
References client_, and is_connecting_.
Referenced by ~ws_connection_adapter().
connect() [1/2]
auto kcenon::network::unified::adapters::ws_connection_adapter::connect (const endpoint_info & endpoint) -> VoidResult override virtual
Connects to a remote endpoint using host/port.
Parameters
endpoint The remote endpoint to connect to
Returns
VoidResult indicating success or failure
Behavior
Initiates connection to the specified endpoint
May block until connection is established (sync mode)
May return immediately and notify via callback (async mode)
Error Conditions
Returns error if already connected
Returns error if connection fails
Returns error if host resolution fails
Returns error if connection timeout expires
Thread Safety
Thread-safe. Only one connect operation can succeed at a time.
Implements kcenon::network::unified::i_connection.
Definition at line 102 of file ws_connection_adapter.cpp.
{
    if (!client_) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "Client is not initialized"
        );
    }
    if (client_->is_connected() || client_->is_running()) {
        return error_void(
            static_cast<int>(std::errc::already_connected),
            "Already connected or connecting"
        );
    }
    {
        std::lock_guard lock(endpoint_mutex_);
        remote_endpoint_ = endpoint;
    }
    is_connecting_ = true;
    // Use endpoint's port, default to 80 if not specified
    uint16_t port = endpoint.port;
    if (port == 0) {
        port = 80;
    }
    auto result = client_->start_client(endpoint.host, port, ws_path_);
    if (!result.is_ok()) {
        is_connecting_ = false;
    }
    return result;
}
References kcenon::network::error_void().
connect() [2/2]
auto kcenon::network::unified::adapters::ws_connection_adapter::connect (std::string_view url) -> VoidResult override virtual
Connects to a remote endpoint using URL.
Parameters
url The URL to connect to (e.g., "wss://example.com/ws")
Returns
VoidResult indicating success or failure
This overload is primarily for URL-based protocols like WebSocket and HTTP. For socket-based protocols, use the endpoint_info overload.
Error Conditions
Same as connect(endpoint_info) plus:
Returns error if URL is malformed
Returns error if protocol is not supported
Implements kcenon::network::unified::i_connection.
Definition at line 140 of file ws_connection_adapter.cpp.
{
    if (!client_) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "Client is not initialized"
        );
    }
    if (client_->is_connected() || client_->is_running()) {
        return error_void(
            static_cast<int>(std::errc::already_connected),
            "Already connected or connecting"
        );
    }
    std::string host;
    uint16_t port = 0;
    std::string path;
    bool secure = false;
    if (!parse_websocket_url(url, host, port, path, secure)) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "Invalid WebSocket URL format. Expected: ws://host:port/path or wss://host:port/path"
        );
    }
    {
        std::lock_guard lock(endpoint_mutex_);
        remote_endpoint_ = endpoint_info{host, port};
    }
    is_connecting_ = true;
    auto result = client_->start_client(host, port, path);
    if (!result.is_ok()) {
        is_connecting_ = false;
    }
    return result;
}
References kcenon::network::error_void().
id()
auto kcenon::network::unified::adapters::ws_connection_adapter::id () const -> std::string_view override virtual noexcept
Gets the unique identifier for this transport/connection.
Returns
A string view of the transport ID
The ID is unique within the application and remains constant for the lifetime of the transport instance.
Implements kcenon::network::unified::i_transport.
Definition at line 85 of file ws_connection_adapter.cpp.
{
    return connection_id_;
}
References connection_id_.
is_connected()
auto kcenon::network::unified::adapters::ws_connection_adapter::is_connected () const -> bool override virtual noexcept
Checks if the transport is currently connected.
Returns
true if connected and ready to send/receive, false otherwise
Thread Safety
Thread-safe. Uses atomic operations internally.
Note
A false return may indicate:
Connection not yet established
Connection closed by remote peer
Connection closed locally
Network error occurred
Implements kcenon::network::unified::i_transport.
Definition at line 80 of file ws_connection_adapter.cpp.
{
    return client_ && client_->is_connected();
}
References client_.
is_connecting()
auto kcenon::network::unified::adapters::ws_connection_adapter::is_connecting () const -> bool override virtual noexcept
Checks if the connection is in the process of connecting.
Returns
true if connect() was called but not yet completed
Implements kcenon::network::unified::i_connection.
Definition at line 212 of file ws_connection_adapter.cpp.
{
    return is_connecting_.load();
}
References is_connecting_.
local_endpoint()
auto kcenon::network::unified::adapters::ws_connection_adapter::local_endpoint () const -> endpoint_info override virtual noexcept
Gets the local endpoint information.
Returns
endpoint_info of the local side
Returns valid information only when connected/listening. Returns empty endpoint_info if not bound.
Implements kcenon::network::unified::i_transport.
Definition at line 96 of file ws_connection_adapter.cpp.
{
    std::lock_guard lock(endpoint_mutex_);
    return local_endpoint_;
}
References endpoint_mutex_, and local_endpoint_.
operator=() [1/2]
ws_connection_adapter & kcenon::network::unified::adapters::ws_connection_adapter::operator= (const ws_connection_adapter &) delete
operator=() [2/2]
ws_connection_adapter & kcenon::network::unified::adapters::ws_connection_adapter::operator= (ws_connection_adapter &&) delete
parse_websocket_url()
auto kcenon::network::unified::adapters::ws_connection_adapter::parse_websocket_url (std::string_view url, std::string & host, uint16_t & port, std::string & path, bool & secure) -> bool static private
Parses a WebSocket URL into components.
Parameters
url The URL to parse
host Output: extracted host
port Output: extracted port
path Output: extracted path
secure Output: true if wss://
Returns
true if parsing succeeded
Definition at line 290 of file ws_connection_adapter.cpp.
{
    std::string url_str(url);
    // Check for WebSocket schemes
    secure = false;
    std::string remaining;
    if (url_str.substr(0, 6) == "wss://") {
        secure = true;
        remaining = url_str.substr(6);
    } else if (url_str.substr(0, 5) == "ws://") {
        secure = false;
        remaining = url_str.substr(5);
    } else {
        // No scheme, assume ws://
        remaining = url_str;
    }
    // Find path start
    auto path_pos = remaining.find('/');
    std::string host_port;
    if (path_pos != std::string::npos) {
        host_port = remaining.substr(0, path_pos);
        path = remaining.substr(path_pos);
    } else {
        host_port = remaining;
        path = "/";
    }
    // Parse host and port
    auto colon_pos = host_port.rfind(':');
    // Check if this is IPv6 (contains '[')
    bool is_ipv6 = host_port.find('[') != std::string::npos;
    if (is_ipv6) {
        auto bracket_end = host_port.find(']');
        if (bracket_end == std::string::npos) {
            return false;  // Invalid IPv6 format
        }
        host = host_port.substr(0, bracket_end + 1);
        if (bracket_end + 1 < host_port.size() && host_port[bracket_end + 1] == ':') {
            std::string port_str = host_port.substr(bracket_end + 2);
            try {
                port = static_cast<uint16_t>(std::stoi(port_str));
            } catch (...) {
                return false;
            }
        } else {
            port = secure ? 443 : 80;
        }
    } else if (colon_pos != std::string::npos) {
        host = host_port.substr(0, colon_pos);
        std::string port_str = host_port.substr(colon_pos + 1);
        try {
            port = static_cast<uint16_t>(std::stoi(port_str));
        } catch (...) {
            return false;
        }
    } else {
        host = host_port;
        port = secure ? 443 : 80;
    }
    return !host.empty();
}
remote_endpoint()
auto kcenon::network::unified::adapters::ws_connection_adapter::remote_endpoint () const -> endpoint_info override virtual noexcept
Gets the remote endpoint information.
Returns
endpoint_info of the remote peer
Returns valid information only when connected. Returns empty endpoint_info if not connected.
Implements kcenon::network::unified::i_transport.
Definition at line 90 of file ws_connection_adapter.cpp.
{
    std::lock_guard lock(endpoint_mutex_);
    return remote_endpoint_;
}
References endpoint_mutex_, and remote_endpoint_.
send() [1/2]
auto kcenon::network::unified::adapters::ws_connection_adapter::send (std::span< const std::byte > data) -> VoidResult override virtual
Sends raw data to the remote endpoint.
Parameters
data The data to send as a span of bytes
Returns
VoidResult indicating success or failure
Error Conditions
Returns error if not connected
Returns error if send operation fails
Returns error if data size exceeds protocol limits
Thread Safety
Thread-safe. Multiple sends may be queued internally.
Performance Note
Data is typically copied to an internal send buffer. For zero-copy sends, see protocol-specific implementations.
Implements kcenon::network::unified::i_transport.
Definition at line 53 of file ws_connection_adapter.cpp.
{
    if (!client_ || !client_->is_connected()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "WebSocket is not connected"
        );
    }
    std::vector<uint8_t> buffer(data.size());
    std::memcpy(buffer.data(), data.data(), data.size());
    return client_->send_binary(std::move(buffer));
}
References kcenon::network::error_void().
send() [2/2]
auto kcenon::network::unified::adapters::ws_connection_adapter::send (std::vector< uint8_t > && data) -> VoidResult override virtual
Sends data from a uint8_t vector.
Parameters
data The data to send as a vector of uint8_t
Returns
VoidResult indicating success or failure
Convenience overload for compatibility with existing code using std::vector<uint8_t>.
Implements kcenon::network::unified::i_transport.
Definition at line 68 of file ws_connection_adapter.cpp.
{
    if (!client_ || !client_->is_connected()) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "WebSocket is not connected"
        );
    }
    return client_->send_binary(std::move(data));
}
References kcenon::network::error_void().
set_callbacks()
auto kcenon::network::unified::adapters::ws_connection_adapter::set_callbacks (connection_callbacks callbacks) -> void override virtual
Sets all connection callbacks at once.
Parameters
callbacks The callback structure with handlers
Replaces all previously set callbacks. Empty callback functions in the structure will clear the corresponding handler.
Thread Safety
Thread-safe, but callbacks may be invoked from I/O threads.
Implements kcenon::network::unified::i_connection.
Definition at line 192 of file ws_connection_adapter.cpp.
{
    {
        std::lock_guard lock(callbacks_mutex_);
        callbacks_ = std::move(callbacks);
    }
    setup_internal_callbacks();
}
set_options()
auto kcenon::network::unified::adapters::ws_connection_adapter::set_options (connection_options options) -> void override virtual
Sets connection options.
Parameters
options The configuration options
Some options may only be effective before connect() is called.
Thread Safety
Thread-safe. Changes may not affect in-flight operations.
Implements kcenon::network::unified::i_connection.
Definition at line 202 of file ws_connection_adapter.cpp.
{
    options_ = options;
}
set_path()
auto kcenon::network::unified::adapters::ws_connection_adapter::set_path (std::string_view path) -> void
Sets the WebSocket path for endpoint-based connections.
Parameters
path The WebSocket path (e.g., "/ws", "/socket.io")
Definition at line 224 of file ws_connection_adapter.cpp.
{
    ws_path_ = std::string(path);
}
set_timeout()
auto kcenon::network::unified::adapters::ws_connection_adapter::set_timeout (std::chrono::milliseconds timeout) -> void override virtual
Sets the connection timeout.
Parameters
timeout Timeout duration (0 = no timeout)
Shorthand for setting just the connect_timeout option.
Implements kcenon::network::unified::i_connection.
Definition at line 207 of file ws_connection_adapter.cpp.
{
    options_.connect_timeout = timeout;
}
setup_internal_callbacks()
auto kcenon::network::unified::adapters::ws_connection_adapter::setup_internal_callbacks () -> void private
Sets up internal callbacks to bridge to unified callbacks.
Definition at line 229 of file ws_connection_adapter.cpp.
{
    if (!client_) {
        return;
    }
    // Bridge binary message callback to on_data
    client_->set_binary_callback([this](const std::vector<uint8_t>& data) {
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_data) {
            std::span<const std::byte> byte_span(
                reinterpret_cast<const std::byte*>(data.data()),
                data.size()
            );
            callbacks_.on_data(byte_span);
        }
    });
    // Also bridge text messages as binary data for unified interface
    client_->set_text_callback([this](const std::string& text) {
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_data) {
            std::span<const std::byte> byte_span(
                reinterpret_cast<const std::byte*>(text.data()),
                text.size()
            );
            callbacks_.on_data(byte_span);
        }
    });
    // Bridge connected callback
    client_->set_connected_callback([this]() {
        is_connecting_ = false;
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_connected) {
            callbacks_.on_connected();
        }
    });
    // Bridge disconnected callback
    client_->set_disconnected_callback([this](uint16_t /*code*/, std::string_view /*reason*/) {
        is_connecting_ = false;
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_disconnected) {
            callbacks_.on_disconnected();
        }
    });
    // Bridge error callback
    client_->set_error_callback([this](std::error_code ec) {
        is_connecting_ = false;
        std::lock_guard lock(callbacks_mutex_);
        if (callbacks_.on_error) {
            callbacks_.on_error(ec);
        }
    });
}
Referenced by ws_connection_adapter().
wait_for_stop()
auto kcenon::network::unified::adapters::ws_connection_adapter::wait_for_stop () -> void override virtual
Blocks until the component has stopped.
Waits for all pending operations to complete and the connection to be fully closed.
Thread Safety
Safe to call from any thread. Uses internal synchronization.
Implements kcenon::network::unified::i_connection.
Definition at line 217 of file ws_connection_adapter.cpp.
{
    if (client_) {
        client_->wait_for_stop();
    }
}
Member Data Documentation
callbacks_
connection_callbacks kcenon::network::unified::adapters::ws_connection_adapter::callbacks_ private
Definition at line 144 of file ws_connection_adapter.h.
callbacks_mutex_
std::mutex kcenon::network::unified::adapters::ws_connection_adapter::callbacks_mutex_ mutable private
Definition at line 143 of file ws_connection_adapter.h.
client_
std::shared_ptr<core::messaging_ws_client> kcenon::network::unified::adapters::ws_connection_adapter::client_ private
Definition at line 140 of file ws_connection_adapter.h.
Referenced by close(), and is_connected().
connection_id_
std::string kcenon::network::unified::adapters::ws_connection_adapter::connection_id_ private
Definition at line 139 of file ws_connection_adapter.h.
Referenced by id().
endpoint_mutex_
std::mutex kcenon::network::unified::adapters::ws_connection_adapter::endpoint_mutex_ mutable private
Definition at line 146 of file ws_connection_adapter.h.
Referenced by local_endpoint(), and remote_endpoint().
is_connecting_
std::atomic<bool> kcenon::network::unified::adapters::ws_connection_adapter::is_connecting_ {false} private
Definition at line 150 of file ws_connection_adapter.h.
{false};
Referenced by close(), and is_connecting().
local_endpoint_
endpoint_info kcenon::network::unified::adapters::ws_connection_adapter::local_endpoint_ private
Definition at line 148 of file ws_connection_adapter.h.
Referenced by local_endpoint().
options_
connection_options kcenon::network::unified::adapters::ws_connection_adapter::options_ private
Definition at line 151 of file ws_connection_adapter.h.
remote_endpoint_
endpoint_info kcenon::network::unified::adapters::ws_connection_adapter::remote_endpoint_ private
Definition at line 147 of file ws_connection_adapter.h.
Referenced by remote_endpoint().
ws_path_
std::string kcenon::network::unified::adapters::ws_connection_adapter::ws_path_ = "/" private
Definition at line 141 of file ws_connection_adapter.h.
The documentation for this class was generated from the following files:
src/internal/unified/adapters/ws_connection_adapter.h
src/unified/adapters/ws_connection_adapter.cpp