Network System: kcenon::network::core::messaging_server Class Reference
kcenon::network::core::messaging_server Class Reference export
module kcenon.network
A server class that manages incoming TCP connections, creating messaging_session instances for each accepted socket.
#include <messaging_server.h>
Public Types
using connection_callback_t = std::function< void(std::shared_ptr< session::messaging_session >)>
Callback type for new connection.
using disconnection_callback_t = std::function< void(const std::string &)>
Callback type for disconnection.
using receive_callback_t = std::function< void(std::shared_ptr< session::messaging_session >, const std::vector< uint8_t > &)>
Callback type for received data.
using error_callback_t = std::function< void(std::shared_ptr< session::messaging_session >, std::error_code)>
Callback type for errors.
using client_connected_callback = std::function< void(const std::string &session_id)>
Callback type for client connection events.
using client_disconnected_callback = std::function< void(const std::string &session_id)>
Callback type for client disconnection events.
using client_data_callback = std::function< void(const std::string &session_id, std::span< const uint8_t > data)>
Callback type for client data events.
Public Member Functions
messaging_server (const std::string &server_id)
Constructs a messaging_server with an optional string server_id.
~messaging_server () noexcept
Destructor. If the server is still running, stop_server() is invoked.
messaging_server (const messaging_server &)=delete
messaging_server & operator= (const messaging_server &)=delete
messaging_server (messaging_server &&)=delete
messaging_server & operator= (messaging_server &&)=delete
auto start_server (unsigned short port) -> VoidResult
Starts the server on the specified port.
auto stop_server () -> VoidResult
Stops the server and closes all connections.
auto server_id () const -> const std::string &
Returns the server identifier.
auto set_connection_callback (connection_callback_t callback) -> void
Sets the callback for new client connections.
auto set_disconnection_callback (disconnection_callback_t callback) -> void
Sets the callback for client disconnections.
auto set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received messages.
auto set_error_callback (error_callback_t callback) -> void
Sets the callback for session errors.
messaging_server (std::string_view server_id)
Construct a server with a given server_id.
virtual ~messaging_server () noexcept
Destructor - automatically stops the server if running.
messaging_server (const messaging_server &)=delete
messaging_server & operator= (const messaging_server &)=delete
messaging_server (messaging_server &&) noexcept
messaging_server & operator= (messaging_server &&) noexcept
bool start_server (uint16_t port, int backlog=128)
Start the server on a specified port.
bool start_server (std::string_view address, uint16_t port, int backlog=128)
Start the server on a specific interface.
void stop_server ()
Stop the server and disconnect all clients.
bool wait_for_stop (std::chrono::milliseconds timeout=std::chrono::milliseconds(5000))
Wait for the server to stop.
bool send_to (std::string_view session_id, std::span< const uint8_t > data)
Send data to a specific client.
bool send_to (std::string_view session_id, std::string_view data)
Send data to a specific client.
void broadcast (std::span< const uint8_t > data)
Broadcast data to all connected clients.
void broadcast (std::string_view data)
Broadcast string data to all connected clients.
void disconnect (std::string_view session_id)
Disconnect a specific client.
bool is_running () const noexcept
Check if the server is running.
size_t client_count () const noexcept
Get the number of connected clients.
std::string_view server_id () const noexcept
Get the server identifier.
void set_client_connected_callback (client_connected_callback callback)
Set client connected callback.
void set_client_disconnected_callback (client_disconnected_callback callback)
Set client disconnected callback.
void set_client_data_callback (client_data_callback callback)
Set client data callback.
void set_error_callback (error_callback callback)
Set error callback.
Public Member Functions inherited from kcenon::network::utils::startable_base< messaging_server >
auto is_running () const noexcept -> bool
Checks if the component is currently running.
auto wait_for_stop () -> void
Blocks until stop is called.
Private Types
using callback_index = tcp_server_callback
Callback index type alias for clarity.
using callbacks_t = utils::callback_manager< connection_callback_t, disconnection_callback_t, receive_callback_t, error_callback_t >
Callback manager type for this server.
Private Member Functions
auto on_stopped () -> void
Called after stop operation completes. No-op for server (no disconnection callback at server level).
auto do_start_impl (unsigned short port) -> VoidResult
TCP-specific implementation of server start.
auto do_stop_impl () -> VoidResult
TCP-specific implementation of server stop.
auto get_connection_callback () const -> connection_callback_t
Gets a copy of the connection callback.
auto get_disconnection_callback () const -> disconnection_callback_t
Gets a copy of the disconnection callback.
auto get_receive_callback () const -> receive_callback_t
Gets a copy of the receive callback.
auto get_error_callback () const -> error_callback_t
Gets a copy of the error callback.
auto invoke_connection_callback (std::shared_ptr< session::messaging_session > session) -> void
Invokes the connection callback with the given session.
auto do_accept () -> void
Initiates an asynchronous accept operation (async_accept).
auto on_accept (std::error_code ec, asio::ip::tcp::socket socket) -> void
Handler called when an asynchronous accept finishes.
auto cleanup_dead_sessions () -> void
Removes stopped sessions from the sessions vector.
auto start_cleanup_timer () -> void
Starts a periodic timer that triggers session cleanup.
Static Private Member Functions
static constexpr auto component_name () noexcept -> std::string_view
Returns the component name for error messages.
Private Attributes
std::string server_id_
callbacks_t callbacks_
std::shared_ptr< asio::io_context > io_context_
std::unique_ptr< asio::executor_work_guard< asio::io_context::executor_type > > work_guard_
std::unique_ptr< asio::ip::tcp::acceptor > acceptor_
std::future< void > io_context_future_
std::vector< std::shared_ptr< kcenon::network::session::messaging_session > > sessions_
Holds all active sessions. When stop_server() is invoked, each session's stop_session() is called and they are cleared.
std::mutex sessions_mutex_
Mutex protecting access to sessions_ vector.
std::mutex acceptor_mutex_
Mutex protecting access to acceptor_ for thread-safe operations.
std::unique_ptr< asio::steady_timer > cleanup_timer_
Timer for periodic cleanup of stopped sessions.
std::unique_ptr< impl > pimpl_
Friends
class utils::startable_base< messaging_server >
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::utils::startable_base< messaging_server >
startable_base ()=default
Default constructor.
startable_base (const startable_base &)=delete
startable_base (startable_base &&) noexcept=default
~startable_base ()=default
Destructor.
startable_base & operator= (const startable_base &)=delete
startable_base & operator= (startable_base &&) noexcept=default
auto do_start (Args &&... args) -> VoidResult
Unified start operation with lifecycle management.
auto do_stop () -> VoidResult
Unified stop operation with lifecycle management.
auto is_stop_initiated () const noexcept -> bool
Checks if stop has been initiated.
auto get_lifecycle () -> lifecycle_manager &
Gets the lifecycle manager for derived class access.
auto get_lifecycle () const -> const lifecycle_manager &
Gets the lifecycle manager (const version).
Detailed Description
A server class that manages incoming TCP connections, creating messaging_session instances for each accepted socket.
A TCP server for handling multiple client connections.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling.
Thread Safety
All public methods are thread-safe.
Internal state (is_running_, sessions_) is protected by atomics and mutex.
Background thread runs io_context.run() independently.
Multiple sessions can be active concurrently without blocking each other.
Sessions vector is protected by sessions_mutex_ for thread-safe cleanup.
Key Responsibilities
Maintains an asio::io_context and tcp::acceptor to listen on a specified port.
For each incoming connection, instantiates a messaging_session to handle the communication logic (compression, encryption, message parsing, etc.).
Allows external control via start_server(), stop_server(), and wait_for_stop().
Thread Model
A single background thread calls io_context.run() to process I/O events.
Each accepted connection runs asynchronously; thus multiple sessions can be active concurrently without blocking each other.
Usage Example
// 1. Create a messaging_server:
auto server = std::make_shared<network::messaging_server>("ServerID");
// 2. Start listening on a port:
server->start_server(5555);
// 3. Wait for stop or run other tasks:
//    ...
// 4. Eventually stop the server:
server->stop_server();
// 5. (optional) If a separate thread is calling wait_for_stop():
server->wait_for_stop();
This class provides a TCP server that accepts client connections, manages sessions, and handles data exchange with multiple clients concurrently.
Thread Safety
All public methods are thread-safe.
Session management is internally synchronized.
Callbacks may be invoked from multiple threads.
Key Features
Multiple concurrent client support
Session-based connection management
Broadcast capability to all connected clients
Optional SSL/TLS upgrade support
import kcenon.network;
auto server = std::make_unique<kcenon::network::core::messaging_server>("my_server");
server->set_client_connected_callback([](const std::string& session_id) {
    std::cout << "Client connected: " << session_id << std::endl;
});
server->start_server(8080);
Definition at line 119 of file messaging_server.h.
Member Typedef Documentation
callback_index
using kcenon::network::core::messaging_server::callback_index = tcp_server_callback private
Callback index type alias for clarity.
Definition at line 351 of file messaging_server.h.
callbacks_t
using kcenon::network::core::messaging_server::callbacks_t = utils::callback_manager< connection_callback_t, disconnection_callback_t, receive_callback_t, error_callback_t > private
Callback manager type for this server.
Definition at line 354 of file messaging_server.h.
client_connected_callback
using kcenon::network::core::messaging_server::client_connected_callback = std::function<void(const std::string& session_id)> export
Callback type for client connection events.
Definition at line 242 of file tcp.cppm.
client_data_callback
using kcenon::network::core::messaging_server::client_data_callback = std::function<void(const std::string& session_id, std::span<const uint8_t> data)> export
Callback type for client data events.
Definition at line 252 of file tcp.cppm.
client_disconnected_callback
using kcenon::network::core::messaging_server::client_disconnected_callback = std::function<void(const std::string& session_id)> export
Callback type for client disconnection events.
Definition at line 247 of file tcp.cppm.
connection_callback_t
using kcenon::network::core::messaging_server::connection_callback_t = std::function<void(std::shared_ptr<session::messaging_session>)>
Callback type for new connection.
Definition at line 126 of file messaging_server.h.
disconnection_callback_t
using kcenon::network::core::messaging_server::disconnection_callback_t = std::function<void(const std::string&)>
Callback type for disconnection.
Definition at line 128 of file messaging_server.h.
error_callback_t
using kcenon::network::core::messaging_server::error_callback_t = std::function<void(std::shared_ptr<session::messaging_session>, std::error_code)>
Callback type for errors.
Definition at line 133 of file messaging_server.h.
receive_callback_t
using kcenon::network::core::messaging_server::receive_callback_t = std::function<void(std::shared_ptr<session::messaging_session>, const std::vector<uint8_t>&)>
Callback type for received data.
Definition at line 130 of file messaging_server.h.
Constructor & Destructor Documentation
messaging_server() [1/6]
kcenon::network::core::messaging_server::messaging_server (const std::string & server_id) explicit
Constructs a messaging_server with an optional string server_id.
Parameters
server_id A descriptive identifier for this server instance (e.g., "main_server").
Definition at line 49 of file messaging_server.cpp.
        : server_id_(server_id)
    {
    }
~messaging_server() [1/2]
kcenon::network::core::messaging_server::~messaging_server () noexcept
Destructor. If the server is still running, stop_server() is invoked.
Definition at line 54 of file messaging_server.cpp.
    {
        if (is_running())
        {
            (void)stop_server();
        }
        // Additional cleanup for resources not managed by lifecycle manager.
        try
        {
            // Ensure all resources are cleaned up even if stop_server() returned early
            // This handles the case where start_server() failed and is_running() is false
            // but resources were partially created
            // Lock to prevent race with do_accept() accessing the acceptor
            {
                std::lock_guard<std::mutex> lock(acceptor_mutex_);
                if (acceptor_)
                {
                    asio::error_code ec;
                    acceptor_->cancel(ec);
                    if (acceptor_->is_open())
                    {
                        acceptor_->close(ec);
                    }
                    acceptor_.reset();
                }
            }
            if (cleanup_timer_)
            {
                cleanup_timer_->cancel();
                cleanup_timer_.reset();
            }
            if (work_guard_)
            {
                work_guard_.reset();
            }
            if (io_context_)
            {
                io_context_->stop();
                io_context_.reset();
            }
        }
        catch (...)
        {
            // Destructor must not throw - swallow all exceptions
        }
    }
References acceptor_, acceptor_mutex_, cleanup_timer_, io_context_, is_running(), stop_server(), and work_guard_.
messaging_server() [2/6]
kcenon::network::core::messaging_server::messaging_server (const messaging_server &) delete
messaging_server() [3/6]
kcenon::network::core::messaging_server::messaging_server (messaging_server &&) delete
messaging_server() [4/6]
kcenon::network::core::messaging_server::messaging_server (std::string_view server_id) explicit export
Construct a server with a given server_id.
Parameters
server_id A string identifier for this server instance
~messaging_server() [2/2]
virtual kcenon::network::core::messaging_server::~messaging_server () export virtual noexcept
Destructor - automatically stops the server if running.
messaging_server() [5/6]
kcenon::network::core::messaging_server::messaging_server (const messaging_server &) export delete
messaging_server() [6/6]
kcenon::network::core::messaging_server::messaging_server (messaging_server &&) export noexcept
Member Function Documentation
broadcast() [1/2]
void kcenon::network::core::messaging_server::broadcast (std::span< const uint8_t > data) export
Broadcast data to all connected clients.
Parameters
data The data to broadcast
broadcast() [2/2]
void kcenon::network::core::messaging_server::broadcast (std::string_view data) export
Broadcast string data to all connected clients.
Parameters
data The string data to broadcast
cleanup_dead_sessions()
auto kcenon::network::core::messaging_server::cleanup_dead_sessions () -> void private
Removes stopped sessions from the sessions vector.
This method iterates through all sessions and removes those that have been stopped. Should be called periodically to prevent memory leaks from accumulating dead sessions.
Thread-safe: Protected by sessions_mutex_.
Definition at line 563 of file messaging_server.cpp.
    {
        std::lock_guard<std::mutex> lock(sessions_mutex_);
        // Remove sessions that have been stopped
        sessions_.erase(
            std::remove_if(sessions_.begin(), sessions_.end(),
                [](const auto& session) {
                    return session && session->is_stopped();
                }),
            sessions_.end()
        );
        NETWORK_LOG_DEBUG("[messaging_server] Cleaned up dead sessions. Active: " +
            std::to_string(sessions_.size()));
#if KCENON_WITH_COMMON_SYSTEM
        // Update active connections metric after cleanup
        if (monitor_) {
            monitor_->record_metric("active_connections", static_cast<double>(sessions_.size()));
        }
#endif
    }
References NETWORK_LOG_DEBUG.
client_count()
size_t kcenon::network::core::messaging_server::client_count () const export noexcept
Get the number of connected clients.
Returns
Number of connected clients
component_name()
static constexpr auto kcenon::network::core::messaging_server::component_name () -> std::string_view inline static constexpr private noexcept
Returns the component name for error messages.
Returns
The component name string view.
Definition at line 243 of file messaging_server.h.
        {
            return "Server";
        }
disconnect()
void kcenon::network::core::messaging_server::disconnect (std::string_view session_id) export
Disconnect a specific client.
Parameters
session_id The client's session ID to disconnect
do_accept()
auto kcenon::network::core::messaging_server::do_accept () -> void private
Initiates an asynchronous accept operation (async_accept).
On success, on_accept() is invoked with a newly accepted tcp::socket.
Definition at line 405 of file messaging_server.cpp.
    {
        // Lock to prevent race with do_stop() closing the acceptor
        std::lock_guard<std::mutex> lock(acceptor_mutex_);
        // Early return if server is stopping or acceptor is invalid
        if (!is_running() || !acceptor_ || !acceptor_->is_open())
        {
            return;
        }
        auto self = shared_from_this();
        acceptor_->async_accept(
            [this, self](std::error_code ec, tcp::socket sock)
            { on_accept(ec, std::move(sock)); });
    }
do_start_impl()
auto kcenon::network::core::messaging_server::do_start_impl (unsigned short port) -> VoidResult private
TCP-specific implementation of server start.
Parameters
port The TCP port to bind and listen on.
Returns
Result<void> - Success if server started, or error.
Definition at line 217 of file messaging_server.cpp.
    {
        // This method handles TCP-specific initialization.
        try
        {
            // Create io_context and acceptor
            io_context_ = std::make_shared<asio::io_context>();
            // Create work guard to keep io_context running
            work_guard_ = std::make_unique<asio::executor_work_guard<asio::io_context::executor_type>>(
                asio::make_work_guard(*io_context_)
            );
            acceptor_ = std::make_unique<tcp::acceptor>(
                *io_context_, tcp::endpoint(tcp::v4(), port));
            // Create cleanup timer
            cleanup_timer_ = std::make_unique<asio::steady_timer>(*io_context_);
            // Begin accepting connections
            do_accept();
            // Start periodic cleanup timer
            start_cleanup_timer();
            // Use io_context_thread_manager for unified thread management
            io_context_future_ = integration::io_context_thread_manager::instance()
                .run_io_context(io_context_, "messaging_server:" + server_id());
            NETWORK_LOG_INFO("[messaging_server] Started listening on port " + std::to_string(port));
            return ok();
        }
        catch (const std::system_error& e)
        {
            // Cleanup partially created resources to prevent memory corruption
            // Resources may have been created before the exception was thrown
            acceptor_.reset();
            cleanup_timer_.reset();
            work_guard_.reset();
            io_context_.reset();
            // Check for specific error codes (ASIO uses asio::error category)
            if (e.code() == asio::error::address_in_use ||
                e.code() == std::errc::address_in_use)
            {
                return error_void(
                    error_codes::network_system::bind_failed,
                    "Failed to bind to port: address already in use",
                    "messaging_server::do_start",
                    "Port: " + std::to_string(port)
                );
            }
            else if (e.code() == asio::error::access_denied ||
                     e.code() == std::errc::permission_denied)
            {
                return error_void(
                    error_codes::network_system::bind_failed,
                    "Failed to bind to port: permission denied",
                    "messaging_server::do_start",
                    "Port: " + std::to_string(port)
                );
            }
            return error_void(
                error_codes::common_errors::internal_error,
                "Failed to start server: " + std::string(e.what()),
                "messaging_server::do_start",
                "Port: " + std::to_string(port)
            );
        }
        catch (const std::exception& e)
        {
            // Cleanup partially created resources to prevent memory corruption
            acceptor_.reset();
            cleanup_timer_.reset();
            work_guard_.reset();
            io_context_.reset();
            return error_void(
                error_codes::common_errors::internal_error,
                "Failed to start server: " + std::string(e.what()),
                "messaging_server::do_start",
                "Port: " + std::to_string(port)
            );
        }
    }
References kcenon::network::error_codes::network_system::bind_failed, kcenon::network::error_void(), kcenon::network::integration::io_context_thread_manager::instance(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_INFO, kcenon::network::ok(), and kcenon::network::integration::io_context_thread_manager::run_io_context().
do_stop_impl()
auto kcenon::network::core::messaging_server::do_stop_impl () -> VoidResult private
TCP-specific implementation of server stop.
Returns
Result<void> - Success if server stopped, or error.
Definition at line 302 of file messaging_server.cpp.
    {
        // This method handles TCP-specific cleanup.
        try
        {
            // Step 1: Cancel and close the acceptor to stop accepting new connections
            // Lock to prevent race with do_accept() accessing the acceptor
            {
                std::lock_guard<std::mutex> lock(acceptor_mutex_);
                if (acceptor_)
                {
                    asio::error_code ec;
                    // Cancel pending async_accept operations to prevent memory leaks
                    acceptor_->cancel(ec);
                    if (acceptor_->is_open())
                    {
                        acceptor_->close(ec);
                    }
                }
            }
            // Cancel cleanup timer
            if (cleanup_timer_)
            {
                cleanup_timer_->cancel();
            }
            // Step 2: Stop all active sessions (close sockets, stop reading)
            // NOTE: Do NOT clear sessions here - they may still be referenced by
            // pending async callbacks. We must wait for io_context to finish first.
            {
                std::lock_guard<std::mutex> lock(sessions_mutex_);
                for (auto& sess : sessions_)
                {
                    if (sess)
                    {
                        sess->stop_session();
                    }
                }
            }
            // Step 3: Release work guard to allow io_context to finish
            if (work_guard_)
            {
                work_guard_.reset();
            }
            // Step 4: Stop io_context via unified manager
            if (io_context_)
            {
                integration::io_context_thread_manager::instance().stop_io_context(io_context_);
            }
            // Step 5: Wait for io_context task to complete
            // This ensures all pending async callbacks have finished executing
            if (io_context_future_.valid())
            {
                io_context_future_.wait();
            }
            // Step 5.5: Run remaining handlers to clean up pending async operations.
            // When io_context::stop() is called, pending handlers may not have
            // executed yet. Running poll() ensures all handlers are invoked and
            // their captured resources (resolver/socket) are properly destroyed
            // before io_context is destroyed, preventing heap corruption.
            if (io_context_)
            {
                try
                {
                    io_context_->restart();
                    io_context_->poll();
                }
                catch (...)
                {
                    // Ignore exceptions during cleanup
                }
            }
            // Step 6: NOW it's safe to clear sessions - all async operations are done
            {
                std::lock_guard<std::mutex> lock(sessions_mutex_);
                sessions_.clear();
            }
            // Step 7: Release resources explicitly to ensure cleanup
            acceptor_.reset();
            cleanup_timer_.reset();
            io_context_.reset();
            NETWORK_LOG_INFO("[messaging_server] Stopped.");
            return ok();
        }
        catch (const std::exception& e)
        {
            return error_void(
                error_codes::common_errors::internal_error,
                "Failed to stop server: " + std::string(e.what()),
                "messaging_server::do_stop",
                "Server ID: " + server_id()
            );
        }
    }
References kcenon::network::error_void(), kcenon::network::integration::io_context_thread_manager::instance(), kcenon::network::error_codes::common_errors::internal_error, NETWORK_LOG_INFO, kcenon::network::ok(), and kcenon::network::integration::io_context_thread_manager::stop_io_context().
get_connection_callback()
auto kcenon::network::core::messaging_server::get_connection_callback () const -> connection_callback_t private
Gets a copy of the connection callback.
Returns
Copy of the connection callback (may be empty).
Definition at line 187 of file messaging_server.cpp.
    {
        return callbacks_.get<to_index(callback_index::connection)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
get_disconnection_callback()
auto kcenon::network::core::messaging_server::get_disconnection_callback () const -> disconnection_callback_t private
Gets a copy of the disconnection callback.
Returns
Copy of the disconnection callback (may be empty).
Definition at line 192 of file messaging_server.cpp.
    {
        return callbacks_.get<to_index(callback_index::disconnection)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
get_error_callback()
auto kcenon::network::core::messaging_server::get_error_callback () const -> error_callback_t private
Gets a copy of the error callback.
Returns
Copy of the error callback (may be empty).
Definition at line 202 of file messaging_server.cpp.
    {
        return callbacks_.get<to_index(callback_index::error)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
get_receive_callback()
auto kcenon::network::core::messaging_server::get_receive_callback () const -> receive_callback_t private
Gets a copy of the receive callback.
Returns
Copy of the receive callback (may be empty).
Definition at line 197 of file messaging_server.cpp.
    {
        return callbacks_.get<to_index(callback_index::receive)>();
    }
References callbacks_, kcenon::network::utils::callback_manager< CallbackTypes >::get(), and kcenon::network::to_index().
invoke_connection_callback()
auto kcenon::network::core::messaging_server::invoke_connection_callback (std::shared_ptr< session::messaging_session > session) -> void private
Invokes the connection callback with the given session.
Parameters
session The newly connected session.
Definition at line 207 of file messaging_server.cpp.
    {
        callbacks_.invoke<to_index(callback_index::connection)>(std::move(session));
    }
References kcenon::network::to_index().
is_running()
bool kcenon::network::core::messaging_server::is_running () const export noexcept
Check if the server is running.
Returns
true if running, false otherwise
Referenced by ~messaging_server().
on_accept()
auto kcenon::network::core::messaging_server::on_accept (std::error_code ec, asio::ip::tcp::socket socket) -> void private
Handler called when an asynchronous accept finishes.
Parameters
ec The std::error_code indicating success or error.
socket The newly accepted tcp::socket.
If ec is successful and is_running_ is still true, a messaging_session is created and stored, then do_accept() is invoked again to accept the next connection.
Definition at line 422 of file messaging_server.cpp.
    {
        if (!is_running())
        {
            return;
        }
        // Create tracing span for accept operation
        auto span = tracing::is_tracing_enabled()
            ? std::make_optional(tracing::trace_context::create_span("tcp.server.accept"))
            : std::nullopt;
        if (span)
        {
            span->set_attribute("net.transport", "tcp")
                 .set_attribute("server.id", server_id_);
        }
        if (ec)
        {
            if (span)
            {
                span->set_error(ec.message());
            }
            NETWORK_LOG_ERROR("[messaging_server] Accept error: " + ec.message());
#if KCENON_WITH_COMMON_SYSTEM
            // Record connection error
            connection_errors_.fetch_add(1, std::memory_order_relaxed);
            if (monitor_) {
                monitor_->record_metric("connection_errors", static_cast<double>(connection_errors_.load()));
            }
#endif
            // Report metrics
            metrics::metric_reporter::report_connection_failed(ec.message());
            return;
        }
        // Add peer information to span
        if (span)
        {
            try
            {
                auto endpoint = socket.remote_endpoint();
                span->set_attribute("net.peer.ip", endpoint.address().to_string())
                     .set_attribute("net.peer.port", static_cast<int64_t>(endpoint.port()));
            }
            catch (...)
            {
                // Ignore errors getting endpoint info
            }
        }
        // Report successful connection
        metrics::metric_reporter::report_connection_accepted();
        // Cleanup dead sessions before adding new one
        cleanup_dead_sessions();
        // Create a new messaging_session
        auto new_session = std::make_shared<kcenon::network::session::messaging_session>(
            std::move(socket), server_id());
        // Set up session callbacks to forward to server callbacks
        // Use base class getters to avoid direct member access
        auto self = shared_from_this();
        // Get copies of callbacks via thread-safe getters from base class
        auto local_receive_callback = get_receive_callback();
        auto local_disconnection_callback = get_disconnection_callback();
        auto local_error_callback = get_error_callback();
        // Set up callbacks without holding any locks to avoid lock-order-inversion
        // Lambdas use captured local callbacks directly to avoid locking callback_mutex_
        if (local_receive_callback)
        {
            new_session->set_receive_callback(
                [self, new_session, local_receive_callback](const std::vector<uint8_t>& data)
                {
                    // Call the captured callback directly without locking to prevent deadlock
                    local_receive_callback(new_session, data);
                });
        }
        if (local_disconnection_callback)
        {
            new_session->set_disconnection_callback(
                [self, local_disconnection_callback](const std::string& session_id)
                {
                    // Call the captured callback directly without locking to prevent deadlock
                    local_disconnection_callback(session_id);
                });
        }
        if (local_error_callback)
        {
            new_session->set_error_callback(
                [self, new_session, local_error_callback](std::error_code ec)
                {
                    // Call the captured callback directly without locking to prevent deadlock
                    local_error_callback(new_session, ec);
                });
        }
        // Track it in our sessions_ vector (protected by mutex)
        {
            std::lock_guard<std::mutex> lock(sessions_mutex_);
            sessions_.push_back(new_session);
        }
        // Start the session
        new_session->start_session();
        // Invoke connection callback via base class helper
        invoke_connection_callback(new_session);
#if KCENON_WITH_COMMON_SYSTEM
        // Record active connections metric
        {
            std::lock_guard<std::mutex> lock(sessions_mutex_);
            if (monitor_) {
                monitor_->record_metric("active_connections", static_cast<double>(sessions_.size()));
            }
        }
#endif
        // Report active connections to metrics system
        {
            std::lock_guard<std::mutex> lock(sessions_mutex_);
            metrics::metric_reporter::report_active_connections(sessions_.size());
        }
        // Mark span as successful before accepting next connection
        if (span)
        {
            span->set_status(tracing::span_status::ok);
        }
        // Accept next connection
        do_accept();
    }
References kcenon::network::tracing::trace_context::create_span(), kcenon::network::tracing::is_tracing_enabled(), NETWORK_LOG_ERROR, kcenon::network::tracing::ok, kcenon::network::metrics::metric_reporter::report_active_connections(), kcenon::network::metrics::metric_reporter::report_connection_accepted(), and kcenon::network::metrics::metric_reporter::report_connection_failed().
on_stopped()
auto kcenon::network::core::messaging_server::on_stopped () -> void private
Called after stop operation completes. No-op for server (no disconnection callback at server level).
Definition at line 147 of file messaging_server.cpp.
    {
        // No-op for server - no disconnection callback at server level
    }
operator=() [1/4]
messaging_server & kcenon::network::core::messaging_server::operator= (const messaging_server &) delete
operator=() [2/4]
messaging_server & kcenon::network::core::messaging_server::operator= (const messaging_server &) export delete
operator=() [3/4]
messaging_server & kcenon::network::core::messaging_server::operator= (messaging_server &&) export noexcept
operator=() [4/4]
messaging_server & kcenon::network::core::messaging_server::operator= (messaging_server &&) delete
send_to() [1/2]
bool kcenon::network::core::messaging_server::send_to (std::string_view session_id, std::span< const uint8_t > data) export
Send data to a specific client.
Parameters
session_id The target client's session ID
data The data to send
Returns
true if data was queued for sending
send_to() [2/2]
bool kcenon::network::core::messaging_server::send_to (std::string_view session_id, std::string_view data) export
Send data to a specific client.
Parameters
session_id The target client's session ID
data The string data to send
Returns
true if data was queued for sending
server_id() [1/2]
auto kcenon::network::core::messaging_server::server_id () const -> const std::string&
Returns the server identifier.
Returns
The server_id string.
Definition at line 154 of file messaging_server.cpp.
    {
        return server_id_;
    }
References server_id_.
server_id() [2/2]
std::string_view kcenon::network::core::messaging_server::server_id () const export noexcept
Get the server identifier.
Returns
Server ID string
set_client_connected_callback()
void kcenon::network::core::messaging_server::set_client_connected_callback (client_connected_callback callback) export
Set client connected callback.
Parameters
callback Function to call when a client connects
set_client_data_callback()
void kcenon::network::core::messaging_server::set_client_data_callback (client_data_callback callback) export
Set client data callback.
Parameters
callback Function to call when data is received from a client
set_client_disconnected_callback()
void kcenon::network::core::messaging_server::set_client_disconnected_callback (client_disconnected_callback callback) export
Set client disconnected callback.
Parameters
callback Function to call when a client disconnects
set_connection_callback()
auto kcenon::network::core::messaging_server::set_connection_callback (connection_callback_t callback) -> void
Sets the callback for new client connections.
Parameters
callback Function called when a client connects.
Definition at line 163 of file messaging_server.cpp.
    {
        callbacks_.set<to_index(callback_index::connection)>(std::move(callback));
    }
References kcenon::network::to_index().
set_disconnection_callback()
auto kcenon::network::core::messaging_server::set_disconnection_callback (disconnection_callback_t callback) -> void
Sets the callback for client disconnections.
Parameters
callback Function called when a client disconnects.
Definition at line 168 of file messaging_server.cpp.
    {
        callbacks_.set<to_index(callback_index::disconnection)>(std::move(callback));
    }
References kcenon::network::to_index().
set_error_callback() [1/2]
void kcenon::network::core::messaging_server::set_error_callback (error_callback callback) export
Set error callback.
Parameters
callback Function to call on errors
set_error_callback() [2/2]
auto kcenon::network::core::messaging_server::set_error_callback (error_callback_t callback) -> void
Sets the callback for session errors.
Parameters
callback Function called when an error occurs on a session.
Definition at line 178 of file messaging_server.cpp.
    {
        callbacks_.set<to_index(callback_index::error)>(std::move(callback));
    }
References kcenon::network::to_index().
set_receive_callback()
auto kcenon::network::core::messaging_server::set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received messages.
Parameters
callback Function called when data is received from a client.
Definition at line 173 of file messaging_server.cpp.
    {
        callbacks_.set<to_index(callback_index::receive)>(std::move(callback));
    }
References kcenon::network::to_index().
start_cleanup_timer()
auto kcenon::network::core::messaging_server::start_cleanup_timer () -> void private
Starts a periodic timer that triggers session cleanup.
The cleanup timer runs every 30 seconds and calls cleanup_dead_sessions() to remove stopped sessions from the vector.
Definition at line 587 of file messaging_server.cpp.
    {
        if (!cleanup_timer_ || !is_running())
        {
            return;
        }
        // Schedule cleanup every 30 seconds
        cleanup_timer_->expires_after(std::chrono::seconds(30));
        auto self = shared_from_this();
        cleanup_timer_->async_wait(
            [this, self](const std::error_code& ec)
            {
                if (!ec && is_running())
                {
                    cleanup_dead_sessions();
                    start_cleanup_timer(); // Reschedule
                }
            }
        );
    }
start_server() [1/3]
bool kcenon::network::core::messaging_server::start_server (std::string_view address, uint16_t port, int backlog = 128) export
Start the server on a specific interface.
Parameters
address The interface address to bind to
port The port to listen on
backlog The listen backlog size
Returns
true if server started successfully
start_server() [2/3]
bool kcenon::network::core::messaging_server::start_server (uint16_t port, int backlog = 128) export
Start the server on a specified port.
Parameters
port The port to listen on
backlog The listen backlog size
Returns
true if server started successfully
start_server() [3/3]
auto kcenon::network::core::messaging_server::start_server (unsigned short port) -> VoidResult
Starts the server on the specified port.
Parameters
port The port to listen on.
Returns
Result<void> - Success if server started, or error with code:
error_codes::network_system::server_already_running if already running
error_codes::network_system::bind_failed if port binding failed
error_codes::common_errors::internal_error for other failures
Definition at line 108 of file messaging_server.cpp.
    {
        // Create tracing span for server start operation
        auto span = tracing::is_tracing_enabled()
            ? std::make_optional(tracing::trace_context::create_span("tcp.server.start"))
            : std::nullopt;
        if (span)
        {
            span->set_attribute("net.host.port", static_cast<int64_t>(port))
                 .set_attribute("net.transport", "tcp")
                 .set_attribute("server.id", server_id_);
        }
        // Use base class do_start which handles lifecycle management
        auto result = do_start(port);
        if (result.is_err())
        {
            if (span)
            {
                span->set_error(result.error().message);
            }
        }
        else
        {
            if (span)
            {
                span->set_status(tracing::span_status::ok);
            }
        }
        return result;
    }
References kcenon::network::tracing::trace_context::create_span(), kcenon::network::tracing::is_tracing_enabled(), and kcenon::network::tracing::ok.
stop_server() [1/2]
void kcenon::network::core::messaging_server::stop_server () export
Stop the server and disconnect all clients.
stop_server() [2/2]
auto kcenon::network::core::messaging_server::stop_server () -> VoidResult
Stops the server and closes all connections.
Returns
Result<void> - Success if server stopped, or error with code:
error_codes::network_system::server_not_started if not running
error_codes::common_errors::internal_error for other failures
Definition at line 141 of file messaging_server.cpp.
    {
        // Use base class do_stop which handles lifecycle management and calls on_stopped()
        return do_stop();
    }
Referenced by ~messaging_server().
wait_for_stop()
bool kcenon::network::core::messaging_server::wait_for_stop (std::chrono::milliseconds timeout = std::chrono::milliseconds(5000)) export
Wait for the server to stop.
Parameters
timeout Maximum wait time
Returns
true if stopped within timeout
Friends And Related Symbol Documentation
utils::startable_base< messaging_server >
friend class utils::startable_base< messaging_server > friend
Definition at line 1 of file messaging_server.h.
Member Data Documentation
acceptor_
std::unique_ptr<asio::ip::tcp::acceptor> kcenon::network::core::messaging_server::acceptor_ private
Acceptor to listen for new connections.
Definition at line 374 of file messaging_server.h.
Referenced by ~messaging_server().
acceptor_mutex_
std::mutex kcenon::network::core::messaging_server::acceptor_mutex_ mutable private
Mutex protecting access to acceptor_ for thread-safe operations.
Definition at line 393 of file messaging_server.h.
Referenced by ~messaging_server().
callbacks_
callbacks_t kcenon::network::core::messaging_server::callbacks_ private
Callback manager.
Definition at line 367 of file messaging_server.h.
Referenced by get_connection_callback(), get_disconnection_callback(), get_error_callback(), and get_receive_callback().
cleanup_timer_
std::unique_ptr<asio::steady_timer> kcenon::network::core::messaging_server::cleanup_timer_ private
Timer for periodic cleanup of stopped sessions.
Definition at line 398 of file messaging_server.h.
Referenced by ~messaging_server().
io_context_
std::shared_ptr<asio::io_context> kcenon::network::core::messaging_server::io_context_ private
The I/O context for async ops.
Definition at line 370 of file messaging_server.h.
Referenced by ~messaging_server().
io_context_future_
std::future<void> kcenon::network::core::messaging_server::io_context_future_ private
Future for the io_context run task.
Definition at line 376 of file messaging_server.h.
pimpl_
std::unique_ptr<impl> kcenon::network::core::messaging_server::pimpl_ export private
Definition at line 380 of file tcp.cppm.
server_id_
std::string kcenon::network::core::messaging_server::server_id_ private
Server identifier.
Definition at line 365 of file messaging_server.h.
Referenced by server_id().
sessions_
std::vector<std::shared_ptr<kcenon::network::session::messaging_session> > kcenon::network::core::messaging_server::sessions_ private
Holds all active sessions. When stop_server() is invoked, each session's stop_session() is called and they are cleared.
Definition at line 383 of file messaging_server.h.
sessions_mutex_
std::mutex kcenon::network::core::messaging_server::sessions_mutex_ private
Mutex protecting access to sessions_ vector.
Definition at line 388 of file messaging_server.h.
work_guard_
std::unique_ptr<asio::executor_work_guard<asio::io_context::executor_type> > kcenon::network::core::messaging_server::work_guard_ private
Keeps io_context running.
Definition at line 372 of file messaging_server.h.
Referenced by ~messaging_server().
The documentation for this class was generated from the following files:
src/internal/core/messaging_server.h
src/modules/tcp.cppm
src/core/messaging_server.cpp