Network System: kcenon::network::core::reliable_udp_client::impl Class Reference
kcenon::network::core::reliable_udp_client::impl Class Reference
Public Member Functions
impl (std::string_view client_id, reliability_mode mode)
~impl () noexcept
auto start_client (std::string_view host, uint16_t port) -> VoidResult
auto stop_client () -> VoidResult
auto send_packet (std::vector< uint8_t > &&data) -> VoidResult
auto wait_for_stop () -> void
auto set_receive_callback (std::function< void(const std::vector< uint8_t > &)> callback) -> void
auto set_error_callback (std::function< void(std::error_code)> callback) -> void
auto set_congestion_window (size_t packets) -> void
auto set_max_retries (size_t retries) -> void
auto set_retransmission_timeout (uint32_t timeout_ms) -> void
auto get_stats () const -> reliable_udp_stats
auto is_running () const -> bool
auto client_id () const -> const std::string &
auto mode () const -> reliability_mode
auto shared_from_this () -> std::shared_ptr< impl >
Private Member Functions
auto send_unreliable (std::vector< uint8_t > &&data) -> VoidResult
auto send_reliable (std::vector< uint8_t > &&data) -> VoidResult
auto send_sequenced (std::vector< uint8_t > &&data) -> VoidResult
auto create_packet (const packet_header &header, const std::vector< uint8_t > &payload) -> std::vector< uint8_t >
auto handle_received_packet (const std::vector< uint8_t > &data) -> void
auto handle_ack (uint32_t ack_number) -> void
auto send_ack (uint32_t sequence_number) -> void
auto handle_ordered_delivery (uint32_t sequence_number, std::vector< uint8_t > &&payload) -> void
auto handle_sequenced_delivery (uint32_t sequence_number, std::vector< uint8_t > &&payload) -> void
auto deliver_to_application (std::vector< uint8_t > &&payload) -> void
auto handle_error (std::error_code ec) -> void
auto start_retransmission_timer () -> void
auto stop_retransmission_timer () -> void
auto check_and_retransmit () -> void
Private Attributes
std::string client_id_
reliability_mode mode_
std::atomic< bool > is_running_ {false}
std::shared_ptr< messaging_udp_client > udp_client_
std::atomic< uint32_t > next_sequence_ {1}
std::atomic< uint32_t > expected_sequence_ {1}
std::mutex pending_mutex_
std::map< uint32_t, packet_info > pending_packets_
std::mutex receive_mutex_
std::map< uint32_t, std::vector< uint8_t > > receive_buffer_
std::mutex callback_mutex_
std::function< void(const std::vector< uint8_t > &)> receive_callback_
std::function< void(std::error_code)> error_callback_
size_t congestion_window_ {32}
size_t max_retries_ {5}
uint32_t retransmission_timeout_ms_ {200}
std::mutex stats_mutex_
reliable_udp_stats stats_
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::future< void > retransmission_future_
std::atomic< bool > stop_retransmission_ {false}
std::mutex state_mutex_
Detailed Description
Definition at line 62 of file reliable_udp_client.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::core::reliable_udp_client::impl::impl (std::string_view client_id, reliability_mode mode) inline
Definition at line 65 of file reliable_udp_client.cpp.
            : client_id_(client_id), mode_(mode), next_sequence_(1), expected_sequence_(1)
        {
            NETWORK_LOG_DEBUG("[reliable_udp_client::" + client_id_ +
                              "] Created with mode=" + std::to_string(static_cast<int>(mode)));
        }
References client_id_, mode(), and NETWORK_LOG_DEBUG.
~impl()
kcenon::network::core::reliable_udp_client::impl::~impl () inline noexcept
Definition at line 72 of file reliable_udp_client.cpp.
        {
            if (is_running_.load())
            {
                (void)stop_client();
            }
        }
References is_running_, and stop_client().
Member Function Documentation
check_and_retransmit()
auto kcenon::network::core::reliable_udp_client::impl::check_and_retransmit () -> void inline private
Definition at line 586 of file reliable_udp_client.cpp.
        {
            std::lock_guard<std::mutex> lock(pending_mutex_);
            auto now = std::chrono::steady_clock::now();
            for (auto it = pending_packets_.begin(); it != pending_packets_.end();)
            {
                auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
                                   now - it->second.send_time)
                                   .count();
                if (elapsed >= retransmission_timeout_ms_)
                {
                    // Check max retries
                    if (it->second.retransmit_count >= max_retries_)
                    {
                        NETWORK_LOG_WARN("[reliable_udp_client::" + client_id_ +
                                         "] Packet seq=" + std::to_string(it->first) +
                                         " exceeded max retries, dropping");
{
                            std::lock_guard<std::mutex> stats_lock(stats_mutex_);
                            stats_.packets_dropped++;
                        }
                        it = pending_packets_.erase(it);
                        continue;
                    }
                    // Retransmit
                    auto packet_copy = it->second.data;
                    it->second.send_time = now;
                    it->second.retransmit_count++;
                    {
                        std::lock_guard<std::mutex> stats_lock(stats_mutex_);
                        stats_.packets_retransmitted++;
                    }
                    NETWORK_LOG_TRACE("[reliable_udp_client::" + client_id_ +
                                      "] Retransmitting seq=" + std::to_string(it->first) +
                                      " (attempt " + std::to_string(it->second.retransmit_count) +
                                      ")");
                    udp_client_->send(std::move(packet_copy),
                                             [](std::error_code, std::size_t) {});
                }
                ++it;
            }
        }
References client_id_, max_retries_, NETWORK_LOG_TRACE, NETWORK_LOG_WARN, kcenon::network::core::reliable_udp_stats::packets_dropped, kcenon::network::core::reliable_udp_stats::packets_retransmitted, pending_mutex_, pending_packets_, retransmission_timeout_ms_, stats_, stats_mutex_, and udp_client_.
Referenced by start_retransmission_timer().
client_id()
auto kcenon::network::core::reliable_udp_client::impl::client_id () const -> const std::string& inline
Definition at line 222 of file reliable_udp_client.cpp.
{ return client_id_; }
References client_id_.
Referenced by kcenon::network::core::reliable_udp_client::client_id().
create_packet()
auto kcenon::network::core::reliable_udp_client::impl::create_packet (const packet_header & header, const std::vector< uint8_t > & payload) -> std::vector<uint8_t> inline private
Definition at line 328 of file reliable_udp_client.cpp.
        {
            std::vector<uint8_t> packet(sizeof(packet_header) + payload.size());
            std::memcpy(packet.data(), &header, sizeof(packet_header));
            if (!payload.empty())
            {
                std::memcpy(packet.data() + sizeof(packet_header), payload.data(),
                            payload.size());
            }
            return packet;
        }
Referenced by send_ack(), send_reliable(), send_sequenced(), and send_unreliable().
deliver_to_application()
auto kcenon::network::core::reliable_udp_client::impl::deliver_to_application (std::vector< uint8_t > && payload) -> void inline private
Definition at line 525 of file reliable_udp_client.cpp.
        {
            std::lock_guard<std::mutex> lock(callback_mutex_);
            if (receive_callback_)
            {
                receive_callback_(payload);
            }
        }
References callback_mutex_, and receive_callback_.
Referenced by handle_ordered_delivery(), handle_received_packet(), and handle_sequenced_delivery().
get_stats()
auto kcenon::network::core::reliable_udp_client::impl::get_stats () const -> reliable_udp_stats inline
Definition at line 214 of file reliable_udp_client.cpp.
        {
            std::lock_guard<std::mutex> lock(stats_mutex_);
            return stats_;
        }
References stats_, and stats_mutex_.
Referenced by kcenon::network::core::reliable_udp_client::get_stats().
handle_ack()
auto kcenon::network::core::reliable_udp_client::impl::handle_ack (uint32_t ack_number) -> void inline private
Definition at line 402 of file reliable_udp_client.cpp.
        {
            std::lock_guard<std::mutex> lock(pending_mutex_);
            auto it = pending_packets_.find(ack_number);
            if (it != pending_packets_.end())
            {
                // Calculate RTT
                auto now = std::chrono::steady_clock::now();
                auto rtt = std::chrono::duration_cast<std::chrono::milliseconds>(
                               now - it->second.send_time)
                               .count();
                // Update stats
                {
                    std::lock_guard<std::mutex> stats_lock(stats_mutex_);
                    stats_.acks_received++;
                    // Update average RTT (exponential moving average)
                    if (stats_.average_rtt_ms == 0.0)
                    {
                        stats_.average_rtt_ms = static_cast<double>(rtt);
                    }
                    else
                    {
                        stats_.average_rtt_ms = 0.875 * stats_.average_rtt_ms + 0.125 * rtt;
                    }
                }
                // Remove from pending
                pending_packets_.erase(it);
                NETWORK_LOG_TRACE("[reliable_udp_client::" + client_id_ + "] Received ACK for seq=" +
                                  std::to_string(ack_number) + ", RTT=" + std::to_string(rtt) + "ms");
            }
        }
References kcenon::network::core::reliable_udp_stats::acks_received, kcenon::network::core::reliable_udp_stats::average_rtt_ms, client_id_, NETWORK_LOG_TRACE, pending_mutex_, pending_packets_, stats_, and stats_mutex_.
Referenced by handle_received_packet().
handle_error()
auto kcenon::network::core::reliable_udp_client::impl::handle_error (std::error_code ec) -> void inline private
Definition at line 535 of file reliable_udp_client.cpp.
        {
            NETWORK_LOG_ERROR("[reliable_udp_client::" + client_id_ + "] Error: " + ec.message());
            std::lock_guard<std::mutex> lock(callback_mutex_);
            if (error_callback_)
            {
                error_callback_(ec);
            }
        }
References callback_mutex_, client_id_, error_callback_, and NETWORK_LOG_ERROR.
Referenced by start_client().
handle_ordered_delivery()
auto kcenon::network::core::reliable_udp_client::impl::handle_ordered_delivery (uint32_t sequence_number, std::vector< uint8_t > && payload) -> void inline private
Definition at line 460 of file reliable_udp_client.cpp.
        {
            std::lock_guard<std::mutex> lock(receive_mutex_);
            if (sequence_number == expected_sequence_)
            {
                // Deliver in-order packet
                deliver_to_application(std::move(payload));
                expected_sequence_++;
                // Deliver any buffered packets that are now in order
                while (true)
                {
                    auto it = receive_buffer_.find(expected_sequence_);
                    if (it == receive_buffer_.end())
                    {
                        break;
                    }
                    deliver_to_application(std::move(it->second));
                    receive_buffer_.erase(it);
                    expected_sequence_++;
                }
            }
            else if (sequence_number > expected_sequence_)
            {
                // Buffer out-of-order packet
                receive_buffer_[sequence_number] = std::move(payload);
                NETWORK_LOG_TRACE("[reliable_udp_client::" + client_id_ +
                                  "] Buffered out-of-order packet seq=" +
                                  std::to_string(sequence_number) +
                                  " (expected=" + std::to_string(expected_sequence_) + ")");
            }
            else
            {
                // Duplicate or old packet, ignore
                NETWORK_LOG_TRACE("[reliable_udp_client::" + client_id_ +
                                  "] Dropped old packet seq=" + std::to_string(sequence_number));
            }
        }
References client_id_, deliver_to_application(), expected_sequence_, NETWORK_LOG_TRACE, receive_buffer_, and receive_mutex_.
Referenced by handle_received_packet().
handle_received_packet()
auto kcenon::network::core::reliable_udp_client::impl::handle_received_packet (const std::vector< uint8_t > & data) -> void inline private
Definition at line 342 of file reliable_udp_client.cpp.
        {
            if (data.size() < sizeof(packet_header))
            {
                NETWORK_LOG_WARN("[reliable_udp_client::" + client_id_ +
                                 "] Received invalid packet (too small)");
                return;
            }
            packet_header header{};
            std::memcpy(&header, data.data(), sizeof(packet_header));
            // Handle ACK packet
            if (header.flags & packet_header::FLAG_ACK)
            {
                handle_ack(header.ack_number);
                return;
            }
            // Handle data packet
            if (header.flags & packet_header::FLAG_DATA)
            {
                // Send ACK for reliable modes
                if (mode_ == reliability_mode::reliable_ordered ||
                    mode_ == reliability_mode::reliable_unordered)
                {
                    send_ack(header.sequence_number);
                }
                // Extract payload
                std::vector<uint8_t> payload(data.begin() + sizeof(packet_header), data.end());
                // Process based on mode
                switch (mode_)
                {
                case reliability_mode::unreliable:
                    deliver_to_application(std::move(payload));
                    break;
                case reliability_mode::reliable_ordered:
                    handle_ordered_delivery(header.sequence_number, std::move(payload));
                    break;
                case reliability_mode::reliable_unordered:
                    deliver_to_application(std::move(payload));
                    break;
                case reliability_mode::sequenced:
                    handle_sequenced_delivery(header.sequence_number, std::move(payload));
                    break;
                }
                {
                    std::lock_guard<std::mutex> lock(stats_mutex_);
                    stats_.packets_received++;
                }
            }
        }
References client_id_, deliver_to_application(), kcenon::network::core::packet_header::FLAG_ACK, kcenon::network::core::packet_header::FLAG_DATA, handle_ack(), handle_ordered_delivery(), handle_sequenced_delivery(), mode_, NETWORK_LOG_WARN, kcenon::network::core::reliable_udp_stats::packets_received, kcenon::network::core::reliable_ordered, kcenon::network::core::reliable_unordered, send_ack(), kcenon::network::core::sequenced, stats_, stats_mutex_, and kcenon::network::core::unreliable.
Referenced by start_client().
handle_sequenced_delivery()
auto kcenon::network::core::reliable_udp_client::impl::handle_sequenced_delivery (uint32_t sequence_number, std::vector< uint8_t > && payload) -> void inline private
Definition at line 504 of file reliable_udp_client.cpp.
        {
            if (sequence_number >= expected_sequence_)
            {
                expected_sequence_ = sequence_number + 1;
                deliver_to_application(std::move(payload));
            }
            else
            {
                // Drop old packet
                std::lock_guard<std::mutex> lock(stats_mutex_);
                stats_.packets_dropped++;
                NETWORK_LOG_TRACE("[reliable_udp_client::" + client_id_ +
                                  "] Dropped old packet in sequenced mode seq=" +
                                  std::to_string(sequence_number));
            }
        }
References client_id_, deliver_to_application(), expected_sequence_, NETWORK_LOG_TRACE, kcenon::network::core::reliable_udp_stats::packets_dropped, stats_, and stats_mutex_.
Referenced by handle_received_packet().
is_running()
auto kcenon::network::core::reliable_udp_client::impl::is_running () const -> bool inline
Definition at line 220 of file reliable_udp_client.cpp.
{ return is_running_.load(); }
References is_running_.
Referenced by kcenon::network::core::reliable_udp_client::is_running().
mode()
auto kcenon::network::core::reliable_udp_client::impl::mode () const -> reliability_mode inline
Definition at line 224 of file reliable_udp_client.cpp.
{ return mode_; }
References mode_.
Referenced by impl(), and kcenon::network::core::reliable_udp_client::mode().
send_ack()
auto kcenon::network::core::reliable_udp_client::impl::send_ack (uint32_t sequence_number) -> void inline private
Definition at line 440 of file reliable_udp_client.cpp.
        {
            packet_header header{};
            header.sequence_number = 0;
            header.ack_number = sequence_number;
            header.flags = packet_header::FLAG_ACK;
            header.data_length = 0;
            auto packet = create_packet(header, {});
            udp_client_->send(std::move(packet), [this](std::error_code ec, std::size_t) {
                if (!ec)
                {
                    std::lock_guard<std::mutex> lock(stats_mutex_);
                    stats_.acks_sent++;
                }
            });
        }
References kcenon::network::core::reliable_udp_stats::acks_sent, create_packet(), kcenon::network::core::packet_header::FLAG_ACK, kcenon::network::core::packet_header::sequence_number, stats_, stats_mutex_, and udp_client_.
Referenced by handle_received_packet().
send_packet()
auto kcenon::network::core::reliable_udp_client::impl::send_packet (std::vector< uint8_t > && data) -> VoidResult inline
Definition at line 160 of file reliable_udp_client.cpp.
        {
            if (!is_running_.load())
            {
                return error_void(error_codes::common_errors::internal_error,
                                  "Client is not running");
            }
            switch (mode_)
            {
            case reliability_mode::unreliable:
                return send_unreliable(std::move(data));
            case reliability_mode::reliable_ordered:
            case reliability_mode::reliable_unordered:
                return send_reliable(std::move(data));
            case reliability_mode::sequenced:
                return send_sequenced(std::move(data));
            }
            return error_void(error_codes::common_errors::internal_error, "Invalid reliability mode");
        }
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, is_running_, mode_, kcenon::network::core::reliable_ordered, kcenon::network::core::reliable_unordered, send_reliable(), send_sequenced(), send_unreliable(), kcenon::network::core::sequenced, and kcenon::network::core::unreliable.
send_reliable()
auto kcenon::network::core::reliable_udp_client::impl::send_reliable (std::vector< uint8_t > && data) -> VoidResult inline private
Definition at line 258 of file reliable_udp_client.cpp.
        {
            std::lock_guard<std::mutex> lock(pending_mutex_);
            // Check congestion window
            if (pending_packets_.size() >= congestion_window_)
            {
                return error_void(error_codes::common_errors::internal_error,
                                  "Congestion window full");
            }
            uint32_t seq = next_sequence_++;
            packet_header header{};
            header.sequence_number = seq;
            header.ack_number = 0;
            header.flags = packet_header::FLAG_DATA;
            header.data_length = static_cast<uint16_t>(data.size());
            auto packet = create_packet(header, data);
            // Store for retransmission
            packet_info info{};
            info.data = packet;
            info.send_time = std::chrono::steady_clock::now();
            info.retransmit_count = 0;
            info.sequence_number = seq;
            pending_packets_[seq] = std::move(info);
            // Send packet
            return udp_client_->send(
                std::move(packet), [this, seq](std::error_code ec, std::size_t) {
                    if (!ec)
                    {
                        std::lock_guard<std::mutex> lock(stats_mutex_);
                        stats_.packets_sent++;
                    }
                    else
                    {
                        // Remove from pending if send failed
                        std::lock_guard<std::mutex> pending_lock(pending_mutex_);
                        pending_packets_.erase(seq);
                    }
                });
        }
References congestion_window_, create_packet(), kcenon::network::error_void(), kcenon::network::core::packet_header::FLAG_DATA, kcenon::network::error_codes::common_errors::internal_error, next_sequence_, kcenon::network::core::reliable_udp_stats::packets_sent, pending_mutex_, pending_packets_, kcenon::network::core::packet_header::sequence_number, stats_, stats_mutex_, and udp_client_.
Referenced by send_packet().
send_sequenced()
auto kcenon::network::core::reliable_udp_client::impl::send_sequenced (std::vector< uint8_t > && data) -> VoidResult inline private
Definition at line 305 of file reliable_udp_client.cpp.
        {
            uint32_t seq = next_sequence_++;
            packet_header header{};
            header.sequence_number = seq;
            header.ack_number = 0;
            header.flags = packet_header::FLAG_DATA;
            header.data_length = static_cast<uint16_t>(data.size());
            auto packet = create_packet(header, data);
            return udp_client_->send(
                std::move(packet), [this](std::error_code ec, std::size_t) {
                    if (!ec)
                    {
                        std::lock_guard<std::mutex> lock(stats_mutex_);
                        stats_.packets_sent++;
                    }
                });
        }
References create_packet(), kcenon::network::core::packet_header::FLAG_DATA, next_sequence_, kcenon::network::core::reliable_udp_stats::packets_sent, kcenon::network::core::packet_header::sequence_number, stats_, stats_mutex_, and udp_client_.
Referenced by send_packet().
send_unreliable()
auto kcenon::network::core::reliable_udp_client::impl::send_unreliable (std::vector< uint8_t > && data) -> VoidResult inline private
Definition at line 237 of file reliable_udp_client.cpp.
        {
            packet_header header{};
            header.sequence_number = 0;
            header.ack_number = 0;
            header.flags = packet_header::FLAG_DATA;
            header.data_length = static_cast<uint16_t>(data.size());
            auto packet = create_packet(header, data);
            return udp_client_->send(
                std::move(packet), [this](std::error_code ec, std::size_t) {
                    if (!ec)
                    {
                        std::lock_guard<std::mutex> lock(stats_mutex_);
                        stats_.packets_sent++;
                    }
                });
        }
References create_packet(), kcenon::network::core::packet_header::FLAG_DATA, kcenon::network::core::reliable_udp_stats::packets_sent, kcenon::network::core::packet_header::sequence_number, stats_, stats_mutex_, and udp_client_.
Referenced by send_packet().
set_congestion_window()
auto kcenon::network::core::reliable_udp_client::impl::set_congestion_window (size_t packets) -> void inline
Definition at line 205 of file reliable_udp_client.cpp.
{ congestion_window_ = packets; }
References congestion_window_.
set_error_callback()
auto kcenon::network::core::reliable_udp_client::impl::set_error_callback (std::function< void(std::error_code)> callback) -> void inline
Definition at line 199 of file reliable_udp_client.cpp.
        {
            std::lock_guard<std::mutex> lock(callback_mutex_);
            error_callback_ = std::move(callback);
        }
References callback_mutex_, and error_callback_.
set_max_retries()
auto kcenon::network::core::reliable_udp_client::impl::set_max_retries (size_t retries) -> void inline
Definition at line 207 of file reliable_udp_client.cpp.
{ max_retries_ = retries; }
References max_retries_.
set_receive_callback()
auto kcenon::network::core::reliable_udp_client::impl::set_receive_callback (std::function< void(const std::vector< uint8_t > &)> callback) -> void inline
Definition at line 192 of file reliable_udp_client.cpp.
        {
            std::lock_guard<std::mutex> lock(callback_mutex_);
            receive_callback_ = std::move(callback);
        }
References callback_mutex_, and receive_callback_.
set_retransmission_timeout()
auto kcenon::network::core::reliable_udp_client::impl::set_retransmission_timeout (uint32_t timeout_ms) -> void inline
Definition at line 209 of file reliable_udp_client.cpp.
        {
            retransmission_timeout_ms_ = timeout_ms;
        }
References retransmission_timeout_ms_.
shared_from_this()
auto kcenon::network::core::reliable_udp_client::impl::shared_from_this () -> std::shared_ptr<impl> inline
Definition at line 226 of file reliable_udp_client.cpp.
        {
            // This is called from impl, not from reliable_udp_client
            // We need to be careful about the shared_ptr lifetime
            return std::shared_ptr<impl>(this, [](impl*) {
                // No-op deleter since we don't own the impl
            });
        }
Referenced by start_client().
start_client()
auto kcenon::network::core::reliable_udp_client::impl::start_client (std::string_view host, uint16_t port) -> VoidResult inline
Definition at line 80 of file reliable_udp_client.cpp.
        {
            std::lock_guard<std::mutex> lock(state_mutex_);
            if (is_running_.load())
            {
                return error_void(error_codes::common_errors::already_exists,
                                  "Client is already running");
            }
            // Create underlying UDP client
            udp_client_ = std::make_shared<messaging_udp_client>(client_id_);
            // Set receive callback
            udp_client_->set_receive_callback(
                [this, self = shared_from_this()](const std::vector<uint8_t>& data,
                                                  const asio::ip::udp::endpoint&) {
                    handle_received_packet(data);
                });
            // Set error callback
            udp_client_->set_error_callback([this, self = shared_from_this()](
                                                std::error_code ec) { handle_error(ec); });
            // Start UDP client
            auto result = udp_client_->start_client(host, port);
            if (result.is_err())
            {
                return result;
            }
            is_running_.store(true);
            // Start retransmission timer for reliable modes
            if (mode_ != reliability_mode::unreliable)
            {
                start_retransmission_timer();
            }
            NETWORK_LOG_INFO("[reliable_udp_client::" + client_id_ + "] Started successfully");
            return ok();
        }
References kcenon::network::error_codes::common_errors::already_exists, client_id_, kcenon::network::error_void(), handle_error(), handle_received_packet(), is_running_, mode_, NETWORK_LOG_INFO, kcenon::network::ok(), shared_from_this(), start_retransmission_timer(), state_mutex_, udp_client_, and kcenon::network::core::unreliable.
start_retransmission_timer()
auto kcenon::network::core::reliable_udp_client::impl::start_retransmission_timer () -> void inline private
Definition at line 547 of file reliable_udp_client.cpp.
        {
            thread_pool_ = network_context::instance().get_thread_pool();
            if (!thread_pool_) {
                NETWORK_LOG_ERROR("[reliable_udp_client::" + client_id_ +
                                  "] Failed to get thread pool for retransmission timer");
                return;
            }
            stop_retransmission_.store(false);
            retransmission_future_ = thread_pool_->submit([this]() {
                while (is_running_.load() && !stop_retransmission_.load())
                {
                    std::this_thread::sleep_for(
                        std::chrono::milliseconds(retransmission_timeout_ms_));
                    if (!stop_retransmission_.load()) {
                        check_and_retransmit();
                    }
                }
            });
        }
References check_and_retransmit(), client_id_, kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), is_running_, NETWORK_LOG_ERROR, retransmission_future_, retransmission_timeout_ms_, stop_retransmission_, and thread_pool_.
Referenced by start_client().
stop_client()
auto kcenon::network::core::reliable_udp_client::impl::stop_client () -> VoidResult inline
Definition at line 123 of file reliable_udp_client.cpp.
        {
            std::lock_guard<std::mutex> lock(state_mutex_);
            if (!is_running_.load())
            {
                return ok();
            }
            is_running_.store(false);
            // Stop retransmission timer
            stop_retransmission_timer();
            // Stop underlying UDP client
            if (udp_client_)
            {
                (void)udp_client_->stop_client();
                udp_client_.reset();
            }
            // Clear pending packets
            {
                std::lock_guard<std::mutex> pending_lock(pending_mutex_);
                pending_packets_.clear();
            }
            // Clear receive buffer
            {
                std::lock_guard<std::mutex> recv_lock(receive_mutex_);
                receive_buffer_.clear();
            }
            NETWORK_LOG_INFO("[reliable_udp_client::" + client_id_ + "] Stopped");
            return ok();
        }
References client_id_, is_running_, NETWORK_LOG_INFO, kcenon::network::ok(), pending_mutex_, pending_packets_, receive_buffer_, receive_mutex_, state_mutex_, stop_retransmission_timer(), and udp_client_.
Referenced by ~impl().
stop_retransmission_timer()
auto kcenon::network::core::reliable_udp_client::impl::stop_retransmission_timer () -> void inline private
Definition at line 570 of file reliable_udp_client.cpp.
        {
            stop_retransmission_.store(true);
            if (retransmission_future_.valid())
            {
                try {
                    retransmission_future_.wait();
                } catch (...) {
                    NETWORK_LOG_ERROR("[reliable_udp_client::" + client_id_ +
                                      "] Exception while waiting for retransmission timer to stop");
                }
            }
            thread_pool_.reset();
        }
References client_id_, NETWORK_LOG_ERROR, retransmission_future_, stop_retransmission_, and thread_pool_.
Referenced by stop_client().
wait_for_stop()
auto kcenon::network::core::reliable_udp_client::impl::wait_for_stop () -> void inline
Definition at line 184 of file reliable_udp_client.cpp.
        {
            if (udp_client_)
            {
                udp_client_->wait_for_stop();
            }
        }
References udp_client_.
Member Data Documentation
callback_mutex_
std::mutex kcenon::network::core::reliable_udp_client::impl::callback_mutex_ mutable private
Definition at line 659 of file reliable_udp_client.cpp.
Referenced by deliver_to_application(), handle_error(), set_error_callback(), and set_receive_callback().
client_id_
std::string kcenon::network::core::reliable_udp_client::impl::client_id_ private
Definition at line 640 of file reliable_udp_client.cpp.
Referenced by check_and_retransmit(), client_id(), handle_ack(), handle_error(), handle_ordered_delivery(), handle_received_packet(), handle_sequenced_delivery(), impl(), start_client(), start_retransmission_timer(), stop_client(), and stop_retransmission_timer().
congestion_window_
size_t kcenon::network::core::reliable_udp_client::impl::congestion_window_ {32} private
Definition at line 664 of file reliable_udp_client.cpp.
{32};
Referenced by send_reliable(), and set_congestion_window().
error_callback_
std::function<void(std::error_code)> kcenon::network::core::reliable_udp_client::impl::error_callback_ private
Definition at line 661 of file reliable_udp_client.cpp.
Referenced by handle_error(), and set_error_callback().
expected_sequence_
std::atomic<uint32_t> kcenon::network::core::reliable_udp_client::impl::expected_sequence_ {1} private
Definition at line 648 of file reliable_udp_client.cpp.
{1};
Referenced by handle_ordered_delivery(), and handle_sequenced_delivery().
is_running_
std::atomic<bool> kcenon::network::core::reliable_udp_client::impl::is_running_ {false} private
Definition at line 643 of file reliable_udp_client.cpp.
{false};
Referenced by is_running(), send_packet(), start_client(), start_retransmission_timer(), stop_client(), and ~impl().
max_retries_
size_t kcenon::network::core::reliable_udp_client::impl::max_retries_ {5} private
Definition at line 665 of file reliable_udp_client.cpp.
{5};
Referenced by check_and_retransmit(), and set_max_retries().
mode_
reliability_mode kcenon::network::core::reliable_udp_client::impl::mode_ private
Definition at line 641 of file reliable_udp_client.cpp.
Referenced by handle_received_packet(), mode(), send_packet(), and start_client().
next_sequence_
std::atomic<uint32_t> kcenon::network::core::reliable_udp_client::impl::next_sequence_ {1} private
Definition at line 647 of file reliable_udp_client.cpp.
{1};
Referenced by send_reliable(), and send_sequenced().
pending_mutex_
std::mutex kcenon::network::core::reliable_udp_client::impl::pending_mutex_ mutable private
Definition at line 651 of file reliable_udp_client.cpp.
Referenced by check_and_retransmit(), handle_ack(), send_reliable(), and stop_client().
pending_packets_
std::map<uint32_t, packet_info> kcenon::network::core::reliable_udp_client::impl::pending_packets_ private
Definition at line 652 of file reliable_udp_client.cpp.
Referenced by check_and_retransmit(), handle_ack(), send_reliable(), and stop_client().
receive_buffer_
std::map<uint32_t, std::vector<uint8_t> > kcenon::network::core::reliable_udp_client::impl::receive_buffer_ private
Definition at line 656 of file reliable_udp_client.cpp.
Referenced by handle_ordered_delivery(), and stop_client().
receive_callback_
std::function<void(const std::vector<uint8_t>&)> kcenon::network::core::reliable_udp_client::impl::receive_callback_ private
Definition at line 660 of file reliable_udp_client.cpp.
Referenced by deliver_to_application(), and set_receive_callback().
receive_mutex_
std::mutex kcenon::network::core::reliable_udp_client::impl::receive_mutex_ mutable private
Definition at line 655 of file reliable_udp_client.cpp.
Referenced by handle_ordered_delivery(), and stop_client().
retransmission_future_
std::future<void> kcenon::network::core::reliable_udp_client::impl::retransmission_future_ private
Definition at line 674 of file reliable_udp_client.cpp.
Referenced by start_retransmission_timer(), and stop_retransmission_timer().
retransmission_timeout_ms_
uint32_t kcenon::network::core::reliable_udp_client::impl::retransmission_timeout_ms_ {200} private
Definition at line 666 of file reliable_udp_client.cpp.
{200};
Referenced by check_and_retransmit(), set_retransmission_timeout(), and start_retransmission_timer().
state_mutex_
std::mutex kcenon::network::core::reliable_udp_client::impl::state_mutex_ private
Definition at line 678 of file reliable_udp_client.cpp.
Referenced by start_client(), and stop_client().
stats_
reliable_udp_stats kcenon::network::core::reliable_udp_client::impl::stats_ private
Definition at line 670 of file reliable_udp_client.cpp.
Referenced by check_and_retransmit(), get_stats(), handle_ack(), handle_received_packet(), handle_sequenced_delivery(), send_ack(), send_reliable(), send_sequenced(), and send_unreliable().
stats_mutex_
std::mutex kcenon::network::core::reliable_udp_client::impl::stats_mutex_ mutable private
Definition at line 669 of file reliable_udp_client.cpp.
Referenced by check_and_retransmit(), get_stats(), handle_ack(), handle_received_packet(), handle_sequenced_delivery(), send_ack(), send_reliable(), send_sequenced(), and send_unreliable().
stop_retransmission_
std::atomic<bool> kcenon::network::core::reliable_udp_client::impl::stop_retransmission_ {false} private
Definition at line 675 of file reliable_udp_client.cpp.
{false};
Referenced by start_retransmission_timer(), and stop_retransmission_timer().
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::reliable_udp_client::impl::thread_pool_ private
Definition at line 673 of file reliable_udp_client.cpp.
Referenced by start_retransmission_timer(), and stop_retransmission_timer().
udp_client_
std::shared_ptr<messaging_udp_client> kcenon::network::core::reliable_udp_client::impl::udp_client_ private
Definition at line 644 of file reliable_udp_client.cpp.
Referenced by check_and_retransmit(), send_ack(), send_reliable(), send_sequenced(), send_unreliable(), start_client(), stop_client(), and wait_for_stop().
The documentation for this class was generated from the following file:
src/experimental/reliable_udp_client.cpp