Network System: kcenon::network::protocols::quic::packet_number Class Reference
kcenon::network::protocols::quic::packet_number Class Reference
QUIC packet number utilities (RFC 9000 Section 17.1)
#include <packet.h>
Static Public Member Functions
static auto encode (uint64_t full_pn, uint64_t largest_acked) -> std::pair< std::vector< uint8_t >, size_t >
Encode a packet number for transmission.
static auto decode (uint64_t truncated_pn, size_t pn_length, uint64_t largest_pn) noexcept -> uint64_t
Decode a packet number from received data.
static auto encoded_length (uint64_t full_pn, uint64_t largest_acked) noexcept -> size_t
Get the minimum number of bytes needed to encode a packet number.
Detailed Description
QUIC packet number utilities (RFC 9000 Section 17.1)
Packet numbers are encoded using a variable-length encoding based on the difference from the largest acknowledged packet number.
Definition at line 201 of file packet.h.
Member Function Documentation
decode()
auto kcenon::network::protocols::quic::packet_number::decode (uint64_t truncated_pn, size_t pn_length, uint64_t largest_pn) -> uint64_t static noexcept
Decode a packet number from received data.
Parameters
truncated_pn Truncated packet number from packet
pn_length Length of the truncated packet number (1-4)
largest_pn Largest packet number received so far
Returns
Full recovered packet number
Definition at line 131 of file packet.cpp.
{
    // RFC 9000 Appendix A
    uint64_t expected_pn = largest_pn + 1;
    uint64_t pn_win = 1ULL << (pn_length * 8);
    uint64_t pn_hwin = pn_win / 2;
    uint64_t pn_mask = pn_win - 1;
    // Reconstruct the full packet number
    uint64_t candidate_pn = (expected_pn & ~pn_mask) | truncated_pn;
    // Handle wrap-around cases
    if (candidate_pn <= expected_pn - pn_hwin && candidate_pn < (1ULL << 62) - pn_win)
    {
        return candidate_pn + pn_win;
    }
    if (candidate_pn > expected_pn + pn_hwin && candidate_pn >= pn_win)
    {
        return candidate_pn - pn_win;
    }
    return candidate_pn;
}
Referenced by kcenon::network::internal::quic_socket::handle_packet().
encode()
auto kcenon::network::protocols::quic::packet_number::encode (uint64_t full_pn, uint64_t largest_acked) -> std::pair<std::vector<uint8_t>, size_t> static
Encode a packet number for transmission.
Parameters
full_pn Full packet number to encode
largest_acked Largest acknowledged packet number (0 if none)
Returns
Pair of (encoded bytes, number of bytes used)
Definition at line 116 of file packet.cpp.
{
    size_t len = encoded_length(full_pn, largest_acked);
    std::vector<uint8_t> result(len);
    // Encode in big-endian order
    for (size_t i = 0; i < len; ++i)
    {
        result[len - 1 - i] = static_cast<uint8_t>(full_pn >> (i * 8));
    }
    return {result, len};
}
Referenced by kcenon::network::protocols::quic::packet_builder::build_handshake(), kcenon::network::protocols::quic::packet_builder::build_initial(), kcenon::network::protocols::quic::packet_builder::build_short(), and kcenon::network::protocols::quic::packet_builder::build_zero_rtt().
encoded_length()
auto kcenon::network::protocols::quic::packet_number::encoded_length (uint64_t full_pn, uint64_t largest_acked) -> size_t static noexcept
Get the minimum number of bytes needed to encode a packet number.
Parameters
full_pn Full packet number
largest_acked Largest acknowledged packet number
Returns
Number of bytes (1-4)
Definition at line 155 of file packet.cpp.
{
    uint64_t num_unacked = (full_pn > largest_acked) ? (full_pn - largest_acked) : 1;
    if (num_unacked < (1ULL << 7))
    {
        return 1;
    }
    if (num_unacked < (1ULL << 15))
    {
        return 2;
    }
    if (num_unacked < (1ULL << 23))
    {
        return 3;
    }
    return 4;
}
Referenced by kcenon::network::protocols::quic::packet_builder::build_handshake(), kcenon::network::protocols::quic::packet_builder::build_initial(), kcenon::network::protocols::quic::packet_builder::build_short(), and kcenon::network::protocols::quic::packet_builder::build_zero_rtt().
The documentation for this class was generated from the following files:
src/internal/protocols/quic/packet.h
src/protocols/quic/packet.cpp