Network System: kcenon::network::core::secure_messaging_udp_client Class Reference
kcenon::network::core::secure_messaging_udp_client Class Reference export
module kcenon.network
A secure UDP client using DTLS (Datagram TLS) for encrypted communication.
#include <secure_messaging_udp_client.h>
Public Types
using receive_callback_t = std::function< void(const std::vector< uint8_t > &)>
Callback type for received data.
using connected_callback_t = std::function< void()>
Callback type for connection established.
using disconnected_callback_t = std::function< void()>
Callback type for disconnection.
using error_callback_t = std::function< void(std::error_code)>
Callback type for errors.
using udp_receive_callback_t = std::function< void(const std::vector< uint8_t > &, const asio::ip::udp::endpoint &)>
UDP-specific receive callback type with sender endpoint.
Public Member Functions
secure_messaging_udp_client (std::string_view client_id, bool verify_cert=true)
Constructs a secure_messaging_udp_client with an identifier.
~secure_messaging_udp_client () noexcept
Destructor. Automatically calls stop_client() if still running.
secure_messaging_udp_client (const secure_messaging_udp_client &)=delete
secure_messaging_udp_client & operator= (const secure_messaging_udp_client &)=delete
secure_messaging_udp_client (secure_messaging_udp_client &&)=delete
secure_messaging_udp_client & operator= (secure_messaging_udp_client &&)=delete
auto start_client (std::string_view host, unsigned short port) -> VoidResult
Starts the client and connects to the specified host and port.
auto stop_client () -> VoidResult
Stops the client and disconnects.
auto wait_for_stop () -> void
Blocks until stop_client() is called.
auto is_running () const noexcept -> bool
Checks if the client is currently running.
auto is_connected () const noexcept -> bool
Checks if the client is connected to the server.
auto client_id () const -> const std::string &
Returns the client identifier.
auto send_packet (std::vector< uint8_t > &&data) -> VoidResult
Sends an encrypted datagram to the server.
auto send_packet_with_handler (std::vector< uint8_t > &&data, std::function< void(std::error_code, std::size_t)> handler) -> VoidResult
Sends an encrypted datagram with a completion handler.
auto set_udp_receive_callback (udp_receive_callback_t callback) -> void
Sets a UDP-specific callback to handle received decrypted datagrams.
auto set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received data.
auto set_connected_callback (connected_callback_t callback) -> void
Sets the callback for connection established.
auto set_disconnected_callback (disconnected_callback_t callback) -> void
Sets the callback for disconnection.
auto set_error_callback (error_callback_t callback) -> void
Sets the callback for errors.
secure_messaging_udp_client (std::string_view client_id, const ssl_config &config={})
Construct a secure UDP client with DTLS configuration.
virtual ~secure_messaging_udp_client () noexcept
Destructor.
secure_messaging_udp_client (const secure_messaging_udp_client &)=delete
secure_messaging_udp_client & operator= (const secure_messaging_udp_client &)=delete
secure_messaging_udp_client (secure_messaging_udp_client &&) noexcept
secure_messaging_udp_client & operator= (secure_messaging_udp_client &&) noexcept
bool start_client (std::string_view remote_host, uint16_t remote_port)
Start the client and perform DTLS handshake.
void stop_client ()
Stop the client.
bool send_packet (std::span< const uint8_t > data)
Send encrypted datagram.
bool is_connected () const noexcept
Check if the client is connected and DTLS handshake completed.
bool is_running () const noexcept
Check if the client is running.
std::string_view client_id () const noexcept
Get the client identifier.
void set_connection_callback (connection_callback callback)
Set connection callback (called after DTLS handshake)
void set_disconnection_callback (disconnection_callback callback)
Set disconnection callback.
void set_data_callback (data_callback callback)
Set data received callback.
void set_error_callback (error_callback callback)
Set error callback.
Private Types
using callback_index = secure_udp_client_callback
Callback index type alias for clarity.
using callbacks_t = utils::callback_manager< receive_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t >
Callback manager type for this client.
Private Member Functions
auto do_start_impl (std::string_view host, unsigned short port) -> VoidResult
DTLS-specific implementation of client start.
auto do_stop_impl () -> VoidResult
DTLS-specific implementation of client stop.
auto do_send_impl (std::vector< uint8_t > &&data) -> VoidResult
DTLS-specific implementation of data send.
auto init_ssl_context () -> VoidResult
Initializes the SSL context for DTLS.
auto do_handshake () -> VoidResult
Performs the DTLS handshake.
auto set_connected (bool connected) -> void
Sets the connected state.
auto invoke_receive_callback (const std::vector< uint8_t > &data) -> void
Invokes the receive callback.
auto invoke_connected_callback () -> void
Invokes the connected callback.
auto invoke_disconnected_callback () -> void
Invokes the disconnected callback.
auto invoke_error_callback (std::error_code ec) -> void
Invokes the error callback.
Private Attributes
std::string client_id_
utils::lifecycle_manager lifecycle_
callbacks_t callbacks_
std::atomic< bool > is_connected_ {false}
bool verify_cert_ {true}
std::unique_ptr< asio::io_context > io_context_
std::shared_ptr< internal::dtls_socket > socket_
SSL_CTX * ssl_ctx_ {nullptr}
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::future< void > io_context_future_
std::mutex endpoint_mutex_
asio::ip::udp::endpoint target_endpoint_
std::mutex udp_callback_mutex_
UDP-specific receive callback (includes sender endpoint)
udp_receive_callback_t udp_receive_callback_
std::unique_ptr< impl > pimpl_
Detailed Description
A secure UDP client using DTLS (Datagram TLS) for encrypted communication.
A DTLS encrypted UDP client.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling.
Thread Safety
All public methods are thread-safe.
Socket access is protected by appropriate mutexes.
Atomic flags prevent race conditions.
Key Characteristics
Uses DTLS 1.2/1.3 for encryption over UDP transport.
Performs DTLS handshake after socket setup.
Provides confidentiality and integrity for UDP datagrams.
Suitable for secure real-time communication.
Usage Example
auto client = std::make_shared<secure_messaging_udp_client>("SecureUDPClient");
// Set callback to handle received datagrams (UDP-specific with endpoint)
client->set_udp_receive_callback(
    [](const std::vector<uint8_t>& data, const asio::ip::udp::endpoint& sender) {
        std::cout << "Received " << data.size() << " encrypted bytes\n";
    });
// Start client with DTLS connection
auto result = client->start_client("localhost", 5555);
if (!result) {
    std::cerr << "Failed to start: " << result.error().message << "\n";
    return -1;
}
// Send encrypted datagram
std::vector<uint8_t> data = {0x01, 0x02, 0x03};
client->send_packet(std::move(data));
// Stop client
client->stop_client();
This class provides secure UDP communication using DTLS (Datagram TLS), combining the benefits of UDP with encryption.
Key Features
DTLS 1.2/1.3 support
Replay protection
Certificate verification
import kcenon.network;
using namespace kcenon::network::core;
ssl_config config;
config.protocol = ssl_protocol::dtls_1_2;
config.ca_certificate_path = "/path/to/ca.pem";
auto client = std::make_unique<secure_messaging_udp_client>("dtls_client", config);
client->start_client("example.com", 5684);
Definition at line 110 of file secure_messaging_udp_client.h.
Member Typedef Documentation
callback_index
using kcenon::network::core::secure_messaging_udp_client::callback_index = secure_udp_client_callback private
Callback index type alias for clarity.
Definition at line 319 of file secure_messaging_udp_client.h.
callbacks_t
using kcenon::network::core::secure_messaging_udp_client::callbacks_t = utils::callback_manager< receive_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t > private
Callback manager type for this client.
Definition at line 322 of file secure_messaging_udp_client.h.
connected_callback_t
using kcenon::network::core::secure_messaging_udp_client::connected_callback_t = std::function<void()>
Callback type for connection established.
Definition at line 117 of file secure_messaging_udp_client.h.
disconnected_callback_t
using kcenon::network::core::secure_messaging_udp_client::disconnected_callback_t = std::function<void()>
Callback type for disconnection.
Definition at line 119 of file secure_messaging_udp_client.h.
error_callback_t
using kcenon::network::core::secure_messaging_udp_client::error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Definition at line 121 of file secure_messaging_udp_client.h.
receive_callback_t
using kcenon::network::core::secure_messaging_udp_client::receive_callback_t = std::function<void(const std::vector<uint8_t>&)>
Callback type for received data.
Definition at line 115 of file secure_messaging_udp_client.h.
udp_receive_callback_t
using kcenon::network::core::secure_messaging_udp_client::udp_receive_callback_t = std::function<void(const std::vector<uint8_t>&, const asio::ip::udp::endpoint&)>
UDP-specific receive callback type with sender endpoint.
Definition at line 124 of file secure_messaging_udp_client.h.
Constructor & Destructor Documentation
secure_messaging_udp_client() [1/6]
kcenon::network::core::secure_messaging_udp_client::secure_messaging_udp_client (std::string_view client_id, bool verify_cert = true)
Constructs a secure_messaging_udp_client with an identifier.
Parameters
client_id A string identifier for this client instance.
verify_cert Whether to verify server certificate (default: true).
Definition at line 44 of file secure_messaging_udp_client.cpp.
    : client_id_(client_id)
    , verify_cert_(verify_cert)
{
}
~secure_messaging_udp_client() [1/2]
kcenon::network::core::secure_messaging_udp_client::~secure_messaging_udp_client () noexcept
Destructor. Automatically calls stop_client() if still running.
Definition at line 51 of file secure_messaging_udp_client.cpp.
{
    if (lifecycle_.is_running())
    {
        (void)stop_client();
    }
}
References kcenon::network::utils::lifecycle_manager::is_running(), lifecycle_, and stop_client().
secure_messaging_udp_client() [2/6]
kcenon::network::core::secure_messaging_udp_client::secure_messaging_udp_client (const secure_messaging_udp_client &) delete
secure_messaging_udp_client() [3/6]
kcenon::network::core::secure_messaging_udp_client::secure_messaging_udp_client (secure_messaging_udp_client &&) delete
secure_messaging_udp_client() [4/6]
kcenon::network::core::secure_messaging_udp_client::secure_messaging_udp_client (std::string_view client_id, const ssl_config & config = {}) explicit export
Construct a secure UDP client with DTLS configuration.
Parameters
client_id A string identifier for this client instance
config SSL/DTLS configuration
~secure_messaging_udp_client() [2/2]
virtual kcenon::network::core::secure_messaging_udp_client::~secure_messaging_udp_client () export virtual noexcept
Destructor.
secure_messaging_udp_client() [5/6]
kcenon::network::core::secure_messaging_udp_client::secure_messaging_udp_client (const secure_messaging_udp_client &) export delete
secure_messaging_udp_client() [6/6]
kcenon::network::core::secure_messaging_udp_client::secure_messaging_udp_client (secure_messaging_udp_client &&) export noexcept
Member Function Documentation
client_id() [1/2]
auto kcenon::network::core::secure_messaging_udp_client::client_id () const -> const std::string&
Returns the client identifier.
Returns
The client_id string.
Definition at line 143 of file secure_messaging_udp_client.cpp.
{
    return client_id_;
}
References client_id_.
client_id() [2/2]
std::string_view kcenon::network::core::secure_messaging_udp_client::client_id () const export noexcept
Get the client identifier.
Returns
Client ID string
do_handshake()
auto kcenon::network::core::secure_messaging_udp_client::do_handshake () -> VoidResult private
Performs the DTLS handshake.
Returns
Result<void> - Success if handshake completed.
Definition at line 390 of file secure_messaging_udp_client.cpp.
{
    std::mutex handshake_mutex;
    std::condition_variable handshake_cv;
    bool handshake_done = false;
    std::error_code handshake_error;
    socket_->async_handshake(
        internal::dtls_socket::handshake_type::client,
        [&](std::error_code ec)
        {
            {
                std::lock_guard<std::mutex> lock(handshake_mutex);
                handshake_done = true;
                handshake_error = ec;
            }
            handshake_cv.notify_one();
        });
    // Wait for handshake with timeout
    {
        std::unique_lock<std::mutex> lock(handshake_mutex);
        if (!handshake_cv.wait_for(lock, std::chrono::seconds(30),
                                   [&] { return handshake_done; }))
        {
            return error_void(error_codes::network_system::connection_timeout,
                              "DTLS handshake timeout",
                              "secure_messaging_udp_client::do_handshake");
        }
    }
    if (handshake_error)
    {
        return error_void(error_codes::network_system::connection_failed,
                          "DTLS handshake failed: " + handshake_error.message(),
                          "secure_messaging_udp_client::do_handshake");
    }
    return ok();
}
References kcenon::network::internal::dtls_socket::client, kcenon::network::error_codes::network_system::connection_failed, kcenon::network::error_codes::network_system::connection_timeout, kcenon::network::error_void(), and kcenon::network::ok().
do_send_impl()
auto kcenon::network::core::secure_messaging_udp_client::do_send_impl (std::vector< uint8_t > && data) -> VoidResult private
DTLS-specific implementation of data send.
Parameters
data The plaintext data to encrypt and send (moved for efficiency).
Returns
Result<void> - Success if send initiated.
Definition at line 462 of file secure_messaging_udp_client.cpp.
{
    if (!socket_)
    {
        return error_void(error_codes::common_errors::internal_error,
                          "Socket not available",
                          "secure_messaging_udp_client::do_send_impl");
    }
    socket_->async_send(std::move(data), nullptr);
    return ok();
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, and kcenon::network::ok().
do_start_impl()
auto kcenon::network::core::secure_messaging_udp_client::do_start_impl (std::string_view host, unsigned short port) -> VoidResult private
DTLS-specific implementation of client start.
Parameters
host The target hostname or IP address.
port The target port number.
Returns
Result<void> - Success if client started and handshake completed.
Definition at line 288 of file secure_messaging_udp_client.cpp.
{
    // Initialize SSL context
    auto ssl_result = init_ssl_context();
    if (!ssl_result.is_ok())
    {
        return ssl_result;
    }
    // Create io_context
    io_context_ = std::make_unique<asio::io_context>();
    // Resolve the target endpoint
    asio::ip::udp::resolver resolver(*io_context_);
    std::error_code resolve_ec;
    auto endpoints = resolver.resolve(
        asio::ip::udp::v4(),
        std::string(host),
        std::to_string(port),
        resolve_ec);
    if (resolve_ec || endpoints.empty())
    {
        SSL_CTX_free(ssl_ctx_);
        ssl_ctx_ = nullptr;
        return error_void(error_codes::common_errors::internal_error,
                          "Failed to resolve host: " + std::string(host),
                          "secure_messaging_udp_client::do_start_impl");
    }
    {
        std::lock_guard<std::mutex> lock(endpoint_mutex_);
        target_endpoint_ = *endpoints.begin();
    }
    // Create UDP socket
    asio::ip::udp::socket udp_socket(*io_context_, asio::ip::udp::v4());
    // Create DTLS socket
    socket_ = std::make_shared<internal::dtls_socket>(
        std::move(udp_socket), ssl_ctx_);
    // Set peer endpoint
    {
        std::lock_guard<std::mutex> lock(endpoint_mutex_);
        socket_->set_peer_endpoint(target_endpoint_);
    }
    // Set callbacks - use UDP-specific callback for receive
    auto self = shared_from_this();
    socket_->set_receive_callback(
        [this, self](const std::vector<uint8_t>& data, const asio::ip::udp::endpoint& sender)
        {
            udp_receive_callback_t callback;
            {
                std::lock_guard<std::mutex> lock(udp_callback_mutex_);
                callback = udp_receive_callback_;
            }
            if (callback)
            {
                callback(data, sender);
            }
        });
    socket_->set_error_callback(
        [this, self](std::error_code ec)
        {
            invoke_error_callback(ec);
        });
    // Get thread pool from network context
    thread_pool_ = network_context::instance().get_thread_pool();
    if (!thread_pool_) {
        // Fallback: create a temporary thread pool if network_context is not initialized
        thread_pool_ = std::make_shared<integration::basic_thread_pool>(std::thread::hardware_concurrency());
    }
    // Start io_context in background
    io_context_future_ = thread_pool_->submit(
        [this]()
        {
            auto work_guard = asio::make_work_guard(*io_context_);
            io_context_->run();
        });
    // Perform handshake
    auto handshake_result = do_handshake();
    if (!handshake_result.is_ok())
    {
        return handshake_result;
    }
    // Mark as connected
    set_connected(true);
    // Notify connected
    invoke_connected_callback();
    return ok();
}
References kcenon::network::error_void(), kcenon::network::core::network_context::get_thread_pool(), kcenon::network::core::network_context::instance(), kcenon::network::error_codes::common_errors::internal_error, and kcenon::network::ok().
do_stop_impl()
auto kcenon::network::core::secure_messaging_udp_client::do_stop_impl () -> VoidResult private
DTLS-specific implementation of client stop.
Returns
Result<void> - Success if client stopped.
Definition at line 431 of file secure_messaging_udp_client.cpp.
{
    // Stop socket
    if (socket_)
    {
        socket_->stop_receive();
        socket_.reset();
    }
    // Stop io_context
    if (io_context_)
    {
        io_context_->stop();
    }
    // Wait for io_context thread
    if (io_context_future_.valid())
    {
        io_context_future_.wait();
    }
    // Cleanup SSL context
    if (ssl_ctx_)
    {
        SSL_CTX_free(ssl_ctx_);
        ssl_ctx_ = nullptr;
    }
    return ok();
}
References kcenon::network::ok().
init_ssl_context()
auto kcenon::network::core::secure_messaging_udp_client::init_ssl_context () -> VoidResult private
Initializes the SSL context for DTLS.
Returns
Result<void> - Success if context initialized.
Definition at line 259 of file secure_messaging_udp_client.cpp.
{
    // Create DTLS client context
    ssl_ctx_ = SSL_CTX_new(DTLS_client_method());
    if (!ssl_ctx_)
    {
        return error_void(error_codes::common_errors::internal_error,
                          "Failed to create DTLS context",
                          "secure_messaging_udp_client::init_ssl_context");
    }
    // Set DTLS options
    SSL_CTX_set_options(ssl_ctx_, SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3);
    // Set verification mode
    if (verify_cert_)
    {
        SSL_CTX_set_verify(ssl_ctx_, SSL_VERIFY_PEER, nullptr);
        // Load default CA certificates
        SSL_CTX_set_default_verify_paths(ssl_ctx_);
    }
    else
    {
        SSL_CTX_set_verify(ssl_ctx_, SSL_VERIFY_NONE, nullptr);
    }
    return ok();
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, and kcenon::network::ok().
invoke_connected_callback()
auto kcenon::network::core::secure_messaging_udp_client::invoke_connected_callback () -> void private
Invokes the connected callback.
Definition at line 240 of file secure_messaging_udp_client.cpp.
{
    callbacks_.invoke<to_index(callback_index::connected)>();
}
References kcenon::network::to_index().
invoke_disconnected_callback()
auto kcenon::network::core::secure_messaging_udp_client::invoke_disconnected_callback () -> void private
Invokes the disconnected callback.
Definition at line 245 of file secure_messaging_udp_client.cpp.
{
    callbacks_.invoke<to_index(callback_index::disconnected)>();
}
References kcenon::network::to_index().
invoke_error_callback()
auto kcenon::network::core::secure_messaging_udp_client::invoke_error_callback (std::error_code ec) -> void private
Invokes the error callback.
Definition at line 250 of file secure_messaging_udp_client.cpp.
{
    callbacks_.invoke<to_index(callback_index::error)>(ec);
}
References kcenon::network::to_index().
invoke_receive_callback()
auto kcenon::network::core::secure_messaging_udp_client::invoke_receive_callback (const std::vector< uint8_t > & data) -> void private
Invokes the receive callback.
Definition at line 235 of file secure_messaging_udp_client.cpp.
{
    callbacks_.invoke<to_index(callback_index::receive)>(data);
}
References kcenon::network::to_index().
is_connected() [1/2]
bool kcenon::network::core::secure_messaging_udp_client::is_connected () const export noexcept
Check if the client is connected and DTLS handshake completed.
Returns
true if securely connected
is_connected() [2/2]
auto kcenon::network::core::secure_messaging_udp_client::is_connected () const -> bool noexcept
Checks if the client is connected to the server.
Returns
true if connected, false otherwise.
Definition at line 138 of file secure_messaging_udp_client.cpp.
{
    return is_connected_.load(std::memory_order_acquire);
}
References is_connected_.
is_running() [1/2]
bool kcenon::network::core::secure_messaging_udp_client::is_running () const export noexcept
Check if the client is running.
Returns
true if running
is_running() [2/2]
auto kcenon::network::core::secure_messaging_udp_client::is_running () const -> bool noexcept
Checks if the client is currently running.
Returns
true if running, false otherwise.
Definition at line 133 of file secure_messaging_udp_client.cpp.
{
    return lifecycle_.is_running();
}
References kcenon::network::utils::lifecycle_manager::is_running(), and lifecycle_.
operator=() [1/4]
secure_messaging_udp_client & kcenon::network::core::secure_messaging_udp_client::operator= (const secure_messaging_udp_client &) delete
operator=() [2/4]
secure_messaging_udp_client & kcenon::network::core::secure_messaging_udp_client::operator= (const secure_messaging_udp_client &) export delete
operator=() [3/4]
secure_messaging_udp_client & kcenon::network::core::secure_messaging_udp_client::operator= (secure_messaging_udp_client &&) export noexcept
operator=() [4/4]
secure_messaging_udp_client & kcenon::network::core::secure_messaging_udp_client::operator= (secure_messaging_udp_client &&) delete
send_packet() [1/2]
bool kcenon::network::core::secure_messaging_udp_client::send_packet (std::span< const uint8_t > data) export
Send encrypted datagram.
Parameters
data The data to send
Returns
true if data was sent
send_packet() [2/2]
auto kcenon::network::core::secure_messaging_udp_client::send_packet (std::vector< uint8_t > && data) -> VoidResult
Sends an encrypted datagram to the server.
Parameters
data The plaintext data to encrypt and send (moved for efficiency).
Returns
Result<void> - Success if send initiated, or error.
Definition at line 152 of file secure_messaging_udp_client.cpp.
{
    if (!is_connected_.load(std::memory_order_acquire))
    {
        return error_void(
            error_codes::network_system::connection_closed,
            "Not connected",
            "secure_messaging_udp_client::send_packet");
    }
    if (data.empty())
    {
        return error_void(
            error_codes::common_errors::invalid_argument,
            "Data cannot be empty",
            "secure_messaging_udp_client::send_packet");
    }
    return do_send_impl(std::move(data));
}
References kcenon::network::error_codes::network_system::connection_closed, kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::invalid_argument.
send_packet_with_handler()
auto kcenon::network::core::secure_messaging_udp_client::send_packet_with_handler (std::vector< uint8_t > && data, std::function< void(std::error_code, std::size_t)> handler) -> VoidResult
Sends an encrypted datagram with a completion handler.
Parameters
data The plaintext data to encrypt and send (moved for efficiency).
handler Optional completion handler.
Returns
Result<void> - Success if send initiated.
Definition at line 173 of file secure_messaging_udp_client.cpp.
{
    if (!is_connected())
    {
        return error_void(error_codes::common_errors::internal_error,
                          "Client not connected",
                          "secure_messaging_udp_client::send_packet_with_handler");
    }
    if (!socket_)
    {
        return error_void(error_codes::common_errors::internal_error,
                          "Socket not available",
                          "secure_messaging_udp_client::send_packet_with_handler");
    }
    socket_->async_send(std::move(data), std::move(handler));
    return ok();
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::internal_error, and kcenon::network::ok().
set_connected()
auto kcenon::network::core::secure_messaging_udp_client::set_connected (bool connected) -> void private
Sets the connected state.
Parameters
connected The new connection state.
Definition at line 230 of file secure_messaging_udp_client.cpp.
{
    is_connected_.store(connected, std::memory_order_release);
}
References kcenon::network::core::connected.
set_connected_callback()
auto kcenon::network::core::secure_messaging_udp_client::set_connected_callback (connected_callback_t callback) -> void
Sets the callback for connection established.
Parameters
callback Function called when connection is established.
Definition at line 211 of file secure_messaging_udp_client.cpp.
{
    callbacks_.set<to_index(callback_index::connected)>(std::move(callback));
}
References kcenon::network::to_index().
set_connection_callback()
void kcenon::network::core::secure_messaging_udp_client::set_connection_callback (connection_callback callback) export
Set connection callback (called after DTLS handshake)
Parameters
callback Function to call when securely connected
set_data_callback()
void kcenon::network::core::secure_messaging_udp_client::set_data_callback (data_callback callback) export
Set data received callback.
Parameters
callback Function to call when decrypted data is received
set_disconnected_callback()
auto kcenon::network::core::secure_messaging_udp_client::set_disconnected_callback (disconnected_callback_t callback) -> void
Sets the callback for disconnection.
Parameters
callback Function called when disconnected.
Definition at line 216 of file secure_messaging_udp_client.cpp.
{
    callbacks_.set<to_index(callback_index::disconnected)>(std::move(callback));
}
References kcenon::network::to_index().
set_disconnection_callback()
void kcenon::network::core::secure_messaging_udp_client::set_disconnection_callback (disconnection_callback callback) export
Set disconnection callback.
Parameters
callback Function to call when disconnected
set_error_callback() [1/2]
void kcenon::network::core::secure_messaging_udp_client::set_error_callback (error_callback callback) export
Set error callback.
Parameters
callback Function to call on errors
set_error_callback() [2/2]
auto kcenon::network::core::secure_messaging_udp_client::set_error_callback (error_callback_t callback) -> void
Sets the callback for errors.
Parameters
callback Function called when an error occurs.
Definition at line 221 of file secure_messaging_udp_client.cpp.
{
    callbacks_.set<to_index(callback_index::error)>(std::move(callback));
}
References kcenon::network::to_index().
set_receive_callback()
auto kcenon::network::core::secure_messaging_udp_client::set_receive_callback (receive_callback_t callback) -> void
Sets the callback for received data.
Parameters
callback Function called when data is received.
Definition at line 206 of file secure_messaging_udp_client.cpp.
{
    callbacks_.set<to_index(callback_index::receive)>(std::move(callback));
}
References kcenon::network::to_index().
set_udp_receive_callback()
auto kcenon::network::core::secure_messaging_udp_client::set_udp_receive_callback (udp_receive_callback_t callback) -> void
Sets a UDP-specific callback to handle received decrypted datagrams.
Parameters
callback Function with signature void(const std::vector<uint8_t>&, const asio::ip::udp::endpoint&)
Note
This is UDP-specific and includes sender endpoint information. Use this instead of set_receive_callback().
Definition at line 199 of file secure_messaging_udp_client.cpp.
{
    std::lock_guard<std::mutex> lock(udp_callback_mutex_);
    udp_receive_callback_ = std::move(callback);
}
start_client() [1/2]
auto kcenon::network::core::secure_messaging_udp_client::start_client (std::string_view host, unsigned short port) -> VoidResult
Starts the client and connects to the specified host and port.
Parameters
host The remote hostname or IP address.
port The remote port number to connect.
Returns
Result<void> - Success if client started, or error with code:
error_codes::common_errors::already_exists if already running
error_codes::common_errors::invalid_argument if empty host
error_codes::common_errors::internal_error for other failures
Definition at line 63 of file secure_messaging_udp_client.cpp.
{
    if (lifecycle_.is_running())
    {
        return error_void(
            error_codes::common_errors::already_exists,
            "Client is already running",
            "secure_messaging_udp_client::start_client");
    }
    if (host.empty())
    {
        return error_void(
            error_codes::common_errors::invalid_argument,
            "Host cannot be empty",
            "secure_messaging_udp_client::start_client");
    }
    if (!lifecycle_.try_start())
    {
        return error_void(
            error_codes::common_errors::already_exists,
            "Client is already starting",
            "secure_messaging_udp_client::start_client");
    }
    is_connected_.store(false, std::memory_order_release);
    // Call implementation
    auto result = do_start_impl(host, port);
    if (result.is_err())
    {
        lifecycle_.mark_stopped();
    }
    return result;
}
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::invalid_argument.
start_client() [2/2]
bool kcenon::network::core::secure_messaging_udp_client::start_client (std::string_view remote_host, uint16_t remote_port) export
Start the client and perform DTLS handshake.
Parameters
remote_host The remote host address
remote_port The remote port number
Returns
true if connection initiated successfully
stop_client() [1/2]
void kcenon::network::core::secure_messaging_udp_client::stop_client () export
Stop the client.
stop_client() [2/2]
auto kcenon::network::core::secure_messaging_udp_client::stop_client () -> VoidResult
Stops the client and disconnects.
Returns
Result<void> - Success if client stopped, or error with code:
error_codes::common_errors::internal_error for failures
Definition at line 102 of file secure_messaging_udp_client.cpp.
{
    if (!lifecycle_.is_running())
    {
        return ok();
    }
    if (!lifecycle_.prepare_stop())
    {
        return ok(); // Already stopping or not running
    }
    is_connected_.store(false, std::memory_order_release);
    // Call implementation
    auto result = do_stop_impl();
    // Signal stop completion
    lifecycle_.mark_stopped();
    // Invoke disconnected callback
    invoke_disconnected_callback();
    return result;
}
References kcenon::network::ok().
Referenced by ~secure_messaging_udp_client().
wait_for_stop()
auto kcenon::network::core::secure_messaging_udp_client::wait_for_stop () -> void
Blocks until stop_client() is called.
Definition at line 128 of file secure_messaging_udp_client.cpp.
{
    lifecycle_.wait_for_stop();
}
Member Data Documentation
callbacks_
callbacks_t kcenon::network::core::secure_messaging_udp_client::callbacks_ private
Callback manager.
Definition at line 335 of file secure_messaging_udp_client.h.
client_id_
std::string kcenon::network::core::secure_messaging_udp_client::client_id_ private
Client identifier.
Definition at line 333 of file secure_messaging_udp_client.h.
Referenced by client_id().
endpoint_mutex_
std::mutex kcenon::network::core::secure_messaging_udp_client::endpoint_mutex_ private
Protects target endpoint.
Definition at line 348 of file secure_messaging_udp_client.h.
io_context_
std::unique_ptr<asio::io_context> kcenon::network::core::secure_messaging_udp_client::io_context_ private
ASIO I/O context.
Definition at line 340 of file secure_messaging_udp_client.h.
io_context_future_
std::future<void> kcenon::network::core::secure_messaging_udp_client::io_context_future_ private
Future for io_context run task.
Definition at line 346 of file secure_messaging_udp_client.h.
is_connected_
std::atomic<bool> kcenon::network::core::secure_messaging_udp_client::is_connected_ {false} private
Connection state.
Definition at line 336 of file secure_messaging_udp_client.h.
{false};
Referenced by is_connected().
lifecycle_
utils::lifecycle_manager kcenon::network::core::secure_messaging_udp_client::lifecycle_ private
Lifecycle state manager.
Definition at line 334 of file secure_messaging_udp_client.h.
Referenced by is_running(), and ~secure_messaging_udp_client().
pimpl_
std::unique_ptr<impl> kcenon::network::core::secure_messaging_udp_client::pimpl_ export private
Definition at line 555 of file ssl.cppm.
socket_
std::shared_ptr<internal::dtls_socket> kcenon::network::core::secure_messaging_udp_client::socket_ private
DTLS socket wrapper.
Definition at line 341 of file secure_messaging_udp_client.h.
ssl_ctx_
SSL_CTX* kcenon::network::core::secure_messaging_udp_client::ssl_ctx_ {nullptr} private
OpenSSL SSL context.
Definition at line 343 of file secure_messaging_udp_client.h.
{nullptr};
target_endpoint_
asio::ip::udp::endpoint kcenon::network::core::secure_messaging_udp_client::target_endpoint_ private
Target endpoint.
Definition at line 349 of file secure_messaging_udp_client.h.
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::secure_messaging_udp_client::thread_pool_ private
Definition at line 345 of file secure_messaging_udp_client.h.
udp_callback_mutex_
std::mutex kcenon::network::core::secure_messaging_udp_client::udp_callback_mutex_ private
UDP-specific receive callback (includes sender endpoint)
Definition at line 352 of file secure_messaging_udp_client.h.
udp_receive_callback_
udp_receive_callback_t kcenon::network::core::secure_messaging_udp_client::udp_receive_callback_ private
Definition at line 353 of file secure_messaging_udp_client.h.
verify_cert_
bool kcenon::network::core::secure_messaging_udp_client::verify_cert_ {true} private
Certificate verification flag.
Definition at line 338 of file secure_messaging_udp_client.h.
{true};
The documentation for this class was generated from the following files:
src/internal/core/secure_messaging_udp_client.h
src/modules/ssl.cppm
src/core/secure_messaging_udp_client.cpp