Network System: kcenon::network::integration::thread_integration_manager::impl Class Reference
kcenon::network::integration::thread_integration_manager::impl Class Reference
Public Member Functions
impl ()=default
void set_thread_pool (std::shared_ptr< thread_pool_interface > pool)
std::shared_ptr< thread_pool_interface > get_thread_pool ()
std::future< void > submit_task (std::function< void()> task)
std::future< void > submit_delayed_task (std::function< void()> task, std::chrono::milliseconds delay)
thread_integration_manager::metrics get_metrics () const
Private Attributes
std::mutex mutex_
std::shared_ptr< thread_pool_interface > thread_pool_
Detailed Description
Definition at line 448 of file thread_integration.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::integration::thread_integration_manager::impl::impl () default
Member Function Documentation
get_metrics()
thread_integration_manager::metrics kcenon::network::integration::thread_integration_manager::impl::get_metrics () const inline
Definition at line 479 of file thread_integration.cpp.
{
        std::unique_lock<std::mutex> lock(mutex_);
        metrics m;
        if (thread_pool_) {
            m.worker_threads = thread_pool_->worker_count();
            m.pending_tasks = thread_pool_->pending_tasks();
            m.is_running = thread_pool_->is_running();
            if (auto* basic = dynamic_cast<basic_thread_pool*>(thread_pool_.get())) {
                m.completed_tasks = basic->completed_tasks();
            }
        }
        return m;
    }
References kcenon::network::integration::thread_integration_manager::metrics::completed_tasks, kcenon::network::integration::thread_integration_manager::metrics::is_running, mutex_, kcenon::network::integration::thread_integration_manager::metrics::pending_tasks, thread_pool_, and kcenon::network::integration::thread_integration_manager::metrics::worker_threads.
get_thread_pool()
std::shared_ptr< thread_pool_interface > kcenon::network::integration::thread_integration_manager::impl::get_thread_pool () inline
Definition at line 457 of file thread_integration.cpp.
{
        std::unique_lock<std::mutex> lock(mutex_);
        if (!thread_pool_) {
            // When thread_system is available, basic_thread_pool now internally
            // uses thread_system::thread_pool, so creating basic_thread_pool
            // automatically gets the benefits of thread_system.
            thread_pool_ = std::make_shared<basic_thread_pool>();
        }
        return thread_pool_;
    }
References mutex_, and thread_pool_.
Referenced by submit_delayed_task(), and submit_task().
set_thread_pool()
void kcenon::network::integration::thread_integration_manager::impl::set_thread_pool (std::shared_ptr< thread_pool_interface > pool) inline
Definition at line 452 of file thread_integration.cpp.
{
        std::unique_lock<std::mutex> lock(mutex_);
        thread_pool_ = pool;
    }
References mutex_, and thread_pool_.
submit_delayed_task()
std::future< void > kcenon::network::integration::thread_integration_manager::impl::submit_delayed_task (std::function< void()> task, std::chrono::milliseconds delay) inline
Definition at line 472 of file thread_integration.cpp.
      {
        return get_thread_pool()->submit_delayed(task, delay);
    }
References get_thread_pool().
submit_task()
std::future< void > kcenon::network::integration::thread_integration_manager::impl::submit_task (std::function< void()> task) inline
Definition at line 468 of file thread_integration.cpp.
{
        return get_thread_pool()->submit(task);
    }
References get_thread_pool().
Member Data Documentation
mutex_
std::mutex kcenon::network::integration::thread_integration_manager::impl::mutex_ mutable private
Definition at line 497 of file thread_integration.cpp.
Referenced by get_metrics(), get_thread_pool(), and set_thread_pool().
thread_pool_
std::shared_ptr<thread_pool_interface> kcenon::network::integration::thread_integration_manager::impl::thread_pool_ private
Definition at line 498 of file thread_integration.cpp.
Referenced by get_metrics(), get_thread_pool(), and set_thread_pool().
The documentation for this class was generated from the following file:
src/integration/thread_integration.cpp