Network System: kcenon::network::core::messaging_client Class Reference
kcenon::network::core::messaging_client Class Reference export
module kcenon.network
A basic TCP client that connects to a remote host, sends/receives data using asynchronous operations, and can apply a pipeline for transformations.
#include <messaging_client.h>
Public Types
using receive_callback_t = std::function< void(const std::vector< uint8_t > &)>
Callback type for received data.
using connected_callback_t = std::function< void()>
Callback type for connection established.
using disconnected_callback_t = std::function< void()>
Callback type for disconnection.
using error_callback_t = std::function< void(std::error_code)>
Callback type for errors.
Public Types inherited from kcenon::network::interfaces::i_protocol_client
using receive_callback_t = std::function< void(const std::vector< uint8_t > &)>
Callback type for received data.
using connected_callback_t = std::function< void()>
Callback type for connection established.
using disconnected_callback_t = std::function< void()>
Callback type for disconnection.
using error_callback_t = std::function< void(std::error_code)>
Callback type for errors.
Public Member Functions
auto is_running () const -> bool override
Checks if the client is currently running.
auto wait_for_stop () -> void override
Waits for the client to stop.
messaging_client (std::string_view client_id)
Constructs a client with a given client_id used for logging or identification.
~messaging_client () noexcept
Destructor; automatically calls stop_client() if the client is still running.
messaging_client (const messaging_client &)=delete
messaging_client & operator= (const messaging_client &)=delete
messaging_client (messaging_client &&)=delete
messaging_client & operator= (messaging_client &&)=delete
auto start (std::string_view host, uint16_t port) -> VoidResult override
Starts the client and connects to the specified server (IProtocolClient interface).
auto stop () -> VoidResult override
Stops the client and closes the connection (IProtocolClient interface).
auto send (std::vector< uint8_t > &&data) -> VoidResult override
Sends data to the connected server (IProtocolClient interface).
auto is_connected () const -> bool override
Checks if the client is connected to the server (IProtocolClient interface).
auto set_observer (std::shared_ptr< interfaces::connection_observer > observer) -> void override
Sets the connection observer for unified event handling.
auto start_client (std::string_view host, unsigned short port) -> VoidResult
Starts the client and connects to the specified host and port.
auto stop_client () -> VoidResult
Stops the client and disconnects from the server.
auto client_id () const -> const std::string &
Returns the client identifier.
auto send_packet (std::vector< uint8_t > &&data) -> VoidResult
Sends data to the connected server.
auto set_receive_callback (receive_callback_t callback) -> void override
Sets the callback for received data.
auto set_connected_callback (connected_callback_t callback) -> void override
Sets the callback for connection established.
auto set_disconnected_callback (disconnected_callback_t callback) -> void override
Sets the callback for disconnection.
auto set_error_callback (error_callback_t callback) -> void override
Sets the callback for errors.
messaging_client (std::string_view client_id)
Construct a client with a given client_id.
virtual ~messaging_client () noexcept
Destructor - automatically stops the client if running.
messaging_client (const messaging_client &)=delete
messaging_client & operator= (const messaging_client &)=delete
messaging_client (messaging_client &&) noexcept
messaging_client & operator= (messaging_client &&) noexcept
bool start_client (std::string_view host, uint16_t port)
Start the client and connect to a remote host.
void stop_client ()
Stop the client and disconnect.
bool wait_for_stop (std::chrono::milliseconds timeout=std::chrono::milliseconds(5000))
Wait for the client to stop.
bool send_packet (std::span< const uint8_t > data)
Send data to the connected server.
bool send_packet (std::string_view data)
Send string data to the connected server.
bool is_connected () const noexcept
Check if the client is connected.
bool is_running () const noexcept
Check if the client is running.
connection_state get_state () const noexcept
Get the current connection state.
std::string_view client_id () const noexcept
Get the client identifier.
void set_connection_callback (connection_callback callback)
Set connection callback.
void set_disconnection_callback (disconnection_callback callback)
Set disconnection callback.
void set_error_callback (error_callback callback)
Set error callback.
void set_data_callback (data_callback callback)
Set data received callback.
void set_auto_reconnect (bool enable, std::chrono::seconds delay=std::chrono::seconds(5))
Enable automatic reconnection.
void set_heartbeat (bool enable, std::chrono::seconds interval=std::chrono::seconds(30))
Enable heartbeat mechanism.
Public Member Functions inherited from kcenon::network::utils::startable_base< messaging_client >
auto is_running () const noexcept -> bool
Checks if the component is currently running.
auto wait_for_stop () -> void
Blocks until stop is called.
Public Member Functions inherited from kcenon::network::interfaces::i_network_component
virtual ~i_network_component ()=default
Virtual destructor for proper cleanup of derived classes.
i_network_component (const i_network_component &)=delete
i_network_component & operator= (const i_network_component &)=delete
i_network_component (i_network_component &&)=delete
i_network_component & operator= (i_network_component &&)=delete
Private Types
using callback_index = tcp_client_callback
Callback index type alias for clarity.
using callbacks_t = utils::callback_manager< receive_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t >
Callback manager type for this client.
Private Member Functions
auto on_stopped () -> void
Called after stop operation completes. Invokes the disconnected callback.
auto do_start_impl (std::string_view host, unsigned short port) -> VoidResult
TCP-specific implementation of client start.
auto do_stop_impl () -> VoidResult
TCP-specific implementation of client stop.
auto do_send_impl (std::vector< uint8_t > &&data) -> VoidResult
TCP-specific implementation of data send.
auto set_connected (bool connected) -> void
Sets the connected state.
auto invoke_receive_callback (const std::vector< uint8_t > &data) -> void
Invokes the receive callback.
auto invoke_connected_callback () -> void
Invokes the connected callback.
auto invoke_disconnected_callback () -> void
Invokes the disconnected callback.
auto invoke_error_callback (std::error_code ec) -> void
Invokes the error callback.
auto do_connect (std::string_view host, unsigned short port) -> void
Internally attempts to resolve and connect to the remote host:port.
auto on_connect (std::error_code ec) -> void
Callback invoked upon completion of an async connect.
auto on_receive (std::span< const uint8_t > data) -> void
Callback for receiving data from the tcp_socket.
auto on_error (std::error_code ec) -> void
Callback for handling socket errors from tcp_socket.
auto on_connection_failed (std::error_code ec) -> void
Handles connection failure during async resolve or connect.
auto get_socket () const -> std::shared_ptr< internal::tcp_socket >
Static Private Member Functions
static constexpr auto component_name () noexcept -> std::string_view
Returns the component name for error messages.
Private Attributes
std::string client_id_
callbacks_t callbacks_
std::atomic< bool > is_connected_ {false}
std::shared_ptr< interfaces::connection_observer > observer_
Connection observer for unified event handling (IProtocolClient interface)
std::shared_ptr< asio::io_context > io_context_
std::unique_ptr< asio::executor_work_guard< asio::io_context::executor_type > > work_guard_
std::future< void > io_context_future_
std::mutex socket_mutex_
std::shared_ptr< internal::tcp_socket > socket_
std::mutex pending_mutex_
Pending connection resources that need explicit cleanup. These are stored as members to allow cancellation during stop_client(), preventing heap corruption when io_context is destroyed with pending async operations.
std::shared_ptr< asio::ip::tcp::resolver > pending_resolver_
std::shared_ptr< asio::ip::tcp::socket > pending_socket_
std::unique_ptr< impl > pimpl_
Friends
class utils::startable_base< messaging_client >
Additional Inherited Members
Protected Member Functions inherited from kcenon::network::utils::startable_base< messaging_client >
startable_base ()=default
Default constructor.
startable_base (const startable_base &)=delete
startable_base (startable_base &&) noexcept=default
~startable_base ()=default
Destructor.
startable_base & operator= (const startable_base &)=delete
startable_base & operator= (startable_base &&) noexcept=default
auto do_start (Args &&... args) -> VoidResult
Unified start operation with lifecycle management.
auto do_stop () -> VoidResult
Unified stop operation with lifecycle management.
auto is_stop_initiated () const noexcept -> bool
Checks if stop has been initiated.
auto get_lifecycle () -> lifecycle_manager &
Gets the lifecycle manager for derived class access.
auto get_lifecycle () const -> const lifecycle_manager &
Gets the lifecycle manager (const version).
Protected Member Functions inherited from kcenon::network::interfaces::i_network_component
i_network_component ()=default
Default constructor (only for derived classes)
Detailed Description
A basic TCP client that connects to a remote host, sends/receives data using asynchronous operations, and can apply a pipeline for transformations.
A basic TCP client for asynchronous messaging.
This class uses composition pattern with lifecycle_manager and callback_manager for common lifecycle management and callback handling.
Thread Safety
All public methods are thread-safe.
Socket access is protected by socket_mutex_.
Atomic flags (is_running_, is_connected_, stop_initiated_) prevent race conditions.
send_packet() can be called from any thread safely.
Connection state changes are serialized through ASIO's io_context.
Key Features
Uses asio::io_context in a dedicated thread to handle I/O events.
Connects via async_connect, then wraps the socket in a tcp_socket for asynchronous reads and writes.
Optionally compresses/encrypts data before sending, and can similarly decompress/decrypt incoming data if extended.
Provides start_client(), stop_client(), and wait_for_stop() to control lifecycle.
This class provides a TCP client that connects to a remote host, sends/receives data using asynchronous operations, and can apply a pipeline for data transformations.
Thread Safety
All public methods are thread-safe.
Socket access is protected by internal mutex.
Atomic flags prevent race conditions during state transitions.
send_packet() can be called from any thread safely.
Key Features
Uses asio::io_context for async I/O
Automatic reconnection support
Optional compression and encryption pipelines
Heartbeat mechanism for connection health
import kcenon.network;
auto client = std::make_unique<kcenon::network::core::messaging_client>("my_client");
client->set_connection_callback([]() {
    std::cout << "Connected!" << std::endl;
});
client->set_data_callback([](std::span<const uint8_t> data) {
    std::cout << "Received " << data.size() << " bytes" << std::endl;
});
client->start_client("localhost", 8080);
Definition at line 93 of file messaging_client.h.
Member Typedef Documentation
callback_index
using kcenon::network::core::messaging_client::callback_index = tcp_client_callback private
Callback index type alias for clarity.
Definition at line 366 of file messaging_client.h.
callbacks_t
using kcenon::network::core::messaging_client::callbacks_t = utils::callback_manager< receive_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t > private
Callback manager type for this client.
Definition at line 369 of file messaging_client.h.
connected_callback_t
using kcenon::network::core::messaging_client::connected_callback_t = std::function<void()>
Callback type for connection established.
Definition at line 124 of file messaging_client.h.
disconnected_callback_t
using kcenon::network::core::messaging_client::disconnected_callback_t = std::function<void()>
Callback type for disconnection.
Definition at line 126 of file messaging_client.h.
error_callback_t
using kcenon::network::core::messaging_client::error_callback_t = std::function<void(std::error_code)>
Callback type for errors.
Definition at line 128 of file messaging_client.h.
receive_callback_t
using kcenon::network::core::messaging_client::receive_callback_t = std::function<void(const std::vector<uint8_t>&)>
Callback type for received data.
Definition at line 122 of file messaging_client.h.
Constructor & Destructor Documentation
messaging_client() [1/6]
kcenon::network::core::messaging_client::messaging_client (std::string_view client_id) explicit
Constructs a client with a given client_id used for logging or identification.
Parameters
client_id A string identifier for this client instance.
Definition at line 49 of file messaging_client.cpp.
    : client_id_(client_id) {
}
~messaging_client() [1/2]
kcenon::network::core::messaging_client::~messaging_client () noexcept
Destructor; automatically calls stop_client() if the client is still running.
Definition at line 53 of file messaging_client.cpp.
{
  if (is_running()) {
    (void)stop_client();
  }
}
References is_running(), and stop_client().
messaging_client() [2/6]
kcenon::network::core::messaging_client::messaging_client (const messaging_client &) delete
messaging_client() [3/6]
kcenon::network::core::messaging_client::messaging_client (messaging_client &&) delete
messaging_client() [4/6]
kcenon::network::core::messaging_client::messaging_client (std::string_view client_id) explicit export
Construct a client with a given client_id.
Parameters
client_id A string identifier for this client instance
~messaging_client() [2/2]
virtual kcenon::network::core::messaging_client::~messaging_client () export virtual noexcept
Destructor - automatically stops the client if running.
messaging_client() [5/6]
kcenon::network::core::messaging_client::messaging_client (const messaging_client &) export delete
messaging_client() [6/6]
kcenon::network::core::messaging_client::messaging_client (messaging_client &&) export noexcept
Member Function Documentation
client_id() [1/2]
auto kcenon::network::core::messaging_client::client_id () const -> const std::string&
Returns the client identifier.
Returns
The client_id string.
Definition at line 117 of file messaging_client.cpp.
{
  return client_id_;
}
References client_id_.
client_id() [2/2]
std::string_view kcenon::network::core::messaging_client::client_id () const export noexcept
Get the client identifier.
Returns
Client ID string
component_name()
static constexpr auto kcenon::network::core::messaging_client::component_name () -> std::string_view inline static constexpr private noexcept
Returns the component name for error messages.
Returns
The component name string view.
Definition at line 248 of file messaging_client.h.
        {
            return "Client";
        }
do_connect()
auto kcenon::network::core::messaging_client::do_connect (std::string_view host, unsigned short port) -> void private
Internally attempts to resolve and connect to the remote host:port.
Definition at line 405 of file messaging_client.cpp.
            {
  // Use resolver to get endpoints
  // Store resolver as member so we can cancel it during stop_client()
  auto resolver = std::make_shared<tcp::resolver>(*io_context_);
  {
    std::lock_guard<std::mutex> lock(pending_mutex_);
    pending_resolver_ = resolver;
  }
  auto self = shared_from_this();
  // NOTE: No logging in async handlers to prevent heap corruption during
  // static destruction. The is_logging_safe() check cannot synchronize with
  // common_system's static destruction order.
  resolver->async_resolve(
      std::string(host), std::to_string(port),
      [self, resolver](std::error_code ec,
                             tcp::resolver::results_type results) {
        // Check if stop was initiated before proceeding with socket operations.
        // This prevents race conditions when do_stop() is called during connection.
        if (self->is_stop_initiated()) {
          return;
        }
        // Clear pending resolver only if it's still the same resolver
        // (prevents race when rapid connect/disconnect overwrites pending_resolver_)
        {
          std::lock_guard<std::mutex> lock(self->pending_mutex_);
          if (self->pending_resolver_.get() == resolver.get()) {
            self->pending_resolver_.reset();
          }
        }
        if (ec) {
          self->on_connection_failed(ec);
          return;
        }
        // Check again after clearing resolver
        if (self->is_stop_initiated()) {
          return;
        }
        // Attempt to connect to one of the resolved endpoints
        // Store socket as member so we can cancel it during stop_client()
        auto raw_socket = std::make_shared<tcp::socket>(*self->io_context_);
        {
          std::lock_guard<std::mutex> lock(self->pending_mutex_);
          self->pending_socket_ = raw_socket;
        }
        asio::async_connect(
            *raw_socket, results,
            [self,
             raw_socket](std::error_code connect_ec,
                         [[maybe_unused]] const tcp::endpoint &endpoint) {
              // Check if stop was initiated before proceeding with socket operations.
              // This prevents race conditions when do_stop() is called during connection.
              if (self->is_stop_initiated()) {
                return;
              }
              // Clear pending socket only if it's still the same socket
              // (prevents race when rapid connect/disconnect overwrites pending_socket_)
              {
                std::lock_guard<std::mutex> lock(self->pending_mutex_);
                if (self->pending_socket_.get() == raw_socket.get()) {
                  self->pending_socket_.reset();
                }
              }
              if (connect_ec) {
                self->on_connection_failed(connect_ec);
                return;
              }
              // Check again after clearing socket
              if (self->is_stop_initiated()) {
                return;
              }
              // On success, wrap it in our tcp_socket with mutex protection
              {
                std::lock_guard<std::mutex> lock(self->socket_mutex_);
                self->socket_ = std::make_shared<internal::tcp_socket>(
                    std::move(*raw_socket));
              }
              self->on_connect(connect_ec);
            });
      });
}
do_send_impl()
auto kcenon::network::core::messaging_client::do_send_impl (std::vector< uint8_t > && data) -> VoidResult private
TCP-specific implementation of data send.
Parameters
data The buffer to send (moved for efficiency).
Returns
Result<void> - Success if data queued for send, or error.
Definition at line 531 of file messaging_client.cpp.
{
  // Get a local copy of socket with mutex protection
  auto local_socket = get_socket();
  if (!local_socket) {
    return error_void(error_codes::network_system::connection_closed,
                      "Socket not available",
                      "messaging_client::do_send",
                      "Client ID: " + client_id());
  }
  // Send data directly without pipeline transformation
  // NOTE: No logging in send callbacks to prevent heap corruption during
  // static destruction.
  local_socket->async_send(std::move(data),
      [](std::error_code, std::size_t) {
        // Silently ignore errors - no logging during potential static destruction
      });
  return ok();
}
References kcenon::network::error_codes::network_system::connection_closed, kcenon::network::error_void(), and kcenon::network::ok().
do_start_impl()
auto kcenon::network::core::messaging_client::do_start_impl (std::string_view host, unsigned short port) -> VoidResult private
TCP-specific implementation of client start.
Parameters
host The remote hostname or IP address.
port The remote port number to connect.
Returns
Result<void> - Success if client started, or error.
Definition at line 242 of file messaging_client.cpp.
                  {
  try {
    {
      std::lock_guard<std::mutex> lock(socket_mutex_);
      socket_.reset();
    }
    // Use Intentional Leak pattern for io_context to prevent heap corruption
    // during static destruction phase. The no-op deleter ensures io_context
    // survives until process termination, avoiding issues when pending async
    // operations' handlers reference io_context internals.
    // Memory impact: ~few KB per client (reclaimed by OS on process termination)
    io_context_ = std::shared_ptr<asio::io_context>(
        new asio::io_context(),
        [](asio::io_context*) { /* no-op deleter - intentional leak */ });
    // Create work guard to keep io_context running
    work_guard_ = std::make_unique<
        asio::executor_work_guard<asio::io_context::executor_type>>(
        asio::make_work_guard(*io_context_));
    // Use io_context_thread_manager for unified thread management
    io_context_future_ = integration::io_context_thread_manager::instance()
        .run_io_context(io_context_, "messaging_client:" + client_id());
    do_connect(host, port);
    // NOTE: No logging here to prevent heap corruption during static destruction.
    // When common_system uses async logging, log messages may still be queued
    // when static destruction begins, causing heap corruption when the logging
    // thread accesses destroyed GlobalLoggerRegistry.
    return ok();
  } catch (const std::exception &e) {
    return error_void(error_codes::common_errors::internal_error,
                      "Failed to start client: " + std::string(e.what()),
                      "messaging_client::do_start",
                      "Client ID: " + client_id() +
                          ", Host: " + std::string(host));
  }
}
References kcenon::network::error_void(), kcenon::network::integration::io_context_thread_manager::instance(), kcenon::network::error_codes::common_errors::internal_error, kcenon::network::ok(), and kcenon::network::integration::io_context_thread_manager::run_io_context().
do_stop_impl()
auto kcenon::network::core::messaging_client::do_stop_impl () -> VoidResult private
TCP-specific implementation of client stop.
Returns
Result<void> - Success if client stopped, or error.
Definition at line 285 of file messaging_client.cpp.
{
  // NOTE: No logging in do_stop to prevent heap corruption during static
  // destruction. This method may be called from destructor when
  // GlobalLoggerRegistry is already destroyed.
  // Mark as disconnected first (stop_initiated_ is already set by base class do_stop())
  is_connected_.store(false, std::memory_order_release);
  try {
    // Swap out socket with mutex protection and close outside lock
    std::shared_ptr<internal::tcp_socket> local_socket;
    {
      std::lock_guard<std::mutex> lock(socket_mutex_);
      local_socket = std::move(socket_);
    }
    // Close socket safely using tcp_socket::close() which posts to the socket's
    // executor for thread-safety with async operations.
    if (local_socket) {
      local_socket->close();
    }
    // Cancel pending connection operations by posting to io_context.
    // This ensures socket operations happen on the same thread as async_connect,
    // preventing data races detected by ThreadSanitizer.
    if (io_context_) {
      std::shared_ptr<asio::ip::tcp::resolver> resolver_to_cancel;
      std::shared_ptr<asio::ip::tcp::socket> socket_to_close;
      {
        std::lock_guard<std::mutex> lock(pending_mutex_);
        resolver_to_cancel = pending_resolver_;
        socket_to_close = pending_socket_;
      }
      if (resolver_to_cancel || socket_to_close) {
        // Use promise/future to wait for the close operation to complete
        auto close_promise = std::make_shared<std::promise<void>>();
        auto close_future = close_promise->get_future();
        asio::post(*io_context_,
                   [resolver_to_cancel, socket_to_close, close_promise]() {
                     if (resolver_to_cancel) {
                       resolver_to_cancel->cancel();
                     }
                     if (socket_to_close) {
                       asio::error_code ec;
                       // Only use close() - do NOT call cancel() on pending_socket_.
                       // When async_connect() is in progress, the socket may be open but
                       // not fully registered with the reactor. Calling cancel() on such
                       // a socket causes SEGV in epoll_reactor::cancel_ops() when accessing
                       // uninitialized op_queue. close() is sufficient as it cancels all
                       // pending async operations and is safe in any socket state.
                       socket_to_close->close(ec);
                     }
                     close_promise->set_value();
                   });
        // Wait with timeout in case io_context is already stopped
        close_future.wait_for(std::chrono::milliseconds(100));
      }
    }
    // Release work guard to allow io_context to finish
    if (work_guard_) {
      work_guard_.reset();
    }
    // Stop io_context BEFORE waiting. This ensures io_context::run() returns
    // promptly without waiting for pending async operations to complete.
    // This is safe because io_context uses intentional leak pattern (no-op deleter),
    // so any handlers that don't run won't cause heap corruption since
    // io_context won't be destroyed.
    if (io_context_) {
      integration::io_context_thread_manager::instance().stop_io_context(
          io_context_);
    }
    // Wait for io_context task to complete - should return immediately after stop()
    if (io_context_future_.valid()) {
      io_context_future_.wait();
    }
    // Clear pending resources after io_context is stopped
    {
      std::lock_guard<std::mutex> lock(pending_mutex_);
      pending_resolver_.reset();
      pending_socket_.reset();
    }
    // Note: io_context uses intentional leak pattern (no-op deleter),
    // so reset() just clears the shared_ptr without destroying io_context
    io_context_.reset();
    return ok();
  } catch (const std::exception &e) {
    return error_void(error_codes::common_errors::internal_error,
                      "Failed to stop client: " + std::string(e.what()),
                      "messaging_client::do_stop",
                      "Client ID: " + client_id());
  }
}
References kcenon::network::error_void(), kcenon::network::integration::io_context_thread_manager::instance(), kcenon::network::error_codes::common_errors::internal_error, kcenon::network::ok(), and kcenon::network::integration::io_context_thread_manager::stop_io_context().
get_socket()
auto kcenon::network::core::messaging_client::get_socket () const -> std::shared_ptr<internal::tcp_socket> private
Definition at line 583 of file messaging_client.cpp.
{
  std::lock_guard<std::mutex> lock(socket_mutex_);
  return socket_;
}
get_state()
connection_state kcenon::network::core::messaging_client::get_state () const export noexcept
Get the current connection state.
Returns
Current connection state
invoke_connected_callback()
auto kcenon::network::core::messaging_client::invoke_connected_callback () -> void private
Invokes the connected callback.
Definition at line 229 of file messaging_client.cpp.
{
  callbacks_.invoke<to_index(callback_index::connected)>();
}
References kcenon::network::to_index().
invoke_disconnected_callback()
auto kcenon::network::core::messaging_client::invoke_disconnected_callback () -> void private
Invokes the disconnected callback.
Definition at line 233 of file messaging_client.cpp.
{
  callbacks_.invoke<to_index(callback_index::disconnected)>();
}
References kcenon::network::to_index().
invoke_error_callback()
auto kcenon::network::core::messaging_client::invoke_error_callback (std::error_code ec) -> void private
Invokes the error callback.
Definition at line 237 of file messaging_client.cpp.
{
  callbacks_.invoke<to_index(callback_index::error)>(ec);
}
References kcenon::network::to_index().
invoke_receive_callback()
auto kcenon::network::core::messaging_client::invoke_receive_callback (const std::vector< uint8_t > & data) -> void private
Invokes the receive callback.
Definition at line 225 of file messaging_client.cpp.
{
  callbacks_.invoke<to_index(callback_index::receive)>(data);
}
References kcenon::network::to_index().
is_connected() [1/2]
auto kcenon::network::core::messaging_client::is_connected () const -> bool override virtual
Checks if the client is connected to the server (IProtocolClient interface).
Returns
true if connected, false otherwise.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 113 of file messaging_client.cpp.
{
  return is_connected_.load(std::memory_order_acquire);
}
References is_connected_.
is_connected() [2/2]
bool kcenon::network::core::messaging_client::is_connected () const export virtual noexcept
Check if the client is connected.
Returns
true if connected, false otherwise
Implements kcenon::network::interfaces::i_protocol_client.
is_running() [1/2]
auto kcenon::network::core::messaging_client::is_running () const -> bool inline override virtual
Checks if the client is currently running.
Returns
true if running, false otherwise.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 109 of file messaging_client.h.
        {
            return utils::startable_base<messaging_client>::is_running();
        }
References kcenon::network::utils::startable_base< Derived >::is_running().
Referenced by ~messaging_client().
is_running() [2/2]
bool kcenon::network::core::messaging_client::is_running () const export virtual noexcept
Check if the client is running.
Returns
true if running, false otherwise
Implements kcenon::network::interfaces::i_network_component.
on_connect()
auto kcenon::network::core::messaging_client::on_connect (std::error_code ec) -> void private
Callback invoked upon completion of an async connect.
Parameters
ec The std::error_code indicating success/failure.
Definition at line 495 of file messaging_client.cpp.
{
  // NOTE: No logging in async handlers to prevent heap corruption during
  // static destruction. The is_logging_safe() check cannot synchronize with
  // common_system's static destruction order.
  if (ec) {
    return;
  }
  set_connected(true);
  // Invoke connected callback using base class method
  invoke_connected_callback();
  // set callbacks and start read loop with mutex protection
  // Use span-based callback for zero-copy receive path (no per-read allocation)
  auto self = shared_from_this();
  auto local_socket = get_socket();
  if (local_socket) {
    local_socket->set_receive_callback_view(
        [self](std::span<const uint8_t> chunk) { self->on_receive(chunk); });
    local_socket->set_error_callback(
        [self](std::error_code err) { self->on_error(err); });
    // Post start_read() to io_context to ensure tcp_socket is fully initialized
    // This prevents SEGV in async_read_some when socket descriptor state is incomplete
    if (io_context_) {
      asio::post(*io_context_, [local_socket]() {
        if (local_socket) {
          local_socket->start_read();
        }
      });
    }
  }
}
on_connection_failed()
auto kcenon::network::core::messaging_client::on_connection_failed (std::error_code ec) -> void private
Handles connection failure during async resolve or connect.
Parameters
ec The error code from the failed operation.
Cleans up resources and signals stop to prevent hangs in destructor.
Definition at line 387 of file messaging_client.cpp.
{
  // NOTE: No logging here to prevent heap corruption during static destruction.
  // When common_system's GlobalLoggerRegistry is destroyed before this callback
  // completes, any logging (even with is_logging_safe() check) causes heap
  // corruption because the check cannot synchronize with common_system's
  // static destruction order.
  // Mark as not connected (but keep is_running_ true so destructor calls stop_client)
  set_connected(false);
  // Invoke error callback using base class method
  invoke_error_callback(ec);
  // Note: Do NOT release work_guard_ or signal stop_promise_ here.
  // The destructor will call stop_client() which handles all cleanup properly.
  // This avoids race conditions between callback cleanup and destructor cleanup.
}
on_error()
auto kcenon::network::core::messaging_client::on_error (std::error_code ec) -> void private
Callback for handling socket errors from tcp_socket.
Parameters
ec The std::error_code describing the error.
By default, logs the error message and stop_client().
Definition at line 566 of file messaging_client.cpp.
{
  // NOTE: No logging in async handlers to prevent heap corruption during
  // static destruction.
  // Invoke error callback using base class method
  invoke_error_callback(ec);
  // Invoke disconnected callback if was connected
  if (is_connected()) {
    invoke_disconnected_callback();
  }
  // Mark connection as lost using base class method
  // Note: We don't modify is_running_ here - the base class stop_client() handles that
  set_connected(false);
}
on_receive()
auto kcenon::network::core::messaging_client::on_receive (std::span< const uint8_t > data) -> void private
Callback for receiving data from the tcp_socket.
Parameters
data A span view of bytes that has arrived.
Zero-Copy Performance
The span provides a non-owning view directly into the socket's internal read buffer, avoiding per-read vector allocations.
Lifetime Contract
The span is valid only until this callback returns.
Data is copied into a vector only when invoking external receive_callback_ to maintain API compatibility.
By default, logs the size of received data. To fully handle incoming messages, one could parse, decompress, decrypt, etc.
Definition at line 553 of file messaging_client.cpp.
{
  // NOTE: No logging in async handlers to prevent heap corruption during
  // static destruction.
  if (!is_connected()) {
    return;
  }
  // Invoke receive callback using base class method
  // Copy span to vector only at API boundary to maintain external callback compatibility
  std::vector<uint8_t> data_copy(data.begin(), data.end());
  invoke_receive_callback(data_copy);
}
on_stopped()
auto kcenon::network::core::messaging_client::on_stopped () -> void private
Called after stop operation completes. Invokes the disconnected callback.
Definition at line 106 of file messaging_client.cpp.
{
  // Invoke disconnected callback after stop completes
  callbacks_.invoke<to_index(callback_index::disconnected)>();
}
References kcenon::network::to_index().
operator=() [1/4]
messaging_client & kcenon::network::core::messaging_client::operator= (const messaging_client &) delete
operator=() [2/4]
messaging_client & kcenon::network::core::messaging_client::operator= (const messaging_client &) export delete
operator=() [3/4]
messaging_client & kcenon::network::core::messaging_client::operator= (messaging_client &&) export noexcept
operator=() [4/4]
messaging_client & kcenon::network::core::messaging_client::operator= (messaging_client &&) delete
send()
auto kcenon::network::core::messaging_client::send (std::vector< uint8_t > && data) -> VoidResult override virtual
Sends data to the connected server (IProtocolClient interface).
Parameters
data The data to send.
Returns
VoidResult indicating success or failure.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 190 of file messaging_client.cpp.
{
  return send_packet(std::move(data));
}
send_packet() [1/3]
bool kcenon::network::core::messaging_client::send_packet (std::span< const uint8_t > data) export
Send data to the connected server.
Parameters
data The data to send
Returns
true if data was queued for sending
send_packet() [2/3]
bool kcenon::network::core::messaging_client::send_packet (std::string_view data) export
Send string data to the connected server.
Parameters
data The string data to send
Returns
true if data was queued for sending
send_packet() [3/3]
auto kcenon::network::core::messaging_client::send_packet (std::vector< uint8_t > && data) -> VoidResult
Sends data to the connected server.
Parameters
data The buffer to send (moved for efficiency).
Returns
Result<void> - Success if data queued for send, or error with code:
error_codes::network_system::connection_closed if not connected
error_codes::network_system::send_failed for other failures
Definition at line 121 of file messaging_client.cpp.
{
  // Create tracing span for send operation
  auto span = tracing::is_tracing_enabled()
      ? std::make_optional(tracing::trace_context::create_span("tcp.client.send"))
      : std::nullopt;
  if (span) {
    span->set_attribute("net.transport", "tcp")
         .set_attribute("message.size", static_cast<int64_t>(data.size()))
         .set_attribute("client.id", client_id_);
  }
  if (!is_connected()) {
    if (span) {
      span->set_error("Client is not connected");
    }
    return error_void(error_codes::network_system::connection_closed,
                      "Client is not connected",
                      "messaging_client::send_packet",
                      "Client ID: " + client_id_);
  }
  if (data.empty()) {
    if (span) {
      span->set_error("Data cannot be empty");
    }
    return error_void(error_codes::common_errors::invalid_argument,
                      "Data cannot be empty",
                      "messaging_client::send_packet");
  }
  auto result = do_send_impl(std::move(data));
  if (span) {
    if (result.is_err()) {
      span->set_error(result.error().message);
    } else {
      span->set_status(tracing::span_status::ok);
    }
  }
  return result;
}
References kcenon::network::error_codes::network_system::connection_closed, kcenon::network::tracing::trace_context::create_span(), kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, kcenon::network::tracing::is_tracing_enabled(), and kcenon::network::tracing::ok.
set_auto_reconnect()
void kcenon::network::core::messaging_client::set_auto_reconnect (bool enable, std::chrono::seconds delay = std::chrono::seconds(5)) export
Enable automatic reconnection.
Parameters
enable true to enable, false to disable
delay Delay between reconnection attempts
set_connected()
auto kcenon::network::core::messaging_client::set_connected (bool connected) -> void private
Sets the connected state.
Parameters
connected The new connection state.
Definition at line 221 of file messaging_client.cpp.
{
  is_connected_.store(connected, std::memory_order_release);
}
References kcenon::network::core::connected.
set_connected_callback()
auto kcenon::network::core::messaging_client::set_connected_callback (connected_callback_t callback) -> void override virtual
Sets the callback for connection established.
Parameters
callback The callback function.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 166 of file messaging_client.cpp.
{
  callbacks_.set<to_index(callback_index::connected)>(std::move(callback));
}
References kcenon::network::to_index().
set_connection_callback()
void kcenon::network::core::messaging_client::set_connection_callback (connection_callback callback) export
Set connection callback.
Parameters
callback Function to call when connected
set_data_callback()
void kcenon::network::core::messaging_client::set_data_callback (data_callback callback) export
Set data received callback.
Parameters
callback Function to call when data is received
set_disconnected_callback()
auto kcenon::network::core::messaging_client::set_disconnected_callback (disconnected_callback_t callback) -> void override virtual
Sets the callback for disconnection.
Parameters
callback The callback function.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 170 of file messaging_client.cpp.
{
  callbacks_.set<to_index(callback_index::disconnected)>(std::move(callback));
}
References kcenon::network::to_index().
set_disconnection_callback()
void kcenon::network::core::messaging_client::set_disconnection_callback (disconnection_callback callback) export
Set disconnection callback.
Parameters
callback Function to call when disconnected
set_error_callback() [1/2]
void kcenon::network::core::messaging_client::set_error_callback (error_callback callback) export
Set error callback.
Parameters
callback Function to call on errors
set_error_callback() [2/2]
auto kcenon::network::core::messaging_client::set_error_callback (error_callback_t callback) -> void override virtual
Sets the callback for errors.
Parameters
callback The callback function.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 174 of file messaging_client.cpp.
{
  callbacks_.set<to_index(callback_index::error)>(std::move(callback));
}
References kcenon::network::to_index().
set_heartbeat()
void kcenon::network::core::messaging_client::set_heartbeat (bool enable, std::chrono::seconds interval = std::chrono::seconds(30)) export
Enable heartbeat mechanism.
Parameters
enable true to enable, false to disable
interval Heartbeat interval
set_observer()
auto kcenon::network::core::messaging_client::set_observer (std::shared_ptr< interfaces::connection_observer > observer) -> void override virtual
Sets the connection observer for unified event handling.
Parameters
observer The observer instance (shared ownership).
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 194 of file messaging_client.cpp.
{
  observer_ = observer;
  // Bridge observer methods to existing callbacks
  if (observer_) {
    set_receive_callback([observer](const std::vector<uint8_t>& data) {
      observer->on_receive(data);
    });
    set_connected_callback([observer]() {
      observer->on_connected();
    });
    set_disconnected_callback([observer]() {
      observer->on_disconnected();
    });
    set_error_callback([observer](std::error_code ec) {
      observer->on_error(ec);
    });
  }
}
set_receive_callback()
auto kcenon::network::core::messaging_client::set_receive_callback (receive_callback_t callback) -> void override virtual
Sets the callback for received data.
Parameters
callback The callback function.
Thread Safety
Thread-safe. The callback may be invoked from I/O threads. Callback must be thread-safe if it accesses shared state.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 162 of file messaging_client.cpp.
{
  callbacks_.set<to_index(callback_index::receive)>(std::move(callback));
}
References kcenon::network::to_index().
start()
auto kcenon::network::core::messaging_client::start (std::string_view host, uint16_t port) -> VoidResult override virtual
Starts the client and connects to the specified server (IProtocolClient interface).
Parameters
host The server hostname or IP address.
port The server port number.
Returns
VoidResult indicating success or failure.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 182 of file messaging_client.cpp.
{
  return start_client(host, port);
}
start_client() [1/2]
bool kcenon::network::core::messaging_client::start_client (std::string_view host, uint16_t port) export
Start the client and connect to a remote host.
Parameters
host The host address to connect to
port The port number to connect to
Returns
true if connection initiated successfully
start_client() [2/2]
auto kcenon::network::core::messaging_client::start_client (std::string_view host, unsigned short port) -> VoidResult
Starts the client and connects to the specified host and port.
Parameters
host The remote hostname or IP address.
port The remote port number to connect.
Returns
Result<void> - Success if client started, or error with code:
error_codes::network_system::client_already_running if already running
error_codes::common_errors::internal_error for other failures
Definition at line 59 of file messaging_client.cpp.
                  {
  // Create tracing span for client start operation
  auto span = tracing::is_tracing_enabled()
      ? std::make_optional(tracing::trace_context::create_span("tcp.client.start"))
      : std::nullopt;
  if (span) {
    span->set_attribute("net.peer.name", host)
         .set_attribute("net.peer.port", static_cast<int64_t>(port))
         .set_attribute("net.transport", "tcp")
         .set_attribute("client.id", client_id_);
  }
  if (host.empty()) {
    if (span) {
      span->set_error("Host cannot be empty");
    }
    return error_void(error_codes::common_errors::invalid_argument,
                      "Host cannot be empty",
                      "messaging_client::start_client");
  }
  // Reset connection state before start
  is_connected_.store(false, std::memory_order_release);
  // Use base class do_start which handles lifecycle management
  auto result = do_start(host, port);
  if (result.is_err()) {
    if (span) {
      span->set_error(result.error().message);
    }
  } else {
    if (span) {
      span->set_status(tracing::span_status::ok);
    }
  }
  return result;
}
References kcenon::network::tracing::trace_context::create_span(), kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, kcenon::network::tracing::is_tracing_enabled(), and kcenon::network::tracing::ok.
stop()
auto kcenon::network::core::messaging_client::stop () -> VoidResult override virtual
Stops the client and closes the connection (IProtocolClient interface).
Returns
VoidResult indicating success or failure.
Implements kcenon::network::interfaces::i_protocol_client.
Definition at line 186 of file messaging_client.cpp.
{
  return stop_client();
}
stop_client() [1/2]
void kcenon::network::core::messaging_client::stop_client () export
Stop the client and disconnect.
stop_client() [2/2]
auto kcenon::network::core::messaging_client::stop_client () -> VoidResult
Stops the client and disconnects from the server.
Returns
Result<void> - Success if client stopped, or error with code:
error_codes::network_system::client_not_started if not running
error_codes::common_errors::internal_error for failures
Definition at line 99 of file messaging_client.cpp.
{
  // Use base class do_stop which handles lifecycle management and calls on_stopped()
  // Note: do_stop() sets stop_initiated_ first, then calls do_stop_impl() which
  // handles is_connected_ reset and async operation cleanup in the correct order.
  return do_stop();
}
Referenced by ~messaging_client().
wait_for_stop() [1/2]
auto kcenon::network::core::messaging_client::wait_for_stop () -> void inline override virtual
Waits for the client to stop.
Implements kcenon::network::interfaces::i_network_component.
Definition at line 117 of file messaging_client.h.
        {
            return utils::startable_base<messaging_client>::wait_for_stop();
        }
References kcenon::network::utils::startable_base< Derived >::wait_for_stop().
wait_for_stop() [2/2]
bool kcenon::network::core::messaging_client::wait_for_stop (std::chrono::milliseconds timeout = std::chrono::milliseconds(5000)) export
Wait for the client to stop.
Parameters
timeout Maximum wait time
Returns
true if stopped within timeout
Friends And Related Symbol Documentation
utils::startable_base< messaging_client >
friend class utils::startable_base< messaging_client > friend
Definition at line 1 of file messaging_client.h.
Member Data Documentation
callbacks_
callbacks_t kcenon::network::core::messaging_client::callbacks_ private
Callback manager.
Definition at line 382 of file messaging_client.h.
client_id_
std::string kcenon::network::core::messaging_client::client_id_ private
Client identifier.
Definition at line 380 of file messaging_client.h.
Referenced by client_id().
io_context_
std::shared_ptr<asio::io_context> kcenon::network::core::messaging_client::io_context_ private
I/O context for async operations.
Definition at line 389 of file messaging_client.h.
io_context_future_
std::future<void> kcenon::network::core::messaging_client::io_context_future_ private
Future for the io_context run task.
Definition at line 393 of file messaging_client.h.
is_connected_
std::atomic<bool> kcenon::network::core::messaging_client::is_connected_ {false} private
Connection state.
Definition at line 383 of file messaging_client.h.
{false};
Referenced by is_connected().
observer_
std::shared_ptr<interfaces::connection_observer> kcenon::network::core::messaging_client::observer_ private
Connection observer for unified event handling (IProtocolClient interface)
Definition at line 386 of file messaging_client.h.
pending_mutex_
std::mutex kcenon::network::core::messaging_client::pending_mutex_ mutable private
Pending connection resources that need explicit cleanup. These are stored as members to allow cancellation during stop_client(), preventing heap corruption when io_context is destroyed with pending async operations.
Protects pending connection state.
Definition at line 407 of file messaging_client.h.
pending_resolver_
std::shared_ptr<asio::ip::tcp::resolver> kcenon::network::core::messaging_client::pending_resolver_ private
Definition at line 408 of file messaging_client.h.
pending_socket_
std::shared_ptr<asio::ip::tcp::socket> kcenon::network::core::messaging_client::pending_socket_ private
Definition at line 409 of file messaging_client.h.
pimpl_
std::unique_ptr<impl> kcenon::network::core::messaging_client::pimpl_ export private
Definition at line 201 of file tcp.cppm.
socket_
std::shared_ptr<internal::tcp_socket> kcenon::network::core::messaging_client::socket_ private
The tcp_socket wrapper once connected.
Definition at line 399 of file messaging_client.h.
socket_mutex_
std::mutex kcenon::network::core::messaging_client::socket_mutex_ mutable private
Protects socket_ from data races.
Definition at line 397 of file messaging_client.h.
work_guard_
std::unique_ptr<asio::executor_work_guard<asio::io_context::executor_type> > kcenon::network::core::messaging_client::work_guard_ private
Keeps io_context running.
Definition at line 391 of file messaging_client.h.
The documentation for this class was generated from the following files:
src/internal/core/messaging_client.h
src/modules/tcp.cppm
src/core/messaging_client.cpp