Network System: kcenon::network::protocols::grpc::generic_service::impl Class Reference
kcenon::network::protocols::grpc::generic_service::impl Class Reference
Public Member Functions
impl (std::string service_name)
auto descriptor () const -> const service_descriptor &
auto register_unary_method (const std::string &method_name, unary_handler handler, const std::string &input_type, const std::string &output_type) -> VoidResult
auto register_server_streaming_method (const std::string &method_name, server_streaming_handler handler, const std::string &input_type, const std::string &output_type) -> VoidResult
auto register_client_streaming_method (const std::string &method_name, client_streaming_handler handler, const std::string &input_type, const std::string &output_type) -> VoidResult
auto register_bidi_streaming_method (const std::string &method_name, bidi_streaming_handler handler, const std::string &input_type, const std::string &output_type) -> VoidResult
auto get_unary_handler (const std::string &method_name) const -> const unary_handler *
auto get_server_streaming_handler (const std::string &method_name) const -> const server_streaming_handler *
auto get_client_streaming_handler (const std::string &method_name) const -> const client_streaming_handler *
auto get_bidi_streaming_handler (const std::string &method_name) const -> const bidi_streaming_handler *
Private Attributes
service_descriptor descriptor_
std::mutex mutex_
std::unordered_map< std::string, unary_handler > unary_handlers_
std::unordered_map< std::string, server_streaming_handler > server_streaming_handlers_
std::unordered_map< std::string, client_streaming_handler > client_streaming_handlers_
std::unordered_map< std::string, bidi_streaming_handler > bidi_streaming_handlers_
Detailed Description
Definition at line 74 of file service_registry.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::protocols::grpc::generic_service::impl::impl (std::string service_name) inline explicit
Definition at line 77 of file service_registry.cpp.
    {
        // Parse package and service name
        auto dot_pos = service_name.rfind('.');
        if (dot_pos != std::string::npos)
        {
            descriptor_.package = service_name.substr(0, dot_pos);
            descriptor_.name = service_name.substr(dot_pos + 1);
        }
        else
        {
            descriptor_.name = std::move(service_name);
        }
    }
References descriptor_, kcenon::network::protocols::grpc::service_descriptor::name, and kcenon::network::protocols::grpc::service_descriptor::package.
Member Function Documentation
descriptor()
auto kcenon::network::protocols::grpc::generic_service::impl::descriptor () const -> const service_descriptor& inline
Definition at line 92 of file service_registry.cpp.
    {
        return descriptor_;
    }
References descriptor_.
get_bidi_streaming_handler()
auto kcenon::network::protocols::grpc::generic_service::impl::get_bidi_streaming_handler (const std::string & method_name) const -> const bidi_streaming_handler* inline
Definition at line 238 of file service_registry.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        auto it = bidi_streaming_handlers_.find(method_name);
        return it != bidi_streaming_handlers_.end() ? &it->second : nullptr;
    }
References bidi_streaming_handlers_, and mutex_.
get_client_streaming_handler()
auto kcenon::network::protocols::grpc::generic_service::impl::get_client_streaming_handler (const std::string & method_name) const -> const client_streaming_handler* inline
Definition at line 230 of file service_registry.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        auto it = client_streaming_handlers_.find(method_name);
        return it != client_streaming_handlers_.end() ? &it->second : nullptr;
    }
References client_streaming_handlers_, and mutex_.
get_server_streaming_handler()
auto kcenon::network::protocols::grpc::generic_service::impl::get_server_streaming_handler (const std::string & method_name) const -> const server_streaming_handler* inline
Definition at line 222 of file service_registry.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        auto it = server_streaming_handlers_.find(method_name);
        return it != server_streaming_handlers_.end() ? &it->second : nullptr;
    }
References mutex_, and server_streaming_handlers_.
get_unary_handler()
auto kcenon::network::protocols::grpc::generic_service::impl::get_unary_handler (const std::string & method_name) const -> const unary_handler* inline
Definition at line 214 of file service_registry.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        auto it = unary_handlers_.find(method_name);
        return it != unary_handlers_.end() ? &it->second : nullptr;
    }
References mutex_, and unary_handlers_.
register_bidi_streaming_method()
auto kcenon::network::protocols::grpc::generic_service::impl::register_bidi_streaming_method (const std::string & method_name, bidi_streaming_handler handler, const std::string & input_type, const std::string & output_type) -> VoidResult inline
Definition at line 185 of file service_registry.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (bidi_streaming_handlers_.find(method_name) != bidi_streaming_handlers_.end())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "Method already registered: " + method_name,
                "generic_service");
        }
        method_descriptor method;
        method.name = method_name;
        method.full_name = build_method_path(descriptor_.full_name(), method_name);
        method.type = method_type::bidi_streaming;
        method.input_type = input_type;
        method.output_type = output_type;
        descriptor_.methods.push_back(std::move(method));
        bidi_streaming_handlers_[method_name] = std::move(handler);
        return ok();
    }
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::protocols::grpc::bidi_streaming, bidi_streaming_handlers_, kcenon::network::protocols::grpc::build_method_path(), descriptor_, kcenon::network::error_void(), kcenon::network::protocols::grpc::method_descriptor::full_name, kcenon::network::protocols::grpc::service_descriptor::full_name(), kcenon::network::protocols::grpc::method_descriptor::input_type, kcenon::network::protocols::grpc::service_descriptor::methods, mutex_, kcenon::network::protocols::grpc::method_descriptor::name, kcenon::network::protocols::grpc::ok, kcenon::network::protocols::grpc::method_descriptor::output_type, and kcenon::network::protocols::grpc::method_descriptor::type.
register_client_streaming_method()
auto kcenon::network::protocols::grpc::generic_service::impl::register_client_streaming_method (const std::string & method_name, client_streaming_handler handler, const std::string & input_type, const std::string & output_type) -> VoidResult inline
Definition at line 156 of file service_registry.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (client_streaming_handlers_.find(method_name) != client_streaming_handlers_.end())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "Method already registered: " + method_name,
                "generic_service");
        }
        method_descriptor method;
        method.name = method_name;
        method.full_name = build_method_path(descriptor_.full_name(), method_name);
        method.type = method_type::client_streaming;
        method.input_type = input_type;
        method.output_type = output_type;
        descriptor_.methods.push_back(std::move(method));
        client_streaming_handlers_[method_name] = std::move(handler);
        return ok();
    }
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::protocols::grpc::build_method_path(), kcenon::network::protocols::grpc::client_streaming, client_streaming_handlers_, descriptor_, kcenon::network::error_void(), kcenon::network::protocols::grpc::method_descriptor::full_name, kcenon::network::protocols::grpc::service_descriptor::full_name(), kcenon::network::protocols::grpc::method_descriptor::input_type, kcenon::network::protocols::grpc::service_descriptor::methods, mutex_, kcenon::network::protocols::grpc::method_descriptor::name, kcenon::network::protocols::grpc::ok, kcenon::network::protocols::grpc::method_descriptor::output_type, and kcenon::network::protocols::grpc::method_descriptor::type.
register_server_streaming_method()
auto kcenon::network::protocols::grpc::generic_service::impl::register_server_streaming_method (const std::string & method_name, server_streaming_handler handler, const std::string & input_type, const std::string & output_type) -> VoidResult inline
Definition at line 127 of file service_registry.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (server_streaming_handlers_.find(method_name) != server_streaming_handlers_.end())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "Method already registered: " + method_name,
                "generic_service");
        }
        method_descriptor method;
        method.name = method_name;
        method.full_name = build_method_path(descriptor_.full_name(), method_name);
        method.type = method_type::server_streaming;
        method.input_type = input_type;
        method.output_type = output_type;
        descriptor_.methods.push_back(std::move(method));
        server_streaming_handlers_[method_name] = std::move(handler);
        return ok();
    }
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::protocols::grpc::build_method_path(), descriptor_, kcenon::network::error_void(), kcenon::network::protocols::grpc::method_descriptor::full_name, kcenon::network::protocols::grpc::service_descriptor::full_name(), kcenon::network::protocols::grpc::method_descriptor::input_type, kcenon::network::protocols::grpc::service_descriptor::methods, mutex_, kcenon::network::protocols::grpc::method_descriptor::name, kcenon::network::protocols::grpc::ok, kcenon::network::protocols::grpc::method_descriptor::output_type, kcenon::network::protocols::grpc::server_streaming, server_streaming_handlers_, and kcenon::network::protocols::grpc::method_descriptor::type.
register_unary_method()
auto kcenon::network::protocols::grpc::generic_service::impl::register_unary_method (const std::string & method_name, unary_handler handler, const std::string & input_type, const std::string & output_type) -> VoidResult inline
Definition at line 97 of file service_registry.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (unary_handlers_.find(method_name) != unary_handlers_.end())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "Method already registered: " + method_name,
                "generic_service");
        }
        // Create method descriptor
        method_descriptor method;
        method.name = method_name;
        method.full_name = build_method_path(descriptor_.full_name(), method_name);
        method.type = method_type::unary;
        method.input_type = input_type;
        method.output_type = output_type;
        descriptor_.methods.push_back(std::move(method));
        unary_handlers_[method_name] = std::move(handler);
        return ok();
    }
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::protocols::grpc::build_method_path(), descriptor_, kcenon::network::error_void(), kcenon::network::protocols::grpc::method_descriptor::full_name, kcenon::network::protocols::grpc::service_descriptor::full_name(), kcenon::network::protocols::grpc::method_descriptor::input_type, kcenon::network::protocols::grpc::service_descriptor::methods, mutex_, kcenon::network::protocols::grpc::method_descriptor::name, kcenon::network::protocols::grpc::ok, kcenon::network::protocols::grpc::method_descriptor::output_type, kcenon::network::protocols::grpc::method_descriptor::type, kcenon::network::protocols::grpc::unary, and unary_handlers_.
Member Data Documentation
bidi_streaming_handlers_
std::unordered_map<std::string, bidi_streaming_handler> kcenon::network::protocols::grpc::generic_service::impl::bidi_streaming_handlers_ private
Definition at line 253 of file service_registry.cpp.
Referenced by get_bidi_streaming_handler(), and register_bidi_streaming_method().
client_streaming_handlers_
std::unordered_map<std::string, client_streaming_handler> kcenon::network::protocols::grpc::generic_service::impl::client_streaming_handlers_ private
Definition at line 252 of file service_registry.cpp.
Referenced by get_client_streaming_handler(), and register_client_streaming_method().
descriptor_
service_descriptor kcenon::network::protocols::grpc::generic_service::impl::descriptor_ private
Definition at line 247 of file service_registry.cpp.
Referenced by descriptor(), impl(), register_bidi_streaming_method(), register_client_streaming_method(), register_server_streaming_method(), and register_unary_method().
mutex_
std::mutex kcenon::network::protocols::grpc::generic_service::impl::mutex_ mutable private
Definition at line 248 of file service_registry.cpp.
Referenced by get_bidi_streaming_handler(), get_client_streaming_handler(), get_server_streaming_handler(), get_unary_handler(), register_bidi_streaming_method(), register_client_streaming_method(), register_server_streaming_method(), and register_unary_method().
server_streaming_handlers_
std::unordered_map<std::string, server_streaming_handler> kcenon::network::protocols::grpc::generic_service::impl::server_streaming_handlers_ private
Definition at line 251 of file service_registry.cpp.
Referenced by get_server_streaming_handler(), and register_server_streaming_method().
unary_handlers_
std::unordered_map<std::string, unary_handler> kcenon::network::protocols::grpc::generic_service::impl::unary_handlers_ private
Definition at line 250 of file service_registry.cpp.
Referenced by get_unary_handler(), and register_unary_method().
The documentation for this class was generated from the following file:
src/protocols/grpc/service_registry.cpp