Network System: kcenon::network::core::network_context Class Reference
kcenon::network::core::network_context Class Reference export
module kcenon.network
Global context for shared network system resources.
#include <network_context.h>
Classes
class impl
Public Member Functions
void set_thread_pool (std::shared_ptr< kcenon::network::integration::thread_pool_interface > pool)
Set custom thread pool.
std::shared_ptr< kcenon::network::integration::thread_pool_interface > get_thread_pool ()
Get current thread pool.
void set_logger (std::shared_ptr< kcenon::network::integration::logger_interface > logger)
Set custom logger.
std::shared_ptr< kcenon::network::integration::logger_interface > get_logger ()
Get current logger.
void set_monitoring (std::shared_ptr< kcenon::network::integration::monitoring_interface > monitoring)
Set custom monitoring system.
std::shared_ptr< kcenon::network::integration::monitoring_interface > get_monitoring ()
Get current monitoring system.
void initialize (size_t thread_count=0)
Initialize all systems.
void shutdown ()
Shutdown all systems.
bool is_initialized () const
Check if context is initialized.
void set_thread_pool (std::shared_ptr< integration::thread_pool_interface > pool)
Set custom thread pool.
std::shared_ptr< integration::thread_pool_interface > get_thread_pool ()
Get current thread pool.
void set_logger (std::shared_ptr< integration::logger_interface > logger)
Set custom logger.
std::shared_ptr< integration::logger_interface > get_logger ()
Get current logger.
void set_monitoring (std::shared_ptr< integration::monitoring_interface > monitoring)
Set custom monitoring system.
std::shared_ptr< integration::monitoring_interface > get_monitoring ()
Get current monitoring system.
integration::io_context_thread_manager & get_io_context_manager ()
Get the io_context thread manager.
void reset ()
Reset all resources to defaults.
Static Public Member Functions
static network_context & instance ()
Get the singleton instance.
static network_context & instance ()
Get the singleton instance.
Private Member Functions
network_context ()
~network_context ()
network_context (const network_context &)=delete
network_context & operator= (const network_context &)=delete
network_context (network_context &&)=delete
network_context & operator= (network_context &&)=delete
network_context ()
~network_context ()=default
network_context (const network_context &)=delete
network_context & operator= (const network_context &)=delete
Private Attributes
std::shared_ptr< impl > pimpl_
PIMPL pointer with intentional leak pattern.
std::shared_ptr< integration::thread_pool_interface > thread_pool_
std::shared_ptr< integration::logger_interface > logger_
std::shared_ptr< integration::monitoring_interface > monitoring_
std::unique_ptr< integration::io_context_thread_manager > io_manager_
std::shared_mutex mutex_
Detailed Description
Global context for shared network system resources.
This class manages shared resources like thread pools, loggers, and monitoring across all network system components. It follows the singleton pattern.
Definition at line 252 of file core.cppm.
Constructor & Destructor Documentation
network_context() [1/5]
kcenon::network::core::network_context::network_context () private
Definition at line 41 of file network_context.cpp.
    : pimpl_(new impl(), [](impl*) { /* no-op deleter - intentional leak */ }) {
}
~network_context() [1/2]
kcenon::network::core::network_context::~network_context () private
Definition at line 49 of file network_context.cpp.
{
    // Note: With Intentional Leak pattern, shutdown() is never called
    // during static destruction. The OS reclaims all resources on exit.
    // This prevents heap corruption from thread pool destruction order issues.
}
network_context() [2/5]
kcenon::network::core::network_context::network_context (const network_context &) private delete
network_context() [3/5]
kcenon::network::core::network_context::network_context (network_context &&) private delete
network_context() [4/5]
kcenon::network::core::network_context::network_context () export private
~network_context() [2/2]
kcenon::network::core::network_context::~network_context () export private default
network_context() [5/5]
kcenon::network::core::network_context::network_context (const network_context &) export private delete
Member Function Documentation
get_io_context_manager()
integration::io_context_thread_manager & kcenon::network::core::network_context::get_io_context_manager () export
Get the io_context thread manager.
Returns
Reference to the io_context thread manager
get_logger() [1/2]
std::shared_ptr< integration::logger_interface > kcenon::network::core::network_context::get_logger ()
Get current logger.
Returns
Shared pointer to logger interface
Definition at line 179 of file network_context.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->mutex_);
    return pimpl_->logger_;
}
References pimpl_.
get_logger() [2/2]
std::shared_ptr< integration::logger_interface > kcenon::network::core::network_context::get_logger () export
Get current logger.
Returns
Shared pointer to logger interface
get_monitoring() [1/2]
std::shared_ptr< integration::monitoring_interface > kcenon::network::core::network_context::get_monitoring ()
Get current monitoring system.
Returns
Shared pointer to monitoring interface
Note: Since issue #342, metrics are also published via EventBus. External consumers can subscribe to network_metric_event instead of using this interface directly.
Definition at line 191 of file network_context.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->mutex_);
    if (!pimpl_->monitoring_) {
        // Return the default from integration manager
        return integration::monitoring_integration_manager::instance().get_monitoring();
    }
    return pimpl_->monitoring_;
}
References kcenon::network::integration::monitoring_integration_manager::get_monitoring(), kcenon::network::integration::monitoring_integration_manager::instance(), and pimpl_.
get_monitoring() [2/2]
std::shared_ptr< integration::monitoring_interface > kcenon::network::core::network_context::get_monitoring () export
Get current monitoring system.
Returns
Shared pointer to monitoring interface
get_thread_pool() [1/2]
std::shared_ptr< integration::thread_pool_interface > kcenon::network::core::network_context::get_thread_pool ()
Get current thread pool.
Returns
Shared pointer to thread pool interface
Definition at line 168 of file network_context.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->mutex_);
    return pimpl_->thread_pool_;
}
References pimpl_.
Referenced by kcenon::network::core::messaging_quic_client::do_start_impl(), kcenon::network::core::messaging_quic_server::do_start_impl(), kcenon::network::core::messaging_udp_client::do_start_impl(), kcenon::network::core::messaging_udp_server::do_start_impl(), kcenon::network::core::messaging_ws_client::do_start_impl(), kcenon::network::core::messaging_ws_server::do_start_impl(), kcenon::network::core::secure_messaging_client::do_start_impl(), kcenon::network::core::secure_messaging_server::do_start_impl(), kcenon::network::core::secure_messaging_udp_client::do_start_impl(), kcenon::network::integration::io_context_thread_manager::impl::get_thread_pool(), kcenon::network::core::reliable_udp_client::impl::start_retransmission_timer(), and kcenon::network::core::secure_messaging_udp_server::start_server().
get_thread_pool() [2/2]
std::shared_ptr< integration::thread_pool_interface > kcenon::network::core::network_context::get_thread_pool () export
Get current thread pool.
Returns
Shared pointer to thread pool interface
initialize()
void kcenon::network::core::network_context::initialize (size_t thread_count = 0)
Initialize all systems.
Parameters
thread_count Number of worker threads (0 = auto-detect)
Definition at line 60 of file network_context.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->mutex_);
    if (pimpl_->initialized_) {
        return;
    }
    // Initialize thread pool if not already set
    if (!pimpl_->thread_pool_) {
        if (thread_count == 0) {
            thread_count = std::thread::hardware_concurrency();
            if (thread_count == 0) {
                thread_count = 2; // Fallback
            }
        }
#if KCENON_WITH_THREAD_SYSTEM
        // Use thread_system's thread_pool via adapter
        try {
            auto adapter = integration::thread_system_pool_adapter::from_service_or_default("network_pool");
            if (adapter && adapter->is_running()) {
                pimpl_->thread_pool_ = adapter;
                pimpl_->owns_thread_pool_ = false; // Managed by thread_system
            } else {
                // Fallback to basic pool if thread_system pool is not available
                pimpl_->thread_pool_ = std::make_shared<integration::basic_thread_pool>(thread_count);
                pimpl_->owns_thread_pool_ = true;
            }
        } catch (...) {
            // If thread_system integration fails, use basic pool
            pimpl_->thread_pool_ = std::make_shared<integration::basic_thread_pool>(thread_count);
            pimpl_->owns_thread_pool_ = true;
        }
#else
        // Use basic thread pool when thread_system is not available
        pimpl_->thread_pool_ = std::make_shared<integration::basic_thread_pool>(thread_count);
        pimpl_->owns_thread_pool_ = true;
#endif
    }
    // Initialize logger if not already set
    // Issue #285: Uses common_system_logger_adapter when available, basic_logger otherwise
    if (!pimpl_->logger_) {
#if KCENON_WITH_COMMON_SYSTEM
        pimpl_->logger_ = std::make_shared<integration::common_system_logger_adapter>();
#else
        pimpl_->logger_ = std::make_shared<integration::basic_logger>(
            integration::log_level::info);
#endif
        integration::logger_integration_manager::instance().set_logger(pimpl_->logger_);
    }
    // Initialize monitoring if not already set
    // Note: Uses basic_monitoring by default. Metrics are also published via EventBus.
    if (!pimpl_->monitoring_) {
        pimpl_->monitoring_ = integration::monitoring_integration_manager::instance().get_monitoring();
    }
    pimpl_->initialized_ = true;
    if (pimpl_->logger_) {
        pimpl_->logger_->log(
            integration::log_level::info,
            "network_context initialized with " + std::to_string(thread_count) + " threads"
        );
    }
}
References kcenon::network::integration::monitoring_integration_manager::get_monitoring(), kcenon::network::integration::info, kcenon::network::integration::logger_integration_manager::instance(), kcenon::network::integration::monitoring_integration_manager::instance(), pimpl_, and kcenon::network::integration::logger_integration_manager::set_logger().
instance() [1/2]
network_context & kcenon::network::core::network_context::instance () static
Get the singleton instance.
Returns
Reference to the singleton instance
Definition at line 55 of file network_context.cpp.
{
    static network_context ctx;
    return ctx;
}
Referenced by kcenon::network::core::messaging_quic_client::do_start_impl(), kcenon::network::core::messaging_quic_server::do_start_impl(), kcenon::network::core::messaging_udp_client::do_start_impl(), kcenon::network::core::messaging_udp_server::do_start_impl(), kcenon::network::core::messaging_ws_client::do_start_impl(), kcenon::network::core::messaging_ws_server::do_start_impl(), kcenon::network::core::secure_messaging_client::do_start_impl(), kcenon::network::core::secure_messaging_server::do_start_impl(), kcenon::network::core::secure_messaging_udp_client::do_start_impl(), kcenon::network::integration::io_context_thread_manager::impl::get_thread_pool(), kcenon::network::initialize(), kcenon::network::initialize(), kcenon::network::shutdown(), kcenon::network::core::reliable_udp_client::impl::start_retransmission_timer(), and kcenon::network::core::secure_messaging_udp_server::start_server().
instance() [2/2]
static network_context & kcenon::network::core::network_context::instance () static export
Get the singleton instance.
Returns
Reference to the singleton instance
is_initialized()
bool kcenon::network::core::network_context::is_initialized () const
Check if context is initialized.
Returns
true if initialized, false otherwise
Definition at line 157 of file network_context.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->mutex_);
    return pimpl_->initialized_;
}
References pimpl_.
operator=() [1/3]
network_context & kcenon::network::core::network_context::operator= (const network_context &) private delete
operator=() [2/3]
network_context & kcenon::network::core::network_context::operator= (const network_context &) export private delete
operator=() [3/3]
network_context & kcenon::network::core::network_context::operator= (network_context &&) private delete
reset()
void kcenon::network::core::network_context::reset () export
Reset all resources to defaults.
set_logger() [1/2]
void kcenon::network::core::network_context::set_logger (std::shared_ptr< integration::logger_interface > logger) export
Set custom logger.
Parameters
logger Logger implementation
set_logger() [2/2]
void kcenon::network::core::network_context::set_logger (std::shared_ptr< kcenon::network::integration::logger_interface > logger)
Set custom logger.
Parameters
logger Logger implementation
Definition at line 173 of file network_context.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->mutex_);
    pimpl_->logger_ = logger;
    integration::logger_integration_manager::instance().set_logger(logger);
}
References kcenon::network::integration::logger_integration_manager::instance(), pimpl_, and kcenon::network::integration::logger_integration_manager::set_logger().
set_monitoring() [1/2]
void kcenon::network::core::network_context::set_monitoring (std::shared_ptr< integration::monitoring_interface > monitoring) export
Set custom monitoring system.
Parameters
monitoring Monitoring implementation
set_monitoring() [2/2]
void kcenon::network::core::network_context::set_monitoring (std::shared_ptr< kcenon::network::integration::monitoring_interface > monitoring)
Set custom monitoring system.
Parameters
monitoring Monitoring implementation
Note: Since issue #342, metrics are also published via EventBus. External consumers can subscribe to network_metric_event instead of using this interface directly.
Definition at line 184 of file network_context.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->mutex_);
    pimpl_->monitoring_ = monitoring;
    // Also update the integration manager for backward compatibility
    integration::monitoring_integration_manager::instance().set_monitoring(monitoring);
}
References kcenon::network::integration::monitoring_integration_manager::instance(), pimpl_, and kcenon::network::integration::monitoring_integration_manager::set_monitoring().
set_thread_pool() [1/2]
void kcenon::network::core::network_context::set_thread_pool (std::shared_ptr< integration::thread_pool_interface > pool) export
Set custom thread pool.
Parameters
pool Thread pool implementation
set_thread_pool() [2/2]
void kcenon::network::core::network_context::set_thread_pool (std::shared_ptr< kcenon::network::integration::thread_pool_interface > pool)
Set custom thread pool.
Parameters
pool Thread pool implementation
Definition at line 162 of file network_context.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->mutex_);
    pimpl_->thread_pool_ = pool;
    pimpl_->owns_thread_pool_ = false;
}
References pimpl_.
shutdown()
void kcenon::network::core::network_context::shutdown ()
Shutdown all systems.
Definition at line 128 of file network_context.cpp.
{
    std::lock_guard<std::mutex> lock(pimpl_->mutex_);
    if (!pimpl_->initialized_) {
        return;
    }
    if (pimpl_->logger_) {
        pimpl_->logger_->log(integration::log_level::info, "network_context shutting down");
    }
    if (pimpl_->monitoring_) {
        pimpl_->monitoring_.reset();
    }
    // Only stop thread pool if we own it
    if (pimpl_->owns_thread_pool_ && pimpl_->thread_pool_) {
        // Try to stop the thread pool if it's a basic_thread_pool
        if (auto* basic_pool = dynamic_cast<integration::basic_thread_pool*>(pimpl_->thread_pool_.get())) {
            basic_pool->stop(true);
        }
        pimpl_->thread_pool_.reset();
    }
    // Don't reset logger as it may be used during shutdown logging
    // Just mark as not initialized
    pimpl_->initialized_ = false;
}
References kcenon::network::integration::info, and pimpl_.
Member Data Documentation
io_manager_
std::unique_ptr<integration::io_context_thread_manager> kcenon::network::core::network_context::io_manager_ export private
Definition at line 318 of file core.cppm.
logger_
std::shared_ptr<integration::logger_interface> kcenon::network::core::network_context::logger_ export private
Definition at line 316 of file core.cppm.
monitoring_
std::shared_ptr<integration::monitoring_interface> kcenon::network::core::network_context::monitoring_ export private
Definition at line 317 of file core.cppm.
mutex_
std::shared_mutex kcenon::network::core::network_context::mutex_ mutable export private
Definition at line 319 of file core.cppm.
pimpl_
std::shared_ptr<impl> kcenon::network::core::network_context::pimpl_ private
PIMPL pointer with intentional leak pattern.
Uses shared_ptr with no-op deleter to prevent heap corruption during static destruction. This is intentional - see docs/DESIGN_DECISIONS.md for detailed rationale.
Note
Memory is intentionally not freed. This is safe because:
Only ~100-200 bytes per instance
Process terminates immediately after static destruction
OS reclaims all process memory on exit
Warning
Do not "fix" this by changing to unique_ptr or adding a real deleter. Doing so will cause heap corruption on shutdown.
See also
docs/DESIGN_DECISIONS.md#intentional-leak-pattern
Definition at line 129 of file network_context.h.
Referenced by get_logger(), get_monitoring(), get_thread_pool(), initialize(), is_initialized(), set_logger(), set_monitoring(), set_thread_pool(), and shutdown().
thread_pool_
std::shared_ptr<integration::thread_pool_interface> kcenon::network::core::network_context::thread_pool_ export private
Definition at line 315 of file core.cppm.
The documentation for this class was generated from the following files:
src/internal/core/network_context.h
src/modules/core.cppm
src/core/network_context.cpp