Network System: kcenon::network::integration::basic_monitoring Class Reference
kcenon::network::integration::basic_monitoring Class Reference
Basic monitoring implementation for standalone use.
#include <monitoring_integration.h>
Classes
class impl
Public Member Functions
basic_monitoring (bool enable_logging=true)
Constructor.
~basic_monitoring () override
void report_counter (const std::string &name, double value, const std::map< std::string, std::string > &labels={}) override
Report a counter metric.
void report_gauge (const std::string &name, double value, const std::map< std::string, std::string > &labels={}) override
Report a gauge metric.
void report_histogram (const std::string &name, double value, const std::map< std::string, std::string > &labels={}) override
Report a histogram metric.
void report_health (const std::string &connection_id, bool is_alive, double response_time_ms, size_t missed_heartbeats, double packet_loss_rate) override
Report connection health metrics.
void set_logging_enabled (bool enabled)
Enable or disable logging.
bool is_logging_enabled () const
Check if logging is enabled.
Public Member Functions inherited from kcenon::network::integration::monitoring_interface
virtual ~monitoring_interface ()=default
virtual ~monitoring_interface ()=default
virtual void record_counter (std::string_view name, int64_t value)=0
Record a counter metric.
virtual void record_gauge (std::string_view name, double value)=0
Record a gauge metric.
virtual void record_histogram (std::string_view name, double value)=0
Record a histogram metric.
Private Attributes
std::unique_ptr< impl > pimpl_
Detailed Description
Basic monitoring implementation for standalone use.
This provides a simple monitoring implementation for when monitoring_system is not available. Logs metrics to console.
Definition at line 104 of file monitoring_integration.h.
Constructor & Destructor Documentation
basic_monitoring()
kcenon::network::integration::basic_monitoring::basic_monitoring (bool enable_logging = true) explicit
Constructor.
Parameters
enable_logging Enable console logging (default: true)
Definition at line 120 of file monitoring_integration.cpp.
        : pimpl_(std::make_unique<impl>(enable_logging))
    {
    }
~basic_monitoring()
kcenon::network::integration::basic_monitoring::~basic_monitoring () override default
Member Function Documentation
is_logging_enabled()
bool kcenon::network::integration::basic_monitoring::is_logging_enabled () const
Check if logging is enabled.
Returns
true if logging is enabled
Definition at line 158 of file monitoring_integration.cpp.
{ return pimpl_->is_logging_enabled(); }
References kcenon::network::integration::basic_monitoring::impl::is_logging_enabled(), and pimpl_.
report_counter()
void kcenon::network::integration::basic_monitoring::report_counter (const std::string & name, double value, const std::map< std::string, std::string > & labels = {}) override virtual
Report a counter metric.
Parameters
name Metric name
value Counter value
labels Optional labels for the metric
Implements kcenon::network::integration::monitoring_interface.
Definition at line 127 of file monitoring_integration.cpp.
    {
        pimpl_->report_counter(name, value, labels);
    }
References pimpl_, and kcenon::network::integration::basic_monitoring::impl::report_counter().
report_gauge()
void kcenon::network::integration::basic_monitoring::report_gauge (const std::string & name, double value, const std::map< std::string, std::string > & labels = {}) override virtual
Report a gauge metric.
Parameters
name Metric name
value Gauge value
labels Optional labels for the metric
Implements kcenon::network::integration::monitoring_interface.
Definition at line 133 of file monitoring_integration.cpp.
    {
        pimpl_->report_gauge(name, value, labels);
    }
References pimpl_, and kcenon::network::integration::basic_monitoring::impl::report_gauge().
report_health()
void kcenon::network::integration::basic_monitoring::report_health (const std::string & connection_id, bool is_alive, double response_time_ms, size_t missed_heartbeats, double packet_loss_rate) override virtual
Report connection health metrics.
Parameters
connection_id Connection identifier
is_alive Connection alive status
response_time_ms Response time in milliseconds
missed_heartbeats Number of missed heartbeats
packet_loss_rate Packet loss rate (0.0-1.0)
Implements kcenon::network::integration::monitoring_interface.
Definition at line 145 of file monitoring_integration.cpp.
    {
        pimpl_->report_health(connection_id, is_alive, response_time_ms, missed_heartbeats,
                              packet_loss_rate);
    }
References pimpl_, and kcenon::network::integration::basic_monitoring::impl::report_health().
report_histogram()
void kcenon::network::integration::basic_monitoring::report_histogram (const std::string & name, double value, const std::map< std::string, std::string > & labels = {}) override virtual
Report a histogram metric.
Parameters
name Metric name
value Histogram value
labels Optional labels for the metric
Implements kcenon::network::integration::monitoring_interface.
Definition at line 139 of file monitoring_integration.cpp.
    {
        pimpl_->report_histogram(name, value, labels);
    }
References pimpl_, and kcenon::network::integration::basic_monitoring::impl::report_histogram().
set_logging_enabled()
void kcenon::network::integration::basic_monitoring::set_logging_enabled (bool enabled)
Enable or disable logging.
Parameters
enabled New logging state
Definition at line 153 of file monitoring_integration.cpp.
    {
        pimpl_->set_logging_enabled(enabled);
    }
References enabled, pimpl_, and kcenon::network::integration::basic_monitoring::impl::set_logging_enabled().
Member Data Documentation
pimpl_
std::unique_ptr<impl> kcenon::network::integration::basic_monitoring::pimpl_ private
Definition at line 143 of file monitoring_integration.h.
Referenced by is_logging_enabled(), report_counter(), report_gauge(), report_health(), report_histogram(), and set_logging_enabled().
The documentation for this class was generated from the following files:
src/internal/integration/monitoring_integration.h
src/integration/monitoring_integration.cpp