Network System: kcenon::network::protocols::grpc::grpc_server::impl Class Reference
kcenon::network::protocols::grpc::grpc_server::impl Class Reference
Public Member Functions
impl (grpc_server_config config)
~impl ()
auto start (uint16_t port) -> VoidResult
auto start_tls (uint16_t port, const std::string &cert_path, const std::string &key_path, const std::string &ca_path) -> VoidResult
auto stop () -> void
auto wait () -> void
auto is_running () const -> bool
auto port () const -> uint16_t
auto register_service (grpc_service *service) -> VoidResult
auto register_unary_method (const std::string &full_method_name, unary_handler handler) -> VoidResult
auto register_server_streaming_method (const std::string &full_method_name, server_streaming_handler handler) -> VoidResult
auto register_client_streaming_method (const std::string &full_method_name, client_streaming_handler handler) -> VoidResult
auto register_bidi_streaming_method (const std::string &full_method_name, bidi_streaming_handler handler) -> VoidResult
Private Attributes
grpc_server_config config_
std::atomic< bool > running_
uint16_t port_
std::string cert_path_
std::string key_path_
std::string ca_path_
std::vector< grpc_service * > services_
std::unordered_map< std::string, method_handler > methods_
std::mutex mutex_
std::condition_variable stop_cv_
Detailed Description
Definition at line 613 of file server.cpp.
Constructor & Destructor Documentation
impl()
kcenon::network::protocols::grpc::grpc_server::impl::impl (grpc_server_config config) inline explicit
Definition at line 616 of file server.cpp.
        : config_(std::move(config))
        , running_(false)
        , port_(0)
    {
    }
References config.
~impl()
kcenon::network::protocols::grpc::grpc_server::impl::~impl () inline
Definition at line 623 of file server.cpp.
    {
        stop();
    }
References stop().
Member Function Documentation
is_running()
auto kcenon::network::protocols::grpc::grpc_server::impl::is_running () const -> bool inline
Definition at line 733 of file server.cpp.
    {
        return running_.load();
    }
References running_.
Referenced by kcenon::network::protocols::grpc::grpc_server::is_running().
port()
auto kcenon::network::protocols::grpc::grpc_server::impl::port () const -> uint16_t inline
Definition at line 738 of file server.cpp.
    {
        return port_;
    }
References port_.
Referenced by kcenon::network::protocols::grpc::grpc_server::port(), start(), and start_tls().
register_bidi_streaming_method()
auto kcenon::network::protocols::grpc::grpc_server::impl::register_bidi_streaming_method (const std::string & full_method_name, bidi_streaming_handler handler) -> VoidResult inline
Definition at line 872 of file server.cpp.
    {
        if (full_method_name.empty() || full_method_name[0] != '/')
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Invalid method name format",
                "grpc::server");
        }
        if (!handler)
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Handler cannot be null",
                "grpc::server");
        }
        std::lock_guard<std::mutex> lock(mutex_);
        if (methods_.find(full_method_name) != methods_.end())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "Method already registered",
                "grpc::server");
        }
        method_handler mh;
        mh.type = method_type::bidi_streaming;
        mh.bidi_streaming = std::move(handler);
        methods_[full_method_name] = std::move(mh);
        return ok();
    }
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::protocols::grpc::bidi_streaming, kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, methods_, mutex_, and kcenon::network::protocols::grpc::ok.
register_client_streaming_method()
auto kcenon::network::protocols::grpc::grpc_server::impl::register_client_streaming_method (const std::string & full_method_name, client_streaming_handler handler) -> VoidResult inline
Definition at line 835 of file server.cpp.
    {
        if (full_method_name.empty() || full_method_name[0] != '/')
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Invalid method name format",
                "grpc::server");
        }
        if (!handler)
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Handler cannot be null",
                "grpc::server");
        }
        std::lock_guard<std::mutex> lock(mutex_);
        if (methods_.find(full_method_name) != methods_.end())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "Method already registered",
                "grpc::server");
        }
        method_handler mh;
        mh.type = method_type::client_streaming;
        mh.client_streaming = std::move(handler);
        methods_[full_method_name] = std::move(mh);
        return ok();
    }
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::protocols::grpc::client_streaming, kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, methods_, mutex_, and kcenon::network::protocols::grpc::ok.
register_server_streaming_method()
auto kcenon::network::protocols::grpc::grpc_server::impl::register_server_streaming_method (const std::string & full_method_name, server_streaming_handler handler) -> VoidResult inline
Definition at line 798 of file server.cpp.
    {
        if (full_method_name.empty() || full_method_name[0] != '/')
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Invalid method name format",
                "grpc::server");
        }
        if (!handler)
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Handler cannot be null",
                "grpc::server");
        }
        std::lock_guard<std::mutex> lock(mutex_);
        if (methods_.find(full_method_name) != methods_.end())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "Method already registered",
                "grpc::server");
        }
        method_handler mh;
        mh.type = method_type::server_streaming;
        mh.server_streaming = std::move(handler);
        methods_[full_method_name] = std::move(mh);
        return ok();
    }
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, methods_, mutex_, kcenon::network::protocols::grpc::ok, and kcenon::network::protocols::grpc::server_streaming.
register_service()
auto kcenon::network::protocols::grpc::grpc_server::impl::register_service (grpc_service * service) -> VoidResult inline
Definition at line 743 of file server.cpp.
    {
        if (service == nullptr)
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Service cannot be null",
                "grpc::server");
        }
        std::lock_guard<std::mutex> lock(mutex_);
        services_.push_back(service);
        return ok();
    }
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, mutex_, kcenon::network::protocols::grpc::ok, and services_.
register_unary_method()
auto kcenon::network::protocols::grpc::grpc_server::impl::register_unary_method (const std::string & full_method_name, unary_handler handler) -> VoidResult inline
Definition at line 759 of file server.cpp.
    {
        if (full_method_name.empty() || full_method_name[0] != '/')
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Invalid method name format",
                "grpc::server",
                "Method name must start with '/'");
        }
        if (!handler)
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Handler cannot be null",
                "grpc::server");
        }
        std::lock_guard<std::mutex> lock(mutex_);
        if (methods_.find(full_method_name) != methods_.end())
        {
            return error_void(
                error_codes::common_errors::already_exists,
                "Method already registered",
                "grpc::server",
                full_method_name);
        }
        method_handler mh;
        mh.type = method_type::unary;
        mh.unary = std::move(handler);
        methods_[full_method_name] = std::move(mh);
        return ok();
    }
References kcenon::network::error_codes::common_errors::already_exists, kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, methods_, mutex_, kcenon::network::protocols::grpc::ok, and kcenon::network::protocols::grpc::unary.
start()
auto kcenon::network::protocols::grpc::grpc_server::impl::start (uint16_t port) -> VoidResult inline
Definition at line 628 of file server.cpp.
    {
        auto span = tracing::is_tracing_enabled()
            ? std::make_optional(tracing::trace_context::create_span("grpc.server.start"))
            : std::nullopt;
        if (span)
        {
            span->set_attribute("rpc.system", "grpc")
                 .set_attribute("net.host.port", static_cast<int64_t>(port))
                 .set_attribute("rpc.grpc.use_tls", false);
        }
        std::lock_guard<std::mutex> lock(mutex_);
        if (running_.load())
        {
            if (span)
            {
                span->set_error("Server is already running");
            }
            return error_void(
                error_codes::network_system::server_already_running,
                "Server is already running",
                "grpc::server");
        }
        if (port == 0)
        {
            if (span)
            {
                span->set_error("Invalid port number");
            }
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Invalid port number",
                "grpc::server");
        }
        // In a full implementation, this would:
        // 1. Create HTTP/2 server socket
        // 2. Start accepting connections
        // 3. Spawn worker threads
        port_ = port;
        running_.store(true);
        return ok();
    }
References kcenon::network::tracing::trace_context::create_span(), kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, kcenon::network::tracing::is_tracing_enabled(), mutex_, kcenon::network::protocols::grpc::ok, port(), port_, running_, and kcenon::network::error_codes::network_system::server_already_running.
start_tls()
auto kcenon::network::protocols::grpc::grpc_server::impl::start_tls (uint16_t port, const std::string & cert_path, const std::string & key_path, const std::string & ca_path) -> VoidResult inline
Definition at line 677 of file server.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (running_.load())
        {
            return error_void(
                error_codes::network_system::server_already_running,
                "Server is already running",
                "grpc::server");
        }
        if (cert_path.empty() || key_path.empty())
        {
            return error_void(
                error_codes::common_errors::invalid_argument,
                "Certificate and key paths are required for TLS",
                "grpc::server");
        }
        // In a full implementation, this would configure TLS context
        cert_path_ = cert_path;
        key_path_ = key_path;
        ca_path_ = ca_path;
        port_ = port;
        running_.store(true);
        return ok();
    }
References ca_path_, cert_path_, kcenon::network::error_void(), kcenon::network::error_codes::common_errors::invalid_argument, key_path_, mutex_, kcenon::network::protocols::grpc::ok, port(), port_, running_, and kcenon::network::error_codes::network_system::server_already_running.
stop()
auto kcenon::network::protocols::grpc::grpc_server::impl::stop () -> void inline
Definition at line 711 of file server.cpp.
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (!running_.load())
        {
            return;
        }
        running_.store(false);
        port_ = 0;
        // Notify waiting threads
        stop_cv_.notify_all();
    }
References mutex_, port_, running_, and stop_cv_.
Referenced by ~impl().
wait()
auto kcenon::network::protocols::grpc::grpc_server::impl::wait () -> void inline
Definition at line 727 of file server.cpp.
    {
        std::unique_lock<std::mutex> lock(mutex_);
        stop_cv_.wait(lock, [this] { return !running_.load(); });
    }
References mutex_, running_, and stop_cv_.
Member Data Documentation
ca_path_
std::string kcenon::network::protocols::grpc::grpc_server::impl::ca_path_ private
Definition at line 916 of file server.cpp.
Referenced by start_tls().
cert_path_
std::string kcenon::network::protocols::grpc::grpc_server::impl::cert_path_ private
Definition at line 914 of file server.cpp.
Referenced by start_tls().
config_
grpc_server_config kcenon::network::protocols::grpc::grpc_server::impl::config_ private
Definition at line 910 of file server.cpp.
key_path_
std::string kcenon::network::protocols::grpc::grpc_server::impl::key_path_ private
Definition at line 915 of file server.cpp.
Referenced by start_tls().
methods_
std::unordered_map<std::string, method_handler> kcenon::network::protocols::grpc::grpc_server::impl::methods_ private
Definition at line 919 of file server.cpp.
Referenced by register_bidi_streaming_method(), register_client_streaming_method(), register_server_streaming_method(), and register_unary_method().
mutex_
std::mutex kcenon::network::protocols::grpc::grpc_server::impl::mutex_ mutable private
Definition at line 921 of file server.cpp.
Referenced by register_bidi_streaming_method(), register_client_streaming_method(), register_server_streaming_method(), register_service(), register_unary_method(), start(), start_tls(), stop(), and wait().
port_
uint16_t kcenon::network::protocols::grpc::grpc_server::impl::port_ private
Definition at line 912 of file server.cpp.
Referenced by port(), start(), start_tls(), and stop().
running_
std::atomic<bool> kcenon::network::protocols::grpc::grpc_server::impl::running_ private
Definition at line 911 of file server.cpp.
Referenced by is_running(), start(), start_tls(), stop(), and wait().
services_
std::vector<grpc_service*> kcenon::network::protocols::grpc::grpc_server::impl::services_ private
Definition at line 918 of file server.cpp.
Referenced by register_service().
stop_cv_
std::condition_variable kcenon::network::protocols::grpc::grpc_server::impl::stop_cv_ private
Definition at line 922 of file server.cpp.
Referenced by stop(), and wait().
The documentation for this class was generated from the following file:
src/protocols/grpc/server.cpp