Network System: kcenon::network::unified::adapters::tcp_listener_adapter Class Reference
kcenon::network::unified::adapters::tcp_listener_adapter Class Reference
Adapter that wraps unified_messaging_server to implement i_listener.
#include <tcp_listener_adapter.h>
Public Member Functions
tcp_listener_adapter (std::string_view listener_id)
Constructs an adapter with a unique listener ID.
~tcp_listener_adapter () override
Destructor ensures proper cleanup.
tcp_listener_adapter (const tcp_listener_adapter &)=delete
tcp_listener_adapter & operator= (const tcp_listener_adapter &)=delete
tcp_listener_adapter (tcp_listener_adapter &&)=delete
tcp_listener_adapter & operator= (tcp_listener_adapter &&)=delete
auto start (const endpoint_info &bind_address) -> VoidResult override
Starts listening for incoming connections.
auto start (uint16_t port) -> VoidResult override
Starts listening on a specific port (all interfaces)
auto stop () noexcept -> void override
Stops listening and closes all connections.
auto set_callbacks (listener_callbacks callbacks) -> void override
Sets all listener callbacks at once.
auto set_accept_callback (accept_callback_t callback) -> void override
Sets the accept callback for new connections.
auto is_listening () const noexcept -> bool override
Checks if the listener is currently listening.
auto local_endpoint () const noexcept -> endpoint_info override
Gets the local endpoint the listener is bound to.
auto connection_count () const noexcept -> size_t override
Gets the number of active connections.
auto send_to (std::string_view connection_id, std::span< const std::byte > data) -> VoidResult override
Sends data to a specific connection.
auto broadcast (std::span< const std::byte > data) -> VoidResult override
Broadcasts data to all connected clients.
auto close_connection (std::string_view connection_id) noexcept -> void override
Closes a specific connection.
auto wait_for_stop () -> void override
Blocks until the listener has stopped.
Public Member Functions inherited from kcenon::network::unified::i_listener
virtual ~i_listener ()=default
Virtual destructor.
i_listener (const i_listener &)=delete
i_listener & operator= (const i_listener &)=delete
i_listener (i_listener &&)=default
i_listener & operator= (i_listener &&)=default
Private Member Functions
auto setup_internal_callbacks () -> void
Sets up internal callbacks to bridge to unified callbacks.
auto generate_connection_id (const core::tcp_server::session_ptr &session) -> std::string
Generates a unique connection ID for a session.
Private Attributes
std::string listener_id_
std::shared_ptr< core::tcp_server > server_
std::mutex callbacks_mutex_
listener_callbacks callbacks_
accept_callback_t accept_callback_
std::mutex endpoint_mutex_
endpoint_info local_endpoint_
std::mutex sessions_mutex_
std::unordered_map< std::string, core::tcp_server::session_ptr > sessions_
std::unordered_map< void *, std::string > session_to_id_
Additional Inherited Members
Public Types inherited from kcenon::network::unified::i_listener
using accept_callback_t = std::function<void(std::unique_ptr<i_connection>)>
Callback for accepted connections.
Protected Member Functions inherited from kcenon::network::unified::i_listener
i_listener ()=default
Default constructor (only for derived classes)
Detailed Description
Adapter that wraps unified_messaging_server to implement i_listener.
This adapter bridges the existing TCP server implementation with the new unified interface, enabling protocol factory functions to return i_listener while using the battle-tested underlying implementation.
Thread Safety
Thread-safe. All methods can be called from any thread.
Connection Management
Accepted connections are tracked internally and can be accessed via send_to(), broadcast(), and close_connection() methods.
Definition at line 33 of file tcp_listener_adapter.h.
Constructor & Destructor Documentation
tcp_listener_adapter() [1/3]
kcenon::network::unified::adapters::tcp_listener_adapter::tcp_listener_adapter (std::string_view listener_id) explicit
Constructs an adapter with a unique listener ID.
Parameters
listener_id Unique identifier for this listener
Definition at line 12 of file tcp_listener_adapter.cpp.
    : listener_id_(listener_id)
    , server_(std::make_shared<core::tcp_server>(listener_id))
{
    setup_internal_callbacks();
}
References setup_internal_callbacks().
~tcp_listener_adapter()
kcenon::network::unified::adapters::tcp_listener_adapter::~tcp_listener_adapter () override
Destructor ensures proper cleanup.
Definition at line 19 of file tcp_listener_adapter.cpp.
{
    stop();
}
References stop().
tcp_listener_adapter() [2/3]
kcenon::network::unified::adapters::tcp_listener_adapter::tcp_listener_adapter (const tcp_listener_adapter &) delete
tcp_listener_adapter() [3/3]
kcenon::network::unified::adapters::tcp_listener_adapter::tcp_listener_adapter (tcp_listener_adapter &&) delete
Member Function Documentation
broadcast()
auto kcenon::network::unified::adapters::tcp_listener_adapter::broadcast (std::span< const std::byte > data) -> VoidResult nodiscard override virtual
Broadcasts data to all connected clients.
Parameters
data The data to send to all connections
Returns
VoidResult indicating success or failure
Behavior
Sends data to all currently connected clients
Returns success if at least one send succeeded
Failures on individual connections are logged but don't fail the call
Implements kcenon::network::unified::i_listener.
Definition at line 122 of file tcp_listener_adapter.cpp.
{
    std::vector<core::tcp_server::session_ptr> sessions_copy;
    {
        std::lock_guard lock(sessions_mutex_);
        sessions_copy.reserve(sessions_.size());
        for (const auto& [id, session] : sessions_) {
            if (session) {
                sessions_copy.push_back(session);
            }
        }
    }
    if (sessions_copy.empty()) {
        return ok();  // No connections, nothing to broadcast
    }
    std::vector<uint8_t> buffer(data.size());
    std::memcpy(buffer.data(), data.data(), data.size());
    bool any_success = false;
    for (const auto& session : sessions_copy) {
        std::vector<uint8_t> buffer_copy = buffer;
        auto result = session->send(std::move(buffer_copy));
        if (result.is_ok()) {
            any_success = true;
        }
    }
    if (any_success) {
        return ok();
    }
    return error_void(
        static_cast<int>(std::errc::io_error),
        "Failed to send to any connection"
    );
}
References kcenon::network::error_void(), and kcenon::network::ok().
close_connection()
auto kcenon::network::unified::adapters::tcp_listener_adapter::close_connection (std::string_view connection_id) -> void override virtual noexcept
Closes a specific connection.
Parameters
connection_id The ID of the connection to close
Triggers the on_disconnect callback for the connection.
Implements kcenon::network::unified::i_listener.
Definition at line 161 of file tcp_listener_adapter.cpp.
{
    core::tcp_server::session_ptr session;
    {
        std::lock_guard lock(sessions_mutex_);
        auto it = sessions_.find(std::string(connection_id));
        if (it != sessions_.end()) {
            session = it->second;
            if (session) {
                session_to_id_.erase(session.get());
            }
            sessions_.erase(it);
        }
    }
    // Session will be closed when its shared_ptr goes out of scope
    // or we could explicitly close it if such method exists
}
connection_count()
auto kcenon::network::unified::adapters::tcp_listener_adapter::connection_count () const -> size_t nodiscard override virtual noexcept
Gets the number of active connections.
Returns
The count of currently connected clients
Implements kcenon::network::unified::i_listener.
Definition at line 87 of file tcp_listener_adapter.cpp.
{
    std::lock_guard lock(sessions_mutex_);
    return sessions_.size();
}
References sessions_, and sessions_mutex_.
generate_connection_id()
auto kcenon::network::unified::adapters::tcp_listener_adapter::generate_connection_id (const core::tcp_server::session_ptr & session) -> std::string private
Generates a unique connection ID for a session.
Definition at line 295 of file tcp_listener_adapter.cpp.
{
    // Use the session's internal ID
    return std::string(session->id());
}
is_listening()
auto kcenon::network::unified::adapters::tcp_listener_adapter::is_listening () const -> bool nodiscard override virtual noexcept
Checks if the listener is currently listening.
Returns
true if listening for connections, false otherwise
Implements kcenon::network::unified::i_listener.
Definition at line 76 of file tcp_listener_adapter.cpp.
{
    return server_ && server_->is_running();
}
References server_.
local_endpoint()
auto kcenon::network::unified::adapters::tcp_listener_adapter::local_endpoint () const -> endpoint_info nodiscard override virtual noexcept
Gets the local endpoint the listener is bound to.
Returns
endpoint_info of the local binding
Returns valid information only when listening. Returns empty endpoint_info if not bound.
Implements kcenon::network::unified::i_listener.
Definition at line 81 of file tcp_listener_adapter.cpp.
{
    std::lock_guard lock(endpoint_mutex_);
    return local_endpoint_;
}
References endpoint_mutex_, and local_endpoint_.
operator=() [1/2]
tcp_listener_adapter & kcenon::network::unified::adapters::tcp_listener_adapter::operator= (const tcp_listener_adapter &) delete
operator=() [2/2]
tcp_listener_adapter & kcenon::network::unified::adapters::tcp_listener_adapter::operator= (tcp_listener_adapter &&) delete
send_to()
auto kcenon::network::unified::adapters::tcp_listener_adapter::send_to (std::string_view connection_id, std::span< const std::byte > data) -> VoidResult nodiscard override virtual
Sends data to a specific connection.
Parameters
connection_id The ID of the target connection
data The data to send
Returns
VoidResult indicating success or failure
Error Conditions
Returns error if connection_id not found
Returns error if send fails
Implements kcenon::network::unified::i_listener.
Definition at line 93 of file tcp_listener_adapter.cpp.
{
    core::tcp_server::session_ptr session;
    {
        std::lock_guard lock(sessions_mutex_);
        auto it = sessions_.find(std::string(connection_id));
        if (it == sessions_.end()) {
            return error_void(
                static_cast<int>(std::errc::no_such_device_or_address),
                "Connection not found: " + std::string(connection_id)
            );
        }
        session = it->second;
    }
    if (!session) {
        return error_void(
            static_cast<int>(std::errc::not_connected),
            "Session is no longer valid"
        );
    }
    std::vector<uint8_t> buffer(data.size());
    std::memcpy(buffer.data(), data.data(), data.size());
    return session->send(std::move(buffer));
}
References kcenon::network::error_void().
set_accept_callback()
auto kcenon::network::unified::adapters::tcp_listener_adapter::set_accept_callback (accept_callback_t callback) -> void override virtual
Sets the accept callback for new connections.
Parameters
callback Called when a connection is accepted
This callback receives ownership of the connection object. If set, the on_accept callback in listener_callbacks is not called.
Thread Safety
Thread-safe. Callback invoked from I/O thread.
Implements kcenon::network::unified::i_listener.
Definition at line 70 of file tcp_listener_adapter.cpp.
{
    std::lock_guard lock(callbacks_mutex_);
    accept_callback_ = std::move(callback);
}
set_callbacks()
auto kcenon::network::unified::adapters::tcp_listener_adapter::set_callbacks (listener_callbacks callbacks) -> void override virtual
Sets all listener callbacks at once.
Parameters
callbacks The callback structure with handlers
Replaces all previously set callbacks.
Thread Safety
Thread-safe, but callbacks are invoked from I/O threads.
Implements kcenon::network::unified::i_listener.
Definition at line 60 of file tcp_listener_adapter.cpp.
{
    {
        std::lock_guard lock(callbacks_mutex_);
        callbacks_ = std::move(callbacks);
    }
    setup_internal_callbacks();
}
setup_internal_callbacks()
auto kcenon::network::unified::adapters::tcp_listener_adapter::setup_internal_callbacks () -> void private
Sets up internal callbacks to bridge to unified callbacks.
Definition at line 187 of file tcp_listener_adapter.cpp.
{
    if (!server_) {
        return;
    }
    // Bridge connection callback
    server_->set_connection_callback([this](core::tcp_server::session_ptr session) {
        if (!session) {
            return;
        }
        std::string conn_id = generate_connection_id(session);
        {
            std::lock_guard lock(sessions_mutex_);
            sessions_[conn_id] = session;
            session_to_id_[session.get()] = conn_id;
        }
        // Call user callbacks
        {
            std::lock_guard lock(callbacks_mutex_);
            if (callbacks_.on_accept) {
                callbacks_.on_accept(conn_id);
            }
        }
    });
    // Bridge disconnection callback
    server_->set_disconnection_callback([this](const std::string& session_id) {
        std::string conn_id;
        {
            std::lock_guard lock(sessions_mutex_);
            // Find the connection ID by session's internal ID
            for (auto it = sessions_.begin(); it != sessions_.end(); ++it) {
                if (it->second && std::string(it->second->id()) == session_id) {
                    conn_id = it->first;
                    if (it->second) {
                        session_to_id_.erase(it->second.get());
                    }
                    sessions_.erase(it);
                    break;
                }
            }
        }
        if (!conn_id.empty()) {
            std::lock_guard lock(callbacks_mutex_);
            if (callbacks_.on_disconnect) {
                callbacks_.on_disconnect(conn_id);
            }
        }
    });
    // Bridge receive callback
    server_->set_receive_callback([this](core::tcp_server::session_ptr session,
                                         const std::vector<uint8_t>& data) {
        if (!session) {
            return;
        }
        std::string conn_id;
        {
            std::lock_guard lock(sessions_mutex_);
            auto it = session_to_id_.find(session.get());
            if (it != session_to_id_.end()) {
                conn_id = it->second;
            }
        }
        if (!conn_id.empty()) {
            std::lock_guard lock(callbacks_mutex_);
            if (callbacks_.on_data) {
                std::span<const std::byte> byte_span(
                    reinterpret_cast<const std::byte*>(data.data()),
                    data.size()
                );
                callbacks_.on_data(conn_id, byte_span);
            }
        }
    });
    // Bridge error callback
    server_->set_error_callback([this](core::tcp_server::session_ptr session,
                                       std::error_code ec) {
        if (!session) {
            return;
        }
        std::string conn_id;
        {
            std::lock_guard lock(sessions_mutex_);
            auto it = session_to_id_.find(session.get());
            if (it != session_to_id_.end()) {
                conn_id = it->second;
            }
        }
        if (!conn_id.empty()) {
            std::lock_guard lock(callbacks_mutex_);
            if (callbacks_.on_error) {
                callbacks_.on_error(conn_id, ec);
            }
        }
    });
}
Referenced by tcp_listener_adapter().
start() [1/2]
auto kcenon::network::unified::adapters::tcp_listener_adapter::start (const endpoint_info & bind_address) -> VoidResult nodiscard override virtual
Starts listening for incoming connections.
Parameters
bind_address The local address to bind to
Returns
VoidResult indicating success or failure
Behavior
Binds to the specified local address
Begins accepting incoming connections
Accepted connections are delivered via callbacks
Error Conditions
Returns error if already listening
Returns error if bind fails (e.g., address in use)
Returns error if listen fails
Thread Safety
Thread-safe. Only one start operation can succeed at a time.
Implements kcenon::network::unified::i_listener.
Definition at line 24 of file tcp_listener_adapter.cpp.
{
    if (!server_) {
        return error_void(
            static_cast<int>(std::errc::invalid_argument),
            "Server is not initialized"
        );
    }
    {
        std::lock_guard lock(endpoint_mutex_);
        local_endpoint_ = bind_address;
    }
    return server_->start_server(bind_address.port);
}
References kcenon::network::error_void().
start() [2/2]
auto kcenon::network::unified::adapters::tcp_listener_adapter::start (uint16_t port) -> VoidResult nodiscard override virtual
Starts listening on a specific port (all interfaces)
Parameters
port The port number to listen on
Returns
VoidResult indicating success or failure
Convenience overload that binds to all interfaces (0.0.0.0 / ::).
Implements kcenon::network::unified::i_listener.
Definition at line 41 of file tcp_listener_adapter.cpp.
{
    return start(endpoint_info{"0.0.0.0", port});
}
stop()
auto kcenon::network::unified::adapters::tcp_listener_adapter::stop () -> void override virtual noexcept
Stops listening and closes all connections.
Behavior
Stops accepting new connections
Closes all active connections
Triggers on_disconnect callback for each connection
Thread Safety
Thread-safe. Safe to call multiple times.
Implements kcenon::network::unified::i_listener.
Definition at line 46 of file tcp_listener_adapter.cpp.
{
    if (server_ && server_->is_running()) {
        (void)server_->stop_server();
    }
    // Clear all tracked sessions
    {
        std::lock_guard lock(sessions_mutex_);
        sessions_.clear();
        session_to_id_.clear();
    }
}
References server_, session_to_id_, sessions_, and sessions_mutex_.
Referenced by ~tcp_listener_adapter().
wait_for_stop()
auto kcenon::network::unified::adapters::tcp_listener_adapter::wait_for_stop () -> void override virtual
Blocks until the listener has stopped.
Waits for all connections to close and the listener to fully stop.
Thread Safety
Safe to call from any thread.
Implements kcenon::network::unified::i_listener.
Definition at line 180 of file tcp_listener_adapter.cpp.
{
    if (server_) {
        server_->wait_for_stop();
    }
}
Member Data Documentation
accept_callback_
accept_callback_t kcenon::network::unified::adapters::tcp_listener_adapter::accept_callback_ private
Definition at line 86 of file tcp_listener_adapter.h.
callbacks_
listener_callbacks kcenon::network::unified::adapters::tcp_listener_adapter::callbacks_ private
Definition at line 85 of file tcp_listener_adapter.h.
callbacks_mutex_
std::mutex kcenon::network::unified::adapters::tcp_listener_adapter::callbacks_mutex_ mutable private
Definition at line 84 of file tcp_listener_adapter.h.
endpoint_mutex_
std::mutex kcenon::network::unified::adapters::tcp_listener_adapter::endpoint_mutex_ mutable private
Definition at line 88 of file tcp_listener_adapter.h.
Referenced by local_endpoint().
listener_id_
std::string kcenon::network::unified::adapters::tcp_listener_adapter::listener_id_ private
Definition at line 81 of file tcp_listener_adapter.h.
local_endpoint_
endpoint_info kcenon::network::unified::adapters::tcp_listener_adapter::local_endpoint_ private
Definition at line 89 of file tcp_listener_adapter.h.
Referenced by local_endpoint().
server_
std::shared_ptr<core::tcp_server> kcenon::network::unified::adapters::tcp_listener_adapter::server_ private
Definition at line 82 of file tcp_listener_adapter.h.
Referenced by is_listening(), and stop().
session_to_id_
std::unordered_map<void*, std::string> kcenon::network::unified::adapters::tcp_listener_adapter::session_to_id_ private
Definition at line 94 of file tcp_listener_adapter.h.
Referenced by stop().
sessions_
std::unordered_map<std::string, core::tcp_server::session_ptr> kcenon::network::unified::adapters::tcp_listener_adapter::sessions_ private
Definition at line 93 of file tcp_listener_adapter.h.
Referenced by connection_count(), and stop().
sessions_mutex_
std::mutex kcenon::network::unified::adapters::tcp_listener_adapter::sessions_mutex_ mutable private
Definition at line 92 of file tcp_listener_adapter.h.
Referenced by connection_count(), and stop().
The documentation for this class was generated from the following files:
src/internal/unified/adapters/tcp_listener_adapter.h
src/unified/adapters/tcp_listener_adapter.cpp