Network System: kcenon::network::integration::NetworkSystemBridge Class Reference
kcenon::network::integration::NetworkSystemBridge Class Reference
Unified facade for all network_system integration bridges.
#include <network_system_bridge.h>
Classes
class Impl
Public Member Functions
NetworkSystemBridge ()
Default constructor.
NetworkSystemBridge (std::shared_ptr< ThreadPoolBridge > thread_pool)
Construct bridge with custom thread pool.
~NetworkSystemBridge ()
Destructor.
NetworkSystemBridge (const NetworkSystemBridge &)=delete
NetworkSystemBridge & operator= (const NetworkSystemBridge &)=delete
NetworkSystemBridge (NetworkSystemBridge &&) noexcept
NetworkSystemBridge & operator= (NetworkSystemBridge &&) noexcept
VoidResult initialize (const NetworkSystemBridgeConfig &config)
Initialize all configured bridges.
VoidResult shutdown ()
Shutdown all bridges.
bool is_initialized () const
Check if the bridge is initialized.
BridgeMetrics get_metrics () const
Get aggregated metrics from all bridges.
std::shared_ptr< ThreadPoolBridge > get_thread_pool_bridge () const
Get thread pool bridge.
std::shared_ptr< thread_pool_interface > get_thread_pool () const
Get thread pool interface.
std::shared_ptr< logger_interface > get_logger () const
Get logger interface.
std::shared_ptr< monitoring_interface > get_monitoring () const
Get monitoring interface.
VoidResult set_thread_pool_bridge (std::shared_ptr< ThreadPoolBridge > bridge)
Set custom thread pool bridge.
VoidResult set_logger (std::shared_ptr< logger_interface > logger)
Set custom logger.
VoidResult set_monitoring (std::shared_ptr< monitoring_interface > monitoring)
Set custom monitoring.
Static Public Member Functions
static std::shared_ptr< NetworkSystemBridge > create_default ()
Create bridge with default configuration.
static std::shared_ptr< NetworkSystemBridge > with_thread_system (const std::string &pool_name="network_pool")
Create bridge with thread_system integration.
static std::shared_ptr< NetworkSystemBridge > with_custom (std::shared_ptr< thread_pool_interface > thread_pool=nullptr, std::shared_ptr< logger_interface > logger=nullptr, std::shared_ptr< monitoring_interface > monitoring=nullptr)
Create bridge with custom components.
Private Attributes
std::unique_ptr< Impl > pimpl_
Detailed Description
Unified facade for all network_system integration bridges.
This class provides a single entry point for managing all external system integrations in network_system. It consolidates thread pool, logger, and monitoring integrations into a unified interface.
Key Features:
Single initialization point for all integrations
Factory methods for common scenarios
Thread-safe access to bridge components
Centralized lifecycle management
Metrics aggregation from all bridges
Lifecycle:
Create using factory method or direct constructor
Call initialize() with configuration
Access bridge components via getters
Call shutdown() before destruction
Thread Safety:
All public methods are thread-safe
initialize() and shutdown() can be called from multiple threads
Getters are thread-safe after initialization
Definition at line 174 of file network_system_bridge.h.
Constructor & Destructor Documentation
NetworkSystemBridge() [1/4]
kcenon::network::integration::NetworkSystemBridge::NetworkSystemBridge ()
Default constructor.
Creates a bridge with default settings. All integrations are disabled until explicitly configured and initialized.
Definition at line 231 of file network_system_bridge.cpp.
    : pimpl_(std::make_unique<Impl>()) {
}
NetworkSystemBridge() [2/4]
kcenon::network::integration::NetworkSystemBridge::NetworkSystemBridge (std::shared_ptr< ThreadPoolBridge > thread_pool) explicit
Construct bridge with custom thread pool.
Parameters
thread_pool Thread pool bridge to use
Creates a bridge with a specific thread pool bridge. Other integrations can be added via set_* methods.
Definition at line 235 of file network_system_bridge.cpp.
    : pimpl_(std::make_unique<Impl>()) {
    pimpl_->set_thread_pool_bridge(std::move(thread_pool));
}
References pimpl_.
~NetworkSystemBridge()
kcenon::network::integration::NetworkSystemBridge::~NetworkSystemBridge () default
Destructor.
Automatically calls shutdown() if initialized
NetworkSystemBridge() [3/4]
kcenon::network::integration::NetworkSystemBridge::NetworkSystemBridge (const NetworkSystemBridge &) delete
NetworkSystemBridge() [4/4]
kcenon::network::integration::NetworkSystemBridge::NetworkSystemBridge (NetworkSystemBridge &&) default noexcept
Member Function Documentation
create_default()
std::shared_ptr< NetworkSystemBridge > kcenon::network::integration::NetworkSystemBridge::create_default () static
Create bridge with default configuration.
Returns
Shared pointer to NetworkSystemBridge
Creates a bridge with:
Thread pool from thread_system (if available)
Default logger (disabled)
Default monitoring (disabled)
Example:
auto bridge = NetworkSystemBridge::create_default();
NetworkSystemBridgeConfig config;
bridge->initialize(config);
Definition at line 336 of file network_system_bridge.cpp.
{
    auto bridge = std::make_shared<NetworkSystemBridge>();
    // Try to create thread pool from thread_system if available
#if KCENON_WITH_THREAD_SYSTEM
    auto thread_pool_bridge = ThreadPoolBridge::from_thread_system("network_pool");
    bridge->set_thread_pool_bridge(thread_pool_bridge);
#endif
    return bridge;
}
References kcenon::network::integration::ThreadPoolBridge::from_thread_system().
get_logger()
std::shared_ptr< logger_interface > kcenon::network::integration::NetworkSystemBridge::get_logger () const
Get logger interface.
Returns
Shared pointer to logger, or nullptr if not configured
Definition at line 290 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return nullptr;
    }
    return pimpl_->get_logger();
}
References pimpl_.
get_metrics()
BridgeMetrics kcenon::network::integration::NetworkSystemBridge::get_metrics () const
Get aggregated metrics from all bridges.
Returns
Aggregated bridge metrics
Returns combined metrics from all initialized bridges. Custom metrics from each bridge are prefixed with the bridge name.
Definition at line 269 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return BridgeMetrics{};
    }
    return pimpl_->get_metrics();
}
References pimpl_.
get_monitoring()
std::shared_ptr< monitoring_interface > kcenon::network::integration::NetworkSystemBridge::get_monitoring () const
Get monitoring interface.
Returns
Shared pointer to monitoring, or nullptr if not configured
Definition at line 297 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return nullptr;
    }
    return pimpl_->get_monitoring();
}
References pimpl_.
get_thread_pool()
std::shared_ptr< thread_pool_interface > kcenon::network::integration::NetworkSystemBridge::get_thread_pool () const
Get thread pool interface.
Returns
Shared pointer to thread pool, or nullptr if not configured
Convenience method equivalent to:
auto bridge = get_thread_pool_bridge();
return bridge ? bridge->get_thread_pool() : nullptr;
Definition at line 283 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return nullptr;
    }
    return pimpl_->get_thread_pool();
}
References pimpl_.
get_thread_pool_bridge()
std::shared_ptr< ThreadPoolBridge > kcenon::network::integration::NetworkSystemBridge::get_thread_pool_bridge () const
Get thread pool bridge.
Returns
Shared pointer to thread pool bridge, or nullptr if not configured
Definition at line 276 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return nullptr;
    }
    return pimpl_->get_thread_pool_bridge();
}
References pimpl_.
initialize()
VoidResult kcenon::network::integration::NetworkSystemBridge::initialize (const NetworkSystemBridgeConfig & config)
Initialize all configured bridges.
Parameters
config Configuration for all bridges
Returns
ok() on success, error_info on failure
Initializes all enabled bridges according to the configuration. If any bridge fails to initialize, all previously initialized bridges are shut down and an error is returned.
Error Conditions:
Already initialized
Bridge initialization failure
Invalid configuration
Example:
NetworkSystemBridgeConfig config;
config.enable_thread_pool = true;
config.thread_pool_properties["pool_name"] = "network_pool";
auto result = bridge->initialize(config);
if (result.is_err()) {
    std::cerr << "Init failed: " << result.error().message << std::endl;
}
Definition at line 245 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return error_void(
            error_codes::common_errors::not_initialized,
            "Bridge has been moved",
            "NetworkSystemBridge::initialize");
    }
    return pimpl_->initialize(config);
}
References config, kcenon::network::error_void(), and kcenon::network::error_codes::common_errors::not_initialized.
is_initialized()
bool kcenon::network::integration::NetworkSystemBridge::is_initialized () const
Check if the bridge is initialized.
Returns
true if initialized and ready, false otherwise
Definition at line 262 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return false;
    }
    return pimpl_->is_initialized();
}
References pimpl_.
operator=() [1/2]
NetworkSystemBridge & kcenon::network::integration::NetworkSystemBridge::operator= (const NetworkSystemBridge &) delete
operator=() [2/2]
NetworkSystemBridge & kcenon::network::integration::NetworkSystemBridge::operator= (NetworkSystemBridge &&) default noexcept
set_logger()
VoidResult kcenon::network::integration::NetworkSystemBridge::set_logger (std::shared_ptr< logger_interface > logger)
Set custom logger.
Parameters
logger Logger implementation to use
Returns
ok() on success, error_info on failure
Sets a custom logger. Must be called before initialize().
Definition at line 314 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return error_void(
            error_codes::common_errors::not_initialized,
            "Bridge has been moved",
            "NetworkSystemBridge::set_logger");
    }
    return pimpl_->set_logger(std::move(logger));
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::not_initialized, and pimpl_.
set_monitoring()
VoidResult kcenon::network::integration::NetworkSystemBridge::set_monitoring (std::shared_ptr< monitoring_interface > monitoring)
Set custom monitoring.
Parameters
monitoring Monitoring implementation to use
Returns
ok() on success, error_info on failure
Sets a custom monitoring implementation. Must be called before initialize().
Definition at line 324 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return error_void(
            error_codes::common_errors::not_initialized,
            "Bridge has been moved",
            "NetworkSystemBridge::set_monitoring");
    }
    return pimpl_->set_monitoring(std::move(monitoring));
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::not_initialized, and pimpl_.
set_thread_pool_bridge()
VoidResult kcenon::network::integration::NetworkSystemBridge::set_thread_pool_bridge (std::shared_ptr< ThreadPoolBridge > bridge)
Set custom thread pool bridge.
Parameters
bridge Thread pool bridge to use
Returns
ok() on success, error_info on failure
Sets a custom thread pool bridge. Must be called before initialize().
Error Conditions:
Already initialized
Null bridge pointer
Definition at line 304 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return error_void(
            error_codes::common_errors::not_initialized,
            "Bridge has been moved",
            "NetworkSystemBridge::set_thread_pool_bridge");
    }
    return pimpl_->set_thread_pool_bridge(std::move(bridge));
}
References kcenon::network::error_void(), kcenon::network::error_codes::common_errors::not_initialized, and pimpl_.
shutdown()
VoidResult kcenon::network::integration::NetworkSystemBridge::shutdown ()
Shutdown all bridges.
Returns
ok() on success, error_info on failure
Shuts down all initialized bridges in reverse initialization order. This method is idempotent - multiple calls are safe.
Definition at line 255 of file network_system_bridge.cpp.
{
    if (!pimpl_) {
        return ok(); // Already moved or destroyed
    }
    return pimpl_->shutdown();
}
References kcenon::network::ok(), and pimpl_.
with_custom()
std::shared_ptr< NetworkSystemBridge > kcenon::network::integration::NetworkSystemBridge::with_custom (std::shared_ptr< thread_pool_interface > thread_pool = nullptr, std::shared_ptr< logger_interface > logger = nullptr, std::shared_ptr< monitoring_interface > monitoring = nullptr) static
Create bridge with custom components.
Parameters
thread_pool Custom thread pool (optional)
logger Custom logger (optional)
monitoring Custom monitoring (optional)
Returns
Shared pointer to NetworkSystemBridge
Creates a bridge with custom components.
Definition at line 390 of file network_system_bridge.cpp.
{
    auto bridge = std::make_shared<NetworkSystemBridge>();
    if (thread_pool) {
        auto thread_pool_bridge = std::make_shared<ThreadPoolBridge>(
            thread_pool, ThreadPoolBridge::BackendType::Custom);
        bridge->set_thread_pool_bridge(thread_pool_bridge);
    }
    if (logger) {
        bridge->set_logger(logger);
    }
    if (monitoring) {
        bridge->set_monitoring(monitoring);
    }
    return bridge;
}
References kcenon::network::integration::ThreadPoolBridge::Custom.
with_thread_system()
std::shared_ptr< NetworkSystemBridge > kcenon::network::integration::NetworkSystemBridge::with_thread_system (const std::string & pool_name = "network_pool") static
Create bridge with thread_system integration.
Parameters
pool_name Thread pool name (default: "network_pool")
Returns
Shared pointer to NetworkSystemBridge
Creates a bridge configured for thread_system integration.
Example:
auto bridge = NetworkSystemBridge::with_thread_system("network_pool");
NetworkSystemBridgeConfig config;
config.enable_thread_pool = true;
bridge->initialize(config);
Definition at line 348 of file network_system_bridge.cpp.
{
    auto bridge = std::make_shared<NetworkSystemBridge>();
#if KCENON_WITH_THREAD_SYSTEM
    auto thread_pool_bridge = ThreadPoolBridge::from_thread_system(pool_name);
    bridge->set_thread_pool_bridge(thread_pool_bridge);
#endif
    return bridge;
}
References kcenon::network::integration::ThreadPoolBridge::from_thread_system().
Member Data Documentation
pimpl_
std::unique_ptr<Impl> kcenon::network::integration::NetworkSystemBridge::pimpl_ private
Definition at line 404 of file network_system_bridge.h.
Referenced by get_logger(), get_metrics(), get_monitoring(), get_thread_pool(), get_thread_pool_bridge(), is_initialized(), NetworkSystemBridge(), set_logger(), set_monitoring(), set_thread_pool_bridge(), and shutdown().
The documentation for this class was generated from the following files:
include/kcenon/network/integration/network_system_bridge.h
src/integration/network_system_bridge.cpp