# Codecov Configuration for network_system
# Reference: https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: 25%  # Phase 1: Realistic baseline based on current coverage (~26%)
        threshold: 2%
    patch:
      default:
        target: auto  # Match existing coverage level for new code
        threshold: 5%

# Gradual improvement plan:
# - Phase 1 (Current): 25% project, auto patch - establish realistic baseline
# - Phase 2: 35% project, 50% patch - improve unit test coverage
# - Phase 3: 50% project, 70% patch - comprehensive coverage
# - Phase 4: 65% project, 80% patch - production-ready coverage
#
# Note: gRPC wrapper code depends on external gRPC library and is better tested
# via integration tests rather than unit tests

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "integration_tests/**/*"
  - "samples/**/*"
  - "benchmarks/**/*"
  - "build/**/*"
  - "**/test_*.cpp"
  - "**/*_test.cpp"
