var hierarchy =
[
    [ "kcenon::network::protocols::quic::ack_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ack__frame.html", null ],
    [ "kcenon::network::protocols::quic::ack_range", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ack__range.html", null ],
    [ "kcenon::network::tracing::batch_config", "structkcenon_1_1network_1_1tracing_1_1batch__config.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_client::bidi_stream", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__client_1_1bidi__stream.html", [
      [ "kcenon::network::protocols::grpc::bidi_stream_impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1bidi__stream__impl.html", null ]
    ] ],
    [ "std::bool_constant", null, [
      [ "kcenon::network::policy::is_tls_enabled< Policy >", "structkcenon_1_1network_1_1policy_1_1is__tls__enabled.html", null ],
      [ "kcenon::network::protocol::is_connection_oriented< P >", "structkcenon_1_1network_1_1protocol_1_1is__connection__oriented.html", null ],
      [ "kcenon::network::protocol::is_reliable< P >", "structkcenon_1_1network_1_1protocol_1_1is__reliable.html", null ]
    ] ],
    [ "kcenon::network::integration::BridgeConfig", "structkcenon_1_1network_1_1integration_1_1BridgeConfig.html", null ],
    [ "kcenon::network::integration::BridgeMetrics", "structkcenon_1_1network_1_1integration_1_1BridgeMetrics.html", null ],
    [ "kcenon::network::rate_limiter::bucket", "structkcenon_1_1network_1_1rate__limiter_1_1bucket.html", null ],
    [ "kcenon::network::protocols::grpc::call_options", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1call__options.html", null ],
    [ "kcenon::network::utils::callback_manager< CallbackTypes >", "classkcenon_1_1network_1_1utils_1_1callback__manager.html", null ],
    [ "kcenon::network::utils::callback_manager< connection_callback_t, disconnection_callback_t, message_callback_t, text_message_callback_t, binary_message_callback_t, error_callback_t >", "classkcenon_1_1network_1_1utils_1_1callback__manager.html", null ],
    [ "kcenon::network::utils::callback_manager< connection_callback_t, disconnection_callback_t, receive_callback_t, error_callback_t >", "classkcenon_1_1network_1_1utils_1_1callback__manager.html", null ],
    [ "kcenon::network::utils::callback_manager< connection_callback_t, disconnection_callback_t, receive_callback_t, stream_receive_callback_t, error_callback_t >", "classkcenon_1_1network_1_1utils_1_1callback__manager.html", null ],
    [ "kcenon::network::utils::callback_manager< message_callback_t, text_message_callback_t, binary_message_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t >", "classkcenon_1_1network_1_1utils_1_1callback__manager.html", null ],
    [ "kcenon::network::utils::callback_manager< receive_callback_t, client_connected_callback_t, client_disconnected_callback_t, error_callback_t >", "classkcenon_1_1network_1_1utils_1_1callback__manager.html", null ],
    [ "kcenon::network::utils::callback_manager< receive_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t >", "classkcenon_1_1network_1_1utils_1_1callback__manager.html", null ],
    [ "kcenon::network::utils::callback_manager< receive_callback_t, error_callback_t >", "classkcenon_1_1network_1_1utils_1_1callback__manager.html", null ],
    [ "kcenon::network::utils::callback_manager< receive_callback_t, stream_receive_callback_t, connected_callback_t, disconnected_callback_t, error_callback_t >", "classkcenon_1_1network_1_1utils_1_1callback__manager.html", null ],
    [ "kcenon::network::protocols::grpc::channel_credentials_config", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1channel__credentials__config.html", null ],
    [ "kcenon::network::facade::http_facade::client_config", "structkcenon_1_1network_1_1facade_1_1http__facade_1_1client__config.html", null ],
    [ "kcenon::network::facade::quic_facade::client_config", "structkcenon_1_1network_1_1facade_1_1quic__facade_1_1client__config.html", null ],
    [ "kcenon::network::facade::tcp_facade::client_config", "structkcenon_1_1network_1_1facade_1_1tcp__facade_1_1client__config.html", null ],
    [ "kcenon::network::facade::udp_facade::client_config", "structkcenon_1_1network_1_1facade_1_1udp__facade_1_1client__config.html", null ],
    [ "kcenon::network::facade::websocket_facade::client_config", "structkcenon_1_1network_1_1facade_1_1websocket__facade_1_1client__config.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_client::client_stream_writer", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__client_1_1client__stream__writer.html", [
      [ "kcenon::network::protocols::grpc::client_stream_writer_impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1client__stream__writer__impl.html", null ]
    ] ],
    [ "kcenon::network::integration::common_to_network_thread_adapter_unavailable", "structkcenon_1_1network_1_1integration_1_1common__to__network__thread__adapter__unavailable.html", null ],
    [ "kcenon::network::utils::compression_pipeline", "classkcenon_1_1network_1_1utils_1_1compression__pipeline.html", null ],
    [ "kcenon::network::protocols::quic::replay_filter::config", "structkcenon_1_1network_1_1protocols_1_1quic_1_1replay__filter_1_1config.html", null ],
    [ "kcenon::network::protocols::quic::congestion_controller", "classkcenon_1_1network_1_1protocols_1_1quic_1_1congestion__controller.html", null ],
    [ "kcenon::network::protocols::quic::connection", "classkcenon_1_1network_1_1protocols_1_1quic_1_1connection.html", null ],
    [ "kcenon::network::unified::connection_callbacks", "structkcenon_1_1network_1_1unified_1_1connection__callbacks.html", null ],
    [ "kcenon::network::protocols::quic::connection_close_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1connection__close__frame.html", null ],
    [ "kcenon::network::connection_guard", "classkcenon_1_1network_1_1connection__guard.html", null ],
    [ "kcenon::network::utils::connection_health", "structkcenon_1_1network_1_1utils_1_1connection__health.html", null ],
    [ "kcenon::network::protocols::quic::connection_id", "classkcenon_1_1network_1_1protocols_1_1quic_1_1connection__id.html", null ],
    [ "kcenon::network::protocols::quic::connection_id_entry", "structkcenon_1_1network_1_1protocols_1_1quic_1_1connection__id__entry.html", null ],
    [ "kcenon::network::protocols::quic::connection_id_manager", "classkcenon_1_1network_1_1protocols_1_1quic_1_1connection__id__manager.html", null ],
    [ "kcenon::network::unified::adapters::quic_listener_adapter::connection_info", "structkcenon_1_1network_1_1unified_1_1adapters_1_1quic__listener__adapter_1_1connection__info.html", null ],
    [ "kcenon::network::connection_limiter", "classkcenon_1_1network_1_1connection__limiter.html", null ],
    [ "kcenon::network::interfaces::connection_observer", "classkcenon_1_1network_1_1interfaces_1_1connection__observer.html", [
      [ "chat_observer", "classchat__observer.html", null ],
      [ "kcenon::network::interfaces::callback_adapter", "classkcenon_1_1network_1_1interfaces_1_1callback__adapter.html", null ],
      [ "kcenon::network::interfaces::null_connection_observer", "classkcenon_1_1network_1_1interfaces_1_1null__connection__observer.html", [
        [ "receive_only_observer", "classreceive__only__observer.html", null ]
      ] ]
    ] ],
    [ "kcenon::network::unified::connection_options", "structkcenon_1_1network_1_1unified_1_1connection__options.html", null ],
    [ "kcenon::network::core::connection_pool", "classkcenon_1_1network_1_1core_1_1connection__pool.html", null ],
    [ "kcenon::network::utils::connection_state", "classkcenon_1_1network_1_1utils_1_1connection__state.html", null ],
    [ "kcenon::network::integration::container_interface", "classkcenon_1_1network_1_1integration_1_1container__interface.html", [
      [ "kcenon::network::integration::basic_container", "classkcenon_1_1network_1_1integration_1_1basic__container.html", null ]
    ] ],
    [ "kcenon::network::integration::container_manager", "classkcenon_1_1network_1_1integration_1_1container__manager.html", null ],
    [ "kcenon::network::integration::io_context_thread_manager::impl::context_entry", "structkcenon_1_1network_1_1integration_1_1io__context__thread__manager_1_1impl_1_1context__entry.html", null ],
    [ "kcenon::network::internal::cookie", "structkcenon_1_1network_1_1internal_1_1cookie.html", null ],
    [ "kcenon::network::protocols::quic::crypto_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1crypto__frame.html", null ],
    [ "kcenon::network::protocols::quic::data_blocked_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1data__blocked__frame.html", null ],
    [ "kcenon::network::concepts::datagram_receive_guard< S >", "classkcenon_1_1network_1_1concepts_1_1datagram__receive__guard.html", null ],
    [ "kcenon::network::integration::basic_thread_pool::impl::DelayedTask", "structkcenon_1_1network_1_1integration_1_1basic__thread__pool_1_1impl_1_1DelayedTask.html", null ],
    [ "kcenon::network::core::secure_messaging_udp_server::dtls_session", "structkcenon_1_1network_1_1core_1_1secure__messaging__udp__server_1_1dtls__session.html", null ],
    [ "kcenon::network::protocols::http2::dynamic_table", "classkcenon_1_1network_1_1protocols_1_1http2_1_1dynamic__table.html", null ],
    [ "kcenon::network::protocols::quic::ecn_counts", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ecn__counts.html", null ],
    [ "kcenon::network::protocols::quic::ecn_tracker", "classkcenon_1_1network_1_1protocols_1_1quic_1_1ecn__tracker.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "kcenon::network::core::http_client", "classkcenon_1_1network_1_1core_1_1http__client.html", null ],
      [ "kcenon::network::core::http_server", "classkcenon_1_1network_1_1core_1_1http__server.html", null ],
      [ "kcenon::network::core::messaging_client", "classkcenon_1_1network_1_1core_1_1messaging__client.html", null ],
      [ "kcenon::network::core::messaging_quic_client", "classkcenon_1_1network_1_1core_1_1messaging__quic__client.html", null ],
      [ "kcenon::network::core::messaging_quic_server", "classkcenon_1_1network_1_1core_1_1messaging__quic__server.html", null ],
      [ "kcenon::network::core::messaging_server", "classkcenon_1_1network_1_1core_1_1messaging__server.html", null ],
      [ "kcenon::network::core::messaging_session", "classkcenon_1_1network_1_1core_1_1messaging__session.html", null ],
      [ "kcenon::network::core::messaging_udp_client", "classkcenon_1_1network_1_1core_1_1messaging__udp__client.html", null ],
      [ "kcenon::network::core::messaging_udp_server", "classkcenon_1_1network_1_1core_1_1messaging__udp__server.html", null ],
      [ "kcenon::network::core::messaging_ws_client", "classkcenon_1_1network_1_1core_1_1messaging__ws__client.html", null ],
      [ "kcenon::network::core::messaging_ws_server", "classkcenon_1_1network_1_1core_1_1messaging__ws__server.html", null ],
      [ "kcenon::network::core::reliable_udp_client", "classkcenon_1_1network_1_1core_1_1reliable__udp__client.html", null ],
      [ "kcenon::network::core::secure_messaging_client", "classkcenon_1_1network_1_1core_1_1secure__messaging__client.html", null ],
      [ "kcenon::network::core::secure_messaging_server", "classkcenon_1_1network_1_1core_1_1secure__messaging__server.html", null ],
      [ "kcenon::network::core::secure_messaging_udp_client", "classkcenon_1_1network_1_1core_1_1secure__messaging__udp__client.html", null ],
      [ "kcenon::network::core::secure_messaging_udp_server", "classkcenon_1_1network_1_1core_1_1secure__messaging__udp__server.html", null ],
      [ "kcenon::network::core::unified_messaging_client< Protocol, TlsPolicy >", "classkcenon_1_1network_1_1core_1_1unified__messaging__client.html", null ],
      [ "kcenon::network::core::unified_messaging_server< Protocol, TlsPolicy >", "classkcenon_1_1network_1_1core_1_1unified__messaging__server.html", null ],
      [ "kcenon::network::core::unified_udp_messaging_client< TlsPolicy >", "classkcenon_1_1network_1_1core_1_1unified__udp__messaging__client.html", null ],
      [ "kcenon::network::core::unified_udp_messaging_server< TlsPolicy >", "classkcenon_1_1network_1_1core_1_1unified__udp__messaging__server.html", null ],
      [ "kcenon::network::internal::dtls_socket", "classkcenon_1_1network_1_1internal_1_1dtls__socket.html", null ],
      [ "kcenon::network::internal::quic_socket", "classkcenon_1_1network_1_1internal_1_1quic__socket.html", null ],
      [ "kcenon::network::internal::secure_tcp_socket", "classkcenon_1_1network_1_1internal_1_1secure__tcp__socket.html", null ],
      [ "kcenon::network::internal::tcp_socket", "classkcenon_1_1network_1_1internal_1_1tcp__socket.html", null ],
      [ "kcenon::network::internal::udp_socket", "classkcenon_1_1network_1_1internal_1_1udp__socket.html", null ],
      [ "kcenon::network::internal::websocket_socket", "classkcenon_1_1network_1_1internal_1_1websocket__socket.html", null ],
      [ "kcenon::network::protocols::http2::http2_client", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__client.html", null ],
      [ "kcenon::network::protocols::http2::http2_server", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__server.html", null ],
      [ "kcenon::network::protocols::http2::http2_server_connection", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__server__connection.html", null ],
      [ "kcenon::network::session::messaging_session", "classkcenon_1_1network_1_1session_1_1messaging__session.html", null ],
      [ "kcenon::network::session::quic_session", "classkcenon_1_1network_1_1session_1_1quic__session.html", null ],
      [ "kcenon::network::session::secure_session", "classkcenon_1_1network_1_1session_1_1secure__session.html", null ],
      [ "kcenon::network::utils::buffer_pool", "classkcenon_1_1network_1_1utils_1_1buffer__pool.html", null ],
      [ "kcenon::network::utils::health_monitor", "classkcenon_1_1network_1_1utils_1_1health__monitor.html", null ]
    ] ],
    [ "kcenon::network::core::secure_messaging_udp_server::endpoint_hash", "structkcenon_1_1network_1_1core_1_1secure__messaging__udp__server_1_1endpoint__hash.html", null ],
    [ "kcenon::network::interfaces::i_udp_client::endpoint_info", "structkcenon_1_1network_1_1interfaces_1_1i__udp__client_1_1endpoint__info.html", null ],
    [ "kcenon::network::unified::endpoint_info", "structkcenon_1_1network_1_1unified_1_1endpoint__info.html", null ],
    [ "std::false_type", null, [
      [ "kcenon::network::core::session_model< SessionType >::has_close_method< T, typename >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__close__method.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_id_method< T, typename >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__id__method.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_is_connected_method< T, typename >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__is__connected__method.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_is_stopped_method< T, typename >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__is__stopped__method.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_send_method< T, typename >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__send__method.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_send_packet_method< T, typename >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__send__packet__method.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_server_id_method< T, typename >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__server__id__method.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_stop_session_method< T, typename >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__stop__session__method.html", null ]
    ] ],
    [ "kcenon::network::protocols::quic::flow_control_stats", "structkcenon_1_1network_1_1protocols_1_1quic_1_1flow__control__stats.html", null ],
    [ "kcenon::network::protocols::quic::flow_controller", "classkcenon_1_1network_1_1protocols_1_1quic_1_1flow__controller.html", null ],
    [ "kcenon::network::protocols::http2::frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1frame.html", [
      [ "kcenon::network::protocols::http2::data_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1data__frame.html", null ],
      [ "kcenon::network::protocols::http2::goaway_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1goaway__frame.html", null ],
      [ "kcenon::network::protocols::http2::headers_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1headers__frame.html", null ],
      [ "kcenon::network::protocols::http2::ping_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1ping__frame.html", null ],
      [ "kcenon::network::protocols::http2::rst_stream_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1rst__stream__frame.html", null ],
      [ "kcenon::network::protocols::http2::settings_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1settings__frame.html", null ],
      [ "kcenon::network::protocols::http2::window_update_frame", "classkcenon_1_1network_1_1protocols_1_1http2_1_1window__update__frame.html", null ]
    ] ],
    [ "kcenon::network::protocols::quic::frame_builder", "classkcenon_1_1network_1_1protocols_1_1quic_1_1frame__builder.html", null ],
    [ "kcenon::network::protocols::http2::frame_header", "structkcenon_1_1network_1_1protocols_1_1http2_1_1frame__header.html", null ],
    [ "kcenon::network::protocols::quic::frame_parser", "classkcenon_1_1network_1_1protocols_1_1quic_1_1frame__parser.html", null ],
    [ "kcenon::network::integration::function_job_unavailable", "structkcenon_1_1network_1_1integration_1_1function__job__unavailable.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_channel_config", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__channel__config.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_client", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__client.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_message", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__message.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_server", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__server.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_server_config", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__server__config.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_service", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__service.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_status", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__status.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_trailers", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__trailers.html", null ],
    [ "kcenon::network::protocols::quic::handshake_done_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1handshake__done__frame.html", null ],
    [ "kcenon::network::metrics::histogram", "classkcenon_1_1network_1_1metrics_1_1histogram.html", null ],
    [ "kcenon::network::metrics::histogram_config", "structkcenon_1_1network_1_1metrics_1_1histogram__config.html", null ],
    [ "kcenon::network::metrics::histogram_snapshot", "structkcenon_1_1network_1_1metrics_1_1histogram__snapshot.html", null ],
    [ "kcenon::network::protocols::quic::hkdf", "classkcenon_1_1network_1_1protocols_1_1quic_1_1hkdf.html", null ],
    [ "kcenon::network::protocols::http2::hpack_decoder", "classkcenon_1_1network_1_1protocols_1_1http2_1_1hpack__decoder.html", null ],
    [ "kcenon::network::protocols::http2::hpack_encoder", "classkcenon_1_1network_1_1protocols_1_1http2_1_1hpack__encoder.html", null ],
    [ "kcenon::network::protocols::http2::http2_request", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__request.html", null ],
    [ "kcenon::network::protocols::http2::http2_response", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__response.html", null ],
    [ "kcenon::network::protocols::http2::http2_server_stream", "classkcenon_1_1network_1_1protocols_1_1http2_1_1http2__server__stream.html", null ],
    [ "kcenon::network::protocols::http2::http2_settings", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__settings.html", null ],
    [ "kcenon::network::protocols::http2::http2_stream", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http2__stream.html", null ],
    [ "kcenon::network::internal::http_error", "structkcenon_1_1network_1_1internal_1_1http__error.html", null ],
    [ "kcenon::network::internal::http_error_response", "classkcenon_1_1network_1_1internal_1_1http__error__response.html", null ],
    [ "kcenon::network::facade::http_facade", "classkcenon_1_1network_1_1facade_1_1http__facade.html", null ],
    [ "kcenon::network::protocols::http2::http_header", "structkcenon_1_1network_1_1protocols_1_1http2_1_1http__header.html", null ],
    [ "kcenon::network::internal::http_parser", "classkcenon_1_1network_1_1internal_1_1http__parser.html", null ],
    [ "kcenon::network::internal::http_request", "structkcenon_1_1network_1_1internal_1_1http__request.html", null ],
    [ "kcenon::network::core::http_request_buffer", "structkcenon_1_1network_1_1core_1_1http__request__buffer.html", null ],
    [ "kcenon::network::core::http_request_context", "structkcenon_1_1network_1_1core_1_1http__request__context.html", null ],
    [ "kcenon::network::internal::http_response", "structkcenon_1_1network_1_1internal_1_1http__response.html", null ],
    [ "kcenon::network::core::http_route", "structkcenon_1_1network_1_1core_1_1http__route.html", null ],
    [ "kcenon::network::core::http_url", "structkcenon_1_1network_1_1core_1_1http__url.html", null ],
    [ "kcenon::network::unified::i_listener", "classkcenon_1_1network_1_1unified_1_1i__listener.html", [
      [ "kcenon::network::unified::adapters::quic_listener_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1quic__listener__adapter.html", null ],
      [ "kcenon::network::unified::adapters::tcp_listener_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1tcp__listener__adapter.html", null ],
      [ "kcenon::network::unified::adapters::udp_listener_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1udp__listener__adapter.html", null ],
      [ "kcenon::network::unified::adapters::ws_listener_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1ws__listener__adapter.html", null ]
    ] ],
    [ "kcenon::network::interfaces::i_network_component", "classkcenon_1_1network_1_1interfaces_1_1i__network__component.html", [
      [ "kcenon::network::interfaces::i_client", "classkcenon_1_1network_1_1interfaces_1_1i__client.html", null ],
      [ "kcenon::network::interfaces::i_protocol_client", "classkcenon_1_1network_1_1interfaces_1_1i__protocol__client.html", [
        [ "kcenon::network::core::messaging_client", "classkcenon_1_1network_1_1core_1_1messaging__client.html", null ],
        [ "kcenon::network::internal::adapters::http_client_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1http__client__adapter.html", null ],
        [ "kcenon::network::internal::adapters::quic_client_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1quic__client__adapter.html", null ],
        [ "kcenon::network::internal::adapters::udp_client_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1udp__client__adapter.html", null ],
        [ "kcenon::network::internal::adapters::ws_client_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1ws__client__adapter.html", null ]
      ] ],
      [ "kcenon::network::interfaces::i_protocol_server", "classkcenon_1_1network_1_1interfaces_1_1i__protocol__server.html", [
        [ "kcenon::network::internal::adapters::http_server_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1http__server__adapter.html", null ],
        [ "kcenon::network::internal::adapters::quic_server_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1quic__server__adapter.html", null ],
        [ "kcenon::network::internal::adapters::tcp_server_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1tcp__server__adapter.html", null ],
        [ "kcenon::network::internal::adapters::udp_server_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1udp__server__adapter.html", null ],
        [ "kcenon::network::internal::adapters::ws_server_adapter", "classkcenon_1_1network_1_1internal_1_1adapters_1_1ws__server__adapter.html", null ]
      ] ],
      [ "kcenon::network::interfaces::i_quic_client", "classkcenon_1_1network_1_1interfaces_1_1i__quic__client.html", [
        [ "kcenon::network::core::messaging_quic_client", "classkcenon_1_1network_1_1core_1_1messaging__quic__client.html", null ]
      ] ],
      [ "kcenon::network::interfaces::i_quic_server", "classkcenon_1_1network_1_1interfaces_1_1i__quic__server.html", [
        [ "kcenon::network::core::messaging_quic_server", "classkcenon_1_1network_1_1core_1_1messaging__quic__server.html", null ]
      ] ],
      [ "kcenon::network::interfaces::i_server", "classkcenon_1_1network_1_1interfaces_1_1i__server.html", null ],
      [ "kcenon::network::interfaces::i_udp_client", "classkcenon_1_1network_1_1interfaces_1_1i__udp__client.html", [
        [ "kcenon::network::core::messaging_udp_client", "classkcenon_1_1network_1_1core_1_1messaging__udp__client.html", null ],
        [ "kcenon::network::core::unified_udp_messaging_client< TlsPolicy >", "classkcenon_1_1network_1_1core_1_1unified__udp__messaging__client.html", null ]
      ] ],
      [ "kcenon::network::interfaces::i_udp_server", "classkcenon_1_1network_1_1interfaces_1_1i__udp__server.html", [
        [ "kcenon::network::core::messaging_udp_server", "classkcenon_1_1network_1_1core_1_1messaging__udp__server.html", null ],
        [ "kcenon::network::core::unified_udp_messaging_server< TlsPolicy >", "classkcenon_1_1network_1_1core_1_1unified__udp__messaging__server.html", null ]
      ] ],
      [ "kcenon::network::interfaces::i_websocket_client", "classkcenon_1_1network_1_1interfaces_1_1i__websocket__client.html", [
        [ "kcenon::network::core::messaging_ws_client", "classkcenon_1_1network_1_1core_1_1messaging__ws__client.html", null ]
      ] ],
      [ "kcenon::network::interfaces::i_websocket_server", "classkcenon_1_1network_1_1interfaces_1_1i__websocket__server.html", [
        [ "kcenon::network::core::messaging_ws_server", "classkcenon_1_1network_1_1core_1_1messaging__ws__server.html", null ]
      ] ]
    ] ],
    [ "kcenon::network::interfaces::i_session", "classkcenon_1_1network_1_1interfaces_1_1i__session.html", [
      [ "kcenon::network::interfaces::i_quic_session", "classkcenon_1_1network_1_1interfaces_1_1i__quic__session.html", [
        [ "kcenon::network::session::quic_session", "classkcenon_1_1network_1_1session_1_1quic__session.html", null ]
      ] ],
      [ "kcenon::network::interfaces::i_websocket_session", "classkcenon_1_1network_1_1interfaces_1_1i__websocket__session.html", [
        [ "kcenon::network::core::ws_connection", "classkcenon_1_1network_1_1core_1_1ws__connection.html", null ]
      ] ],
      [ "kcenon::network::internal::adapters::http_request_session", "classkcenon_1_1network_1_1internal_1_1adapters_1_1http__request__session.html", null ],
      [ "kcenon::network::internal::adapters::quic_session_wrapper", "classkcenon_1_1network_1_1internal_1_1adapters_1_1quic__session__wrapper.html", null ],
      [ "kcenon::network::internal::adapters::udp_endpoint_session", "classkcenon_1_1network_1_1internal_1_1adapters_1_1udp__endpoint__session.html", null ],
      [ "kcenon::network::internal::adapters::ws_session_wrapper", "classkcenon_1_1network_1_1internal_1_1adapters_1_1ws__session__wrapper.html", null ],
      [ "kcenon::network::session::messaging_session", "classkcenon_1_1network_1_1session_1_1messaging__session.html", null ]
    ] ],
    [ "kcenon::network::unified::i_transport", "classkcenon_1_1network_1_1unified_1_1i__transport.html", [
      [ "kcenon::network::unified::i_connection", "classkcenon_1_1network_1_1unified_1_1i__connection.html", [
        [ "kcenon::network::unified::adapters::quic_connection_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1quic__connection__adapter.html", null ],
        [ "kcenon::network::unified::adapters::tcp_connection_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1tcp__connection__adapter.html", null ],
        [ "kcenon::network::unified::adapters::udp_connection_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1udp__connection__adapter.html", null ],
        [ "kcenon::network::unified::adapters::ws_connection_adapter", "classkcenon_1_1network_1_1unified_1_1adapters_1_1ws__connection__adapter.html", null ]
      ] ]
    ] ],
    [ "kcenon::network::integration::NetworkSystemBridge::Impl", "classkcenon_1_1network_1_1integration_1_1NetworkSystemBridge_1_1Impl.html", null ],
    [ "kcenon::network::core::network_context::impl", "classkcenon_1_1network_1_1core_1_1network__context_1_1impl.html", null ],
    [ "kcenon::network::core::reliable_udp_client::impl", "classkcenon_1_1network_1_1core_1_1reliable__udp__client_1_1impl.html", null ],
    [ "kcenon::network::core::unified_session_manager::impl", "classkcenon_1_1network_1_1core_1_1unified__session__manager_1_1impl.html", null ],
    [ "kcenon::network::integration::basic_container::impl", "classkcenon_1_1network_1_1integration_1_1basic__container_1_1impl.html", null ],
    [ "kcenon::network::integration::basic_logger::impl", "classkcenon_1_1network_1_1integration_1_1basic__logger_1_1impl.html", null ],
    [ "kcenon::network::integration::basic_monitoring::impl", "classkcenon_1_1network_1_1integration_1_1basic__monitoring_1_1impl.html", null ],
    [ "kcenon::network::integration::basic_thread_pool::impl", "classkcenon_1_1network_1_1integration_1_1basic__thread__pool_1_1impl.html", null ],
    [ "kcenon::network::integration::container_manager::impl", "classkcenon_1_1network_1_1integration_1_1container__manager_1_1impl.html", null ],
    [ "kcenon::network::integration::io_context_thread_manager::impl", "classkcenon_1_1network_1_1integration_1_1io__context__thread__manager_1_1impl.html", null ],
    [ "kcenon::network::integration::logger_integration_manager::impl", "classkcenon_1_1network_1_1integration_1_1logger__integration__manager_1_1impl.html", null ],
    [ "kcenon::network::integration::messaging_bridge::impl", "classkcenon_1_1network_1_1integration_1_1messaging__bridge_1_1impl.html", null ],
    [ "kcenon::network::integration::monitoring_integration_manager::impl", "classkcenon_1_1network_1_1integration_1_1monitoring__integration__manager_1_1impl.html", null ],
    [ "kcenon::network::integration::thread_integration_manager::impl", "classkcenon_1_1network_1_1integration_1_1thread__integration__manager_1_1impl.html", null ],
    [ "kcenon::network::protocols::grpc::generic_service::impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1generic__service_1_1impl.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_client::impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__client_1_1impl.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_server::impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__server_1_1impl.html", null ],
    [ "kcenon::network::protocols::grpc::health_service::impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1health__service_1_1impl.html", null ],
    [ "kcenon::network::protocols::grpc::service_registry::impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1service__registry_1_1impl.html", null ],
    [ "kcenon::network::protocols::quic::quic_crypto::impl", "structkcenon_1_1network_1_1protocols_1_1quic_1_1quic__crypto_1_1impl.html", null ],
    [ "kcenon::network::tracing::span::impl", "structkcenon_1_1network_1_1tracing_1_1span_1_1impl.html", null ],
    [ "kcenon::network::utils::buffer_pool::impl", "classkcenon_1_1network_1_1utils_1_1buffer__pool_1_1impl.html", null ],
    [ "kcenon::network::utils::compression_pipeline::impl", "classkcenon_1_1network_1_1utils_1_1compression__pipeline_1_1impl.html", null ],
    [ "kcenon::network::integration::INetworkBridge", "classkcenon_1_1network_1_1integration_1_1INetworkBridge.html", [
      [ "kcenon::network::integration::ObservabilityBridge", "classkcenon_1_1network_1_1integration_1_1ObservabilityBridge.html", null ],
      [ "kcenon::network::integration::ThreadPoolBridge", "classkcenon_1_1network_1_1integration_1_1ThreadPoolBridge.html", null ],
      [ "kcenon::network::integration::messaging_bridge", "classkcenon_1_1network_1_1integration_1_1messaging__bridge.html", null ]
    ] ],
    [ "kcenon::network::protocols::quic::initial_keys", "classkcenon_1_1network_1_1protocols_1_1quic_1_1initial__keys.html", null ],
    [ "kcenon::network::integration::messaging_bridge::impl::internal_metrics", "structkcenon_1_1network_1_1integration_1_1messaging__bridge_1_1impl_1_1internal__metrics.html", null ],
    [ "kcenon::network::integration::io_context_thread_manager", "classkcenon_1_1network_1_1integration_1_1io__context__thread__manager.html", null ],
    [ "kcenon::network::protocols::quic::key_pair", "structkcenon_1_1network_1_1protocols_1_1quic_1_1key__pair.html", null ],
    [ "kcenon::network::utils::lifecycle_manager", "classkcenon_1_1network_1_1utils_1_1lifecycle__manager.html", null ],
    [ "kcenon::network::unified::listener_callbacks", "structkcenon_1_1network_1_1unified_1_1listener__callbacks.html", null ],
    [ "kcenon::network::config::logger_config", "structkcenon_1_1network_1_1config_1_1logger__config.html", null ],
    [ "kcenon::network::integration::logger_integration_manager", "classkcenon_1_1network_1_1integration_1_1logger__integration__manager.html", null ],
    [ "kcenon::network::integration::logger_interface", "classkcenon_1_1network_1_1integration_1_1logger__interface.html", [
      [ "kcenon::network::integration::basic_logger", "classkcenon_1_1network_1_1integration_1_1basic__logger.html", null ]
    ] ],
    [ "kcenon::network::protocols::quic::long_header", "structkcenon_1_1network_1_1protocols_1_1quic_1_1long__header.html", null ],
    [ "kcenon::network::protocols::quic::loss_detection_result", "structkcenon_1_1network_1_1protocols_1_1quic_1_1loss__detection__result.html", null ],
    [ "kcenon::network::protocols::quic::loss_detector", "classkcenon_1_1network_1_1protocols_1_1quic_1_1loss__detector.html", null ],
    [ "kcenon::network::protocols::quic::max_data_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1max__data__frame.html", null ],
    [ "kcenon::network::protocols::quic::max_stream_data_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1max__stream__data__frame.html", null ],
    [ "kcenon::network::protocols::quic::max_streams_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1max__streams__frame.html", null ],
    [ "kcenon::network::utils::memory_profiler", "classkcenon_1_1network_1_1utils_1_1memory__profiler.html", null ],
    [ "kcenon::network::utils::memory_snapshot", "structkcenon_1_1network_1_1utils_1_1memory__snapshot.html", null ],
    [ "kcenon::network::message_limits", "structkcenon_1_1network_1_1message__limits.html", null ],
    [ "kcenon::network::message_validator", "classkcenon_1_1network_1_1message__validator.html", null ],
    [ "kcenon::network::protocols::grpc::method_descriptor", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1method__descriptor.html", null ],
    [ "kcenon::network::protocols::grpc::method_handler", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1method__handler.html", null ],
    [ "kcenon::network::metrics::metric_reporter", "classkcenon_1_1network_1_1metrics_1_1metric__reporter.html", null ],
    [ "kcenon::network::integration::io_context_thread_manager::metrics", "structkcenon_1_1network_1_1integration_1_1io__context__thread__manager_1_1metrics.html", null ],
    [ "kcenon::network::integration::thread_integration_manager::metrics", "structkcenon_1_1network_1_1integration_1_1thread__integration__manager_1_1metrics.html", null ],
    [ "kcenon::network::module_version", "structkcenon_1_1network_1_1module__version.html", null ],
    [ "kcenon::network::config::monitoring_config", "structkcenon_1_1network_1_1config_1_1monitoring__config.html", null ],
    [ "kcenon::network::integration::monitoring_integration_manager", "classkcenon_1_1network_1_1integration_1_1monitoring__integration__manager.html", null ],
    [ "kcenon::network::integration::monitoring_interface", "classkcenon_1_1network_1_1integration_1_1monitoring__interface.html", [
      [ "kcenon::network::integration::basic_monitoring", "classkcenon_1_1network_1_1integration_1_1basic__monitoring.html", null ]
    ] ],
    [ "kcenon::network::internal::multipart_file", "structkcenon_1_1network_1_1internal_1_1multipart__file.html", null ],
    [ "kcenon::network::config::network_config", "structkcenon_1_1network_1_1config_1_1network__config.html", null ],
    [ "kcenon::network::events::network_connection_event", "structkcenon_1_1network_1_1events_1_1network__connection__event.html", null ],
    [ "kcenon::network::core::network_context", "classkcenon_1_1network_1_1core_1_1network__context.html", null ],
    [ "kcenon::network::events::network_health_event", "structkcenon_1_1network_1_1events_1_1network__health__event.html", null ],
    [ "kcenon::network::events::network_latency_event", "structkcenon_1_1network_1_1events_1_1network__latency__event.html", null ],
    [ "kcenon::network::events::network_metric_event", "structkcenon_1_1network_1_1events_1_1network__metric__event.html", null ],
    [ "kcenon::network::config::network_system_config", "structkcenon_1_1network_1_1config_1_1network__system__config.html", null ],
    [ "kcenon::network::integration::network_to_common_thread_adapter_unavailable", "structkcenon_1_1network_1_1integration_1_1network__to__common__thread__adapter__unavailable.html", null ],
    [ "kcenon::network::events::network_transfer_event", "structkcenon_1_1network_1_1events_1_1network__transfer__event.html", null ],
    [ "kcenon::network::integration::NetworkSystemBridge", "classkcenon_1_1network_1_1integration_1_1NetworkSystemBridge.html", null ],
    [ "kcenon::network::integration::NetworkSystemBridgeConfig", "structkcenon_1_1network_1_1integration_1_1NetworkSystemBridgeConfig.html", null ],
    [ "kcenon::network::protocols::quic::new_connection_id_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1new__connection__id__frame.html", null ],
    [ "kcenon::network::protocols::quic::new_token_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1new__token__frame.html", null ],
    [ "kcenon::network::policy::no_tls", "structkcenon_1_1network_1_1policy_1_1no__tls.html", null ],
    [ "kcenon::network::protocols::quic::replay_filter::nonce_entry", "structkcenon_1_1network_1_1protocols_1_1quic_1_1replay__filter_1_1nonce__entry.html", null ],
    [ "kcenon::network::tracing::otlp_config", "structkcenon_1_1network_1_1tracing_1_1otlp__config.html", null ],
    [ "kcenon::network::protocols::quic::packet_builder", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__builder.html", null ],
    [ "kcenon::network::core::packet_header", "structkcenon_1_1network_1_1core_1_1packet__header.html", null ],
    [ "kcenon::network::core::packet_info", "structkcenon_1_1network_1_1core_1_1packet__info.html", null ],
    [ "kcenon::network::protocols::quic::packet_number", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__number.html", null ],
    [ "kcenon::network::protocols::quic::packet_number_space", "structkcenon_1_1network_1_1protocols_1_1quic_1_1packet__number__space.html", null ],
    [ "kcenon::network::protocols::quic::packet_parser", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__parser.html", null ],
    [ "kcenon::network::protocols::quic::packet_protection", "classkcenon_1_1network_1_1protocols_1_1quic_1_1packet__protection.html", null ],
    [ "kcenon::network::protocols::quic::padding_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1padding__frame.html", null ],
    [ "kcenon::network::internal::parse_error", "structkcenon_1_1network_1_1internal_1_1parse__error.html", null ],
    [ "kcenon::network::protocols::quic::path_challenge_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1path__challenge__frame.html", null ],
    [ "kcenon::network::protocols::quic::path_response_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1path__response__frame.html", null ],
    [ "kcenon::network::per_client_connection_limiter", "classkcenon_1_1network_1_1per__client__connection__limiter.html", null ],
    [ "kcenon::network::protocols::quic::ping_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ping__frame.html", null ],
    [ "kcenon::network::protocols::quic::pmtud_config", "structkcenon_1_1network_1_1protocols_1_1quic_1_1pmtud__config.html", null ],
    [ "kcenon::network::protocols::quic::pmtud_controller", "classkcenon_1_1network_1_1protocols_1_1quic_1_1pmtud__controller.html", null ],
    [ "kcenon::network::facade::tcp_facade::pool_config", "structkcenon_1_1network_1_1facade_1_1tcp__facade_1_1pool__config.html", null ],
    [ "kcenon::network::protocols::quic::preferred_address_info", "structkcenon_1_1network_1_1protocols_1_1quic_1_1preferred__address__info.html", null ],
    [ "kcenon::network::core::quic_client_config", "structkcenon_1_1network_1_1core_1_1quic__client__config.html", null ],
    [ "kcenon::network::protocol::quic::quic_config", "structkcenon_1_1network_1_1protocol_1_1quic_1_1quic__config.html", null ],
    [ "kcenon::network::core::quic_connection_stats", "structkcenon_1_1network_1_1core_1_1quic__connection__stats.html", null ],
    [ "kcenon::network::protocols::quic::quic_crypto", "classkcenon_1_1network_1_1protocols_1_1quic_1_1quic__crypto.html", null ],
    [ "kcenon::network::facade::quic_facade", "classkcenon_1_1network_1_1facade_1_1quic__facade.html", null ],
    [ "kcenon::network::protocols::quic::quic_keys", "structkcenon_1_1network_1_1protocols_1_1quic_1_1quic__keys.html", null ],
    [ "kcenon::network::protocol::quic_protocol", "structkcenon_1_1network_1_1protocol_1_1quic__protocol.html", null ],
    [ "kcenon::network::core::quic_server_config", "structkcenon_1_1network_1_1core_1_1quic__server__config.html", null ],
    [ "kcenon::network::rate_limiter", "classkcenon_1_1network_1_1rate__limiter.html", null ],
    [ "kcenon::network::rate_limiter_config", "structkcenon_1_1network_1_1rate__limiter__config.html", null ],
    [ "kcenon::network::protocols::grpc::registry_config", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1registry__config.html", null ],
    [ "kcenon::network::core::reliable_udp_stats", "structkcenon_1_1network_1_1core_1_1reliable__udp__stats.html", null ],
    [ "kcenon::network::protocols::quic::replay_filter", "classkcenon_1_1network_1_1protocols_1_1quic_1_1replay__filter.html", null ],
    [ "kcenon::network::protocols::quic::reset_stream_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1reset__stream__frame.html", null ],
    [ "kcenon::network::utils::resilient_client", "classkcenon_1_1network_1_1utils_1_1resilient__client.html", null ],
    [ "kcenon::network::Result< T >", "classkcenon_1_1network_1_1Result.html", null ],
    [ "kcenon::network::protocols::quic::retire_connection_id_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1retire__connection__id__frame.html", null ],
    [ "kcenon::network::protocols::quic::rtt_estimator", "classkcenon_1_1network_1_1protocols_1_1quic_1_1rtt__estimator.html", null ],
    [ "kcenon::network::protocols::quic::sent_packet", "structkcenon_1_1network_1_1protocols_1_1quic_1_1sent__packet.html", null ],
    [ "kcenon::network::protocols::quic::sent_packet_info", "structkcenon_1_1network_1_1protocols_1_1quic_1_1sent__packet__info.html", null ],
    [ "kcenon::network::facade::http_facade::server_config", "structkcenon_1_1network_1_1facade_1_1http__facade_1_1server__config.html", null ],
    [ "kcenon::network::facade::quic_facade::server_config", "structkcenon_1_1network_1_1facade_1_1quic__facade_1_1server__config.html", null ],
    [ "kcenon::network::facade::tcp_facade::server_config", "structkcenon_1_1network_1_1facade_1_1tcp__facade_1_1server__config.html", null ],
    [ "kcenon::network::facade::udp_facade::server_config", "structkcenon_1_1network_1_1facade_1_1udp__facade_1_1server__config.html", null ],
    [ "kcenon::network::facade::websocket_facade::server_config", "structkcenon_1_1network_1_1facade_1_1websocket__facade_1_1server__config.html", null ],
    [ "kcenon::network::protocols::grpc::server_context", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__context.html", null ],
    [ "kcenon::network::protocols::grpc::server_reader", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__reader.html", null ],
    [ "kcenon::network::protocols::grpc::server_reader_writer", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__reader__writer.html", null ],
    [ "kcenon::network::protocols::grpc::grpc_client::server_stream_reader", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__client_1_1server__stream__reader.html", [
      [ "kcenon::network::protocols::grpc::server_stream_reader_impl", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__stream__reader__impl.html", null ]
    ] ],
    [ "kcenon::network::protocols::grpc::server_writer", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__writer.html", null ],
    [ "kcenon::network::protocols::grpc::service_base", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1service__base.html", [
      [ "kcenon::network::protocols::grpc::generic_service", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1generic__service.html", null ],
      [ "kcenon::network::protocols::grpc::health_service", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1health__service.html", null ]
    ] ],
    [ "kcenon::network::protocols::grpc::service_descriptor", "structkcenon_1_1network_1_1protocols_1_1grpc_1_1service__descriptor.html", null ],
    [ "kcenon::network::protocols::grpc::service_registry", "classkcenon_1_1network_1_1protocols_1_1grpc_1_1service__registry.html", null ],
    [ "kcenon::network::core::session_concept", "classkcenon_1_1network_1_1core_1_1session__concept.html", [
      [ "kcenon::network::core::session_model< SessionType >", "classkcenon_1_1network_1_1core_1_1session__model.html", null ]
    ] ],
    [ "kcenon::network::core::session_config", "structkcenon_1_1network_1_1core_1_1session__config.html", null ],
    [ "kcenon::network::core::session_handle", "classkcenon_1_1network_1_1core_1_1session__handle.html", null ],
    [ "kcenon::network::core::session_info", "structkcenon_1_1network_1_1core_1_1session__info.html", null ],
    [ "kcenon::network::core::session_info_base< SessionType, HasActivityTracking >", "structkcenon_1_1network_1_1core_1_1session__info__base.html", null ],
    [ "kcenon::network::core::session_info_base< SessionType, false >", "structkcenon_1_1network_1_1core_1_1session__info__base_3_01SessionType_00_01false_01_4.html", null ],
    [ "kcenon::network::core::session_info_base< SessionType, true >", "structkcenon_1_1network_1_1core_1_1session__info__base_3_01SessionType_00_01true_01_4.html", null ],
    [ "kcenon::network::core::session_manager_base< SessionType >", "classkcenon_1_1network_1_1core_1_1session__manager__base.html", null ],
    [ "kcenon::network::core::session_manager_base< session::messaging_session >", "classkcenon_1_1network_1_1core_1_1session__manager__base.html", [
      [ "kcenon::network::core::session_manager", "classkcenon_1_1network_1_1core_1_1session__manager.html", null ]
    ] ],
    [ "kcenon::network::core::session_manager_base< ws_connection >", "classkcenon_1_1network_1_1core_1_1session__manager__base.html", [
      [ "kcenon::network::core::ws_session_manager", "classkcenon_1_1network_1_1core_1_1ws__session__manager.html", null ]
    ] ],
    [ "kcenon::network::protocols::quic::session_ticket_info", "structkcenon_1_1network_1_1protocols_1_1quic_1_1session__ticket__info.html", null ],
    [ "kcenon::network::protocols::quic::session_ticket_store", "classkcenon_1_1network_1_1protocols_1_1quic_1_1session__ticket__store.html", null ],
    [ "kcenon::network::session_timeout_manager", "classkcenon_1_1network_1_1session__timeout__manager.html", null ],
    [ "kcenon::network::core::session_traits< SessionType >", "structkcenon_1_1network_1_1core_1_1session__traits.html", null ],
    [ "kcenon::network::core::session_traits< session::messaging_session >", "structkcenon_1_1network_1_1core_1_1session__traits_3_01session_1_1messaging__session_01_4.html", null ],
    [ "kcenon::network::core::session_traits< ws_connection >", "structkcenon_1_1network_1_1core_1_1session__traits_3_01ws__connection_01_4.html", null ],
    [ "kcenon::network::protocols::http2::setting_parameter", "structkcenon_1_1network_1_1protocols_1_1http2_1_1setting__parameter.html", null ],
    [ "kcenon::network::protocols::quic::short_header", "structkcenon_1_1network_1_1protocols_1_1quic_1_1short__header.html", null ],
    [ "kcenon::network::simple_error", "structkcenon_1_1network_1_1simple__error.html", null ],
    [ "kcenon::network::metrics::sliding_histogram", "classkcenon_1_1network_1_1metrics_1_1sliding__histogram.html", null ],
    [ "kcenon::network::metrics::sliding_histogram_config", "structkcenon_1_1network_1_1metrics_1_1sliding__histogram__config.html", null ],
    [ "kcenon::network::internal::socket_config", "structkcenon_1_1network_1_1internal_1_1socket__config.html", null ],
    [ "kcenon::network::internal::socket_metrics", "structkcenon_1_1network_1_1internal_1_1socket__metrics.html", null ],
    [ "kcenon::network::concepts::socket_read_guard< S >", "classkcenon_1_1network_1_1concepts_1_1socket__read__guard.html", null ],
    [ "kcenon::network::protocols::quic::loss_detector::space_state", "structkcenon_1_1network_1_1protocols_1_1quic_1_1loss__detector_1_1space__state.html", null ],
    [ "kcenon::network::tracing::span", "classkcenon_1_1network_1_1tracing_1_1span.html", null ],
    [ "kcenon::network::tracing::span_event", "structkcenon_1_1network_1_1tracing_1_1span__event.html", null ],
    [ "kcenon::network::core::ssl_config", "structkcenon_1_1network_1_1core_1_1ssl__config.html", null ],
    [ "kcenon::network::utils::startable_base< Derived >", "classkcenon_1_1network_1_1utils_1_1startable__base.html", null ],
    [ "kcenon::network::utils::startable_base< messaging_client >", "classkcenon_1_1network_1_1utils_1_1startable__base.html", [
      [ "kcenon::network::core::messaging_client", "classkcenon_1_1network_1_1core_1_1messaging__client.html", null ]
    ] ],
    [ "kcenon::network::utils::startable_base< messaging_server >", "classkcenon_1_1network_1_1utils_1_1startable__base.html", [
      [ "kcenon::network::core::messaging_server", "classkcenon_1_1network_1_1core_1_1messaging__server.html", null ]
    ] ],
    [ "kcenon::network::integration::detail::static_destruction_guard", "classkcenon_1_1network_1_1integration_1_1detail_1_1static__destruction__guard.html", null ],
    [ "kcenon::network::protocols::http2::static_table", "classkcenon_1_1network_1_1protocols_1_1http2_1_1static__table.html", null ],
    [ "kcenon::network::core::session_manager_base< SessionType >::stats", "structkcenon_1_1network_1_1core_1_1session__manager__base_1_1stats.html", null ],
    [ "kcenon::network::core::unified_session_manager::stats", "structkcenon_1_1network_1_1core_1_1unified__session__manager_1_1stats.html", null ],
    [ "kcenon::network::protocols::quic::stop_sending_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1stop__sending__frame.html", null ],
    [ "kcenon::network::protocols::quic::stream", "classkcenon_1_1network_1_1protocols_1_1quic_1_1stream.html", null ],
    [ "kcenon::network::protocols::quic::stream_data_blocked_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1stream__data__blocked__frame.html", null ],
    [ "kcenon::network::protocols::quic::stream_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1stream__frame.html", null ],
    [ "kcenon::network::protocols::quic::stream_manager", "classkcenon_1_1network_1_1protocols_1_1quic_1_1stream__manager.html", null ],
    [ "kcenon::network::protocols::quic::streams_blocked_frame", "structkcenon_1_1network_1_1protocols_1_1quic_1_1streams__blocked__frame.html", null ],
    [ "kcenon::network::utils::tcp_client_callback_index", "structkcenon_1_1network_1_1utils_1_1tcp__client__callback__index.html", null ],
    [ "kcenon::network::facade::tcp_facade", "classkcenon_1_1network_1_1facade_1_1tcp__facade.html", null ],
    [ "kcenon::network::protocol::tcp_protocol", "structkcenon_1_1network_1_1protocol_1_1tcp__protocol.html", null ],
    [ "kcenon::network::integration::thread_integration_manager", "classkcenon_1_1network_1_1integration_1_1thread__integration__manager.html", null ],
    [ "kcenon::network::config::thread_pool_config", "structkcenon_1_1network_1_1config_1_1thread__pool__config.html", null ],
    [ "kcenon::network::integration::thread_pool_interface", "classkcenon_1_1network_1_1integration_1_1thread__pool__interface.html", [
      [ "kcenon::network::integration::basic_thread_pool", "classkcenon_1_1network_1_1integration_1_1basic__thread__pool.html", null ]
    ] ],
    [ "kcenon::network::integration::thread_system_pool_adapter_unavailable", "structkcenon_1_1network_1_1integration_1_1thread__system__pool__adapter__unavailable.html", null ],
    [ "kcenon::network::metrics::sliding_histogram::time_bucket", "structkcenon_1_1network_1_1metrics_1_1sliding__histogram_1_1time__bucket.html", null ],
    [ "kcenon::network::internal::tls_config", "structkcenon_1_1network_1_1internal_1_1tls__config.html", null ],
    [ "kcenon::network::protocols::http2::tls_config", "structkcenon_1_1network_1_1protocols_1_1http2_1_1tls__config.html", null ],
    [ "kcenon::network::policy::tls_enabled", "structkcenon_1_1network_1_1policy_1_1tls__enabled.html", null ],
    [ "kcenon::network::tracing::trace_context", "classkcenon_1_1network_1_1tracing_1_1trace__context.html", null ],
    [ "kcenon::network::tracing::tracing_config", "structkcenon_1_1network_1_1tracing_1_1tracing__config.html", null ],
    [ "kcenon::network::protocols::quic::transport_parameters", "structkcenon_1_1network_1_1protocols_1_1quic_1_1transport__parameters.html", null ],
    [ "std::true_type", null, [
      [ "kcenon::network::core::session_model< SessionType >::has_close_method< T, std::void_t< decltype(std::declval< T & >().close())> >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__close__method_3_01T_00_01std_1_1void__2b455b66903d7823be546522c438fe4a.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_id_method< T, std::void_t< decltype(std::declval< const T & >().id())> >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__id__method_3_01T_00_01std_1_1void__t_39ae44dbf111c63a5c30888fdf8dde621.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_is_connected_method< T, std::void_t< decltype(std::declval< const T & >().is_connected())> >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__is__connected__method_3_01T_00_01std_10eb3a13f85367f0c50cd87e3608c7bb4.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_is_stopped_method< T, std::void_t< decltype(std::declval< const T & >().is_stopped())> >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__is__stopped__method_3_01T_00_01std_1_1437201d40c57c904df2adf48504293ee.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_send_method< T, std::void_t< decltype(std::declval< T & >().send(std::declval< std::vector< uint8_t > && >()))> >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__send__method_3_01T_00_01std_1_1void__t14620cbbe17ed3e4038ff148cc7c854e.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_send_packet_method< T, std::void_t< decltype(std::declval< T & >().send_packet(std::declval< std::vector< uint8_t > && >()))> >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__send__packet__method_3_01T_00_01std_1_7945d5941fdd51783c4d2decbd326deb.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_server_id_method< T, std::void_t< decltype(std::declval< const T & >().server_id())> >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__server__id__method_3_01T_00_01std_1_1v1c04c91703ac0e2826152a3894bf7a8c.html", null ],
      [ "kcenon::network::core::session_model< SessionType >::has_stop_session_method< T, std::void_t< decltype(std::declval< T & >().stop_session())> >", "structkcenon_1_1network_1_1core_1_1session__model_1_1has__stop__session__method_3_01T_00_01std_19a3fc61519b158c6f0dbe0fe61bd5016.html", null ]
    ] ],
    [ "kcenon::network::facade::udp_facade", "classkcenon_1_1network_1_1facade_1_1udp__facade.html", null ],
    [ "kcenon::network::protocol::udp_protocol", "structkcenon_1_1network_1_1protocol_1_1udp__protocol.html", null ],
    [ "kcenon::network::core::unified_session_config", "structkcenon_1_1network_1_1core_1_1unified__session__config.html", null ],
    [ "kcenon::network::core::unified_session_manager", "classkcenon_1_1network_1_1core_1_1unified__session__manager.html", null ],
    [ "kcenon::network::protocols::quic::ecn_tracker::validation_state", "structkcenon_1_1network_1_1protocols_1_1quic_1_1ecn__tracker_1_1validation__state.html", null ],
    [ "kcenon::network::protocols::quic::varint", "classkcenon_1_1network_1_1protocols_1_1quic_1_1varint.html", null ],
    [ "kcenon::network::facade::websocket_facade", "classkcenon_1_1network_1_1facade_1_1websocket__facade.html", null ],
    [ "kcenon::network::internal::websocket_frame", "classkcenon_1_1network_1_1internal_1_1websocket__frame.html", null ],
    [ "kcenon::network::internal::websocket_handshake", "classkcenon_1_1network_1_1internal_1_1websocket__handshake.html", null ],
    [ "kcenon::network::internal::websocket_protocol", "classkcenon_1_1network_1_1internal_1_1websocket__protocol.html", null ],
    [ "kcenon::network::protocol::websocket_protocol", "structkcenon_1_1network_1_1protocol_1_1websocket__protocol.html", null ],
    [ "kcenon::network::core::ws_client_config", "structkcenon_1_1network_1_1core_1_1ws__client__config.html", null ],
    [ "kcenon::network::core::ws_connection_impl", "classkcenon_1_1network_1_1core_1_1ws__connection__impl.html", null ],
    [ "kcenon::network::internal::ws_frame_header", "structkcenon_1_1network_1_1internal_1_1ws__frame__header.html", null ],
    [ "kcenon::network::internal::ws_handshake_result", "structkcenon_1_1network_1_1internal_1_1ws__handshake__result.html", null ],
    [ "kcenon::network::internal::ws_message", "structkcenon_1_1network_1_1internal_1_1ws__message.html", null ],
    [ "kcenon::network::core::ws_server_config", "structkcenon_1_1network_1_1core_1_1ws__server__config.html", null ]
];