# =============================================================================
# DEPRECATED build entry point -- CMake (with presets) is the SINGLE supported
# build system for network_system. See issue #1153 and #953.
# =============================================================================
#
# This file previously contained a ~183 KB, 4115-line CMake-GENERATED Unix
# Makefile whose first line was literally:
#
#     # CMAKE generated file: DO NOT EDIT!
#     # Generated by "Unix Makefiles" Generator, CMake Version 4.2
#
# That generated artifact had been committed to version control by accident.
# It is a build OUTPUT, not a build INPUT: it hard-codes the absolute paths of
# one developer's machine and a specific CMake binary, so it cannot work on any
# other machine or in CI, and it created a misleading SECOND build entry point
# alongside the real, supported CMake build. It is referenced by no CI workflow
# (.github/), script, or documentation.
#
# It has been replaced by this small hand-written wrapper that simply forwards
# to CMake/CTest, so the dual build path is neutralized without silently
# deleting the file (per issue #1153). The wrapper uses CMake PRESETS, which
# this repository provides in CMakePresets.json (debug, release, asan, tsan,
# ubsan, coverage, ci-*, vcpkg, ...).
#
# -----------------------------------------------------------------------------
# Recommended: drive CMake directly via presets
# -----------------------------------------------------------------------------
#
#     cmake --preset debug            # configure (see CMakePresets.json)
#     cmake --build --preset debug    # build
#     ctest --preset debug            # run tests
#
# The build tree lives under ./build*/ (git-ignored). Never commit a generated
# Makefile or other build artifacts.
#
# -----------------------------------------------------------------------------
# Convenience targets (thin forwarders -- they intentionally do NOT reimplement
# a parallel build graph). Override the preset with `make PRESET=release build`.
# -----------------------------------------------------------------------------

PRESET ?= debug

.PHONY: all build configure test clean help

help:
	@echo "network_system is built with CMake presets. This Makefile only forwards."
	@echo ""
	@echo "  make configure          ->  cmake --preset $(PRESET)"
	@echo "  make build              ->  cmake --build --preset $(PRESET)"
	@echo "  make test               ->  ctest --preset $(PRESET)"
	@echo "  make clean              ->  cmake --build --preset $(PRESET) --target clean"
	@echo ""
	@echo "  Override the preset:    make PRESET=release build"
	@echo "  Available presets:      cmake --list-presets"
	@echo ""
	@echo "See CMakePresets.json, CMakeLists.txt, and issue #1153 for details."

configure:
	cmake --preset $(PRESET)

build:
	cmake --build --preset $(PRESET)

all: build

test:
	ctest --preset $(PRESET) --output-on-failure

clean:
	cmake --build --preset $(PRESET) --target clean
