# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dongcheolshin/Sources/network_system

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dongcheolshin/Sources/network_system

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dongcheolshin/Sources/network_system/CMakeFiles /Users/dongcheolshin/Sources/network_system//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dongcheolshin/Sources/network_system/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NetworkSystem

# Build rule for target.
NetworkSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NetworkSystem
.PHONY : NetworkSystem

# fast build rule for target.
NetworkSystem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/build
.PHONY : NetworkSystem/fast

#=============================================================================
# Target rules for targets named verify_build

# Build rule for target.
verify_build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 verify_build
.PHONY : verify_build

# fast build rule for target.
verify_build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_build.dir/build.make CMakeFiles/verify_build.dir/build
.PHONY : verify_build/fast

#=============================================================================
# Target rules for targets named test_integration

# Build rule for target.
test_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integration
.PHONY : test_integration

# fast build rule for target.
test_integration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integration.dir/build.make CMakeFiles/test_integration.dir/build
.PHONY : test_integration/fast

#=============================================================================
# Target rules for targets named test_compatibility

# Build rule for target.
test_compatibility: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_compatibility
.PHONY : test_compatibility

# fast build rule for target.
test_compatibility/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_compatibility.dir/build.make CMakeFiles/test_compatibility.dir/build
.PHONY : test_compatibility/fast

#=============================================================================
# Target rules for targets named test_e2e

# Build rule for target.
test_e2e: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_e2e
.PHONY : test_e2e

# fast build rule for target.
test_e2e/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_e2e.dir/build.make CMakeFiles/test_e2e.dir/build
.PHONY : test_e2e/fast

#=============================================================================
# Target rules for targets named stress_test

# Build rule for target.
stress_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stress_test
.PHONY : stress_test

# fast build rule for target.
stress_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stress_test.dir/build.make CMakeFiles/stress_test.dir/build
.PHONY : stress_test/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

src/core/messaging_client.o: src/core/messaging_client.cpp.o
.PHONY : src/core/messaging_client.o

# target to build an object file
src/core/messaging_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/core/messaging_client.cpp.o
.PHONY : src/core/messaging_client.cpp.o

src/core/messaging_client.i: src/core/messaging_client.cpp.i
.PHONY : src/core/messaging_client.i

# target to preprocess a source file
src/core/messaging_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/core/messaging_client.cpp.i
.PHONY : src/core/messaging_client.cpp.i

src/core/messaging_client.s: src/core/messaging_client.cpp.s
.PHONY : src/core/messaging_client.s

# target to generate assembly for a file
src/core/messaging_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/core/messaging_client.cpp.s
.PHONY : src/core/messaging_client.cpp.s

src/core/messaging_server.o: src/core/messaging_server.cpp.o
.PHONY : src/core/messaging_server.o

# target to build an object file
src/core/messaging_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/core/messaging_server.cpp.o
.PHONY : src/core/messaging_server.cpp.o

src/core/messaging_server.i: src/core/messaging_server.cpp.i
.PHONY : src/core/messaging_server.i

# target to preprocess a source file
src/core/messaging_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/core/messaging_server.cpp.i
.PHONY : src/core/messaging_server.cpp.i

src/core/messaging_server.s: src/core/messaging_server.cpp.s
.PHONY : src/core/messaging_server.s

# target to generate assembly for a file
src/core/messaging_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/core/messaging_server.cpp.s
.PHONY : src/core/messaging_server.cpp.s

src/integration/container_integration.o: src/integration/container_integration.cpp.o
.PHONY : src/integration/container_integration.o

# target to build an object file
src/integration/container_integration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/integration/container_integration.cpp.o
.PHONY : src/integration/container_integration.cpp.o

src/integration/container_integration.i: src/integration/container_integration.cpp.i
.PHONY : src/integration/container_integration.i

# target to preprocess a source file
src/integration/container_integration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/integration/container_integration.cpp.i
.PHONY : src/integration/container_integration.cpp.i

src/integration/container_integration.s: src/integration/container_integration.cpp.s
.PHONY : src/integration/container_integration.s

# target to generate assembly for a file
src/integration/container_integration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/integration/container_integration.cpp.s
.PHONY : src/integration/container_integration.cpp.s

src/integration/messaging_bridge.o: src/integration/messaging_bridge.cpp.o
.PHONY : src/integration/messaging_bridge.o

# target to build an object file
src/integration/messaging_bridge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/integration/messaging_bridge.cpp.o
.PHONY : src/integration/messaging_bridge.cpp.o

src/integration/messaging_bridge.i: src/integration/messaging_bridge.cpp.i
.PHONY : src/integration/messaging_bridge.i

# target to preprocess a source file
src/integration/messaging_bridge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/integration/messaging_bridge.cpp.i
.PHONY : src/integration/messaging_bridge.cpp.i

src/integration/messaging_bridge.s: src/integration/messaging_bridge.cpp.s
.PHONY : src/integration/messaging_bridge.s

# target to generate assembly for a file
src/integration/messaging_bridge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/integration/messaging_bridge.cpp.s
.PHONY : src/integration/messaging_bridge.cpp.s

src/integration/thread_integration.o: src/integration/thread_integration.cpp.o
.PHONY : src/integration/thread_integration.o

# target to build an object file
src/integration/thread_integration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/integration/thread_integration.cpp.o
.PHONY : src/integration/thread_integration.cpp.o

src/integration/thread_integration.i: src/integration/thread_integration.cpp.i
.PHONY : src/integration/thread_integration.i

# target to preprocess a source file
src/integration/thread_integration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/integration/thread_integration.cpp.i
.PHONY : src/integration/thread_integration.cpp.i

src/integration/thread_integration.s: src/integration/thread_integration.cpp.s
.PHONY : src/integration/thread_integration.s

# target to generate assembly for a file
src/integration/thread_integration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/integration/thread_integration.cpp.s
.PHONY : src/integration/thread_integration.cpp.s

src/internal/pipeline.o: src/internal/pipeline.cpp.o
.PHONY : src/internal/pipeline.o

# target to build an object file
src/internal/pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/internal/pipeline.cpp.o
.PHONY : src/internal/pipeline.cpp.o

src/internal/pipeline.i: src/internal/pipeline.cpp.i
.PHONY : src/internal/pipeline.i

# target to preprocess a source file
src/internal/pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/internal/pipeline.cpp.i
.PHONY : src/internal/pipeline.cpp.i

src/internal/pipeline.s: src/internal/pipeline.cpp.s
.PHONY : src/internal/pipeline.s

# target to generate assembly for a file
src/internal/pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/internal/pipeline.cpp.s
.PHONY : src/internal/pipeline.cpp.s

src/internal/send_coroutine.o: src/internal/send_coroutine.cpp.o
.PHONY : src/internal/send_coroutine.o

# target to build an object file
src/internal/send_coroutine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/internal/send_coroutine.cpp.o
.PHONY : src/internal/send_coroutine.cpp.o

src/internal/send_coroutine.i: src/internal/send_coroutine.cpp.i
.PHONY : src/internal/send_coroutine.i

# target to preprocess a source file
src/internal/send_coroutine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/internal/send_coroutine.cpp.i
.PHONY : src/internal/send_coroutine.cpp.i

src/internal/send_coroutine.s: src/internal/send_coroutine.cpp.s
.PHONY : src/internal/send_coroutine.s

# target to generate assembly for a file
src/internal/send_coroutine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/internal/send_coroutine.cpp.s
.PHONY : src/internal/send_coroutine.cpp.s

src/internal/tcp_socket.o: src/internal/tcp_socket.cpp.o
.PHONY : src/internal/tcp_socket.o

# target to build an object file
src/internal/tcp_socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/internal/tcp_socket.cpp.o
.PHONY : src/internal/tcp_socket.cpp.o

src/internal/tcp_socket.i: src/internal/tcp_socket.cpp.i
.PHONY : src/internal/tcp_socket.i

# target to preprocess a source file
src/internal/tcp_socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/internal/tcp_socket.cpp.i
.PHONY : src/internal/tcp_socket.cpp.i

src/internal/tcp_socket.s: src/internal/tcp_socket.cpp.s
.PHONY : src/internal/tcp_socket.s

# target to generate assembly for a file
src/internal/tcp_socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/internal/tcp_socket.cpp.s
.PHONY : src/internal/tcp_socket.cpp.s

src/session/messaging_session.o: src/session/messaging_session.cpp.o
.PHONY : src/session/messaging_session.o

# target to build an object file
src/session/messaging_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/session/messaging_session.cpp.o
.PHONY : src/session/messaging_session.cpp.o

src/session/messaging_session.i: src/session/messaging_session.cpp.i
.PHONY : src/session/messaging_session.i

# target to preprocess a source file
src/session/messaging_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/session/messaging_session.cpp.i
.PHONY : src/session/messaging_session.cpp.i

src/session/messaging_session.s: src/session/messaging_session.cpp.s
.PHONY : src/session/messaging_session.s

# target to generate assembly for a file
src/session/messaging_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetworkSystem.dir/build.make CMakeFiles/NetworkSystem.dir/src/session/messaging_session.cpp.s
.PHONY : src/session/messaging_session.cpp.s

tests/integration/test_compatibility.o: tests/integration/test_compatibility.cpp.o
.PHONY : tests/integration/test_compatibility.o

# target to build an object file
tests/integration/test_compatibility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_compatibility.dir/build.make CMakeFiles/test_compatibility.dir/tests/integration/test_compatibility.cpp.o
.PHONY : tests/integration/test_compatibility.cpp.o

tests/integration/test_compatibility.i: tests/integration/test_compatibility.cpp.i
.PHONY : tests/integration/test_compatibility.i

# target to preprocess a source file
tests/integration/test_compatibility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_compatibility.dir/build.make CMakeFiles/test_compatibility.dir/tests/integration/test_compatibility.cpp.i
.PHONY : tests/integration/test_compatibility.cpp.i

tests/integration/test_compatibility.s: tests/integration/test_compatibility.cpp.s
.PHONY : tests/integration/test_compatibility.s

# target to generate assembly for a file
tests/integration/test_compatibility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_compatibility.dir/build.make CMakeFiles/test_compatibility.dir/tests/integration/test_compatibility.cpp.s
.PHONY : tests/integration/test_compatibility.cpp.s

tests/integration/test_e2e.o: tests/integration/test_e2e.cpp.o
.PHONY : tests/integration/test_e2e.o

# target to build an object file
tests/integration/test_e2e.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_e2e.dir/build.make CMakeFiles/test_e2e.dir/tests/integration/test_e2e.cpp.o
.PHONY : tests/integration/test_e2e.cpp.o

tests/integration/test_e2e.i: tests/integration/test_e2e.cpp.i
.PHONY : tests/integration/test_e2e.i

# target to preprocess a source file
tests/integration/test_e2e.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_e2e.dir/build.make CMakeFiles/test_e2e.dir/tests/integration/test_e2e.cpp.i
.PHONY : tests/integration/test_e2e.cpp.i

tests/integration/test_e2e.s: tests/integration/test_e2e.cpp.s
.PHONY : tests/integration/test_e2e.s

# target to generate assembly for a file
tests/integration/test_e2e.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_e2e.dir/build.make CMakeFiles/test_e2e.dir/tests/integration/test_e2e.cpp.s
.PHONY : tests/integration/test_e2e.cpp.s

tests/integration/test_integration.o: tests/integration/test_integration.cpp.o
.PHONY : tests/integration/test_integration.o

# target to build an object file
tests/integration/test_integration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integration.dir/build.make CMakeFiles/test_integration.dir/tests/integration/test_integration.cpp.o
.PHONY : tests/integration/test_integration.cpp.o

tests/integration/test_integration.i: tests/integration/test_integration.cpp.i
.PHONY : tests/integration/test_integration.i

# target to preprocess a source file
tests/integration/test_integration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integration.dir/build.make CMakeFiles/test_integration.dir/tests/integration/test_integration.cpp.i
.PHONY : tests/integration/test_integration.cpp.i

tests/integration/test_integration.s: tests/integration/test_integration.cpp.s
.PHONY : tests/integration/test_integration.s

# target to generate assembly for a file
tests/integration/test_integration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integration.dir/build.make CMakeFiles/test_integration.dir/tests/integration/test_integration.cpp.s
.PHONY : tests/integration/test_integration.cpp.s

tests/performance/benchmark.o: tests/performance/benchmark.cpp.o
.PHONY : tests/performance/benchmark.o

# target to build an object file
tests/performance/benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/tests/performance/benchmark.cpp.o
.PHONY : tests/performance/benchmark.cpp.o

tests/performance/benchmark.i: tests/performance/benchmark.cpp.i
.PHONY : tests/performance/benchmark.i

# target to preprocess a source file
tests/performance/benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/tests/performance/benchmark.cpp.i
.PHONY : tests/performance/benchmark.cpp.i

tests/performance/benchmark.s: tests/performance/benchmark.cpp.s
.PHONY : tests/performance/benchmark.s

# target to generate assembly for a file
tests/performance/benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/tests/performance/benchmark.cpp.s
.PHONY : tests/performance/benchmark.cpp.s

tests/stress/stress_test.o: tests/stress/stress_test.cpp.o
.PHONY : tests/stress/stress_test.o

# target to build an object file
tests/stress/stress_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stress_test.dir/build.make CMakeFiles/stress_test.dir/tests/stress/stress_test.cpp.o
.PHONY : tests/stress/stress_test.cpp.o

tests/stress/stress_test.i: tests/stress/stress_test.cpp.i
.PHONY : tests/stress/stress_test.i

# target to preprocess a source file
tests/stress/stress_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stress_test.dir/build.make CMakeFiles/stress_test.dir/tests/stress/stress_test.cpp.i
.PHONY : tests/stress/stress_test.cpp.i

tests/stress/stress_test.s: tests/stress/stress_test.cpp.s
.PHONY : tests/stress/stress_test.s

# target to generate assembly for a file
tests/stress/stress_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stress_test.dir/build.make CMakeFiles/stress_test.dir/tests/stress/stress_test.cpp.s
.PHONY : tests/stress/stress_test.cpp.s

verify_build.o: verify_build.cpp.o
.PHONY : verify_build.o

# target to build an object file
verify_build.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_build.dir/build.make CMakeFiles/verify_build.dir/verify_build.cpp.o
.PHONY : verify_build.cpp.o

verify_build.i: verify_build.cpp.i
.PHONY : verify_build.i

# target to preprocess a source file
verify_build.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_build.dir/build.make CMakeFiles/verify_build.dir/verify_build.cpp.i
.PHONY : verify_build.cpp.i

verify_build.s: verify_build.cpp.s
.PHONY : verify_build.s

# target to generate assembly for a file
verify_build.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_build.dir/build.make CMakeFiles/verify_build.dir/verify_build.cpp.s
.PHONY : verify_build.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... NetworkSystem"
	@echo "... benchmark"
	@echo "... stress_test"
	@echo "... test_compatibility"
	@echo "... test_e2e"
	@echo "... test_integration"
	@echo "... verify_build"
	@echo "... src/core/messaging_client.o"
	@echo "... src/core/messaging_client.i"
	@echo "... src/core/messaging_client.s"
	@echo "... src/core/messaging_server.o"
	@echo "... src/core/messaging_server.i"
	@echo "... src/core/messaging_server.s"
	@echo "... src/integration/container_integration.o"
	@echo "... src/integration/container_integration.i"
	@echo "... src/integration/container_integration.s"
	@echo "... src/integration/messaging_bridge.o"
	@echo "... src/integration/messaging_bridge.i"
	@echo "... src/integration/messaging_bridge.s"
	@echo "... src/integration/thread_integration.o"
	@echo "... src/integration/thread_integration.i"
	@echo "... src/integration/thread_integration.s"
	@echo "... src/internal/pipeline.o"
	@echo "... src/internal/pipeline.i"
	@echo "... src/internal/pipeline.s"
	@echo "... src/internal/send_coroutine.o"
	@echo "... src/internal/send_coroutine.i"
	@echo "... src/internal/send_coroutine.s"
	@echo "... src/internal/tcp_socket.o"
	@echo "... src/internal/tcp_socket.i"
	@echo "... src/internal/tcp_socket.s"
	@echo "... src/session/messaging_session.o"
	@echo "... src/session/messaging_session.i"
	@echo "... src/session/messaging_session.s"
	@echo "... tests/integration/test_compatibility.o"
	@echo "... tests/integration/test_compatibility.i"
	@echo "... tests/integration/test_compatibility.s"
	@echo "... tests/integration/test_e2e.o"
	@echo "... tests/integration/test_e2e.i"
	@echo "... tests/integration/test_e2e.s"
	@echo "... tests/integration/test_integration.o"
	@echo "... tests/integration/test_integration.i"
	@echo "... tests/integration/test_integration.s"
	@echo "... tests/performance/benchmark.o"
	@echo "... tests/performance/benchmark.i"
	@echo "... tests/performance/benchmark.s"
	@echo "... tests/stress/stress_test.o"
	@echo "... tests/stress/stress_test.i"
	@echo "... tests/stress/stress_test.s"
	@echo "... verify_build.o"
	@echo "... verify_build.i"
	@echo "... verify_build.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

