Network System: kcenon::network::protocol::tcp Namespace Reference
kcenon::network::protocol::tcp Namespace Reference
Functions
auto create_connection (std::string_view id="") -> std::unique_ptr< unified::i_connection >
Creates a TCP connection (not yet connected)
auto connect (const unified::endpoint_info &endpoint, std::string_view id="") -> std::unique_ptr< unified::i_connection >
Creates and connects a TCP connection in one call.
auto connect (std::string_view url, std::string_view id="") -> std::unique_ptr< unified::i_connection >
Creates and connects a TCP connection using URL format.
auto create_listener (std::string_view id="") -> std::unique_ptr< unified::i_listener >
Creates a TCP listener (not yet listening)
auto listen (const unified::endpoint_info &bind_address, std::string_view id="") -> std::unique_ptr< unified::i_listener >
Creates and starts a TCP listener in one call.
auto listen (uint16_t port, std::string_view id="") -> std::unique_ptr< unified::i_listener >
Creates and starts a TCP listener on a specific port.
Function Documentation
connect() [1/2]
auto kcenon::network::protocol::tcp::connect (const unified::endpoint_info & endpoint, std::string_view id = "") -> std::unique_ptr<unified::i_connection>
Creates and connects a TCP connection in one call.
Parameters
endpoint The remote endpoint to connect to
id Optional unique identifier for the connection
Returns
Unique pointer to an i_connection instance (connecting or connected)
This is a convenience function that creates a connection and immediately initiates the connection to the specified endpoint.
Usage Example
auto conn = protocol::tcp::connect({"localhost", 8080});
conn->set_callbacks({
    .on_connected = []() { std::cout << "Connected!\n"; }
});
// Connection is already in progress
Definition at line 67 of file tcp.cpp.
{
    auto conn = create_connection(id);
    // Initiate connection (async, will complete in background)
    (void)conn->connect(endpoint);
    return conn;
}
References create_connection().
connect() [2/2]
auto kcenon::network::protocol::tcp::connect (std::string_view url, std::string_view id = "") -> std::unique_ptr<unified::i_connection>
Creates and connects a TCP connection using URL format.
Parameters
url The URL to connect to (format: "tcp://host:port" or "host:port")
id Optional unique identifier for the connection
Returns
Unique pointer to an i_connection instance (connecting or connected)
Definition at line 76 of file tcp.cpp.
{
    auto conn = create_connection(id);
    (void)conn->connect(url);
    return conn;
}
References create_connection().
create_connection()
auto kcenon::network::protocol::tcp::create_connection (std::string_view id = "") -> std::unique_ptr<unified::i_connection>
Creates a TCP connection (not yet connected)
Parameters
id Optional unique identifier for the connection
Returns
Unique pointer to an i_connection instance
The returned connection is not connected. Call connect() to establish the connection to a remote endpoint.
Usage Example
auto conn = protocol::tcp::create_connection("my-client");
conn->set_callbacks({
    .on_connected = []() { std::cout << "Connected!\n"; },
    .on_data = [](std::span<const std::byte> data) { }
});
conn->connect({"localhost", 8080});
Definition at line 61 of file tcp.cpp.
{
    std::string connection_id = id.empty() ? generate_unique_id("tcp-conn") : std::string(id);
    return std::make_unique<unified::adapters::tcp_connection_adapter>(connection_id);
}
Referenced by connect(), and connect().
create_listener()
auto kcenon::network::protocol::tcp::create_listener (std::string_view id = "") -> std::unique_ptr<unified::i_listener>
Creates a TCP listener (not yet listening)
Parameters
id Optional unique identifier for the listener
Returns
Unique pointer to an i_listener instance
The returned listener is not listening. Call start() to begin accepting connections.
Usage Example
auto listener = protocol::tcp::create_listener("my-server");
listener->set_callbacks({
    .on_accept = [](std::string_view conn_id) {
        std::cout << "New connection: " << conn_id << "\n";
    }
});
listener->start(8080);
Definition at line 84 of file tcp.cpp.
{
    std::string listener_id = id.empty() ? generate_unique_id("tcp-listener") : std::string(id);
    return std::make_unique<unified::adapters::tcp_listener_adapter>(listener_id);
}
Referenced by listen().
listen() [1/2]
auto kcenon::network::protocol::tcp::listen (const unified::endpoint_info & bind_address, std::string_view id = "") -> std::unique_ptr<unified::i_listener>
Creates and starts a TCP listener in one call.
Parameters
bind_address The local address to bind to
id Optional unique identifier for the listener
Returns
Unique pointer to an i_listener instance (listening)
This is a convenience function that creates a listener and immediately starts listening on the specified address.
Usage Example
auto listener = protocol::tcp::listen({"0.0.0.0", 8080});
listener->set_callbacks({
    .on_accept = [](std::string_view conn_id) { }
});
// Listener is already accepting connections
Definition at line 90 of file tcp.cpp.
{
    auto listener = create_listener(id);
    (void)listener->start(bind_address);
    return listener;
}
References create_listener().
Referenced by listen().
listen() [2/2]
auto kcenon::network::protocol::tcp::listen (uint16_t port, std::string_view id = "") -> std::unique_ptr<unified::i_listener>
Creates and starts a TCP listener on a specific port.
Parameters
port The port number to listen on
id Optional unique identifier for the listener
Returns
Unique pointer to an i_listener instance (listening)
Convenience overload that binds to all interfaces (0.0.0.0).
Definition at line 98 of file tcp.cpp.
{
    return listen(unified::endpoint_info{"0.0.0.0", port}, id);
}
References listen().