Network System: kcenon::network::protocols::quic::stream_id_type Namespace Reference
kcenon::network::protocols::quic::stream_id_type Namespace Reference
Stream ID type information.
Functions
constexpr auto is_client_initiated (uint64_t stream_id) noexcept -> bool
Check if stream is client-initiated.
constexpr auto is_server_initiated (uint64_t stream_id) noexcept -> bool
Check if stream is server-initiated.
constexpr auto is_bidirectional (uint64_t stream_id) noexcept -> bool
Check if stream is bidirectional.
constexpr auto is_unidirectional (uint64_t stream_id) noexcept -> bool
Check if stream is unidirectional.
constexpr auto get_type (uint64_t stream_id) noexcept -> uint64_t
Get stream type bits (0-3)
constexpr auto get_sequence (uint64_t stream_id) noexcept -> uint64_t
Get stream sequence number (stream_id >> 2)
constexpr auto make_stream_id (uint64_t type, uint64_t sequence) noexcept -> uint64_t
Make stream ID from type and sequence number.
Variables
constexpr uint64_t client_bidi = 0x00
constexpr uint64_t server_bidi = 0x01
constexpr uint64_t client_uni = 0x02
constexpr uint64_t server_uni = 0x03
Detailed Description
Stream ID type information.
Stream ID structure (RFC 9000 Section 2.1):
Bit 0: Initiator (0=client, 1=server)
Bit 1: Directionality (0=bidirectional, 1=unidirectional)
Stream types:
0x00: Client-initiated, bidirectional
0x01: Server-initiated, bidirectional
0x02: Client-initiated, unidirectional
0x03: Server-initiated, unidirectional
Function Documentation
get_sequence()
auto kcenon::network::protocols::quic::stream_id_type::get_sequence (uint64_t stream_id) -> uint64_t nodiscard constexpr noexcept
Get stream sequence number (stream_id >> 2)
Definition at line 84 of file stream.h.
    {
        return stream_id >> 2;
    }
Referenced by kcenon::network::protocols::quic::stream_manager::can_accept_peer_stream().
get_type()
auto kcenon::network::protocols::quic::stream_id_type::get_type (uint64_t stream_id) -> uint64_t nodiscard constexpr noexcept
Get stream type bits (0-3)
Definition at line 76 of file stream.h.
    {
        return stream_id & 0x03;
    }
Referenced by kcenon::network::protocols::quic::stream_manager::get_or_create_stream(), and kcenon::network::protocols::quic::stream_manager::validate_stream_id().
is_bidirectional()
auto kcenon::network::protocols::quic::stream_id_type::is_bidirectional (uint64_t stream_id) -> bool nodiscard constexpr noexcept
Check if stream is bidirectional.
Definition at line 60 of file stream.h.
    {
        return (stream_id & 0x02) == 0;
    }
Referenced by kcenon::network::protocols::quic::stream_manager::can_accept_peer_stream(), kcenon::network::protocols::quic::stream_manager::get_or_create_stream(), kcenon::network::protocols::quic::stream::is_bidirectional(), and kcenon::network::protocols::quic::stream_manager::validate_stream_id().
is_client_initiated()
auto kcenon::network::protocols::quic::stream_id_type::is_client_initiated (uint64_t stream_id) -> bool nodiscard constexpr noexcept
Check if stream is client-initiated.
Definition at line 44 of file stream.h.
    {
        return (stream_id & 0x01) == 0;
    }
is_server_initiated()
auto kcenon::network::protocols::quic::stream_id_type::is_server_initiated (uint64_t stream_id) -> bool nodiscard constexpr noexcept
Check if stream is server-initiated.
Definition at line 52 of file stream.h.
    {
        return (stream_id & 0x01) == 1;
    }
Referenced by kcenon::network::protocols::quic::stream_manager::is_local_stream().
is_unidirectional()
auto kcenon::network::protocols::quic::stream_id_type::is_unidirectional (uint64_t stream_id) -> bool nodiscard constexpr noexcept
Check if stream is unidirectional.
Definition at line 68 of file stream.h.
    {
        return (stream_id & 0x02) != 0;
    }
Referenced by kcenon::network::protocols::quic::stream::is_unidirectional().
make_stream_id()
auto kcenon::network::protocols::quic::stream_id_type::make_stream_id (uint64_t type, uint64_t sequence) -> uint64_t nodiscard constexpr noexcept
Make stream ID from type and sequence number.
Definition at line 92 of file stream.h.
    {
        return (sequence << 2) | (type & 0x03);
    }
Variable Documentation
client_bidi
uint64_t kcenon::network::protocols::quic::stream_id_type::client_bidi = 0x00 constexpr
Definition at line 36 of file stream.h.
Referenced by kcenon::network::protocols::quic::stream_manager::reset().
client_uni
uint64_t kcenon::network::protocols::quic::stream_id_type::client_uni = 0x02 constexpr
Definition at line 38 of file stream.h.
Referenced by kcenon::network::protocols::quic::stream_manager::reset().
server_bidi
uint64_t kcenon::network::protocols::quic::stream_id_type::server_bidi = 0x01 constexpr
Definition at line 37 of file stream.h.
Referenced by kcenon::network::protocols::quic::stream_manager::reset().
server_uni
uint64_t kcenon::network::protocols::quic::stream_id_type::server_uni = 0x03 constexpr
Definition at line 39 of file stream.h.
Referenced by kcenon::network::protocols::quic::stream_manager::reset().