Network System: kcenon::network::integration Namespace Reference
kcenon::network::integration Namespace Reference
Namespaces
namespace detail
Classes
class basic_container
Basic container implementation for standalone use.
class basic_logger
Basic console logger implementation for standalone use.
class basic_monitoring
Basic monitoring implementation for standalone use.
class basic_thread_pool
Basic thread pool implementation for standalone use.
struct BridgeConfig
Configuration for bridge initialization.
struct BridgeMetrics
Metrics and health information for a bridge.
struct common_to_network_thread_adapter_unavailable
class container_interface
Abstract interface for container operations.
class container_manager
Manager for container system integration.
struct function_job_unavailable
class INetworkBridge
Abstract interface for external system integration bridges.
class io_context_thread_manager
Manages io_context execution on shared thread pools.
class logger_integration_manager
Manager for logger system integration.
class logger_interface
Interface for logger integration.
class messaging_bridge
Bridge class for messaging_system compatibility implementing INetworkBridge.
class monitoring_integration_manager
Manager for monitoring system integration.
class monitoring_interface
Interface for monitoring integration.
struct network_to_common_thread_adapter_unavailable
class NetworkSystemBridge
Unified facade for all network_system integration bridges.
struct NetworkSystemBridgeConfig
Configuration for NetworkSystemBridge.
class ObservabilityBridge
Bridge for observability (logger + monitoring) integration implementing INetworkBridge.
class thread_integration_manager
Manager for thread system integration.
class thread_pool_interface
Interface for thread pool integration.
struct thread_system_pool_adapter_unavailable
class ThreadPoolBridge
Bridge for thread pool integration implementing INetworkBridge.
Enumerations
enum class log_level : int {
trace = 0 , debug = 1 , info = 2 , warn = 3 ,
error = 4 , fatal = 5
}
Log severity levels.
enum class metric_type { counter , gauge , histogram , summary }
Types of metrics supported.
Functions
static const char * level_to_string (log_level level)
static std::string get_timestamp ()
Enumeration Type Documentation
log_level
enum class kcenon::network::integration::log_level : int strong
Log severity levels.
Enumerator
trace
debug
info
warn
error
fatal
Definition at line 44 of file logger_integration.h.
                     : int {
    trace = 0,
    debug = 1,
    info = 2,
    warn = 3,
    error = 4,
    fatal = 5
};
metric_type
enum class kcenon::network::integration::metric_type strong
Types of metrics supported.
Enumerator
counter
Monotonically increasing value
gauge
Value that can increase or decrease
histogram
Distribution of values
summary
Statistical summary of values
Definition at line 37 of file monitoring_integration.h.
    {
        counter,
        gauge,
        histogram,
        summary
    };
Function Documentation
get_timestamp()
static std::string kcenon::network::integration::get_timestamp () static
Definition at line 45 of file logger_integration.cpp.
{
    auto now = std::chrono::system_clock::now();
    auto time_t_val = std::chrono::system_clock::to_time_t(now);
    auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
        now.time_since_epoch()) % 1000;
    std::tm tm_buf{};
#ifdef _WIN32
    localtime_s(&tm_buf, &time_t_val);  // Windows thread-safe version
#else
    localtime_r(&time_t_val, &tm_buf);  // POSIX thread-safe version
#endif
    std::stringstream ss;
    ss << std::put_time(&tm_buf, "%Y-%m-%d %H:%M:%S");
    ss << '.' << std::setfill('0') << std::setw(3) << ms.count();
    return ss.str();
}
Referenced by kcenon::network::integration::basic_logger::impl::log(), and kcenon::network::integration::basic_logger::impl::log().
level_to_string()
static const char * kcenon::network::integration::level_to_string (log_level level) static
Definition at line 32 of file logger_integration.cpp.
{
    switch (level) {
        case log_level::trace: return "TRACE";
        case log_level::debug: return "DEBUG";
        case log_level::info:  return "INFO ";
        case log_level::warn:  return "WARN ";
        case log_level::error: return "ERROR";
        case log_level::fatal: return "FATAL";
        default: return "UNKN ";
    }
}
References debug, error, fatal, info, trace, and warn.
Referenced by kcenon::network::integration::basic_logger::impl::log(), and kcenon::network::integration::basic_logger::impl::log().