Network System: examples/network_tracing_example.cpp File Reference
network_tracing_example.cpp File Reference
Demonstrates distributed tracing for network operations.
#include <kcenon/network/tracing/tracing.h>
#include <chrono>
#include <iostream>
#include <string>
#include <thread>
Functions
void simulate_database_query (tracing::trace_context &ctx)
void simulate_cache_lookup (tracing::trace_context &ctx)
int main ()
Detailed Description
Demonstrates distributed tracing for network operations.
Definition in file network_tracing_example.cpp.
Function Documentation
main()
int main ()
Definition at line 51 of file network_tracing_example.cpp.
{
    std::cout << "=== Network Tracing Example ===" << std::endl;
    // 1. Create a trace context for an incoming request
    std::cout << "\n1. Creating trace context:" << std::endl;
    auto ctx = tracing::trace_context::create("handle_request");
    std::cout << "   Trace context created for 'handle_request'" << std::endl;
    // 2. Create spans for sub-operations
    std::cout << "\n2. Creating nested spans:" << std::endl;
    {
        auto request_span = ctx.create_span("process_request");
        simulate_cache_lookup(ctx);
        simulate_database_query(ctx);
        std::cout << "   Request processing complete" << std::endl;
    }
    // 3. Propagate context via headers
    std::cout << "\n3. Header propagation:" << std::endl;
    auto headers = ctx.to_headers();
    std::cout << "   Trace headers (" << headers.size() << "):" << std::endl;
    for (const auto& [key, value] : headers)
    {
        std::cout << "     " << key << ": " << value << std::endl;
    }
    // 4. Reconstruct context from headers (simulating receiving service)
    std::cout << "\n4. Reconstructing context from headers:" << std::endl;
    std::unordered_map<std::string, std::string> header_map;
    for (const auto& [key, value] : headers)
    {
        header_map[key] = value;
    }
    auto downstream_ctx = tracing::trace_context::from_headers(header_map);
    auto downstream_span = downstream_ctx.create_span("downstream_service");
    std::cout << "   Downstream context reconstructed" << std::endl;
    std::cout << "   Downstream span created" << std::endl;
    std::cout << "\nDone." << std::endl;
    return 0;
}
References kcenon::network::tracing::trace_context::from_headers(), simulate_cache_lookup(), and simulate_database_query().
simulate_cache_lookup()
void simulate_cache_lookup (tracing::trace_context & ctx)
Examples
network_tracing_example.cpp.
Definition at line 43 of file network_tracing_example.cpp.
{
    auto cache_span = ctx.create_span("cache_lookup");
    std::cout << "   Checking cache..." << std::endl;
    std::this_thread::sleep_for(std::chrono::milliseconds(5));
    std::cout << "   Cache miss" << std::endl;
}
References kcenon::network::tracing::trace_context::create_span().
Referenced by main().
simulate_database_query()
void simulate_database_query (tracing::trace_context & ctx)
Examples
network_tracing_example.cpp.
Definition at line 34 of file network_tracing_example.cpp.
{
    auto db_span = ctx.create_span("database_query");
    std::cout << "   Executing database query..." << std::endl;
    std::this_thread::sleep_for(std::chrono::milliseconds(50));
    std::cout << "   Query completed" << std::endl;
    // span ends automatically (RAII)
}
References kcenon::network::tracing::trace_context::create_span().
Referenced by main().