Network System: kcenon::network::core::http_url Struct Reference
kcenon::network::core::http_url Struct Reference
Parsed URL components.
#include <http_client.h>
Public Member Functions
auto get_default_port () const -> unsigned short
Get default port for scheme.
Static Public Member Functions
static auto parse (const std::string &url) -> Result< http_url >
Parse URL string into components.
Public Attributes
std::string scheme
std::string host
unsigned short port = 0
std::string path
std::map< std::string, std::string > query
Detailed Description
Parsed URL components.
Definition at line 52 of file http_client.h.
Member Function Documentation
get_default_port()
auto kcenon::network::core::http_url::get_default_port () const -> unsigned short
Get default port for scheme.
Returns
Default port (80 for http, 443 for https)
Definition at line 90 of file http_client.cpp.
{
  if (scheme == "https") {
    return 443;
  }
  return 80; // default for http
}
References scheme.
Referenced by parse().
parse()
auto kcenon::network::core::http_url::parse (const std::string & url) -> Result<http_url> static
Parse URL string into components.
Parameters
url URL string (e.g., "http://example.com:8080/path?key=value")
Returns
Result containing parsed URL or error
Definition at line 48 of file http_client.cpp.
{
  http_url result;
  // Regular expression for URL parsing
  // Format: scheme://[user:pass@]host[:port][/path][?query]
  // Static to avoid recompilation and ensure thread-safety (C++11 magic
  // statics)
  static const std::regex url_regex(
      R"(^(https?):\/\/([^:\/\s]+)(?::(\d+))?(\/[^\?]*)?(?:\?(.*))?$)",
      std::regex::icase);
  std::smatch matches;
  if (!std::regex_match(url, matches, url_regex)) {
    return error<http_url>(-1, "Invalid URL format: " + url);
  }
  // Extract components
  result.scheme = matches[1].str();
  result.host = matches[2].str();
  // Parse port
  if (matches[3].matched) {
    try {
      result.port = static_cast<unsigned short>(std::stoi(matches[3].str()));
    } catch (const std::exception &) {
      return error<http_url>(-1, "Invalid port number in URL");
    }
  } else {
    result.port = result.get_default_port();
  }
  // Parse path
  result.path = matches[4].matched ? matches[4].str() : "/";
  // Parse query string
  if (matches[5].matched) {
    result.query = internal::http_parser::parse_query_string(matches[5].str());
  }
  return ok(std::move(result));
}
References get_default_port(), host, kcenon::network::ok(), kcenon::network::internal::http_parser::parse_query_string(), path, port, query, and scheme.
Referenced by kcenon::network::core::http_client::request().
Member Data Documentation
host
std::string kcenon::network::core::http_url::host
Definition at line 55 of file http_client.h.
Referenced by parse().
path
std::string kcenon::network::core::http_url::path
Definition at line 57 of file http_client.h.
Referenced by parse().
port
unsigned short kcenon::network::core::http_url::port = 0
Definition at line 56 of file http_client.h.
Referenced by parse().
query
std::map<std::string, std::string> kcenon::network::core::http_url::query
Definition at line 58 of file http_client.h.
Referenced by parse().
scheme
std::string kcenon::network::core::http_url::scheme
Definition at line 54 of file http_client.h.
Referenced by get_default_port(), and parse().
The documentation for this struct was generated from the following files:
src/internal/http/http_client.h
src/http/http_client.cpp