Network System: kcenon::network::protocols::grpc::grpc_message Struct Reference
kcenon::network::protocols::grpc::grpc_message Struct Reference
gRPC message with compression flag and payload
#include <frame.h>
Public Member Functions
grpc_message ()=default
Default constructor.
grpc_message (std::vector< uint8_t > payload, bool is_compressed=false)
Construct with data.
auto serialize () const -> std::vector< uint8_t >
Serialize message to bytes with length prefix.
auto serialized_size () const -> size_t
Get total serialized size including header.
auto empty () const -> bool
Check if message is empty.
auto size () const -> size_t
Get message size (payload only)
Static Public Member Functions
static auto parse (std::span< const uint8_t > input) -> Result< grpc_message >
Parse gRPC message from raw bytes.
Public Attributes
bool compressed = false
Whether payload is compressed.
std::vector< uint8_t > data
Message payload.
Detailed Description
gRPC message with compression flag and payload
Represents a gRPC message as transmitted over HTTP/2. Format: | Compressed-Flag (1 byte) | Message-Length (4 bytes) | Message |
Examples
grpc_service_example.cpp.
Definition at line 49 of file frame.h.
Constructor & Destructor Documentation
grpc_message() [1/2]
kcenon::network::protocols::grpc::grpc_message::grpc_message () default
Default constructor.
grpc_message() [2/2]
kcenon::network::protocols::grpc::grpc_message::grpc_message (std::vector< uint8_t > payload, bool is_compressed = false) inline explicit
Construct with data.
Parameters
payload Message data
is_compressed Whether data is compressed
Definition at line 64 of file frame.h.
            : compressed(is_compressed), data(std::move(payload)) {}
Member Function Documentation
empty()
auto kcenon::network::protocols::grpc::grpc_message::empty () const -> bool inline
Check if message is empty.
Returns
True if data is empty
Definition at line 97 of file frame.h.
{ return data.empty(); }
References data.
parse()
auto kcenon::network::protocols::grpc::grpc_message::parse (std::span< const uint8_t > input) -> Result<grpc_message> static
Parse gRPC message from raw bytes.
Parameters
input Raw byte data (header + payload)
Returns
Result containing parsed message or error
Parses a gRPC length-prefixed message from the input buffer.
Definition at line 14 of file frame.cpp.
{
    // Check minimum header size
    if (input.size() < grpc_header_size)
    {
        return error<grpc_message>(
            error_codes::common_errors::invalid_argument,
            "Input too small for gRPC message header",
            "grpc::frame",
            "Expected at least 5 bytes, got " + std::to_string(input.size()));
    }
    // Parse compressed flag (1 byte)
    bool compressed = (input[0] != 0);
    // Parse message length (4 bytes, big-endian)
    uint32_t length = (static_cast<uint32_t>(input[1]) << 24) |
                      (static_cast<uint32_t>(input[2]) << 16) |
                      (static_cast<uint32_t>(input[3]) << 8) |
                      (static_cast<uint32_t>(input[4]));
    // Validate message length
    if (length > default_max_message_size)
    {
        return error<grpc_message>(
            error_codes::common_errors::invalid_argument,
            "gRPC message exceeds maximum size",
            "grpc::frame",
            "Max: " + std::to_string(default_max_message_size) +
            ", Got: " + std::to_string(length));
    }
    // Check if we have enough data
    size_t total_size = grpc_header_size + length;
    if (input.size() < total_size)
    {
        return error<grpc_message>(
            error_codes::common_errors::invalid_argument,
            "Input too small for gRPC message payload",
            "grpc::frame",
            "Expected " + std::to_string(total_size) +
            " bytes, got " + std::to_string(input.size()));
    }
    // Extract message data
    grpc_message msg;
    msg.compressed = compressed;
    msg.data.assign(input.begin() + grpc_header_size,
                    input.begin() + grpc_header_size + length);
    return ok(std::move(msg));
}
References compressed, data, kcenon::network::protocols::grpc::default_max_message_size, kcenon::network::error, kcenon::network::protocols::grpc::grpc_header_size, kcenon::network::error_codes::common_errors::invalid_argument, and kcenon::network::protocols::grpc::ok.
Referenced by kcenon::network::protocols::grpc::grpc_client::impl::call_raw(), kcenon::network::protocols::grpc::client_stream_writer_impl::on_complete(), kcenon::network::protocols::grpc::bidi_stream_impl::read(), and kcenon::network::protocols::grpc::server_stream_reader_impl::read().
serialize()
auto kcenon::network::protocols::grpc::grpc_message::serialize () const -> std::vector<uint8_t>
Serialize message to bytes with length prefix.
Returns
Byte vector containing header + payload
Serializes the message with a 5-byte header prefix.
Definition at line 67 of file frame.cpp.
{
    std::vector<uint8_t> result;
    result.reserve(grpc_header_size + data.size());
    // Compressed flag (1 byte)
    result.push_back(compressed ? 1 : 0);
    // Message length (4 bytes, big-endian)
    uint32_t length = static_cast<uint32_t>(data.size());
    result.push_back(static_cast<uint8_t>((length >> 24) & 0xFF));
    result.push_back(static_cast<uint8_t>((length >> 16) & 0xFF));
    result.push_back(static_cast<uint8_t>((length >> 8) & 0xFF));
    result.push_back(static_cast<uint8_t>(length & 0xFF));
    // Message data
    result.insert(result.end(), data.begin(), data.end());
    return result;
}
References compressed, data, and kcenon::network::protocols::grpc::grpc_header_size.
Referenced by kcenon::network::protocols::grpc::grpc_client::impl::call_raw(), kcenon::network::protocols::grpc::grpc_client::impl::server_stream_raw(), kcenon::network::protocols::grpc::bidi_stream_impl::write(), and kcenon::network::protocols::grpc::client_stream_writer_impl::write().
serialized_size()
auto kcenon::network::protocols::grpc::grpc_message::serialized_size () const -> size_t inline
Get total serialized size including header.
Returns
Total size in bytes
Definition at line 88 of file frame.h.
        {
            return grpc_header_size + data.size();
        }
References data, and kcenon::network::protocols::grpc::grpc_header_size.
size()
auto kcenon::network::protocols::grpc::grpc_message::size () const -> size_t inline
Get message size (payload only)
Returns
Payload size in bytes
Definition at line 103 of file frame.h.
{ return data.size(); }
References data.
Member Data Documentation
compressed
bool kcenon::network::protocols::grpc::grpc_message::compressed = false
Whether payload is compressed.
Definition at line 51 of file frame.h.
Referenced by parse(), and serialize().
data
std::vector<uint8_t> kcenon::network::protocols::grpc::grpc_message::data
Message payload.
Examples
grpc_service_example.cpp.
Definition at line 52 of file frame.h.
Referenced by empty(), kcenon::network::protocols::grpc::client_stream_writer_impl::finish(), main(), parse(), serialize(), serialized_size(), and size().
The documentation for this struct was generated from the following files:
include/kcenon/network/detail/protocols/grpc/frame.h
src/protocols/grpc/frame.cpp