Network System: kcenon::network::internal::http_response Struct Reference
kcenon::network::internal::http_response Struct Reference
Represents an HTTP response message.
#include <http_types.h>
Public Member Functions
auto get_header (const std::string &name) const -> std::optional< std::string >
Get the value of a header (case-insensitive)
auto set_header (const std::string &name, const std::string &value) -> void
Set a header value.
auto get_body_string () const -> std::string
Get body as string.
auto set_body_string (const std::string &content) -> void
Set body from string.
auto set_cookie (const std::string &name, const std::string &value, const std::string &path="/", int max_age=-1, bool http_only=true, bool secure=false, const std::string &same_site="") -> void
Set a cookie in the response.
Public Attributes
int status_code = 200
std::string status_message = "OK"
http_version version = http_version::HTTP_1_1
std::map< std::string, std::string > headers
std::vector< uint8_t > body
std::vector< cookie > set_cookies
bool use_chunked_encoding = false
Detailed Description
Represents an HTTP response message.
Structure
status_code: HTTP status code (200, 404, etc.)
status_message: Status message ("OK", "Not Found", etc.)
version: HTTP version (1.0, 1.1, 2.0)
headers: Map of header name to value
body: Response body as raw bytes
Definition at line 189 of file http_types.h.
Member Function Documentation
get_body_string()
auto kcenon::network::internal::http_response::get_body_string () const -> std::string
Get body as string.
Returns
Body content as UTF-8 string
Definition at line 130 of file http_types.cpp.
    {
        return std::string(body.begin(), body.end());
    }
References body.
get_header()
auto kcenon::network::internal::http_response::get_header (const std::string & name) const -> std::optional<std::string>
Get the value of a header (case-insensitive)
Parameters
name Header name
Returns
Optional header value
Definition at line 97 of file http_types.cpp.
    {
        auto lower_name = to_lower(name);
        for (const auto& [key, value] : headers)
        {
            if (to_lower(key) == lower_name)
            {
                return value;
            }
        }
        return std::nullopt;
    }
Referenced by kcenon::network::core::http_server::handle_request(), kcenon::network::core::http_server::process_http_request(), and kcenon::network::core::http_server::should_close_connection().
set_body_string()
auto kcenon::network::internal::http_response::set_body_string (const std::string & content) -> void
Set body from string.
Parameters
content Body content as UTF-8 string
Definition at line 135 of file http_types.cpp.
    {
        body.assign(content.begin(), content.end());
    }
Referenced by kcenon::network::internal::http_error_response::build_html_error(), and kcenon::network::internal::http_error_response::build_json_error().
set_cookie()
auto kcenon::network::internal::http_response::set_cookie (const std::string & name, const std::string & value, const std::string & path = "/", int max_age = -1, bool http_only = true, bool secure = false, const std::string & same_site = "") -> void
Set a cookie in the response.
Parameters
name Cookie name
value Cookie value
path Cookie path (default: "/")
max_age Maximum age in seconds (default: -1 for session cookie)
http_only HttpOnly flag (default: true)
secure Secure flag (default: false)
same_site SameSite attribute (default: empty)
Definition at line 295 of file http_types.cpp.
    {
        cookie c;
        c.name = name;
        c.value = value;
        c.path = path;
        c.max_age = max_age;
        c.http_only = http_only;
        c.secure = secure;
        c.same_site = same_site;
        set_cookies.push_back(c);
    }
References kcenon::network::internal::cookie::http_only, kcenon::network::internal::cookie::max_age, kcenon::network::internal::cookie::name, kcenon::network::internal::cookie::path, kcenon::network::internal::cookie::same_site, kcenon::network::internal::cookie::secure, and kcenon::network::internal::cookie::value.
set_header()
auto kcenon::network::internal::http_response::set_header (const std::string & name, const std::string & value) -> void
Set a header value.
Parameters
name Header name
value Header value
Definition at line 110 of file http_types.cpp.
    {
        // Remove existing header with same name (case-insensitive)
        auto lower_name = to_lower(name);
        for (auto it = headers.begin(); it != headers.end();)
        {
            if (to_lower(it->first) == lower_name)
            {
                it = headers.erase(it);
            }
            else
            {
                ++it;
            }
        }
        // Add new header
        headers[name] = value;
    }
Referenced by kcenon::network::internal::http_error_response::build_html_error(), kcenon::network::internal::http_error_response::build_json_error(), kcenon::network::core::http_server::handle_request(), kcenon::network::core::http_server::process_http_request(), and kcenon::network::internal::adapters::http_server_adapter::setup_internal_routes().
Member Data Documentation
body
std::vector<uint8_t> kcenon::network::internal::http_response::body
Definition at line 195 of file http_types.h.
Referenced by get_body_string(), kcenon::network::core::http_server::handle_request(), kcenon::network::core::http_server::process_http_request(), and kcenon::network::internal::adapters::http_server_adapter::setup_internal_routes().
headers
std::map<std::string, std::string> kcenon::network::internal::http_response::headers
Definition at line 194 of file http_types.h.
set_cookies
std::vector<cookie> kcenon::network::internal::http_response::set_cookies
Definition at line 196 of file http_types.h.
status_code
int kcenon::network::internal::http_response::status_code = 200
Definition at line 191 of file http_types.h.
Referenced by kcenon::network::internal::http_error_response::build_html_error(), kcenon::network::internal::http_error_response::build_json_error(), kcenon::network::internal::http_parser::parse_status_line(), and kcenon::network::internal::adapters::http_server_adapter::setup_internal_routes().
status_message
std::string kcenon::network::internal::http_response::status_message = "OK"
Definition at line 192 of file http_types.h.
Referenced by kcenon::network::internal::http_error_response::build_html_error(), kcenon::network::internal::http_error_response::build_json_error(), and kcenon::network::internal::http_parser::parse_status_line().
use_chunked_encoding
bool kcenon::network::internal::http_response::use_chunked_encoding = false
Definition at line 197 of file http_types.h.
version
http_version kcenon::network::internal::http_response::version = http_version::HTTP_1_1
Definition at line 193 of file http_types.h.
Referenced by kcenon::network::internal::http_parser::parse_status_line().
The documentation for this struct was generated from the following files:
src/internal/http/http_types.h
src/internal/http_types.cpp