var searchData=
[
  ['after_20separation_0',['Target (After Separation)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md127',1,'']]],
  ['analysis_1',['Analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md5',1,'🎯 Phase 1: Preparation and Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md79',1,'🏗️ Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md8',1,'Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md6',1,'Day 1: Backup and Current State Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md139',1,'Phase 1: Preparation and Analysis']]],
  ['analysis_202_203_20days_2',['Analysis 2 3 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md90',1,'Phase 1: Preparation and Analysis (2-3 days)'],['../md_README.html#autotoc_md171',1,'Phase 1: Preparation and Analysis (2-3 days)']]],
  ['and_20analysis_3',['and Analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md5',1,'🎯 Phase 1: Preparation and Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md139',1,'Phase 1: Preparation and Analysis']]],
  ['and_20analysis_202_203_20days_4',['and Analysis 2 3 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md90',1,'Phase 1: Preparation and Analysis (2-3 days)'],['../md_README.html#autotoc_md171',1,'Phase 1: Preparation and Analysis (2-3 days)']]],
  ['and_20current_20state_20analysis_5',['Day 1: Backup and Current State Analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md6',1,'']]],
  ['and_20deployment_6',['and Deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md46',1,'✅ Phase 5: Verification and Deployment'],['../md_MIGRATION__CHECKLIST.html#autotoc_md51',1,'Day 18: Final Verification and Deployment'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md143',1,'Phase 5: Verification and Deployment']]],
  ['and_20deployment_202_203_20days_7',['and Deployment 2 3 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md104',1,'Phase 5: Verification and Deployment (2-3 days)'],['../md_README.html#autotoc_md175',1,'Phase 5: Verification and Deployment (2-3 days)']]],
  ['and_20design_20documents_8',['📋 Planning and Design Documents',['../md_README.html#autotoc_md154',1,'']]],
  ['and_20include_20path_20updates_9',['Day 6-7: Namespace and Include Path Updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md21',1,'']]],
  ['and_20mitigation_10',['and Mitigation',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md129',1,'🚨 Risk Factors and Mitigation'],['../md_README.html#autotoc_md191',1,'🚨 Risk Factors and Mitigation']]],
  ['and_20planning_11',['Day 2: Design and Planning',['../md_MIGRATION__CHECKLIST.html#autotoc_md9',1,'']]],
  ['and_20reorganization_12',['Code Copy and Reorganization',['../md_MIGRATION__CHECKLIST.html#autotoc_md20',1,'']]],
  ['and_20requirements_13',['Dependencies and Requirements',['../index.html#dependencies_sec',1,'']]],
  ['and_20solutions_14',['Issues and Solutions',['../md_MIGRATION__CHECKLIST.html#autotoc_md69',1,'']]],
  ['and_20support_15',['and Support',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md145',1,'📞 Contact and Support'],['../md_README.html#autotoc_md195',1,'📞 Contact and Support'],['../index.html#contact_sec',1,'Contact and Support']]],
  ['and_20testing_16',['3. Verification and Testing',['../md_README.html#autotoc_md160',1,'']]],
  ['and_20testing_20strategy_17',['Day 3: Build System and Testing Strategy',['../md_MIGRATION__CHECKLIST.html#autotoc_md12',1,'']]],
  ['api_18',['1. Core API',['../md_README.html#autotoc_md166',1,'']]],
  ['api_20design_19',['2. Core API Design',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md217',1,'']]],
  ['api_20documentation_20',['1. API Documentation',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md134',1,'']]],
  ['api_20implementation_21',['Compatibility API Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md36',1,'']]],
  ['architecture_20design_22',['Architecture Design',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md211',1,'🏗️ Architecture Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md10',1,'Architecture Design']]],
  ['architecture_20documentation_23',['2. Architecture Documentation',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md135',1,'']]],
  ['architecture_20overview_24',['Architecture Overview',['../md_README.html#autotoc_md162',1,'🏗️ Architecture Overview'],['../index.html#architecture_sec',1,'Architecture Overview']]],
  ['assessment_25',['Risk Assessment',['../md_MIGRATION__CHECKLIST.html#autotoc_md15',1,'']]],
  ['asynchronous_20operations_26',['Asynchronous Operations',['../index.html#feat_async',1,'']]]
];
