var searchData=
[
  ['change_20history_0',['📝 Change History',['../md_README.html#autotoc_md200',1,'']]],
  ['changes_1',['Namespace Changes',['../md_MIGRATION__CHECKLIST.html#autotoc_md22',1,'']]],
  ['characteristics_2',['Characteristics',['../md_README.html#autotoc_md168',1,'3. Performance Characteristics'],['../index.html#performance_sec',1,'Performance Characteristics']]],
  ['checklist_3',['Checklist',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md138',1,'✅ Completion Checklist'],['../md_MIGRATION__CHECKLIST.html#autotoc_md70',1,'Final Checklist'],['../md_MIGRATION__CHECKLIST.html',1,'Network System Migration Checklist']]],
  ['checklist_20for_20network_5fsystem_20separation_20from_20messaging_5fsystem_4',['Detailed Execution Checklist for network_system Separation from messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md1',1,'']]],
  ['class_5',['1. messaging_bridge Class',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md216',1,'']]],
  ['class_20implementation_6',['Day 9-10: Bridge Class Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md30',1,'']]],
  ['client_20usage_7',['Basic Client Usage',['../index.html#usage_client',1,'']]],
  ['cmake_20build_20system_8',['2. CMake Build System',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md111',1,'']]],
  ['cmake_20module_20files_9',['1. CMake Module Files',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md221',1,'']]],
  ['cmakelists_20txt_10',['Main CMakeLists.txt',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md112',1,'']]],
  ['cmakelists_20txt_20creation_11',['CMakeLists.txt Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md25',1,'']]],
  ['cmakelists_20txt_20update_12',['CMakeLists.txt Update',['../md_MIGRATION__CHECKLIST.html#autotoc_md40',1,'']]],
  ['code_20compatibility_20verification_13',['Existing Code Compatibility Verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md43',1,'']]],
  ['code_20copy_20and_20reorganization_14',['Code Copy and Reorganization',['../md_MIGRATION__CHECKLIST.html#autotoc_md20',1,'']]],
  ['code_20updates_15',['Code Updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md41',1,'']]],
  ['collection_16',['1. Performance Metric Collection',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md229',1,'']]],
  ['common_20issues_17',['Common Issues',['../index.html#trouble_common',1,'']]],
  ['compatibility_20api_20implementation_18',['Compatibility API Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md36',1,'']]],
  ['compatibility_20issues_19',['Compatibility Issues',['../md_MIGRATION__CHECKLIST.html#autotoc_md65',1,'']]],
  ['compatibility_20layer_20',['3. Compatibility Layer',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md87',1,'']]],
  ['compatibility_20verification_21',['Compatibility Verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md59',1,'Compatibility Verification'],['../md_MIGRATION__CHECKLIST.html#autotoc_md43',1,'Existing Code Compatibility Verification']]],
  ['completion_22',['v2.0.2 (Planned) - Integration Completion',['../md_README.html#autotoc_md203',1,'']]],
  ['completion_20checklist_23',['✅ Completion Checklist',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md138',1,'']]],
  ['completion_20report_24',['Task Completion Report',['../md_MIGRATION__CHECKLIST.html#autotoc_md68',1,'']]],
  ['completion_20report_20template_25',['📝 Completion Report Template',['../md_MIGRATION__CHECKLIST.html#autotoc_md67',1,'']]],
  ['component_20implementation_26',['🔧 Core Component Implementation',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md215',1,'']]],
  ['components_27',['Core Components',['../md_README.html#autotoc_md165',1,'']]],
  ['conditional_28',['Integration Dependencies (Conditional)',['../md_README.html#autotoc_md184',1,'']]],
  ['config_20file_29',['2. pkg-config File',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md222',1,'']]],
  ['configuration_30',['Configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md24',1,'Day 8: Basic Build System Configuration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md26',1,'Dependency Configuration']]],
  ['considerations_31',['Security Considerations',['../index.html#feat_security',1,'']]],
  ['contact_20and_20support_32',['Contact and Support',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md145',1,'📞 Contact and Support'],['../md_README.html#autotoc_md195',1,'📞 Contact and Support'],['../index.html#contact_sec',1,'Contact and Support']]],
  ['container_5fsystem_20integration_33',['container_system Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md34',1,'']]],
  ['contributing_34',['Contributing',['../index.html#contributing_sec',1,'']]],
  ['copy_20and_20reorganization_35',['Code Copy and Reorganization',['../md_MIGRATION__CHECKLIST.html#autotoc_md20',1,'']]],
  ['core_20api_36',['1. Core API',['../md_README.html#autotoc_md166',1,'']]],
  ['core_20api_20design_37',['2. Core API Design',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md217',1,'']]],
  ['core_20component_20implementation_38',['🔧 Core Component Implementation',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md215',1,'']]],
  ['core_20components_39',['Core Components',['../md_README.html#autotoc_md165',1,'']]],
  ['core_20dependencies_40',['Core Dependencies',['../md_README.html#autotoc_md183',1,'']]],
  ['core_20layer_41',['Core Layer',['../index.html#arch_core',1,'']]],
  ['core_20objectives_42',['Core Objectives',['../md_README.html#autotoc_md151',1,'']]],
  ['core_20separation_43',['v2.0.1 (Planned) - Core Separation',['../md_README.html#autotoc_md202',1,'']]],
  ['core_20system_20separation_44',['Core System Separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md17',1,'🔧 Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md140',1,'Phase 2: Core System Separation']]],
  ['core_20system_20separation_204_205_20days_45',['Core System Separation 4 5 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md94',1,'Phase 2: Core System Separation (4-5 days)'],['../md_README.html#autotoc_md172',1,'Phase 2: Core System Separation (4-5 days)']]],
  ['creation_46',['Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md25',1,'CMakeLists.txt Creation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md18',1,'Day 4-5: Basic Structure Creation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md19',1,'Directory Structure Creation']]],
  ['criteria_47',['📊 Verification Criteria',['../md_MIGRATION__CHECKLIST.html#autotoc_md56',1,'']]],
  ['current_20state_20analysis_48',['Current State Analysis',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md79',1,'🏗️ Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md8',1,'Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md6',1,'Day 1: Backup and Current State Analysis']]]
];
