var searchData=
[
  ['factors_20and_20mitigation_0',['factors and mitigation',['../md_README.html#autotoc_md458',1,'🚨 Risk Factors and Mitigation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md193',1,'🚨 Risk Factors and Mitigation']]],
  ['failure_1',['vcpkg Build Failure',['../md_BUILD.html#autotoc_md35',1,'']]],
  ['failures_2',['Build Failures',['../md_MIGRATION__CHECKLIST.html#autotoc_md127',1,'']]],
  ['feature_20build_3',['Full Feature Build',['../md_BUILD.html#autotoc_md25',1,'']]],
  ['feature_20implementation_4',['Phase 2: Feature Implementation',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md215',1,'']]],
  ['feature_20implementation_20🔨_20in_20progress_5',['Phase 2: Feature Implementation 🔨 (In Progress)',['../md_README.html#autotoc_md315',1,'']]],
  ['features_6',['features',['../index.html#features_sec',1,'Key Features'],['../index.html#feat_reliability',1,'Reliability Features']]],
  ['features_20📝_20planned_7',['Phase 3: Advanced Features 📝 (Planned)',['../md_README.html#autotoc_md316',1,'']]],
  ['features_20not_20available_8',['C++20 Features Not Available',['../md_BUILD.html#autotoc_md36',1,'']]],
  ['features_20priority_3a_20low_9',['4. Advanced Features (Priority: Low)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md219',1,'']]],
  ['file_10',['2. pkg-config File',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md509',1,'']]],
  ['files_11',['1. CMake Module Files',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md508',1,'']]],
  ['final_20checklist_12',['Final Checklist',['../md_MIGRATION__CHECKLIST.html#autotoc_md134',1,'']]],
  ['final_20deployment_13',['Final Deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md118',1,'']]],
  ['final_20verification_20and_20deployment_14',['Day 18: Final Verification and Deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md115',1,'']]],
  ['fixed_15',['fixed',['../md_CHANGELOG.html#autotoc_md51',1,'Fixed'],['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md227',1,'Known Issues Fixed']]],
  ['for_20network_5fsystem_20separation_20from_20messaging_5fsystem_16',['Detailed Execution Checklist for network_system Separation from messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md65',1,'']]],
  ['for_20separating_20network_5fsystem_20from_20messaging_5fsystem_17',['Detailed Plan for Separating network_system from messaging_system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md137',1,'']]],
  ['found_18',['ASIO Not Found',['../md_BUILD.html#autotoc_md33',1,'']]],
  ['found_20on_20windows_19',['pthread Not Found on Windows',['../md_BUILD.html#autotoc_md34',1,'']]],
  ['framework_20',['🧪 Test Framework',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md511',1,'']]],
  ['from_201_200_200_20to_202_200_200_21',['From 1.0.0 to 2.0.0',['../md_CHANGELOG.html#autotoc_md59',1,'']]],
  ['from_20legacy_20messaging_5fsystem_22',['From Legacy messaging_system',['../index.html#migration_from_legacy',1,'']]],
  ['from_20messaging_5fsystem_23',['from messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md65',1,'Detailed Execution Checklist for network_system Separation from messaging_system'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md137',1,'Detailed Plan for Separating network_system from messaging_system']]],
  ['full_20feature_20build_24',['Full Feature Build',['../md_BUILD.html#autotoc_md25',1,'']]],
  ['full_20system_20testing_25',['Day 16-17: Full System Testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md111',1,'']]],
  ['functional_20verification_26',['Functional Verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md121',1,'']]]
];
