var searchData=
[
  ['latest_20results_20v2_200_200_0',['Latest Results (v2.0.0)',['../md_README.html#autotoc_md360',1,'']]],
  ['layer_1',['layer',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md244',1,'3. Compatibility Layer'],['../index.html#arch_core',1,'Core Layer'],['../index.html#arch_integration',1,'Integration Layer'],['../index.html#arch_internal',1,'Internal Layer'],['../index.html#arch_session',1,'Session Layer']]],
  ['layer_20structure_2',['1. Module Layer Structure',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md414',1,'']]],
  ['leak_20patterns_3',['Common Memory Leak Patterns',['../md_TROUBLESHOOTING.html#autotoc_md480',1,'']]],
  ['leak_20prevention_4',['Memory Leak Prevention',['../md_TROUBLESHOOTING.html#autotoc_md484',1,'']]],
  ['leaks_5',['leaks',['../md_TROUBLESHOOTING.html#autotoc_md483',1,'Container Leaks'],['../md_TROUBLESHOOTING.html#autotoc_md475',1,'Memory Leaks']]],
  ['legacy_20api_20compatibility_6',['Legacy API Compatibility',['../md_README.html#autotoc_md357',1,'']]],
  ['legacy_20api_20still_20supported_7',['legacy api still supported',['../md_MIGRATION__GUIDE.html#autotoc_md200',1,'Legacy API (Still Supported)'],['../md_MIGRATION__GUIDE.html#autotoc_md203',1,'Legacy API (Still Supported)']]],
  ['legacy_20messaging_5fsystem_8',['From Legacy messaging_system',['../index.html#migration_from_legacy',1,'']]],
  ['legacy_20namespace_20mapping_9',['Legacy Namespace Mapping',['../md_MIGRATION__GUIDE.html#autotoc_md196',1,'']]],
  ['level_20optimization_10',['level optimization',['../md_OPERATIONS.html#autotoc_md325',1,'Application-Level Optimization'],['../md_OPERATIONS.html#autotoc_md322',1,'System-Level Optimization']]],
  ['library_20order_11',['Library Order',['../md_TROUBLESHOOTING.html#autotoc_md492',1,'']]],
  ['library_20paths_12',['Homebrew Library Paths',['../md_TROUBLESHOOTING.html#autotoc_md502',1,'']]],
  ['license_13',['license',['../md_RELEASE__NOTES.html#autotoc_md408',1,'📄 License'],['../md_README.html#autotoc_md376',1,'📄 License'],['../md_API__REFERENCE.html#autotoc_md40',1,'License'],['../index.html#license_sec',1,'License']]],
  ['limits_14',['limits',['../md_TROUBLESHOOTING.html#autotoc_md498',1,'File Descriptor Limits'],['../md_OPERATIONS.html#autotoc_md324',1,'Resource Limits']]],
  ['link_20time_20optimization_20lto_15',['Link-Time Optimization (LTO)',['../md_BUILD.html#autotoc_md82',1,'']]],
  ['linking_20errors_16',['Linking Errors',['../md_TROUBLESHOOTING.html#autotoc_md490',1,'']]],
  ['links_17',['🔗 Links',['../md_RELEASE__NOTES.html#autotoc_md407',1,'']]],
  ['linux_18',['Linux',['../md_API__REFERENCE.html#autotoc_md36',1,'']]],
  ['linux_20deployment_19',['Linux Deployment',['../md_OPERATIONS.html#autotoc_md309',1,'']]],
  ['linux_20issues_20',['Linux Issues',['../md_TROUBLESHOOTING.html#autotoc_md497',1,'']]],
  ['linux_20kernel_20parameters_21',['Linux Kernel Parameters',['../md_OPERATIONS.html#autotoc_md323',1,'']]],
  ['linux_20macos_22',['Linux/macOS',['../md_RELEASE__NOTES.html#autotoc_md396',1,'']]],
  ['logging_23',['Enable Debug Logging',['../md_TROUBLESHOOTING.html#autotoc_md454',1,'']]],
  ['logging_20and_20tracing_24',['Logging and Tracing',['../md_TROUBLESHOOTING.html#autotoc_md453',1,'']]],
  ['logging_20best_20practices_25',['Logging Best Practices',['../md_TROUBLESHOOTING.html#autotoc_md511',1,'']]],
  ['logging_20configuration_26',['Logging Configuration',['../md_OPERATIONS.html#autotoc_md319',1,'']]],
  ['lto_27',['Link-Time Optimization (LTO)',['../md_BUILD.html#autotoc_md82',1,'']]]
];
