var searchData=
[
  ['package_20configuration_20optional_0',['Step 2.2: Update Package Configuration (Optional)',['../md_MIGRATION.html#autotoc_md285',1,'']]],
  ['partial_20rollback_1',['Partial Rollback',['../md_MIGRATION.html#autotoc_md340',1,'']]],
  ['paths_2',['paths',['../md_MIGRATION.html#autotoc_md266',1,'Migration Paths'],['../md_STRUCTURE.html#autotoc_md545',1,'Step 2: Update Include Paths']]],
  ['pattern_3',['pattern',['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md183',1,'Result&lt;T&gt; Pattern'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md137',1,'Result&lt;T&gt; Pattern']]],
  ['pattern_20systems_4',['Comparison with Pattern Systems',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md158',1,'']]],
  ['patterns_5',['patterns',['../md_UDP__SUPPORT.html#autotoc_md569',1,'Design Patterns'],['../md_README.html#autotoc_md389',1,'Design Patterns'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md130',1,'Network-Specific Patterns']]],
  ['patterns_20used_6',['API Patterns Used',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md136',1,'']]],
  ['performance_7',['performance',['../md_BASELINE.html#autotoc_md11',1,'Concurrent Performance'],['../md_README.html#autotoc_md380',1,'Concurrent Performance'],['../md_UDP__SUPPORT.html#autotoc_md570',1,'Performance']]],
  ['performance_20baseline_20metrics_8',['Network System - Performance Baseline Metrics',['../md_BASELINE.html',1,'']]],
  ['performance_20benchmarks_9',['performance benchmarks',['../md_README.html#autotoc_md409',1,'📊 Performance Benchmarks'],['../md_CHANGELOG.html#autotoc_md75',1,'Performance Benchmarks']]],
  ['performance_20benchmarks_20strong_10',['📊 &lt;strong&gt;Performance Benchmarks&lt;/strong&gt;',['../md_README.html#autotoc_md377',1,'']]],
  ['performance_20by_20message_20size_11',['Throughput Performance by Message Size',['../md_README.html#autotoc_md378',1,'']]],
  ['performance_20characteristics_12',['performance characteristics',['../md_STRUCTURE.html#autotoc_md542',1,'📊 Performance Characteristics'],['../index.html#performance_sec',1,'Performance Characteristics']]],
  ['performance_20comparison_20notes_13',['Performance Comparison Notes',['../md_README.html#autotoc_md384',1,'']]],
  ['performance_20excellence_20strong_14',['🚀 &lt;strong&gt;Performance Excellence&lt;/strong&gt;',['../md_README.html#autotoc_md370',1,'']]],
  ['performance_20excellence_20strong_20✅_15',['&lt;strong&gt;Performance Excellence&lt;/strong&gt; ✅',['../md_README.html#autotoc_md420',1,'']]],
  ['performance_20expectations_16',['Performance Expectations',['../md_MIGRATION.html#autotoc_md342',1,'']]],
  ['performance_20features_17',['Key Performance Features',['../md_README.html#autotoc_md411',1,'']]],
  ['performance_20insights_18',['Key Performance Insights',['../md_README.html#autotoc_md382',1,'']]],
  ['performance_20issues_19',['Performance Issues',['../md_MIGRATION.html#autotoc_md317',1,'']]],
  ['performance_20measurement_20',['Performance Measurement',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md140',1,'']]],
  ['performance_20metrics_20intel_20i7_2012700k_21',['Performance Metrics (Intel i7-12700K)',['../md_BASELINE.html#autotoc_md8',1,'']]],
  ['performance_20optimizations_22',['Performance Optimizations',['../index.html#feat_perf',1,'']]],
  ['performance_20tests_23',['Performance Tests',['../md_MIGRATION.html#autotoc_md331',1,'']]],
  ['performance_20tests_2010_20tests_24',['performance tests 10 tests',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md120',1,'3. Network Performance Tests (10 tests)'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md166',1,'3. Network Performance Tests (10 tests)']]],
  ['phase_200_20요구사항_25',['Phase 0 요구사항',['../md_BASELINE__KO.html#autotoc_md43',1,'']]],
  ['phase_200_20requirements_26',['Phase 0 Requirements',['../md_BASELINE.html#autotoc_md17',1,'']]],
  ['phase_201_3a_20preparation_27',['Phase 1: Preparation',['../md_MIGRATION.html#autotoc_md278',1,'']]],
  ['phase_202_3a_20update_20build_20configuration_28',['Phase 2: Update Build Configuration',['../md_MIGRATION.html#autotoc_md283',1,'']]],
  ['phase_203_3a_20오류_20처리_2075_2080_20완료_20핵심_20api_20마이그레이션_20완료_20✅_29',['Phase 3: 오류 처리 (75-80% 완료) - 핵심 API 마이그레이션 완료 ✅',['../md_README__KO.html#autotoc_md530',1,'']]],
  ['phase_203_3a_20error_20handling_2075_2080_20complete_20core_20api_20migration_20complete_20✅_30',['Phase 3: Error Handling (75-80% Complete) - Core API Migration Complete ✅',['../md_README.html#autotoc_md444',1,'']]],
  ['phase_203_3a_20update_20code_31',['Phase 3: Update Code',['../md_MIGRATION.html#autotoc_md288',1,'']]],
  ['phase_204_3a_20verify_20migration_32',['Phase 4: Verify Migration',['../md_MIGRATION.html#autotoc_md295',1,'']]],
  ['phases_33',['Architecture Improvement Phases',['../md_README.html#autotoc_md443',1,'']]],
  ['pipeline_34',['pipeline',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md125',1,'3. CI/CD Pipeline'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md171',1,'3. CI/CD Pipeline']]],
  ['plan_35',['plan',['../md_IMPROVEMENTS.html',1,'Network System - Improvement Plan'],['../md_MIGRATION.html#autotoc_md338',1,'Rollback Plan']]],
  ['planned_36',['Planned',['../md_CHANGELOG.html#autotoc_md55',1,'']]],
  ['planned_20features_37',['Planned Features',['../md_README.html#autotoc_md415',1,'']]],
  ['platform_20compatibility_20strong_38',['🌐 &lt;strong&gt;Cross-Platform Compatibility&lt;/strong&gt;',['../md_README.html#autotoc_md373',1,'']]],
  ['platform_20support_39',['🎯 Platform Support',['../md_README.html#autotoc_md427',1,'']]],
  ['pooling_20추가_40',['3. Client용 Connection Pooling 추가',['../md_IMPROVEMENTS__KO.html#autotoc_md229',1,'']]],
  ['pooling_20for_20client_41',['3. Add Connection Pooling for Client',['../md_IMPROVEMENTS.html#autotoc_md214',1,'']]],
  ['port_20allocation_42',['port allocation',['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md177',1,'1. Dynamic Port Allocation'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md131',1,'1. Dynamic Port Allocation']]],
  ['pre_20commit_20체크리스트_43',['Pre-commit 체크리스트',['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md201',1,'']]],
  ['pre_20commit_20checklist_44',['Pre-commit Checklist',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md155',1,'']]],
  ['pre_20migration_45',['Pre-Migration',['../md_MIGRATION.html#autotoc_md271',1,'']]],
  ['pre_20separation_20from_20messaging_5fsystem_46',['[0.9.0] - 2025-09-15 (Pre-separation from messaging_system)',['../md_CHANGELOG.html#autotoc_md65',1,'']]],
  ['preparation_47',['Phase 1: Preparation',['../md_MIGRATION.html#autotoc_md278',1,'']]],
  ['prerequisites_48',['prerequisites',['../md_README.html#autotoc_md394',1,'Prerequisites'],['../md_MIGRATION.html#autotoc_md281',1,'Step 1.3: Verify Prerequisites']]],
  ['primary_49',['Reference Hardware Configuration (Primary)',['../md_BASELINE.html#autotoc_md5',1,'']]],
  ['priority_20improvements_50',['High Priority Improvements',['../md_IMPROVEMENTS.html#autotoc_md213',1,'']]],
  ['production_20grade_20reliability_20strong_51',['🛡️ &lt;strong&gt;Production-Grade Reliability&lt;/strong&gt;',['../md_README.html#autotoc_md371',1,'']]],
  ['production_20quality_20architecture_52',['Production Quality &amp; Architecture',['../md_README.html#autotoc_md438',1,'']]],
  ['productivity_20strong_53',['🔧 &lt;strong&gt;Developer Productivity&lt;/strong&gt;',['../md_README.html#autotoc_md372',1,'']]],
  ['project_54',['project',['../md_README.html#autotoc_md361',1,'Network System Project'],['../md_README__KO.html#autotoc_md446',1,'Network System Project']]],
  ['project_20ecosystem_20inter_20dependencies_55',['🔗 Project Ecosystem &amp; Inter-Dependencies',['../md_README.html#autotoc_md363',1,'']]],
  ['project_20information_56',['Project Information',['../md_CHANGELOG.html#autotoc_md69',1,'']]],
  ['project_20integration_20status_57',['project integration status',['../md_INTEGRATION__STATUS.html',1,'External Project Integration Status'],['../md_INTEGRATION__STATUS__KO.html',1,'External Project Integration Status']]],
  ['project_20purpose_20mission_58',['Project Purpose &amp; Mission',['../md_README.html#autotoc_md368',1,'']]],
  ['project_20structure_59',['project structure',['../md_README.html#autotoc_md390',1,'📁 Project Structure'],['../md_STRUCTURE.html',1,'Network System - Project Structure']]],
  ['project_20summary_60',['🎯 Project Summary',['../md_README.html#autotoc_md416',1,'']]],
  ['projects_61',['projects',['../md_MIGRATION.html#autotoc_md268',1,'Option 2: Full Migration (Recommended for New Projects)'],['../md_README.html#autotoc_md365',1,'Related Projects'],['../md_MIGRATION.html#autotoc_md353',1,'Related Projects']]],
  ['proper_20resource_20cleanup_62',['proper resource cleanup',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md134',1,'4. Proper Resource Cleanup'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md180',1,'4. Proper Resource Cleanup']]],
  ['protocol_20integration_20tests_2013_20tests_63',['protocol integration tests 13 tests',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md119',1,'2. Protocol Integration Tests (13 tests)'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md165',1,'2. Protocol Integration Tests (13 tests)']]],
  ['public_20api_20layer_20tt_20include_20network_5fsystem_20tt_64',['🎯 Public API Layer (&lt;tt&gt;include/network_system/&lt;/tt&gt;)',['../md_STRUCTURE.html#autotoc_md539',1,'']]],
  ['purpose_20mission_65',['Project Purpose &amp; Mission',['../md_README.html#autotoc_md368',1,'']]]
];
