var searchData=
[
  ['table_20of_20contents_0',['Table of Contents',['../md_BUILD.html#autotoc_md1',1,'']]],
  ['target_20after_20separation_1',['Target (After Separation)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md191',1,'']]],
  ['target_20post_20separation_2',['Target (Post-Separation)',['../md_README.html#autotoc_md411',1,'']]],
  ['target_20structure_3',['Target Structure',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md174',1,'']]],
  ['task_20completion_20report_4',['Task Completion Report',['../md_MIGRATION__CHECKLIST.html#autotoc_md132',1,'']]],
  ['tasks_5',['Backup Tasks',['../md_MIGRATION__CHECKLIST.html#autotoc_md71',1,'']]],
  ['technical_20implementation_20details_6',['technical implementation details',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md172',1,'🛠️ Technical Implementation Details'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html',1,'Technical Implementation Details']]],
  ['technical_20implementation_20guide_7',['Network System Separation Technical Implementation Guide',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md496',1,'']]],
  ['technology_20stack_8',['🔧 Technology Stack',['../md_README.html#autotoc_md367',1,'']]],
  ['template_9',['📝 Completion Report Template',['../md_MIGRATION__CHECKLIST.html#autotoc_md131',1,'']]],
  ['test_10',['Initial Build Test',['../md_MIGRATION__CHECKLIST.html#autotoc_md91',1,'']]],
  ['test_20framework_11',['🧪 Test Framework',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md511',1,'']]],
  ['test_20structure_12',['1. Unit Test Structure',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md512',1,'']]],
  ['test_20suite_20priority_3a_20high_13',['3. Test Suite (Priority: High)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md218',1,'']]],
  ['testing_14',['testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md106',1,'Day 15: Integration Testing'],['../md_MIGRATION__CHECKLIST.html#autotoc_md111',1,'Day 16-17: Full System Testing'],['../md_BUILD.html#autotoc_md42',1,'Testing']]],
  ['testing_20during_20migration_15',['Testing During Migration',['../index.html#migration_testing',1,'']]],
  ['testing_20requirements_16',['Testing Requirements',['../index.html#contrib_testing',1,'']]],
  ['testing_20strategy_17',['testing strategy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md183',1,'🧪 Testing Strategy'],['../md_MIGRATION__CHECKLIST.html#autotoc_md76',1,'Day 3: Build System and Testing Strategy']]],
  ['testing_20strategy_20development_18',['Testing Strategy Development',['../md_MIGRATION__CHECKLIST.html#autotoc_md78',1,'']]],
  ['tests_19',['tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md184',1,'1. Unit Tests'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md185',1,'2. Integration Tests'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md513',1,'2. Integration Tests'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md186',1,'3. Performance Tests'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md187',1,'4. Stress Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md113',1,'Integration Tests'],['../md_BUILD.html#autotoc_md43',1,'Run Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md114',1,'Stress Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md112',1,'Unit Tests']]],
  ['tests_201_20week_20',['Stage 2: Samples and Tests (1 week)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md222',1,'']]],
  ['thread_5fsystem_20integration_21',['thread_system Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md99',1,'']]],
  ['time_20optimization_20lto_22',['Link-Time Optimization (LTO)',['../md_BUILD.html#autotoc_md41',1,'']]],
  ['timeline_23',['Implementation Timeline',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md235',1,'']]],
  ['tips_24',['Debugging Tips',['../index.html#trouble_debugging',1,'']]],
  ['to_202_200_200_25',['From 1.0.0 to 2.0.0',['../md_CHANGELOG.html#autotoc_md59',1,'']]],
  ['to_20be_20implemented_26',['To Be Implemented',['../md_CHANGELOG.html#autotoc_md48',1,'']]],
  ['tools_27',['tools',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md517',1,'2. Benchmark Tools'],['../md_README.html#autotoc_md370',1,'Build Tools']]],
  ['troubleshooting_28',['troubleshooting',['../index.html#troubleshooting_sec',1,'Troubleshooting'],['../md_BUILD.html#autotoc_md31',1,'Troubleshooting']]],
  ['troubleshooting_20guide_29',['🚨 Troubleshooting Guide',['../md_MIGRATION__CHECKLIST.html#autotoc_md126',1,'']]],
  ['tuning_30',['Performance Tuning',['../md_BUILD.html#autotoc_md39',1,'']]],
  ['txt_31',['Main CMakeLists.txt',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md176',1,'']]],
  ['txt_20creation_32',['CMakeLists.txt Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md89',1,'']]],
  ['txt_20update_33',['CMakeLists.txt Update',['../md_MIGRATION__CHECKLIST.html#autotoc_md104',1,'']]]
];
