var searchData=
[
  ['raii_20grade_20a_0',['리소스 관리 (RAII - Grade A)',['../md_README__KO.html#autotoc_md429',1,'']]],
  ['readme_1',['README',['../md_README.html',1,'']]],
  ['readme_5fko_2',['README_KO',['../md_README__KO.html',1,'']]],
  ['real_20network_20performance_20metrics_3',['Real Network Performance Metrics',['../md_BASELINE.html#autotoc_md15',1,'']]],
  ['recently_20completed_4',['Recently Completed',['../md_README.html#autotoc_md327',1,'']]],
  ['recommended_20for_20gradual_20migration_5',['Option 1: Compatibility Mode (Recommended for Gradual Migration)',['../md_MIGRATION.html#autotoc_md181',1,'']]],
  ['recommended_20for_20new_20projects_6',['Option 2: Full Migration (Recommended for New Projects)',['../md_MIGRATION.html#autotoc_md182',1,'']]],
  ['refactored_7',['Refactored',['../md_CHANGELOG.html#autotoc_md62',1,'']]],
  ['reference_20hardware_20configuration_20primary_8',['Reference Hardware Configuration (Primary)',['../md_BASELINE.html#autotoc_md5',1,'']]],
  ['reference_20to_20network_5fsystem_20functions_9',['Issue 1: Undefined Reference to network_system Functions',['../md_MIGRATION.html#autotoc_md223',1,'']]],
  ['references_10',['Step 3.3: Update Namespace References',['../md_MIGRATION.html#autotoc_md205',1,'']]],
  ['related_20documentation_11',['Related Documentation',['../md_UDP__SUPPORT.html#autotoc_md481',1,'']]],
  ['related_20projects_12',['related projects',['../md_README.html#autotoc_md302',1,'Related Projects'],['../md_MIGRATION.html#autotoc_md267',1,'Related Projects']]],
  ['reliability_20features_13',['Reliability Features',['../index.html#feat_reliability',1,'']]],
  ['removed_14',['Removed',['../md_CHANGELOG.html#autotoc_md96',1,'']]],
  ['reproducing_20benchmarks_15',['Reproducing Benchmarks',['../md_README.html#autotoc_md297',1,'']]],
  ['reproducing_20these_20measurements_16',['🔬 Reproducing These Measurements',['../md_BASELINE.html#autotoc_md22',1,'']]],
  ['required_17',['Required',['../md_README.html#autotoc_md319',1,'']]],
  ['required_20dependencies_18',['Required Dependencies',['../index.html#deps_required',1,'']]],
  ['requirements_19',['requirements',['../index.html#deps_build',1,'Build Requirements'],['../index.html#dependencies_sec',1,'Dependencies and Requirements'],['../md_README.html#autotoc_md279',1,'Requirements'],['../index.html#contrib_testing',1,'Testing Requirements']]],
  ['resource_20usage_20',['Resource Usage',['../md_MIGRATION.html#autotoc_md260',1,'']]],
  ['resources_21',['resources',['../md_STRUCTURE.html#autotoc_md462',1,'📝 Additional Resources'],['../md_MIGRATION.html#autotoc_md263',1,'Support and Resources']]],
  ['result_20t_20를_20사용한_20오류_20처리_22',['Result&lt;T&gt;를 사용한 오류 처리',['../md_README__KO.html#autotoc_md391',1,'']]],
  ['result_20t_20패턴_20예시_23',['Result&lt;T&gt; 패턴 예시',['../md_README__KO.html#autotoc_md359',1,'']]],
  ['results_24',['Benchmark Results',['../index.html#perf_benchmarks',1,'']]],
  ['roadmap_25',['Roadmap',['../md_README.html#autotoc_md326',1,'']]],
  ['rollback_26',['rollback',['../md_MIGRATION.html#autotoc_md254',1,'Partial Rollback'],['../md_MIGRATION.html#autotoc_md253',1,'Quick Rollback']]],
  ['rollback_20plan_27',['Rollback Plan',['../md_MIGRATION.html#autotoc_md252',1,'']]],
  ['run_20benchmarks_28',['Run Benchmarks',['../md_BASELINE.html#autotoc_md24',1,'']]],
  ['run_20migration_20scripts_29',['Step 4: Run Migration Scripts',['../md_STRUCTURE.html#autotoc_md456',1,'']]],
  ['run_20unit_20tests_30',['Step 4.2: Run Unit Tests',['../md_MIGRATION.html#autotoc_md211',1,'']]],
  ['running_20load_20tests_31',['Running Load Tests',['../md_BASELINE.html#autotoc_md18',1,'']]],
  ['runtime_20issues_32',['Runtime Issues',['../md_MIGRATION.html#autotoc_md227',1,'']]]
];
