var searchData=
[
  ['c_2020_20features_20not_20available_0',['C++20 Features Not Available',['../md_BUILD.html#autotoc_md36',1,'']]],
  ['cd_20pipeline_20status_1',['CI/CD Pipeline Status',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md224',1,'']]],
  ['cd_20status_2',['🎯 CI/CD Status',['../md_README.html#autotoc_md325',1,'']]],
  ['change_20history_3',['📝 Change History',['../md_README.html#autotoc_md477',1,'']]],
  ['changed_4',['Changed',['../md_CHANGELOG.html#autotoc_md52',1,'']]],
  ['changelog_5',['Changelog',['../md_CHANGELOG.html',1,'']]],
  ['changes_6',['changes',['../md_MIGRATION__CHECKLIST.html#autotoc_md86',1,'Namespace Changes'],['../md_CHANGELOG.html#autotoc_md60',1,'Namespace Changes']]],
  ['characteristics_7',['characteristics',['../md_README.html#autotoc_md306',1,'3. Performance Characteristics'],['../index.html#performance_sec',1,'Performance Characteristics']]],
  ['checklist_8',['checklist',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md202',1,'✅ Completion Checklist'],['../md_MIGRATION__CHECKLIST.html#autotoc_md134',1,'Final Checklist'],['../md_MIGRATION__CHECKLIST.html',1,'Network System Migration Checklist']]],
  ['checklist_20for_20network_5fsystem_20separation_20from_20messaging_5fsystem_9',['Detailed Execution Checklist for network_system Separation from messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md65',1,'']]],
  ['ci_20cd_20pipeline_20status_10',['CI/CD Pipeline Status',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md224',1,'']]],
  ['ci_20cd_20status_11',['🎯 CI/CD Status',['../md_README.html#autotoc_md325',1,'']]],
  ['class_12',['1. messaging_bridge Class',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md503',1,'']]],
  ['class_20implementation_13',['Day 9-10: Bridge Class Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md94',1,'']]],
  ['classes_201_202_20weeks_14',['Stage 1: Core Classes (1-2 weeks)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md221',1,'']]],
  ['classes_20priority_3a_20high_15',['1. Core Networking Classes (Priority: High)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md216',1,'']]],
  ['clean_20build_16',['Clean Build',['../md_BUILD.html#autotoc_md38',1,'']]],
  ['client_20usage_17',['Basic Client Usage',['../index.html#usage_client',1,'']]],
  ['cmake_20build_20system_18',['2. CMake Build System',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md175',1,'']]],
  ['cmake_20detection_19',['CMake Detection',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md229',1,'']]],
  ['cmake_20integration_20',['cmake integration',['../md_CHANGELOG.html#autotoc_md61',1,'CMake Integration'],['../md_BUILD.html#autotoc_md29',1,'CMake Integration']]],
  ['cmake_20module_20files_21',['1. CMake Module Files',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md508',1,'']]],
  ['cmake_20options_22',['CMake Options',['../md_BUILD.html#autotoc_md22',1,'']]],
  ['cmakelists_20txt_23',['Main CMakeLists.txt',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md176',1,'']]],
  ['cmakelists_20txt_20creation_24',['CMakeLists.txt Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md89',1,'']]],
  ['cmakelists_20txt_20update_25',['CMakeLists.txt Update',['../md_MIGRATION__CHECKLIST.html#autotoc_md104',1,'']]],
  ['code_20compatibility_20verification_26',['Existing Code Compatibility Verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md107',1,'']]],
  ['code_20copy_20and_20reorganization_27',['Code Copy and Reorganization',['../md_MIGRATION__CHECKLIST.html#autotoc_md84',1,'']]],
  ['code_20updates_28',['Code Updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md105',1,'']]],
  ['collection_29',['1. Performance Metric Collection',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md516',1,'']]],
  ['commands_30',['Build Commands',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md234',1,'']]],
  ['common_20issues_31',['common issues',['../md_BUILD.html#autotoc_md32',1,'Common Issues'],['../index.html#trouble_common',1,'Common Issues']]],
  ['compatibility_20api_20implementation_32',['Compatibility API Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md100',1,'']]],
  ['compatibility_20issues_33',['Compatibility Issues',['../md_MIGRATION__CHECKLIST.html#autotoc_md129',1,'']]],
  ['compatibility_20layer_34',['3. Compatibility Layer',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md151',1,'']]],
  ['compatibility_20verification_35',['compatibility verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md123',1,'Compatibility Verification'],['../md_MIGRATION__CHECKLIST.html#autotoc_md107',1,'Existing Code Compatibility Verification']]],
  ['compiler_20optimizations_36',['Compiler Optimizations',['../md_BUILD.html#autotoc_md40',1,'']]],
  ['completed_37',['Phase 1: Core Infrastructure ✅ (Completed)',['../md_README.html#autotoc_md314',1,'']]],
  ['completion_38',['v2.0.2 (Planned) - Integration Completion',['../md_README.html#autotoc_md480',1,'']]],
  ['completion_20checklist_39',['✅ Completion Checklist',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md202',1,'']]],
  ['completion_20report_40',['Task Completion Report',['../md_MIGRATION__CHECKLIST.html#autotoc_md132',1,'']]],
  ['completion_20report_20template_41',['📝 Completion Report Template',['../md_MIGRATION__CHECKLIST.html#autotoc_md131',1,'']]],
  ['completion_20summary_42',['Phase 1 Completion Summary',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md212',1,'']]],
  ['component_20implementation_43',['🔧 Core Component Implementation',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md502',1,'']]],
  ['components_44',['Core Components',['../md_README.html#autotoc_md303',1,'']]],
  ['components_20built_45',['Core Components Built',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md214',1,'']]],
  ['conditional_46',['Integration Dependencies (Conditional)',['../md_README.html#autotoc_md369',1,'']]],
  ['config_20file_47',['2. pkg-config File',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md509',1,'']]],
  ['configuration_48',['configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md88',1,'Day 8: Basic Build System Configuration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md90',1,'Dependency Configuration']]],
  ['configurations_49',['Example Configurations',['../md_BUILD.html#autotoc_md23',1,'']]],
  ['considerations_50',['Security Considerations',['../index.html#feat_security',1,'']]],
  ['contact_51',['contact',['../md_README.html#autotoc_md345',1,'📧 Contact'],['../md_README.html#autotoc_md390',1,'📧 Contact'],['../md_README.html#autotoc_md386',1,'📧 Contact'],['../md_README.html#autotoc_md382',1,'📧 Contact'],['../md_README.html#autotoc_md375',1,'📧 Contact'],['../md_README.html#autotoc_md365',1,'📧 Contact'],['../md_README.html#autotoc_md357',1,'📧 Contact'],['../md_README.html#autotoc_md353',1,'📧 Contact'],['../md_README.html#autotoc_md349',1,'📧 Contact'],['../md_README.html#autotoc_md402',1,'📧 Contact'],['../md_README.html#autotoc_md341',1,'📧 Contact'],['../md_README.html#autotoc_md333',1,'📧 Contact'],['../md_README.html#autotoc_md329',1,'📧 Contact'],['../md_README.html#autotoc_md323',1,'📧 Contact'],['../md_README.html#autotoc_md311',1,'📧 Contact'],['../md_README.html#autotoc_md337',1,'📧 Contact'],['../md_README.html#autotoc_md431',1,'📧 Contact'],['../md_README.html#autotoc_md493',1,'📧 Contact'],['../md_README.html#autotoc_md475',1,'📧 Contact'],['../md_README.html#autotoc_md465',1,'📧 Contact'],['../md_README.html#autotoc_md456',1,'📧 Contact'],['../md_README.html#autotoc_md451',1,'📧 Contact'],['../md_README.html#autotoc_md447',1,'📧 Contact'],['../md_README.html#autotoc_md443',1,'📧 Contact'],['../md_README.html#autotoc_md439',1,'📧 Contact'],['../md_README.html#autotoc_md435',1,'📧 Contact'],['../md_README.html#autotoc_md394',1,'📧 Contact'],['../md_README.html#autotoc_md427',1,'📧 Contact'],['../md_README.html#autotoc_md423',1,'📧 Contact'],['../md_README.html#autotoc_md419',1,'📧 Contact'],['../md_README.html#autotoc_md415',1,'📧 Contact'],['../md_README.html#autotoc_md410',1,'📧 Contact'],['../md_README.html#autotoc_md406',1,'📧 Contact'],['../md_README.html#autotoc_md486',1,'📧 Contact'],['../md_README.html#autotoc_md398',1,'📧 Contact'],['../md_README.html#autotoc_md264',1,'📧 Contact'],['../md_README.html#autotoc_md272',1,'📧 Contact'],['../md_README.html#autotoc_md242',1,'📧 Contact'],['../md_README.html#autotoc_md276',1,'📧 Contact'],['../md_README.html#autotoc_md268',1,'📧 Contact'],['../md_README.html#autotoc_md280',1,'📧 Contact'],['../md_README.html#autotoc_md250',1,'📧 Contact'],['../md_README.html#autotoc_md286',1,'📧 Contact'],['../md_README.html#autotoc_md256',1,'📧 Contact'],['../md_README.html#autotoc_md260',1,'📧 Contact'],['../md_README.html#autotoc_md298',1,'📧 Contact']]],
  ['contact_20and_20support_52',['contact and support',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md209',1,'📞 Contact and Support'],['../md_README.html#autotoc_md467',1,'📞 Contact and Support'],['../index.html#contact_sec',1,'Contact and Support']]],
  ['container_20integration_53',['Container Integration',['../md_CHANGELOG.html#autotoc_md62',1,'']]],
  ['container_20system_20integration_20details_54',['Container System Integration Details',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md228',1,'']]],
  ['container_5fsystem_20integration_55',['container_system Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md98',1,'']]],
  ['contents_56',['Table of Contents',['../md_BUILD.html#autotoc_md1',1,'']]],
  ['contributing_57',['contributing',['../md_README.html#autotoc_md247',1,'🤝 Contributing'],['../md_README.html#autotoc_md407',1,'🤝 Contributing'],['../md_README.html#autotoc_md395',1,'🤝 Contributing'],['../md_README.html#autotoc_md412',1,'🤝 Contributing'],['../md_README.html#autotoc_md253',1,'🤝 Contributing'],['../md_README.html#autotoc_md399',1,'🤝 Contributing'],['../md_README.html#autotoc_md416',1,'🤝 Contributing'],['../md_README.html#autotoc_md403',1,'🤝 Contributing'],['../md_README.html#autotoc_md420',1,'🤝 Contributing'],['../md_README.html#autotoc_md239',1,'🤝 Contributing'],['../md_README.html#autotoc_md424',1,'🤝 Contributing'],['../md_README.html#autotoc_md428',1,'🤝 Contributing'],['../md_README.html#autotoc_md432',1,'🤝 Contributing'],['../md_README.html#autotoc_md436',1,'🤝 Contributing'],['../md_README.html#autotoc_md440',1,'🤝 Contributing'],['../md_README.html#autotoc_md444',1,'🤝 Contributing'],['../md_README.html#autotoc_md448',1,'🤝 Contributing'],['../md_README.html#autotoc_md453',1,'🤝 Contributing'],['../md_README.html#autotoc_md462',1,'🤝 Contributing'],['../md_README.html#autotoc_md472',1,'🤝 Contributing'],['../md_README.html#autotoc_md483',1,'🤝 Contributing'],['../md_README.html#autotoc_md490',1,'🤝 Contributing'],['../md_README.html#autotoc_md391',1,'🤝 Contributing'],['../md_README.html#autotoc_md308',1,'🤝 Contributing'],['../md_README.html#autotoc_md320',1,'🤝 Contributing'],['../md_README.html#autotoc_md295',1,'🤝 Contributing'],['../md_README.html#autotoc_md326',1,'🤝 Contributing'],['../md_README.html#autotoc_md330',1,'🤝 Contributing'],['../md_README.html#autotoc_md283',1,'🤝 Contributing'],['../md_README.html#autotoc_md334',1,'🤝 Contributing'],['../md_README.html#autotoc_md338',1,'🤝 Contributing'],['../md_README.html#autotoc_md342',1,'🤝 Contributing'],['../md_README.html#autotoc_md277',1,'🤝 Contributing'],['../md_README.html#autotoc_md346',1,'🤝 Contributing'],['../md_README.html#autotoc_md350',1,'🤝 Contributing'],['../md_README.html#autotoc_md273',1,'🤝 Contributing'],['../md_README.html#autotoc_md362',1,'🤝 Contributing'],['../md_README.html#autotoc_md257',1,'🤝 Contributing'],['../md_README.html#autotoc_md387',1,'🤝 Contributing'],['../md_README.html#autotoc_md261',1,'🤝 Contributing'],['../md_README.html#autotoc_md383',1,'🤝 Contributing'],['../md_README.html#autotoc_md379',1,'🤝 Contributing'],['../md_README.html#autotoc_md265',1,'🤝 Contributing'],['../md_README.html#autotoc_md372',1,'🤝 Contributing'],['../md_README.html#autotoc_md354',1,'🤝 Contributing'],['../md_README.html#autotoc_md269',1,'🤝 Contributing'],['../index.html#contributing_sec',1,'Contributing']]],
  ['copy_20and_20reorganization_58',['Code Copy and Reorganization',['../md_MIGRATION__CHECKLIST.html#autotoc_md84',1,'']]],
  ['core_20api_59',['1. Core API',['../md_README.html#autotoc_md304',1,'']]],
  ['core_20api_20design_60',['2. Core API Design',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md504',1,'']]],
  ['core_20classes_201_202_20weeks_61',['Stage 1: Core Classes (1-2 weeks)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md221',1,'']]],
  ['core_20component_20implementation_62',['🔧 Core Component Implementation',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md502',1,'']]],
  ['core_20components_63',['Core Components',['../md_README.html#autotoc_md303',1,'']]],
  ['core_20components_20built_64',['Core Components Built',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md214',1,'']]],
  ['core_20dependencies_65',['Core Dependencies',['../md_README.html#autotoc_md368',1,'']]],
  ['core_20infrastructure_20✅_20completed_66',['Phase 1: Core Infrastructure ✅ (Completed)',['../md_README.html#autotoc_md314',1,'']]],
  ['core_20layer_67',['Core Layer',['../index.html#arch_core',1,'']]],
  ['core_20networking_20classes_20priority_3a_20high_68',['1. Core Networking Classes (Priority: High)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md216',1,'']]],
  ['core_20objectives_69',['Core Objectives',['../md_README.html#autotoc_md245',1,'']]],
  ['core_20separation_70',['v2.0.1 (Planned) - Core Separation',['../md_README.html#autotoc_md479',1,'']]],
  ['core_20system_20separation_71',['core system separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md81',1,'🔧 Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md204',1,'Phase 2: Core System Separation']]],
  ['core_20system_20separation_204_205_20days_72',['Phase 2: Core System Separation (4-5 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md158',1,'']]],
  ['creation_73',['creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md89',1,'CMakeLists.txt Creation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md82',1,'Day 4-5: Basic Structure Creation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md83',1,'Directory Structure Creation']]],
  ['criteria_74',['📊 Verification Criteria',['../md_MIGRATION__CHECKLIST.html#autotoc_md120',1,'']]],
  ['current_20state_20analysis_75',['current state analysis',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md143',1,'🏗️ Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md72',1,'Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md70',1,'Day 1: Backup and Current State Analysis']]],
  ['current_20structure_76',['Current Structure',['../md_README.html#autotoc_md302',1,'']]]
];
