var searchData=
[
  ['macos_0',['macos',['../md_BUILD.html#autotoc_md10',1,'macOS'],['../md_README.html#autotoc_md269',1,'macOS']]],
  ['main_20cmakelists_20txt_1',['Main CMakeLists.txt',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md228',1,'']]],
  ['major_20risks_2',['1. Major Risks',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md246',1,'']]],
  ['management_3',['management',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md309',1,'🔗 Dependency Management'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md307',1,'3. Session Management'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md231',1,'4. Dependency Management'],['../md_MIGRATION__GUIDE.html#autotoc_md167',1,'Package Management']]],
  ['manual_20installation_4',['Option 2: Manual Installation',['../md_BUILD.html#autotoc_md16',1,'']]],
  ['manual_20integration_5',['Manual Integration',['../md_BUILD.html#autotoc_md30',1,'']]],
  ['mapping_6',['Legacy Namespace Mapping',['../md_MIGRATION__GUIDE.html#autotoc_md155',1,'']]],
  ['messaging_5fbridge_20class_7',['1. messaging_bridge Class',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md305',1,'']]],
  ['messaging_5fbridge_20h_8',['messaging_bridge.h',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md230',1,'']]],
  ['messaging_5fbridge_20implementation_9',['messaging_bridge Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md105',1,'']]],
  ['messaging_5fsystem_10',['messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md75',1,'Detailed Execution Checklist for network_system Separation from messaging_system'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md189',1,'Detailed Plan for Separating network_system from messaging_system'],['../index.html#migration_from_legacy',1,'From Legacy messaging_system']]],
  ['messaging_5fsystem_20modification_11',['Day 13-14: messaging_system Modification',['../md_MIGRATION__CHECKLIST.html#autotoc_md113',1,'']]],
  ['messaging_5fsystem_20network_20structure_12',['messaging_system/network Structure',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md196',1,'']]],
  ['messaging_5fsystem_20to_20network_5fsystem_13',['messaging_system to network_system',['../md_CHANGELOG.html#autotoc_md69',1,'From messaging_system to network_system'],['../md_MIGRATION__GUIDE.html',1,'Migration Guide: messaging_system to network_system']]],
  ['messaging_5fsystem_20update_14',['messaging_system update',['../md_MIGRATION__CHECKLIST.html#autotoc_md112',1,'🔄 Phase 4: messaging_system Update'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md258',1,'Phase 4: messaging_system Update']]],
  ['messaging_5fsystem_20update_202_203_20days_15',['Phase 4: messaging_system Update (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md217',1,'']]],
  ['method_20missing_16',['3. API Method Missing',['../md_MIGRATION__GUIDE.html#autotoc_md178',1,'']]],
  ['metric_20collection_17',['1. Performance Metric Collection',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md318',1,'']]],
  ['metrics_18',['Performance Metrics',['../md_MIGRATION__GUIDE.html#autotoc_md183',1,'']]],
  ['migration_19',['migration',['../md_MIGRATION__GUIDE.html#autotoc_md165',1,'Build System Migration'],['../md_MIGRATION__GUIDE.html#autotoc_md150',1,'Quick Migration'],['../index.html#migration_testing',1,'Testing During Migration'],['../md_MIGRATION__GUIDE.html#autotoc_md170',1,'Testing Your Migration']]],
  ['migration_20checklist_20',['migration checklist',['../md_MIGRATION__GUIDE.html#autotoc_md185',1,'Migration Checklist'],['../md_MIGRATION__CHECKLIST.html',1,'Network System Migration Checklist']]],
  ['migration_20guide_21',['migration guide',['../index.html#migration_sec',1,'Migration Guide'],['../md_CHANGELOG.html#autotoc_md68',1,'Migration Guide']]],
  ['migration_20guide_3a_20messaging_5fsystem_20to_20network_5fsystem_22',['Migration Guide: messaging_system to network_system',['../md_MIGRATION__GUIDE.html',1,'']]],
  ['migration_20paths_23',['Migration Paths',['../md_MIGRATION__GUIDE.html#autotoc_md149',1,'']]],
  ['migration_20with_20bridge_24',['Migration with Bridge',['../index.html#usage_bridge',1,'']]],
  ['mingw_25',['Windows (MSYS2/MinGW)',['../md_BUILD.html#autotoc_md18',1,'']]],
  ['minimal_20build_26',['Minimal Build',['../md_BUILD.html#autotoc_md24',1,'']]],
  ['minimum_20requirements_27',['Minimum Requirements',['../md_BUILD.html#autotoc_md3',1,'']]],
  ['missing_28',['3. API Method Missing',['../md_MIGRATION__GUIDE.html#autotoc_md178',1,'']]],
  ['mission_29',['Mission',['../index.html#mission_sec',1,'']]],
  ['mitigation_30',['🚨 Risk Factors and Mitigation',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md245',1,'']]],
  ['mode_31',['Step 2: Update Includes (Compatibility Mode)',['../md_MIGRATION__GUIDE.html#autotoc_md152',1,'']]],
  ['modern_20api_32',['modern api',['../md_MIGRATION__GUIDE.html#autotoc_md160',1,'Modern API'],['../md_MIGRATION__GUIDE.html#autotoc_md163',1,'Modern API']]],
  ['modern_20api_20usage_33',['Modern API Usage',['../md_README.html#autotoc_md273',1,'']]],
  ['modern_20namespace_20structure_34',['Modern Namespace Structure',['../md_MIGRATION__GUIDE.html#autotoc_md156',1,'']]],
  ['modification_35',['Day 13-14: messaging_system Modification',['../md_MIGRATION__CHECKLIST.html#autotoc_md113',1,'']]],
  ['module_20files_36',['1. CMake Module Files',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md310',1,'']]],
  ['module_20layer_20structure_37',['1. Module Layer Structure',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md301',1,'']]],
  ['monitoring_38',['📊 Performance Monitoring',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md317',1,'']]],
  ['monitoring_20implementation_39',['Performance Monitoring Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md106',1,'']]],
  ['msys2_40',['Windows (MSYS2)',['../md_README.html#autotoc_md270',1,'']]],
  ['msys2_20mingw_41',['Windows (MSYS2/MinGW)',['../md_BUILD.html#autotoc_md18',1,'']]]
];
