var searchData=
[
  ['recommended_0',['recommended',['../md_BUILD.html#autotoc_md56',1,'Option 1: vcpkg (Recommended)'],['../md_RELEASE__NOTES.html#autotoc_md404',1,'Recommended']]],
  ['recovery_1',['recovery',['../md_OPERATIONS.html#autotoc_md327',1,'Backup and Recovery'],['../md_OPERATIONS.html#autotoc_md329',1,'Disaster Recovery']]],
  ['recovery_20strategies_2',['Error Recovery Strategies',['../md_TROUBLESHOOTING.html#autotoc_md509',1,'']]],
  ['reference_3',['reference',['../md_API__REFERENCE.html',1,'API Reference'],['../md_TROUBLESHOOTING.html#autotoc_md507',1,'Error Reference']]],
  ['reference_20errors_4',['1. Undefined Reference Errors',['../md_MIGRATION__GUIDE.html#autotoc_md217',1,'']]],
  ['references_5',['references',['../md_TROUBLESHOOTING.html#autotoc_md482',1,'Circular References'],['../md_TROUBLESHOOTING.html#autotoc_md488',1,'Undefined References']]],
  ['refused_6',['Connection Refused',['../md_TROUBLESHOOTING.html#autotoc_md466',1,'']]],
  ['release_20highlights_7',['🎉 Release Highlights',['../md_RELEASE__NOTES.html#autotoc_md381',1,'']]],
  ['release_20notes_8',['Network System v2.0.0 Release Notes',['../md_RELEASE__NOTES.html',1,'']]],
  ['reliability_20features_9',['Reliability Features',['../index.html#feat_reliability',1,'']]],
  ['reorganization_10',['reorganization',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md266',1,'1. Directory Structure Reorganization'],['../md_MIGRATION__CHECKLIST.html#autotoc_md135',1,'Code Copy and Reorganization']]],
  ['report_11',['Task Completion Report',['../md_MIGRATION__CHECKLIST.html#autotoc_md183',1,'']]],
  ['report_20template_12',['📝 Completion Report Template',['../md_MIGRATION__CHECKLIST.html#autotoc_md182',1,'']]],
  ['required_13',['Required',['../md_README.html#autotoc_md371',1,'']]],
  ['required_20dependencies_14',['Required Dependencies',['../index.html#deps_required',1,'']]],
  ['requirements_15',['requirements',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md282',1,'📊 Performance Requirements'],['../md_RELEASE__NOTES.html#autotoc_md402',1,'📋 Requirements'],['../md_OPERATIONS.html#autotoc_md343',1,'Audit Requirements'],['../index.html#deps_build',1,'Build Requirements'],['../index.html#dependencies_sec',1,'Dependencies and Requirements'],['../md_RELEASE__NOTES.html#autotoc_md403',1,'Minimum Requirements'],['../md_BUILD.html#autotoc_md44',1,'Minimum Requirements'],['../index.html#contrib_testing',1,'Testing Requirements']]],
  ['resource_20limits_16',['Resource Limits',['../md_OPERATIONS.html#autotoc_md324',1,'']]],
  ['resources_17',['Support Resources',['../md_TROUBLESHOOTING.html#autotoc_md510',1,'']]],
  ['response_20times_18',['Slow Response Times',['../md_TROUBLESHOOTING.html#autotoc_md459',1,'']]],
  ['result_20type_19',['Result Type',['../md_API__REFERENCE.html#autotoc_md19',1,'']]],
  ['results_20',['results',['../index.html#perf_benchmarks',1,'Benchmark Results'],['../md_CHANGELOG.html#autotoc_md93',1,'Performance Results']]],
  ['results_20v2_200_200_21',['Latest Results (v2.0.0)',['../md_README.html#autotoc_md360',1,'']]],
  ['retention_20policies_22',['Retention Policies',['../md_OPERATIONS.html#autotoc_md344',1,'']]],
  ['risk_20assessment_23',['Risk Assessment',['../md_MIGRATION__CHECKLIST.html#autotoc_md130',1,'']]],
  ['risk_20factors_20and_20mitigation_24',['🚨 Risk Factors and Mitigation',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md286',1,'']]],
  ['risks_25',['1. Major Risks',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md287',1,'']]],
  ['roadmap_26',['📅 Implementation Roadmap',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md246',1,'']]],
  ['rollback_20plan_27',['2. Rollback Plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md288',1,'']]],
  ['rolling_20updates_28',['Rolling Updates',['../md_OPERATIONS.html#autotoc_md341',1,'']]],
  ['run_20benchmarks_29',['Run Benchmarks',['../md_BUILD.html#autotoc_md85',1,'']]],
  ['run_20tests_30',['Run Tests',['../md_BUILD.html#autotoc_md84',1,'']]],
  ['runtime_31',['Visual Studio Runtime',['../md_TROUBLESHOOTING.html#autotoc_md506',1,'']]],
  ['runtime_20test_32',['2. Runtime Test',['../md_MIGRATION__GUIDE.html#autotoc_md213',1,'']]]
];
