var searchData=
[
  ['macos_0',['macos',['../md_README.html#autotoc_md396',1,'macOS'],['../md_README__KO.html#autotoc_md481',1,'macOS']]],
  ['management_1',['management',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md138',1,'RAII Resource Management'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md184',1,'RAII Resource Management']]],
  ['management_20raii_20grade_20a_2',['Resource Management (RAII - Grade A)',['../md_README.html#autotoc_md441',1,'']]],
  ['matrix_3',['Version Support Matrix',['../md_CHANGELOG.html#autotoc_md71',1,'']]],
  ['measurement_4',['Performance Measurement',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md140',1,'']]],
  ['measurements_5',['🔬 Reproducing These Measurements',['../md_BASELINE.html#autotoc_md20',1,'']]],
  ['memory_20efficiency_6',['memory efficiency',['../md_BASELINE.html#autotoc_md12',1,'Memory Efficiency'],['../md_README.html#autotoc_md381',1,'Memory Efficiency']]],
  ['memory_20leak_7',['1. Session Vector Memory Leak',['../md_IMPROVEMENTS.html#autotoc_md209',1,'']]],
  ['memory_20leak_20warnings_8',['Issue 7: Memory Leak Warnings',['../md_MIGRATION.html#autotoc_md316',1,'']]],
  ['message_20size_9',['Throughput Performance by Message Size',['../md_README.html#autotoc_md378',1,'']]],
  ['message_20throughput_10',['Message Throughput',['../md_BASELINE.html#autotoc_md9',1,'']]],
  ['messaging_5fsystem으로부터_20분리_20이전_11',['[0.9.0] - 2025-09-15 (messaging_system으로부터 분리 이전)',['../md_CHANGELOG__KO.html#autotoc_md96',1,'']]],
  ['messaging_5fsystem_12',['messaging_system',['../md_CHANGELOG.html#autotoc_md65',1,'[0.9.0] - 2025-09-15 (Pre-separation from messaging_system)'],['../index.html#migration_from_legacy',1,'From Legacy messaging_system']]],
  ['messaging_5fsystem_20to_20network_5fsystem_13',['Migration Guide: messaging_system to network_system',['../md_MIGRATION.html',1,'']]],
  ['metrics_14',['metrics',['../md_MIGRATION.html#autotoc_md345',1,'Concurrency Metrics'],['../md_MIGRATION.html#autotoc_md344',1,'Latency Metrics'],['../md_BASELINE.html',1,'Network System - Performance Baseline Metrics'],['../md_MIGRATION.html#autotoc_md343',1,'Throughput Metrics']]],
  ['metrics_20collected_15',['Metrics Collected',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md141',1,'']]],
  ['metrics_20intel_20i7_2012700k_16',['Performance Metrics (Intel i7-12700K)',['../md_BASELINE.html#autotoc_md8',1,'']]],
  ['migration_17',['migration',['../md_MIGRATION.html#autotoc_md272',1,'Build System Migration'],['../md_MIGRATION.html#autotoc_md273',1,'Code Migration'],['../md_MIGRATION.html#autotoc_md267',1,'Option 1: Compatibility Mode (Recommended for Gradual Migration)'],['../md_MIGRATION.html#autotoc_md295',1,'Phase 4: Verify Migration'],['../md_MIGRATION.html#autotoc_md271',1,'Pre-Migration'],['../index.html#migration_testing',1,'Testing During Migration'],['../md_MIGRATION.html#autotoc_md324',1,'Testing Your Migration'],['../md_MIGRATION.html#autotoc_md265',1,'Why This Migration']]],
  ['migration_20checklist_18',['Quick Migration Checklist',['../md_MIGRATION.html#autotoc_md270',1,'']]],
  ['migration_20complete_20✅_19',['Phase 3: Error Handling (75-80% Complete) - Core API Migration Complete ✅',['../md_README.html#autotoc_md444',1,'']]],
  ['migration_20complete_2075_2080_20complete_20',['Error Handling (Core API Migration Complete - 75-80% Complete)',['../md_README.html#autotoc_md442',1,'']]],
  ['migration_20guide_21',['migration guide',['../md_STRUCTURE.html#autotoc_md543',1,'🔄 Migration Guide'],['../index.html#migration_sec',1,'Migration Guide'],['../md_CHANGELOG.html#autotoc_md73',1,'Migration Guide'],['../md_MIGRATION.html#autotoc_md277',1,'Step-by-Step Migration Guide']]],
  ['migration_20guide_3a_20messaging_5fsystem_20to_20network_5fsystem_22',['Migration Guide: messaging_system to network_system',['../md_MIGRATION.html',1,'']]],
  ['migration_20issues_23',['Common Migration Issues',['../md_MIGRATION.html#autotoc_md307',1,'']]],
  ['migration_20paths_24',['Migration Paths',['../md_MIGRATION.html#autotoc_md266',1,'']]],
  ['migration_20recommended_20for_20new_20projects_25',['Option 2: Full Migration (Recommended for New Projects)',['../md_MIGRATION.html#autotoc_md268',1,'']]],
  ['migration_20scripts_26',['Step 4: Run Migration Scripts',['../md_STRUCTURE.html#autotoc_md547',1,'']]],
  ['migration_20status_27',['🚀 Migration Status',['../md_README.html#autotoc_md422',1,'']]],
  ['migration_20strategy_28',['Step 3.1: Choose Your Migration Strategy',['../md_MIGRATION.html#autotoc_md289',1,'']]],
  ['migration_20with_20bridge_29',['Migration with Bridge',['../index.html#usage_bridge',1,'']]],
  ['minutes_30',['Getting Started in 5 Minutes',['../md_README.html#autotoc_md393',1,'']]],
  ['mission_31',['mission',['../index.html#mission_sec',1,'Mission'],['../md_README.html#autotoc_md368',1,'Project Purpose &amp; Mission']]],
  ['mode_20recommended_20for_20gradual_20migration_32',['Option 1: Compatibility Mode (Recommended for Gradual Migration)',['../md_MIGRATION.html#autotoc_md267',1,'']]],
  ['modern_20api_33',['Step 3.5: Update API Calls (If Using Modern API)',['../md_MIGRATION.html#autotoc_md293',1,'']]],
  ['modern_20api_20usage_34',['Modern API Usage',['../md_README.html#autotoc_md400',1,'']]],
  ['msys2_35',['msys2',['../md_README.html#autotoc_md397',1,'Windows (MSYS2)'],['../md_README__KO.html#autotoc_md482',1,'Windows (MSYS2)']]],
  ['multiple_20configurations_36',['Test 2: Multiple Configurations',['../md_MIGRATION.html#autotoc_md327',1,'']]]
];
