var searchData=
[
  ['package_20configuration_20optional_0',['Step 2.2: Update Package Configuration (Optional)',['../md_MIGRATION.html#autotoc_md202',1,'']]],
  ['partial_20rollback_1',['Partial Rollback',['../md_MIGRATION.html#autotoc_md257',1,'']]],
  ['paths_2',['paths',['../md_MIGRATION.html#autotoc_md183',1,'Migration Paths'],['../md_STRUCTURE.html#autotoc_md460',1,'Step 2: Update Include Paths']]],
  ['patterns_3',['Design Patterns',['../md_UDP__SUPPORT.html#autotoc_md484',1,'']]],
  ['performance_4',['Performance',['../md_UDP__SUPPORT.html#autotoc_md485',1,'']]],
  ['performance_20baseline_20metrics_5',['Network System - Performance Baseline Metrics',['../md_BASELINE.html',1,'']]],
  ['performance_20benchmarks_6',['Performance Benchmarks',['../md_CHANGELOG.html#autotoc_md112',1,'']]],
  ['performance_20characteristics_7',['performance characteristics',['../md_STRUCTURE.html#autotoc_md457',1,'📊 Performance Characteristics'],['../index.html#performance_sec',1,'Performance Characteristics']]],
  ['performance_20expectations_8',['Performance Expectations',['../md_MIGRATION.html#autotoc_md259',1,'']]],
  ['performance_20highlights_9',['Performance Highlights',['../md_README.html#autotoc_md299',1,'']]],
  ['performance_20issues_10',['Performance Issues',['../md_MIGRATION.html#autotoc_md234',1,'']]],
  ['performance_20metrics_11',['Real Network Performance Metrics',['../md_BASELINE.html#autotoc_md15',1,'']]],
  ['performance_20metrics_20intel_20i7_2012700k_20ubuntu_2022_2004_20gcc_2011_20tt_20o3_20tt_12',['Performance Metrics (Intel i7-12700K, Ubuntu 22.04, GCC 11 &lt;tt&gt;-O3&lt;/tt&gt;)',['../md_BASELINE.html#autotoc_md8',1,'']]],
  ['performance_20optimizations_13',['Performance Optimizations',['../index.html#feat_perf',1,'']]],
  ['performance_20tests_14',['Performance Tests',['../md_MIGRATION.html#autotoc_md248',1,'']]],
  ['phase_200_20체크리스트_15',['Phase 0 체크리스트',['../md_BASELINE__KO.html#autotoc_md41',1,'']]],
  ['phase_200_20checklist_16',['Phase 0 Checklist',['../md_BASELINE.html#autotoc_md13',1,'']]],
  ['phase_201_3a_20preparation_17',['Phase 1: Preparation',['../md_MIGRATION.html#autotoc_md195',1,'']]],
  ['phase_202_3a_20update_20build_20configuration_18',['Phase 2: Update Build Configuration',['../md_MIGRATION.html#autotoc_md200',1,'']]],
  ['phase_203_3a_20오류_20처리_2075_2080_20완료_20핵심_20api_20마이그레이션_20완료_20✅_19',['Phase 3: 오류 처리 (75-80% 완료) - 핵심 API 마이그레이션 완료 ✅',['../md_README__KO.html#autotoc_md445',1,'']]],
  ['phase_203_3a_20update_20code_20',['Phase 3: Update Code',['../md_MIGRATION.html#autotoc_md205',1,'']]],
  ['phase_204_3a_20verify_20migration_21',['Phase 4: Verify Migration',['../md_MIGRATION.html#autotoc_md212',1,'']]],
  ['placeholder_22',['Expected Metrics (Placeholder)',['../md_BASELINE.html#autotoc_md20',1,'']]],
  ['plan_23',['Rollback Plan',['../md_MIGRATION.html#autotoc_md255',1,'']]],
  ['planned_24',['Planned',['../md_CHANGELOG.html#autotoc_md66',1,'']]],
  ['planned_20features_25',['Planned Features',['../md_README.html#autotoc_md335',1,'']]],
  ['platform_20support_26',['Platform Support',['../md_README.html#autotoc_md315',1,'']]],
  ['pool_20adapters_27',['Thread Pool Adapters',['../md_README.html#autotoc_md308',1,'']]],
  ['pre_20migration_28',['Pre-Migration',['../md_MIGRATION.html#autotoc_md188',1,'']]],
  ['pre_20separation_20from_20messaging_5fsystem_29',['[0.9.0] - 2025-09-15 (Pre-separation from messaging_system)',['../md_CHANGELOG.html#autotoc_md102',1,'']]],
  ['preparation_30',['Phase 1: Preparation',['../md_MIGRATION.html#autotoc_md195',1,'']]],
  ['prerequisites_31',['prerequisites',['../md_README.html#autotoc_md287',1,'Prerequisites'],['../md_MIGRATION.html#autotoc_md198',1,'Step 1.3: Verify Prerequisites']]],
  ['presets_20recommended_32',['Using CMake Presets (Recommended)',['../md_README.html#autotoc_md326',1,'']]],
  ['primary_33',['Reference Hardware Configuration (Primary)',['../md_BASELINE.html#autotoc_md5',1,'']]],
  ['production_20quality_34',['Production Quality',['../md_README.html#autotoc_md317',1,'']]],
  ['project_35',['Network System Project',['../md_README__KO.html#autotoc_md347',1,'']]],
  ['project_20information_36',['Project Information',['../md_CHANGELOG.html#autotoc_md106',1,'']]],
  ['project_20structure_37',['Network System - Project Structure',['../md_STRUCTURE.html',1,'']]],
  ['projects_38',['projects',['../md_MIGRATION.html#autotoc_md185',1,'Option 2: Full Migration (Recommended for New Projects)'],['../md_README.html#autotoc_md306',1,'Related Projects'],['../md_MIGRATION.html#autotoc_md270',1,'Related Projects']]],
  ['protocols_39',['Protocols',['../md_README.html#autotoc_md294',1,'']]],
  ['public_20api_20layer_20tt_20include_20network_5fsystem_20tt_40',['🎯 Public API Layer (&lt;tt&gt;include/network_system/&lt;/tt&gt;)',['../md_STRUCTURE.html#autotoc_md454',1,'']]]
];
