var searchData=
[
  ['table_20of_20contents_0',['Table of Contents',['../md_BUILD.html#autotoc_md1',1,'']]],
  ['target_20after_20separation_1',['Target (After Separation)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md194',1,'']]],
  ['target_20post_20separation_2',['Target (Post-Separation)',['../md_README.html#autotoc_md385',1,'']]],
  ['target_20structure_3',['Target Structure',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md177',1,'']]],
  ['task_20completion_20report_4',['Task Completion Report',['../md_MIGRATION__CHECKLIST.html#autotoc_md135',1,'']]],
  ['tasks_5',['Backup Tasks',['../md_MIGRATION__CHECKLIST.html#autotoc_md74',1,'']]],
  ['technical_20implementation_20details_6',['technical implementation details',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md175',1,'🛠️ Technical Implementation Details'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html',1,'Technical Implementation Details']]],
  ['technical_20implementation_20guide_7',['Network System Separation Technical Implementation Guide',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md470',1,'']]],
  ['technology_20stack_8',['🔧 Technology Stack',['../md_README.html#autotoc_md341',1,'']]],
  ['template_9',['📝 Completion Report Template',['../md_MIGRATION__CHECKLIST.html#autotoc_md134',1,'']]],
  ['test_10',['Initial Build Test',['../md_MIGRATION__CHECKLIST.html#autotoc_md94',1,'']]],
  ['test_20framework_11',['🧪 Test Framework',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md485',1,'']]],
  ['test_20structure_12',['1. Unit Test Structure',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md486',1,'']]],
  ['testing_13',['testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md109',1,'Day 15: Integration Testing'],['../md_MIGRATION__CHECKLIST.html#autotoc_md114',1,'Day 16-17: Full System Testing'],['../md_BUILD.html#autotoc_md42',1,'Testing']]],
  ['testing_20during_20migration_14',['Testing During Migration',['../index.html#migration_testing',1,'']]],
  ['testing_20requirements_15',['Testing Requirements',['../index.html#contrib_testing',1,'']]],
  ['testing_20strategy_16',['testing strategy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md186',1,'🧪 Testing Strategy'],['../md_MIGRATION__CHECKLIST.html#autotoc_md79',1,'Day 3: Build System and Testing Strategy']]],
  ['testing_20strategy_20development_17',['Testing Strategy Development',['../md_MIGRATION__CHECKLIST.html#autotoc_md81',1,'']]],
  ['tests_18',['tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md187',1,'1. Unit Tests'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md188',1,'2. Integration Tests'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md487',1,'2. Integration Tests'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md189',1,'3. Performance Tests'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md190',1,'4. Stress Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md116',1,'Integration Tests'],['../md_BUILD.html#autotoc_md43',1,'Run Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md117',1,'Stress Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md115',1,'Unit Tests']]],
  ['thread_5fsystem_20integration_19',['thread_system Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md102',1,'']]],
  ['time_20optimization_20lto_20',['Link-Time Optimization (LTO)',['../md_BUILD.html#autotoc_md41',1,'']]],
  ['timeline_21',['Development Timeline',['../md_CHANGELOG.html#autotoc_md60',1,'']]],
  ['tips_22',['Debugging Tips',['../index.html#trouble_debugging',1,'']]],
  ['to_20be_20implemented_23',['To Be Implemented',['../md_CHANGELOG.html#autotoc_md48',1,'']]],
  ['to_20network_5fsystem_24',['From messaging_system to network_system',['../md_CHANGELOG.html#autotoc_md62',1,'']]],
  ['tools_25',['tools',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md491',1,'2. Benchmark Tools'],['../md_README.html#autotoc_md344',1,'Build Tools']]],
  ['troubleshooting_26',['troubleshooting',['../index.html#troubleshooting_sec',1,'Troubleshooting'],['../md_BUILD.html#autotoc_md31',1,'Troubleshooting']]],
  ['troubleshooting_20guide_27',['🚨 Troubleshooting Guide',['../md_MIGRATION__CHECKLIST.html#autotoc_md129',1,'']]],
  ['tuning_28',['Performance Tuning',['../md_BUILD.html#autotoc_md39',1,'']]],
  ['txt_29',['Main CMakeLists.txt',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md179',1,'']]],
  ['txt_20creation_30',['CMakeLists.txt Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md92',1,'']]],
  ['txt_20update_31',['CMakeLists.txt Update',['../md_MIGRATION__CHECKLIST.html#autotoc_md107',1,'']]]
];
