var searchData=
[
  ['a_0',['리소스 관리 (RAII - Grade A)',['../md_README__KO.html#autotoc_md417',1,'']]],
  ['acknowledgments_1',['Acknowledgments',['../md_README.html#autotoc_md330',1,'']]],
  ['add_20initialization_20code_2',['Step 3.4: Add Initialization Code',['../md_MIGRATION.html#autotoc_md204',1,'']]],
  ['added_3',['added',['../md_CHANGELOG.html#autotoc_md62',1,'Added'],['../md_CHANGELOG.html#autotoc_md100',1,'Added'],['../md_CHANGELOG.html#autotoc_md92',1,'Added'],['../md_CHANGELOG.html#autotoc_md87',1,'Added'],['../md_CHANGELOG.html#autotoc_md82',1,'Added'],['../md_CHANGELOG.html#autotoc_md77',1,'Added'],['../md_CHANGELOG.html#autotoc_md72',1,'Added'],['../md_CHANGELOG.html#autotoc_md66',1,'Added']]],
  ['additional_20resources_4',['📝 Additional Resources',['../md_STRUCTURE.html#autotoc_md450',1,'']]],
  ['advanced_20topics_5',['Advanced Topics',['../md_README.html#autotoc_md301',1,'']]],
  ['advantages_6',['Advantages',['../md_UDP__SUPPORT.html#autotoc_md459',1,'']]],
  ['after_20examples_7',['Before and After Examples',['../md_MIGRATION.html#autotoc_md212',1,'']]],
  ['and_20after_20examples_8',['Before and After Examples',['../md_MIGRATION.html#autotoc_md212',1,'']]],
  ['and_20requirements_9',['Dependencies and Requirements',['../index.html#dependencies_sec',1,'']]],
  ['and_20resources_10',['Support and Resources',['../md_MIGRATION.html#autotoc_md261',1,'']]],
  ['and_20support_11',['Contact and Support',['../index.html#contact_sec',1,'']]],
  ['api_20마이그레이션_20완료_20✅_12',['Phase 3: 오류 처리 (75-80% 완료) - 핵심 API 마이그레이션 완료 ✅',['../md_README__KO.html#autotoc_md427',1,'']]],
  ['api_20마이그레이션_20완료_2075_2080_20완료_13',['오류 처리 (핵심 API 마이그레이션 완료 - 75-80% 완료)',['../md_README__KO.html#autotoc_md418',1,'']]],
  ['api_20문서_14',['📚 API 문서',['../md_README__KO.html#autotoc_md375',1,'']]],
  ['api_20사용법_15',['api 사용법',['../md_README__KO.html#autotoc_md371',1,'TCP API 사용법'],['../md_README__KO.html#autotoc_md372',1,'WebSocket API 사용법']]],
  ['api_20예제_16',['📝 API 예제',['../md_README__KO.html#autotoc_md370',1,'']]],
  ['api_20참조_17',['빠른 API 참조',['../md_README__KO.html#autotoc_md376',1,'']]],
  ['api_20호환성_18',['레거시 API 호환성',['../md_README__KO.html#autotoc_md373',1,'']]],
  ['api_20calls_20if_20using_20modern_20api_19',['Step 3.5: Update API Calls (If Using Modern API)',['../md_MIGRATION.html#autotoc_md205',1,'']]],
  ['api_20layer_20tt_20include_20network_5fsystem_20tt_20',['🎯 Public API Layer (&lt;tt&gt;include/network_system/&lt;/tt&gt;)',['../md_STRUCTURE.html#autotoc_md436',1,'']]],
  ['application_20tests_21',['Test 7: Existing Application Tests',['../md_MIGRATION.html#autotoc_md247',1,'']]],
  ['architecture_22',['Architecture',['../md_UDP__SUPPORT.html#autotoc_md465',1,'']]],
  ['architecture_20overview_23',['architecture overview',['../md_README.html#autotoc_md293',1,'Architecture Overview'],['../index.html#architecture_sec',1,'Architecture Overview']]],
  ['asio_20not_20found_24',['Issue 4: ASIO Not Found',['../md_MIGRATION.html#autotoc_md224',1,'']]],
  ['asynchronous_20model_25',['Asynchronous Model',['../md_README.html#autotoc_md285',1,'']]],
  ['asynchronous_20operations_26',['Asynchronous Operations',['../index.html#feat_async',1,'']]],
  ['audit_20current_20network_20usage_27',['Step 1.2: Audit Current Network Usage',['../md_MIGRATION.html#autotoc_md192',1,'']]],
  ['automated_20baseline_20collection_28',['Automated Baseline Collection',['../md_BASELINE.html#autotoc_md19',1,'']]]
];
