var searchData=
[
  ['database_20scaling_0',['Database Scaling',['../md_OPERATIONS.html#autotoc_md338',1,'']]],
  ['day_201_1',['Day 1',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md249',1,'']]],
  ['day_2011_2012_2',['Day 11-12',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md258',1,'']]],
  ['day_2011_2012_3a_20external_20system_20integration_3',['Day 11-12: External System Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md149',1,'']]],
  ['day_2013_2014_4',['Day 13-14',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md260',1,'']]],
  ['day_2013_2014_3a_20messaging_5fsystem_20modification_5',['Day 13-14: messaging_system Modification',['../md_MIGRATION__CHECKLIST.html#autotoc_md155',1,'']]],
  ['day_2015_6',['Day 15',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md261',1,'']]],
  ['day_2015_3a_20integration_20testing_7',['Day 15: Integration Testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md158',1,'']]],
  ['day_2016_2017_8',['Day 16-17',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md263',1,'']]],
  ['day_2016_2017_3a_20full_20system_20testing_9',['Day 16-17: Full System Testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md163',1,'']]],
  ['day_2018_10',['Day 18',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md264',1,'']]],
  ['day_2018_3a_20final_20verification_20and_20deployment_11',['Day 18: Final Verification and Deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md167',1,'']]],
  ['day_201_3a_20backup_20and_20current_20state_20analysis_12',['Day 1: Backup and Current State Analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md122',1,'']]],
  ['day_202_13',['Day 2',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md250',1,'']]],
  ['day_202_3a_20design_20and_20planning_14',['Day 2: Design and Planning',['../md_MIGRATION__CHECKLIST.html#autotoc_md125',1,'']]],
  ['day_203_15',['Day 3',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md251',1,'']]],
  ['day_203_3a_20build_20system_20and_20testing_20strategy_16',['Day 3: Build System and Testing Strategy',['../md_MIGRATION__CHECKLIST.html#autotoc_md128',1,'']]],
  ['day_204_205_17',['Day 4-5',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md253',1,'']]],
  ['day_204_205_3a_20basic_20structure_20creation_18',['Day 4-5: Basic Structure Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md134',1,'']]],
  ['day_206_207_19',['Day 6-7',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md254',1,'']]],
  ['day_206_207_3a_20namespace_20and_20include_20path_20updates_20',['Day 6-7: Namespace and Include Path Updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md137',1,'']]],
  ['day_208_21',['Day 8',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md255',1,'']]],
  ['day_208_3a_20basic_20build_20system_20configuration_22',['Day 8: Basic Build System Configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md140',1,'']]],
  ['day_209_2010_23',['Day 9-10',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md257',1,'']]],
  ['day_209_2010_3a_20bridge_20class_20implementation_24',['Day 9-10: Bridge Class Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md146',1,'']]],
  ['days_25',['days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md248',1,'Phase 1: Preparation and Analysis (2-3 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md252',1,'Phase 2: Core System Separation (4-5 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md256',1,'Phase 3: Integration Interface Implementation (3-4 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md259',1,'Phase 4: messaging_system Update (2-3 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md262',1,'Phase 5: Verification and Deployment (2-3 days)']]],
  ['debian_26',['debian',['../md_BUILD.html#autotoc_md48',1,'Ubuntu/Debian'],['../md_README.html#autotoc_md352',1,'Ubuntu/Debian']]],
  ['debug_20build_27',['Debug Build',['../md_BUILD.html#autotoc_md67',1,'']]],
  ['debug_20build_20issues_28',['Debug Build Issues',['../md_BUILD.html#autotoc_md78',1,'']]],
  ['debug_20logging_29',['Enable Debug Logging',['../md_TROUBLESHOOTING.html#autotoc_md455',1,'']]],
  ['debugging_20techniques_30',['Debugging Techniques',['../md_TROUBLESHOOTING.html#autotoc_md450',1,'']]],
  ['debugging_20tips_31',['Debugging Tips',['../index.html#trouble_debugging',1,'']]],
  ['degradation_32',['degradation',['../md_MIGRATION__GUIDE.html#autotoc_md221',1,'4. Performance Degradation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md180',1,'Performance Degradation']]],
  ['delete_33',['Missing Delete',['../md_TROUBLESHOOTING.html#autotoc_md482',1,'']]],
  ['dependencies_34',['dependencies',['../md_README.html#autotoc_md371',1,'🔧 Dependencies'],['../md_BUILD.html#autotoc_md49',1,'Install Dependencies'],['../md_BUILD.html#autotoc_md52',1,'Install Dependencies'],['../md_BUILD.html#autotoc_md55',1,'Install Dependencies'],['../md_BUILD.html#autotoc_md60',1,'Install Dependencies'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md240',1,'Key Dependencies'],['../md_BUILD.html#autotoc_md45',1,'Optional Dependencies'],['../index.html#deps_optional',1,'Optional Dependencies'],['../index.html#deps_required',1,'Required Dependencies'],['../md_MIGRATION__GUIDE.html#autotoc_md193',1,'Step 1: Update Dependencies']]],
  ['dependencies_20and_20requirements_35',['Dependencies and Requirements',['../index.html#dependencies_sec',1,'']]],
  ['dependency_20configuration_36',['Dependency Configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md142',1,'']]],
  ['dependency_20management_37',['dependency management',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md423',1,'🔗 Dependency Management'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md273',1,'4. Dependency Management']]],
  ['dependency_20sh_38',['dependency.sh',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md275',1,'']]],
  ['deployment_39',['deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md162',1,'✅ Phase 5: Verification and Deployment'],['../md_MIGRATION__CHECKLIST.html#autotoc_md167',1,'Day 18: Final Verification and Deployment'],['../md_RELEASE__NOTES.html#autotoc_md386',1,'DevOps &amp; Deployment'],['../md_OPERATIONS.html#autotoc_md311',1,'Docker Deployment'],['../md_MIGRATION__CHECKLIST.html#autotoc_md170',1,'Final Deployment'],['../md_OPERATIONS.html#autotoc_md310',1,'Linux Deployment'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md301',1,'Phase 5: Verification and Deployment'],['../md_OPERATIONS.html#autotoc_md309',1,'Platform-Specific Deployment']]],
  ['deployment_202_203_20days_40',['Phase 5: Verification and Deployment (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md262',1,'']]],
  ['deployment_20best_20practices_41',['Deployment Best Practices',['../md_OPERATIONS.html#autotoc_md307',1,'']]],
  ['deployment_20checklist_42',['Pre-deployment Checklist',['../md_OPERATIONS.html#autotoc_md308',1,'']]],
  ['descriptor_20limits_43',['File Descriptor Limits',['../md_TROUBLESHOOTING.html#autotoc_md499',1,'']]],
  ['design_44',['design',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md414',1,'🏗️ Architecture Design'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md420',1,'2. Core API Design'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md416',1,'2. Namespace Design'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md271',1,'3. Integration Interface Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md126',1,'Architecture Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md129',1,'Build System Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md127',1,'Integration Interface Design']]],
  ['design_20and_20planning_45',['Day 2: Design and Planning',['../md_MIGRATION__CHECKLIST.html#autotoc_md125',1,'']]],
  ['detailed_20execution_20checklist_20for_20network_5fsystem_20separation_20from_20messaging_5fsystem_46',['Detailed Execution Checklist for network_system Separation from messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md117',1,'']]],
  ['detailed_20plan_20for_20separating_20network_5fsystem_20from_20messaging_5fsystem_47',['Detailed Plan for Separating network_system from messaging_system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md231',1,'']]],
  ['details_48',['details',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md266',1,'🛠️ Technical Implementation Details'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html',1,'Technical Implementation Details']]],
  ['detection_49',['Detection',['../md_TROUBLESHOOTING.html#autotoc_md477',1,'']]],
  ['development_50',['Testing Strategy Development',['../md_MIGRATION__CHECKLIST.html#autotoc_md130',1,'']]],
  ['development_20guidelines_51',['Development Guidelines',['../index.html#contrib_guidelines',1,'']]],
  ['development_20timeline_52',['Development Timeline',['../md_CHANGELOG.html#autotoc_md109',1,'']]],
  ['devops_20deployment_53',['DevOps &amp; Deployment',['../md_RELEASE__NOTES.html#autotoc_md386',1,'']]],
  ['diagnosis_54',['diagnosis',['../md_TROUBLESHOOTING.html#autotoc_md444',1,'Diagnosis'],['../md_TROUBLESHOOTING.html#autotoc_md468',1,'Diagnosis'],['../md_TROUBLESHOOTING.html#autotoc_md461',1,'Diagnosis'],['../md_TROUBLESHOOTING.html#autotoc_md474',1,'Diagnosis'],['../md_TROUBLESHOOTING.html#autotoc_md448',1,'Diagnosis'],['../md_TROUBLESHOOTING.html#autotoc_md471',1,'Diagnosis'],['../md_TROUBLESHOOTING.html#autotoc_md464',1,'Diagnosis']]],
  ['diagnosis_20steps_55',['Diagnosis Steps',['../md_TROUBLESHOOTING.html#autotoc_md440',1,'']]],
  ['differences_56',['Key API Differences',['../md_MIGRATION__GUIDE.html#autotoc_md206',1,'']]],
  ['directory_20structure_20creation_57',['Directory Structure Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md135',1,'']]],
  ['directory_20structure_20reorganization_58',['1. Directory Structure Reorganization',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md267',1,'']]],
  ['disaster_20recovery_59',['Disaster Recovery',['../md_OPERATIONS.html#autotoc_md330',1,'']]],
  ['dll_20not_20found_60',['DLL Not Found',['../md_TROUBLESHOOTING.html#autotoc_md505',1,'']]],
  ['docker_20deployment_61',['Docker Deployment',['../md_OPERATIONS.html#autotoc_md311',1,'']]],
  ['documentation_62',['documentation',['../md_README.html#autotoc_md375',1,'📚 Documentation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md292',1,'1. API Documentation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md293',1,'2. Architecture Documentation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md294',1,'3. Operations Documentation'],['../md_RELEASE__NOTES.html#autotoc_md387',1,'Documentation'],['../index.html',1,'Network System Documentation']]],
  ['documentation_20plan_63',['📝 Documentation Plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md291',1,'']]],
  ['documentation_20updates_64',['Documentation Updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md169',1,'']]],
  ['drops_65',['Connection Drops',['../md_TROUBLESHOOTING.html#autotoc_md473',1,'']]],
  ['dtrace_20analysis_66',['Strace/DTrace Analysis',['../md_TROUBLESHOOTING.html#autotoc_md458',1,'']]],
  ['dump_67',['Analyze Core Dump',['../md_TROUBLESHOOTING.html#autotoc_md453',1,'']]],
  ['dump_20analysis_68',['Core Dump Analysis',['../md_TROUBLESHOOTING.html#autotoc_md451',1,'']]],
  ['dumps_69',['Enable Core Dumps',['../md_TROUBLESHOOTING.html#autotoc_md452',1,'']]],
  ['during_20migration_70',['Testing During Migration',['../index.html#migration_testing',1,'']]]
];
