var searchData=
[
  ['macos_0',['macos',['../md_BUILD.html#autotoc_md10',1,'macOS'],['../md_README.html#autotoc_md291',1,'macOS']]],
  ['main_20cmakelists_20txt_1',['Main CMakeLists.txt',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md176',1,'']]],
  ['major_20risks_2',['major risks',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md194',1,'1. Major Risks'],['../md_README.html#autotoc_md459',1,'Major Risks']]],
  ['management_3',['management',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md507',1,'🔗 Dependency Management'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md505',1,'3. Session Management'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md179',1,'4. Dependency Management']]],
  ['management_20✅_4',['Dependency Management ✅',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md226',1,'']]],
  ['manual_20installation_5',['Option 2: Manual Installation',['../md_BUILD.html#autotoc_md16',1,'']]],
  ['manual_20integration_6',['Manual Integration',['../md_BUILD.html#autotoc_md30',1,'']]],
  ['medium_7',['2. Sample Applications (Priority: Medium)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md217',1,'']]],
  ['messaging_5fbridge_20class_8',['1. messaging_bridge Class',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md503',1,'']]],
  ['messaging_5fbridge_20h_9',['messaging_bridge.h',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md178',1,'']]],
  ['messaging_5fbridge_20implementation_10',['messaging_bridge Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md95',1,'']]],
  ['messaging_5fsystem_11',['messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md65',1,'Detailed Execution Checklist for network_system Separation from messaging_system'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md137',1,'Detailed Plan for Separating network_system from messaging_system'],['../index.html#migration_from_legacy',1,'From Legacy messaging_system']]],
  ['messaging_5fsystem_20modification_12',['Day 13-14: messaging_system Modification',['../md_MIGRATION__CHECKLIST.html#autotoc_md103',1,'']]],
  ['messaging_5fsystem_20network_20structure_13',['messaging_system/network Structure',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md144',1,'']]],
  ['messaging_5fsystem_20update_14',['messaging_system update',['../md_MIGRATION__CHECKLIST.html#autotoc_md102',1,'🔄 Phase 4: messaging_system Update'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md206',1,'Phase 4: messaging_system Update']]],
  ['messaging_5fsystem_20update_202_203_20days_15',['Phase 4: messaging_system Update (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md165',1,'']]],
  ['metric_20collection_16',['1. Performance Metric Collection',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md516',1,'']]],
  ['migration_17',['Testing During Migration',['../index.html#migration_testing',1,'']]],
  ['migration_20checklist_18',['Network System Migration Checklist',['../md_MIGRATION__CHECKLIST.html',1,'']]],
  ['migration_20guide_19',['Migration Guide',['../index.html#migration_sec',1,'']]],
  ['migration_20with_20bridge_20',['Migration with Bridge',['../index.html#usage_bridge',1,'']]],
  ['mingw_21',['Windows (MSYS2/MinGW)',['../md_BUILD.html#autotoc_md18',1,'']]],
  ['minimal_20build_22',['Minimal Build',['../md_BUILD.html#autotoc_md24',1,'']]],
  ['minimum_20requirements_23',['Minimum Requirements',['../md_BUILD.html#autotoc_md3',1,'']]],
  ['mission_24',['Mission',['../index.html#mission_sec',1,'']]],
  ['mitigation_25',['mitigation',['../md_README.html#autotoc_md458',1,'🚨 Risk Factors and Mitigation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md193',1,'🚨 Risk Factors and Mitigation']]],
  ['modification_26',['Day 13-14: messaging_system Modification',['../md_MIGRATION__CHECKLIST.html#autotoc_md103',1,'']]],
  ['module_20files_27',['1. CMake Module Files',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md508',1,'']]],
  ['module_20layer_20structure_28',['1. Module Layer Structure',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md499',1,'']]],
  ['monitoring_29',['📊 Performance Monitoring',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md515',1,'']]],
  ['monitoring_20implementation_30',['Performance Monitoring Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md96',1,'']]],
  ['msys2_31',['Windows (MSYS2)',['../md_README.html#autotoc_md292',1,'']]],
  ['msys2_20mingw_32',['Windows (MSYS2/MinGW)',['../md_BUILD.html#autotoc_md18',1,'']]]
];
