var searchData=
[
  ['t_0',['Error Handling with Result&lt;T&gt;',['../md_README.html#autotoc_md407',1,'']]],
  ['t_20를_20사용한_20오류_20처리_1',['Result&lt;T&gt;를 사용한 오류 처리',['../md_README__KO.html#autotoc_md492',1,'']]],
  ['t_20pattern_2',['t pattern',['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md183',1,'Result&lt;T&gt; Pattern'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md137',1,'Result&lt;T&gt; Pattern']]],
  ['table_20of_20contents_3',['Table of Contents',['../md_MIGRATION.html#autotoc_md261',1,'']]],
  ['takeaways_4',['Key Takeaways',['../md_MIGRATION.html#autotoc_md356',1,'']]],
  ['target_20coverage_5',['Target Coverage',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md144',1,'']]],
  ['tcp_20client_6',['tcp client',['../md_README.html#autotoc_md406',1,'TCP Client'],['../md_README__KO.html#autotoc_md491',1,'TCP Client']]],
  ['tcp_20comparison_7',['UDP vs TCP Comparison',['../md_UDP__SUPPORT.html#autotoc_md560',1,'']]],
  ['tcp_20server_8',['tcp server',['../md_README.html#autotoc_md405',1,'TCP Server'],['../md_README__KO.html#autotoc_md490',1,'TCP Server']]],
  ['technologies_9',['Core Technologies',['../md_README.html#autotoc_md387',1,'']]],
  ['technology_20stack_20architecture_10',['🛠️ Technology Stack &amp; Architecture',['../md_README.html#autotoc_md386',1,'']]],
  ['test_11',['Step 4.1: Compilation Test',['../md_MIGRATION.html#autotoc_md296',1,'']]],
  ['test_201_3a_20clean_20build_12',['Test 1: Clean Build',['../md_MIGRATION.html#autotoc_md326',1,'']]],
  ['test_202_3a_20multiple_20configurations_13',['Test 2: Multiple Configurations',['../md_MIGRATION.html#autotoc_md327',1,'']]],
  ['test_203_3a_20basic_20connectivity_14',['Test 3: Basic Connectivity',['../md_MIGRATION.html#autotoc_md329',1,'']]],
  ['test_204_3a_20concurrent_20connections_15',['Test 4: Concurrent Connections',['../md_MIGRATION.html#autotoc_md330',1,'']]],
  ['test_205_3a_20throughput_20benchmark_16',['Test 5: Throughput Benchmark',['../md_MIGRATION.html#autotoc_md332',1,'']]],
  ['test_206_3a_20latency_20benchmark_17',['Test 6: Latency Benchmark',['../md_MIGRATION.html#autotoc_md333',1,'']]],
  ['test_207_3a_20existing_20application_20tests_18',['Test 7: Existing Application Tests',['../md_MIGRATION.html#autotoc_md335',1,'']]],
  ['test_208_3a_20end_20to_20end_20scenario_19',['Test 8: End-to-End Scenario',['../md_MIGRATION.html#autotoc_md336',1,'']]],
  ['test_20count_20by_20suite_20',['Test Count by Suite',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md128',1,'']]],
  ['test_20distribution_21',['Test Distribution',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md129',1,'']]],
  ['test_20implementation_204_20files_22',['test implementation 4 files',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md147',1,'Test Implementation (4 files)'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md193',1,'Test Implementation (4 files)']]],
  ['test_20statistics_23',['Test Statistics',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md127',1,'']]],
  ['test_20status_24',['test status',['../md_INTEGRATION__STATUS__KO.html#autotoc_md257',1,'Integration Test Status'],['../md_INTEGRATION__STATUS.html#autotoc_md246',1,'Integration Test Status']]],
  ['test_20suites_25',['생성된 Test Suites',['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md163',1,'']]],
  ['test_20suites_20created_26',['Test Suites Created',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md117',1,'']]],
  ['testing_27',['testing',['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md178',1,'2. Localhost-Only Testing'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md132',1,'2. Localhost-Only Testing']]],
  ['testing_20구현_20요약_28',['Integration Testing 구현 요약',['../md_IMPLEMENTATION__SUMMARY__KO.html',1,'']]],
  ['testing_20during_20migration_29',['Testing During Migration',['../index.html#migration_testing',1,'']]],
  ['testing_20implementation_20summary_30',['Integration Testing Implementation Summary',['../md_IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['testing_20infrastructure_31',['Build &amp; Testing Infrastructure',['../md_README.html#autotoc_md439',1,'']]],
  ['testing_20requirements_32',['testing requirements',['../md_IMPROVEMENTS.html#autotoc_md220',1,'Testing Requirements'],['../index.html#contrib_testing',1,'Testing Requirements']]],
  ['testing_20validation_33',['Testing &amp; Validation',['../md_MIGRATION.html#autotoc_md274',1,'']]],
  ['testing_20your_20migration_34',['Testing Your Migration',['../md_MIGRATION.html#autotoc_md324',1,'']]],
  ['tests와_20보완적_35',['Unit Tests와 보완적',['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md198',1,'']]],
  ['tests_36',['tests',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md118',1,'1. Connection Lifecycle Tests (17 tests)'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md164',1,'1. Connection Lifecycle Tests (17 tests)'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md165',1,'2. Protocol Integration Tests (13 tests)'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md119',1,'2. Protocol Integration Tests (13 tests)'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md120',1,'3. Network Performance Tests (10 tests)'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md166',1,'3. Network Performance Tests (10 tests)'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md121',1,'4. Error Handling Tests (18 tests)'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md167',1,'4. Error Handling Tests (18 tests)'],['../md_MIGRATION.html#autotoc_md325',1,'Compilation Tests'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md152',1,'Complementary to Unit Tests'],['../md_MIGRATION.html#autotoc_md328',1,'Functional Tests'],['../md_MIGRATION.html#autotoc_md334',1,'Integration Tests'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md151',1,'Integration with Existing Tests'],['../md_MIGRATION.html#autotoc_md331',1,'Performance Tests'],['../md_MIGRATION.html#autotoc_md297',1,'Step 4.2: Run Unit Tests'],['../md_MIGRATION.html#autotoc_md335',1,'Test 7: Existing Application Tests']]],
  ['tests_2010_20tests_37',['tests 10 tests',['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md166',1,'3. Network Performance Tests (10 tests)'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md120',1,'3. Network Performance Tests (10 tests)']]],
  ['tests_2013_20tests_38',['tests 13 tests',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md119',1,'2. Protocol Integration Tests (13 tests)'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md165',1,'2. Protocol Integration Tests (13 tests)']]],
  ['tests_2017_20tests_39',['tests 17 tests',['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md164',1,'1. Connection Lifecycle Tests (17 tests)'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md118',1,'1. Connection Lifecycle Tests (17 tests)']]],
  ['tests_2018_20tests_40',['tests 18 tests',['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md167',1,'4. Error Handling Tests (18 tests)'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md121',1,'4. Error Handling Tests (18 tests)']]],
  ['than_20expected_41',['Issue 8: Lower Throughput Than Expected',['../md_MIGRATION.html#autotoc_md318',1,'']]],
  ['these_20measurements_42',['🔬 Reproducing These Measurements',['../md_BASELINE.html#autotoc_md20',1,'']]],
  ['this_20migration_43',['Why This Migration',['../md_MIGRATION.html#autotoc_md265',1,'']]],
  ['thread_20안전성_20및_20동시성_44',['Thread 안전성 및 동시성',['../md_README__KO.html#autotoc_md526',1,'']]],
  ['thread_20safety_45',['Thread Safety',['../md_UDP__SUPPORT.html#autotoc_md565',1,'']]],
  ['thread_20safety_20concurrency_46',['Thread Safety &amp; Concurrency',['../md_README.html#autotoc_md440',1,'']]],
  ['thread_20system_20integration_47',['Thread System Integration',['../md_STRUCTURE.html#autotoc_md551',1,'']]],
  ['thread_5fsystem_48',['thread_system',['../md_INTEGRATION__STATUS.html#autotoc_md240',1,'thread_system'],['../md_INTEGRATION__STATUS__KO.html#autotoc_md251',1,'thread_system']]],
  ['thread_5fsystem_20integration_20failure_49',['Issue 11: thread_system Integration Failure',['../md_MIGRATION.html#autotoc_md322',1,'']]],
  ['throughput_50',['Message Throughput',['../md_BASELINE.html#autotoc_md9',1,'']]],
  ['throughput_20benchmark_51',['Test 5: Throughput Benchmark',['../md_MIGRATION.html#autotoc_md332',1,'']]],
  ['throughput_20benchmarks_52',['Throughput Benchmarks',['../md_CHANGELOG.html#autotoc_md76',1,'']]],
  ['throughput_20metrics_53',['Throughput Metrics',['../md_MIGRATION.html#autotoc_md343',1,'']]],
  ['throughput_20performance_20by_20message_20size_54',['Throughput Performance by Message Size',['../md_README.html#autotoc_md378',1,'']]],
  ['throughput_20than_20expected_55',['Issue 8: Lower Throughput Than Expected',['../md_MIGRATION.html#autotoc_md318',1,'']]],
  ['timeline_56',['Development Timeline',['../md_README.html#autotoc_md437',1,'']]],
  ['timeout_57',['Issue 6: Connection Timeout',['../md_MIGRATION.html#autotoc_md315',1,'']]],
  ['timeout_20strategies_58',['timeout strategies',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md135',1,'5. Timeout Strategies'],['../md_IMPLEMENTATION__SUMMARY__KO.html#autotoc_md181',1,'5. Timeout Strategies']]],
  ['tips_59',['Debugging Tips',['../index.html#trouble_debugging',1,'']]],
  ['tls_20ssl_20지원_20추가_60',['4. TLS/SSL 지원 추가',['../md_IMPROVEMENTS__KO.html#autotoc_md231',1,'']]],
  ['tls_20ssl_20support_61',['4. Add TLS/SSL Support',['../md_IMPROVEMENTS.html#autotoc_md216',1,'']]],
  ['to_20end_20scenario_62',['Test 8: End-to-End Scenario',['../md_MIGRATION.html#autotoc_md336',1,'']]],
  ['to_20network_5fsystem_63',['Migration Guide: messaging_system to network_system',['../md_MIGRATION.html',1,'']]],
  ['to_20network_5fsystem_20functions_64',['Issue 1: Undefined Reference to network_system Functions',['../md_MIGRATION.html#autotoc_md309',1,'']]],
  ['to_20stage_65',['Files to Stage',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md156',1,'']]],
  ['to_20unit_20tests_66',['Complementary to Unit Tests',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md152',1,'']]],
  ['transfer_67',['Zero-Copy Data Transfer',['../md_README.html#autotoc_md408',1,'']]],
  ['troubleshooting_68',['Troubleshooting',['../index.html#troubleshooting_sec',1,'']]],
  ['tt_20include_20network_5fsystem_20internal_20tt_69',['🔒 Internal Components (&lt;tt&gt;include/network_system/internal/&lt;/tt&gt;)',['../md_STRUCTURE.html#autotoc_md541',1,'']]],
  ['tt_20include_20network_5fsystem_20tt_70',['🎯 Public API Layer (&lt;tt&gt;include/network_system/&lt;/tt&gt;)',['../md_STRUCTURE.html#autotoc_md539',1,'']]],
  ['tt_20src_20tt_71',['⚙️ Implementation Layer (&lt;tt&gt;src/&lt;/tt&gt;)',['../md_STRUCTURE.html#autotoc_md540',1,'']]],
  ['txt_72',['Step 2.1: Update CMakeLists.txt',['../md_MIGRATION.html#autotoc_md284',1,'']]]
];
