var searchData=
[
  ['table_20of_20contents_0',['table of contents',['../md_MIGRATION__GUIDE.html#autotoc_md147',1,'Table of Contents'],['../md_BUILD.html#autotoc_md1',1,'Table of Contents']]],
  ['target_20after_20separation_1',['Target (After Separation)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md243',1,'']]],
  ['target_20structure_2',['Target Structure',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md226',1,'']]],
  ['task_20completion_20report_3',['Task Completion Report',['../md_MIGRATION__CHECKLIST.html#autotoc_md142',1,'']]],
  ['tasks_4',['Backup Tasks',['../md_MIGRATION__CHECKLIST.html#autotoc_md81',1,'']]],
  ['technical_20implementation_20details_5',['technical implementation details',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md224',1,'🛠️ Technical Implementation Details'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html',1,'Technical Implementation Details']]],
  ['technical_20implementation_20guide_6',['Network System Separation Technical Implementation Guide',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md298',1,'']]],
  ['template_7',['📝 Completion Report Template',['../md_MIGRATION__CHECKLIST.html#autotoc_md141',1,'']]],
  ['test_8',['test',['../md_MIGRATION__GUIDE.html#autotoc_md171',1,'1. Compile Test'],['../md_MIGRATION__GUIDE.html#autotoc_md172',1,'2. Runtime Test'],['../md_MIGRATION__GUIDE.html#autotoc_md173',1,'3. Performance Test'],['../md_MIGRATION__CHECKLIST.html#autotoc_md101',1,'Initial Build Test']]],
  ['test_20framework_9',['🧪 Test Framework',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md313',1,'']]],
  ['test_20structure_10',['1. Unit Test Structure',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md314',1,'']]],
  ['testing_11',['testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md116',1,'Day 15: Integration Testing'],['../md_MIGRATION__CHECKLIST.html#autotoc_md121',1,'Day 16-17: Full System Testing'],['../md_BUILD.html#autotoc_md42',1,'Testing']]],
  ['testing_20during_20migration_12',['Testing During Migration',['../index.html#migration_testing',1,'']]],
  ['testing_20requirements_13',['Testing Requirements',['../index.html#contrib_testing',1,'']]],
  ['testing_20strategy_14',['testing strategy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md235',1,'🧪 Testing Strategy'],['../md_MIGRATION__CHECKLIST.html#autotoc_md86',1,'Day 3: Build System and Testing Strategy']]],
  ['testing_20strategy_20development_15',['Testing Strategy Development',['../md_MIGRATION__CHECKLIST.html#autotoc_md88',1,'']]],
  ['testing_20your_20migration_16',['Testing Your Migration',['../md_MIGRATION__GUIDE.html#autotoc_md170',1,'']]],
  ['tests_17',['tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md236',1,'1. Unit Tests'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md237',1,'2. Integration Tests'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md315',1,'2. Integration Tests'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md238',1,'3. Performance Tests'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md239',1,'4. Stress Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md123',1,'Integration Tests'],['../md_BUILD.html#autotoc_md43',1,'Run Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md124',1,'Stress Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md122',1,'Unit Tests']]],
  ['thread_5fsystem_20integration_18',['thread_system Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md109',1,'']]],
  ['time_20optimization_20lto_19',['Link-Time Optimization (LTO)',['../md_BUILD.html#autotoc_md41',1,'']]],
  ['timeline_20',['Development Timeline',['../md_CHANGELOG.html#autotoc_md67',1,'']]],
  ['tips_21',['tips',['../index.html#trouble_debugging',1,'Debugging Tips'],['../md_MIGRATION__GUIDE.html#autotoc_md182',1,'Optimization Tips']]],
  ['to_20be_20implemented_22',['To Be Implemented',['../md_CHANGELOG.html#autotoc_md48',1,'']]],
  ['to_20network_5fsystem_23',['to network_system',['../md_CHANGELOG.html#autotoc_md69',1,'From messaging_system to network_system'],['../md_MIGRATION__GUIDE.html',1,'Migration Guide: messaging_system to network_system']]],
  ['tools_24',['2. Benchmark Tools',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md319',1,'']]],
  ['troubleshooting_25',['troubleshooting',['../index.html#troubleshooting_sec',1,'Troubleshooting'],['../md_MIGRATION__GUIDE.html#autotoc_md174',1,'Troubleshooting'],['../md_BUILD.html#autotoc_md31',1,'Troubleshooting']]],
  ['troubleshooting_20guide_26',['🚨 Troubleshooting Guide',['../md_MIGRATION__CHECKLIST.html#autotoc_md136',1,'']]],
  ['tuning_27',['Performance Tuning',['../md_BUILD.html#autotoc_md39',1,'']]],
  ['txt_28',['Main CMakeLists.txt',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md228',1,'']]],
  ['txt_20creation_29',['CMakeLists.txt Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md99',1,'']]],
  ['txt_20update_30',['CMakeLists.txt Update',['../md_MIGRATION__CHECKLIST.html#autotoc_md114',1,'']]]
];
