var searchData=
[
  ['change_20history_0',['📝 Change History',['../md_README.html#autotoc_md219',1,'']]],
  ['changes_1',['Namespace Changes',['../md_MIGRATION__CHECKLIST.html#autotoc_md22',1,'']]],
  ['characteristics_2',['characteristics',['../md_README.html#autotoc_md187',1,'3. Performance Characteristics'],['../index.html#performance_sec',1,'Performance Characteristics']]],
  ['checklist_3',['checklist',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md138',1,'✅ Completion Checklist'],['../md_MIGRATION__CHECKLIST.html#autotoc_md70',1,'Final Checklist'],['../md_MIGRATION__CHECKLIST.html',1,'Network System Migration Checklist']]],
  ['checklist_20for_20network_5fsystem_20separation_20from_20messaging_5fsystem_4',['Detailed Execution Checklist for network_system Separation from messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md1',1,'']]],
  ['ci_20status_5',['Current CI Status',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md160',1,'']]],
  ['class_6',['1. messaging_bridge Class',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md235',1,'']]],
  ['class_20implementation_7',['Day 9-10: Bridge Class Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md30',1,'']]],
  ['classes_201_202_20weeks_8',['Stage 1: Core Classes (1-2 weeks)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md157',1,'']]],
  ['classes_20priority_3a_20high_9',['1. Core Networking Classes (Priority: High)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md152',1,'']]],
  ['client_20usage_10',['Basic Client Usage',['../index.html#usage_client',1,'']]],
  ['cmake_20build_20system_11',['2. CMake Build System',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md111',1,'']]],
  ['cmake_20detection_12',['CMake Detection',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md162',1,'']]],
  ['cmake_20module_20files_13',['1. CMake Module Files',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md240',1,'']]],
  ['cmakelists_20txt_14',['Main CMakeLists.txt',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md112',1,'']]],
  ['cmakelists_20txt_20creation_15',['CMakeLists.txt Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md25',1,'']]],
  ['cmakelists_20txt_20update_16',['CMakeLists.txt Update',['../md_MIGRATION__CHECKLIST.html#autotoc_md40',1,'']]],
  ['code_20compatibility_20verification_17',['Existing Code Compatibility Verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md43',1,'']]],
  ['code_20copy_20and_20reorganization_18',['Code Copy and Reorganization',['../md_MIGRATION__CHECKLIST.html#autotoc_md20',1,'']]],
  ['code_20updates_19',['Code Updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md41',1,'']]],
  ['collection_20',['1. Performance Metric Collection',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md248',1,'']]],
  ['common_20issues_21',['Common Issues',['../index.html#trouble_common',1,'']]],
  ['compatibility_20api_20implementation_22',['Compatibility API Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md36',1,'']]],
  ['compatibility_20issues_23',['Compatibility Issues',['../md_MIGRATION__CHECKLIST.html#autotoc_md65',1,'']]],
  ['compatibility_20layer_24',['3. Compatibility Layer',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md87',1,'']]],
  ['compatibility_20verification_25',['compatibility verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md59',1,'Compatibility Verification'],['../md_MIGRATION__CHECKLIST.html#autotoc_md43',1,'Existing Code Compatibility Verification']]],
  ['complete_20✅_26',['Current Status (Phase 1 Complete ✅)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md148',1,'']]],
  ['completion_27',['v2.0.2 (Planned) - Integration Completion',['../md_README.html#autotoc_md222',1,'']]],
  ['completion_20checklist_28',['✅ Completion Checklist',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md138',1,'']]],
  ['completion_20report_29',['Task Completion Report',['../md_MIGRATION__CHECKLIST.html#autotoc_md68',1,'']]],
  ['completion_20report_20template_30',['📝 Completion Report Template',['../md_MIGRATION__CHECKLIST.html#autotoc_md67',1,'']]],
  ['component_20implementation_31',['🔧 Core Component Implementation',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md234',1,'']]],
  ['components_32',['Core Components',['../md_README.html#autotoc_md184',1,'']]],
  ['components_20built_33',['Core Components Built',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md150',1,'']]],
  ['conditional_34',['Integration Dependencies (Conditional)',['../md_README.html#autotoc_md203',1,'']]],
  ['config_20file_35',['2. pkg-config File',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md241',1,'']]],
  ['configuration_36',['configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md24',1,'Day 8: Basic Build System Configuration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md26',1,'Dependency Configuration']]],
  ['considerations_37',['Security Considerations',['../index.html#feat_security',1,'']]],
  ['contact_20and_20support_38',['contact and support',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md145',1,'📞 Contact and Support'],['../md_README.html#autotoc_md214',1,'📞 Contact and Support'],['../index.html#contact_sec',1,'Contact and Support']]],
  ['container_20system_20integration_20details_39',['Container System Integration Details',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md161',1,'']]],
  ['container_5fsystem_20integration_40',['container_system Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md34',1,'']]],
  ['contributing_41',['Contributing',['../index.html#contributing_sec',1,'']]],
  ['copy_20and_20reorganization_42',['Code Copy and Reorganization',['../md_MIGRATION__CHECKLIST.html#autotoc_md20',1,'']]],
  ['core_20api_43',['1. Core API',['../md_README.html#autotoc_md185',1,'']]],
  ['core_20api_20design_44',['2. Core API Design',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md236',1,'']]],
  ['core_20classes_201_202_20weeks_45',['Stage 1: Core Classes (1-2 weeks)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md157',1,'']]],
  ['core_20component_20implementation_46',['🔧 Core Component Implementation',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md234',1,'']]],
  ['core_20components_47',['Core Components',['../md_README.html#autotoc_md184',1,'']]],
  ['core_20components_20built_48',['Core Components Built',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md150',1,'']]],
  ['core_20dependencies_49',['Core Dependencies',['../md_README.html#autotoc_md202',1,'']]],
  ['core_20layer_50',['Core Layer',['../index.html#arch_core',1,'']]],
  ['core_20networking_20classes_20priority_3a_20high_51',['1. Core Networking Classes (Priority: High)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md152',1,'']]],
  ['core_20objectives_52',['Core Objectives',['../md_README.html#autotoc_md170',1,'']]],
  ['core_20separation_53',['v2.0.1 (Planned) - Core Separation',['../md_README.html#autotoc_md221',1,'']]],
  ['core_20system_20separation_54',['core system separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md17',1,'🔧 Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md140',1,'Phase 2: Core System Separation']]],
  ['core_20system_20separation_204_205_20days_55',['core system separation 4 5 days',['../md_README.html#autotoc_md191',1,'Phase 2: Core System Separation (4-5 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md94',1,'Phase 2: Core System Separation (4-5 days)']]],
  ['creation_56',['creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md25',1,'CMakeLists.txt Creation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md18',1,'Day 4-5: Basic Structure Creation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md19',1,'Directory Structure Creation']]],
  ['criteria_57',['📊 Verification Criteria',['../md_MIGRATION__CHECKLIST.html#autotoc_md56',1,'']]],
  ['current_20ci_20status_58',['Current CI Status',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md160',1,'']]],
  ['current_20state_20analysis_59',['current state analysis',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md79',1,'🏗️ Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md8',1,'Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md6',1,'Day 1: Backup and Current State Analysis']]],
  ['current_20status_20phase_201_20complete_20✅_60',['Current Status (Phase 1 Complete ✅)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md148',1,'']]]
];
