var searchData=
[
  ['scope_0',['Scope',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md144',1,'']]],
  ['security_1',['Security',['../md_CHANGELOG.html#autotoc_md56',1,'']]],
  ['security_20considerations_2',['Security Considerations',['../index.html#feat_security',1,'']]],
  ['separating_20network_5fsystem_20from_20messaging_5fsystem_3',['Detailed Plan for Separating network_system from messaging_system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md140',1,'']]],
  ['separation_4',['separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md84',1,'🔧 Phase 2: Core System Separation'],['../md_CHANGELOG.html#autotoc_md57',1,'2025-09-18 - Initial Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md193',1,'Baseline (Before Separation)'],['../md_README.html#autotoc_md352',1,'Baseline (Pre-Separation)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md207',1,'Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md194',1,'Target (After Separation)'],['../md_README.html#autotoc_md385',1,'Target (Post-Separation)'],['../md_README.html#autotoc_md453',1,'v2.0.1 (Planned) - Core Separation']]],
  ['separation_204_205_20days_5',['Phase 2: Core System Separation (4-5 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md161',1,'']]],
  ['separation_20from_20messaging_5fsystem_6',['Detailed Execution Checklist for network_system Separation from messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md68',1,'']]],
  ['separation_20plan_7',['Network System Separation Plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html',1,'']]],
  ['separation_20strategy_8',['🎯 Separation Strategy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md151',1,'']]],
  ['separation_20structure_9',['Pre-Separation Structure',['../md_README.html#autotoc_md275',1,'']]],
  ['separation_20technical_20implementation_20guide_10',['Network System Separation Technical Implementation Guide',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md470',1,'']]],
  ['server_20usage_11',['Basic Server Usage',['../index.html#usage_server',1,'']]],
  ['session_20layer_12',['Session Layer',['../index.html#arch_session',1,'']]],
  ['session_20management_13',['3. Session Management',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md479',1,'']]],
  ['sh_14',['dependency.sh',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md184',1,'']]],
  ['solutions_15',['Issues and Solutions',['../md_MIGRATION__CHECKLIST.html#autotoc_md136',1,'']]],
  ['specific_20instructions_16',['Platform-Specific Instructions',['../md_BUILD.html#autotoc_md6',1,'']]],
  ['stabilization_17',['v2.1.0 (Planned) - Stabilization',['../md_README.html#autotoc_md455',1,'']]],
  ['stack_18',['🔧 Technology Stack',['../md_README.html#autotoc_md341',1,'']]],
  ['start_19',['🚀 Quick Start',['../md_README.html#autotoc_md262',1,'']]],
  ['started_20',['🎉 Getting Started',['../md_README.html#autotoc_md462',1,'']]],
  ['state_20analysis_21',['state analysis',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md146',1,'🏗️ Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md75',1,'Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md73',1,'Day 1: Backup and Current State Analysis']]],
  ['status_22',['🎯 CI/CD Status',['../md_README.html#autotoc_md299',1,'']]],
  ['strategy_23',['strategy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md151',1,'🎯 Separation Strategy'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md186',1,'🧪 Testing Strategy'],['../md_MIGRATION__CHECKLIST.html#autotoc_md79',1,'Day 3: Build System and Testing Strategy']]],
  ['strategy_20development_24',['Testing Strategy Development',['../md_MIGRATION__CHECKLIST.html#autotoc_md81',1,'']]],
  ['stress_20tests_25',['stress tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md190',1,'4. Stress Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md117',1,'Stress Tests']]],
  ['structure_26',['structure',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md473',1,'1. Module Layer Structure'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md486',1,'1. Unit Test Structure'],['../md_README.html#autotoc_md276',1,'Current Structure'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md148',1,'Existing network_system Structure'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md147',1,'messaging_system/network Structure'],['../md_README.html#autotoc_md275',1,'Pre-Separation Structure'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md177',1,'Target Structure']]],
  ['structure_20creation_27',['structure creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md85',1,'Day 4-5: Basic Structure Creation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md86',1,'Directory Structure Creation']]],
  ['structure_20reorganization_28',['1. Directory Structure Reorganization',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md176',1,'']]],
  ['studio_29',['Windows (Visual Studio)',['../md_BUILD.html#autotoc_md13',1,'']]],
  ['support_30',['support',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md212',1,'📞 Contact and Support'],['../md_README.html#autotoc_md441',1,'📞 Contact and Support'],['../index.html#contact_sec',1,'Contact and Support'],['../md_BUILD.html#autotoc_md45',1,'Support'],['../md_CHANGELOG.html#autotoc_md66',1,'Support']]],
  ['system_31',['system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md178',1,'2. CMake Build System'],['../md_README.html',1,'Network System']]],
  ['system_20and_20testing_20strategy_32',['Day 3: Build System and Testing Strategy',['../md_MIGRATION__CHECKLIST.html#autotoc_md79',1,'']]],
  ['system_20configuration_33',['Day 8: Basic Build System Configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md91',1,'']]],
  ['system_20design_34',['Build System Design',['../md_MIGRATION__CHECKLIST.html#autotoc_md80',1,'']]],
  ['system_20documentation_35',['Network System Documentation',['../index.html',1,'']]],
  ['system_20integration_36',['Day 11-12: External System Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md100',1,'']]],
  ['system_20migration_20checklist_37',['Network System Migration Checklist',['../md_MIGRATION__CHECKLIST.html',1,'']]],
  ['system_20separation_38',['system separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md84',1,'🔧 Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md207',1,'Phase 2: Core System Separation']]],
  ['system_20separation_204_205_20days_39',['Phase 2: Core System Separation (4-5 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md161',1,'']]],
  ['system_20separation_20plan_40',['Network System Separation Plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html',1,'']]],
  ['system_20separation_20technical_20implementation_20guide_41',['Network System Separation Technical Implementation Guide',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md470',1,'']]],
  ['system_20testing_42',['Day 16-17: Full System Testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md114',1,'']]]
];
