var searchData=
[
  ['package_20management_0',['Package Management',['../md_MIGRATION__GUIDE.html#autotoc_md209',1,'']]],
  ['packages_1',['packages',['../md_TROUBLESHOOTING.html#autotoc_md495',1,'Finding Packages'],['../md_MIGRATION__GUIDE.html#autotoc_md211',1,'Using System Packages']]],
  ['packet_20capture_2',['Network Packet Capture',['../md_TROUBLESHOOTING.html#autotoc_md457',1,'']]],
  ['parameters_3',['Linux Kernel Parameters',['../md_OPERATIONS.html#autotoc_md324',1,'']]],
  ['path_20updates_4',['path updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md137',1,'Day 6-7: Namespace and Include Path Updates'],['../md_MIGRATION__CHECKLIST.html#autotoc_md139',1,'Include Path Updates']]],
  ['paths_5',['paths',['../md_TROUBLESHOOTING.html#autotoc_md503',1,'Homebrew Library Paths'],['../md_MIGRATION__GUIDE.html#autotoc_md191',1,'Migration Paths']]],
  ['patterns_6',['Common Memory Leak Patterns',['../md_TROUBLESHOOTING.html#autotoc_md481',1,'']]],
  ['performance_20benchmarks_7',['performance benchmarks',['../md_README.html#autotoc_md360',1,'📊 Performance Benchmarks'],['../md_MIGRATION__CHECKLIST.html#autotoc_md160',1,'Performance Benchmarks']]],
  ['performance_20characteristics_8',['Performance Characteristics',['../index.html#performance_sec',1,'']]],
  ['performance_20considerations_9',['performance considerations',['../md_MIGRATION__GUIDE.html#autotoc_md223',1,'Performance Considerations'],['../md_API__REFERENCE.html#autotoc_md31',1,'Performance Considerations']]],
  ['performance_20degradation_10',['performance degradation',['../md_MIGRATION__GUIDE.html#autotoc_md221',1,'4. Performance Degradation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md180',1,'Performance Degradation']]],
  ['performance_20features_11',['Key Performance Features',['../md_README.html#autotoc_md362',1,'']]],
  ['performance_20metric_20collection_12',['1. Performance Metric Collection',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md432',1,'']]],
  ['performance_20metrics_13',['performance metrics',['../md_RELEASE__NOTES.html#autotoc_md388',1,'📊 Performance Metrics'],['../md_MIGRATION__GUIDE.html#autotoc_md225',1,'Performance Metrics']]],
  ['performance_20metrics_20collection_14',['Performance Metrics Collection',['../md_TROUBLESHOOTING.html#autotoc_md513',1,'']]],
  ['performance_20monitoring_15',['📊 Performance Monitoring',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md431',1,'']]],
  ['performance_20monitoring_20implementation_16',['Performance Monitoring Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md148',1,'']]],
  ['performance_20optimization_17',['Performance Optimization',['../md_MIGRATION__CHECKLIST.html#autotoc_md168',1,'']]],
  ['performance_20optimizations_18',['Performance Optimizations',['../index.html#feat_perf',1,'']]],
  ['performance_20problems_19',['Performance Problems',['../md_TROUBLESHOOTING.html#autotoc_md459',1,'']]],
  ['performance_20requirements_20',['📊 Performance Requirements',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md283',1,'']]],
  ['performance_20results_21',['Performance Results',['../md_CHANGELOG.html#autotoc_md94',1,'']]],
  ['performance_20test_22',['3. Performance Test',['../md_MIGRATION__GUIDE.html#autotoc_md215',1,'']]],
  ['performance_20tests_23',['3. Performance Tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md280',1,'']]],
  ['performance_20tuning_24',['performance tuning',['../md_BUILD.html#autotoc_md80',1,'Performance Tuning'],['../md_OPERATIONS.html#autotoc_md322',1,'Performance Tuning']]],
  ['performance_20verification_25',['Performance Verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md174',1,'']]],
  ['phase_26',['phase',['../md_README.html#autotoc_md369',1,'Current Phase'],['../md_README.html#autotoc_md370',1,'Upcoming Phase']]],
  ['phase_201_20complete_27',['2025-09-19 - Phase 1 Complete',['../md_CHANGELOG.html#autotoc_md101',1,'']]],
  ['phase_201_3a_20preparation_20and_20analysis_28',['phase 1: preparation and analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md121',1,'🎯 Phase 1: Preparation and Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md297',1,'Phase 1: Preparation and Analysis']]],
  ['phase_201_3a_20preparation_20and_20analysis_202_203_20days_29',['Phase 1: Preparation and Analysis (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md248',1,'']]],
  ['phase_202_20complete_30',['2025-09-19 - Phase 2 Complete',['../md_CHANGELOG.html#autotoc_md98',1,'']]],
  ['phase_202_3a_20core_20system_20separation_31',['phase 2: core system separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md133',1,'🔧 Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md298',1,'Phase 2: Core System Separation']]],
  ['phase_202_3a_20core_20system_20separation_204_205_20days_32',['Phase 2: Core System Separation (4-5 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md252',1,'']]],
  ['phase_203_20complete_33',['2025-09-20 - Phase 3 Complete',['../md_CHANGELOG.html#autotoc_md95',1,'']]],
  ['phase_203_3a_20integration_20interface_20implementation_34',['phase 3: integration interface implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md145',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md299',1,'Phase 3: Integration Interface Implementation']]],
  ['phase_203_3a_20integration_20interface_20implementation_203_204_20days_35',['Phase 3: Integration Interface Implementation (3-4 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md256',1,'']]],
  ['phase_204_20in_20progress_36',['2025-09-20 - Phase 4 In Progress',['../md_CHANGELOG.html#autotoc_md91',1,'']]],
  ['phase_204_3a_20messaging_5fsystem_20update_37',['phase 4: messaging_system update',['../md_MIGRATION__CHECKLIST.html#autotoc_md154',1,'🔄 Phase 4: messaging_system Update'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md300',1,'Phase 4: messaging_system Update']]],
  ['phase_204_3a_20messaging_5fsystem_20update_202_203_20days_38',['Phase 4: messaging_system Update (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md259',1,'']]],
  ['phase_205_3a_20verification_20and_20deployment_39',['phase 5: verification and deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md162',1,'✅ Phase 5: Verification and Deployment'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md301',1,'Phase 5: Verification and Deployment']]],
  ['phase_205_3a_20verification_20and_20deployment_202_203_20days_40',['Phase 5: Verification and Deployment (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md262',1,'']]],
  ['phases_41',['phases',['../md_README.html#autotoc_md367',1,'📈 Project Phases'],['../md_README.html#autotoc_md368',1,'Completed Phases']]],
  ['pkg_20config_20file_42',['2. pkg-config File',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md425',1,'']]],
  ['plan_43',['plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md291',1,'📝 Documentation Plan'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md289',1,'2. Rollback Plan'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html',1,'Network System Separation Plan']]],
  ['plan_20for_20separating_20network_5fsystem_20from_20messaging_5fsystem_44',['Detailed Plan for Separating network_system from messaging_system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md231',1,'']]],
  ['planned_20features_45',['Planned Features',['../md_README.html#autotoc_md366',1,'']]],
  ['planned_20maintenance_46',['Planned Maintenance',['../md_OPERATIONS.html#autotoc_md341',1,'']]],
  ['planning_47',['Day 2: Design and Planning',['../md_MIGRATION__CHECKLIST.html#autotoc_md125',1,'']]],
  ['platform_20builds_48',['Cross-Platform Builds',['../md_TROUBLESHOOTING.html#autotoc_md496',1,'']]],
  ['platform_20specific_20deployment_49',['Platform-Specific Deployment',['../md_OPERATIONS.html#autotoc_md309',1,'']]],
  ['platform_20specific_20instructions_50',['Platform-Specific Instructions',['../md_BUILD.html#autotoc_md47',1,'']]],
  ['platform_20specific_20issues_51',['Platform-Specific Issues',['../md_TROUBLESHOOTING.html#autotoc_md497',1,'']]],
  ['platform_20specific_20notes_52',['Platform-Specific Notes',['../md_API__REFERENCE.html#autotoc_md35',1,'']]],
  ['policies_53',['Retention Policies',['../md_OPERATIONS.html#autotoc_md345',1,'']]],
  ['policy_54',['2. Namespace Policy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md244',1,'']]],
  ['pooling_55',['Memory Pooling',['../md_API__REFERENCE.html#autotoc_md33',1,'']]],
  ['practices_56',['practices',['../md_OPERATIONS.html#autotoc_md307',1,'Deployment Best Practices'],['../md_TROUBLESHOOTING.html#autotoc_md512',1,'Logging Best Practices']]],
  ['pre_20deployment_20checklist_57',['Pre-deployment Checklist',['../md_OPERATIONS.html#autotoc_md308',1,'']]],
  ['preparation_20and_20analysis_58',['preparation and analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md121',1,'🎯 Phase 1: Preparation and Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md297',1,'Phase 1: Preparation and Analysis']]],
  ['preparation_20and_20analysis_202_203_20days_59',['Phase 1: Preparation and Analysis (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md248',1,'']]],
  ['prerequisites_60',['prerequisites',['../md_README.html#autotoc_md351',1,'Prerequisites'],['../md_BUILD.html#autotoc_md43',1,'Prerequisites']]],
  ['prevention_61',['Memory Leak Prevention',['../md_TROUBLESHOOTING.html#autotoc_md485',1,'']]],
  ['principles_62',['1. Basic Principles',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md243',1,'']]],
  ['problems_63',['problems',['../md_TROUBLESHOOTING.html#autotoc_md486',1,'Build Problems'],['../md_TROUBLESHOOTING.html#autotoc_md459',1,'Performance Problems']]],
  ['profiling_20and_20benchmarking_64',['Profiling and Benchmarking',['../md_OPERATIONS.html#autotoc_md327',1,'']]],
  ['progress_65',['progress',['../md_MIGRATION__CHECKLIST.html#autotoc_md119',1,'📋 Overall Progress'],['../md_CHANGELOG.html#autotoc_md91',1,'2025-09-20 - Phase 4 In Progress']]],
  ['project_66',['Using NetworkSystem in Your Project',['../md_BUILD.html#autotoc_md69',1,'']]],
  ['project_20overview_67',['project overview',['../md_README.html#autotoc_md348',1,'🎯 Project Overview'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md233',1,'📋 Project Overview']]],
  ['project_20phases_68',['📈 Project Phases',['../md_README.html#autotoc_md367',1,'']]],
  ['prometheus_20integration_69',['Prometheus Integration',['../md_OPERATIONS.html#autotoc_md319',1,'']]],
  ['protocol_20handlers_70',['Protocol Handlers',['../md_API__REFERENCE.html#autotoc_md11',1,'']]],
  ['pthread_20not_20found_20on_20windows_71',['pthread Not Found on Windows',['../md_BUILD.html#autotoc_md75',1,'']]]
];
