var searchData=
[
  ['path_20updates_0',['path updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md85',1,'Day 6-7: Namespace and Include Path Updates'],['../md_MIGRATION__CHECKLIST.html#autotoc_md87',1,'Include Path Updates']]],
  ['performance_20benchmarks_1',['Performance Benchmarks',['../md_MIGRATION__CHECKLIST.html#autotoc_md108',1,'']]],
  ['performance_20characteristics_2',['performance characteristics',['../md_README.html#autotoc_md306',1,'3. Performance Characteristics'],['../index.html#performance_sec',1,'Performance Characteristics']]],
  ['performance_20degradation_3',['Performance Degradation',['../md_MIGRATION__CHECKLIST.html#autotoc_md128',1,'']]],
  ['performance_20metric_20collection_4',['1. Performance Metric Collection',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md516',1,'']]],
  ['performance_20monitoring_5',['📊 Performance Monitoring',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md515',1,'']]],
  ['performance_20monitoring_20implementation_6',['Performance Monitoring Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md96',1,'']]],
  ['performance_20optimization_7',['Performance Optimization',['../md_MIGRATION__CHECKLIST.html#autotoc_md116',1,'']]],
  ['performance_20optimization_20🚀_20planned_8',['Phase 4: Performance &amp; Optimization 🚀 (Planned)',['../md_README.html#autotoc_md317',1,'']]],
  ['performance_20optimizations_9',['Performance Optimizations',['../index.html#feat_perf',1,'']]],
  ['performance_20requirements_10',['performance requirements',['../md_README.html#autotoc_md377',1,'📈 Performance Requirements'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md189',1,'📊 Performance Requirements']]],
  ['performance_20tests_11',['3. Performance Tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md186',1,'']]],
  ['performance_20tuning_12',['Performance Tuning',['../md_BUILD.html#autotoc_md39',1,'']]],
  ['performance_20verification_13',['Performance Verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md122',1,'']]],
  ['phase_14',['v2.0.0 (2025-09-19) - Planning Phase',['../md_README.html#autotoc_md478',1,'']]],
  ['phase_201_20achievements_15',['✅ Phase 1 Achievements',['../md_README.html#autotoc_md281',1,'']]],
  ['phase_201_20completion_20summary_16',['Phase 1 Completion Summary',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md212',1,'']]],
  ['phase_201_3a_20core_20infrastructure_20✅_20completed_17',['Phase 1: Core Infrastructure ✅ (Completed)',['../md_README.html#autotoc_md314',1,'']]],
  ['phase_201_3a_20preparation_20and_20analysis_18',['phase 1: preparation and analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md69',1,'🎯 Phase 1: Preparation and Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md203',1,'Phase 1: Preparation and Analysis']]],
  ['phase_201_3a_20preparation_20and_20analysis_202_203_20days_19',['Phase 1: Preparation and Analysis (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md154',1,'']]],
  ['phase_202_20implementation_20plan_20',['Phase 2 Implementation Plan',['../md_PHASE2__IMPLEMENTATION__PLAN.html',1,'']]],
  ['phase_202_20prerequisites_21',['Phase 2 Prerequisites',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md232',1,'']]],
  ['phase_202_3a_20core_20system_20separation_22',['phase 2: core system separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md81',1,'🔧 Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md204',1,'Phase 2: Core System Separation']]],
  ['phase_202_3a_20core_20system_20separation_204_205_20days_23',['Phase 2: Core System Separation (4-5 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md158',1,'']]],
  ['phase_202_3a_20feature_20implementation_24',['Phase 2: Feature Implementation',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md215',1,'']]],
  ['phase_202_3a_20feature_20implementation_20🔨_20in_20progress_25',['Phase 2: Feature Implementation 🔨 (In Progress)',['../md_README.html#autotoc_md315',1,'']]],
  ['phase_203_3a_20advanced_20features_20📝_20planned_26',['Phase 3: Advanced Features 📝 (Planned)',['../md_README.html#autotoc_md316',1,'']]],
  ['phase_203_3a_20integration_20interface_20implementation_27',['phase 3: integration interface implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md93',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md205',1,'Phase 3: Integration Interface Implementation']]],
  ['phase_203_3a_20integration_20interface_20implementation_203_204_20days_28',['Phase 3: Integration Interface Implementation (3-4 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md162',1,'']]],
  ['phase_204_3a_20messaging_5fsystem_20update_29',['phase 4: messaging_system update',['../md_MIGRATION__CHECKLIST.html#autotoc_md102',1,'🔄 Phase 4: messaging_system Update'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md206',1,'Phase 4: messaging_system Update']]],
  ['phase_204_3a_20messaging_5fsystem_20update_202_203_20days_30',['Phase 4: messaging_system Update (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md165',1,'']]],
  ['phase_204_3a_20performance_20optimization_20🚀_20planned_31',['Phase 4: Performance &amp; Optimization 🚀 (Planned)',['../md_README.html#autotoc_md317',1,'']]],
  ['phase_205_3a_20production_20ready_20🏆_20planned_32',['Phase 5: Production Ready 🏆 (Planned)',['../md_README.html#autotoc_md318',1,'']]],
  ['phase_205_3a_20verification_20and_20deployment_33',['phase 5: verification and deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md110',1,'✅ Phase 5: Verification and Deployment'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md207',1,'Phase 5: Verification and Deployment']]],
  ['phase_205_3a_20verification_20and_20deployment_202_203_20days_34',['Phase 5: Verification and Deployment (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md168',1,'']]],
  ['pipeline_20status_35',['CI/CD Pipeline Status',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md224',1,'']]],
  ['pkg_20config_20file_36',['2. pkg-config File',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md509',1,'']]],
  ['plan_37',['plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md197',1,'📝 Documentation Plan'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md195',1,'2. Rollback Plan'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html',1,'Network System Separation Plan'],['../md_PHASE2__IMPLEMENTATION__PLAN.html',1,'Phase 2 Implementation Plan'],['../md_README.html#autotoc_md460',1,'Rollback Plan']]],
  ['plan_20for_20separating_20network_5fsystem_20from_20messaging_5fsystem_38',['Detailed Plan for Separating network_system from messaging_system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md137',1,'']]],
  ['planned_39',['planned',['../md_README.html#autotoc_md316',1,'Phase 3: Advanced Features 📝 (Planned)'],['../md_README.html#autotoc_md317',1,'Phase 4: Performance &amp; Optimization 🚀 (Planned)'],['../md_README.html#autotoc_md318',1,'Phase 5: Production Ready 🏆 (Planned)']]],
  ['planned_20core_20separation_40',['v2.0.1 (Planned) - Core Separation',['../md_README.html#autotoc_md479',1,'']]],
  ['planned_20integration_20completion_41',['v2.0.2 (Planned) - Integration Completion',['../md_README.html#autotoc_md480',1,'']]],
  ['planned_20stabilization_42',['v2.1.0 (Planned) - Stabilization',['../md_README.html#autotoc_md481',1,'']]],
  ['planning_43',['Day 2: Design and Planning',['../md_MIGRATION__CHECKLIST.html#autotoc_md73',1,'']]],
  ['planning_20phase_44',['v2.0.0 (2025-09-19) - Planning Phase',['../md_README.html#autotoc_md478',1,'']]],
  ['platform_20specific_20instructions_45',['Platform-Specific Instructions',['../md_BUILD.html#autotoc_md6',1,'']]],
  ['platforms_20✅_46',['Build Platforms ✅',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md225',1,'']]],
  ['policy_47',['2. Namespace Policy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md150',1,'']]],
  ['polish_203_205_20days_48',['Stage 3: Documentation and Polish (3-5 days)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md223',1,'']]],
  ['post_20separation_49',['Target (Post-Separation)',['../md_README.html#autotoc_md411',1,'']]],
  ['pre_20separation_50',['Baseline (Pre-Separation)',['../md_README.html#autotoc_md378',1,'']]],
  ['pre_20separation_20structure_51',['Pre-Separation Structure',['../md_README.html#autotoc_md301',1,'']]],
  ['preparation_20and_20analysis_52',['preparation and analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md69',1,'🎯 Phase 1: Preparation and Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md203',1,'Phase 1: Preparation and Analysis']]],
  ['preparation_20and_20analysis_202_203_20days_53',['Phase 1: Preparation and Analysis (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md154',1,'']]],
  ['prerequisites_54',['prerequisites',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md232',1,'Phase 2 Prerequisites'],['../md_README.html#autotoc_md289',1,'Prerequisites'],['../md_BUILD.html#autotoc_md2',1,'Prerequisites']]],
  ['principles_55',['1. Basic Principles',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md149',1,'']]],
  ['priority_3a_20high_56',['priority: high',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md216',1,'1. Core Networking Classes (Priority: High)'],['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md218',1,'3. Test Suite (Priority: High)']]],
  ['priority_3a_20low_57',['4. Advanced Features (Priority: Low)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md219',1,'']]],
  ['priority_3a_20medium_58',['2. Sample Applications (Priority: Medium)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md217',1,'']]],
  ['production_20ready_20🏆_20planned_59',['Phase 5: Production Ready 🏆 (Planned)',['../md_README.html#autotoc_md318',1,'']]],
  ['progress_60',['progress',['../md_MIGRATION__CHECKLIST.html#autotoc_md67',1,'📋 Overall Progress'],['../md_README.html#autotoc_md315',1,'Phase 2: Feature Implementation 🔨 (In Progress)']]],
  ['project_61',['Using NetworkSystem in Your Project',['../md_BUILD.html#autotoc_md28',1,'']]],
  ['project_20overview_62',['project overview',['../md_README.html#autotoc_md244',1,'🎯 Project Overview'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md139',1,'📋 Project Overview']]],
  ['project_20owner_63',['Project Owner',['../md_README.html#autotoc_md468',1,'']]],
  ['pthread_20not_20found_20on_20windows_64',['pthread Not Found on Windows',['../md_BUILD.html#autotoc_md34',1,'']]]
];
