var searchData=
[
  ['a_0',['리소스 관리 (RAII - Grade A)',['../md_README__KO.html#autotoc_md435',1,'']]],
  ['acknowledgments_1',['Acknowledgments',['../md_README.html#autotoc_md343',1,'']]],
  ['adapters_2',['Thread Pool Adapters',['../md_README.html#autotoc_md308',1,'']]],
  ['add_20initialization_20code_3',['Step 3.4: Add Initialization Code',['../md_MIGRATION.html#autotoc_md209',1,'']]],
  ['added_4',['added',['../md_CHANGELOG.html#autotoc_md59',1,'Added'],['../md_CHANGELOG.html#autotoc_md65',1,'Added'],['../md_CHANGELOG.html#autotoc_md69',1,'Added'],['../md_CHANGELOG.html#autotoc_md75',1,'Added'],['../md_CHANGELOG.html#autotoc_md80',1,'Added'],['../md_CHANGELOG.html#autotoc_md85',1,'Added'],['../md_CHANGELOG.html#autotoc_md90',1,'Added'],['../md_CHANGELOG.html#autotoc_md95',1,'Added'],['../md_CHANGELOG.html#autotoc_md103',1,'Added']]],
  ['additional_20resources_5',['📝 Additional Resources',['../md_STRUCTURE.html#autotoc_md468',1,'']]],
  ['advanced_20topics_6',['Advanced Topics',['../md_README.html#autotoc_md312',1,'']]],
  ['advantages_7',['Advantages',['../md_UDP__SUPPORT.html#autotoc_md477',1,'']]],
  ['after_20examples_8',['Before and After Examples',['../md_MIGRATION.html#autotoc_md217',1,'']]],
  ['and_20after_20examples_9',['Before and After Examples',['../md_MIGRATION.html#autotoc_md217',1,'']]],
  ['and_20requirements_10',['Dependencies and Requirements',['../index.html#dependencies_sec',1,'']]],
  ['and_20resources_11',['Support and Resources',['../md_MIGRATION.html#autotoc_md266',1,'']]],
  ['and_20support_12',['Contact and Support',['../index.html#contact_sec',1,'']]],
  ['api_20마이그레이션_20완료_20✅_13',['Phase 3: 오류 처리 (75-80% 완료) - 핵심 API 마이그레이션 완료 ✅',['../md_README__KO.html#autotoc_md445',1,'']]],
  ['api_20마이그레이션_20완료_2075_2080_20완료_14',['오류 처리 (핵심 API 마이그레이션 완료 - 75-80% 완료)',['../md_README__KO.html#autotoc_md436',1,'']]],
  ['api_20문서_15',['📚 API 문서',['../md_README__KO.html#autotoc_md394',1,'']]],
  ['api_20사용법_16',['api 사용법',['../md_README__KO.html#autotoc_md390',1,'TCP API 사용법'],['../md_README__KO.html#autotoc_md391',1,'WebSocket API 사용법']]],
  ['api_20예제_17',['📝 API 예제',['../md_README__KO.html#autotoc_md389',1,'']]],
  ['api_20참조_18',['빠른 API 참조',['../md_README__KO.html#autotoc_md395',1,'']]],
  ['api_20호환성_19',['레거시 API 호환성',['../md_README__KO.html#autotoc_md392',1,'']]],
  ['api_20calls_20if_20using_20modern_20api_20',['Step 3.5: Update API Calls (If Using Modern API)',['../md_MIGRATION.html#autotoc_md210',1,'']]],
  ['api_20layer_20tt_20include_20network_5fsystem_20tt_21',['🎯 Public API Layer (&lt;tt&gt;include/network_system/&lt;/tt&gt;)',['../md_STRUCTURE.html#autotoc_md454',1,'']]],
  ['application_20tests_22',['Test 7: Existing Application Tests',['../md_MIGRATION.html#autotoc_md252',1,'']]],
  ['architecture_23',['Architecture',['../md_UDP__SUPPORT.html#autotoc_md483',1,'']]],
  ['architecture_20overview_24',['architecture overview',['../md_README.html#autotoc_md303',1,'Architecture Overview'],['../index.html#architecture_sec',1,'Architecture Overview']]],
  ['asio_20not_20found_25',['Issue 4: ASIO Not Found',['../md_MIGRATION.html#autotoc_md229',1,'']]],
  ['asynchronous_20model_26',['Asynchronous Model',['../md_README.html#autotoc_md295',1,'']]],
  ['asynchronous_20operations_27',['Asynchronous Operations',['../index.html#feat_async',1,'']]],
  ['audit_20current_20network_20usage_28',['Step 1.2: Audit Current Network Usage',['../md_MIGRATION.html#autotoc_md197',1,'']]],
  ['automated_20baseline_20collection_29',['Automated Baseline Collection',['../md_BASELINE.html#autotoc_md19',1,'']]],
  ['available_20cmake_20options_30',['Available CMake Options',['../md_README.html#autotoc_md328',1,'']]]
];
