var searchData=
[
  ['backup_20current_20setup_0',['Step 1: Backup Current Setup',['../md_STRUCTURE.html#autotoc_md459',1,'']]],
  ['backup_20your_20code_1',['Step 1.1: Backup Your Code',['../md_MIGRATION.html#autotoc_md196',1,'']]],
  ['baseline_20검증_2',['Baseline 검증',['../md_BASELINE__KO.html#autotoc_md40',1,'']]],
  ['baseline_20수집_3',['자동 Baseline 수집',['../md_BASELINE__KO.html#autotoc_md47',1,'']]],
  ['baseline_20collection_4',['Automated Baseline Collection',['../md_BASELINE.html#autotoc_md19',1,'']]],
  ['baseline_20metrics_5',['Network System - Performance Baseline Metrics',['../md_BASELINE.html',1,'']]],
  ['baseline_20validation_6',['Baseline Validation',['../md_BASELINE.html#autotoc_md12',1,'']]],
  ['basic_20client_20usage_7',['Basic Client Usage',['../index.html#usage_client',1,'']]],
  ['basic_20connectivity_8',['Test 3: Basic Connectivity',['../md_MIGRATION.html#autotoc_md246',1,'']]],
  ['basic_20server_20usage_9',['Basic Server Usage',['../index.html#usage_server',1,'']]],
  ['before_20and_20after_20examples_10',['Before and After Examples',['../md_MIGRATION.html#autotoc_md217',1,'']]],
  ['benchmark_11',['benchmark',['../md_MIGRATION.html#autotoc_md249',1,'Test 5: Throughput Benchmark'],['../md_MIGRATION.html#autotoc_md250',1,'Test 6: Latency Benchmark']]],
  ['benchmark_20results_12',['Benchmark Results',['../index.html#perf_benchmarks',1,'']]],
  ['benchmarks_13',['benchmarks',['../md_BASELINE.html#autotoc_md23',1,'Build Benchmarks'],['../md_CHANGELOG.html#autotoc_md114',1,'Latency Benchmarks'],['../md_CHANGELOG.html#autotoc_md112',1,'Performance Benchmarks'],['../md_README.html#autotoc_md301',1,'Reproducing Benchmarks'],['../md_BASELINE.html#autotoc_md24',1,'Run Benchmarks'],['../md_CHANGELOG.html#autotoc_md113',1,'Throughput Benchmarks']]],
  ['benchmarks_20intel_20i7_2012700k_20ubuntu_2022_2004_20gcc_2011_20tt_20o3_20tt_14',['Synthetic Benchmarks (Intel i7-12700K, Ubuntu 22.04, GCC 11, &lt;tt&gt;-O3&lt;/tt&gt;)',['../md_README.html#autotoc_md300',1,'']]],
  ['blockquote_15',['blockquote',['../md_README__KO.html#autotoc_md349',1,'&lt;/blockquote&gt;'],['../md_README.html#autotoc_md279',1,'&lt;/blockquote&gt;']]],
  ['breaking_20changes_16',['Breaking Changes',['../md_CHANGELOG.html#autotoc_md117',1,'']]],
  ['bridge_17',['Migration with Bridge',['../index.html#usage_bridge',1,'']]],
  ['build_18',['build',['../md_README.html#autotoc_md288',1,'Build'],['../md_MIGRATION.html#autotoc_md203',1,'Step 2.3: Configure Network System Build'],['../md_MIGRATION.html#autotoc_md243',1,'Test 1: Clean Build']]],
  ['build_20benchmarks_19',['Build Benchmarks',['../md_BASELINE.html#autotoc_md23',1,'']]],
  ['build_20configuration_20',['build configuration',['../md_UDP__SUPPORT.html#autotoc_md479',1,'Build Configuration'],['../md_MIGRATION.html#autotoc_md200',1,'Phase 2: Update Build Configuration']]],
  ['build_20experimental_21',['C++20 Module Build (Experimental)',['../md_README.html#autotoc_md289',1,'']]],
  ['build_20issues_22',['Build Issues',['../md_MIGRATION.html#autotoc_md225',1,'']]],
  ['build_20options_23',['Build Options',['../md_README.html#autotoc_md325',1,'']]],
  ['build_20requirements_24',['Build Requirements',['../index.html#deps_build',1,'']]],
  ['build_20system_20migration_25',['Build System Migration',['../md_MIGRATION.html#autotoc_md189',1,'']]],
  ['building_20with_20dependencies_26',['Building with Dependencies',['../md_README.html#autotoc_md284',1,'']]],
  ['by_20step_20migration_20guide_27',['Step-by-Step Migration Guide',['../md_MIGRATION.html#autotoc_md194',1,'']]]
];
