var searchData=
[
  ['c_2020_20compiler_20errors_0',['Issue 3: C++20 Compiler Errors',['../md_MIGRATION.html#autotoc_md216',1,'']]],
  ['calls_20if_20using_20modern_20api_1',['Step 3.5: Update API Calls (If Using Modern API)',['../md_MIGRATION.html#autotoc_md198',1,'']]],
  ['cd_20infrastructure_2',['CI/CD Infrastructure',['../md_README.html#autotoc_md300',1,'']]],
  ['changed_3',['changed',['../md_CHANGELOG.html#autotoc_md97',1,'Changed'],['../md_CHANGELOG.html#autotoc_md64',1,'Changed'],['../md_CHANGELOG.html#autotoc_md69',1,'Changed'],['../md_CHANGELOG.html#autotoc_md74',1,'Changed'],['../md_CHANGELOG.html#autotoc_md79',1,'Changed'],['../md_CHANGELOG.html#autotoc_md84',1,'Changed'],['../md_CHANGELOG.html#autotoc_md89',1,'Changed'],['../md_MIGRATION.html#autotoc_md169',1,'What Changed']]],
  ['changelog_20network_20system_4',['Changelog - Network System',['../md_CHANGELOG.html',1,'']]],
  ['changes_5',['Breaking Changes',['../md_CHANGELOG.html#autotoc_md110',1,'']]],
  ['characteristics_6',['characteristics',['../md_STRUCTURE.html#autotoc_md431',1,'📊 Performance Characteristics'],['../index.html#performance_sec',1,'Performance Characteristics'],['../md_UDP__SUPPORT.html#autotoc_md450',1,'UDP Characteristics']]],
  ['checklist_7',['checklist',['../md_BASELINE.html#autotoc_md13',1,'Phase 0 Checklist'],['../md_MIGRATION.html#autotoc_md175',1,'Quick Migration Checklist']]],
  ['choose_20your_20migration_20strategy_8',['Step 3.1: Choose Your Migration Strategy',['../md_MIGRATION.html#autotoc_md194',1,'']]],
  ['ci_20cd_20infrastructure_9',['CI/CD Infrastructure',['../md_README.html#autotoc_md300',1,'']]],
  ['clean_20build_10',['Test 1: Clean Build',['../md_MIGRATION.html#autotoc_md231',1,'']]],
  ['client_11',['client',['../md_UDP__SUPPORT.html#autotoc_md448',1,'3. UDP Client'],['../md_README__KO.html#autotoc_md370',1,'TCP Client'],['../md_README.html#autotoc_md274',1,'Your First Client']]],
  ['client_20usage_12',['client usage',['../index.html#usage_client',1,'Basic Client Usage'],['../md_MIGRATION.html#autotoc_md210',1,'Client Usage']]],
  ['cmake_20configuration_13',['CMake Configuration',['../md_MIGRATION.html#autotoc_md206',1,'']]],
  ['cmakelists_20txt_14',['Step 2.1: Update CMakeLists.txt',['../md_MIGRATION.html#autotoc_md189',1,'']]],
  ['code_15',['code',['../md_MIGRATION.html#autotoc_md193',1,'Phase 3: Update Code'],['../md_MIGRATION.html#autotoc_md256',1,'Sample Code'],['../md_MIGRATION.html#autotoc_md184',1,'Step 1.1: Backup Your Code'],['../md_MIGRATION.html#autotoc_md197',1,'Step 3.4: Add Initialization Code']]],
  ['code_20migration_16',['Code Migration',['../md_MIGRATION.html#autotoc_md178',1,'']]],
  ['collection_17',['Automated Baseline Collection',['../md_BASELINE.html#autotoc_md19',1,'']]],
  ['common_20issues_18',['Common Issues',['../index.html#trouble_common',1,'']]],
  ['common_20migration_20issues_19',['Common Migration Issues',['../md_MIGRATION.html#autotoc_md212',1,'']]],
  ['community_20support_20',['Community Support',['../md_MIGRATION.html#autotoc_md257',1,'']]],
  ['comparison_21',['UDP vs TCP Comparison',['../md_UDP__SUPPORT.html#autotoc_md449',1,'']]],
  ['comparison_20with_20legacy_22',['Comparison with Legacy',['../md_MIGRATION.html#autotoc_md252',1,'']]],
  ['compatibility_20mode_20recommended_20for_20gradual_20migration_23',['Option 1: Compatibility Mode (Recommended for Gradual Migration)',['../md_MIGRATION.html#autotoc_md172',1,'']]],
  ['compilation_20test_24',['Step 4.1: Compilation Test',['../md_MIGRATION.html#autotoc_md201',1,'']]],
  ['compilation_20tests_25',['Compilation Tests',['../md_MIGRATION.html#autotoc_md230',1,'']]],
  ['compiler_20errors_26',['Issue 3: C++20 Compiler Errors',['../md_MIGRATION.html#autotoc_md216',1,'']]],
  ['components_27',['Components',['../md_UDP__SUPPORT.html#autotoc_md445',1,'']]],
  ['components_20overview_28',['🔧 Key Components Overview',['../md_STRUCTURE.html#autotoc_md427',1,'']]],
  ['components_20tt_20include_20network_5fsystem_20internal_20tt_29',['🔒 Internal Components (&lt;tt&gt;include/network_system/internal/&lt;/tt&gt;)',['../md_STRUCTURE.html#autotoc_md430',1,'']]],
  ['conclusion_30',['Conclusion',['../md_MIGRATION.html#autotoc_md260',1,'']]],
  ['concurrency_20metrics_31',['Concurrency Metrics',['../md_MIGRATION.html#autotoc_md250',1,'']]],
  ['concurrent_20connections_32',['Test 4: Concurrent Connections',['../md_MIGRATION.html#autotoc_md235',1,'']]],
  ['configuration_33',['configuration',['../md_UDP__SUPPORT.html#autotoc_md453',1,'Build Configuration'],['../md_MIGRATION.html#autotoc_md206',1,'CMake Configuration'],['../md_MIGRATION.html#autotoc_md188',1,'Phase 2: Update Build Configuration']]],
  ['configuration_20optional_34',['Step 2.2: Update Package Configuration (Optional)',['../md_MIGRATION.html#autotoc_md190',1,'']]],
  ['configuration_20primary_35',['Reference Hardware Configuration (Primary)',['../md_BASELINE.html#autotoc_md5',1,'']]],
  ['configuration_20secondary_36',['Development Hardware Configuration (Secondary)',['../md_BASELINE.html#autotoc_md6',1,'']]],
  ['configurations_37',['Test 2: Multiple Configurations',['../md_MIGRATION.html#autotoc_md232',1,'']]],
  ['configure_20network_20system_20build_38',['Step 2.3: Configure Network System Build',['../md_MIGRATION.html#autotoc_md191',1,'']]],
  ['connection_20timeout_39',['Issue 6: Connection Timeout',['../md_MIGRATION.html#autotoc_md220',1,'']]],
  ['connections_40',['Test 4: Concurrent Connections',['../md_MIGRATION.html#autotoc_md235',1,'']]],
  ['connectivity_41',['Test 3: Basic Connectivity',['../md_MIGRATION.html#autotoc_md234',1,'']]],
  ['considerations_42',['considerations',['../md_UDP__SUPPORT.html#autotoc_md452',1,'Considerations'],['../index.html#feat_security',1,'Security Considerations']]],
  ['contact_20and_20support_43',['Contact and Support',['../index.html#contact_sec',1,'']]],
  ['contact_20support_44',['Contact &amp; Support',['../md_README.html#autotoc_md320',1,'']]],
  ['container_20integration_45',['Container Integration',['../md_STRUCTURE.html#autotoc_md441',1,'']]],
  ['container_5fsystem_20integration_20failure_46',['Issue 10: container_system Integration Failure',['../md_MIGRATION.html#autotoc_md226',1,'']]],
  ['contents_47',['Table of Contents',['../md_MIGRATION.html#autotoc_md166',1,'']]],
  ['contributing_48',['contributing',['../index.html#contributing_sec',1,'Contributing'],['../md_README.html#autotoc_md316',1,'Contributing']]],
  ['copy_20데이터_20전송_49',['Zero-Copy 데이터 전송',['../md_README__KO.html#autotoc_md372',1,'']]],
  ['core_20dependencies_50',['Core Dependencies',['../md_README.html#autotoc_md323',1,'']]],
  ['core_20features_51',['Core Features',['../md_README.html#autotoc_md276',1,'']]],
  ['core_20layer_52',['Core Layer',['../index.html#arch_core',1,'']]],
  ['core_20namespaces_53',['Core Namespaces',['../md_STRUCTURE.html#autotoc_md425',1,'']]],
  ['creation_54',['Server Creation',['../md_MIGRATION.html#autotoc_md209',1,'']]],
  ['current_20findings_55',['Current Findings',['../md_BASELINE.html#autotoc_md10',1,'']]],
  ['current_20focus_56',['Current Focus',['../md_README.html#autotoc_md313',1,'']]],
  ['current_20network_20usage_57',['Step 1.2: Audit Current Network Usage',['../md_MIGRATION.html#autotoc_md185',1,'']]],
  ['current_20setup_58',['Step 1: Backup Current Setup',['../md_STRUCTURE.html#autotoc_md433',1,'']]]
];
