var searchData=
[
  ['implementation_0',['implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md93',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md476',1,'🔧 Core Component Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md100',1,'Compatibility API Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md94',1,'Day 9-10: Bridge Class Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md95',1,'messaging_bridge Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md96',1,'Performance Monitoring Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md205',1,'Phase 3: Integration Interface Implementation']]],
  ['implementation_20🔨_20in_20progress_1',['Phase 2: Feature Implementation 🔨 (In Progress)',['../md_README.html#autotoc_md289',1,'']]],
  ['implementation_203_204_20days_2',['Phase 3: Integration Interface Implementation (3-4 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md162',1,'']]],
  ['implementation_20details_3',['implementation details',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md172',1,'🛠️ Technical Implementation Details'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html',1,'Technical Implementation Details']]],
  ['implementation_20guide_4',['Network System Separation Technical Implementation Guide',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md470',1,'']]],
  ['implementation_20roadmap_5',['📅 Implementation Roadmap',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md153',1,'']]],
  ['implemented_6',['To Be Implemented',['../md_CHANGELOG.html#autotoc_md48',1,'']]],
  ['in_20progress_7',['Phase 2: Feature Implementation 🔨 (In Progress)',['../md_README.html#autotoc_md289',1,'']]],
  ['in_20your_20project_8',['Using NetworkSystem in Your Project',['../md_BUILD.html#autotoc_md28',1,'']]],
  ['include_20path_20updates_9',['include path updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md85',1,'Day 6-7: Namespace and Include Path Updates'],['../md_MIGRATION__CHECKLIST.html#autotoc_md87',1,'Include Path Updates']]],
  ['infrastructure_20✅_20completed_10',['Phase 1: Core Infrastructure ✅ (Completed)',['../md_README.html#autotoc_md288',1,'']]],
  ['initial_20build_20test_11',['Initial Build Test',['../md_MIGRATION__CHECKLIST.html#autotoc_md91',1,'']]],
  ['initial_20separation_12',['2025-09-18 - Initial Separation',['../md_CHANGELOG.html#autotoc_md54',1,'']]],
  ['inquiries_13',['Inquiries',['../md_README.html#autotoc_md443',1,'']]],
  ['install_20dependencies_14',['install dependencies',['../md_BUILD.html#autotoc_md8',1,'Install Dependencies'],['../md_BUILD.html#autotoc_md19',1,'Install Dependencies'],['../md_BUILD.html#autotoc_md14',1,'Install Dependencies'],['../md_BUILD.html#autotoc_md11',1,'Install Dependencies']]],
  ['installation_15',['Option 2: Manual Installation',['../md_BUILD.html#autotoc_md16',1,'']]],
  ['instructions_16',['instructions',['../md_README.html#autotoc_md267',1,'Build Instructions'],['../md_BUILD.html',1,'Build Instructions'],['../md_BUILD.html#autotoc_md6',1,'Platform-Specific Instructions']]],
  ['integration_17',['integration',['../md_CHANGELOG.html#autotoc_md61',1,'CMake Integration'],['../md_BUILD.html#autotoc_md29',1,'CMake Integration'],['../md_CHANGELOG.html#autotoc_md62',1,'Container Integration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md98',1,'container_system Integration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md97',1,'Day 11-12: External System Integration'],['../md_BUILD.html#autotoc_md27',1,'Integration'],['../md_BUILD.html#autotoc_md30',1,'Manual Integration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md99',1,'thread_system Integration']]],
  ['integration_20completion_18',['v2.0.2 (Planned) - Integration Completion',['../md_README.html#autotoc_md454',1,'']]],
  ['integration_20dependencies_20conditional_19',['Integration Dependencies (Conditional)',['../md_README.html#autotoc_md343',1,'']]],
  ['integration_20interface_20design_20',['integration interface design',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md177',1,'3. Integration Interface Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md75',1,'Integration Interface Design']]],
  ['integration_20interface_20implementation_21',['integration interface implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md93',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md205',1,'Phase 3: Integration Interface Implementation']]],
  ['integration_20interface_20implementation_203_204_20days_22',['Phase 3: Integration Interface Implementation (3-4 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md162',1,'']]],
  ['integration_20layer_23',['integration layer',['../md_README.html#autotoc_md279',1,'2. Integration Layer'],['../index.html#arch_integration',1,'Integration Layer']]],
  ['integration_20testing_24',['Day 15: Integration Testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md106',1,'']]],
  ['integration_20tests_25',['integration tests',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md487',1,'2. Integration Tests'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md185',1,'2. Integration Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md113',1,'Integration Tests']]],
  ['interface_20design_26',['interface design',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md177',1,'3. Integration Interface Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md75',1,'Integration Interface Design']]],
  ['interface_20implementation_27',['interface implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md93',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md205',1,'Phase 3: Integration Interface Implementation']]],
  ['interface_20implementation_203_204_20days_28',['Phase 3: Integration Interface Implementation (3-4 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md162',1,'']]],
  ['internal_20layer_29',['Internal Layer',['../index.html#arch_internal',1,'']]],
  ['introduction_30',['Introduction',['../index.html#intro_sec',1,'']]],
  ['issues_31',['issues',['../index.html#trouble_common',1,'Common Issues'],['../md_BUILD.html#autotoc_md32',1,'Common Issues'],['../md_MIGRATION__CHECKLIST.html#autotoc_md129',1,'Compatibility Issues'],['../md_BUILD.html#autotoc_md37',1,'Debug Build Issues']]],
  ['issues_20and_20solutions_32',['Issues and Solutions',['../md_MIGRATION__CHECKLIST.html#autotoc_md133',1,'']]]
];
