var searchData=
[
  ['macos_0',['macOS',['../md_README__KO.html#autotoc_md367',1,'']]],
  ['matrix_1',['Version Support Matrix',['../md_CHANGELOG.html#autotoc_md105',1,'']]],
  ['measurements_2',['🔬 Reproducing These Measurements',['../md_BASELINE.html#autotoc_md22',1,'']]],
  ['memory_20leak_20warnings_3',['Issue 7: Memory Leak Warnings',['../md_MIGRATION.html#autotoc_md228',1,'']]],
  ['memory_20safety_4',['Thread Safety &amp; Memory Safety',['../md_README.html#autotoc_md309',1,'']]],
  ['messaging_5fsystem으로부터_20분리_20이전_5',['[0.9.0] - 2025-09-15 (messaging_system으로부터 분리 이전)',['../md_CHANGELOG__KO.html#autotoc_md153',1,'']]],
  ['messaging_5fsystem_6',['messaging_system',['../md_CHANGELOG.html#autotoc_md99',1,'[0.9.0] - 2025-09-15 (Pre-separation from messaging_system)'],['../index.html#migration_from_legacy',1,'From Legacy messaging_system']]],
  ['messaging_5fsystem_20to_20network_5fsystem_7',['Migration Guide: messaging_system to network_system',['../md_MIGRATION.html',1,'']]],
  ['methodology_8',['Methodology',['../md_BASELINE.html#autotoc_md17',1,'']]],
  ['metrics_9',['metrics',['../md_MIGRATION.html#autotoc_md257',1,'Concurrency Metrics'],['../md_MIGRATION.html#autotoc_md256',1,'Latency Metrics'],['../md_BASELINE.html',1,'Network System - Performance Baseline Metrics'],['../md_BASELINE.html#autotoc_md15',1,'Real Network Performance Metrics'],['../md_MIGRATION.html#autotoc_md255',1,'Throughput Metrics']]],
  ['metrics_20intel_20i7_2012700k_20ubuntu_2022_2004_20gcc_2011_20tt_20o3_20tt_10',['Performance Metrics (Intel i7-12700K, Ubuntu 22.04, GCC 11 &lt;tt&gt;-O3&lt;/tt&gt;)',['../md_BASELINE.html#autotoc_md8',1,'']]],
  ['metrics_20placeholder_11',['Expected Metrics (Placeholder)',['../md_BASELINE.html#autotoc_md20',1,'']]],
  ['migration_12',['migration',['../md_MIGRATION.html#autotoc_md184',1,'Build System Migration'],['../md_MIGRATION.html#autotoc_md185',1,'Code Migration'],['../md_MIGRATION.html#autotoc_md179',1,'Option 1: Compatibility Mode (Recommended for Gradual Migration)'],['../md_MIGRATION.html#autotoc_md207',1,'Phase 4: Verify Migration'],['../md_MIGRATION.html#autotoc_md183',1,'Pre-Migration'],['../index.html#migration_testing',1,'Testing During Migration'],['../md_MIGRATION.html#autotoc_md236',1,'Testing Your Migration'],['../md_MIGRATION.html#autotoc_md177',1,'Why This Migration']]],
  ['migration_20checklist_13',['Quick Migration Checklist',['../md_MIGRATION.html#autotoc_md182',1,'']]],
  ['migration_20guide_14',['migration guide',['../md_STRUCTURE.html#autotoc_md440',1,'🔄 Migration Guide'],['../index.html#migration_sec',1,'Migration Guide'],['../md_CHANGELOG.html#autotoc_md107',1,'Migration Guide'],['../md_MIGRATION.html#autotoc_md189',1,'Step-by-Step Migration Guide']]],
  ['migration_20guide_3a_20messaging_5fsystem_20to_20network_5fsystem_15',['Migration Guide: messaging_system to network_system',['../md_MIGRATION.html',1,'']]],
  ['migration_20issues_16',['Common Migration Issues',['../md_MIGRATION.html#autotoc_md219',1,'']]],
  ['migration_20paths_17',['Migration Paths',['../md_MIGRATION.html#autotoc_md178',1,'']]],
  ['migration_20recommended_20for_20new_20projects_18',['Option 2: Full Migration (Recommended for New Projects)',['../md_MIGRATION.html#autotoc_md180',1,'']]],
  ['migration_20scripts_19',['Step 4: Run Migration Scripts',['../md_STRUCTURE.html#autotoc_md444',1,'']]],
  ['migration_20strategy_20',['Step 3.1: Choose Your Migration Strategy',['../md_MIGRATION.html#autotoc_md201',1,'']]],
  ['migration_20with_20bridge_21',['Migration with Bridge',['../index.html#usage_bridge',1,'']]],
  ['mission_22',['Mission',['../index.html#mission_sec',1,'']]],
  ['mode_20recommended_20for_20gradual_20migration_23',['Option 1: Compatibility Mode (Recommended for Gradual Migration)',['../md_MIGRATION.html#autotoc_md179',1,'']]],
  ['model_24',['Asynchronous Model',['../md_README.html#autotoc_md285',1,'']]],
  ['modern_20api_25',['Step 3.5: Update API Calls (If Using Modern API)',['../md_MIGRATION.html#autotoc_md205',1,'']]],
  ['msys2_26',['Windows (MSYS2)',['../md_README__KO.html#autotoc_md368',1,'']]],
  ['multiple_20configurations_27',['Test 2: Multiple Configurations',['../md_MIGRATION.html#autotoc_md239',1,'']]]
];
