var searchData=
[
  ['path_20updates_0',['path updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md21',1,'Day 6-7: Namespace and Include Path Updates'],['../md_MIGRATION__CHECKLIST.html#autotoc_md23',1,'Include Path Updates']]],
  ['performance_20benchmarks_1',['Performance Benchmarks',['../md_MIGRATION__CHECKLIST.html#autotoc_md44',1,'']]],
  ['performance_20characteristics_2',['performance characteristics',['../md_README.html#autotoc_md187',1,'3. Performance Characteristics'],['../index.html#performance_sec',1,'Performance Characteristics']]],
  ['performance_20degradation_3',['Performance Degradation',['../md_MIGRATION__CHECKLIST.html#autotoc_md64',1,'']]],
  ['performance_20metric_20collection_4',['1. Performance Metric Collection',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md248',1,'']]],
  ['performance_20monitoring_5',['📊 Performance Monitoring',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md247',1,'']]],
  ['performance_20monitoring_20implementation_6',['Performance Monitoring Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md32',1,'']]],
  ['performance_20network_20system_20separated_20from_20messaging_5fsystem_7',['Independent High-Performance Network System Separated from messaging_system',['../md_README.html#autotoc_md167',1,'']]],
  ['performance_20optimization_8',['Performance Optimization',['../md_MIGRATION__CHECKLIST.html#autotoc_md52',1,'']]],
  ['performance_20optimizations_9',['Performance Optimizations',['../index.html#feat_perf',1,'']]],
  ['performance_20requirements_10',['performance requirements',['../md_README.html#autotoc_md206',1,'📈 Performance Requirements'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md125',1,'📊 Performance Requirements']]],
  ['performance_20tests_11',['performance tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md122',1,'3. Performance Tests'],['../md_README.html#autotoc_md199',1,'Performance Tests']]],
  ['performance_20verification_12',['Performance Verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md58',1,'']]],
  ['phase_13',['v2.0.0 (2025-09-19) - Planning Phase',['../md_README.html#autotoc_md220',1,'']]],
  ['phase_201_20complete_20✅_14',['Current Status (Phase 1 Complete ✅)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md148',1,'']]],
  ['phase_201_3a_20preparation_20and_20analysis_15',['phase 1: preparation and analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md5',1,'🎯 Phase 1: Preparation and Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md139',1,'Phase 1: Preparation and Analysis']]],
  ['phase_201_3a_20preparation_20and_20analysis_202_203_20days_16',['phase 1: preparation and analysis 2 3 days',['../md_README.html#autotoc_md190',1,'Phase 1: Preparation and Analysis (2-3 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md90',1,'Phase 1: Preparation and Analysis (2-3 days)']]],
  ['phase_202_20implementation_20plan_17',['Phase 2 Implementation Plan',['../md_PHASE2__IMPLEMENTATION__PLAN.html',1,'']]],
  ['phase_202_3a_20core_20system_20separation_18',['phase 2: core system separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md17',1,'🔧 Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md140',1,'Phase 2: Core System Separation']]],
  ['phase_202_3a_20core_20system_20separation_204_205_20days_19',['phase 2: core system separation 4 5 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md94',1,'Phase 2: Core System Separation (4-5 days)'],['../md_README.html#autotoc_md191',1,'Phase 2: Core System Separation (4-5 days)']]],
  ['phase_202_3a_20feature_20implementation_20',['Phase 2: Feature Implementation',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md151',1,'']]],
  ['phase_203_3a_20integration_20interface_20implementation_21',['phase 3: integration interface implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md29',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md141',1,'Phase 3: Integration Interface Implementation']]],
  ['phase_203_3a_20integration_20interface_20implementation_203_204_20days_22',['phase 3: integration interface implementation 3 4 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md98',1,'Phase 3: Integration Interface Implementation (3-4 days)'],['../md_README.html#autotoc_md192',1,'Phase 3: Integration Interface Implementation (3-4 days)']]],
  ['phase_204_3a_20messaging_5fsystem_20update_23',['phase 4: messaging_system update',['../md_MIGRATION__CHECKLIST.html#autotoc_md38',1,'🔄 Phase 4: messaging_system Update'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md142',1,'Phase 4: messaging_system Update']]],
  ['phase_204_3a_20messaging_5fsystem_20update_202_203_20days_24',['phase 4: messaging_system update 2 3 days',['../md_README.html#autotoc_md193',1,'Phase 4: messaging_system Update (2-3 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md101',1,'Phase 4: messaging_system Update (2-3 days)']]],
  ['phase_205_3a_20verification_20and_20deployment_25',['phase 5: verification and deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md46',1,'✅ Phase 5: Verification and Deployment'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md143',1,'Phase 5: Verification and Deployment']]],
  ['phase_205_3a_20verification_20and_20deployment_202_203_20days_26',['phase 5: verification and deployment 2 3 days',['../md_README.html#autotoc_md194',1,'Phase 5: Verification and Deployment (2-3 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md104',1,'Phase 5: Verification and Deployment (2-3 days)']]],
  ['pkg_20config_20file_27',['2. pkg-config File',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md241',1,'']]],
  ['plan_28',['plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md133',1,'📝 Documentation Plan'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md131',1,'2. Rollback Plan'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html',1,'Network System Separation Plan'],['../md_PHASE2__IMPLEMENTATION__PLAN.html',1,'Phase 2 Implementation Plan'],['../md_README.html#autotoc_md212',1,'Rollback Plan']]],
  ['plan_20for_20separating_20network_5fsystem_20from_20messaging_5fsystem_29',['Detailed Plan for Separating network_system from messaging_system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md73',1,'']]],
  ['planned_20core_20separation_30',['v2.0.1 (Planned) - Core Separation',['../md_README.html#autotoc_md221',1,'']]],
  ['planned_20integration_20completion_31',['v2.0.2 (Planned) - Integration Completion',['../md_README.html#autotoc_md222',1,'']]],
  ['planned_20stabilization_32',['v2.1.0 (Planned) - Stabilization',['../md_README.html#autotoc_md223',1,'']]],
  ['planning_33',['Day 2: Design and Planning',['../md_MIGRATION__CHECKLIST.html#autotoc_md9',1,'']]],
  ['planning_20and_20design_20documents_34',['📋 Planning and Design Documents',['../md_README.html#autotoc_md173',1,'']]],
  ['planning_20phase_35',['v2.0.0 (2025-09-19) - Planning Phase',['../md_README.html#autotoc_md220',1,'']]],
  ['policy_36',['2. Namespace Policy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md86',1,'']]],
  ['polish_203_205_20days_37',['Stage 3: Documentation and Polish (3-5 days)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md159',1,'']]],
  ['post_20separation_38',['Target (Post-Separation)',['../md_README.html#autotoc_md208',1,'']]],
  ['post_20separation_20structure_39',['Post-Separation Structure',['../md_README.html#autotoc_md183',1,'']]],
  ['pre_20separation_40',['Baseline (Pre-Separation)',['../md_README.html#autotoc_md207',1,'']]],
  ['pre_20separation_20structure_41',['Pre-Separation Structure',['../md_README.html#autotoc_md182',1,'']]],
  ['preparation_20and_20analysis_42',['preparation and analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md5',1,'🎯 Phase 1: Preparation and Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md139',1,'Phase 1: Preparation and Analysis']]],
  ['preparation_20and_20analysis_202_203_20days_43',['preparation and analysis 2 3 days',['../md_README.html#autotoc_md190',1,'Phase 1: Preparation and Analysis (2-3 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md90',1,'Phase 1: Preparation and Analysis (2-3 days)']]],
  ['prerequisites_44',['1. Prerequisites',['../md_README.html#autotoc_md177',1,'']]],
  ['principles_45',['1. Basic Principles',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md85',1,'']]],
  ['priority_3a_20high_46',['priority: high',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md152',1,'1. Core Networking Classes (Priority: High)'],['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md154',1,'3. Test Suite (Priority: High)']]],
  ['priority_3a_20low_47',['4. Advanced Features (Priority: Low)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md155',1,'']]],
  ['priority_3a_20medium_48',['2. Sample Applications (Priority: Medium)',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md153',1,'']]],
  ['progress_49',['📋 Overall Progress',['../md_MIGRATION__CHECKLIST.html#autotoc_md3',1,'']]],
  ['project_50',['Network System Migration Project',['../md_README.html',1,'']]],
  ['project_20overview_51',['project overview',['../md_README.html#autotoc_md169',1,'🎯 Project Overview'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md75',1,'📋 Project Overview']]],
  ['project_20owner_52',['Project Owner',['../md_README.html#autotoc_md215',1,'']]]
];
