var searchData=
[
  ['cases_0',['Real-World Impact &amp; Use Cases',['../md_README.html#autotoc_md14',1,'']]],
  ['characteristics_1',['Performance Characteristics',['../index.html#performance_sec',1,'']]],
  ['client_2',['TCP Client',['../md_README.html#autotoc_md41',1,'']]],
  ['client_20usage_3',['Basic Client Usage',['../index.html#usage_client',1,'']]],
  ['common_20issues_4',['Common Issues',['../index.html#trouble_common',1,'']]],
  ['community_20contributions_5',['Community &amp; Contributions',['../md_README.html#autotoc_md70',1,'']]],
  ['comparison_20with_20industry_20standards_6',['Performance Comparison with Industry Standards',['../md_README.html#autotoc_md18',1,'']]],
  ['compatibility_7',['Legacy API Compatibility',['../md_README.html#autotoc_md36',1,'']]],
  ['compatibility_20strong_8',['🌐 &lt;strong&gt;Cross-Platform Compatibility&lt;/strong&gt;',['../md_README.html#autotoc_md12',1,'']]],
  ['compatibility_20strong_20✅_9',['&lt;strong&gt;Backward Compatibility&lt;/strong&gt; ✅',['../md_README.html#autotoc_md55',1,'']]],
  ['complete_20independence_20strong_20✅_10',['&lt;strong&gt;Complete Independence&lt;/strong&gt; ✅',['../md_README.html#autotoc_md54',1,'']]],
  ['considerations_11',['Security Considerations',['../index.html#feat_security',1,'']]],
  ['contact_20and_20support_12',['Contact and Support',['../index.html#contact_sec',1,'']]],
  ['contact_20support_13',['📧 Contact &amp; Support',['../md_README.html#autotoc_md73',1,'']]],
  ['context_14',['Historical Context',['../md_README.html#autotoc_md3',1,'']]],
  ['contributing_15',['contributing',['../md_README.html#autotoc_md65',1,'🤝 Contributing'],['../index.html#contributing_sec',1,'Contributing']]],
  ['contributions_16',['Community &amp; Contributions',['../md_README.html#autotoc_md70',1,'']]],
  ['core_20advantages_20benefits_17',['Core Advantages &amp; Benefits',['../md_README.html#autotoc_md8',1,'']]],
  ['core_20dependencies_18',['Core Dependencies',['../md_README.html#autotoc_md68',1,'']]],
  ['core_20features_19',['Core Features',['../md_README.html#autotoc_md49',1,'']]],
  ['core_20layer_20',['Core Layer',['../index.html#arch_core',1,'']]],
  ['core_20objectives_21',['Core Objectives',['../md_README.html#autotoc_md20',1,'']]],
  ['core_20performance_20metrics_20latest_20benchmarks_22',['Core Performance Metrics (Latest Benchmarks)',['../md_README.html#autotoc_md17',1,'']]],
  ['core_20technologies_23',['Core Technologies',['../md_README.html#autotoc_md22',1,'']]],
  ['cross_20platform_20compatibility_20strong_24',['🌐 &lt;strong&gt;Cross-Platform Compatibility&lt;/strong&gt;',['../md_README.html#autotoc_md12',1,'']]]
];
