var searchData=
[
  ['day_201_0',['Day 1',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md207',1,'']]],
  ['day_2011_2012_1',['Day 11-12',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md216',1,'']]],
  ['day_2011_2012_3a_20external_20system_20integration_2',['Day 11-12: External System Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md107',1,'']]],
  ['day_2013_2014_3',['Day 13-14',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md218',1,'']]],
  ['day_2013_2014_3a_20messaging_5fsystem_20modification_4',['Day 13-14: messaging_system Modification',['../md_MIGRATION__CHECKLIST.html#autotoc_md113',1,'']]],
  ['day_2015_5',['Day 15',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md219',1,'']]],
  ['day_2015_3a_20integration_20testing_6',['Day 15: Integration Testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md116',1,'']]],
  ['day_2016_2017_7',['Day 16-17',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md221',1,'']]],
  ['day_2016_2017_3a_20full_20system_20testing_8',['Day 16-17: Full System Testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md121',1,'']]],
  ['day_2018_9',['Day 18',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md222',1,'']]],
  ['day_2018_3a_20final_20verification_20and_20deployment_10',['Day 18: Final Verification and Deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md125',1,'']]],
  ['day_201_3a_20backup_20and_20current_20state_20analysis_11',['Day 1: Backup and Current State Analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md80',1,'']]],
  ['day_202_12',['Day 2',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md208',1,'']]],
  ['day_202_3a_20design_20and_20planning_13',['Day 2: Design and Planning',['../md_MIGRATION__CHECKLIST.html#autotoc_md83',1,'']]],
  ['day_203_14',['Day 3',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md209',1,'']]],
  ['day_203_3a_20build_20system_20and_20testing_20strategy_15',['Day 3: Build System and Testing Strategy',['../md_MIGRATION__CHECKLIST.html#autotoc_md86',1,'']]],
  ['day_204_205_16',['Day 4-5',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md211',1,'']]],
  ['day_204_205_3a_20basic_20structure_20creation_17',['Day 4-5: Basic Structure Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md92',1,'']]],
  ['day_206_207_18',['Day 6-7',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md212',1,'']]],
  ['day_206_207_3a_20namespace_20and_20include_20path_20updates_19',['Day 6-7: Namespace and Include Path Updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md95',1,'']]],
  ['day_208_20',['Day 8',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md213',1,'']]],
  ['day_208_3a_20basic_20build_20system_20configuration_21',['Day 8: Basic Build System Configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md98',1,'']]],
  ['day_209_2010_22',['Day 9-10',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md215',1,'']]],
  ['day_209_2010_3a_20bridge_20class_20implementation_23',['Day 9-10: Bridge Class Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md104',1,'']]],
  ['days_24',['days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md206',1,'Phase 1: Preparation and Analysis (2-3 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md210',1,'Phase 2: Core System Separation (4-5 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md214',1,'Phase 3: Integration Interface Implementation (3-4 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md217',1,'Phase 4: messaging_system Update (2-3 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md220',1,'Phase 5: Verification and Deployment (2-3 days)']]],
  ['debian_25',['debian',['../md_BUILD.html#autotoc_md7',1,'Ubuntu/Debian'],['../md_README.html#autotoc_md268',1,'Ubuntu/Debian']]],
  ['debug_20build_26',['Debug Build',['../md_BUILD.html#autotoc_md26',1,'']]],
  ['debug_20build_20issues_27',['Debug Build Issues',['../md_BUILD.html#autotoc_md37',1,'']]],
  ['debugging_20tips_28',['Debugging Tips',['../index.html#trouble_debugging',1,'']]],
  ['degradation_29',['degradation',['../md_MIGRATION__GUIDE.html#autotoc_md179',1,'4. Performance Degradation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md138',1,'Performance Degradation']]],
  ['dependencies_30',['dependencies',['../md_README.html#autotoc_md287',1,'🔧 Dependencies'],['../md_BUILD.html#autotoc_md19',1,'Install Dependencies'],['../md_BUILD.html#autotoc_md8',1,'Install Dependencies'],['../md_BUILD.html#autotoc_md11',1,'Install Dependencies'],['../md_BUILD.html#autotoc_md14',1,'Install Dependencies'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md198',1,'Key Dependencies'],['../index.html#deps_optional',1,'Optional Dependencies'],['../md_BUILD.html#autotoc_md4',1,'Optional Dependencies'],['../index.html#deps_required',1,'Required Dependencies'],['../md_MIGRATION__GUIDE.html#autotoc_md151',1,'Step 1: Update Dependencies']]],
  ['dependencies_20and_20requirements_31',['Dependencies and Requirements',['../index.html#dependencies_sec',1,'']]],
  ['dependency_20configuration_32',['Dependency Configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md100',1,'']]],
  ['dependency_20management_33',['dependency management',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md309',1,'🔗 Dependency Management'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md231',1,'4. Dependency Management']]],
  ['dependency_20sh_34',['dependency.sh',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md233',1,'']]],
  ['deployment_35',['deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md120',1,'✅ Phase 5: Verification and Deployment'],['../md_MIGRATION__CHECKLIST.html#autotoc_md125',1,'Day 18: Final Verification and Deployment'],['../md_MIGRATION__CHECKLIST.html#autotoc_md128',1,'Final Deployment'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md259',1,'Phase 5: Verification and Deployment']]],
  ['deployment_202_203_20days_36',['Phase 5: Verification and Deployment (2-3 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md220',1,'']]],
  ['design_37',['design',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md300',1,'🏗️ Architecture Design'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md306',1,'2. Core API Design'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md302',1,'2. Namespace Design'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md229',1,'3. Integration Interface Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md84',1,'Architecture Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md87',1,'Build System Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md85',1,'Integration Interface Design']]],
  ['design_20and_20planning_38',['Day 2: Design and Planning',['../md_MIGRATION__CHECKLIST.html#autotoc_md83',1,'']]],
  ['detailed_20execution_20checklist_20for_20network_5fsystem_20separation_20from_20messaging_5fsystem_39',['Detailed Execution Checklist for network_system Separation from messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md75',1,'']]],
  ['detailed_20plan_20for_20separating_20network_5fsystem_20from_20messaging_5fsystem_40',['Detailed Plan for Separating network_system from messaging_system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md189',1,'']]],
  ['details_41',['details',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md224',1,'🛠️ Technical Implementation Details'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html',1,'Technical Implementation Details']]],
  ['development_42',['Testing Strategy Development',['../md_MIGRATION__CHECKLIST.html#autotoc_md88',1,'']]],
  ['development_20guidelines_43',['Development Guidelines',['../index.html#contrib_guidelines',1,'']]],
  ['development_20timeline_44',['Development Timeline',['../md_CHANGELOG.html#autotoc_md67',1,'']]],
  ['differences_45',['Key API Differences',['../md_MIGRATION__GUIDE.html#autotoc_md164',1,'']]],
  ['directory_20structure_20creation_46',['Directory Structure Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md93',1,'']]],
  ['directory_20structure_20reorganization_47',['1. Directory Structure Reorganization',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md225',1,'']]],
  ['documentation_48',['documentation',['../md_README.html#autotoc_md291',1,'📚 Documentation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md250',1,'1. API Documentation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md251',1,'2. Architecture Documentation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md252',1,'3. Operations Documentation'],['../index.html',1,'Network System Documentation']]],
  ['documentation_20plan_49',['📝 Documentation Plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md249',1,'']]],
  ['documentation_20updates_50',['Documentation Updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md127',1,'']]],
  ['during_20migration_51',['Testing During Migration',['../index.html#migration_testing',1,'']]]
];
