var searchData=
[
  ['implementation_0',['implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md29',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md234',1,'🔧 Core Component Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md36',1,'Compatibility API Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md30',1,'Day 9-10: Bridge Class Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md31',1,'messaging_bridge Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md32',1,'Performance Monitoring Implementation'],['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md151',1,'Phase 2: Feature Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md141',1,'Phase 3: Integration Interface Implementation']]],
  ['implementation_203_204_20days_1',['implementation 3 4 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md98',1,'Phase 3: Integration Interface Implementation (3-4 days)'],['../md_README.html#autotoc_md192',1,'Phase 3: Integration Interface Implementation (3-4 days)']]],
  ['implementation_20details_2',['implementation details',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md108',1,'🛠️ Technical Implementation Details'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html',1,'Technical Implementation Details']]],
  ['implementation_20guide_3',['Network System Separation Technical Implementation Guide',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md228',1,'']]],
  ['implementation_20plan_4',['Phase 2 Implementation Plan',['../md_PHASE2__IMPLEMENTATION__PLAN.html',1,'']]],
  ['implementation_20roadmap_5',['📅 Implementation Roadmap',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md89',1,'']]],
  ['implementation_20strategy_6',['Implementation Strategy',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md156',1,'']]],
  ['implemented_7',['Successfully Implemented',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md149',1,'']]],
  ['include_20path_20updates_8',['include path updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md21',1,'Day 6-7: Namespace and Include Path Updates'],['../md_MIGRATION__CHECKLIST.html#autotoc_md23',1,'Include Path Updates']]],
  ['independent_20high_20performance_20network_20system_20separated_20from_20messaging_5fsystem_9',['Independent High-Performance Network System Separated from messaging_system',['../md_README.html#autotoc_md167',1,'']]],
  ['initial_20build_20test_10',['Initial Build Test',['../md_MIGRATION__CHECKLIST.html#autotoc_md27',1,'']]],
  ['inquiries_11',['Inquiries',['../md_README.html#autotoc_md216',1,'']]],
  ['integration_12',['integration',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md163',1,'API Integration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md34',1,'container_system Integration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md33',1,'Day 11-12: External System Integration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md35',1,'thread_system Integration']]],
  ['integration_20completion_13',['v2.0.2 (Planned) - Integration Completion',['../md_README.html#autotoc_md222',1,'']]],
  ['integration_20dependencies_20conditional_14',['Integration Dependencies (Conditional)',['../md_README.html#autotoc_md203',1,'']]],
  ['integration_20details_15',['Container System Integration Details',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md161',1,'']]],
  ['integration_20interface_20design_16',['integration interface design',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md113',1,'3. Integration Interface Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md11',1,'Integration Interface Design']]],
  ['integration_20interface_20implementation_17',['integration interface implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md29',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md141',1,'Phase 3: Integration Interface Implementation']]],
  ['integration_20interface_20implementation_203_204_20days_18',['integration interface implementation 3 4 days',['../md_README.html#autotoc_md192',1,'Phase 3: Integration Interface Implementation (3-4 days)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md98',1,'Phase 3: Integration Interface Implementation (3-4 days)']]],
  ['integration_20layer_19',['integration layer',['../md_README.html#autotoc_md186',1,'2. Integration Layer'],['../index.html#arch_integration',1,'Integration Layer']]],
  ['integration_20testing_20',['Day 15: Integration Testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md42',1,'']]],
  ['integration_20tests_21',['integration tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md121',1,'2. Integration Tests'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md245',1,'2. Integration Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md49',1,'Integration Tests'],['../md_README.html#autotoc_md198',1,'Integration Tests']]],
  ['interface_20design_22',['interface design',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md113',1,'3. Integration Interface Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md11',1,'Integration Interface Design']]],
  ['interface_20implementation_23',['interface implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md29',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md141',1,'Phase 3: Integration Interface Implementation']]],
  ['interface_20implementation_203_204_20days_24',['interface implementation 3 4 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md98',1,'Phase 3: Integration Interface Implementation (3-4 days)'],['../md_README.html#autotoc_md192',1,'Phase 3: Integration Interface Implementation (3-4 days)']]],
  ['internal_20layer_25',['Internal Layer',['../index.html#arch_internal',1,'']]],
  ['introduction_26',['Introduction',['../index.html#intro_sec',1,'']]],
  ['issues_27',['issues',['../index.html#trouble_common',1,'Common Issues'],['../md_MIGRATION__CHECKLIST.html#autotoc_md65',1,'Compatibility Issues']]],
  ['issues_20and_20solutions_28',['Issues and Solutions',['../md_MIGRATION__CHECKLIST.html#autotoc_md69',1,'']]]
];
