var searchData=
[
  ['scope_0',['Scope',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md193',1,'']]],
  ['security_1',['Security',['../md_CHANGELOG.html#autotoc_md63',1,'']]],
  ['security_20considerations_2',['Security Considerations',['../index.html#feat_security',1,'']]],
  ['separating_20network_5fsystem_20from_20messaging_5fsystem_3',['Detailed Plan for Separating network_system from messaging_system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md189',1,'']]],
  ['separation_4',['separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md91',1,'🔧 Phase 2: Core System Separation'],['../md_CHANGELOG.html#autotoc_md64',1,'2025-09-18 - Initial Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md242',1,'Baseline (Before Separation)'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md256',1,'Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md243',1,'Target (After Separation)']]],
  ['separation_204_205_20days_5',['Phase 2: Core System Separation (4-5 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md210',1,'']]],
  ['separation_20from_20messaging_5fsystem_6',['Detailed Execution Checklist for network_system Separation from messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md75',1,'']]],
  ['separation_20plan_7',['Network System Separation Plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html',1,'']]],
  ['separation_20strategy_8',['🎯 Separation Strategy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md200',1,'']]],
  ['separation_20technical_20implementation_20guide_9',['Network System Separation Technical Implementation Guide',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md298',1,'']]],
  ['server_20api_10',['Server API',['../md_MIGRATION__GUIDE.html#autotoc_md158',1,'']]],
  ['server_20usage_11',['Basic Server Usage',['../index.html#usage_server',1,'']]],
  ['session_20layer_12',['Session Layer',['../index.html#arch_session',1,'']]],
  ['session_20management_13',['3. Session Management',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md307',1,'']]],
  ['sh_14',['dependency.sh',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md233',1,'']]],
  ['solutions_15',['solutions',['../md_MIGRATION__GUIDE.html#autotoc_md175',1,'Common Issues and Solutions'],['../md_MIGRATION__CHECKLIST.html#autotoc_md143',1,'Issues and Solutions']]],
  ['specific_20instructions_16',['Platform-Specific Instructions',['../md_BUILD.html#autotoc_md6',1,'']]],
  ['start_17',['🚀 Quick Start',['../md_README.html#autotoc_md266',1,'']]],
  ['state_20analysis_18',['state analysis',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md195',1,'🏗️ Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md82',1,'Current State Analysis'],['../md_MIGRATION__CHECKLIST.html#autotoc_md80',1,'Day 1: Backup and Current State Analysis']]],
  ['status_19',['🎯 CI/CD Status',['../md_README.html#autotoc_md290',1,'']]],
  ['step_201_3a_20update_20dependencies_20',['Step 1: Update Dependencies',['../md_MIGRATION__GUIDE.html#autotoc_md151',1,'']]],
  ['step_202_3a_20update_20includes_20compatibility_20mode_21',['Step 2: Update Includes (Compatibility Mode)',['../md_MIGRATION__GUIDE.html#autotoc_md152',1,'']]],
  ['step_203_3a_20initialize_20system_22',['Step 3: Initialize System',['../md_MIGRATION__GUIDE.html#autotoc_md153',1,'']]],
  ['still_20supported_23',['still supported',['../md_MIGRATION__GUIDE.html#autotoc_md159',1,'Legacy API (Still Supported)'],['../md_MIGRATION__GUIDE.html#autotoc_md162',1,'Legacy API (Still Supported)']]],
  ['strategy_24',['strategy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md200',1,'🎯 Separation Strategy'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md235',1,'🧪 Testing Strategy'],['../md_MIGRATION__CHECKLIST.html#autotoc_md86',1,'Day 3: Build System and Testing Strategy']]],
  ['strategy_20development_25',['Testing Strategy Development',['../md_MIGRATION__CHECKLIST.html#autotoc_md88',1,'']]],
  ['stress_20tests_26',['stress tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md239',1,'4. Stress Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md124',1,'Stress Tests']]],
  ['structure_27',['structure',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md301',1,'1. Module Layer Structure'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md314',1,'1. Unit Test Structure'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md197',1,'Existing network_system Structure'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md196',1,'messaging_system/network Structure'],['../md_MIGRATION__GUIDE.html#autotoc_md156',1,'Modern Namespace Structure'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md226',1,'Target Structure']]],
  ['structure_20creation_28',['structure creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md92',1,'Day 4-5: Basic Structure Creation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md93',1,'Directory Structure Creation']]],
  ['structure_20reorganization_29',['1. Directory Structure Reorganization',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md225',1,'']]],
  ['studio_30',['Windows (Visual Studio)',['../md_BUILD.html#autotoc_md13',1,'']]],
  ['support_31',['support',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md261',1,'📞 Contact and Support'],['../index.html#contact_sec',1,'Contact and Support'],['../md_CHANGELOG.html#autotoc_md73',1,'Support'],['../md_MIGRATION__GUIDE.html#autotoc_md186',1,'Support'],['../md_BUILD.html#autotoc_md45',1,'Support']]],
  ['supported_32',['supported',['../md_MIGRATION__GUIDE.html#autotoc_md162',1,'Legacy API (Still Supported)'],['../md_MIGRATION__GUIDE.html#autotoc_md159',1,'Legacy API (Still Supported)']]],
  ['system_33',['system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md227',1,'2. CMake Build System'],['../md_README.html',1,'Network System'],['../md_MIGRATION__GUIDE.html#autotoc_md153',1,'Step 3: Initialize System']]],
  ['system_20and_20testing_20strategy_34',['Day 3: Build System and Testing Strategy',['../md_MIGRATION__CHECKLIST.html#autotoc_md86',1,'']]],
  ['system_20configuration_35',['Day 8: Basic Build System Configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md98',1,'']]],
  ['system_20design_36',['Build System Design',['../md_MIGRATION__CHECKLIST.html#autotoc_md87',1,'']]],
  ['system_20documentation_37',['Network System Documentation',['../index.html',1,'']]],
  ['system_20integration_38',['Day 11-12: External System Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md107',1,'']]],
  ['system_20migration_39',['Build System Migration',['../md_MIGRATION__GUIDE.html#autotoc_md165',1,'']]],
  ['system_20migration_20checklist_40',['Network System Migration Checklist',['../md_MIGRATION__CHECKLIST.html',1,'']]],
  ['system_20not_20found_41',['5. Container System Not Found',['../md_MIGRATION__GUIDE.html#autotoc_md180',1,'']]],
  ['system_20packages_42',['Using System Packages',['../md_MIGRATION__GUIDE.html#autotoc_md169',1,'']]],
  ['system_20separation_43',['system separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md91',1,'🔧 Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md256',1,'Phase 2: Core System Separation']]],
  ['system_20separation_204_205_20days_44',['Phase 2: Core System Separation (4-5 days)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md210',1,'']]],
  ['system_20separation_20plan_45',['Network System Separation Plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html',1,'']]],
  ['system_20separation_20technical_20implementation_20guide_46',['Network System Separation Technical Implementation Guide',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md298',1,'']]],
  ['system_20testing_47',['Day 16-17: Full System Testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md121',1,'']]]
];
