var searchData=
[
  ['backup_20and_20current_20state_20analysis_0',['Day 1: Backup and Current State Analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md70',1,'']]],
  ['backup_20tasks_1',['Backup Tasks',['../md_MIGRATION__CHECKLIST.html#autotoc_md71',1,'']]],
  ['baseline_20before_20separation_2',['Baseline (Before Separation)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md190',1,'']]],
  ['baseline_20pre_20separation_3',['Baseline (Pre-Separation)',['../md_README.html#autotoc_md378',1,'']]],
  ['basic_20build_20system_20configuration_4',['Day 8: Basic Build System Configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md88',1,'']]],
  ['basic_20client_20usage_5',['Basic Client Usage',['../index.html#usage_client',1,'']]],
  ['basic_20principles_6',['1. Basic Principles',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md149',1,'']]],
  ['basic_20server_20usage_7',['Basic Server Usage',['../index.html#usage_server',1,'']]],
  ['basic_20structure_20creation_8',['Day 4-5: Basic Structure Creation',['../md_MIGRATION__CHECKLIST.html#autotoc_md82',1,'']]],
  ['be_20implemented_9',['To Be Implemented',['../md_CHANGELOG.html#autotoc_md48',1,'']]],
  ['before_20separation_10',['Baseline (Before Separation)',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md190',1,'']]],
  ['benchmark_20results_11',['Benchmark Results',['../index.html#perf_benchmarks',1,'']]],
  ['benchmark_20tools_12',['2. Benchmark Tools',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md517',1,'']]],
  ['benchmarks_13',['benchmarks',['../md_MIGRATION__CHECKLIST.html#autotoc_md108',1,'Performance Benchmarks'],['../md_BUILD.html#autotoc_md44',1,'Run Benchmarks']]],
  ['bridge_14',['Migration with Bridge',['../index.html#usage_bridge',1,'']]],
  ['bridge_20class_20implementation_15',['Day 9-10: Bridge Class Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md94',1,'']]],
  ['build_16',['build',['../md_BUILD.html#autotoc_md9',1,'Build'],['../md_BUILD.html#autotoc_md20',1,'Build'],['../md_BUILD.html#autotoc_md12',1,'Build'],['../md_BUILD.html#autotoc_md17',1,'Build'],['../md_BUILD.html#autotoc_md38',1,'Clean Build'],['../md_BUILD.html#autotoc_md26',1,'Debug Build'],['../md_BUILD.html#autotoc_md25',1,'Full Feature Build'],['../md_BUILD.html#autotoc_md24',1,'Minimal Build'],['../md_BUILD.html#autotoc_md5',1,'Quick Build']]],
  ['build_20commands_17',['Build Commands',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md234',1,'']]],
  ['build_20failure_18',['vcpkg Build Failure',['../md_BUILD.html#autotoc_md35',1,'']]],
  ['build_20failures_19',['Build Failures',['../md_MIGRATION__CHECKLIST.html#autotoc_md127',1,'']]],
  ['build_20instructions_20',['build instructions',['../md_README.html#autotoc_md293',1,'Build Instructions'],['../md_BUILD.html',1,'Build Instructions']]],
  ['build_20issues_21',['Debug Build Issues',['../md_BUILD.html#autotoc_md37',1,'']]],
  ['build_20options_22',['Build Options',['../md_BUILD.html#autotoc_md21',1,'']]],
  ['build_20platforms_20✅_23',['Build Platforms ✅',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md225',1,'']]],
  ['build_20requirements_24',['Build Requirements',['../index.html#deps_build',1,'']]],
  ['build_20system_25',['2. CMake Build System',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md175',1,'']]],
  ['build_20system_20and_20testing_20strategy_26',['Day 3: Build System and Testing Strategy',['../md_MIGRATION__CHECKLIST.html#autotoc_md76',1,'']]],
  ['build_20system_20configuration_27',['Day 8: Basic Build System Configuration',['../md_MIGRATION__CHECKLIST.html#autotoc_md88',1,'']]],
  ['build_20system_20design_28',['Build System Design',['../md_MIGRATION__CHECKLIST.html#autotoc_md77',1,'']]],
  ['build_20test_29',['Initial Build Test',['../md_MIGRATION__CHECKLIST.html#autotoc_md91',1,'']]],
  ['build_20tools_30',['Build Tools',['../md_README.html#autotoc_md370',1,'']]],
  ['built_31',['Core Components Built',['../md_PHASE2__IMPLEMENTATION__PLAN.html#autotoc_md214',1,'']]]
];
