var searchData=
[
  ['sample_5finfo_0',['sample_info',['../structsample__info.html',1,'']]],
  ['sample_5frunner_1',['sample_runner',['../classsample__runner.html',1,'']]],
  ['scoped_5fconnection_2',['scoped_connection',['../classscoped__connection.html',1,'']]],
  ['secure_5fmessaging_5fclient_3',['secure_messaging_client',['../classkcenon_1_1network_1_1core_1_1secure__messaging__client.html',1,'kcenon::network::core']]],
  ['secure_5fmessaging_5fserver_4',['secure_messaging_server',['../classkcenon_1_1network_1_1core_1_1secure__messaging__server.html',1,'kcenon::network::core']]],
  ['secure_5fmessaging_5fudp_5fclient_5',['secure_messaging_udp_client',['../classkcenon_1_1network_1_1core_1_1secure__messaging__udp__client.html',1,'kcenon::network::core']]],
  ['secure_5fmessaging_5fudp_5fserver_6',['secure_messaging_udp_server',['../classkcenon_1_1network_1_1core_1_1secure__messaging__udp__server.html',1,'kcenon::network::core']]],
  ['secure_5fsession_7',['secure_session',['../classkcenon_1_1network_1_1session_1_1secure__session.html',1,'kcenon::network::session']]],
  ['secure_5ftcp_5fsocket_8',['secure_tcp_socket',['../classkcenon_1_1network_1_1internal_1_1secure__tcp__socket.html',1,'kcenon::network::internal']]],
  ['sent_5fpacket_9',['sent_packet',['../structkcenon_1_1network_1_1protocols_1_1quic_1_1sent__packet.html',1,'kcenon::network::protocols::quic']]],
  ['sent_5fpacket_5finfo_10',['sent_packet_info',['../structkcenon_1_1network_1_1protocols_1_1quic_1_1sent__packet__info.html',1,'kcenon::network::protocols::quic']]],
  ['server_5fconfig_11',['server_config',['../structkcenon_1_1network_1_1facade_1_1http__facade_1_1server__config.html',1,'kcenon::network::facade::http_facade::server_config'],['../structkcenon_1_1network_1_1facade_1_1quic__facade_1_1server__config.html',1,'kcenon::network::facade::quic_facade::server_config'],['../structkcenon_1_1network_1_1facade_1_1tcp__facade_1_1server__config.html',1,'kcenon::network::facade::tcp_facade::server_config'],['../structkcenon_1_1network_1_1facade_1_1udp__facade_1_1server__config.html',1,'kcenon::network::facade::udp_facade::server_config'],['../structkcenon_1_1network_1_1facade_1_1websocket__facade_1_1server__config.html',1,'kcenon::network::facade::websocket_facade::server_config']]],
  ['server_5fcontext_12',['server_context',['../classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__context.html',1,'kcenon::network::protocols::grpc']]],
  ['server_5freader_13',['server_reader',['../classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__reader.html',1,'kcenon::network::protocols::grpc']]],
  ['server_5freader_5fwriter_14',['server_reader_writer',['../classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__reader__writer.html',1,'kcenon::network::protocols::grpc']]],
  ['server_5fstream_5freader_15',['server_stream_reader',['../classkcenon_1_1network_1_1protocols_1_1grpc_1_1grpc__client_1_1server__stream__reader.html',1,'kcenon::network::protocols::grpc::grpc_client']]],
  ['server_5fstream_5freader_5fimpl_16',['server_stream_reader_impl',['../classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__stream__reader__impl.html',1,'kcenon::network::protocols::grpc']]],
  ['server_5fwriter_17',['server_writer',['../classkcenon_1_1network_1_1protocols_1_1grpc_1_1server__writer.html',1,'kcenon::network::protocols::grpc']]],
  ['service_5fbase_18',['service_base',['../classkcenon_1_1network_1_1protocols_1_1grpc_1_1service__base.html',1,'kcenon::network::protocols::grpc']]],
  ['service_5fdescriptor_19',['service_descriptor',['../structkcenon_1_1network_1_1protocols_1_1grpc_1_1service__descriptor.html',1,'kcenon::network::protocols::grpc']]],
  ['service_5fregistry_20',['service_registry',['../classkcenon_1_1network_1_1protocols_1_1grpc_1_1service__registry.html',1,'kcenon::network::protocols::grpc']]],
  ['session_5fconcept_21',['session_concept',['../classkcenon_1_1network_1_1core_1_1session__concept.html',1,'kcenon::network::core']]],
  ['session_5fconfig_22',['session_config',['../structkcenon_1_1network_1_1core_1_1session__config.html',1,'kcenon::network::core']]],
  ['session_5fhandle_23',['session_handle',['../classkcenon_1_1network_1_1core_1_1session__handle.html',1,'kcenon::network::core']]],
  ['session_5finfo_24',['session_info',['../structkcenon_1_1network_1_1core_1_1session__info.html',1,'kcenon::network::core']]],
  ['session_5finfo_5fbase_25',['session_info_base',['../structkcenon_1_1network_1_1core_1_1session__info__base.html',1,'kcenon::network::core']]],
  ['session_5finfo_5fbase_3c_20sessiontype_2c_20false_20_3e_26',['session_info_base&lt; SessionType, false &gt;',['../structkcenon_1_1network_1_1core_1_1session__info__base_3_01SessionType_00_01false_01_4.html',1,'kcenon::network::core']]],
  ['session_5finfo_5fbase_3c_20sessiontype_2c_20true_20_3e_27',['session_info_base&lt; SessionType, true &gt;',['../structkcenon_1_1network_1_1core_1_1session__info__base_3_01SessionType_00_01true_01_4.html',1,'kcenon::network::core']]],
  ['session_5fmanager_28',['session_manager',['../classkcenon_1_1network_1_1core_1_1session__manager.html',1,'kcenon::network::core']]],
  ['session_5fmanager_5fbase_29',['session_manager_base',['../classkcenon_1_1network_1_1core_1_1session__manager__base.html',1,'kcenon::network::core']]],
  ['session_5fmanager_5fbase_3c_20session_3a_3amessaging_5fsession_20_3e_30',['session_manager_base&lt; session::messaging_session &gt;',['../classkcenon_1_1network_1_1core_1_1session__manager__base.html',1,'kcenon::network::core']]],
  ['session_5fmanager_5fbase_3c_20ws_5fconnection_20_3e_31',['session_manager_base&lt; ws_connection &gt;',['../classkcenon_1_1network_1_1core_1_1session__manager__base.html',1,'kcenon::network::core']]],
  ['session_5fmodel_32',['session_model',['../classkcenon_1_1network_1_1core_1_1session__model.html',1,'kcenon::network::core']]],
  ['session_5fticket_5finfo_33',['session_ticket_info',['../structkcenon_1_1network_1_1protocols_1_1quic_1_1session__ticket__info.html',1,'kcenon::network::protocols::quic']]],
  ['session_5fticket_5fstore_34',['session_ticket_store',['../classkcenon_1_1network_1_1protocols_1_1quic_1_1session__ticket__store.html',1,'kcenon::network::protocols::quic']]],
  ['session_5ftimeout_5fmanager_35',['session_timeout_manager',['../classkcenon_1_1network_1_1session__timeout__manager.html',1,'kcenon::network']]],
  ['session_5ftraits_36',['session_traits',['../structkcenon_1_1network_1_1core_1_1session__traits.html',1,'kcenon::network::core']]],
  ['session_5ftraits_3c_20session_3a_3amessaging_5fsession_20_3e_37',['session_traits&lt; session::messaging_session &gt;',['../structkcenon_1_1network_1_1core_1_1session__traits_3_01session_1_1messaging__session_01_4.html',1,'kcenon::network::core']]],
  ['session_5ftraits_3c_20ws_5fconnection_20_3e_38',['session_traits&lt; ws_connection &gt;',['../structkcenon_1_1network_1_1core_1_1session__traits_3_01ws__connection_01_4.html',1,'kcenon::network::core']]],
  ['setting_5fparameter_39',['setting_parameter',['../structkcenon_1_1network_1_1protocols_1_1http2_1_1setting__parameter.html',1,'kcenon::network::protocols::http2']]],
  ['settings_5fframe_40',['settings_frame',['../classkcenon_1_1network_1_1protocols_1_1http2_1_1settings__frame.html',1,'kcenon::network::protocols::http2']]],
  ['short_5fheader_41',['short_header',['../structkcenon_1_1network_1_1protocols_1_1quic_1_1short__header.html',1,'kcenon::network::protocols::quic']]],
  ['simple_5ferror_42',['simple_error',['../structkcenon_1_1network_1_1simple__error.html',1,'kcenon::network']]],
  ['sliding_5fhistogram_43',['sliding_histogram',['../classkcenon_1_1network_1_1metrics_1_1sliding__histogram.html',1,'kcenon::network::metrics']]],
  ['sliding_5fhistogram_5fconfig_44',['sliding_histogram_config',['../structkcenon_1_1network_1_1metrics_1_1sliding__histogram__config.html',1,'kcenon::network::metrics']]],
  ['socket_5fconfig_45',['socket_config',['../structkcenon_1_1network_1_1internal_1_1socket__config.html',1,'kcenon::network::internal']]],
  ['socket_5fmetrics_46',['socket_metrics',['../structkcenon_1_1network_1_1internal_1_1socket__metrics.html',1,'kcenon::network::internal']]],
  ['socket_5fread_5fguard_47',['socket_read_guard',['../classkcenon_1_1network_1_1concepts_1_1socket__read__guard.html',1,'kcenon::network::concepts']]],
  ['space_5fstate_48',['space_state',['../structkcenon_1_1network_1_1protocols_1_1quic_1_1loss__detector_1_1space__state.html',1,'kcenon::network::protocols::quic::loss_detector']]],
  ['span_49',['span',['../classkcenon_1_1network_1_1tracing_1_1span.html',1,'kcenon::network::tracing']]],
  ['span_5fevent_50',['span_event',['../structkcenon_1_1network_1_1tracing_1_1span__event.html',1,'kcenon::network::tracing']]],
  ['ssl_5fconfig_51',['ssl_config',['../structkcenon_1_1network_1_1core_1_1ssl__config.html',1,'kcenon::network::core']]],
  ['startable_5fbase_52',['startable_base',['../classkcenon_1_1network_1_1utils_1_1startable__base.html',1,'kcenon::network::utils']]],
  ['startable_5fbase_3c_20messaging_5fclient_20_3e_53',['startable_base&lt; messaging_client &gt;',['../classkcenon_1_1network_1_1utils_1_1startable__base.html',1,'kcenon::network::utils']]],
  ['startable_5fbase_3c_20messaging_5fserver_20_3e_54',['startable_base&lt; messaging_server &gt;',['../classkcenon_1_1network_1_1utils_1_1startable__base.html',1,'kcenon::network::utils']]],
  ['static_5fdestruction_5fguard_55',['static_destruction_guard',['../classkcenon_1_1network_1_1integration_1_1detail_1_1static__destruction__guard.html',1,'kcenon::network::integration::detail']]],
  ['static_5ftable_56',['static_table',['../classkcenon_1_1network_1_1protocols_1_1http2_1_1static__table.html',1,'kcenon::network::protocols::http2']]],
  ['stats_57',['stats',['../structkcenon_1_1network_1_1core_1_1session__manager__base_1_1stats.html',1,'kcenon::network::core::session_manager_base&lt; SessionType &gt;::stats'],['../structkcenon_1_1network_1_1core_1_1unified__session__manager_1_1stats.html',1,'kcenon::network::core::unified_session_manager::stats']]],
  ['stop_5fsending_5fframe_58',['stop_sending_frame',['../structkcenon_1_1network_1_1protocols_1_1quic_1_1stop__sending__frame.html',1,'kcenon::network::protocols::quic']]],
  ['stream_59',['stream',['../classkcenon_1_1network_1_1protocols_1_1quic_1_1stream.html',1,'kcenon::network::protocols::quic']]],
  ['stream_5fdata_5fblocked_5fframe_60',['stream_data_blocked_frame',['../structkcenon_1_1network_1_1protocols_1_1quic_1_1stream__data__blocked__frame.html',1,'kcenon::network::protocols::quic']]],
  ['stream_5fframe_61',['stream_frame',['../structkcenon_1_1network_1_1protocols_1_1quic_1_1stream__frame.html',1,'kcenon::network::protocols::quic']]],
  ['stream_5fmanager_62',['stream_manager',['../classkcenon_1_1network_1_1protocols_1_1quic_1_1stream__manager.html',1,'kcenon::network::protocols::quic']]],
  ['streams_5fblocked_5fframe_63',['streams_blocked_frame',['../structkcenon_1_1network_1_1protocols_1_1quic_1_1streams__blocked__frame.html',1,'kcenon::network::protocols::quic']]]
];
