var searchData=
[
  ['main_20cmakelists_20txt_0',['Main CMakeLists.txt',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md112',1,'']]],
  ['major_20risks_1',['Major Risks',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md130',1,'1. Major Risks'],['../md_README.html#autotoc_md192',1,'Major Risks']]],
  ['management_2',['Management',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md220',1,'🔗 Dependency Management'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md218',1,'3. Session Management'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md115',1,'4. Dependency Management']]],
  ['messaging_5fbridge_20class_3',['1. messaging_bridge Class',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md216',1,'']]],
  ['messaging_5fbridge_20h_4',['messaging_bridge.h',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md114',1,'']]],
  ['messaging_5fbridge_20implementation_5',['messaging_bridge Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md31',1,'']]],
  ['messaging_5fsystem_6',['messaging_system',['../md_MIGRATION__CHECKLIST.html#autotoc_md1',1,'Detailed Execution Checklist for network_system Separation from messaging_system'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md73',1,'Detailed Plan for Separating network_system from messaging_system'],['../index.html#migration_from_legacy',1,'From Legacy messaging_system'],['../md_README.html#autotoc_md148',1,'Independent High-Performance Network System Separated from messaging_system']]],
  ['messaging_5fsystem_20modification_7',['Day 13-14: messaging_system Modification',['../md_MIGRATION__CHECKLIST.html#autotoc_md39',1,'']]],
  ['messaging_5fsystem_20network_20structure_8',['messaging_system/network Structure',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md80',1,'']]],
  ['messaging_5fsystem_20update_9',['messaging_system Update',['../md_MIGRATION__CHECKLIST.html#autotoc_md38',1,'🔄 Phase 4: messaging_system Update'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md142',1,'Phase 4: messaging_system Update']]],
  ['messaging_5fsystem_20update_202_203_20days_10',['messaging_system Update 2 3 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md101',1,'Phase 4: messaging_system Update (2-3 days)'],['../md_README.html#autotoc_md174',1,'Phase 4: messaging_system Update (2-3 days)']]],
  ['metric_20collection_11',['1. Performance Metric Collection',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md229',1,'']]],
  ['migration_12',['Migration',['../md_README.html#autotoc_md159',1,'2. Run Migration'],['../index.html#migration_testing',1,'Testing During Migration']]],
  ['migration_20checklist_13',['Network System Migration Checklist',['../md_MIGRATION__CHECKLIST.html',1,'']]],
  ['migration_20guide_14',['Migration Guide',['../index.html#migration_sec',1,'']]],
  ['migration_20project_15',['Network System Migration Project',['../md_README.html',1,'']]],
  ['migration_20roadmap_16',['📊 Migration Roadmap',['../md_README.html#autotoc_md170',1,'']]],
  ['migration_20with_20bridge_17',['Migration with Bridge',['../index.html#usage_bridge',1,'']]],
  ['mission_18',['Mission',['../index.html#mission_sec',1,'']]],
  ['mitigation_19',['Mitigation',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md129',1,'🚨 Risk Factors and Mitigation'],['../md_README.html#autotoc_md191',1,'🚨 Risk Factors and Mitigation']]],
  ['modification_20',['Day 13-14: messaging_system Modification',['../md_MIGRATION__CHECKLIST.html#autotoc_md39',1,'']]],
  ['module_20files_21',['1. CMake Module Files',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md221',1,'']]],
  ['module_20layer_20structure_22',['1. Module Layer Structure',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md212',1,'']]],
  ['monitoring_23',['📊 Performance Monitoring',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md228',1,'']]],
  ['monitoring_20implementation_24',['Performance Monitoring Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md32',1,'']]]
];
