var searchData=
[
  ['implementation_0',['Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md29',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md215',1,'🔧 Core Component Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md36',1,'Compatibility API Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md30',1,'Day 9-10: Bridge Class Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md31',1,'messaging_bridge Implementation'],['../md_MIGRATION__CHECKLIST.html#autotoc_md32',1,'Performance Monitoring Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md141',1,'Phase 3: Integration Interface Implementation']]],
  ['implementation_203_204_20days_1',['Implementation 3 4 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md98',1,'Phase 3: Integration Interface Implementation (3-4 days)'],['../md_README.html#autotoc_md173',1,'Phase 3: Integration Interface Implementation (3-4 days)']]],
  ['implementation_20details_2',['Implementation Details',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md108',1,'🛠️ Technical Implementation Details'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html',1,'Technical Implementation Details']]],
  ['implementation_20guide_3',['Network System Separation Technical Implementation Guide',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md209',1,'']]],
  ['implementation_20roadmap_4',['📅 Implementation Roadmap',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md89',1,'']]],
  ['include_20path_20updates_5',['Include Path Updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md21',1,'Day 6-7: Namespace and Include Path Updates'],['../md_MIGRATION__CHECKLIST.html#autotoc_md23',1,'Include Path Updates']]],
  ['independent_20high_20performance_20network_20system_20separated_20from_20messaging_5fsystem_6',['Independent High-Performance Network System Separated from messaging_system',['../md_README.html#autotoc_md148',1,'']]],
  ['initial_20build_20test_7',['Initial Build Test',['../md_MIGRATION__CHECKLIST.html#autotoc_md27',1,'']]],
  ['inquiries_8',['Inquiries',['../md_README.html#autotoc_md197',1,'']]],
  ['integration_9',['Integration',['../md_MIGRATION__CHECKLIST.html#autotoc_md34',1,'container_system Integration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md33',1,'Day 11-12: External System Integration'],['../md_MIGRATION__CHECKLIST.html#autotoc_md35',1,'thread_system Integration']]],
  ['integration_20completion_10',['v2.0.2 (Planned) - Integration Completion',['../md_README.html#autotoc_md203',1,'']]],
  ['integration_20dependencies_20conditional_11',['Integration Dependencies (Conditional)',['../md_README.html#autotoc_md184',1,'']]],
  ['integration_20interface_20design_12',['Integration Interface Design',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md113',1,'3. Integration Interface Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md11',1,'Integration Interface Design']]],
  ['integration_20interface_20implementation_13',['Integration Interface Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md29',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md141',1,'Phase 3: Integration Interface Implementation']]],
  ['integration_20interface_20implementation_203_204_20days_14',['Integration Interface Implementation 3 4 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md98',1,'Phase 3: Integration Interface Implementation (3-4 days)'],['../md_README.html#autotoc_md173',1,'Phase 3: Integration Interface Implementation (3-4 days)']]],
  ['integration_20layer_15',['Integration Layer',['../md_README.html#autotoc_md167',1,'2. Integration Layer'],['../index.html#arch_integration',1,'Integration Layer']]],
  ['integration_20testing_16',['Day 15: Integration Testing',['../md_MIGRATION__CHECKLIST.html#autotoc_md42',1,'']]],
  ['integration_20tests_17',['Integration Tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md121',1,'2. Integration Tests'],['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md226',1,'2. Integration Tests'],['../md_MIGRATION__CHECKLIST.html#autotoc_md49',1,'Integration Tests'],['../md_README.html#autotoc_md179',1,'Integration Tests']]],
  ['interface_20design_18',['Interface Design',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md113',1,'3. Integration Interface Design'],['../md_MIGRATION__CHECKLIST.html#autotoc_md11',1,'Integration Interface Design']]],
  ['interface_20implementation_19',['Interface Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md29',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md141',1,'Phase 3: Integration Interface Implementation']]],
  ['interface_20implementation_203_204_20days_20',['Interface Implementation 3 4 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md98',1,'Phase 3: Integration Interface Implementation (3-4 days)'],['../md_README.html#autotoc_md173',1,'Phase 3: Integration Interface Implementation (3-4 days)']]],
  ['internal_20layer_21',['Internal Layer',['../index.html#arch_internal',1,'']]],
  ['introduction_22',['Introduction',['../index.html#intro_sec',1,'']]],
  ['issues_23',['Issues',['../index.html#trouble_common',1,'Common Issues'],['../md_MIGRATION__CHECKLIST.html#autotoc_md65',1,'Compatibility Issues']]],
  ['issues_20and_20solutions_24',['Issues and Solutions',['../md_MIGRATION__CHECKLIST.html#autotoc_md69',1,'']]]
];
