var searchData=
[
  ['path_20updates_0',['Path Updates',['../md_MIGRATION__CHECKLIST.html#autotoc_md21',1,'Day 6-7: Namespace and Include Path Updates'],['../md_MIGRATION__CHECKLIST.html#autotoc_md23',1,'Include Path Updates']]],
  ['performance_20benchmarks_1',['Performance Benchmarks',['../md_MIGRATION__CHECKLIST.html#autotoc_md44',1,'']]],
  ['performance_20characteristics_2',['Performance Characteristics',['../md_README.html#autotoc_md168',1,'3. Performance Characteristics'],['../index.html#performance_sec',1,'Performance Characteristics']]],
  ['performance_20degradation_3',['Performance Degradation',['../md_MIGRATION__CHECKLIST.html#autotoc_md64',1,'']]],
  ['performance_20metric_20collection_4',['1. Performance Metric Collection',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md229',1,'']]],
  ['performance_20monitoring_5',['📊 Performance Monitoring',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md228',1,'']]],
  ['performance_20monitoring_20implementation_6',['Performance Monitoring Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md32',1,'']]],
  ['performance_20network_20system_20separated_20from_20messaging_5fsystem_7',['Independent High-Performance Network System Separated from messaging_system',['../md_README.html#autotoc_md148',1,'']]],
  ['performance_20optimization_8',['Performance Optimization',['../md_MIGRATION__CHECKLIST.html#autotoc_md52',1,'']]],
  ['performance_20optimizations_9',['Performance Optimizations',['../index.html#feat_perf',1,'']]],
  ['performance_20requirements_10',['Performance Requirements',['../md_README.html#autotoc_md187',1,'📈 Performance Requirements'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md125',1,'📊 Performance Requirements']]],
  ['performance_20tests_11',['Performance Tests',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md122',1,'3. Performance Tests'],['../md_README.html#autotoc_md180',1,'Performance Tests']]],
  ['performance_20verification_12',['Performance Verification',['../md_MIGRATION__CHECKLIST.html#autotoc_md58',1,'']]],
  ['phase_13',['v2.0.0 (2025-09-19) - Planning Phase',['../md_README.html#autotoc_md201',1,'']]],
  ['phase_201_3a_20preparation_20and_20analysis_14',['Phase 1: Preparation and Analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md5',1,'🎯 Phase 1: Preparation and Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md139',1,'Phase 1: Preparation and Analysis']]],
  ['phase_201_3a_20preparation_20and_20analysis_202_203_20days_15',['Phase 1: Preparation and Analysis 2 3 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md90',1,'Phase 1: Preparation and Analysis (2-3 days)'],['../md_README.html#autotoc_md171',1,'Phase 1: Preparation and Analysis (2-3 days)']]],
  ['phase_202_3a_20core_20system_20separation_16',['Phase 2: Core System Separation',['../md_MIGRATION__CHECKLIST.html#autotoc_md17',1,'🔧 Phase 2: Core System Separation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md140',1,'Phase 2: Core System Separation']]],
  ['phase_202_3a_20core_20system_20separation_204_205_20days_17',['Phase 2: Core System Separation 4 5 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md94',1,'Phase 2: Core System Separation (4-5 days)'],['../md_README.html#autotoc_md172',1,'Phase 2: Core System Separation (4-5 days)']]],
  ['phase_203_3a_20integration_20interface_20implementation_18',['Phase 3: Integration Interface Implementation',['../md_MIGRATION__CHECKLIST.html#autotoc_md29',1,'🔗 Phase 3: Integration Interface Implementation'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md141',1,'Phase 3: Integration Interface Implementation']]],
  ['phase_203_3a_20integration_20interface_20implementation_203_204_20days_19',['Phase 3: Integration Interface Implementation 3 4 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md98',1,'Phase 3: Integration Interface Implementation (3-4 days)'],['../md_README.html#autotoc_md173',1,'Phase 3: Integration Interface Implementation (3-4 days)']]],
  ['phase_204_3a_20messaging_5fsystem_20update_20',['Phase 4: messaging_system Update',['../md_MIGRATION__CHECKLIST.html#autotoc_md38',1,'🔄 Phase 4: messaging_system Update'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md142',1,'Phase 4: messaging_system Update']]],
  ['phase_204_3a_20messaging_5fsystem_20update_202_203_20days_21',['Phase 4: messaging_system Update 2 3 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md101',1,'Phase 4: messaging_system Update (2-3 days)'],['../md_README.html#autotoc_md174',1,'Phase 4: messaging_system Update (2-3 days)']]],
  ['phase_205_3a_20verification_20and_20deployment_22',['Phase 5: Verification and Deployment',['../md_MIGRATION__CHECKLIST.html#autotoc_md46',1,'✅ Phase 5: Verification and Deployment'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md143',1,'Phase 5: Verification and Deployment']]],
  ['phase_205_3a_20verification_20and_20deployment_202_203_20days_23',['Phase 5: Verification and Deployment 2 3 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md104',1,'Phase 5: Verification and Deployment (2-3 days)'],['../md_README.html#autotoc_md175',1,'Phase 5: Verification and Deployment (2-3 days)']]],
  ['pkg_20config_20file_24',['2. pkg-config File',['../md_TECHNICAL__IMPLEMENTATION__DETAILS.html#autotoc_md222',1,'']]],
  ['plan_25',['Plan',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md133',1,'📝 Documentation Plan'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md131',1,'2. Rollback Plan'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html',1,'Network System Separation Plan'],['../md_README.html#autotoc_md193',1,'Rollback Plan']]],
  ['plan_20for_20separating_20network_5fsystem_20from_20messaging_5fsystem_26',['Detailed Plan for Separating network_system from messaging_system',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md73',1,'']]],
  ['planned_20core_20separation_27',['v2.0.1 (Planned) - Core Separation',['../md_README.html#autotoc_md202',1,'']]],
  ['planned_20integration_20completion_28',['v2.0.2 (Planned) - Integration Completion',['../md_README.html#autotoc_md203',1,'']]],
  ['planned_20stabilization_29',['v2.1.0 (Planned) - Stabilization',['../md_README.html#autotoc_md204',1,'']]],
  ['planning_30',['Day 2: Design and Planning',['../md_MIGRATION__CHECKLIST.html#autotoc_md9',1,'']]],
  ['planning_20and_20design_20documents_31',['📋 Planning and Design Documents',['../md_README.html#autotoc_md154',1,'']]],
  ['planning_20phase_32',['v2.0.0 (2025-09-19) - Planning Phase',['../md_README.html#autotoc_md201',1,'']]],
  ['policy_33',['2. Namespace Policy',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md86',1,'']]],
  ['post_20separation_34',['Target (Post-Separation)',['../md_README.html#autotoc_md189',1,'']]],
  ['post_20separation_20structure_35',['Post-Separation Structure',['../md_README.html#autotoc_md164',1,'']]],
  ['pre_20separation_36',['Baseline (Pre-Separation)',['../md_README.html#autotoc_md188',1,'']]],
  ['pre_20separation_20structure_37',['Pre-Separation Structure',['../md_README.html#autotoc_md163',1,'']]],
  ['preparation_20and_20analysis_38',['Preparation and Analysis',['../md_MIGRATION__CHECKLIST.html#autotoc_md5',1,'🎯 Phase 1: Preparation and Analysis'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md139',1,'Phase 1: Preparation and Analysis']]],
  ['preparation_20and_20analysis_202_203_20days_39',['Preparation and Analysis 2 3 days',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md90',1,'Phase 1: Preparation and Analysis (2-3 days)'],['../md_README.html#autotoc_md171',1,'Phase 1: Preparation and Analysis (2-3 days)']]],
  ['prerequisites_40',['1. Prerequisites',['../md_README.html#autotoc_md158',1,'']]],
  ['principles_41',['1. Basic Principles',['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md85',1,'']]],
  ['progress_42',['📋 Overall Progress',['../md_MIGRATION__CHECKLIST.html#autotoc_md3',1,'']]],
  ['project_43',['Network System Migration Project',['../md_README.html',1,'']]],
  ['project_20overview_44',['Project Overview',['../md_README.html#autotoc_md150',1,'🎯 Project Overview'],['../md_NETWORK__SYSTEM__SEPARATION__PLAN.html#autotoc_md75',1,'📋 Project Overview']]],
  ['project_20owner_45',['Project Owner',['../md_README.html#autotoc_md196',1,'']]]
];
