// BSD 3-Clause License
// Copyright (c) 2024, 🍀☀🌕🌥 🌊
// See the LICENSE file in the project root for full license information.

#include <gtest/gtest.h>

#include "kcenon/network/facade/tcp_facade.h"
#include "kcenon/network/interfaces/i_protocol_client.h"
#include "kcenon/network/interfaces/i_protocol_server.h"

#include <chrono>
#include <memory>
#include <string>
#include <thread>
#include <vector>

using namespace kcenon::network::facade;
using namespace kcenon::network::interfaces;

class TcpFacadeTest : public ::testing::Test
{
protected:
	void SetUp() override
	{
		facade_ = std::make_unique<tcp_facade>();
	}

	void TearDown() override
	{
		if (client_)
		{
			(void)client_->stop();
		}
		if (server_)
		{
			(void)server_->stop();
		}
	}

	std::unique_ptr<tcp_facade> facade_;
	std::shared_ptr<i_protocol_server> server_;
	std::shared_ptr<i_protocol_client> client_;
};

// ============================================================================
// Client Configuration Validation Tests
// ============================================================================

TEST_F(TcpFacadeTest, CreateClientThrowsOnEmptyHost)
{
	tcp_facade::client_config config{
		.host = "",
		.port = 8080,
	};

	auto result = facade_->create_client(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(TcpFacadeTest, CreateClientThrowsOnInvalidPortZero)
{
	tcp_facade::client_config config{
		.host = "127.0.0.1",
		.port = 0,
	};

	auto result = facade_->create_client(config);
	EXPECT_TRUE(result.is_err());
}

// Temporarily disabled: uint16_t conversion makes port validation difficult to test
// Will be re-enabled with proper uint32_t port type or separate validation logic
// TEST_F(TcpFacadeTest, CreateClientThrowsOnInvalidPortTooLarge)

TEST_F(TcpFacadeTest, CreateClientThrowsOnNegativeTimeout)
{
	tcp_facade::client_config config{
		.host = "127.0.0.1",
		.port = 8080,
		.timeout = std::chrono::milliseconds(-1000),
	};

	auto result = facade_->create_client(config);
	EXPECT_TRUE(result.is_err());
}

// ============================================================================
// Server Configuration Validation Tests
// ============================================================================

TEST_F(TcpFacadeTest, CreateServerThrowsOnInvalidPortZero)
{
	tcp_facade::server_config config{
		.port = 0,
	};

	auto result = facade_->create_server(config);
	EXPECT_TRUE(result.is_err());
}

// Temporarily disabled: Server implementation not ready
// TEST_F(TcpFacadeTest, CreateServerThrowsOnInvalidPortTooLarge)

// Server configuration validation tests are temporarily disabled
// Will be re-enabled after messaging_server implements IProtocolServer

// TEST_F(TcpFacadeTest, CreateServerThrowsOnSSLWithoutCert)
// TEST_F(TcpFacadeTest, CreateServerThrowsOnSSLWithoutKey)

// ============================================================================
// Basic Client Creation Tests
// ============================================================================

// Basic client creation tests are temporarily disabled due to lack of server implementation
// Will be re-enabled after messaging_server implements IProtocolServer
// These tests require a running server to connect to

// TEST_F(TcpFacadeTest, CreatePlainClientReturnsNonNull)

// ============================================================================
// Basic Server Creation Tests
// ============================================================================

TEST_F(TcpFacadeTest, CreateServerReturnsNonNull)
{
	tcp_facade::server_config config{
		.port = 8080,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();

	ASSERT_NE(server_, nullptr);
}

TEST_F(TcpFacadeTest, CreateServerWithCustomId)
{
	tcp_facade::server_config config{
		.port = 8080,
		.server_id = "my-custom-server",
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();

	ASSERT_NE(server_, nullptr);
}

TEST_F(TcpFacadeTest, CreateServerWithAutoGeneratedId)
{
	tcp_facade::server_config config{
		.port = 8080,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();

	ASSERT_NE(server_, nullptr);
}

TEST_F(TcpFacadeTest, CreateMultipleServersWithUniqueAutoIds)
{
	tcp_facade::server_config config1{
		.port = 8080,
	};

	tcp_facade::server_config config2{
		.port = 8081,
	};

	auto result1 = facade_->create_server(config1);
	auto result2 = facade_->create_server(config2);

	ASSERT_TRUE(result1.is_ok());
	ASSERT_TRUE(result2.is_ok());
	auto server1 = result1.value();
	auto server2 = result2.value();

	ASSERT_NE(server1, nullptr);
	ASSERT_NE(server2, nullptr);
	EXPECT_NE(server1, server2);

	// Cleanup
	(void)server1->stop();
	(void)server2->stop();
}

TEST_F(TcpFacadeTest, CreateServerSslNotImplemented)
{
	tcp_facade::server_config config{
		.port = 8080,
		.use_ssl = true,
		.cert_path = "/path/to/cert.pem",
		.key_path = "/path/to/key.pem",
	};

	auto result = facade_->create_server(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(TcpFacadeTest, CreateClientSslNotImplemented)
{
	tcp_facade::client_config config{
		.host = "127.0.0.1",
		.port = 8080,
		.use_ssl = true,
	};

	auto result = facade_->create_client(config);
	EXPECT_TRUE(result.is_err());
}

// ============================================================================
// Connection Pool Creation Tests
// ============================================================================

TEST_F(TcpFacadeTest, CreateConnectionPoolReturnsNonNull)
{
	tcp_facade::pool_config config{
		.host = "127.0.0.1",
		.port = 8080,
		.pool_size = 5,
	};

	auto result = facade_->create_connection_pool(config);
	ASSERT_TRUE(result.is_ok());
	auto pool = result.value();

	ASSERT_NE(pool, nullptr);
}

TEST_F(TcpFacadeTest, CreateConnectionPoolThrowsOnEmptyHost)
{
	tcp_facade::pool_config config{
		.host = "",
		.port = 8080,
		.pool_size = 5,
	};

	auto result = facade_->create_connection_pool(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(TcpFacadeTest, CreateConnectionPoolThrowsOnPortZero)
{
	tcp_facade::pool_config config{
		.host = "127.0.0.1",
		.port = 0,
		.pool_size = 5,
	};

	auto result = facade_->create_connection_pool(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(TcpFacadeTest, CreateConnectionPoolThrowsOnPoolSizeZero)
{
	tcp_facade::pool_config config{
		.host = "127.0.0.1",
		.port = 8080,
		.pool_size = 0,
	};

	auto result = facade_->create_connection_pool(config);
	EXPECT_TRUE(result.is_err());
}

// ============================================================================
// Interface Conformance Tests
// ============================================================================

TEST_F(TcpFacadeTest, ServerReturnsProtocolInterface)
{
	tcp_facade::server_config config{
		.port = 8080,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	auto server = result.value();

	// Verify it implements i_protocol_server interface
	ASSERT_NE(server, nullptr);
	// Server has no connections before start()
	EXPECT_EQ(server->connection_count(), 0u);
}

// ============================================================================
// Server Guard Path Tests (pre-start operations)
// ============================================================================

TEST_F(TcpFacadeTest, ConnectionCountZeroBeforeStart)
{
	tcp_facade::server_config config{
		.port = 8080,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();
	ASSERT_NE(server_, nullptr);

	EXPECT_EQ(server_->connection_count(), 0u);
}

TEST_F(TcpFacadeTest, StopServerBeforeStartIsIdempotent)
{
	tcp_facade::server_config config{
		.port = 8080,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();
	ASSERT_NE(server_, nullptr);

	// Stop without start should succeed gracefully
	auto stop_result = server_->stop();
	(void)stop_result;
	SUCCEED();
}

TEST_F(TcpFacadeTest, ServerSetCallbacksBeforeStart)
{
	tcp_facade::server_config config{
		.port = 8080,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();
	ASSERT_NE(server_, nullptr);

	// Setting callbacks before start should not crash
	server_->set_connection_callback([](std::shared_ptr<i_session>) {});
	server_->set_disconnection_callback([](std::string_view) {});
	server_->set_receive_callback([](std::string_view, const std::vector<uint8_t>&) {});
	server_->set_error_callback([](std::string_view, std::error_code) {});

	SUCCEED();
}

// ============================================================================
// SSL Configuration Validation Tests
// ============================================================================

TEST_F(TcpFacadeTest, CreateServerSslWithoutCertReturnsError)
{
	tcp_facade::server_config config{
		.port = 8080,
		.use_ssl = true,
	};

	auto result = facade_->create_server(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(TcpFacadeTest, CreateServerSslWithoutKeyReturnsError)
{
	tcp_facade::server_config config{
		.port = 8080,
		.use_ssl = true,
		.cert_path = "/path/to/cert.pem",
	};

	auto result = facade_->create_server(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(TcpFacadeTest, CreateServerSslWithEmptyCertReturnsError)
{
	tcp_facade::server_config config{
		.port = 8080,
		.use_ssl = true,
		.cert_path = "",
		.key_path = "/path/to/key.pem",
	};

	auto result = facade_->create_server(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(TcpFacadeTest, CreateServerSslWithEmptyKeyReturnsError)
{
	tcp_facade::server_config config{
		.port = 8080,
		.use_ssl = true,
		.cert_path = "/path/to/cert.pem",
		.key_path = "",
	};

	auto result = facade_->create_server(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(TcpFacadeTest, CreateClientWithZeroTimeoutReturnsError)
{
	tcp_facade::client_config config{
		.host = "127.0.0.1",
		.port = 8080,
		.timeout = std::chrono::milliseconds(0),
	};

	auto result = facade_->create_client(config);
	EXPECT_TRUE(result.is_err());
}
