// BSD 3-Clause License
// Copyright (c) 2024, 🍀☀🌕🌥 🌊
// See the LICENSE file in the project root for full license information.

#include <gtest/gtest.h>

#include "kcenon/network/facade/websocket_facade.h"
#include "kcenon/network/interfaces/i_protocol_client.h"
#include "kcenon/network/interfaces/i_protocol_server.h"

#include <chrono>
#include <memory>
#include <string>
#include <thread>
#include <vector>

using namespace kcenon::network::facade;
using namespace kcenon::network::interfaces;

class WebSocketFacadeTest : public ::testing::Test
{
protected:
	void SetUp() override
	{
		facade_ = std::make_unique<websocket_facade>();
	}

	void TearDown() override
	{
		// Cleanup any running clients/servers
		if (client_)
		{
			client_->stop();
		}
		if (server_)
		{
			server_->stop();
		}
	}

	std::unique_ptr<websocket_facade> facade_;
	std::shared_ptr<i_protocol_client> client_;
	std::shared_ptr<i_protocol_server> server_;
};

// ============================================================================
// Client Configuration Validation Tests
// ============================================================================

TEST_F(WebSocketFacadeTest, CreateClientThrowsOnNegativePingInterval)
{
	websocket_facade::client_config config{
		.ping_interval = std::chrono::milliseconds(-1000),
	};

	auto result = facade_->create_client(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(WebSocketFacadeTest, CreateClientThrowsOnZeroPingInterval)
{
	websocket_facade::client_config config{
		.ping_interval = std::chrono::milliseconds(0),
	};

	auto result = facade_->create_client(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(WebSocketFacadeTest, CreateClientWithDefaultPingInterval)
{
	websocket_facade::client_config config{};

	auto result = facade_->create_client(config);
	ASSERT_TRUE(result.is_ok());
	client_ = result.value();

	ASSERT_NE(client_, nullptr);
	EXPECT_FALSE(client_->is_connected());
}

TEST_F(WebSocketFacadeTest, CreateClientWithCustomPingInterval)
{
	websocket_facade::client_config config{
		.ping_interval = std::chrono::seconds(60),
	};

	auto result = facade_->create_client(config);
	ASSERT_TRUE(result.is_ok());
	client_ = result.value();

	ASSERT_NE(client_, nullptr);
	EXPECT_FALSE(client_->is_connected());
}

TEST_F(WebSocketFacadeTest, CreateClientWithCustomClientId)
{
	websocket_facade::client_config config{
		.client_id = "custom_client_123",
	};

	auto result = facade_->create_client(config);
	ASSERT_TRUE(result.is_ok());
	client_ = result.value();

	ASSERT_NE(client_, nullptr);
	// Client is running after successful creation (note: adapter doesn't expose client_id)
}

TEST_F(WebSocketFacadeTest, CreateClientWithAutoGeneratedId)
{
	websocket_facade::client_config config{};

	auto result = facade_->create_client(config);
	ASSERT_TRUE(result.is_ok());
	client_ = result.value();

	ASSERT_NE(client_, nullptr);
}

TEST_F(WebSocketFacadeTest, AutoGeneratedClientIdsAreUnique)
{
	websocket_facade::client_config config1{};
	websocket_facade::client_config config2{};

	auto result1 = facade_->create_client(config1);
	auto result2 = facade_->create_client(config2);

	ASSERT_TRUE(result1.is_ok());
	ASSERT_TRUE(result2.is_ok());
	auto client1 = result1.value();
	auto client2 = result2.value();

	ASSERT_NE(client1, nullptr);
	ASSERT_NE(client2, nullptr);
	// Each client is a distinct object
	EXPECT_NE(client1.get(), client2.get());

	// Cleanup
	client1->stop();
	client2->stop();
}

// ============================================================================
// Server Configuration Validation Tests
// ============================================================================

TEST_F(WebSocketFacadeTest, CreateServerThrowsOnZeroPort)
{
	websocket_facade::server_config config{
		.port = 0,
	};

	auto result = facade_->create_server(config);
	EXPECT_TRUE(result.is_err());
}

// Note: Port range validation is covered by CreateServerThrowsOnZeroPort
// uint16_t naturally limits the maximum port to 65535, so no separate test needed

TEST_F(WebSocketFacadeTest, CreateServerThrowsOnEmptyPath)
{
	websocket_facade::server_config config{
		.port = 8080,
		.path = "",
	};

	auto result = facade_->create_server(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(WebSocketFacadeTest, CreateServerThrowsOnPathWithoutLeadingSlash)
{
	websocket_facade::server_config config{
		.port = 8080,
		.path = "ws",
	};

	auto result = facade_->create_server(config);
	EXPECT_TRUE(result.is_err());
}

TEST_F(WebSocketFacadeTest, CreateServerWithDefaultPath)
{
	websocket_facade::server_config config{
		.port = 8080,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();

	ASSERT_NE(server_, nullptr);
	// Server is not running until start() is called
}

TEST_F(WebSocketFacadeTest, CreateServerWithCustomPath)
{
	websocket_facade::server_config config{
		.port = 8080,
		.path = "/custom/path",
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();

	ASSERT_NE(server_, nullptr);
}

TEST_F(WebSocketFacadeTest, CreateServerWithCustomServerId)
{
	websocket_facade::server_config config{
		.port = 8080,
		.server_id = "custom_server_123",
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();

	ASSERT_NE(server_, nullptr);
}

TEST_F(WebSocketFacadeTest, CreateServerWithAutoGeneratedId)
{
	websocket_facade::server_config config{
		.port = 8080,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();

	ASSERT_NE(server_, nullptr);
}

TEST_F(WebSocketFacadeTest, AutoGeneratedServerIdsAreUnique)
{
	websocket_facade::server_config config1{
		.port = 8080,
	};
	websocket_facade::server_config config2{
		.port = 8081,
	};

	auto result1 = facade_->create_server(config1);
	auto result2 = facade_->create_server(config2);

	ASSERT_TRUE(result1.is_ok());
	ASSERT_TRUE(result2.is_ok());
	auto server1 = result1.value();
	auto server2 = result2.value();

	ASSERT_NE(server1, nullptr);
	ASSERT_NE(server2, nullptr);
	// Each server is a distinct object
	EXPECT_NE(server1.get(), server2.get());

	// Cleanup
	server1->stop();
	server2->stop();
}

// ============================================================================
// Type Safety Tests
// ============================================================================

TEST_F(WebSocketFacadeTest, CreateClientReturnsProtocolClientInterface)
{
	websocket_facade::client_config config{};

	auto result = facade_->create_client(config);
	ASSERT_TRUE(result.is_ok());
	auto client = result.value();

	// Verify it's a valid i_protocol_client
	ASSERT_NE(client, nullptr);
	// Verify interface methods are accessible
	EXPECT_FALSE(client->is_connected());
	EXPECT_FALSE(client->is_connected());

	client->stop();
}

TEST_F(WebSocketFacadeTest, CreateServerReturnsProtocolServerInterface)
{
	websocket_facade::server_config config{
		.port = 8080,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	auto server = result.value();

	// Verify it's a valid i_protocol_server
	ASSERT_NE(server, nullptr);
	// Verify interface methods are accessible
	EXPECT_EQ(server->connection_count(), 0);

	server->stop();
}

// ============================================================================
// Edge Cases and Boundary Tests
// ============================================================================

TEST_F(WebSocketFacadeTest, CreateServerWithMinimalValidPort)
{
	websocket_facade::server_config config{
		.port = 1,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();

	ASSERT_NE(server_, nullptr);
}

TEST_F(WebSocketFacadeTest, CreateServerWithMaximalValidPort)
{
	websocket_facade::server_config config{
		.port = 65535,
	};

	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();

	ASSERT_NE(server_, nullptr);
}

TEST_F(WebSocketFacadeTest, CreateClientWithMinimalValidPingInterval)
{
	websocket_facade::client_config config{
		.ping_interval = std::chrono::milliseconds(1),
	};

	auto result = facade_->create_client(config);
	ASSERT_TRUE(result.is_ok());
	client_ = result.value();

	ASSERT_NE(client_, nullptr);
	EXPECT_FALSE(client_->is_connected());
}

TEST_F(WebSocketFacadeTest, CreateClientWithLargePingInterval)
{
	websocket_facade::client_config config{
		.ping_interval = std::chrono::hours(1),
	};

	auto result = facade_->create_client(config);
	ASSERT_TRUE(result.is_ok());
	client_ = result.value();

	ASSERT_NE(client_, nullptr);
	EXPECT_FALSE(client_->is_connected());
}

// ============================================================================
// Client Guard Path Tests (unconnected operations)
// ============================================================================

TEST_F(WebSocketFacadeTest, SendOnUnconnectedClientReturnsError)
{
	websocket_facade::client_config config{};
	auto result = facade_->create_client(config);
	ASSERT_TRUE(result.is_ok());
	client_ = result.value();
	ASSERT_NE(client_, nullptr);

	// Sending data when not connected should fail
	std::vector<uint8_t> data = {0x01, 0x02, 0x03};
	auto send_result = client_->send(std::move(data));
	EXPECT_TRUE(send_result.is_err());
}

TEST_F(WebSocketFacadeTest, IsConnectedReturnsFalseBeforeStart)
{
	websocket_facade::client_config config{};
	auto result = facade_->create_client(config);
	ASSERT_TRUE(result.is_ok());
	client_ = result.value();
	ASSERT_NE(client_, nullptr);

	EXPECT_FALSE(client_->is_connected());
}

TEST_F(WebSocketFacadeTest, StopClientBeforeStartIsIdempotent)
{
	websocket_facade::client_config config{};
	auto result = facade_->create_client(config);
	ASSERT_TRUE(result.is_ok());
	client_ = result.value();
	ASSERT_NE(client_, nullptr);

	// Stop without start should not crash or throw
	EXPECT_NO_THROW(client_->stop());
}

// ============================================================================
// Server Guard Path Tests (pre-start operations)
// ============================================================================

TEST_F(WebSocketFacadeTest, ConnectionCountZeroBeforeStart)
{
	websocket_facade::server_config config{
		.port = 8080,
	};
	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();
	ASSERT_NE(server_, nullptr);

	EXPECT_EQ(server_->connection_count(), 0u);
}

TEST_F(WebSocketFacadeTest, StopServerBeforeStartIsIdempotent)
{
	websocket_facade::server_config config{
		.port = 8080,
	};
	auto result = facade_->create_server(config);
	ASSERT_TRUE(result.is_ok());
	server_ = result.value();
	ASSERT_NE(server_, nullptr);

	// Stop without start should succeed gracefully
	EXPECT_NO_THROW(server_->stop());
}

