// BSD 3-Clause License
// Copyright (c) 2024, 🍀☀🌕🌥 🌊
// See the LICENSE file in the project root for full license information.

#include <gtest/gtest.h>

#include "kcenon/network/facade/http_facade.h"
#include "kcenon/network/interfaces/i_protocol_client.h"
#include "kcenon/network/interfaces/i_protocol_server.h"

#include <chrono>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>

using namespace kcenon::network::facade;
using namespace kcenon::network::interfaces;

class HttpFacadeTest : public ::testing::Test
{
protected:
	void SetUp() override
	{
		facade_ = std::make_unique<http_facade>();
	}

	void TearDown() override
	{
		if (server_)
		{
			(void)server_->stop();
		}
	}

	std::unique_ptr<http_facade> facade_;
	std::shared_ptr<i_protocol_client> client_;
	std::shared_ptr<i_protocol_server> server_;
};

// ============================================================================
// Client Configuration Validation Tests
// ============================================================================

TEST_F(HttpFacadeTest, CreateClientThrowsOnNegativeTimeout)
{
	http_facade::client_config config{
		.timeout = std::chrono::milliseconds(-1000),
	};

	EXPECT_THROW(facade_->create_client(config), std::invalid_argument);
}

TEST_F(HttpFacadeTest, CreateClientThrowsOnZeroTimeout)
{
	http_facade::client_config config{
		.timeout = std::chrono::milliseconds(0),
	};

	EXPECT_THROW(facade_->create_client(config), std::invalid_argument);
}

TEST_F(HttpFacadeTest, CreateClientWithDefaultTimeout)
{
	http_facade::client_config config{};

	client_ = facade_->create_client(config);

	ASSERT_NE(client_, nullptr);
	// Note: Can't access get_timeout() through i_protocol_client interface
	// The timeout is configured internally in the adapter
}

TEST_F(HttpFacadeTest, CreateClientWithCustomTimeout)
{
	http_facade::client_config config{
		.timeout = std::chrono::seconds(10),
	};

	client_ = facade_->create_client(config);

	ASSERT_NE(client_, nullptr);
	// Note: Can't access get_timeout() through i_protocol_client interface
	// The timeout is configured internally in the adapter
}

// ============================================================================
// Server Configuration Validation Tests
// ============================================================================

TEST_F(HttpFacadeTest, CreateServerThrowsOnInvalidPortZero)
{
	http_facade::server_config config{
		.port = 0,
	};

	EXPECT_THROW(facade_->create_server(config), std::invalid_argument);
}

TEST_F(HttpFacadeTest, CreateServerWithAutoGeneratedId)
{
	http_facade::server_config config{
		.port = 8080,
	};

	server_ = facade_->create_server(config);

	ASSERT_NE(server_, nullptr);
}

TEST_F(HttpFacadeTest, CreateServerWithCustomId)
{
	http_facade::server_config config{
		.port = 8080,
		.server_id = "my-custom-server",
	};

	server_ = facade_->create_server(config);

	ASSERT_NE(server_, nullptr);
}

TEST_F(HttpFacadeTest, CreateMultipleServersWithUniqueAutoIds)
{
	http_facade::server_config config1{
		.port = 8080,
	};

	http_facade::server_config config2{
		.port = 8081,
	};

	auto server1 = facade_->create_server(config1);
	auto server2 = facade_->create_server(config2);

	ASSERT_NE(server1, nullptr);
	ASSERT_NE(server2, nullptr);
	EXPECT_NE(server1, server2);
}

// ============================================================================
// Basic Client Creation Tests
// ============================================================================

TEST_F(HttpFacadeTest, CreateClientReturnsNonNull)
{
	http_facade::client_config config{};

	client_ = facade_->create_client(config);

	ASSERT_NE(client_, nullptr);
}

TEST_F(HttpFacadeTest, CreateMultipleClients)
{
	http_facade::client_config config{};

	auto client1 = facade_->create_client(config);
	auto client2 = facade_->create_client(config);

	ASSERT_NE(client1, nullptr);
	ASSERT_NE(client2, nullptr);
	EXPECT_NE(client1, client2);
}

// ============================================================================
// Basic Server Creation Tests
// ============================================================================

TEST_F(HttpFacadeTest, CreateServerReturnsNonNull)
{
	http_facade::server_config config{
		.port = 8080,
	};

	server_ = facade_->create_server(config);

	ASSERT_NE(server_, nullptr);
}

TEST_F(HttpFacadeTest, CreateServerWithValidPort)
{
	http_facade::server_config config{
		.port = 8080,
	};

	EXPECT_NO_THROW(server_ = facade_->create_server(config));
	ASSERT_NE(server_, nullptr);
}

// ============================================================================
// Interface Conformance Tests
// ============================================================================

TEST_F(HttpFacadeTest, ClientReturnsProtocolInterface)
{
	http_facade::client_config config{};

	auto client = facade_->create_client(config);

	// Verify it implements i_protocol_client interface
	ASSERT_NE(client, nullptr);
	// Client is not connected before start() is called
	EXPECT_FALSE(client->is_connected());
}

TEST_F(HttpFacadeTest, ServerReturnsProtocolInterface)
{
	http_facade::server_config config{
		.port = 8080,
	};

	auto server = facade_->create_server(config);

	// Verify it implements i_protocol_server interface
	ASSERT_NE(server, nullptr);
	// Server has no connections before start()
	EXPECT_EQ(server->connection_count(), 0u);
}

// ============================================================================
// Client Guard Path Tests (unconnected operations)
// ============================================================================

TEST_F(HttpFacadeTest, SendOnUnconnectedClientReturnsError)
{
	http_facade::client_config config{};
	client_ = facade_->create_client(config);
	ASSERT_NE(client_, nullptr);

	// Sending data when not connected should fail
	std::vector<uint8_t> data = {0x01, 0x02, 0x03};
	auto result = client_->send(std::move(data));
	EXPECT_TRUE(result.is_err());
}

TEST_F(HttpFacadeTest, IsConnectedReturnsFalseBeforeStart)
{
	http_facade::client_config config{};
	client_ = facade_->create_client(config);
	ASSERT_NE(client_, nullptr);

	EXPECT_FALSE(client_->is_connected());
}

TEST_F(HttpFacadeTest, StopClientBeforeStartIsIdempotent)
{
	http_facade::client_config config{};
	client_ = facade_->create_client(config);
	ASSERT_NE(client_, nullptr);

	// Stop without start should not crash or throw
	auto result = client_->stop();
	// Either ok or graceful error - just shouldn't crash
	(void)result;
	SUCCEED();
}

// ============================================================================
// Server Guard Path Tests (pre-start operations)
// ============================================================================

TEST_F(HttpFacadeTest, ConnectionCountZeroBeforeStart)
{
	http_facade::server_config config{
		.port = 8080,
	};
	server_ = facade_->create_server(config);
	ASSERT_NE(server_, nullptr);

	EXPECT_EQ(server_->connection_count(), 0u);
}

TEST_F(HttpFacadeTest, StopServerBeforeStartIsIdempotent)
{
	http_facade::server_config config{
		.port = 8080,
	};
	server_ = facade_->create_server(config);
	ASSERT_NE(server_, nullptr);

	// Stop without start should succeed gracefully
	auto result = server_->stop();
	(void)result;
	SUCCEED();
}

