/*****************************************************************************
BSD 3-Clause License

Copyright (c) 2024, 🍀☀🌕🌥 🌊
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*****************************************************************************/

#include <gtest/gtest.h>

#include "kcenon/network/facade/websocket_facade.h"
#include "kcenon/network/http/websocket_client.h"
#include "kcenon/network/http/websocket_server.h"

#include <chrono>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>

using namespace kcenon::network::facade;
using namespace kcenon::network::core;
using namespace kcenon::network::internal;

class WebSocketFacadeTest : public ::testing::Test
{
protected:
	void SetUp() override
	{
		facade_ = std::make_unique<websocket_facade>();
	}

	void TearDown() override
	{
		if (server_)
		{
			server_->stop_server();
		}
		if (client_)
		{
			client_->stop_client();
		}
	}

	std::unique_ptr<websocket_facade> facade_;
	std::shared_ptr<messaging_ws_client> client_;
	std::shared_ptr<messaging_ws_server> server_;
};

// ============================================================================
// Client Configuration Validation Tests
// ============================================================================

TEST_F(WebSocketFacadeTest, CreateClientThrowsOnNegativePingInterval)
{
	websocket_facade::client_config config{
		.ping_interval = std::chrono::milliseconds(-1000),
	};

	EXPECT_THROW(facade_->create_client(config), std::invalid_argument);
}

TEST_F(WebSocketFacadeTest, CreateClientThrowsOnZeroPingInterval)
{
	websocket_facade::client_config config{
		.ping_interval = std::chrono::milliseconds(0),
	};

	EXPECT_THROW(facade_->create_client(config), std::invalid_argument);
}

TEST_F(WebSocketFacadeTest, CreateClientWithDefaultPingInterval)
{
	websocket_facade::client_config config{};

	client_ = facade_->create_client(config);

	ASSERT_NE(client_, nullptr);
	EXPECT_FALSE(client_->is_running());
}

TEST_F(WebSocketFacadeTest, CreateClientWithCustomPingInterval)
{
	websocket_facade::client_config config{
		.ping_interval = std::chrono::seconds(60),
	};

	client_ = facade_->create_client(config);

	ASSERT_NE(client_, nullptr);
	EXPECT_FALSE(client_->is_running());
}

TEST_F(WebSocketFacadeTest, CreateClientWithCustomClientId)
{
	websocket_facade::client_config config{
		.client_id = "custom_client_123",
	};

	client_ = facade_->create_client(config);

	ASSERT_NE(client_, nullptr);
	EXPECT_EQ(client_->client_id(), "custom_client_123");
}

TEST_F(WebSocketFacadeTest, CreateClientWithAutoGeneratedId)
{
	websocket_facade::client_config config{};

	client_ = facade_->create_client(config);

	ASSERT_NE(client_, nullptr);
	EXPECT_FALSE(client_->client_id().empty());
	EXPECT_EQ(client_->client_id().substr(0, 10), "ws_client_");
}

TEST_F(WebSocketFacadeTest, AutoGeneratedClientIdsAreUnique)
{
	websocket_facade::client_config config1{};
	websocket_facade::client_config config2{};

	auto client1 = facade_->create_client(config1);
	auto client2 = facade_->create_client(config2);

	ASSERT_NE(client1, nullptr);
	ASSERT_NE(client2, nullptr);
	EXPECT_NE(client1->client_id(), client2->client_id());
}

// ============================================================================
// Server Configuration Validation Tests
// ============================================================================

TEST_F(WebSocketFacadeTest, CreateServerThrowsOnZeroPort)
{
	websocket_facade::server_config config{
		.port = 0,
	};

	EXPECT_THROW(facade_->create_server(config), std::invalid_argument);
}

// Note: Port range validation is covered by CreateServerThrowsOnZeroPort
// uint16_t naturally limits the maximum port to 65535, so no separate test needed

TEST_F(WebSocketFacadeTest, CreateServerThrowsOnEmptyPath)
{
	websocket_facade::server_config config{
		.port = 8080,
		.path = "",
	};

	EXPECT_THROW(facade_->create_server(config), std::invalid_argument);
}

TEST_F(WebSocketFacadeTest, CreateServerThrowsOnPathWithoutLeadingSlash)
{
	websocket_facade::server_config config{
		.port = 8080,
		.path = "ws",
	};

	EXPECT_THROW(facade_->create_server(config), std::invalid_argument);
}

TEST_F(WebSocketFacadeTest, CreateServerWithDefaultPath)
{
	websocket_facade::server_config config{
		.port = 8080,
	};

	server_ = facade_->create_server(config);

	ASSERT_NE(server_, nullptr);
	EXPECT_FALSE(server_->is_running());
}

TEST_F(WebSocketFacadeTest, CreateServerWithCustomPath)
{
	websocket_facade::server_config config{
		.port = 8080,
		.path = "/custom/path",
	};

	server_ = facade_->create_server(config);

	ASSERT_NE(server_, nullptr);
	EXPECT_FALSE(server_->is_running());
}

TEST_F(WebSocketFacadeTest, CreateServerWithCustomServerId)
{
	websocket_facade::server_config config{
		.port = 8080,
		.server_id = "custom_server_123",
	};

	server_ = facade_->create_server(config);

	ASSERT_NE(server_, nullptr);
	EXPECT_EQ(server_->server_id(), "custom_server_123");
}

TEST_F(WebSocketFacadeTest, CreateServerWithAutoGeneratedId)
{
	websocket_facade::server_config config{
		.port = 8080,
	};

	server_ = facade_->create_server(config);

	ASSERT_NE(server_, nullptr);
	EXPECT_FALSE(server_->server_id().empty());
	EXPECT_EQ(server_->server_id().substr(0, 10), "ws_server_");
}

TEST_F(WebSocketFacadeTest, AutoGeneratedServerIdsAreUnique)
{
	websocket_facade::server_config config1{
		.port = 8080,
	};
	websocket_facade::server_config config2{
		.port = 8081,
	};

	auto server1 = facade_->create_server(config1);
	auto server2 = facade_->create_server(config2);

	ASSERT_NE(server1, nullptr);
	ASSERT_NE(server2, nullptr);
	EXPECT_NE(server1->server_id(), server2->server_id());
}

// ============================================================================
// Type Safety Tests
// ============================================================================

TEST_F(WebSocketFacadeTest, CreateClientReturnsCorrectType)
{
	websocket_facade::client_config config{};

	auto client = facade_->create_client(config);

	// Verify correct type
	ASSERT_NE(dynamic_cast<messaging_ws_client*>(client.get()), nullptr);
}

TEST_F(WebSocketFacadeTest, CreateServerReturnsCorrectType)
{
	websocket_facade::server_config config{
		.port = 8080,
	};

	auto server = facade_->create_server(config);

	// Verify correct type
	ASSERT_NE(dynamic_cast<messaging_ws_server*>(server.get()), nullptr);
}

// ============================================================================
// Edge Cases and Boundary Tests
// ============================================================================

TEST_F(WebSocketFacadeTest, CreateServerWithMinimalValidPort)
{
	websocket_facade::server_config config{
		.port = 1,
	};

	server_ = facade_->create_server(config);

	ASSERT_NE(server_, nullptr);
	EXPECT_EQ(server_->server_id().substr(0, 10), "ws_server_");
}

TEST_F(WebSocketFacadeTest, CreateServerWithMaximalValidPort)
{
	websocket_facade::server_config config{
		.port = 65535,
	};

	server_ = facade_->create_server(config);

	ASSERT_NE(server_, nullptr);
	EXPECT_EQ(server_->server_id().substr(0, 10), "ws_server_");
}

TEST_F(WebSocketFacadeTest, CreateClientWithMinimalValidPingInterval)
{
	websocket_facade::client_config config{
		.ping_interval = std::chrono::milliseconds(1),
	};

	client_ = facade_->create_client(config);

	ASSERT_NE(client_, nullptr);
	EXPECT_FALSE(client_->is_running());
}

TEST_F(WebSocketFacadeTest, CreateClientWithLargePingInterval)
{
	websocket_facade::client_config config{
		.ping_interval = std::chrono::hours(1),
	};

	client_ = facade_->create_client(config);

	ASSERT_NE(client_, nullptr);
	EXPECT_FALSE(client_->is_running());
}
