name: 'Setup thread_system'
description: 'Install thread_system for network_system builds'
outputs:
  include_dir:
    description: 'thread_system include directory'
    value: ${{ steps.install-unix.outputs.include_dir || steps.install-windows.outputs.include_dir }}
  library:
    description: 'thread_system library path'
    value: ${{ steps.install-unix.outputs.library || steps.install-windows.outputs.library }}
runs:
  using: 'composite'
  steps:
    - name: Install thread_system (Unix)
      id: install-unix
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # Use modern compilers on Linux for C++20 std::format support
        # Default to GCC-13, can be overridden by CC/CXX environment variables
        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
          if [ -z "$CC" ]; then
            # Check if GCC-13 is available, otherwise use Clang-15
            if command -v gcc-13 &> /dev/null; then
              export CC=gcc-13
              export CXX=g++-13
            elif command -v clang-15 &> /dev/null; then
              export CC=clang-15
              export CXX=clang++-15
            fi
          fi
        fi

        git clone https://github.com/kcenon/thread_system.git /tmp/thread_system
        cd /tmp/thread_system
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        sudo cmake --install build --prefix /usr/local
        echo "include_dir=/usr/local/include" >> $GITHUB_OUTPUT
        echo "library=/usr/local/lib/libThreadSystem.a" >> $GITHUB_OUTPUT
        echo "THREAD_SYSTEM_INCLUDE_DIR=/usr/local/include" >> $GITHUB_ENV
        echo "THREAD_SYSTEM_LIBRARY=/usr/local/lib/libThreadSystem.a" >> $GITHUB_ENV

    - name: Install thread_system (Windows)
      id: install-windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        git clone https://github.com/kcenon/thread_system.git C:\temp\thread_system
        cd C:\temp\thread_system
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake --install build --prefix C:\thread_system

        # List installed files to verify actual library name
        Write-Host "Installed files in C:\thread_system\lib:"
        Get-ChildItem C:\thread_system\lib -Recurse | Select-Object FullName

        # Check for both possible library names
        $libPath = ""
        if (Test-Path "C:\thread_system\lib\ThreadSystem.lib") {
          $libPath = "C:\thread_system\lib\ThreadSystem.lib"
        } elseif (Test-Path "C:\thread_system\lib\thread_system.lib") {
          $libPath = "C:\thread_system\lib\thread_system.lib"
        } else {
          Write-Error "thread_system library not found!"
          exit 1
        }

        Write-Host "Using library: $libPath"

        echo "include_dir=C:\thread_system\include" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "library=$libPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "THREAD_SYSTEM_INCLUDE_DIR=C:\thread_system\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "THREAD_SYSTEM_LIBRARY=$libPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
