name: 'Setup thread_system'
description: 'Install thread_system for network_system builds'
outputs:
  include_dir:
    description: 'thread_system include directory'
    value: ${{ steps.install-unix.outputs.include_dir || steps.install-windows.outputs.include_dir }}
  library:
    description: 'thread_system library path'
    value: ${{ steps.install-unix.outputs.library || steps.install-windows.outputs.library }}
runs:
  using: 'composite'
  steps:
    - name: Build thread_system (Unix)
      id: install-unix
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # Use modern compilers for C++20 std::format support
        # Respect CC/CXX if already set, otherwise auto-detect
        if [ -z "$CC" ]; then
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            # Linux: prefer GCC-13, fallback to Clang-15
            if command -v gcc-13 &> /dev/null; then
              export CC=gcc-13
              export CXX=g++-13
              echo "Auto-selected GCC-13 for Linux"
            elif command -v clang-15 &> /dev/null; then
              export CC=clang-15
              export CXX=clang++-15
              echo "Auto-selected Clang-15 for Linux"
            fi
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS: use system Clang (avoid LLVM libc++ conflicts with Xcode SDK)
            export CC=clang
            export CXX=clang++
            echo "Using system Clang for macOS (Xcode compatibility)"
          fi
        else
          echo "Using pre-set compilers: CC=$CC, CXX=$CXX"
        fi

        # Clone and build thread_system (no install - use build tree directly)
        echo "=== Cloning thread_system ==="
        # Use specific commit before PR #80 which has compilation issues
        # Commit 159e0a0: Sprint 2: Implement Hazard Pointers and Lock-free MPMC Queue
        git clone https://github.com/kcenon/thread_system.git /tmp/thread_system
        cd /tmp/thread_system
        git checkout 159e0a0a7ea44e5fc10c91f1f8cd83aecd6e63f5

        # Show current commit info
        echo "thread_system commit: $(git rev-parse --short HEAD)"
        echo "Commit date: $(git log -1 --format=%cd)"
        echo "Commit message: $(git log -1 --format=%s)"

        echo "=== Building thread_system with CC=$CC, CXX=$CXX ==="
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTS=OFF \
          -DBUILD_EXAMPLES=OFF
        cmake --build build --parallel

        # Verify library was built
        if [ ! -f "build/lib/libThreadSystem.a" ]; then
          echo "ERROR: thread_system library not found after build!"
          ls -R build/
          exit 1
        fi

        echo "=== thread_system build successful ==="
        ls -lh build/lib/libThreadSystem.a

        # Export build tree paths (no install needed)
        echo "source_dir=/tmp/thread_system" >> $GITHUB_OUTPUT
        echo "include_dir=/tmp/thread_system/include" >> $GITHUB_OUTPUT
        echo "build_dir=/tmp/thread_system/build" >> $GITHUB_OUTPUT
        echo "library=/tmp/thread_system/build/lib/libThreadSystem.a" >> $GITHUB_OUTPUT

        # Set environment variables for network_system CMake
        echo "THREAD_SYSTEM_SOURCE_DIR=/tmp/thread_system" >> $GITHUB_ENV
        echo "THREAD_SYSTEM_INCLUDE_DIR=/tmp/thread_system/include" >> $GITHUB_ENV
        echo "THREAD_SYSTEM_BUILD_DIR=/tmp/thread_system/build" >> $GITHUB_ENV
        echo "THREAD_SYSTEM_LIBRARY=/tmp/thread_system/build/lib/libThreadSystem.a" >> $GITHUB_ENV

    - name: Build thread_system (Windows)
      id: install-windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Clone and build thread_system (no install - use build tree directly)
        Write-Host "=== Cloning thread_system ==="
        # Use specific commit before PR #80 which has compilation issues
        # Commit 159e0a0: Sprint 2: Implement Hazard Pointers and Lock-free MPMC Queue
        git clone https://github.com/kcenon/thread_system.git C:\temp\thread_system
        cd C:\temp\thread_system
        git checkout 159e0a0a7ea44e5fc10c91f1f8cd83aecd6e63f5

        # Show current commit info
        $commitHash = git rev-parse --short HEAD
        $commitDate = git log -1 --format=%cd
        $commitMsg = git log -1 --format=%s
        Write-Host "thread_system commit: $commitHash"
        Write-Host "Commit date: $commitDate"
        Write-Host "Commit message: $commitMsg"

        Write-Host "`n=== Building thread_system ==="
        cmake -B build -G Ninja `
          -DCMAKE_BUILD_TYPE=Release `
          -DBUILD_TESTS=OFF `
          -DBUILD_EXAMPLES=OFF

        if ($LASTEXITCODE -ne 0) {
          Write-Error "CMake configuration failed!"
          exit 1
        }

        cmake --build build --parallel

        if ($LASTEXITCODE -ne 0) {
          Write-Error "thread_system build failed!"
          exit 1
        }

        # Find library in build directory
        Write-Host "`n=== Searching for library in build tree ==="
        $libFiles = Get-ChildItem -Path "C:\temp\thread_system\build" -Recurse -Include "*.lib","*.a" | Where-Object { $_.Name -match "Thread" }

        if ($libFiles.Count -eq 0) {
          Write-Error "No thread_system library found in build directory!"
          Get-ChildItem C:\temp\thread_system\build -Recurse | Select-Object FullName
          exit 1
        }

        # Use the first found library (prefer .lib over .a)
        $libPath = ($libFiles | Sort-Object { if ($_.Extension -eq ".lib") { 0 } else { 1 } })[0].FullName
        Write-Host "=== thread_system build successful ==="
        Write-Host "Found library: $libPath"

        # Export build tree paths
        echo "source_dir=C:\temp\thread_system" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "include_dir=C:\temp\thread_system\include" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "build_dir=C:\temp\thread_system\build" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "library=$libPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

        # Set environment variables for network_system CMake
        echo "THREAD_SYSTEM_SOURCE_DIR=C:\temp\thread_system" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "THREAD_SYSTEM_INCLUDE_DIR=C:\temp\thread_system\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "THREAD_SYSTEM_BUILD_DIR=C:\temp\thread_system\build" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "THREAD_SYSTEM_LIBRARY=$libPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        Write-Host "`n=== Environment variables set ==="
        Write-Host "THREAD_SYSTEM_SOURCE_DIR=C:\temp\thread_system"
        Write-Host "THREAD_SYSTEM_INCLUDE_DIR=C:\temp\thread_system\include"
        Write-Host "THREAD_SYSTEM_BUILD_DIR=C:\temp\thread_system\build"
        Write-Host "THREAD_SYSTEM_LIBRARY=$libPath"
