name: 'Setup thread_system'
description: 'Install thread_system for network_system builds'
outputs:
  include_dir:
    description: 'thread_system include directory'
    value: ${{ steps.install-unix.outputs.include_dir || steps.install-windows.outputs.include_dir }}
  library:
    description: 'thread_system library path'
    value: ${{ steps.install-unix.outputs.library || steps.install-windows.outputs.library }}
runs:
  using: 'composite'
  steps:
    - name: Install thread_system (Unix)
      id: install-unix
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # Use modern compilers for C++20 std::format support
        # Respect CC/CXX if already set, otherwise auto-detect
        if [ -z "$CC" ]; then
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            # Linux: prefer GCC-13, fallback to Clang-15
            if command -v gcc-13 &> /dev/null; then
              export CC=gcc-13
              export CXX=g++-13
              echo "Auto-selected GCC-13 for Linux"
            elif command -v clang-15 &> /dev/null; then
              export CC=clang-15
              export CXX=clang++-15
              echo "Auto-selected Clang-15 for Linux"
            fi
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS: use LLVM 15 from Homebrew if available
            if [ -x "/usr/local/opt/llvm@15/bin/clang" ]; then
              export CC=/usr/local/opt/llvm@15/bin/clang
              export CXX=/usr/local/opt/llvm@15/bin/clang++
              echo "Auto-selected LLVM 15 from /usr/local/opt for macOS"
            elif [ -x "/opt/homebrew/opt/llvm@15/bin/clang" ]; then
              export CC=/opt/homebrew/opt/llvm@15/bin/clang
              export CXX=/opt/homebrew/opt/llvm@15/bin/clang++
              echo "Auto-selected LLVM 15 from /opt/homebrew for macOS"
            fi
          fi
        else
          echo "Using pre-set compilers: CC=$CC, CXX=$CXX"
        fi

        git clone https://github.com/kcenon/thread_system.git /tmp/thread_system
        cd /tmp/thread_system

        echo "Building thread_system with CC=$CC, CXX=$CXX"
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        sudo cmake --install build --prefix /usr/local
        echo "include_dir=/usr/local/include" >> $GITHUB_OUTPUT
        echo "library=/usr/local/lib/libThreadSystem.a" >> $GITHUB_OUTPUT
        echo "THREAD_SYSTEM_INCLUDE_DIR=/usr/local/include" >> $GITHUB_ENV
        echo "THREAD_SYSTEM_LIBRARY=/usr/local/lib/libThreadSystem.a" >> $GITHUB_ENV

    - name: Install thread_system (Windows)
      id: install-windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        git clone https://github.com/kcenon/thread_system.git C:\temp\thread_system
        cd C:\temp\thread_system
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake --install build --prefix C:\thread_system

        # Debug: Show installation directory structure
        Write-Host "=== Installation directory structure ==="
        Get-ChildItem C:\thread_system -Recurse | Select-Object FullName

        # Find library file with flexible search
        Write-Host "`n=== Searching for library files ==="
        $libFiles = Get-ChildItem -Path C:\thread_system -Recurse -Include "*.lib","*.a" | Where-Object { $_.Name -match "thread" }

        if ($libFiles.Count -eq 0) {
          Write-Error "No thread_system library files found!"
          exit 1
        }

        # Use the first found library (prefer .lib over .a)
        $libPath = ($libFiles | Sort-Object { if ($_.Extension -eq ".lib") { 0 } else { 1 } })[0].FullName
        Write-Host "Found library: $libPath"

        # Verify include directory exists
        if (-not (Test-Path "C:\thread_system\include")) {
          Write-Error "Include directory not found at C:\thread_system\include"
          exit 1
        }

        echo "include_dir=C:\thread_system\include" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "library=$libPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "THREAD_SYSTEM_INCLUDE_DIR=C:\thread_system\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "THREAD_SYSTEM_LIBRARY=$libPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        Write-Host "`n=== Environment variables set ==="
        Write-Host "THREAD_SYSTEM_INCLUDE_DIR=C:\thread_system\include"
        Write-Host "THREAD_SYSTEM_LIBRARY=$libPath"
