/*****************************************************************************
BSD 3-Clause License

Copyright (c) 2025, 🍀☀🌕🌥 🌊
All rights reserved.
*****************************************************************************/

#include "kcenon/network/detail/protocol/quic.h"
#include <gtest/gtest.h>

#include <chrono>
#include <memory>
#include <string>

namespace quic = kcenon::network::protocol::quic;
namespace unified = kcenon::network::unified;

/**
 * @file protocol_quic_factory_test.cpp
 * @brief Unit tests for QUIC protocol factory functions
 *
 * Tests validate:
 * - quic_config default values
 * - quic_config custom values
 * - create_connection() returns valid i_connection
 * - create_connection() with custom config and id
 * - create_connection() generates unique ids
 * - create_listener() returns valid i_listener
 * - connect() convenience overloads (endpoint, URL)
 * - listen() convenience overloads (endpoint, port)
 */

// ============================================================================
// quic_config Tests
// ============================================================================

class QuicConfigTest : public ::testing::Test
{
};

TEST_F(QuicConfigTest, DefaultValues)
{
	quic::quic_config config;

	EXPECT_TRUE(config.server_name.empty());
	EXPECT_TRUE(config.cert_file.empty());
	EXPECT_TRUE(config.key_file.empty());
	EXPECT_TRUE(config.alpn_protocols.empty());
	EXPECT_EQ(config.idle_timeout, std::chrono::milliseconds(0));
	EXPECT_EQ(config.max_bidi_streams, 100u);
	EXPECT_EQ(config.max_uni_streams, 100u);
	EXPECT_EQ(config.initial_max_data, 10u * 1024u * 1024u);
	EXPECT_EQ(config.initial_max_stream_data_bidi, 1024u * 1024u);
	EXPECT_EQ(config.initial_max_stream_data_uni, 1024u * 1024u);
	EXPECT_FALSE(config.enable_early_data);
	EXPECT_TRUE(config.enable_pmtud);
	EXPECT_FALSE(config.insecure_skip_verify);
}

TEST_F(QuicConfigTest, CustomValues)
{
	quic::quic_config config;
	config.server_name = "example.com";
	config.cert_file = "/path/to/cert.pem";
	config.key_file = "/path/to/key.pem";
	config.alpn_protocols = {"h3"};
	config.idle_timeout = std::chrono::milliseconds(30000);
	config.max_bidi_streams = 50;
	config.enable_early_data = true;
	config.insecure_skip_verify = true;

	EXPECT_EQ(config.server_name, "example.com");
	EXPECT_EQ(config.cert_file, "/path/to/cert.pem");
	EXPECT_EQ(config.alpn_protocols.size(), 1u);
	EXPECT_EQ(config.alpn_protocols[0], "h3");
	EXPECT_EQ(config.idle_timeout, std::chrono::milliseconds(30000));
	EXPECT_EQ(config.max_bidi_streams, 50u);
	EXPECT_TRUE(config.enable_early_data);
	EXPECT_TRUE(config.insecure_skip_verify);
}

// ============================================================================
// create_connection Tests
// ============================================================================

class QuicCreateConnectionTest : public ::testing::Test
{
};

TEST_F(QuicCreateConnectionTest, ReturnsNonNull)
{
	auto conn = quic::create_connection();

	ASSERT_NE(conn, nullptr);
}

TEST_F(QuicCreateConnectionTest, WithCustomConfig)
{
	quic::quic_config config;
	config.server_name = "test.example.com";
	config.insecure_skip_verify = true;

	auto conn = quic::create_connection(config, "quic-client-1");

	ASSERT_NE(conn, nullptr);
	EXPECT_EQ(conn->id(), "quic-client-1");
}

TEST_F(QuicCreateConnectionTest, AutoGeneratedIdsAreUnique)
{
	auto conn1 = quic::create_connection();
	auto conn2 = quic::create_connection();

	ASSERT_NE(conn1, nullptr);
	ASSERT_NE(conn2, nullptr);
	EXPECT_NE(conn1->id(), conn2->id());
}

TEST_F(QuicCreateConnectionTest, InitiallyNotConnected)
{
	auto conn = quic::create_connection({}, "test");

	EXPECT_FALSE(conn->is_connected());
}

// ============================================================================
// create_listener Tests
// ============================================================================

class QuicCreateListenerTest : public ::testing::Test
{
};

TEST_F(QuicCreateListenerTest, ReturnsNonNull)
{
	quic::quic_config config;
	config.cert_file = "cert.pem";
	config.key_file = "key.pem";

	auto listener = quic::create_listener(config);

	ASSERT_NE(listener, nullptr);
}

TEST_F(QuicCreateListenerTest, WithCustomId)
{
	quic::quic_config config;
	config.cert_file = "cert.pem";
	config.key_file = "key.pem";

	auto listener = quic::create_listener(config, "my-quic-server");

	ASSERT_NE(listener, nullptr);
}

TEST_F(QuicCreateListenerTest, InitiallyNotListening)
{
	quic::quic_config config;
	config.cert_file = "cert.pem";
	config.key_file = "key.pem";

	auto listener = quic::create_listener(config, "test-listener");

	EXPECT_FALSE(listener->is_listening());
}

// ============================================================================
// connect() Convenience Tests
// ============================================================================

class QuicConnectTest : public ::testing::Test
{
};

TEST_F(QuicConnectTest, ConnectWithEndpointReturnsNonNull)
{
	quic::quic_config config;
	config.server_name = "localhost";
	config.insecure_skip_verify = true;

	auto conn = quic::connect(
		unified::endpoint_info{"127.0.0.1", 0}, config, "connect-test");

	ASSERT_NE(conn, nullptr);
}

TEST_F(QuicConnectTest, ConnectWithUrlReturnsNonNull)
{
	quic::quic_config config;
	config.insecure_skip_verify = true;

	auto conn = quic::connect("quic://127.0.0.1:4433", config, "url-test");

	ASSERT_NE(conn, nullptr);
}

TEST_F(QuicConnectTest, ConnectWithInvalidUrlStillReturnsObject)
{
	quic::quic_config config;

	auto conn = quic::connect("invalid-url", config, "bad-url");

	// Should still return a connection object (will fail on connect attempt)
	ASSERT_NE(conn, nullptr);
}

// ============================================================================
// listen() Convenience Tests
// ============================================================================

class QuicListenTest : public ::testing::Test
{
};

TEST_F(QuicListenTest, ListenWithEndpointReturnsNonNull)
{
	quic::quic_config config;
	config.cert_file = "cert.pem";
	config.key_file = "key.pem";

	auto listener = quic::listen(
		unified::endpoint_info{"127.0.0.1", 0}, config, "listen-test");

	ASSERT_NE(listener, nullptr);
}

TEST_F(QuicListenTest, ListenWithPortReturnsNonNull)
{
	quic::quic_config config;
	config.cert_file = "cert.pem";
	config.key_file = "key.pem";

	auto listener = quic::listen(static_cast<uint16_t>(0), config, "port-test");

	ASSERT_NE(listener, nullptr);
}
