/*****************************************************************************
BSD 3-Clause License

Copyright (c) 2025, 🍀☀🌕🌥 🌊
All rights reserved.
*****************************************************************************/

#include "kcenon/network/detail/protocol/websocket.h"
#include <gtest/gtest.h>

#include <memory>
#include <string>

namespace ws = kcenon::network::protocol::websocket;
namespace unified = kcenon::network::unified;

/**
 * @file protocol_websocket_factory_test.cpp
 * @brief Unit tests for WebSocket protocol factory functions
 *
 * Tests validate:
 * - create_connection() returns valid i_connection
 * - create_connection() with custom id
 * - create_connection() generates unique ids
 * - create_listener() returns valid i_listener
 * - create_listener() with custom id
 * - connect() convenience overloads (URL, endpoint+path)
 * - listen() convenience overloads (endpoint+path, port+path)
 */

// ============================================================================
// create_connection Tests
// ============================================================================

class WsCreateConnectionTest : public ::testing::Test
{
};

TEST_F(WsCreateConnectionTest, ReturnsNonNull)
{
	auto conn = ws::create_connection();

	ASSERT_NE(conn, nullptr);
}

TEST_F(WsCreateConnectionTest, WithCustomId)
{
	auto conn = ws::create_connection("my-ws-client");

	ASSERT_NE(conn, nullptr);
	EXPECT_EQ(conn->id(), "my-ws-client");
}

TEST_F(WsCreateConnectionTest, AutoGeneratedIdsAreUnique)
{
	auto conn1 = ws::create_connection();
	auto conn2 = ws::create_connection();

	ASSERT_NE(conn1, nullptr);
	ASSERT_NE(conn2, nullptr);
	EXPECT_NE(conn1->id(), conn2->id());
}

TEST_F(WsCreateConnectionTest, InitiallyNotConnected)
{
	auto conn = ws::create_connection("test");

	EXPECT_FALSE(conn->is_connected());
}

// ============================================================================
// create_listener Tests
// ============================================================================

class WsCreateListenerTest : public ::testing::Test
{
};

TEST_F(WsCreateListenerTest, ReturnsNonNull)
{
	auto listener = ws::create_listener();

	ASSERT_NE(listener, nullptr);
}

TEST_F(WsCreateListenerTest, WithCustomId)
{
	auto listener = ws::create_listener("my-ws-server");

	ASSERT_NE(listener, nullptr);
}

TEST_F(WsCreateListenerTest, InitiallyNotListening)
{
	auto listener = ws::create_listener("test-listener");

	EXPECT_FALSE(listener->is_listening());
}

TEST_F(WsCreateListenerTest, AutoGeneratedIdsAreUnique)
{
	auto l1 = ws::create_listener();
	auto l2 = ws::create_listener();

	ASSERT_NE(l1, nullptr);
	ASSERT_NE(l2, nullptr);
}

// ============================================================================
// connect() Convenience Tests
// ============================================================================

class WsConnectTest : public ::testing::Test
{
};

TEST_F(WsConnectTest, ConnectWithUrlReturnsNonNull)
{
	auto conn = ws::connect("ws://127.0.0.1:0/ws", "url-test");

	ASSERT_NE(conn, nullptr);
}

TEST_F(WsConnectTest, ConnectWithEndpointAndPath)
{
	auto conn = ws::connect(unified::endpoint_info{"127.0.0.1", 0}, "/chat", "ep-test");

	ASSERT_NE(conn, nullptr);
}

// ============================================================================
// listen() Convenience Tests
// ============================================================================

class WsListenTest : public ::testing::Test
{
};

TEST_F(WsListenTest, ListenWithEndpointReturnsNonNull)
{
	auto listener = ws::listen(
		unified::endpoint_info{"127.0.0.1", 0}, "/ws", "listen-test");

	ASSERT_NE(listener, nullptr);
}

TEST_F(WsListenTest, ListenWithPortReturnsNonNull)
{
	auto listener = ws::listen(static_cast<uint16_t>(0), "/ws", "port-test");

	ASSERT_NE(listener, nullptr);
}
