/*****************************************************************************
BSD 3-Clause License

Copyright (c) 2025, 🍀☀🌕🌥 🌊
All rights reserved.
*****************************************************************************/

#include "kcenon/network/detail/protocol/udp.h"
#include <gtest/gtest.h>

#include <memory>
#include <string>

namespace udp = kcenon::network::protocol::udp;
namespace unified = kcenon::network::unified;

/**
 * @file protocol_udp_factory_test.cpp
 * @brief Unit tests for UDP protocol factory functions
 *
 * Tests validate:
 * - create_connection() returns valid i_connection
 * - create_connection() with custom id
 * - create_connection() generates unique ids
 * - create_listener() returns valid i_listener
 * - create_listener() with custom id
 * - connect() convenience overloads
 * - listen() convenience overloads
 */

// ============================================================================
// create_connection Tests
// ============================================================================

class UdpCreateConnectionTest : public ::testing::Test
{
};

TEST_F(UdpCreateConnectionTest, ReturnsNonNull)
{
	auto conn = udp::create_connection();

	ASSERT_NE(conn, nullptr);
}

TEST_F(UdpCreateConnectionTest, WithCustomId)
{
	auto conn = udp::create_connection("my-udp-client");

	ASSERT_NE(conn, nullptr);
	EXPECT_EQ(conn->id(), "my-udp-client");
}

TEST_F(UdpCreateConnectionTest, AutoGeneratedIdsAreUnique)
{
	auto conn1 = udp::create_connection();
	auto conn2 = udp::create_connection();

	ASSERT_NE(conn1, nullptr);
	ASSERT_NE(conn2, nullptr);
	EXPECT_NE(conn1->id(), conn2->id());
}

TEST_F(UdpCreateConnectionTest, InitiallyNotConnected)
{
	auto conn = udp::create_connection("test");

	EXPECT_FALSE(conn->is_connected());
}

// ============================================================================
// create_listener Tests
// ============================================================================

class UdpCreateListenerTest : public ::testing::Test
{
};

TEST_F(UdpCreateListenerTest, ReturnsNonNull)
{
	auto listener = udp::create_listener();

	ASSERT_NE(listener, nullptr);
}

TEST_F(UdpCreateListenerTest, WithCustomId)
{
	auto listener = udp::create_listener("my-udp-server");

	ASSERT_NE(listener, nullptr);
}

TEST_F(UdpCreateListenerTest, InitiallyNotListening)
{
	auto listener = udp::create_listener("test-listener");

	EXPECT_FALSE(listener->is_listening());
}

TEST_F(UdpCreateListenerTest, AutoGeneratedIdsAreUnique)
{
	auto l1 = udp::create_listener();
	auto l2 = udp::create_listener();

	ASSERT_NE(l1, nullptr);
	ASSERT_NE(l2, nullptr);
}

// ============================================================================
// connect() Convenience Tests
// ============================================================================

class UdpConnectTest : public ::testing::Test
{
};

TEST_F(UdpConnectTest, ConnectWithEndpointReturnsNonNull)
{
	auto conn = udp::connect(unified::endpoint_info{"127.0.0.1", 0}, "connect-test");

	ASSERT_NE(conn, nullptr);
}

TEST_F(UdpConnectTest, ConnectWithUrlReturnsNonNull)
{
	auto conn = udp::connect("127.0.0.1:0", "url-test");

	ASSERT_NE(conn, nullptr);
}

// ============================================================================
// listen() Convenience Tests
// ============================================================================

class UdpListenTest : public ::testing::Test
{
};

TEST_F(UdpListenTest, ListenWithEndpointReturnsNonNull)
{
	auto listener = udp::listen(unified::endpoint_info{"127.0.0.1", 0}, "listen-test");

	ASSERT_NE(listener, nullptr);
}

TEST_F(UdpListenTest, ListenWithPortReturnsNonNull)
{
	auto listener = udp::listen(static_cast<uint16_t>(0), "port-test");

	ASSERT_NE(listener, nullptr);
}
