/*****************************************************************************
BSD 3-Clause License

Copyright (c) 2025, 🍀☀🌕🌥 🌊
All rights reserved.
*****************************************************************************/

#include "kcenon/network/detail/protocol/tcp.h"
#include <gtest/gtest.h>

#include <memory>
#include <string>

namespace tcp = kcenon::network::protocol::tcp;
namespace unified = kcenon::network::unified;

/**
 * @file protocol_tcp_factory_test.cpp
 * @brief Unit tests for TCP protocol factory functions
 *
 * Tests validate:
 * - create_connection() returns valid i_connection
 * - create_connection() with custom id
 * - create_connection() generates unique ids
 * - create_listener() returns valid i_listener
 * - create_listener() with custom id
 * - connect() convenience overloads (endpoint_info and URL)
 * - listen() convenience overloads (endpoint_info, port)
 */

// ============================================================================
// create_connection Tests
// ============================================================================

class TcpCreateConnectionTest : public ::testing::Test
{
};

TEST_F(TcpCreateConnectionTest, ReturnsNonNull)
{
	auto conn = tcp::create_connection();

	ASSERT_NE(conn, nullptr);
}

TEST_F(TcpCreateConnectionTest, WithCustomId)
{
	auto conn = tcp::create_connection("my-tcp-client");

	ASSERT_NE(conn, nullptr);
	EXPECT_EQ(conn->id(), "my-tcp-client");
}

TEST_F(TcpCreateConnectionTest, AutoGeneratedIdsAreUnique)
{
	auto conn1 = tcp::create_connection();
	auto conn2 = tcp::create_connection();

	ASSERT_NE(conn1, nullptr);
	ASSERT_NE(conn2, nullptr);
	EXPECT_NE(conn1->id(), conn2->id());
}

TEST_F(TcpCreateConnectionTest, InitiallyNotConnected)
{
	auto conn = tcp::create_connection("test");

	EXPECT_FALSE(conn->is_connected());
}

// ============================================================================
// create_listener Tests
// ============================================================================

class TcpCreateListenerTest : public ::testing::Test
{
};

TEST_F(TcpCreateListenerTest, ReturnsNonNull)
{
	auto listener = tcp::create_listener();

	ASSERT_NE(listener, nullptr);
}

TEST_F(TcpCreateListenerTest, WithCustomId)
{
	auto listener = tcp::create_listener("my-tcp-server");

	ASSERT_NE(listener, nullptr);
}

TEST_F(TcpCreateListenerTest, InitiallyNotListening)
{
	auto listener = tcp::create_listener("test-listener");

	EXPECT_FALSE(listener->is_listening());
}

TEST_F(TcpCreateListenerTest, AutoGeneratedIdsAreUnique)
{
	auto l1 = tcp::create_listener();
	auto l2 = tcp::create_listener();

	ASSERT_NE(l1, nullptr);
	ASSERT_NE(l2, nullptr);
}

// ============================================================================
// connect() Convenience Tests
// ============================================================================

class TcpConnectTest : public ::testing::Test
{
};

TEST_F(TcpConnectTest, ConnectWithEndpointReturnsNonNull)
{
	// Connection will fail but the object should still be valid
	auto conn = tcp::connect(unified::endpoint_info{"127.0.0.1", 0}, "connect-test");

	ASSERT_NE(conn, nullptr);
}

TEST_F(TcpConnectTest, ConnectWithUrlReturnsNonNull)
{
	auto conn = tcp::connect("127.0.0.1:0", "url-test");

	ASSERT_NE(conn, nullptr);
}

// ============================================================================
// listen() Convenience Tests
// ============================================================================

class TcpListenTest : public ::testing::Test
{
};

TEST_F(TcpListenTest, ListenWithEndpointReturnsNonNull)
{
	auto listener = tcp::listen(unified::endpoint_info{"127.0.0.1", 0}, "listen-test");

	ASSERT_NE(listener, nullptr);
}

TEST_F(TcpListenTest, ListenWithPortReturnsNonNull)
{
	auto listener = tcp::listen(static_cast<uint16_t>(0), "port-test");

	ASSERT_NE(listener, nullptr);
}
